{
  "hash": "fba4bec38d2827f06673d43a7e4932bd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Measurement invariance: comparing groups with multigroup CFA\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Factor analysis  \n**Tranche:** core (a first course)  \n**Before this:** [Factor analysis II: confirmatory models, omega, and IRT as factor analysis](fa-confirmatory.qmd)  \n**Builds toward:** [Structural equation modeling with lavaan](sem.qmd)  \n**Starts threads:** Comparing group means needs scalar invariance (→ [Structural equation modeling with lavaan](sem.qmd))  \n**Picks up threads:** Choose the estimator from the data: categories, shape, missingness (from [Factor analysis II: confirmatory models, omega, and IRT as factor analysis](fa-confirmatory.qmd))  \n**IRW tables:** [`neurodegenerative_huizinga_2019_dass`](https://itemresponsewarehouse.org/tables/neurodegenerative_huizinga_2019_dass/), [`alexandrowicz_2018_cesd`](https://itemresponsewarehouse.org/tables/alexandrowicz_2018_cesd/)  \n**From EDUC 252:** n/a  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\nsuppressWarnings(webr::install(\"lavaan\", quiet = TRUE))\noptions(mc.cores = 1)\n# webR can't count CPU cores (detectCores() is NA), and lavaan's option checks then\n# never finish; report one core. Not needed in local R.\nlocal({\n  ns <- asNamespace(\"parallel\")\n  unlockBinding(\"detectCores\", ns)\n  assign(\"detectCores\", function(...) 1L, envir = ns)\n  lockBinding(\"detectCores\", ns)\n})\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {grid, palette} from \"./widgets/irt.js\"\nimport {scalarStep} from \"./widgets/measurement-invariance.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nIn a Dutch community sample, women report a little more anxiety than men on the DASS-21 (0.16 SD, as we'll see). Is that a difference in anxiety, or a difference in how the items work for women and men? The scores alone can't say. [Factor analysis II](fa-confirmatory.qmd) fitted a factor model to one sample. This lesson fits it to two groups at once and asks, one constraint at a time, whether the same model holds in both: **measurement invariance**. Where it holds, the groups' factor means can be compared. Where an item breaks it, we find the item and decide what to do about it. We start with a scale where invariance holds, the DASS-21 across women and men, and then turn to one where a single item doesn't: crying on the CES-D.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- fit a multigroup CFA in `lavaan` and say how the two groups are put on one scale;\n- climb the ladder (configural, metric, scalar) with scaled difference tests and changes in CFI, and say which comparison each step supports;\n- find the constraint that fails with score tests, and fit and report a partial invariance model;\n- say what one unequal intercept does to a comparison of sum scores and of factor means;\n- choose an estimator for a multigroup fit, and say what ordered categories change.\n\n## Core ideas\n\n### One model, two groups\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Factor analysis II](fa-confirmatory.qmd): a confirmatory model fixes most loadings at zero before seeing the data, and it is identified once each factor's scale is set, by fixing one loading or the factor's variance. Nested models are compared by a (scaled) difference in χ².\n:::\n\nA **multigroup** CFA fits the model in several groups at once, with any parameter free in each group or held equal across them ([Jöreskog, 1971](https://doi.org/10.1007/BF02291366)). With intercepts, the model for item $i$ in group $g$ is $x_i = \\nu_{ig} + \\lambda_{ig}\\eta + \\varepsilon_i$. **Measurement invariance** means that responses depend on the factor and not on the group ([Meredith, 1993](https://doi.org/10.1007/BF02294825)). It is tested in steps, each adding constraints to the one before ([Vandenberg & Lance, 2000](https://doi.org/10.1177/109442810031002); [Millsap, 2011](https://doi.org/10.4324/9780203821961); [Putnick & Bornstein, 2016](https://doi.org/10.1016/j.dr.2016.06.004)):\n\n- **configural**: the same items load on the same factors in every group, every parameter free;\n- **metric**: the loadings $\\lambda_i$ are equal, so a unit of the factor means the same in each group;\n- **scalar**: the intercepts $\\nu_i$ (for ordered items, the thresholds) are equal too, so respondents at the same factor level have the same expected response.\n\nMeredith adds a fourth step, **strict** invariance, with equal unique variances as well.\n\nWhy these comparisons at these steps? A factor has no unit and no origin of its own. In the configural model each group's factor is scaled separately, so nothing links them. Once the loadings are equal, the items carry one unit across groups, and group B's factor variance, and its correlations and regressions, can be estimated relative to group A's. Once the intercepts are equal too, the items carry one origin, and group B's factor mean can be estimated relative to A's; `lavaan` frees it at that step. Comparing correlations or regressions needs metric invariance; comparing means needs scalar.\n\nIn item response language, an unequal loading is non-uniform differential item functioning and an unequal intercept is uniform DIF; [Differential item functioning](dif.qmd) takes up the same question item by item, matching on an observed score instead of a factor.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A study compares women and men on the correlation between depression and anxiety factors, and on the mean of the anxiety factor. Which level of invariance does each comparison need?\",\n  options: [\n    {text: \"Metric for the correlation, scalar for the mean\", correct: true, why: \"Equal loadings give the factors one unit in both groups, which is what variances, covariances and correlations need. A mean also needs one origin, which the equal intercepts supply.\"},\n    {text: \"Scalar for both\", correct: false, why: \"Scalar invariance would do, but the correlation doesn't need the intercepts: it involves no means. Metric is enough.\"},\n    {text: \"Configural for the correlation, metric for the mean\", correct: false, why: \"In the configural model each group's factors are scaled separately, so nothing ties group B's unit to group A's; and a mean needs a common origin, which only equal intercepts give.\"}\n  ]\n})\n```\n\n### What an unequal intercept does\n\n#### Try it: one item that works differently\n\nFour items measure one factor in groups A and B (loadings 0.7, intercepts 0, factor SD 1). Item 4 can behave differently in group B.\n\n```{ojs}\n//| echo: false\nviewof inv_k = Inputs.range([-1, 1], {value: 0.5, step: 0.05, label: \"True factor mean, B minus A (SDs)\"})\nviewof inv_nu = Inputs.range([-0.5, 0.5], {value: 0, step: 0.05, label: \"Item 4's intercept, B minus A\"})\nviewof inv_l = Inputs.range([-0.4, 0.4], {value: 0, step: 0.05, label: \"Item 4's loading, B minus A\"})\n```\n\n```{ojs}\n//| echo: false\ninv = {\n  const sdA = Math.sqrt((4 * 0.7) ** 2 + 4 * (1 - 0.49));\n  return {gap: (inv_nu + (3 * 0.7 + 0.7 + inv_l) * inv_k) / sdA, fair: (4 * 0.7 * inv_k) / sdA,\n          level: Math.abs(inv_l) > 1e-9 ? \"metric invariance fails (non-uniform DIF), and so does scalar\" :\n                 Math.abs(inv_nu) > 1e-9 ? \"metric invariance holds, but scalar fails (uniform DIF)\" : \"scalar invariance holds\"};\n}\nPlot.plot({\n  width: 700, height: 290, x: {label: \"Factor η\", domain: [-3, 3]}, y: {label: \"Expected response to item 4\"},\n  color: {legend: true, domain: [\"Group A\", \"Group B\"], range: [palette.main, palette.contrast]},\n  marks: [Plot.ruleX([0], {stroke: palette.main, strokeDasharray: \"4,3\"}), Plot.ruleX([inv_k], {stroke: palette.contrast, strokeDasharray: \"4,3\"}),\n          Plot.line(grid(-3, 3, 61).flatMap(e => [{e, y: 0.7 * e, g: \"Group A\"}, {e, y: inv_nu + (0.7 + inv_l) * e, g: \"Group B\"}]),\n            {x: \"e\", y: \"y\", stroke: \"g\", strokeWidth: 2.5})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Here ${inv.level}. Sum-score gap, B minus A: **${inv.gap.toFixed(2)}** SDs of group A's sum score; if item 4 were invariant it would be **${inv.fair.toFixed(2)}**. (Dashed lines: each group's factor mean.)`\n```\n\nWith both item-4 controls at 0 the lines coincide, and the sum-score gap (0.45 SD) is the latent 0.5 SD shrunk by unreliability. Set the true gap to 0 and item 4's intercept to 0.3: the sum scores differ by 0.10 SD between groups that don't differ at all. A loading difference makes the lines cross, so the item favours one group at low factor levels and the other at high ones.\n\nWhat does the factor model make of the same item? If we impose scalar invariance anyway, the model has to explain item 4's higher mean in group B with the one thing it has left free, group B's factor mean. The shift is spread over every item, and the factor mean absorbs part of it. The remedy is **partial invariance** ([Byrne, Shavelson & Muthén, 1989](https://doi.org/10.1037/0033-2909.105.3.456)): free the offending item's intercept and keep the others equal, so that the comparison of means rests on the items that do work alike.\n\n#### Try it: what the scalar constraint does to the factor mean\n\nNow $k$ items load 0.7 in both groups, and the last item's intercept is higher in group B by the amount you set. The widget computes the large-sample answer: group B's estimated factor mean under full and under partial scalar invariance, and how often the test of the scalar step (on $k - 1$ degrees of freedom) would catch the shifted item.\n\n```{ojs}\n//| echo: false\nviewof ss_k = Inputs.range([4, 12], {value: 4, step: 1, label: \"Number of items k\"})\nviewof ss_d = Inputs.range([-0.5, 0.5], {value: 0.3, step: 0.05, label: \"Last item's intercept, B minus A\"})\nviewof ss_kap = Inputs.range([-1, 1], {value: 0, step: 0.05, label: \"True factor mean, B minus A (SDs)\"})\nviewof ss_n = Inputs.range([50, 2000], {value: 300, step: 50, label: \"Respondents per group\"})\n```\n\n```{ojs}\n//| echo: false\nss = scalarStep({k: ss_k, kappa: ss_kap, delta: ss_d, n: ss_n})\nss_bars = [{m: \"Truth\", v: ss_kap}, {m: \"Full scalar invariance\", v: ss.kappaHat}, {m: \"Partial (last item free)\", v: ss.kappaPartial}]\nPlot.plot({\n  width: 700, height: 150, marginLeft: 180, x: {domain: [-1.4, 1.4], label: \"Group B's factor mean, minus group A's (SDs)\"}, y: {label: null, domain: ss_bars.map(d => d.m)},\n  marks: [Plot.ruleX([0], {stroke: palette.rule}),\n          Plot.dot(ss_bars, {x: \"v\", y: \"m\", r: 7, fill: d => d.m === \"Full scalar invariance\" ? palette.contrast : palette.main}),\n          Plot.text(ss_bars, {x: \"v\", y: \"m\", text: d => d.v.toFixed(3), dy: -14})]\n})\n```\n\n```{ojs}\n//| echo: false\nss_pow = grid(50, 2000, 79).map(n => ({n, p: ss.powerAt(n)}))\nPlot.plot({\n  width: 700, height: 240, x: {label: \"Respondents per group\"}, y: {label: \"Chance the scalar step fails (5% level)\", domain: [0, 1]},\n  marks: [Plot.ruleY([0.05], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n          Plot.line(ss_pow, {x: \"n\", y: \"p\", stroke: palette.main, strokeWidth: 2.5}),\n          Plot.dot([{n: ss_n, p: ss.power}], {x: \"n\", y: \"p\", r: 6, fill: palette.contrast})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Full scalar model: group B's mean is off by **${(ss.kappaHat - ss_kap).toFixed(3)}** SD. Expected χ² difference at the scalar step **${(ss.ncp + ss.df).toFixed(1)}** on ${ss.df} df (5% critical value ${ss.crit.toFixed(1)}); chance it fails: **${ss.power.toFixed(2)}**. (Dashed line: 5%, the chance with no shifted item.)`\n```\n\nAt the start, the groups don't differ, yet the scalar model puts group B 0.107 SD above A. With equal loadings the error is the shift divided by $k\\lambda$ (problem 1), here $0.3/(4 \\times 0.7)$. The partial model recovers the truth. With 300 respondents per group, the scalar step fails 97% of the time; halve the shift and the error halves while the chance of catching it falls to 44%. Raise $k$ to 12 and the error falls to 0.036: more invariant items dilute one shifted one. Move the true mean: the error stays the same size, whatever the groups' real difference.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Eight items load 0.7 in both groups. One item's intercept is 0.4 higher in group B, and a scalar model puts group B's factor mean 0.2 SD above group A's. Roughly what would a partial model, with that intercept free, give?\",\n  options: [\n    {text: \"About 0.13\", correct: true, why: \"The error is the shift over $k\\\\lambda$: $0.4/(8 \\\\times 0.7) \\\\approx 0.07$. Take it off: $0.2 - 0.07 \\\\approx 0.13$.\"},\n    {text: \"About −0.2\", correct: false, why: \"Freeing one intercept removes that item's shift from the comparison; it doesn't reverse the difference. The item accounts for only about 0.07 of it.\"},\n    {text: \"About 0.2: one item out of eight can't matter\", correct: false, why: \"It can, a little: the scalar model spreads the item's 0.4 over the factor mean, about $0.4/(8 \\\\times 0.7) \\\\approx 0.07$ SD.\"}\n  ]\n})\n```\n\n### Testing the steps\n\nEach step is nested in the one before, so a χ² difference tests it, scaled when the estimator is robust ([Satorra & Bentler, 2001](https://doi.org/10.1007/BF02296192)). As with any χ² test, a large enough sample rejects a step for differences too small to matter. So changes in fit indices are read alongside: [Cheung and Rensvold (2002)](https://doi.org/10.1207/s15328007sem0902_5) proposed treating a drop in CFI of more than 0.01 as a failed step, and [Chen (2007)](https://doi.org/10.1080/10705510701301834) paired it with changes in RMSEA and SRMR; [Putnick and Bornstein (2016)](https://doi.org/10.1016/j.dr.2016.06.004) survey how these criteria are used and questioned.\n\nWhen a step fails, which constraint is responsible? A **score test** (`lavTestScore()` in `lavaan`) says, for each equality constraint, how much the χ² would fall if that constraint alone were released. The largest is the first suspect. But a scalar model with many items holds dozens of constraints, and a few small $p$-values turn up by chance.\n\n#### Try it: how many flags by chance?\n\n```{ojs}\n//| echo: false\nviewof fl_m = Inputs.range([1, 60], {value: 39, step: 1, label: \"Equality constraints tested\"})\nviewof fl_a = Inputs.select([0.05, 0.01, 0.001], {value: 0.01, label: \"Level α for each test\"})\n```\n\n```{ojs}\n//| echo: false\nfl = Array.from({length: 60}, (_, i) => ({m: i + 1, p: 1 - (1 - fl_a) ** (i + 1)}))\nPlot.plot({\n  width: 700, height: 240, x: {label: \"Constraints tested\"}, y: {label: \"Chance at least one p < α\", domain: [0, 1]},\n  marks: [Plot.line(fl, {x: \"m\", y: \"p\", stroke: palette.main, strokeWidth: 2.5}),\n          Plot.dot([fl[fl_m - 1]], {x: \"m\", y: \"p\", r: 6, fill: palette.contrast})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`If every one of ${fl_m} constraints were true and the tests were independent, at least one would fall below ${fl_a} with probability **${fl[fl_m - 1].p.toFixed(2)}**. A Bonferroni threshold would be ${fl_a} / ${fl_m} = **${(fl_a / fl_m).toPrecision(2)}**.`\n```\n\nAt 39 constraints and α = 0.01, a flag turns up by chance about a third of the time (0.32); at α = 0.05, 86% of the time. Score tests on one model aren't independent, so these are rough guides, but they set the baseline for reading the largest test.\n\n### Choosing an estimator for multigroup fits\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Factor analysis II](fa-confirmatory.qmd): choose the estimator from the data. ML for continuous, roughly normal items; MLR for skewed items or five or more categories used fairly evenly; WLSMV, on thresholds and polychorics, for fewer than five categories or responses piled at one end; FIML, or the graded model, when responses are missing.\n:::\n\nIn a multigroup fit the guide applies group by group, and three things change. With ordered items each group gets its own thresholds, so every category of every item needs responses in each group; a category that is nearly empty in one group is a problem even when it isn't in the pooled data ([Rutkowski, Svetina & Liaw, 2019](https://doi.org/10.1080/10705511.2018.1547640), who also show that collapsing categories changes fit). Which parameters must be fixed at each step to keep ordinal models identified and nested is subtler than with continuous items ([Wu & Estabrook, 2016](https://doi.org/10.1007/s11336-016-9506-0)). And the difference tests behave differently across estimators: in simulations by [Sass, Schmitt and Marsh (2014)](https://doi.org/10.1080/10705511.2014.882658), their Type I error rates varied across ML, MLR and WLSMV, and changes in fit indices under WLSMV needed caution in misspecified models. With missing ordinal responses, WLSMV with pairwise deletion was the one method in the simulations of [Chen, Wu, Garnier-Villarreal, Kite and Jia (2020)](https://doi.org/10.1080/00273171.2019.1608799) whose difference tests did not reasonably control their Type I error rate; the full-information ordinal models recovered loadings best.\n\nSo a reasonable plan with sparse categories is MLR for the ladder, items as numbers, with an ordinal fit as the check, on collapsed categories if need be.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A four-category item has 40 responses in its top category among men and none among women. You want to test scalar invariance with WLSMV. What happens?\",\n  options: [\n    {text: \"Nothing changes: WLSMV handles skewed items\", correct: false, why: \"Skew is fine; an empty category isn't. With ordered items each group gets thresholds, and no top-category threshold can be estimated for women, so the two groups' thresholds can't even be set equal as they stand.\"},\n    {text: \"The top threshold can't be estimated for women, so you collapse the top two categories (in both groups), or treat the items as numbers\", correct: true, why: \"Collapsing keeps the ordinal model but changes the item, and it can change fit (Rutkowski et al., 2019); MLR sidesteps thresholds altogether. Either way, say which you did.\"},\n    {text: \"Use MLR with FIML, because the missing category is missing data\", correct: false, why: \"No response is missing: every woman answered the item. An empty category is a fact about the responses, not a missing value.\"}\n  ]\n})\n```\n\n## Simulate\n\nThe code simulates 500 respondents in each of two groups answering six items that measure one factor, with group B's factor mean 0.3 SD higher and item 6's intercept 0.4 higher. It climbs the ladder with `lavaan`, runs the score tests on the scalar model, frees the item with the largest one, and compares group B's estimated factor mean with the truth. The first run installs `lavaan`, which takes a little while; after that, each run takes a few seconds.\n\nWith the seed as written, configural to metric passes ($p = 0.31$) and the scalar step fails (Δχ² = 42.3 on 5 df); item 6's intercept has by far the largest score test (40.5); and group B's mean comes out at 0.377 under full scalar invariance and 0.319 with item 6 free (truth 0.3). Set `shift <- 0` and the scalar step should pass; set `n <- 150` and see how often the test still finds item 6 across a few seeds.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-17\n# Simulate two groups answering six items that measure one factor, with one item\n# that works differently in group B. Climb the invariance ladder with lavaan, find\n# the item, and compare group B's estimated factor mean with the truth, with and\n# without partial invariance. Needs the lavaan package.\nlibrary(lavaan)\nset.seed(58)\nn     <- 500                              # respondents per group (try 150, or 3000 locally)\nlam   <- c(0.8, 0.7, 0.7, 0.6, 0.6, 0.5)  # loadings, the same in both groups\nkappa <- 0.3                              # group B's factor mean (group A: 0), in SDs\nshift <- 0.4                              # item 6's intercept in group B minus group A\n\n# Responses x = intercept + loading * factor + error, with var(x) = 1 in group A.\nsim <- function(n, mu, nu) {\n  eta <- rnorm(n, mu)\n  sapply(1:6, function(i) nu[i] + lam[i] * eta + sqrt(1 - lam[i]^2) * rnorm(n))\n}\nd <- as.data.frame(rbind(sim(n, 0, rep(0, 6)), sim(n, kappa, c(0, 0, 0, 0, 0, shift))))\nnames(d) <- paste0(\"x\", 1:6)\nd$group <- rep(c(\"A\", \"B\"), each = n)\n\n# The ladder: configural, metric (equal loadings), scalar (equal intercepts too).\nmodel <- \"F =~ x1 + x2 + x3 + x4 + x5 + x6\"\ncfg <- cfa(model, data = d, group = \"group\")\nmet <- cfa(model, data = d, group = \"group\", group.equal = \"loadings\")\nsca <- cfa(model, data = d, group = \"group\", group.equal = c(\"loadings\", \"intercepts\"))\nprint(lavTestLRT(cfg, met, sca))\n\n# Which equality constraint strains most in the scalar model?\nst <- lavTestScore(sca)$uni\npt <- parTable(sca)\nst$constraint <- sapply(st$lhs, function(l) with(pt[pt$plabel == l, ], paste(lhs, op, rhs)))\nprint(head(st[order(-st$X2), c(\"constraint\", \"X2\", \"p.value\")], 3))\n\n# Partial invariance: free item 6's intercept. Group B's factor mean, in units of\n# group A's factor SD, with and without it, against the truth.\npar <- cfa(model, data = d, group = \"group\", group.equal = c(\"loadings\", \"intercepts\"),\n           group.partial = \"x6 ~ 1\")\nmean_B <- function(fit) {\n  pe <- parameterEstimates(fit)\n  pe$est[pe$lhs == \"F\" & pe$op == \"~1\" & pe$group == 2] / sqrt(lavInspect(fit, \"est\")[[1]]$psi[1, 1])\n}\nprint(round(c(truth = kappa, full_scalar = mean_B(sca), partial = mean_B(par)), 3))\n\n```\n:::\n\n\n[Download this code](code/measurement-invariance-sim.R).\n\n## With real data\n\n\n\n### The DASS-21: women and men\n\nOur main example returns to [neurodegenerative_huizinga_2019_dass](https://itemresponsewarehouse.org/tables/neurodegenerative_huizinga_2019_dass/), the Dutch DASS-21 answered by a community sample recruited by [Huizinga et al. (2020)](https://doi.org/10.1371/journal.pone.0232232), with the three-factor model of [Factor analysis II](fa-confirmatory.qmd) ([Lovibond & Lovibond, 1995](https://doi.org/10.1016/0005-7967(94)00075-u)). Its job is to show the ladder where it holds. [Download the code](code/measurement-invariance-irw.R) to run every chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(lavaan)\n# Each IRW table has a landing page (itemresponsewarehouse.org/tables/<name>/)\n# with a CSV download. This link is pinned to one version of the data.\ndass_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v59_0.neurodegenerative_huizinga_2019_dass/rows?format=csv\"\ndf <- read.csv(dass_url)\ndf$resp <- suppressWarnings(as.numeric(df$resp))   # missing responses arrive as text\nwide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\ndass <- as.data.frame(wide[, paste0(\"DASS.\", 1:21)])\nnames(dass) <- paste0(\"d\", 1:21)\ndass$sex <- df$cov_sex[match(rownames(dass), df$id)]\ntable(sex = dass$sex)                  # all 1,461 respondents\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsex\n  1   2 \n676 785 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ndass <- dass[complete.cases(dass), ]   # 215 respondents skipped all 21 items; no one skipped some\ntable(sex = dass$sex)                  # the 1,246 who answered\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsex\n  1   2 \n577 669 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# 0 = did not apply to me at all ... 3 = applied to me very much. Every item is\n# worded toward more distress, so no keying is needed. Scales from the DASS\n# scoring template (Lovibond & Lovibond, 1995).\ndep <- paste0(\"d\", c(3, 5, 10, 13, 16, 17, 21))\nanx <- paste0(\"d\", c(2, 4, 7, 9, 15, 19, 20))\nstress <- paste0(\"d\", c(1, 6, 8, 11, 12, 14, 18))\nm3 <- paste(\"dep =~\", paste(dep, collapse = \" + \"), \"\\n\",\n            \"anx =~\", paste(anx, collapse = \" + \"), \"\\n\",\n            \"str =~\", paste(stress, collapse = \" + \"))\n```\n:::\n\n\nThe table's `cov_sex` codes are unlabelled in the processing script. The paper reports 785 women among its 1,461 participants (its Table 1), and code 2 holds exactly 785 of the table's 1,461 respondents, so we read 2 as women: a match of counts, not a codebook.\n\nWhich estimator? For the single-group structure the guide pointed to WLSMV: four categories, piled at zero. Group by group, the top category is thin.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The estimator choice, group by group: with ordered items, every category of\n# every item needs responses in each group, since each group gets thresholds.\ntop <- sapply(split(dass[1:21], dass$sex), function(g) sapply(g, function(x) sum(x == 3)))\ntable(responses_at_3 = top)            # items by how many responses sit in the top category\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nresponses_at_3\n 1  2  3  4  5  6  7  8 11 12 \n 5  6  7  7  3  8  3  1  1  1 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncolSums(top == 0 | top == 1)           # items per group with 0 or 1 responses at 3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1 2 \n4 1 \n```\n\n\n:::\n:::\n\n\nEvery item's top category holds between 1 and 12 responses in each group, and five items (four among men, one among women) hold a single one. Thresholds resting on one response per group are fragile, so we climb the ladder with MLR, items as numbers, and fit WLSMV as the check.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Multigroup CFA by cov_sex, three-factor model, items treated as numbers (MLR).\n# Configural: same pattern in both groups. Metric: loadings equal. Scalar: loadings\n# and intercepts equal; lavaan then frees group 2's factor means.\ncfg <- cfa(m3, data = dass, group = \"sex\", estimator = \"MLR\")\nmet <- cfa(m3, data = dass, group = \"sex\", estimator = \"MLR\", group.equal = \"loadings\")\nsca <- cfa(m3, data = dass, group = \"sex\", estimator = \"MLR\",\n           group.equal = c(\"loadings\", \"intercepts\"))\nidx_r <- c(\"chisq.scaled\", \"df\", \"cfi.robust\", \"rmsea.robust\", \"srmr\")\nround(rbind(configural = fitMeasures(cfg, idx_r), metric = fitMeasures(met, idx_r),\n            scalar = fitMeasures(sca, idx_r)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           chisq.scaled  df cfi.robust rmsea.robust  srmr\nconfigural      874.695 372      0.931        0.062 0.044\nmetric          881.133 390      0.932        0.060 0.048\nscalar          912.661 408      0.931        0.059 0.048\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nlavTestLRT(cfg, met, sca)   # scaled (Satorra-Bentler) differences\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    |  Df|      AIC|      BIC|    Chisq| Chisq diff|     RMSEA| Df diff| Pr(>Chisq)|\n|:---|---:|--------:|--------:|--------:|----------:|---------:|-------:|----------:|\n|cfg | 372| 29902.65| 30579.51| 1548.076|         NA|        NA|      NA|         NA|\n|met | 390| 29896.78| 30481.34| 1578.205|   13.50787| 0.0000000|      18|  0.7605629|\n|sca | 408| 29885.31| 30377.57| 1602.735|   24.58263| 0.0242018|      18|  0.1368512|\n\n</div>\n:::\n:::\n\n\nEqual loadings cost almost nothing (a scaled Δχ² of 13.5 on 18 df, $p = 0.76$), and neither do equal intercepts (24.6 on 18 df, $p = 0.14$). Robust CFI is 0.931 or 0.932 at every step, far inside the 0.01 criterion. The configural fit is modest, but the question at each step is whether the constraints make it worse, and they don't.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Which equality constraint strains most? One score test per constraint.\nscore_tests <- function(fit) {\n  st <- lavTestScore(fit)$uni\n  pt <- parTable(fit)\n  st$constraint <- sapply(st$lhs, function(l) with(pt[pt$plabel == l, ], paste(lhs, op, rhs)))\n  st[order(-st$X2.scaled), c(\"constraint\", \"X2.scaled\", \"df\", \"p.value.scaled\")]\n}\nst <- score_tests(sca)\nnrow(st)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 39\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nhead(st, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |constraint | X2.scaled| df| p.value.scaled|\n|:--|:----------|---------:|--:|--------------:|\n|23 |d16 ~1     |  6.921176|  1|      0.0085181|\n|2  |dep =~ d10 |  3.764150|  1|      0.0523625|\n|38 |d14 ~1     |  2.684030|  1|      0.1013589|\n\n</div>\n:::\n:::\n\n\nThe constraint under most strain is item 16's intercept (\"I was unable to become enthusiastic about anything\", in the wording of the [English DASS-21](https://www2.psy.unsw.edu.au/dass/Download%20files/Dass21.pdf); Lovibond & Lovibond, 1995), with a score test of 6.9 on 1 df. Its $p$-value is 0.009, and among 39 tests one that small turns up by chance about three times in ten ($1 - 0.991^{39} \\approx 0.30$, the widget's baseline).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Group 2's factor means under scalar invariance, in units of group 1's factor SD.\nlatent_means <- function(fit, factors) {\n  pe <- parameterEstimates(fit)\n  mu2 <- pe[pe$op == \"~1\" & pe$lhs %in% factors & pe$group == 2, c(\"lhs\", \"est\", \"se\")]\n  sd1 <- sqrt(diag(lavInspect(fit, \"est\")[[1]]$psi))\n  data.frame(factor = mu2$lhs, mean_diff = round(mu2$est, 3), se = round(mu2$se, 3),\n             in_group1_SDs = round(mu2$est / sd1[mu2$lhs], 2))\n}\nlatent_means(sca, c(\"dep\", \"anx\", \"str\"))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    |factor | mean_diff|    se| in_group1_SDs|\n|:---|:------|---------:|-----:|-------------:|\n|dep |dep    |     0.036| 0.024|          0.09|\n|anx |anx    |     0.039| 0.016|          0.16|\n|str |str    |     0.056| 0.020|          0.18|\n\n</div>\n:::\n:::\n\n\nWith scalar invariance the factor means can be compared: women sit 0.16 SD above men on anxiety, 0.18 SD on stress, and 0.09 SD on depression.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same ladder with the items as ordered categories (WLSMV): the thresholds play\n# the intercepts' part. (lavaan may warn about the parameters' covariance matrix:\n# some top categories hold one response in a group.)\ncfg_o <- cfa(m3, data = dass, group = \"sex\", ordered = TRUE)\nmet_o <- cfa(m3, data = dass, group = \"sex\", ordered = TRUE, group.equal = \"loadings\")\nsca_o <- cfa(m3, data = dass, group = \"sex\", ordered = TRUE,\n             group.equal = c(\"loadings\", \"thresholds\", \"intercepts\"))\nidx_o <- c(\"df\", \"cfi.scaled\", \"rmsea.scaled\", \"srmr\")\nround(rbind(configural = fitMeasures(cfg_o, idx_o), metric = fitMeasures(met_o, idx_o),\n            scalar = fitMeasures(sca_o, idx_o)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            df cfi.scaled rmsea.scaled  srmr\nconfigural 372      0.978        0.050 0.051\nmetric     390      0.987        0.037 0.053\nscalar     429      0.983        0.040 0.051\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Are these three models nested? Count what each one frees beyond the loadings and\n# thresholds: the default scalar model frees 21 scale factors and 3 factor means\n# that the default metric model fixes, so it is not the metric model plus constraints.\nsapply(list(configural = cfg_o, metric = met_o, scalar = sca_o), function(f) {\n  pt <- parTable(f)\n  c(free_scale_factors = sum(pt$op == \"~*~\" & pt$free > 0),\n    free_factor_means = sum(pt$op == \"~1\" & pt$lhs %in% c(\"dep\", \"anx\", \"str\") & pt$free > 0))\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   configural metric scalar\nfree_scale_factors          0      0     21\nfree_factor_means           0      0      3\n```\n\n\n:::\n:::\n\n\nAs ordered categories, every step fits well (CFI 0.978 to 0.987, RMSEA at most 0.050). We read only the indices. `lavaan`'s default ordinal scalar model frees 21 scale factors and 3 factor means that its metric model fixes, so the two aren't nested and their difference isn't a test of the thresholds alone (problem 5). The DASS-21 passes.\n\n### The CES-D: where one item breaks\n\nOur failure case is [alexandrowicz_2018_cesd](https://itemresponsewarehouse.org/tables/alexandrowicz_2018_cesd/): the 20-item CES-D ([Radloff, 1977](https://doi.org/10.1177/014662167700100306)), answered 0 to 3 by a sample of Austrian adults ([Alexandrowicz, Jahn & Wancata, 2018](https://doi.org/10.1371/journal.pone.0197908)). Its job is to show the ladder failing and what to do next.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\ncesd_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_4:v8_0.alexandrowicz_2018_cesd/rows?format=csv\"\ndf <- read.csv(cesd_url)\nwide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\nitems <- c(sprintf(\"ces_%02d\", c(1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15, 17, 18, 19, 20)),\n           sprintf(\"cesr%02d\", c(4, 8, 12, 16)))\ncesd <- as.data.frame(wide[, items])\ncesd$sex <- df$cov_sex[match(rownames(cesd), df$id)]\ntable(sex = cesd$sex)                  # all 514 respondents\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsex\n  1   2 \n251 263 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(items_skipped = rowSums(is.na(cesd[items])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nitems_skipped\n  0   1   2 \n508   5   1 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncesd <- cesd[complete.cases(cesd), ]\ntable(sex = cesd$sex)                  # complete cases\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsex\n  1   2 \n246 262 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# 0 = rarely or none of the time ... 3 = most or all of the time. The four positively\n# worded items (cesr04, cesr08, cesr12, cesr16) arrive reversed, so higher = more\n# depressive symptoms on every item: they correlate positively with the rest.\nround(range(cor(cesd[items])[lower.tri(diag(20))]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.02  0.62\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntop <- sapply(split(cesd[items], cesd$sex), function(g) sapply(g, function(x) sum(x == 3)))\ncolSums(top <= 1)   # items per group with 0 or 1 responses in the top category\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1 2 \n7 5 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Two factors: the 16 symptom items, and Radloff's positive-affect items.\npos <- sprintf(\"cesr%02d\", c(4, 8, 12, 16))\nm2 <- paste(\"dep =~\", paste(setdiff(items, pos), collapse = \" + \"), \"\\n\",\n            \"pa =~\", paste(pos, collapse = \" + \"))\n```\n:::\n\n\nThe paper reports 264 women among 518 respondents; the table has 263 respondents coded 2 of 514, so 2 is probably women, though nothing documents it. The four positively worded items arrive reversed: no inter-item correlation is below −0.02. Six respondents skipped an item or two, so listwise deletion costs about 1%. The model has two factors: the 16 symptom items, and the four items of Radloff's positive-affect subscale, as Alexandrowicz et al. list them (their Table 1). The estimator: the top categories are sparser than the DASS's (seven items among men and five among women have at most one response at 3), so MLR again, with an ordinal check.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\ncfg_c <- cfa(m2, data = cesd, group = \"sex\", estimator = \"MLR\")\nmet_c <- cfa(m2, data = cesd, group = \"sex\", estimator = \"MLR\", group.equal = \"loadings\")\nsca_c <- cfa(m2, data = cesd, group = \"sex\", estimator = \"MLR\",\n             group.equal = c(\"loadings\", \"intercepts\"))\nround(rbind(configural = fitMeasures(cfg_c, idx_r), metric = fitMeasures(met_c, idx_r),\n            scalar = fitMeasures(sca_c, idx_r)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           chisq.scaled  df cfi.robust rmsea.robust  srmr\nconfigural      556.332 338      0.902        0.056 0.059\nmetric          625.794 356      0.873        0.062 0.090\nscalar          663.147 374      0.865        0.063 0.092\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nlavTestLRT(cfg_c, met_c, sca_c)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |  Df|      AIC|      BIC|    Chisq| Chisq diff|     RMSEA| Df diff| Pr(>Chisq)|\n|:-----|---:|--------:|--------:|--------:|----------:|---------:|-------:|----------:|\n|cfg_c | 338| 15768.11| 16284.23| 695.6322|         NA|        NA|      NA|         NA|\n|met_c | 356| 15855.50| 16295.47| 819.0141|   51.30654| 0.1323582|      18|  0.0000478|\n|sca_c | 374| 15858.21| 16222.04| 857.7328|   39.10169| 0.0676033|      18|  0.0027614|\n\n</div>\n:::\n:::\n\n\nThe configural model fits modestly by the conventional cutoffs (robust CFI 0.902, below 0.95; RMSEA 0.056, under 0.06). Equal loadings don't: a scaled Δχ² of 51.3 on 18 df ($p < .001$), and CFI drops by 0.029, three times the 0.01 criterion. The scalar step fails as well (39.1 on 18 df).\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"The metric step fails. Which item's loading will the score tests single out?\",\n  choices: [\"Crying spells (item 17)\", \"Feeling happy (item 12)\", \"Restless sleep (item 11)\", \"Talking less than usual (item 13)\"],\n  answer: \"Crying spells (item 17)\",\n  reveal: \"Crying, by a wide margin: its score test is 11.7, twice the next (item 5, 5.8). At the same level of depressive symptoms, crying is tied to the factor differently in the two groups.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nst_met <- score_tests(met_c)   # at the metric step: which loading?\nnrow(st_met)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nhead(st_met, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |constraint    | X2.scaled| df| p.value.scaled|\n|:--|:-------------|---------:|--:|--------------:|\n|12 |dep =~ ces_17 | 11.719253|  1|      0.0006186|\n|3  |dep =~ ces_05 |  5.807588|  1|      0.0159572|\n|1  |dep =~ ces_02 |  3.420608|  1|      0.0643873|\n\n</div>\n:::\n:::\n\n\nThe crying item's loading has the largest score test, 11.7 on 1 df among 18, twice the next. [Alexandrowicz et al. (2018)](https://doi.org/10.1371/journal.pone.0197908) found DIF by gender on the same item with a Rasch model, which is some reassurance that it isn't an accident of this model. We free it, then look at the intercepts.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Partial invariance: free the crying item's loading (metric), then its intercept too\n# (scalar), keeping every other constraint.\nmet_p <- cfa(m2, data = cesd, group = \"sex\", estimator = \"MLR\", group.equal = \"loadings\",\n             group.partial = \"dep =~ ces_17\")\nsca_p1 <- cfa(m2, data = cesd, group = \"sex\", estimator = \"MLR\",\n              group.equal = c(\"loadings\", \"intercepts\"), group.partial = \"dep =~ ces_17\")\nhead(score_tests(sca_p1), 2)   # at the scalar step, with the loading already free\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |constraint | X2.scaled| df| p.value.scaled|\n|:--|:----------|---------:|--:|--------------:|\n|30 |ces_17 ~1  |  7.628321|  1|      0.0057459|\n|27 |ces_13 ~1  |  6.125482|  1|      0.0133247|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsca_p <- cfa(m2, data = cesd, group = \"sex\", estimator = \"MLR\",\n             group.equal = c(\"loadings\", \"intercepts\"),\n             group.partial = c(\"dep =~ ces_17\", \"ces_17 ~ 1\"))\nlavTestLRT(cfg_c, met_p)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |  Df|      AIC|      BIC|    Chisq| Chisq diff|     RMSEA| Df diff| Pr(>Chisq)|\n|:-----|---:|--------:|--------:|--------:|----------:|---------:|-------:|----------:|\n|cfg_c | 338| 15768.11| 16284.23| 695.6322|         NA|        NA|      NA|         NA|\n|met_p | 355| 15801.56| 16245.76| 763.0753|   28.05027| 0.0784414|      17|  0.0443543|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nlavTestLRT(met_p, sca_p)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |  Df|      AIC|      BIC|    Chisq| Chisq diff|     RMSEA| Df diff| Pr(>Chisq)|\n|:-----|---:|--------:|--------:|--------:|----------:|---------:|-------:|----------:|\n|met_p | 355| 15801.56| 16245.76| 763.0753|         NA|        NA|      NA|         NA|\n|sca_p | 372| 15793.15| 16165.43| 788.6632|   25.46969| 0.0443913|      17|  0.0846794|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(rbind(partial_metric = fitMeasures(met_p, idx_r), partial_scalar = fitMeasures(sca_p, idx_r)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               chisq.scaled  df cfi.robust rmsea.robust  srmr\npartial_metric       584.44 355      0.892        0.058 0.077\npartial_scalar       610.47 372      0.889        0.057 0.078\n```\n\n\n:::\n:::\n\n\nWith the crying loading free, the metric step is borderline (28.1 on 17 df, $p = 0.04$; CFI 0.892, a drop of 0.010). At the scalar step the crying intercept is again first (7.6). Freed as well, the partial scalar model holds against the partial metric one (25.5 on 17 df, $p = 0.08$).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nrbind(full_scalar = latent_means(sca_c, c(\"dep\", \"pa\")), partial = latent_means(sca_p, c(\"dep\", \"pa\")))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                |factor | mean_diff|    se| in_group1_SDs|\n|:---------------|:------|---------:|-----:|-------------:|\n|full_scalar.dep |dep    |     0.056| 0.026|          0.21|\n|full_scalar.pa  |pa     |    -0.045| 0.047|         -0.10|\n|partial.dep     |dep    |     0.051| 0.026|          0.18|\n|partial.pa      |pa     |    -0.045| 0.048|         -0.10|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The crying item's loading and intercept in each group (partial model):\npe <- parameterEstimates(sca_p)\npe[(pe$op == \"=~\" & pe$rhs == \"ces_17\") | (pe$op == \"~1\" & pe$lhs == \"ces_17\"),\n   c(\"lhs\", \"op\", \"rhs\", \"group\", \"est\", \"se\")]\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    |lhs    |op |rhs    | group|       est|        se|\n|:---|:------|:--|:------|-----:|---------:|---------:|\n|13  |dep    |=~ |ces_17 |     1| 0.3248080| 0.1572090|\n|56  |ces_17 |~1 |       |     1| 0.0853659| 0.0204093|\n|78  |dep    |=~ |ces_17 |     2| 1.2808958| 0.2350493|\n|121 |ces_17 |~1 |       |     2| 0.1829560| 0.0335570|\n\n</div>\n:::\n:::\n\n\nDoes freeing the item change the comparison? Under full scalar invariance group 2 sits 0.21 SD above group 1 on the symptom factor; with the crying item free, 0.18 SD. Positive affect is 0.10 SD lower in group 2 either way. The crying item's loading is 0.33 in group 1 and 1.28 in group 2 (in units of the first item's loading), and its intercept 0.085 and 0.183: in group 2, crying goes with the other symptoms far more closely, and at the factor's zero point it is reported more often.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# As a check with an ordinal estimator: the top categories are too sparse to keep, so\n# each item is scored as any symptom (1-3) against none (0), and the scalar model is\n# fitted with WLSMV. Which constraints strain most?\ncesd_bin <- cesd\ncesd_bin[items] <- lapply(cesd_bin[items], function(x) as.integer(x > 0))\n# With binary items, the theta parameterization fixes each latent response's\n# residual variance at 1 in both groups, which keeps the scalar model identified\n# (Wu & Estabrook, 2016); the group-2 factor means are free.\nsca_b <- cfa(m2, data = cesd_bin, group = \"sex\", ordered = TRUE, parameterization = \"theta\",\n             group.equal = c(\"loadings\", \"thresholds\", \"intercepts\"))\nst_b <- lavTestScore(sca_b)$uni\npt <- parTable(sca_b)\nst_b$constraint <- sapply(st_b$lhs, function(l) with(pt[pt$plabel == l, ], paste(lhs, op, rhs)))\nhead(st_b[order(-st_b$X2), c(\"constraint\", \"X2\", \"df\", \"p.value\")], 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |constraint    |       X2| df|   p.value|\n|:--|:-------------|--------:|--:|---------:|\n|12 |dep =~ ces_17 | 33.69917|  1| 0.0000000|\n|14 |dep =~ ces_19 | 18.22343|  1| 0.0000196|\n|3  |dep =~ ces_05 | 10.92681|  1| 0.0009478|\n\n</div>\n:::\n:::\n\n\nAs a check with an ordinal estimator, on items scored as any symptom against none, the crying loading again has the largest score test (33.7).\n\nSo what should a report say? One view drops the crying item, so that the scale is invariant as it stands. Another keeps it and frees its parameters, so that the comparison rests on the other 19 items while the item still counts toward each respondent's score. A third ignores the failure because it is one item in twenty. The first changes the instrument, and its scores no longer match published norms; the third lets one item push the comparison, by 0.03 SD here; the second needs enough invariant items to carry the comparison. My practice is to free the item, report the comparison both ways, and say which item and why. Here the two give 0.21 and 0.18 SD, and the conclusion doesn't change.\n\n## Problems\n\n1. **The size of the error.** Four items with equal loadings $\\lambda$ and unique variances $\\psi$ measure one factor in two groups, with item 4's intercept higher by $\\delta$ in group B. (a) Show that the gap between the groups' expected sum scores is $4\\lambda\\kappa + \\delta$, and express it in SDs of group A's sum score, as the first widget does. (b) With $k$ items, show that the scalar model's population estimate of group B's mean is $\\kappa + \\delta/(k\\lambda)$. (Hint: with the covariances fitted exactly, the scalar model's mean part is a generalized least-squares regression of the item mean differences on $\\lambda$.)\n2. **A different grouping.** Split the CES-D respondents at the median of `cov_age` and climb the ladder with the same two-factor model. Does the crying item stand out again? Which constraints do, and what would you do about them?\n3. **Significant but small.** A scale is compared across two groups of 10,000 respondents each. The scalar step gives a scaled Δχ² of 180 on 20 df ($p < .001$) and a drop in CFI of 0.003. Is the scale invariant enough to compare means? What would you look at before deciding, and what would you report?\n4. **Design.** You want to compare DASS-21 scores across the education levels in `cov_education`. Which level of invariance do you need to compare means, and which to compare the depression–anxiety correlation? Check the group sizes first: which estimator would you use, and what would you do if one item's intercept failed in one group?\n5. **Nested or not?** Using the code's ordinal DASS fits, list what each of the three models fixes and frees (thresholds, scale factors, factor means and variances). Why is the default metric-to-scalar difference not a test of equal thresholds? Build a nested sequence as [Wu and Estabrook (2016)](https://doi.org/10.1007/s11336-016-9506-0) propose (the `semTools` function `measEq.syntax()` writes the syntax), test it, and compare the verdict with the MLR ladder.\n6. **Challenge (open).** With thirty countries, [Asparouhov and Muthén (2014)](https://doi.org/10.1080/10705511.2014.919210) note, the scalar model tends to fit poorly and to throw up many large modification indices. They propose **alignment**, which estimates the countries' factor means without requiring exact invariance. What does alignment assume in place of invariance, and how would you decide whether the means it gives are trustworthy enough to rank the countries? I don't know of a settled answer.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Measurement%20invariance%3A%20comparing%20groups%20with%20multigroup%20CFA%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20measurement%20invariance%20with%20multigroup%20confirmatory%20factor%20analysis%20in%20lavaan%3A%20the%20configural%2C%20metric%2C%20scalar%20%28and%20strict%29%20steps%20and%20which%20comparisons%20each%20supports%2C%20how%20the%20groups%20are%20put%20on%20one%20scale%2C%20what%20a%20non-invariant%20intercept%20does%20to%20sum-score%20and%20factor-mean%20comparisons%2C%20partial%20invariance%2C%20scaled%20chi-square%20difference%20tests%2C%20changes%20in%20CFI%2C%20score%20tests%20and%20multiple%20testing%2C%20and%20choosing%20an%20estimator%20%28MLR%20or%20WLSMV%29%20for%20multigroup%20fits%20with%20sparse%20ordered%20categories%2C%20with%20the%20DASS-21%20%28invariance%20holds%20across%20women%20and%20men%29%20and%20the%20CES-D%20%28the%20crying%20item%20is%20not%20invariant%29%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Meredith, W. (1993). Measurement invariance, factor analysis and factorial invariance. *Psychometrika*, 58(4), 525–543. <https://doi.org/10.1007/BF02294825>. The definitions, from weak to strict.\n- Jöreskog, K. G. (1971). Simultaneous factor analysis in several populations. *Psychometrika*, 36(4), 409–426. <https://doi.org/10.1007/BF02291366>. The multigroup model and its tests.\n- Vandenberg, R. J., & Lance, C. E. (2000). A review and synthesis of the measurement invariance literature. *Organizational Research Methods*, 3(1), 4–70. <https://doi.org/10.1177/109442810031002>. The ladder, step by step.\n- Putnick, D. L., & Bornstein, M. H. (2016). Measurement invariance conventions and reporting: The state of the art and future directions for psychological research. *Developmental Review*, 41, 71–90. <https://doi.org/10.1016/j.dr.2016.06.004>. How invariance is tested and reported in practice, with the criteria for changes in fit.\n- Byrne, B. M., Shavelson, R. J., & Muthén, B. (1989). Testing for the equivalence of factor covariance and mean structures: The issue of partial measurement invariance. *Psychological Bulletin*, 105(3), 456–466. <https://doi.org/10.1037/0033-2909.105.3.456>. Partial invariance.\n- Cheung, G. W., & Rensvold, R. B. (2002). Evaluating goodness-of-fit indexes for testing measurement invariance. *Structural Equation Modeling*, 9(2), 233–255. <https://doi.org/10.1207/s15328007sem0902_5>. Where the change-in-CFI criterion comes from.\n- Chen, F. F. (2007). Sensitivity of goodness of fit indexes to lack of measurement invariance. *Structural Equation Modeling*, 14(3), 464–504. <https://doi.org/10.1080/10705510701301834>. Which index notices which kind of non-invariance.\n- Wu, H., & Estabrook, R. (2016). Identification of confirmatory factor analysis models of different levels of invariance for ordered categorical outcomes. *Psychometrika*, 81(4), 1014–1045. <https://doi.org/10.1007/s11336-016-9506-0>. Invariance with ordinal items, identified and nested (problem 5).\n- Svetina, D., Rutkowski, L., & Rutkowski, D. (2020). Multiple-group invariance with categorical outcomes using updated guidelines: An illustration using M*plus* and the lavaan/semTools packages. *Structural Equation Modeling*, 27(1), 111–130. <https://doi.org/10.1080/10705511.2019.1602776>. A worked tutorial for the ordinal ladder in R.\n- Sass, D. A., Schmitt, T. A., & Marsh, H. W. (2014). Evaluating model fit with ordered categorical data within a measurement invariance framework: A comparison of estimators. *Structural Equation Modeling*, 21(2), 167–180. <https://doi.org/10.1080/10705511.2014.882658>. ML, MLR and WLSMV at each step.\n- Chen, P.-Y., Wu, W., Garnier-Villarreal, M., Kite, B. A., & Jia, F. (2020). Testing measurement invariance with ordinal missing data: A comparison of estimators and missing data techniques. *Multivariate Behavioral Research*, 55(1), 87–101. <https://doi.org/10.1080/00273171.2019.1608799>. Missing ordinal responses in the ladder.\n- Nye, C. D., & Drasgow, F. (2011). Effect size indices for analyses of measurement equivalence: Understanding the practical importance of differences between groups. *Journal of Applied Psychology*, 96(5), 966–980. <https://doi.org/10.1037/a0022955>. An effect size for non-invariance, for when \"significant\" isn't the question (problem 3).\n- Millsap, R. E. (2011). *Statistical approaches to measurement invariance*. Routledge. <https://doi.org/10.4324/9780203821961>. The full treatment, factor models and IRT together.\n- The lavaan tutorial on [multiple groups](https://lavaan.ugent.be/tutorial/groups.html): `group.equal`, `group.partial` and the tests.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`neurodegenerative_huizinga_2019_dass`](https://itemresponsewarehouse.org/tables/neurodegenerative_huizinga_2019_dass/): Huizinga, F., Heutink, J., de Haan, G. A., van der Lijn, I., van der Feen, F. E., Vrijling, A. C., ... & Koerts, J. (2020). The development of the Screening of Visual Complaints questionnaire for patients with neurodegenerative disorders: Evaluation of psychometric features in a community sample. PLoS One, 15(4), e0232232. <https://doi.org/10.1371/journal.pone.0232232>. Licence: CC0 1.0.\n- [`alexandrowicz_2018_cesd`](https://itemresponsewarehouse.org/tables/alexandrowicz_2018_cesd/): Alexandrowicz, R.; Jahn, R.; Wancata, J. (2018). Assessing the dimensionality of the CES-D using multi-dimensional multi-level Rasch models. PLOS ONE, 13(5), e0197908. <https://doi.org/10.1371/journal.pone.0197908>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** new material. Split from [Factor analysis II](fa-confirmatory.qmd) on 09-25 (Ben, #58), at a colleague's suggestion that the factor-analysis lesson was too long; multigroup invariance had moved into that lesson from [Differential item functioning](dif.qmd) on 09-24. The DASS example, the CES-D failure case and the first widget come from it; the estimator section is new.\n- **Timing:** about 45 minutes for the core ideas and widgets; the real-data section is a 30-minute lab (the whole script runs in about a minute locally).\n- **Placement:** after [Factor analysis II](fa-confirmatory.qmd), and before [Fairness in testing](fairness.qmd) and [Differential item functioning](dif.qmd) in the first course, which return to invariance with item response models and observed-score matching. [Structural equation modeling with lavaan](sem.qmd) uses it for multigroup SEM.\n- **Held back:** invariance item by item ([Differential item functioning](dif.qmd)); occasions and treatments as groupings ([Measurement invariance under treatment and life events](invariance-experience.qmd)); many groups and alignment (problem 6 only); the effect-size view of non-invariance (in *Going further*).\n- **Data:** the DASS is in the public domain ([DASS FAQ, no. 3](https://www2.psy.unsw.edu.au/dass/DASSFAQ.htm)), so one item is quoted; CES-D items are named by their content, not quoted. Which `cov_sex` code is women rests on counts matching each paper, not on a codebook. The CES-D's positive-affect items are identified from Alexandrowicz et al. (2018, Table 1). The ladders are fitted with MLR, items as numbers, because some top categories hold one response or none in a group; the ordinal fits are checks.\n- **Solutions:** held back in `solutions/measurement-invariance.qmd` (not published).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}