{
  "hash": "8ad8a69d62b06f00130782d819ab17b6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Trials as items: brightness, rotation, Stroop and shots\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Beyond the standard models  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [What is an item? Explanatory item response models](explanatory-irt.qmd)  \n**Builds toward:** none  \n**Picks up threads:** Errors are slower than correct responses, partly because of where errors happen (from [Item response data and the IRW](irw-data.qmd)); Items are a sample from a population of possible items, describable by their features (from [What is an item? Explanatory item response models](explanatory-irt.qmd)); Reliability, like any correlation, depends on how much the population varies (from [Classical test theory and reliability](ctt-reliability.qmd))  \n**IRW tables:** [`rr98_accuracy`](https://itemresponsewarehouse.org/tables/rr98_accuracy/), [`mentalrotation_wolf_2024`](https://itemresponsewarehouse.org/tables/mentalrotation_wolf_2024/), [`enkavi_2019_stroop`](https://itemresponsewarehouse.org/tables/enkavi_2019_stroop/), [`nbashots_sim`](https://itemresponsewarehouse.org/tables/nbashots_sim/)  \n**From EDUC 252:** slides c9; problem sets PS9#2; code [`c9/mrot.R`](https://github.com/ben-domingue/252/blob/main/c9/mrot.R), [`ps9/shots.R`](https://github.com/ben-domingue/252/blob/main/ps9/shots.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.  \n**Comments:** [open an issue on GitHub](https://github.com/ben-domingue/irw-course/issues/new?title=Trials%20as%20items%3A%20brightness%2C%20rotation%2C%20Stroop%20and%20shots%3A%20) about this lesson.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\nwebr::install(\"lme4\", quiet = TRUE)\nsuppressPackageStartupMessages(library(lme4))\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {palette} from \"./widgets/irt.js\"\nimport {RR98, psychFit, varianceParts, shotWorld} from \"./widgets/trials.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nA test usually shows each respondent each item once. Many experiments show each respondent the same few stimuli many times: a patch of a given brightness, a shape rotated by 50 or 150 degrees, a colour word printed in the wrong ink. Each showing is a \"trial\", and a table of trials raises questions a test doesn't. Which trials should be considered as representative of the same \"item\" (i.e., they should share a common difficulty parameter)? Can a feature of the stimulus, such as its brightness, stand in for that parameter? And is the question even about the respondents? It may be about the stimulus: does changing it change performance for everyone? An experiment can answer that emphatically and say almost nothing about how people differ. This lesson brings the explanatory models of [What is an item?](explanatory-irt.qmd) to trial data, and ends on what the reliability paradox means for anyone who wants to use an experimental effect to measure people.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- fit an item response model to trial data, one row per trial, and say what it assumes about trials of the same item;\n- replace item difficulties with a function of a feature of the stimulus, and compare the two in and out of sample;\n- decompose the variance of trial responses into an average effect, person differences in that effect, and trial noise, and compute the reliability of a person's effect from it;\n- explain why a large, universal experimental effect can come with unreliable individual differences;\n- say why ability estimates are biased when respondents choose their own trials, and what adjusting for trial features does about it.\n\n## Core ideas\n\n### Vocabulary\n\nThe lesson uses six terms throughout. The running example is [Ratcliff and Rouder's (1998)](https://doi.org/10.1111/1467-9280.00067) brightness experiment: on each trial an observer sees a patch of pixels at one of 33 brightness levels and says whether it came from a bright or a dark distribution.\n\n- **Respondent**: whatever the IRW's `id` indexes, written $j$. In the brightness data a respondent is one observer's session, not a person.\n- **Stimulus**: what the respondent is shown on a trial and responds to: a patch of pixels, a pair of shapes, a colour word printed in an ink. For a basketball shot it is the situation the shooter shoots from: the spot on the court, the defence, the clock. A stimulus has more properties than any table records.\n- **Trial**: one showing of a stimulus to a respondent, and the response to it, written $t$. In the IRW a trial is one row.\n- **Feature**: a recorded property of the stimulus, such as its brightness, the angle of rotation, whether word and ink agree or the distance of a shot, or of the trial's context, such as what came before or the game clock. An item is usually defined by the values of some features; other features can then explain why items differ in difficulty, as in the LLTM. Properties that aren't recorded end up in the trial noise.\n- **Item**: a set of trials that the model treats as interchangeable and gives one parameter for difficulty (below, an easiness $\\beta_i$), written $i$. We write $i(t)$ for the item that trial $t$ belongs to: $i(\\cdot)$ is a function from trials to items, so every trial that shows a level-12 patch has $i(t) = 12$ and gets the same easiness, $\\beta_{12}$. Which trials to pool is the analyst's choice, usually made on the values of some features, and the IRW's `item` column records one choice: the brightness level, the sheet × shape × angle in mental rotation, the word × ink in Stroop, the zone of a basketball shot. Trials of one item need not show the same stimulus: in the mental rotation data, one IRW item holds both a same pair and a mirrored pair of shapes. A respondent usually has many trials of each item, a median of 12 per brightness level; a test usually has one per respondent and item.\n- **Effect**: the difference in performance between trials that differ in a feature, such as incongruent minus congruent in Stroop. It has an average over respondents and can differ from one respondent to the next.\n\n### Many trials of one item\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Item response data and the IRW](irw-data.qmd): in `rr98_accuracy` the reshape to one row per respondent needed a rule for a respondent with several trials of one item: keep one, average them, or redefine the respondent or the item.\n:::\n\nA test gives each respondent–item pair one row. Here a pair has many: a median of 12 in the brightness data. The rules in the Recall reduce them to one. The common choice is to average each respondent's trials of an item, but that folds the trial-to-trial noise into the averages, where it can no longer be told apart from differences between respondents; [Rouder and Haaf (2019)](https://doi.org/10.3758/s13423-018-1558-y) show that this can shrink effect sizes and correlations alike.\n\nThis lesson keeps every trial as its own row instead. Give each brightness level its own easiness $\\beta_i$ and fit the Rasch model to the trials themselves:\n$$\\text{logit}\\Pr(x_{jt} = 1) = \\theta_j + \\beta_{i(t)}, \\qquad \\theta_j \\sim N(0, \\sigma^2_\\theta),$$\nwhere $x_{jt}$ is 1 if respondent $j$'s trial $t$ is correct and $\\beta_{i(t)}$ is the easiness of that trial's item.\nThis is the Rasch model of [What is an item?](explanatory-irt.qmd) with many rows per respondent–item pair, and `glmer()` ([Bates, Mächler, Bolker & Walker, 2015](https://doi.org/10.18637/jss.v067.i01)) fits it as before. It assumes that a respondent's twelfth trial of an item is interchangeable with the first: no practice, fatigue or memory of the trial before ([De Boeck & Wilson, 2004](https://doi.org/10.1007/978-1-4757-3990-9)).\n\nThe model is only as good as the choice of which trials make an item.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is an item?](explanatory-irt.qmd): in hearts and flowers, a flower after a heart cost 0.59 logits against a flower after a flower, more than the whole spread among the four shape × side items. Pooling trials by shape and side alone put different trials in one item; the better item was the stimulus in its context.\n:::\n\nHearts and flowers has four items, each with dozens of trials per respondent. The brightness experiment has 33, and other experiments vary a feature almost continuously (the angle between two shapes, the coherence of moving dots), so that there are dozens of items that differ only in that one feature. Then it is natural to replace their difficulties with a function of the feature.\n\n### Replace item difficulties with a feature\n\nThe LLTM wrote each item's easiness as a weighted sum of its features ([Fischer, 1973](https://doi.org/10.1016/0001-6918(73)90003-6)). With one continuous feature $s$ it is a regression on that feature,\n$$\\beta_{i} = \\beta_0 + \\beta_1\\, g(s_i),$$\nfor some function $g$. Plotted as probability correct against the strength of the stimulus, the result is what psychophysics calls the **psychometric function** ([Wichmann & Hill, 2001](https://doi.org/10.3758/BF03194544)). In the brightness experiment, brightness is the share of white pixels, in 33 levels from all black (0) to all white (32). Each patch was drawn from one of two overlapping distributions, a bright one and a dark one, and a response is correct if it names the right one. Near the middle level, 16, a patch could easily have come from either, so accuracy should be lowest there and rise with the distance from it: $g(s) = |s - 16|$. The Rasch model above has 33 easinesses, one per level. The line $\\beta_0 + \\beta_1 |s_i - 16|$ has two, an intercept and a slope, and says that every level the same distance from the middle is equally easy.\n\n#### Try it: one easiness per level, or a line through them\n\nEach dot is one brightness level in `rr98_accuracy`, pooled over the 30 sessions and sized by its number of trials. Choose how to model the levels' easinesses and where the middle of the brightness range sits. Between the line and one easiness per level is a third option: one easiness per distance from the middle (17 parameters), which pools the two levels at each distance but doesn't force a line.\n\n```{ojs}\n//| echo: false\nviewof pf_model = Inputs.radio([\"A line in distance from the middle\", \"One easiness per distance from the middle\", \"One easiness per level\"],\n  {value: \"A line in distance from the middle\", label: \"Easiness of each level\"})\nviewof pf_mid = Inputs.range([14, 18], {value: 16, step: 0.5, label: \"Middle of the brightness range (level)\"})\n```\n\n```{ojs}\n//| echo: false\npf_key = pf_model.startsWith(\"A line\") ? \"line\" : pf_model.startsWith(\"One easiness per distance\") ? \"dist\" : \"level\"\npf = psychFit(pf_key, pf_mid)\npf_full = psychFit(\"level\")\npf_pts = RR98.n.map((n, i) => ({level: i, p: RR98.k[i] / n, n, fit: pf.p[i]}))\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Brightness level (0 = all black, 32 = all white)\"}, y: {label: \"Proportion correct\", domain: [0.4, 1]},\n  r: {range: [2, 8]},\n  marks: [\n    Plot.ruleY([0.5], {stroke: palette.guide, strokeDasharray: \"4 3\"}),\n    Plot.ruleX([pf_mid], {stroke: palette.rule}),\n    Plot.dot(pf_pts, {x: \"level\", y: \"p\", r: \"n\", fill: palette.main, fillOpacity: 0.7}),\n    Plot.line(pf_pts, {x: \"level\", y: \"fit\", stroke: palette.contrast, strokeWidth: 2.5})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`**${pf.npar} parameters**, log likelihood **${pf.ll.toFixed(1)}**, AIC **${pf.aic.toFixed(0)}**. One easiness per level (33 parameters) reaches ${pf_full.ll.toFixed(1)}, AIC ${pf_full.aic.toFixed(0)}. (Trials pooled, no session effects.)`\n```\n\nWith the middle at 16, the line gives up about 43 units of log likelihood to one easiness per level, and the AIC prefers the 33 parameters. Move the middle to 15.5: both distance models improve, and one easiness per distance now has the lowest AIC of the three. The data put the point of greatest confusion a little below the design's middle; a feature model has to be told this.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A line in distance for 33 brightness levels fits worse than one easiness per level by a likelihood-ratio test, yet predicts held-out trials about as well. How can both be true?\",\n  options: [\n    {text: \"With thousands of trials the test detects small departures from the line, and 31 extra parameters buy little in new data\", correct: true, why: \"As with the LLTM in *What is an item?*, precise estimates make small misfits significant; out of sample, the noise in the extra parameters offsets most of what they add.\"},\n    {text: \"The likelihood-ratio test is invalid for mixed models\", correct: false, why: \"The test is approximate for a variance on the boundary of its range, but these are fixed effects, and the test is fine.\"},\n    {text: \"Out-of-sample prediction always favours the smaller model\", correct: false, why: \"Not always: when the extra parameters capture real structure and there are data to estimate them, the larger model predicts better, as the pair type does in the mental rotation data below.\"}\n  ]\n})\n```\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Model fit and out-of-sample prediction](fit-prediction.qmd): the IMV is the expected return of betting on held-out responses with one model's predictions against someone holding another's ([Domingue et al., 2024](https://doi.org/10.1007/s11336-024-09977-2)). This lesson uses it to compare models of the items.\n:::\n\n### The question may be about the stimulus\n\nIn an experiment the parameter of interest is often an effect: how much slower people are when word and ink disagree ([Stroop, 1935](https://doi.org/10.1037/h0054651)), or how much accuracy falls per 50 degrees of rotation ([Shepard & Metzler, 1971](https://doi.org/10.1126/science.171.3972.701)). So far the response has been right or wrong. In the Stroop task nearly every response is right, and the effect is measured in time: incongruent trials are slower. So this section models the response time of each trial instead, with a linear mixed model, the simplest model that carries the argument about reliability. [Response time and the speed-accuracy tradeoff](response-time.qmd) models response times properly: on the log scale, with speed as a trait of the respondent and time intensity as a property of the item, and alongside accuracy. Here, with each respondent given their own effect:\n$$\\text{RT}_{jt} = \\mu + \\theta_j + (\\delta + \\gamma_j)\\,c_t + \\varepsilon_{jt}, \\qquad \\theta_j \\sim N(0, \\tau^2_\\theta),\\ \\gamma_j \\sim N(0, \\tau^2_\\gamma),\\ \\varepsilon_{jt} \\sim N(0, \\sigma^2),$$\nwhere $\\theta_j$ is respondent $j$'s usual speed (higher is slower), $c_t$ is 1 on an incongruent trial and 0 on a congruent one, $\\delta$ is the average effect and $\\gamma_j$ is respondent $j$'s departure from it. There are now two questions. Does the manipulation work: is $\\delta$ far from 0? And do people differ in it: is $\\tau_\\gamma$ large enough to rank them?\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd): reliability is a property of scores in a population, the share of observed-score variance that is true-score variance.\n:::\n\nWith $L$ trials of each kind (congruent and incongruent), a respondent's observed effect (mean incongruent RT minus mean congruent RT) has variance $\\tau^2_\\gamma + 2\\sigma^2/L$ across respondents, so its reliability is\n$$\\rho_\\gamma = \\frac{\\tau^2_\\gamma}{\\tau^2_\\gamma + 2\\sigma^2/L}.$$\nThe group test of the average effect, over $N$ respondents, is $t = \\hat\\delta \\big/ \\sqrt{(\\tau^2_\\gamma + 2\\sigma^2/L)/N}$. The between-person variance $\\tau^2_\\gamma$ is in the numerator of the reliability and the denominator of $t$: the less people differ, the larger $t$ and the lower the reliability. [Hedge, Powell and Sumner (2018)](https://doi.org/10.3758/s13428-017-0935-1) draw the consequence: an effect becomes established, and the experiment that shows it popular, when people differ little in it, and that is what leaves the effect unreliable as a measure of individuals. This is the **reliability paradox**.\n\n#### Try it: where the variance lives\n\nThe trial SD (0.17 s) and the SD of respondents' mean speed (0.10 s) are about what the Stroop table below shows; the group test assumes 150 respondents.\n\n```{ojs}\n//| echo: false\nviewof vp_delta = Inputs.range([0, 0.3], {value: 0.12, step: 0.01, label: \"Average effect δ (s)\"})\nviewof vp_tau = Inputs.range([0, 0.15], {value: 0.05, step: 0.005, label: \"Person SD of the effect (s)\"})\nviewof vp_L = Inputs.range([10, 400], {value: 47, step: 1, label: \"Trials of each kind\"})\n```\n\n```{ojs}\n//| echo: false\nvp = varianceParts({delta: vp_delta, tauEffect: vp_tau, L: vp_L})\nvp_bars = [\n  {score: \"Each respondent's effect\", part: \"True differences\", share: vp.relEffect},\n  {score: \"Each respondent's effect\", part: \"Trial noise\", share: 1 - vp.relEffect},\n  {score: \"Each respondent's mean RT\", part: \"True differences\", share: vp.relMean},\n  {score: \"Each respondent's mean RT\", part: \"Trial noise\", share: 1 - vp.relMean}]\nPlot.plot({\n  width: 700, height: 170, marginLeft: 170, x: {label: \"Share of the variance in the observed score\", domain: [0, 1]}, y: {label: null},\n  color: {legend: true, domain: [\"True differences\", \"Trial noise\"], range: [palette.main, palette.light]},\n  marks: [Plot.barX(vp_bars, Plot.stackX({y: \"score\", x: \"share\", fill: \"part\"}))]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Reliability of each respondent's effect: **${vp.relEffect.toFixed(2)}**; of their mean RT: **${vp.relMean.toFixed(2)}**. Group test of the effect: **t = ${vp.t.toFixed(1)}**.`\n```\n\nShrink the person SD toward 0. The t statistic *rises*, from 24 to 42, as the reliability of the effect falls to 0: the less people differ, the clearer the manipulation and the emptier the ranking. More trials help slowly, because a difference carries the noise of two means: at a person SD of 0.05 s it takes about 200 trials of each kind to reach 0.9. The reliability of mean RT stays near 0.97.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Validity as causation](validity-causal.qmd): a timed Stroop there had an effect retest correlation of 0.17, against 0.73 for congruent RT. The variance ratio here says why trials help as they do.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: the reliability of an effect estimated from trials\n\n**Assumptions:** the RT model above; trials are independent given $\\theta_j$ and $\\gamma_j$, with the same noise variance $\\sigma^2$ on congruent and incongruent trials; each respondent has $L$ trials of each kind; $\\theta$, $\\gamma$ and $\\varepsilon$ are mutually independent.\n\nA respondent's mean RTs on congruent and incongruent trials are $\\bar y_{j0} = \\mu + \\theta_j + \\bar\\varepsilon_{j0}$ and $\\bar y_{j1} = \\mu + \\theta_j + \\delta + \\gamma_j + \\bar\\varepsilon_{j1}$, with $\\text{var}(\\bar\\varepsilon) = \\sigma^2/L$. Their difference is $d_j = \\delta + \\gamma_j + (\\bar\\varepsilon_{j1} - \\bar\\varepsilon_{j0})$: $\\theta_j$ cancels, and the two error means add, so $\\text{var}(d_j) = \\tau^2_\\gamma + 2\\sigma^2/L$. The true score is $\\delta + \\gamma_j$, whose variance is $\\tau^2_\\gamma$, so the reliability is $\\tau^2_\\gamma / (\\tau^2_\\gamma + 2\\sigma^2/L)$. The respondent's mean over both kinds of trial is $\\mu + \\theta_j + (\\delta + \\gamma_j)/2 + (\\bar\\varepsilon_{j0} + \\bar\\varepsilon_{j1})/2$, whose error variance is $\\sigma^2/(2L)$, a quarter of the difference's.\n\nSolve for the number of trials that gives a target reliability $R$:\n$$L = \\frac{2\\sigma^2}{\\tau^2_\\gamma}\\cdot\\frac{R}{1 - R},$$\nthe Spearman–Brown formula ([Spearman, 1910](https://doi.org/10.1111/j.2044-8295.1910.tb00206.x); [Brown, 1910](https://doi.org/10.1111/j.2044-8295.1910.tb00207.x)) in the currency of trials. It depends on the ratio $\\sigma/\\tau_\\gamma$ and on nothing else; the average effect $\\delta$ doesn't appear. Two routes follow. One is more trials. The other is to leave the observed effects alone and estimate $\\tau_\\gamma$, and the correlation of $\\gamma$ with anything else, inside the model, where trial noise is a separate term ([Rouder & Haaf, 2019](https://doi.org/10.3758/s13423-018-1558-y)). That estimate is only as good as the model's assumptions about the trial noise, and it doesn't make any single respondent's effect more precise.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Two Stroop-like experiments have the same trial noise and number of trials. Experiment A's average effect is twice experiment B's; the person SD of the effect is the same in both. Which experiment's effect is more reliable as a measure of individuals?\",\n  options: [\n    {text: \"Neither: the reliability depends on the person SD and the trial noise, not the average effect\", correct: true, why: \"The average $\\\\delta$ shifts every respondent's true effect by the same amount and drops out of the variance ratio. Experiment A gives the larger t statistic, not the better ranking.\"},\n    {text: \"Experiment A, because its effect is larger\", correct: false, why: \"A larger average effect makes the group test more powerful. Reliability is about differences among respondents, which the average doesn't touch.\"},\n    {text: \"Experiment B, because a smaller effect has less noise\", correct: false, why: \"The noise comes from the trials, $2\\\\sigma^2/L$, and is the same in both experiments.\"}\n  ]\n})\n```\n\n### When respondents choose their trials\n\nIn a laboratory the experimenter assigns the trials. Elsewhere respondents choose them. A basketball player's shots are trials, each a make or a miss. The item might be the zone the shot is taken from, but no two shots from a zone are the same stimulus, and the player picks which to take. Whether a shooter's chance changes from shot to shot is an old question ([Gilovich, Vallone & Tversky, 1985](https://doi.org/10.1016/0010-0285(85)90010-6)); ours is simpler. A shooting percentage mixes skill with selection.\n\n#### Try it: choosing shots\n\nTwo shooters take 2,000 threes each. A contested three is 0.8 logits harder than an open one, and shooter A makes 40% of open threes. The numbers are invented, at roughly the scale of professional three-point shooting.\n\n```{ojs}\n//| echo: false\nviewof sh_hardA = Inputs.range([0, 1], {value: 0.3, step: 0.05, label: \"Shooter A: share of contested threes\"})\nviewof sh_hardB = Inputs.range([0, 1], {value: 0.7, step: 0.05, label: \"Shooter B: share of contested threes\"})\nviewof sh_gap = Inputs.range([-0.5, 0.5], {value: 0, step: 0.05, label: \"B's true skill minus A's (logits)\"})\n```\n\n```{ojs}\n//| echo: false\nsh = shotWorld({hardA: sh_hardA, hardB: sh_hardB, skillGap: sh_gap})\nsh_pts = [{who: \"Shooter A\", pct: sh.pctA}, {who: \"Shooter B\", pct: sh.pctB}]\nPlot.plot({\n  width: 700, height: 150, marginLeft: 90, x: {label: \"Three-point percentage\", domain: [0, 0.6]}, y: {label: null},\n  color: {domain: [\"Shooter A\", \"Shooter B\"], range: [palette.main, palette.contrast]},\n  marks: [Plot.barX(sh_pts, {y: \"who\", x: \"pct\", fill: \"who\"}),\n          Plot.text(sh_pts, {y: \"who\", x: \"pct\", text: (d) => (100 * d.pct).toFixed(1) + \"%\", dx: 22})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Skill gap, B minus A, from the percentages alone: **${sh.rawGap.toFixed(2)}** logits (SE ${sh.rawSE.toFixed(2)}). Adjusting for shot type: **${sh.adjGap.toFixed(2)}** (SE ${sh.adjSE.toFixed(2)}). True gap: ${sh_gap.toFixed(2)}.`\n```\n\nWith equal skill and the default mixes, B shoots 28.1% to A's 34.9% and looks 0.31 logits worse; with shot type in the model, the tie is restored. Give B a true edge of 0.3 logits and the percentages come out nearly equal, while the adjusted gap finds the edge. The adjustment works because the widget knows the one feature that makes shots differ. When choices also depend on things the data don't record, no adjustment for recorded features is complete.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In the widget, two equally skilled shooters have different percentages. What removes the gap?\",\n  options: [\n    {text: \"Putting shot type in the model as a feature, so each shooter's skill is compared on the same kind of shot\", correct: true, why: \"Shot type is a feature, as in the LLTM. With it in the model, each shooter's parameter is their skill at a given kind of shot.\"},\n    {text: \"More shots\", correct: false, why: \"More shots shrink the standard error around the wrong answer: the raw gap comes from the mix of shots, not from noise.\"},\n    {text: \"Nothing: the percentage is the skill\", correct: false, why: \"A percentage is skill averaged over the shots a player chose. Two players who choose differently are averaged over different items.\"}\n  ]\n})\n```\n\n## Simulate\n\nThe code simulates a mental rotation experiment: 50 respondents meet each of four angles ten times in each of two sessions. Accuracy falls by 0.4 logits per 50 degrees on average, and respondents' slopes vary with SD `slope_sd`. It fits one parameter per angle, a line in angle, and a line with random slopes to session 1, scores their predictions of session 2 with the IMV, and retests each respondent's angle cost (accuracy at the two small angles minus the two large). The first run takes 30 to 45 seconds, mostly loading `lme4`.\n\nWith the seed as written (`slope_sd <- 0.3`), the angle effect is −0.41 (z = −8.7), the line predicts as well as one parameter per angle (IMV 0.023 against 0.022), random slopes add a little (0.026), and the angle cost retests at 0.41 against 0.91 for accuracy. Set `slope_sd <- 0`: the group effect is as clear (z = −9.5), yet the cost still retests at 0.20, because on the probability scale a constant logit cost is smaller near the ceiling, so the cost partly re-measures accuracy. At `slope_sd <- 1` the random slopes' IMV rises to 0.050 and the cost retests at 0.83.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-16\n# Trials as items, simulated: 50 respondents each meet four rotation angles\n# (0, 50, 100, 150 degrees) ten times, in two sessions. Accuracy falls with angle\n# by `slope_mean` logits per 50 degrees on average; respondents differ in overall\n# accuracy (SD 1) and in how much angle costs them (SD `slope_sd`). We fit three\n# accounts of the angles to session 1 with lme4, predict session 2, and ask two\n# questions: which account predicts new trials best (the IMV), and how well does\n# each respondent's own angle cost at session 1 predict it at session 2?\n#\n# nAGQ = 0 keeps each fit to a second or two in the browser; delete it in your own\n# R session for the full Laplace fit. New for this course, after c9/mrot.R.\nlibrary(lme4)\nset.seed(9)\nnp <- 50            # respondents\nreps <- 10          # trials per angle per session\nslope_mean <- -0.4  # average change in logits per 50 degrees\nslope_sd <- 0.3     # SD across respondents of their own slope\n\ntheta <- rnorm(np, 1.5, 1)\nslope <- rnorm(np, slope_mean, slope_sd)\nsession <- function(s) {\n  d <- expand.grid(id = factor(1:np), angle = c(0, 50, 100, 150), rep = 1:reps)\n  d$a50 <- d$angle / 50\n  d$resp <- rbinom(nrow(d), 1, plogis(theta[d$id] + slope[d$id] * d$a50))\n  d$session <- s\n  d\n}\ns1 <- session(1); s2 <- session(2)\n\n# The IMV (Domingue et al., 2024): the expected return of betting on new trials\n# with the second model's predictions against someone holding the first's.\ncoin <- function(ll) if (ll <= log(0.5)) 0.5 else\n  uniroot(function(w) w * log(w) + (1 - w) * log(1 - w) - ll, c(0.5, 1 - 1e-12))$root\nimv <- function(y, p0, p1) {\n  w <- sapply(list(p0, p1), function(p) coin(mean(y * log(p) + (1 - y) * log(1 - p))))\n  (w[2] - w[1]) / w[1]\n}\n\nper_angle <- glmer(resp ~ factor(angle) + (1 | id), s1, binomial, nAGQ = 0)\nlinear    <- glmer(resp ~ a50 + (1 | id), s1, binomial, nAGQ = 0)\nslopes    <- glmer(resp ~ a50 + (1 + a50 | id), s1, binomial, nAGQ = 0)\npeople    <- glmer(resp ~ 1 + (1 | id), s1, binomial, nAGQ = 0)\np <- lapply(list(people = people, per_angle = per_angle, linear = linear, slopes = slopes),\n            predict, newdata = s2, type = \"response\")\n\ncat(sprintf(\"Angle effect at session 1: %.2f logits per 50 degrees (true %.2f), z = %.1f\\n\",\n            fixef(linear)[\"a50\"], slope_mean, coef(summary(linear))[\"a50\", \"z value\"]))\ncat(sprintf(\"SD of respondents' slopes: true %.2f, estimated %.2f\\n\", slope_sd,\n            attr(VarCorr(slopes)$id, \"stddev\")[2]))\ncat(\"\\nIMV for predicting session 2, each model against respondents only:\\n\")\nprint(round(sapply(p[-1], function(q) imv(s2$resp, p$people, q)), 4))\n\n# Each respondent's own scores in each session: overall accuracy, and the angle\n# cost (accuracy at 0 and 50 degrees minus accuracy at 100 and 150), the analogue\n# of a Stroop effect. How well does session 1 predict session 2?\nscores <- function(d) {\n  small <- tapply(d$resp[d$angle < 75], d$id[d$angle < 75], mean)\n  large <- tapply(d$resp[d$angle > 75], d$id[d$angle > 75], mean)\n  cbind(accuracy = (small + large) / 2, cost = small - large)\n}\na <- scores(s1); b <- scores(s2)\ncat(\"\\nSession 1 vs. session 2 correlation of each respondent's scores:\\n\")\nprint(round(c(accuracy = cor(a[, 1], b[, 1]), angle_cost = cor(a[, 2], b[, 2])), 2))\n\n```\n:::\n\n\n[Download this code](code/trials-sim.R) to run it with more respondents, trials or sessions in your own R session.\n\n## With real data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(lme4)\noptions(digits = 7)  # R's default, in case a .Rprofile changes it\n# The IMV (Domingue et al., 2024): coin() turns a mean log likelihood into the\n# weight w >= 0.5 of a coin with the same expected log likelihood per toss, and\n# imv() is the expected return, (w1 - w0) / w0, of betting with the better coin.\ncoin <- function(ll) {\n  if (ll <= log(0.5)) return(0.5)\n  uniroot(function(w) w * log(w) + (1 - w) * log(1 - w) - ll, c(0.5, 1 - 1e-12), tol = 1e-12)$root\n}\nmean_ll <- function(y, p) mean(y * log(p) + (1 - y) * log(1 - p))\nimv <- function(y, p0, p1) (coin(mean_ll(y, p1)) - coin(mean_ll(y, p0))) / coin(mean_ll(y, p0))\n# k-fold cross-validation over trials. fit(formula, data) returns a model whose\n# predict(type = \"response\") gives probabilities for held-out rows. Returns the\n# IMV of each model over the first one, averaged over folds.\ncv_imv <- function(d, formulas, fit, k = 10, seed = 1) {\n  set.seed(seed)\n  fold <- sample(rep(1:k, length.out = nrow(d)))\n  P <- sapply(formulas, function(f) {\n    p <- numeric(nrow(d))\n    for (i in 1:k) p[fold == i] <- predict(fit(f, d[fold != i, ]), d[fold == i, ],\n                                           type = \"response\", allow.new.levels = TRUE)\n    p\n  })\n  sapply(names(formulas)[-1], function(m)\n    round(mean(sapply(1:k, function(i) imv(d$resp[fold == i], P[fold == i, 1], P[fold == i, m]))), 4))\n}\n```\n:::\n\n\n[rr98_accuracy](https://itemresponsewarehouse.org/tables/rr98_accuracy/) is the main example: 33 items, the brightness levels, and a feature that should explain their difficulties. [mentalrotation_wolf_2024](https://itemresponsewarehouse.org/tables/mentalrotation_wolf_2024/) is the contrast, where the feature explains less than which trials the IRW pools into an item. [enkavi_2019_stroop](https://itemresponsewarehouse.org/tables/enkavi_2019_stroop/) is the failure case for individual differences: an effect nearly everyone shows, retested. `nbashots_sim` closes the section: simulated basketball shots, where respondents choose their trials and the true skill is known. [Download the code](code/trials-irw.R); it needs `lme4`. Keying: in all four tables 1 is a correct response (for shots, a make).\n\n### Brightness: 33 items, one feature\n\n[Ratcliff and Rouder (1998)](https://doi.org/10.1111/1467-9280.00067) had three observers judge whether a patch of pixels came from a bright or a dark distribution, over about ten sessions each. The IRW keeps the blocks with accuracy instructions, and its `id` is an observer's session ([processing script](https://github.com/ben-domingue/irw/blob/main/data/rr98.R)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nrr <- read.csv(\"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.rr98_accuracy/rows?format=csv\")\nrr$level <- as.integer(sub(\"i \", \"\", rr$item))   # brightness, 0 (black) to 32 (white)\nrr$observer <- sub(\" .*\", \"\", rr$id)             # \"jf 2\" is observer jf's second session\nrr$dist <- abs(rr$level - 16)                    # distance from the middle level\nc(trials = nrow(rr), observers = length(unique(rr$observer)), sessions = length(unique(rr$id)),\n  levels = length(unique(rr$level)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   trials observers  sessions    levels \n    12205         3        30        33 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\np_level <- tapply(rr$resp, rr$level, mean)\nround(p_level[c(\"0\", \"8\", \"15\", \"16\", \"17\", \"24\", \"32\")], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   0    8   15   16   17   24   32 \n0.95 0.86 0.50 0.52 0.52 0.89 0.95 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nplot(as.integer(names(p_level)), p_level, pch = 19, col = \"#2780e3\", ylim = c(0.4, 1),\n     xlab = \"Brightness level (0 = all black, 32 = all white)\", ylab = \"Proportion correct\")\nabline(h = 0.5, lty = 2, col = \"grey60\")\n```\n\n::: {.cell-output-display}\n![](trials_files/figure-html/rr98-levels-1.png){width=576}\n:::\n:::\n\n\nAccuracy is 0.95 at both ends and 0.50 at level 15. Now three models of the levels' easinesses, each with random effects for observer and session:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Observers and their sessions are crossed with the levels: every session meets\n# every level many times. Three accounts of the levels:\n#   per_level: one easiness for each of the 33 levels (the Rasch-style description)\n#   symmetric: one for each distance from the middle (17)\n#   distance:  a straight line in distance from the middle (2)\nm_level <- glmer(resp ~ 0 + factor(level) + (1 | observer) + (1 | id), rr, binomial)\nm_sym   <- glmer(resp ~ 0 + factor(dist) + (1 | observer) + (1 | id), rr, binomial)\nm_dist  <- glmer(resp ~ dist + (1 | observer) + (1 | id), rr, binomial)\nround(fixef(m_dist), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)        dist \n      -0.17        0.24 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nanova(m_dist, m_sym, m_level)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|        | npar|      AIC|      BIC|    logLik| -2*log(L)|    Chisq| Df| Pr(>Chisq)|\n|:-------|----:|--------:|--------:|---------:|---------:|--------:|--:|----------:|\n|m_dist  |    4| 12948.24| 12977.87| -6470.118|  12940.24|       NA| NA|         NA|\n|m_sym   |   19| 12928.37| 13069.16| -6445.187|  12890.37| 49.86195| 15|  0.0000127|\n|m_level |   35| 12924.81| 13184.15| -6427.406|  12854.81| 35.56263| 16|  0.0033262|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Share of the variance in the 33 level easinesses the straight line accounts for\ne <- fixef(m_level)\npred <- fixef(m_dist)[1] + fixef(m_dist)[2] * abs(0:32 - 16)\nround(cor(e, pred)^2, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9\n```\n\n\n:::\n:::\n\n\nEach step of distance from the middle adds 0.24 logits. The line accounts for 90% of the variance in the 33 level easinesses, yet the likelihood-ratio tests reject it against one easiness per distance (χ² = 49.9 on 15 df), and that in turn against one per level (χ² = 35.6 on 16 df); the AICs are 12,948, 12,928 and 12,925. Out of sample:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Out of sample: which account of the levels predicts held-out trials best?\n# (glm, without the session effects, which are tiny; see below.)\ncv_imv(rr, list(mean = resp ~ 1, distance = resp ~ dist, symmetric = resp ~ factor(dist),\n                per_level = resp ~ factor(level)),\n       function(f, d) glm(f, binomial, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n distance symmetric per_level \n   0.0772    0.0783    0.0759 \n```\n\n\n:::\n:::\n\n\nAgainst the overall proportion correct, the line earns an IMV of 0.0772; one easiness per distance adds a thousandth, and one easiness per level loses one. Two parameters predict new trials as well as 33.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Item response data and the IRW](irw-data.qmd): in this table errors were slower than correct responses by 0.09 s pooled, but by only about 0.02 s within a brightness level, because errors crowd into the hard levels, which are slow for every response. Giving each level its own easiness makes the same separation for accuracy: the difficulty of an item is kept apart from anything about the respondent.\n:::\n\nWhat about the respondents? There are three observers, 33 levels and over 12,000 trials.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"With the 33 levels in the model, how much do the three observers, and their 30 sessions, differ in accuracy?\",\n  choices: [\"A lot: observers differ by a logit or more\", \"Moderately: SDs of a few tenths of a logit\", \"Barely: SDs near zero\"],\n  answer: \"Barely: SDs near zero\",\n  reveal: \"The SD between observers is estimated at 0 and between sessions at 0.05 logits; the observers' accuracies run from 0.715 to 0.726. The items do nearly all the work.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nVarCorr(m_level)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups   Name        Std.Dev.\n id       (Intercept) 0.051195\n observer (Intercept) 0.000000\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(rr$resp, rr$observer, mean), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   jf    kr    nh \n0.724 0.715 0.726 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(range(tapply(rr$resp, rr$id, mean)), 2)   # the 30 sessions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.68 0.77\n```\n\n\n:::\n:::\n\n\nThe SD between observers is 0, and between sessions 0.05 logits; the observers' accuracies run from 0.715 to 0.726, the sessions' from 0.68 to 0.77, partly because sessions drew different levels. For this experiment that is a success: psychophysics wants every observer to be a replicate, so that the psychometric function describes the visual system. There is no individual to measure, and the design didn't ask for one.\n\n### Mental rotation: a feature and a hidden design\n\n[Wolf and Larsen (2024)](https://doi.org/10.5334/jopd.99) had 37 undergraduates look at a 3-D printed shape made of cubes while feeling a second one they could not see, and say whether the two were the same; the shapes follow [Shepard and Metzler (1971)](https://doi.org/10.1126/science.171.3972.701). Each respondent met four shapes at four angles (0, 50, 100 and 150 degrees), each once as a same pair and once as a different, mirrored pair (Wolf & Larsen, 2024, §2.1): 32 trials. The IRW item is sheet × shape × angle ([processing script](https://github.com/ben-domingue/irw/blob/main/data/mentalrotation_wolf_2024.R)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nmr <- read.csv(\"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.mentalrotation_wolf_2024/rows?format=csv\")\nmr$angle50 <- mr$itemcov_angle / 50               # angle in steps of 50 degrees\nc(trials = nrow(mr), respondents = length(unique(mr$id)), items = length(unique(mr$item)),\n  trials_per_respondent = nrow(mr) / length(unique(mr$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               trials           respondents                 items \n                 1184                    37                    64 \ntrials_per_respondent \n                   32 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(pairs_per_item = table(paste(mr$id, mr$item)))   # each respondent meets each item twice\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npairs_per_item\n  2 \n592 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(mr$resp, mr$itemcov_angle, mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   0   50  100  150 \n0.77 0.75 0.68 0.70 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nctl <- glmerControl(optimizer = \"bobyqa\")\nm_angle <- glmer(resp ~ angle50 + (1 | id), mr, binomial, control = ctl)\nround(summary(m_angle)$coefficients, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error z value Pr(>|z|)\n(Intercept)    1.316      0.165   7.988    0.000\nangle50       -0.156      0.061  -2.556    0.011\n```\n\n\n:::\n:::\n\n\nAccuracy falls from 0.77 at 0 degrees to 0.70 at 150, 0.16 logits per 50 degrees (SE 0.06): a fairly small effect. But each IRW item pools two kinds of trial: a same pair and a different, mirrored pair. The pair type isn't in the item label; the answer given (`resp_raw`) and its correctness reveal it:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# resp_raw is the answer given (\"s\" same, \"d\" different) and resp whether it was\n# right, so together they say which kind of pair was on the table.\nmr$pair <- ifelse(mr$resp == 1, mr$resp_raw, ifelse(mr$resp_raw == \"s\", \"d\", \"s\"))\nmr$pair <- factor(ifelse(mr$pair == \"s\", \"same\", \"different\"), levels = c(\"same\", \"different\"))\ntable(mr$pair)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     same different \n      581       603 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(mr$resp, list(angle = mr$itemcov_angle, pair = mr$pair), mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     pair\nangle same different\n  0   0.94      0.62\n  50  0.87      0.64\n  100 0.70      0.66\n  150 0.72      0.69\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nm_pair <- glmer(resp ~ angle50 * pair + (1 | id), mr, binomial, control = ctl)\nround(summary(m_pair)$coefficients, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      Estimate Std. Error z value Pr(>|z|)\n(Intercept)              2.589      0.264   9.796        0\nangle50                 -0.604      0.107  -5.635        0\npairdifferent           -2.032      0.277  -7.345        0\nangle50:pairdifferent    0.707      0.134   5.275        0\n```\n\n\n:::\n:::\n\n\nOn same pairs, accuracy falls from 0.94 to 0.72, a cost of 0.60 logits per 50 degrees; on different pairs it doesn't fall at all ($-0.60 + 0.71 = 0.10$ logits per 50 degrees, a slight rise). Which account predicts held-out trials best?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Each model's IMV over a model with respondents only, from 10-fold\n# cross-validation over trials.\nfit_glmer <- function(f, d) glmer(f, d, binomial, control = ctl)\ncv_imv(mr, list(respondents = resp ~ 1 + (1 | id),\n                angle = resp ~ angle50 + (1 | id),\n                per_angle = resp ~ factor(itemcov_angle) + (1 | id),\n                angle_shape = resp ~ angle50 + factor(itemcov_shape) + (1 | id),\n                random_item = resp ~ 1 + (1 | item) + (1 | id),\n                angle_by_pair = resp ~ angle50 * pair + (1 | id)),\n       fit_glmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        angle     per_angle   angle_shape   random_item angle_by_pair \n       0.0021       -0.0002        0.0002        0.0030        0.0313 \n```\n\n\n:::\n:::\n\n\nAgainst respondents alone, the line in angle earns an IMV of 0.0021; one parameter per angle, −0.0002; adding shape, 0.0002; a random effect for each of the 64 items, 0.0030. Angle × pair earns 0.0313, fifteen times the angle alone. What matters most is which kind of trial it was: for a different pair no rotation makes the shapes match, so the angle has less to act on.\n\n### Stroop: an effect nearly everyone shows\n\n[Enkavi et al. (2019)](https://doi.org/10.1073/pnas.1818430116) gave a large online sample a battery of self-regulation tasks and brought 150 back to estimate long-term retest reliability. In their Stroop task a colour word (red, green or blue) appears in one of the three inks, and the respondent names the ink. The IRW item is word × ink; `position` counts repetitions of an item, not the trial's place in the session ([processing script](https://github.com/ben-domingue/irw/blob/main/data/enkavi_2019_conflict_tasks.py)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nst <- read.csv(\"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_3:v8_0.enkavi_2019_stroop/rows?format=csv\")\nst$inc <- as.integer(st$itemcov_condition == \"incongruent\")\ntable(item = st$item, condition = st$itemcov_condition)[, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             condition\nitem          congruent incongruent\n  blue_blue       10768           0\n  blue_green          0        5384\n  blue_red            0        5384\n  green_blue          0        5384\n  green_green     10768           0\n  green_red           0        5384\n  red_blue            0        5384\n  red_green           0        5384\n  red_red         10768           0\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(respondents = length(unique(st$id)), retested = length(unique(st$id[st$wave == 2])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents    retested \n        523         151 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(st$resp, list(incongruent = st$inc, wave = st$wave), mean), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           wave\nincongruent     1     2\n          0 0.974 0.967\n          1 0.924 0.924\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Response times of correct trials with a recorded time\nok <- st[st$resp == 1 & !is.na(st$rt), ]\nsummary(as.vector(table(ok$id[ok$wave == 1], ok$inc[ok$wave == 1])))   # trials of each kind\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   7.00   45.00   47.00   45.55   48.00   48.00 \n```\n\n\n:::\n:::\n\n\nAccuracy is high (0.97 congruent, 0.92 incongruent), so we use response times of correct trials, a median of 47 of each kind (congruent and incongruent) per respondent.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Each respondent's mean RT on congruent and incongruent trials, and the effect (incongruent - congruent)\nby_person <- function(d) {\n  m <- tapply(d$rt, list(d$id, d$inc), mean)\n  data.frame(id = rownames(m), congruent = m[, 1], incongruent = m[, 2],\n             effect = m[, 2] - m[, 1], mean_rt = (m[, 1] + m[, 2]) / 2)\n}\nw1 <- by_person(ok[ok$wave == 1, ])\nround(colMeans(w1[, -1]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  congruent incongruent      effect     mean_rt \n      0.672       0.795       0.123       0.734 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(sd_effect = sd(w1$effect), t = mean(w1$effect) / (sd(w1$effect) / sqrt(nrow(w1))),\n        n = nrow(w1), positive = sum(w1$effect > 0)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd_effect         t         n  positive \n    0.061    46.230   522.000   520.000 \n```\n\n\n:::\n:::\n\n\nIncongruent trials are slower by 0.123 s on average (t = 46.2), and 520 of the 522 respondents show the effect. The SD of the observed effects is 0.061 s. Where does that variance live?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Where the variance lives, at wave 1: a random intercept (speed) and a random\n# slope (the person's Stroop effect) for each respondent, and trial noise.\ns1 <- lmer(rt ~ inc + (1 + inc | id), ok[ok$wave == 1, ], REML = FALSE)\nround(fixef(s1), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         inc \n      0.672       0.122 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nVarCorr(s1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups   Name        Std.Dev. Corr  \n id       (Intercept) 0.098450       \n          inc         0.049254 0.232 \n Residual             0.167106       \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntau <- attr(VarCorr(s1)$id, \"stddev\"); sig <- sigma(s1); L <- 47\n# Reliability of each respondent's observed effect and mean RT with L trials of\n# each kind (the Go deeper callout derives these)\nround(c(effect = tau[[2]]^2 / (tau[[2]]^2 + 2 * sig^2 / L),\n        mean_rt = tau[[1]]^2 / (tau[[1]]^2 + sig^2 / (2 * L))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n effect mean_rt \n   0.67    0.97 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Trials of each kind for a reliability of 0.9 in the effect\nround(2 * sig^2 * 0.9 / (tau[[2]]^2 * (1 - 0.9)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 207\n```\n\n\n:::\n:::\n\n\nThe person SD of the effect is 0.049 s, against 0.098 s for mean speed and 0.167 s for a single trial. With 47 trials of each kind, the reliability of each respondent's effect is 0.67; of their mean RT, 0.97. A reliability of 0.9 for the effect would take about 207 correct trials of each kind. And over time:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nw2 <- by_person(ok[ok$wave == 2, ])\nb <- merge(w1, w2, by = \"id\", suffixes = c(\"_1\", \"_2\"))\nnrow(b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 150\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(effect = cor(b$effect_1, b$effect_2), mean_rt = cor(b$mean_rt_1, b$mean_rt_2),\n        congruent = cor(b$congruent_1, b$congruent_2),\n        incongruent = cor(b$incongruent_1, b$incongruent_2)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     effect     mean_rt   congruent incongruent \n       0.44        0.61        0.54        0.64 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(effect_positive_wave2 = mean(b$effect_2 > 0)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neffect_positive_wave2 \n                 0.98 \n```\n\n\n:::\n:::\n\n\nFor the 150 respondents seen twice, the effect retests at 0.44 and mean RT at 0.61; 98% still show the effect. With 240 trials of each kind and three weeks apart, [Hedge et al. (2018)](https://doi.org/10.3758/s13428-017-0935-1) found intraclass correlations of 0.60 and 0.66 for the Stroop RT cost in two studies, against 0.77 and 0.72 for congruent RT. How much of the distance from 1 is trial noise, and how much is people changing?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same question inside the model: each respondent has a true speed and a true\n# effect at each wave, and the model estimates how those correlate across waves,\n# with trial noise set aside.\nok2 <- ok[ok$id %in% b$id, ]\nok2$w1 <- as.integer(ok2$wave == 1); ok2$w2 <- 1 - ok2$w1\ns12 <- lmer(rt ~ 0 + factor(wave) + inc:factor(wave) + (0 + w1 + w2 | id) +\n              (0 + w1:inc + w2:inc | id), ok2, REML = FALSE)\nVarCorr(s12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups   Name   Std.Dev. Corr  \n id       w1     0.107756       \n          w2     0.106039 0.590 \n id.1     w1:inc 0.047573       \n          inc:w2 0.041497 0.789 \n Residual        0.172126       \n```\n\n\n:::\n:::\n\n\nWith trial noise set aside, the model puts the correlation of respondents' true effects across sessions at 0.79, and of their true speed at 0.59: much of what separates 0.44 from 1 is the 47 trials. The model assumes normal trial noise, which response times don't have, so I'd hold 0.79 loosely ([Rouder & Haaf, 2019](https://doi.org/10.3758/s13423-018-1558-y), make the case for such estimates). Put together: the effect is large relative to how much people differ in it (SD 0.049 s around 0.122 s), which is why 520 of 522 show it, and the same small SD is why 47 trials leave each person's effect with a reliability of 0.67. The paradox is not a failure of the experiment. It was built to find an effect everyone has.\n\nSo would I use an experimental effect to rank people? It turns on two numbers the group analysis doesn't report: the person SD of the effect against the trial noise, and the number of trials of each kind. If the question is whether a manipulation works, a small person SD is an asset. If it is who is more affected, I'd want the variance decomposition first, and I'd plan the trials from the Go deeper formula, not from the size of the group effect. A large, universal effect is evidence that the manipulation works, not that it measures people.\n\n### Shots: chosen trials with a known answer\n\nThe widget in *When respondents choose their trials* had two shooters and one feature. [nbashots_sim](https://itemresponsewarehouse.org/tables/nbashots_sim/) is a simulated season: 400 shooters and 136,368 shots, from the IRW's [simsyn source](https://itemresponsewarehouse.org/simsyn.html) of simulated and synthetic tables ([generating script](https://github.com/ben-domingue/irw/blob/main/data/simsyn/nbashots_sim.R)). It is built to resemble NBA shooting but contains no NBA data. The item is the shot zone, from the restricted area under the basket to threes above the break; `trial_` columns record each shot's distance, court location and game clock. Each simulated shooter has a skill and a role, and chooses shots: bigs take most of theirs at the rim, and better shooters take more long twos and threes. Because the data are simulated, the true skill comes with them (`cov_true_theta`), so we can check each analysis against the answer. With a Redivis account, `irw::irw_fetch(\"nbashots_sim\", source = \"sim\")` fetches the same table.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# nbashots_sim is simulated, from the IRW's simsyn source: the shooters' true\n# skill is in cov_true_theta. The item is the shot zone; the trial_ columns give\n# the distance (feet), court location, a three-point flag, the game clock and\n# whether the shot came in the last two minutes of a quarter.\nsh <- read.csv(\"https://redivis.com/api/v1/tables/datapages.irw_simsyn:v1_2.nbashots_sim/rows?format=csv\")\nc(shots = nrow(sh), shooters = length(unique(sh$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   shots shooters \n  136368      400 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(cbind(share = prop.table(table(sh$item)), made = tapply(sh$resp, sh$item, mean)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  share made\nabove_break_three  0.27 0.35\ncorner_three       0.07 0.39\nmidrange           0.17 0.42\npaint              0.17 0.41\nrestricted_area    0.33 0.62\n```\n\n\n:::\n:::\n\n\nShots at the rim go in 62% of the time; shots from every other zone, 35% to 42%.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Each shooter's percentage against their true skill, and by role\npl <- aggregate(cbind(pct = resp, dist = trial_dist) ~ id + cov_role + cov_true_theta, sh, mean)\nround(c(pct_vs_skill = cor(pl$pct, pl$cov_true_theta), dist_vs_skill = cor(pl$dist, pl$cov_true_theta)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n pct_vs_skill dist_vs_skill \n         0.68          0.42 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\naggregate(cbind(pct, true_skill = cov_true_theta, dist) ~ cov_role, pl, function(v) round(mean(v), 2))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|cov_role |  pct| true_skill|  dist|\n|:--------|----:|----------:|-----:|\n|big      | 0.50|       0.01|  7.89|\n|guard    | 0.42|      -0.05| 15.42|\n|wing     | 0.43|      -0.01| 15.54|\n\n</div>\n:::\n:::\n\n\nA shooter's percentage correlates 0.68 with their true skill, and better shooters shoot from farther out (0.42). The bigs make 50% of their shots to the wings' and guards' 42% and 43%, with the same average skill: they shoot from 8 feet on average, the others from 15.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Skill from the makes alone, and with the shot in the model as trial features\nfit_fast <- function(f, d) glmer(f, d, binomial, nAGQ = 0)\ns0 <- fit_fast(resp ~ 1 + (1 | id), sh)\ns1 <- fit_fast(resp ~ item + trial_dist + trial_late + (1 | id), sh)\npl$u0 <- ranef(s0)$id[as.character(pl$id), 1]\npl$u1 <- ranef(s1)$id[as.character(pl$id), 1]\nround(c(makes_only = cor(pl$u0, pl$cov_true_theta), with_shot = cor(pl$u1, pl$cov_true_theta)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmakes_only  with_shot \n      0.69       0.92 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\naggregate(cbind(makes_only = u0, with_shot = u1) ~ cov_role, pl, function(v) round(mean(v), 2))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|cov_role | makes_only| with_shot|\n|:--------|----------:|---------:|\n|big      |       0.17|      0.04|\n|guard    |      -0.11|     -0.05|\n|wing     |      -0.08|      0.00|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(sd_makes_only = attr(VarCorr(s0)$id, \"stddev\"), sd_with_shot = attr(VarCorr(s1)$id, \"stddev\"),\n        sd_true = sd(pl$cov_true_theta)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd_makes_only.(Intercept)  sd_with_shot.(Intercept)                   sd_true \n                     0.24                      0.31                      0.31 \n```\n\n\n:::\n:::\n\n\nFrom the makes alone, each shooter's random effect correlates 0.69 with true skill; with zone, distance and the late clock in the model, 0.92. The bigs' edge falls from 0.17 logits to 0.04. The spread moves the other way. The SD of skill is 0.24 from the makes alone, against 0.31 with the shot in the model and 0.31 among the true values. Because the better shooters take the harder shots, their choices pull the percentages together: choosing trials can hide differences between people as well as create them.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Out of sample: what does each account of the item add over the shooters alone?\ncv_imv(sh, list(shooters = resp ~ 1 + (1 | id),\n                zone = resp ~ item + (1 | id),\n                zone_distance = resp ~ item + trial_dist + (1 | id),\n                zone_distance_late = resp ~ item + trial_dist + trial_late + (1 | id)),\n       fit_fast, k = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              zone      zone_distance zone_distance_late \n            0.1172             0.1299             0.1327 \n```\n\n\n:::\n:::\n\n\nOver shooters alone, the zone earns an IMV of 0.117, distance brings it to 0.130 and the late clock to 0.133. Here five zones and a straight line in distance are close to the whole account of a shot, because that is how the simulation was written: a make depends on skill, zone, distance and the clock, and on nothing else. Whether the zone is as good a definition of the item for real shots is problem 5.\n\n## Problems\n\n1. **Trials for a target reliability.** Starting from the RT model in *The question may be about the stimulus*, derive the number of trials of each kind needed for a reliability $R$ of each respondent's effect. With the Stroop estimates, how many correct trials of each kind give 0.8? Show that the average effect $\\delta$ doesn't enter, and say what changes if incongruent trials are noisier than congruent ones.\n2. **Angle², shape and pair.** In `mentalrotation_wolf_2024`, add a squared angle term (as `c9/mrot.R` did), then shape, then angle × pair. Which improves out-of-sample prediction, and by how much? Now give each respondent a random effect for pair type: what would such an effect mean psychologically?\n3. **Who is the respondent?** In `rr98_accuracy`, refit the level model with the observer as the only respondent, then with the session only. Which is right for a question about the visual system, and which for a question about practice across sessions? What does the zero observer SD imply for each?\n4. **Late-game threes (PS9#2).** Two shooters take the same number of threes in a season. One takes most of them in the last minutes of close games, the other early in quarters. Should their percentages be compared directly? What trial features would you want before ranking them, and which of those could the shooter's own choice depend on?\n5. **Real shots (PS9#2).** Download one season of NBA.com shot data from Samangy's collection ([GitHub](https://github.com/DomSamangy/NBA_Shots_04_23)). The files carry no licence, so they aren't in the IRW; download them for your own use. The starter code after this list reshapes a season into the columns of `nbashots_sim`, so the shots code above runs on it. (a) Starting from item = zone, add distance, then a smooth function of distance, then the shot's angle, then the shot type (`trial_action`: dunk, layup, jump shot and so on), and score each with `cv_imv()`. How good a definition of the item is the zone? (b) Compare the SD of player skill from your best model with the one from `nbashots_sim`. Which is larger, and why might they differ? Think about who plays in the NBA, what a finer item absorbs, and where the simulated value came from. (c) Does the ordering of players by skill change as the item gets finer?\n\n6. **Design a rotation measure.** Design a 20-minute mental rotation measure of individual differences in the cost of rotation: angles, trials per angle, pair types, and whether to score accuracy, time or both. Check its retest correlation with the simulation, and say what the ceiling result in Simulate implies for scoring accuracy.\n7. **Challenge (open).** Write a model in which a shooter's choice of shot depends on their skill, or on their recent success. What would identify skill separately from choice? Selection models in economics ([Heckman, 1979](https://doi.org/10.2307/1912352)) are one starting point. I don't know of a satisfying answer for shot data, where the set of shots a player declined is never observed.\n\nStarter code for problem 5:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# NBA_2024_Shots.csv, unzipped from the repository above\nx <- read.csv(\"NBA_2024_Shots.csv\")\nx <- x[x$BASIC_ZONE != \"Backcourt\", ]\nzone <- c(\"Restricted Area\" = \"restricted_area\", \"In The Paint (Non-RA)\" = \"paint\",\n          \"Mid-Range\" = \"midrange\", \"Left Corner 3\" = \"corner_three\",\n          \"Right Corner 3\" = \"corner_three\", \"Above the Break 3\" = \"above_break_three\")\nnba <- data.frame(id = x$PLAYER_ID, item = zone[x$BASIC_ZONE],\n                  resp = as.integer(x$EVENT_TYPE == \"Made Shot\"),\n                  trial_dist = x$SHOT_DISTANCE, trial_locx = x$LOC_X,\n                  trial_locy = x$LOC_Y - 5.25,          # hoop at (0, 0), as in nbashots_sim\n                  trial_late = as.integer(x$MINS_LEFT < 2),\n                  trial_action = x$ACTION_TYPE)\nnba <- nba[nba$id %in% names(which(table(nba$id) >= 100)), ]   # players with 100 or more shots\nrare <- names(which(table(nba$trial_action) < 200))\nnba$trial_action[nba$trial_action %in% rare] <- \"other\"        # so every fold has every type\n# predict() on a glmer fit can't rebuild splines::ns() for held-out rows, so\n# make the spline columns once, on the full data, and put them in the formula\nD <- splines::ns(nba$trial_dist, 6); colnames(D) <- paste0(\"d\", 1:6)\nnba <- cbind(nba, D)\n```\n:::\n\n\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Trials%20as%20items%3A%20brightness%2C%20rotation%2C%20Stroop%20and%20shots%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20experimental%20trials%20as%20item%20response%20data%3A%20respondents%2C%20trials%2C%20stimuli%2C%20features%2C%20items%20%28sets%20of%20trials%20pooled%20under%20one%20difficulty%29%20and%20effects%3B%20the%20Rasch%20model%20fit%20to%20one%20row%20per%20trial%20with%20lme4%27s%20glmer%3B%20replacing%20item%20difficulties%20with%20a%20feature%20of%20the%20stimulus%20%28a%20psychometric%20function%2C%20the%20LLTM%20with%20a%20continuous%20feature%29%20and%20comparing%20the%20accounts%20out%20of%20sample%20with%20the%20IMV%3B%20the%20decomposition%20of%20trial%20responses%20into%20an%20average%20effect%2C%20person%20differences%20in%20the%20effect%20and%20trial%20noise%2C%20the%20reliability%20of%20a%20person%27s%20effect%2C%20and%20the%20reliability%20paradox%20of%20Hedge%2C%20Powell%20and%20Sumner%20%282018%29%3B%20and%20the%20bias%20when%20respondents%20choose%20their%20own%20trials%2C%20with%20a%20brightness-discrimination%20experiment%2C%20a%20cross-modal%20mental%20rotation%20task%2C%20a%20Stroop%20task%20given%20twice%20and%20a%20simulated%20season%20of%20basketball%20shots%20%28from%20the%20IRW%27s%20simsyn%20source%2C%20with%20the%20true%20skills%20known%29%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Hedge, C., Powell, G., & Sumner, P. (2018). The reliability paradox: Why robust cognitive tasks do not produce reliable individual differences. *Behavior Research Methods*, 50(3), 1166–1186. <https://doi.org/10.3758/s13428-017-0935-1>. Retest reliability of seven classic tasks, and the argument that low between-person variance is what makes their effects replicable.\n- Rouder, J. N., & Haaf, J. M. (2019). A psychometrics of individual differences in experimental tasks. *Psychonomic Bulletin & Review*, 26(2), 452–467. <https://doi.org/10.3758/s13423-018-1558-y>. Hierarchical models that keep trial noise apart from person differences, applied to Hedge et al.'s data.\n- Enkavi, A. Z., Eisenberg, I. W., Bissett, P. G., Mazza, G. L., MacKinnon, D. P., Marsch, L. A., & Poldrack, R. A. (2019). Large-scale analysis of test–retest reliabilities of self-regulation measures. *Proceedings of the National Academy of Sciences*, 116(12), 5472–5477. <https://doi.org/10.1073/pnas.1818430116>. Survey and task measures retested side by side; the source of this lesson's Stroop data.\n- Wichmann, F. A., & Hill, N. J. (2001). The psychometric function: I. Fitting, sampling, and goodness of fit. *Perception & Psychophysics*, 63(8), 1293–1313. <https://doi.org/10.3758/BF03194544>. How psychophysics fits accuracy as a function of stimulus strength.\n- Baayen, R. H., Davidson, D. J., & Bates, D. M. (2008). Mixed-effects modeling with crossed random effects for subjects and items. *Journal of Memory and Language*, 59(4), 390–412. <https://doi.org/10.1016/j.jml.2007.12.005>. Crossed respondents and items in experimental psychology: the models of [What is an item?](explanatory-irt.qmd), seen from the other side.\n- De Boeck, P., & Wilson, M. (Eds.). (2004). *Explanatory item response models: A generalized linear and nonlinear approach*. Springer. <https://doi.org/10.1007/978-1-4757-3990-9>. Item and person features in one framework.\n- Jansen, M. G. H. (2016). Poisson and gamma models for reading speed and error. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 245–259). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315374512>. A handbook chapter on Poisson and gamma models for counts of errors and reading times.\n- From the IRW: the [reliability paradox](https://itemresponsewarehouse.org/vignettes/hf_reliability_paradox.html) vignette looks at the reliability of experimental tasks across IRW tables.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`rr98_accuracy`](https://itemresponsewarehouse.org/tables/rr98_accuracy/): Ratcliff, R., & Rouder, J. N. (1998). Modeling Response Times for Two-Choice Decisions. Psychological Science, 9(5), 347-356. <http://doi.org/10.1111/1467-9280.00067>. Licence: GPL-3.0.\n- [`mentalrotation_wolf_2024`](https://itemresponsewarehouse.org/tables/mentalrotation_wolf_2024/): Wolf, J. E., & Larsen, M. (2024). A New Procedure and Stimulus Set for Examining Cross-Modality Mental Rotation. Journal of Open Psychology Data, 12(1). <https://doi.org/10.5334/jopd.99>. Licence: CC BY 4.0.\n- [`enkavi_2019_stroop`](https://itemresponsewarehouse.org/tables/enkavi_2019_stroop/): Enkavi, A. Z., Eisenberg, I. W., Bissett, P. G., Mazza, G. L., MacKinnon, D. P., Marsch, L. A., & Poldrack, R. A. (2019). Large-scale analysis of test-retest reliabilities of self-regulation measures. Proceedings of the National Academy of Sciences, 116(12), 5472-5477. <https://doi.org/10.1073/pnas.1818430116>. Licence: CC BY 4.0.\n- [`nbashots_sim`](https://itemresponsewarehouse.org/tables/nbashots_sim/): Domingue, B. W. (2026). NBA shots simulation [R script]. Item Response Warehouse. <https://github.com/ben-domingue/irw/blob/main/data/simsyn/nbashots_sim.R>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 9 (slides c9, 17–23: trials in psychology, limited versus continuous variation, mental rotation) and problem set 9 (#2, NBA field goals as trials), with the code in `ben-domingue/252`: `c9/mrot.R` and `ps9/shots.R`.\n- **Timing:** the core ideas and widgets take about 45 minutes; the four analyses are a 40-minute lab. The mental rotation cross-validation takes about half a minute, the Stroop models a few seconds each and the shots code about a minute. Problem 5 needs a download of about 3 MB per season and runs in a few minutes.\n- **Changed from 252:** the LEVANTE rotation data (slide 22) and the NBA shot data (Samangy, [GitHub](https://github.com/DomSamangy/NBA_Shots_04_23)) aren't in the IRW, so `mentalrotation_wolf_2024` stands in for the first. The shot data carry no licence, so the IRW has a simulated stand-in, `nbashots_sim` (simsyn), for the worked example, and problem 5 takes the same code to a season of the real data, which readers download themselves. The pair-type finding in the rotation data, the brightness analysis and the Stroop variance decomposition are new.\n- **Data notes:** `nbashots_sim` is read from simsyn v1.2 (CC BY 4.0); its IRW reference is the generating script. Its make probability depends only on skill, zone, a straight line in distance and the late clock, so finer accounts of the item can't help there; in real shots they do (problem 5). The simulated skill SD (0.35 logits) is larger than a real season's. The rotation table's items don't record pair type; it is recovered from `resp` and `resp_raw`. In the Stroop table, `position` counts repetitions of an item, so trial order within a session isn't available and practice or fatigue can't be modelled from it.\n- **Held back:** learning across trials as change in $\\theta$ (dynamic models) is left open; response times on the same trials are in [Response time and the speed-accuracy tradeoff](response-time.qmd) and [Process models for response time](rt-process-models.qmd); adaptive task batteries in [Item banks and adaptive testing](item-banks-cat.qmd). Hearts and flowers repeated across blocks is not taken further here.\n- **Solutions:** held back in `solutions/trials.qmd` (not published). Problem 7 is open.\n",
    "supporting": [
      "trials_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}