# Checks the IRW tables named in lessons.yml, and refreshes the citation cache that
# each lesson's Data sources block reads (lessons/_citations.yml). Needs the network,
# so it is run by hand, not during the render:
#   Rscript check_tables.R
# It fails (exit status 1) if any table
#   - has no tokenless CSV on its landing page;
#   - has no reference in IRW biblio;
#   - appears in more than one lesson without the later lessons listing it under
#     `reuses` (a deliberate return, recorded as such);
#   - is linked or loaded in a lesson page but missing from that lesson's `tables`.
source("lessons/_course.R")
course <- read_course()
uses <- do.call(rbind, lapply(course$lessons, function(l)
  if (length(l$tables)) data.frame(table = unlist(l$tables), lesson = l$id)))
tabs <- sort(unique(uses$table))
problems <- character()

url <- vapply(tabs, irw_csv_url, "")
cites <- setNames(lapply(tabs, irw_citation), tabs)
cited <- vapply(cites, function(c) !is.null(c) && !is.na(c$reference), TRUE)
for (t in tabs) cat(sprintf("%-24s csv %-3s ref %-3s %s\n", t,
                            if (is.na(url[[t]])) "NO" else "ok", if (cited[[t]]) "ok" else "NO",
                            paste(uses$lesson[uses$table == t], collapse = ", ")))
for (t in tabs[is.na(url)])
  problems <- c(problems, sprintf("%s: no tokenless CSV (over 100 MB, so it needs a teaching subsample table; or no landing page)", t))
for (t in tabs[!cited])
  problems <- c(problems, sprintf("%s: no reference in IRW biblio", t))

# The cache holds exactly the tables lessons.yml names.
found <- Filter(Negate(is.null), cites)
writeLines(c("# Generated by check_tables.R from the IRW landing pages; do not edit.",
             yaml::as.yaml(found[order(names(found))])), CITATIONS)
cat("\nWrote ", length(found), " citations to lessons/_citations.yml\n", sep = "")

# Breadth: the first lesson (in lessons.yml order) to use a table owns it; a later
# lesson that uses it again must record the reuse.
for (t in tabs) {
  ls <- uses$lesson[uses$table == t]
  for (id in ls[-1]) if (!t %in% unlist(lesson_by_id(id, course)$reuses))
    problems <- c(problems, sprintf("%s: used in %s and again in %s; not recorded under `reuses`", t, ls[1], id))
}

# Pages against lessons.yml: tables a lesson or its code *loads* (irw_csv(), or a
# pinned Redivis URL) but that are missing from its `tables`. A link to a table's
# landing page alone is a mention, not a use: it needs no `tables` entry
# (check_links.R confirms the page exists). 09-24: irw-data's tour of the IRW.
for (l in course$lessons) {
  code <- Sys.glob(file.path("lessons", "code", paste0(l$id, "-*.R")))
  # A longer lesson id can start with this one (measurement, measurement-invariance):
  # its code files belong to it, not to this lesson.
  longer <- setdiff(vapply(course$lessons, `[[`, "", "id"), l$id)
  longer <- longer[startsWith(longer, paste0(l$id, "-"))]
  code <- code[!vapply(basename(code), function(f) any(startsWith(f, paste0(longer, "-"))), TRUE)]
  files <- c(file.path("lessons", paste0(l$id, ".qmd")), code)
  txt <- unlist(lapply(files[file.exists(files)], readLines, warn = FALSE))
  hits <- c(unlist(regmatches(txt, gregexpr("irw_csv(_url)?\\(\"[^\"]+\"", txt))),
            unlist(regmatches(txt, gregexpr("item_response_warehouse:v[0-9_]+\\.[A-Za-z0-9_.-]+", txt))))
  seen <- unique(tolower(sub('.*(\\.|")', "", sub('"$', "", sub("/rows.*", "", hits)))))
  for (t in setdiff(seen, tolower(unlist(l$tables))))
    problems <- c(problems, sprintf("%s: page uses %s, not in its `tables`", l$id, t))
}

if (length(problems)) {
  cat("\n", length(problems), " problem(s):\n  ", paste(problems, collapse = "\n  "), "\n", sep = "")
  quit(status = 1)
}
