{
  "hash": "b39994395c9b84c9ff102f411face0d5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Many sources of error: generalizability theory\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Classical test theory  \n**Tranche:** core (a first course)  \n**Before this:** [From construct map to items: building an instrument](instrument-building.qmd)  \n**Builds toward:** [Rater models: many-facet Rasch and beyond](rater-models.qmd)  \n**Starts threads:** Raters are treated as exchangeable draws from a universe of raters (→ [Rater models: many-facet Rasch and beyond](rater-models.qmd))  \n**IRW tables:** [`Forthmann-2024-cleverness_ratings`](https://itemresponsewarehouse.org/tables/forthmann-2024-cleverness_ratings/), [`teacherjudgements_lohmann_2026_essayratings`](https://itemresponsewarehouse.org/tables/teacherjudgements_lohmann_2026_essayratings/)  \n**From EDUC 252:** n/a  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.  \n**Feedback:** This page improved thanks to feedback from Rich Shavelson and Mike Hardy. All remaining errors are the responsibility of the page's creator (BD).  \n**Comments:** [open an issue on GitHub](https://github.com/ben-domingue/irw-course/issues/new?title=Many%20sources%20of%20error%3A%20generalizability%20theory%3A%20) about this lesson.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\nwebr::install(\"lme4\", quiet = TRUE)\nsuppressPackageStartupMessages(library(lme4))\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {palette, grid} from \"./widgets/irt.js\"\nimport {gCoef, coefBars, presets, twoRaters} from \"./widgets/g-theory.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nClassical test theory gives a score one error term. Suppose 202 people list unusual uses for a paperclip, a garbage bag and a rope, and five raters judge how clever each list is. A respondent might have done better with other objects, and would have got a different score from other raters. Which source of error is larger decides whether to add raters or objects. **Generalizability theory** (G theory) asks what the score should generalize over, then splits the error into those sources and prices each one ([Cronbach, Rajaratnam & Gleser, 1963](https://doi.org/10.1111/j.2044-8317.1963.tb00206.x)). In the cleverness ratings the answer is *more tasks*; in teachers' ratings of essays, *more raters*. Like CTT, G theory is a theory of observed scores. Item response theory, from [The Rasch model](rasch.qmd) on, is a latent-trait theory that models each response, and the two rest on different assumptions.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- name the facets of a measurement design, say which are crossed and which nested, and decide which the score should generalize over (random) and which not (fixed);\n- estimate variance components for a persons × tasks × raters design with `lme4`, and say which ones are error for which decision;\n- compute relative and absolute G coefficients, and show that the one-facet relative coefficient is alpha;\n- use a D study to decide whether to add tasks or raters;\n- compute consistency and agreement intraclass correlations, and say when each is the one to report.\n\n## Core ideas\n\n### One error term, many sources\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd): an observed score is $X = T + E$, reliability is $\\sigma^2_T/(\\sigma^2_T + \\sigma^2_E)$, alpha estimates it from the items of one administration, and the Spearman–Brown formula says what lengthening the test does.\n:::\n\nWhere does $E$ come from? The items behind alpha are one source; [From construct map to items](instrument-building.qmd) added another, the rater who scores a constructed response; occasions and forms are more. G theory calls each such source a **facet**, and each of its values (this rater, that task) a **condition** ([Cronbach, Gleser, Nanda & Rajaratnam, 1972](https://doi.org/10.1126/science.178.4067.1275), a book with no DOI, linked here through Bock's review in *Science*).\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Constructs and construct maps](constructs.qmd): a test built from a blueprint supports a claim about a domain, and its items can be seen as a sample from a larger pool.\n:::\n\nG theory applies that view to every facet. The tasks we used are a sample from the tasks we could have used; the raters, from the raters we would accept. Together these make up the **universe of admissible observations**, which the investigator, not the data, defines. A decision maker may care about only part of it (raters trained on this rubric, say); that part is the **universe of generalization**. A respondent's average over it is the **universe score**, G theory's counterpart of the true score, and the question of this lesson is how well an average over the few conditions we used stands in for it ([Shavelson, Webb & Rowley, 1989](https://doi.org/10.1037/0003-066X.44.6.922)). A facet we generalize over is **random**; a facet we don't (these three objects and no others) is **fixed**, and what is specific to its conditions stops being error ([Brennan, 2001](https://doi.org/10.1007/978-1-4757-3456-0)).\n\n### Variance components\n\nTake the cleverness design: every person $p$ does every task $t$, and every rater $r$ rates every response, so all three are **crossed**. A rating is a sum of effects:\n$$X_{ptr} = \\mu + \\nu_p + \\nu_t + \\nu_r + \\nu_{pt} + \\nu_{pr} + \\nu_{tr} + \\nu_{ptr,e}.$$\nEach $\\nu$ is a random effect with mean zero and its own variance, and the effects are uncorrelated, so the variance of one rating splits into seven **variance components**, $\\sigma^2_p + \\sigma^2_t + \\dots + \\sigma^2_{ptr,e}$ ([Brennan, 2001](https://doi.org/10.1007/978-1-4757-3456-0)). $\\sigma^2_p$ is how much people differ, the signal; $\\sigma^2_r$, how much raters differ in severity; $\\sigma^2_{pt}$, how much people's standing changes from task to task; $\\sigma^2_{pr}$, raters disagreeing about who is better. The last term mixes the three-way interaction with whatever else the design can't separate from it, hence the $e$.\n\nNot every design is crossed. If each essay is read by its own teachers, raters are **nested** within essays ($r{:}p$), and a teacher seen with one essay can't show both how harsh they are and how they react to that essay: $\\sigma^2_r$ and $\\sigma^2_{pr}$ merge into $\\sigma^2_{r:p}$ ([Brennan, 2001](https://doi.org/10.1007/978-1-4757-3456-0)).\n\nHow do we estimate them? Classically, by setting the mean squares of an analysis of variance equal to their expected values, a reasonable choice for a balanced design ([Brennan, 2001](https://doi.org/10.1007/978-1-4757-3456-0)) and one the essay section uses as a check. This lesson fits each term as a random intercept in a mixed model, with `lme4` ([Bates, Mächler, Bolker & Walker, 2015](https://doi.org/10.18637/jss.v067.i01)) and a long table of one row per rating:\n\n```r\nlmer(resp ~ 1 + (1 | id) + (1 | item) + (1 | rater) +\n       (1 | id:item) + (1 | id:rater) + (1 | item:rater), data = ratings)\n```\n\nThe residual variance is $\\sigma^2_{ptr,e}$. `lmer` estimates the variances by restricted maximum likelihood (REML). Plain maximum likelihood treats the fixed effects as known and so underestimates each variance, by more the fewer levels a facet has; REML removes that bias ([Patterson & Thompson, 1971](https://doi.org/10.1093/biomet/58.3.545); [Harville, 1977](https://doi.org/10.1080/01621459.1977.10480998)), which matters with facets of three and five levels. In a balanced design REML reproduces the ANOVA estimates whenever none is negative ([Searle, Casella & McCulloch, 1992](https://doi.org/10.1002/9780470316856)), and it also handles sparse designs like the second table's.\n\n### Two G coefficients\n\nWhy are some components error only some of the time? It depends on the decision. For a **relative** decision (who ranks above whom), only the components that change a person's standing count: those that interact with $p$. For a score averaged over $n_t$ tasks and $n_r$ raters, the relative error variance is\n$$\\sigma^2_\\delta = \\frac{\\sigma^2_{pt}}{n_t} + \\frac{\\sigma^2_{pr}}{n_r} + \\frac{\\sigma^2_{ptr,e}}{n_t n_r}.$$\nFor an **absolute** decision (is this score above 3? how clever is this list, on the rating scale?), a harsh rater or a hard task moves the score itself, so the main effects count too:\n$$\\sigma^2_\\Delta = \\sigma^2_\\delta + \\frac{\\sigma^2_t}{n_t} + \\frac{\\sigma^2_r}{n_r} + \\frac{\\sigma^2_{tr}}{n_t n_r}.$$\nEach coefficient sets the universe-score variance against one of them ([Brennan, 2001](https://doi.org/10.1007/978-1-4757-3456-0)): the **generalizability coefficient** $E\\rho^2 = \\sigma^2_p/(\\sigma^2_p + \\sigma^2_\\delta)$ and the **dependability coefficient** $\\Phi = \\sigma^2_p/(\\sigma^2_p + \\sigma^2_\\Delta)$. Since $\\sigma^2_\\Delta \\ge \\sigma^2_\\delta$, $\\Phi$ is never the larger. Error near a cut score is taken up in [What does a score mean?](score-meaning.qmd).\n\nBoth have the form of reliability in [Classical test theory and reliability](ctt-reliability.qmd), $\\sigma^2_T/(\\sigma^2_T + \\sigma^2_E)$: the \"true\" variance is universe-score variance, $\\sigma^2_p$, what stays with a person across the conditions we generalize over, and the error is what changes from one sample of conditions to another. Fix a facet and the split moves (the interrater section shows how).\n\n#### Try it: the two coefficients side by side\n\nEach bar is one coefficient's denominator: the universe score plus the error it counts; the light pieces count only for Φ. The sliders start at the cleverness estimates from *With real data*; switch to the essays to see raters that differ in severity (there, \"task\" is a rating criterion).\n\n```{ojs}\n//| echo: false\nviewof gpre = Inputs.radio(Object.keys(presets), {value: \"Cleverness ratings\", label: \"Start from\"})\n```\n\n```{ojs}\n//| echo: false\nviewof wv = Inputs.form({\n  p: Inputs.range([0, 1], {value: presets[gpre].p, step: 0.001, label: \"person\"}),\n  t: Inputs.range([0, 1], {value: presets[gpre].t, step: 0.001, label: \"task\"}),\n  r: Inputs.range([0, 1], {value: presets[gpre].r, step: 0.001, label: \"rater\"}),\n  pt: Inputs.range([0, 1], {value: presets[gpre].pt, step: 0.001, label: \"person × task\"}),\n  pr: Inputs.range([0, 1], {value: presets[gpre].pr, step: 0.001, label: \"person × rater\"}),\n  tr: Inputs.range([0, 1], {value: presets[gpre].tr, step: 0.001, label: \"task × rater\"}),\n  res: Inputs.range([0, 1], {value: presets[gpre].res, step: 0.001, label: \"residual\"})\n})\nviewof wn = Inputs.form({\n  nt: Inputs.range([1, 10], {value: presets[gpre].nt, step: 1, label: \"Tasks averaged over\"}),\n  nr: Inputs.range([1, 10], {value: presets[gpre].nr, step: 1, label: \"Raters averaged over\"})\n})\n```\n\n```{ojs}\n//| echo: false\ncb = coefBars(wv, wn.nt, wn.nr)\nPlot.plot({\n  width: 700, height: 190, marginLeft: 150,\n  x: {label: \"Variance (universe score + error)\", grid: true}, y: {label: null, domain: [cb.rel, cb.abs]},\n  color: {legend: true, domain: [\"universe score\", \"relative and absolute error\", \"absolute error only\"],\n          range: [palette.main, palette.contrast, palette.light]},\n  marks: [\n    Plot.barX(cb.rows, {x: \"value\", y: \"coef\", fill: \"role\", stroke: palette.white, title: d => `${d.name}: ${d.value.toFixed(3)}`}),\n    Plot.text(cb.rows, Plot.stackX({x: \"value\", y: \"coef\", text: d => d.value > 0.05 ? d.name : \"\", fill: d => d.role === \"absolute error only\" ? palette.ink : palette.white, fontSize: 10}))\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Averaged over ${wn.nt} task${wn.nt > 1 ? \"s\" : \"\"} and ${wn.nr} rater${wn.nr > 1 ? \"s\" : \"\"}: relative error **${cb.g.rel.toFixed(3)}**, absolute error **${cb.g.abs.toFixed(3)}**; Eρ² **${cb.g.erho2.toFixed(2)}**, Φ **${cb.g.phi.toFixed(2)}**.`\n```\n\nThe coefficients agree when raters and tasks don't differ in harshness or difficulty (cleverness: 0.71 and 0.71) and part when they do (essays, one teacher: 0.47 and 0.40). The interrater section takes up which to report.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In a persons × raters design, raters differ a lot in severity (large $\\\\sigma^2_r$) but agree closely on who is better (small $\\\\sigma^2_{pr}$). Every respondent is scored by the same two raters, and scores are used only to rank respondents. Does rater severity add error to the ranking?\",\n  options: [\n    {text: \"No: a harsh rater lowers everyone's score by the same amount\", correct: true, why: \"When every respondent has the same raters, severity shifts all scores equally and leaves the order alone. It counts for absolute decisions, or when respondents get different raters.\"},\n    {text: \"Yes: $\\\\sigma^2_r$ is large, so the scores are unreliable\", correct: false, why: \"A large $\\\\sigma^2_r$ moves every score together here. What would disturb the ranking is $\\\\sigma^2_{pr}$, raters disagreeing about who is better, and that is small.\"},\n    {text: \"Only if the raters were trained differently\", correct: false, why: \"Training might explain why severity differs, but the question is what severity does to a ranking when raters are crossed with respondents: nothing.\"}\n  ]\n})\n```\n\n\nWhat does the simplest case look like? Keep one facet, items, in a persons × items design. Then $\\sigma^2_\\delta = \\sigma^2_{pi,e}/n_i$ and\n$$E\\rho^2 = \\frac{\\sigma^2_p}{\\sigma^2_p + \\sigma^2_{pi,e}/n_i},$$\nwhich is Cronbach's alpha ([Cronbach, 1951](https://doi.org/10.1007/BF02310555); [Hoyt, 1941](https://doi.org/10.1007/BF02289270), estimated reliability from the same analysis of variance). The callout shows why.\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: why the one-facet coefficient is alpha\n\n**Assumptions:** a persons × items design with $n_p$ persons and $n_i$ items, one score per cell, $X_{pi} = \\mu + \\nu_p + \\nu_i + \\nu_{pi,e}$, with uncorrelated random effects ([Brennan, 2001](https://doi.org/10.1007/978-1-4757-3456-0)).\n\nIn a two-way analysis of variance without replication, $E(MS_p) = \\sigma^2_{pi,e} + n_i\\sigma^2_p$ and $E(MS_{pi,e}) = \\sigma^2_{pi,e}$, so $\\hat\\sigma^2_p = (MS_p - MS_{pi,e})/n_i$, $\\hat\\sigma^2_{pi,e} = MS_{pi,e}$, and\n$$\\widehat{E\\rho^2} = \\frac{\\hat\\sigma^2_p}{\\hat\\sigma^2_p + \\hat\\sigma^2_{pi,e}/n_i} = 1 - \\frac{MS_{pi,e}}{MS_p}.$$\n\n**Why it is alpha.** Write $X_p = \\sum_i X_{pi}$ for a person's total and $X_{\\cdot i}$ for item $i$'s column, and use sample variances with divisor $n_p - 1$. The persons sum of squares is $n_i$ times the sum of squared deviations of person means, so $MS_p = \\text{Var}(X_p)/n_i$. The residual sum of squares is what is left of the total after the person and item parts, $(n_p - 1)\\big[\\sum_i \\text{Var}(X_{\\cdot i}) - \\text{Var}(X_p)/n_i\\big]$, on $(n_p-1)(n_i-1)$ degrees of freedom. So\n$$\\frac{MS_{pi,e}}{MS_p} = \\frac{n_i\\sum_i \\text{Var}(X_{\\cdot i}) - \\text{Var}(X_p)}{(n_i - 1)\\,\\text{Var}(X_p)},$$\nand\n$$1 - \\frac{MS_{pi,e}}{MS_p} = \\frac{n_i}{n_i - 1}\\left(1 - \\frac{\\sum_i \\text{Var}(X_{\\cdot i})}{\\text{Var}(X_p)}\\right) = \\alpha. \\qquad\\blacksquare$$\nThe equality holds exactly in any sample, not only in expectation. Problem 1 asks you to fill in the sums of squares.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A persons × items G study of a 12-item test gives $\\\\sigma^2_p = 0.5$ and $\\\\sigma^2_{pi,e} = 3.0$. What is the relative G coefficient of the 12-item test?\",\n  options: [\n    {text: \"0.67, the number alpha would give\", correct: true, why: \"$0.5/(0.5 + 3.0/12) = 0.5/0.75 = 0.67$. In a one-facet design the relative G coefficient is alpha.\"},\n    {text: \"0.14\", correct: false, why: \"That is one item: $0.5/(0.5 + 3.0)$. The test averages over 12 items, so the interaction is divided by 12.\"},\n    {text: \"0.67, but it is a test-retest reliability, not alpha\", correct: false, why: \"Occasions aren't a facet of this design. The only facet is items, so the coefficient is the internal-consistency one, alpha.\"}\n  ]\n})\n```\n\n### D studies: what would another design buy?\n\nA **decision study** (D study) uses the G study's components to ask what a different design would give for the universe of generalization: which facets are random, and how many conditions of each are averaged over. Change $n_t$ and $n_r$ in the formulas and recompute. With one facet this is Spearman–Brown (problem 1); with two, the components say which lever moves the coefficient more.\n\n#### Try it: a D study\n\nThe components are the ones set in the previous widget. Each line is a number of raters; the horizontal axis is the number of tasks.\n\n```{ojs}\n//| echo: false\nviewof dcoef = Inputs.radio([\"relative\", \"absolute\"], {value: \"relative\", label: \"Coefficient\"})\n```\n\n```{ojs}\n//| echo: false\nd_lines = [1, 2, 3, 5].flatMap(nr => grid(1, 10, 10).map(nt => {\n  const g = gCoef(wv, nt, nr);\n  return {nt, nr: `${nr} rater${nr > 1 ? \"s\" : \"\"}`, g: dcoef === \"relative\" ? g.erho2 : g.phi};\n}))\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Tasks averaged over\", ticks: 10}, y: {label: `${dcoef === \"relative\" ? \"Relative\" : \"Absolute\"} G coefficient`, domain: [0, 1]},\n  color: {legend: true, domain: [\"1 rater\", \"2 raters\", \"3 raters\", \"5 raters\"], range: [palette.light, palette.main, palette.contrast, palette.guide]},\n  marks: [Plot.line(d_lines, {x: \"nt\", y: \"g\", stroke: \"nr\", strokeWidth: 2.5}), Plot.dot(d_lines, {x: \"nt\", y: \"g\", fill: \"nr\", r: 3}),\n          Plot.ruleY([0.8], {stroke: palette.guide, strokeDasharray: \"4 3\"})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Ten tasks with one rater: **${gCoef(wv, 10, 1).erho2.toFixed(2)}** (relative). One task with ten raters: **${gCoef(wv, 1, 10).erho2.toFixed(2)}**. *The cleverness data had 3 tasks and 5 raters, the essays 4 criteria and 1 to 7 teachers per essay: points beyond those are projections, which assume new tasks and raters are exchangeable with the ones observed.*`\n```\n\nWith the cleverness components, ten tasks with one rater reach 0.74, one task with ten raters 0.49: person × task (0.284) dwarfs person × rater (0.053). Switch the previous widget to the essays and raters become the lever. Every curve flattens: past a point only the *other* facet helps.\n\nWhat are we assuming when a D study adds raters we never had, ten when the data had five? That new raters are exchangeable draws from the universe of generalization, disagreeing with the others as much as the old ones did, and that the design stays crossed. Raters from a different pool change $\\sigma^2_r$ and $\\sigma^2_{pr}$; if each respondent gets different raters, severity joins the relative error (next section). And components estimated from a handful of raters make a far projection uncertain (Simulate shows how noisy a facet with three levels is).\n\n### Interrater reliability as a G study\n\nIn a persons × raters design, the setting for **interrater reliability**, the intraclass correlations of [Shrout and Fleiss (1979)](https://doi.org/10.1037/0033-2909.86.2.420) and [McGraw and Wong (1996)](https://doi.org/10.1037/1082-989X.1.1.30) are G coefficients. The **consistency** ICC for one rater, ICC(C,1) in McGraw and Wong's notation, is $\\sigma^2_p/(\\sigma^2_p + \\sigma^2_{pr,e})$, the relative coefficient. The **absolute agreement** ICC, ICC(A,1), is $\\sigma^2_p/(\\sigma^2_p + \\sigma^2_r + \\sigma^2_{pr,e})$, the dependability coefficient. Averaged over $k$ raters, they are the D study for $k$ raters.\n\nWhen raters score the same tasks and the question is only whether another rater would score the same response the same way, the tasks are fixed. [Brennan (2001)](https://doi.org/10.1007/978-1-4757-3456-0) then puts $\\sigma^2_{pt}$ in the universe score: for one rater on one task the coefficient is $(\\sigma^2_p + \\sigma^2_{pt})/(\\sigma^2_p + \\sigma^2_{pt} + \\sigma^2_{pr} + \\sigma^2_{ptr,e})$, the answer to a narrower question than a coefficient that generalizes over tasks too.\n\n#### Try it: consistency and agreement\n\nForty simulated respondents, two raters. Rater B is harsher by a constant; both add rating noise.\n\n```{ojs}\n//| echo: false\nviewof ic_h = Inputs.range([0, 2], {value: 1, step: 0.1, label: \"How much harsher rater B is\"})\nviewof ic_n = Inputs.range([0.1, 1.5], {value: 0.5, step: 0.05, label: \"Rating noise (SD)\"})\n```\n\n```{ojs}\n//| echo: false\nic = twoRaters({seed: 76, n: 40, harsh: ic_h, noise: ic_n})\nPlot.plot({\n  width: 420, height: 420, aspectRatio: 1,\n  x: {label: \"Rater A\", domain: [-5, 5]}, y: {label: \"Rater B\", domain: [-5, 5]},\n  marks: [Plot.line([[-5, -5], [5, 5]], {stroke: palette.guide, strokeDasharray: \"4 3\"}),\n          Plot.dot(ic.pts, {x: \"a\", y: \"b\", r: 3.5, fill: palette.main, fillOpacity: 0.7})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Consistency ICC(C,1): **${ic.consistency.toFixed(2)}**. Absolute agreement ICC(A,1): **${ic.agreement.toFixed(2)}**. Pearson correlation: ${ic.r.toFixed(2)}. Rater B scores ${ic.meanGap.toFixed(2)} lower on average.`\n```\n\nAt the starting values consistency is 0.84 and agreement 0.62: the points lie along a line, below the dashed line of equal ratings. At harshness 0 the two meet; at 2 agreement falls to 0.35 while consistency stays at 0.84. Agreement charges for the gap.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Rater B gives every essay exactly one point less than rater A. What are the two single-rater ICCs?\",\n  options: [\n    {text: \"Consistency 1; agreement below 1\", correct: true, why: \"One rater's scores are a shift of the other's, so $\\\\sigma^2_{pr,e} = 0$ and consistency is perfect. The shift is rater variance, which only the agreement ICC counts.\"},\n    {text: \"Both 1\", correct: false, why: \"The raters never give the same score, so they don't agree. Agreement counts the one-point gap as error.\"},\n    {text: \"Consistency below 1; agreement 1\", correct: false, why: \"It is the other way round: agreement is the stricter of the two, since its error term includes rater severity.\"}\n  ]\n})\n```\n\nWhich should you report? If every respondent has the same raters and only the order matters, severity cancels. If scores are compared with a fixed standard, or respondents have different raters (each essay its own teachers, a nested design), a harsh rater lowers some scores and not others, and rater variance is error even for ranking ([Brennan, 2001](https://doi.org/10.1007/978-1-4757-3456-0)). In the case that raters vary across respondents or a cut is involved, the absolute coefficient, $\\Phi$ or the agreement ICC, may be the one to report; for a fully crossed design whose scores are used only to rank, the consistency coefficient may be sufficient for some purposes.\n\n## Simulate\n\nThe code generates a persons × tasks × raters design with known variance components (150 persons, 3 tasks, 3 raters, loosely like the cleverness ratings), fits the crossed model with `lme4`, and compares the estimates and G coefficients with the truth. Loading `lme4` takes 10 to 20 seconds the first time the page runs code; the fit, about two.\n\nWith the seed as written, the person components come back close (person 0.346 against 0.30; person × task 0.317 against 0.30), and so does the relative coefficient (0.692 against 0.668). The task component does not (0.065 against 0.02): its variance is estimated from three numbers, however many persons there are. Set `nt <- 10` and the coefficient rises to 0.842; put it back and set `nr <- 10`, and it rises only to 0.723.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-17\n# Simulate a persons x tasks x raters G study with known variance components,\n# estimate them with lme4, and compare. Runs in the browser in about ten seconds.\nlibrary(lme4)\nset.seed(57)\n\nnp <- 150   # persons\nnt <- 3     # tasks\nnr <- 3     # raters\n\n# True variance components (these add to 1, so each is also a share of the total).\ntruth <- c(p = 0.30, t = 0.02, r = 0.03, pt = 0.30, pr = 0.05, tr = 0.01, ptr = 0.29)\n\nd <- expand.grid(p = factor(1:np), t = factor(1:nt), r = factor(1:nr))\neff <- function(f, v) rnorm(nlevels(f), 0, sqrt(v))[f]\nd$y <- 3 +\n  eff(d$p, truth[\"p\"]) + eff(d$t, truth[\"t\"]) + eff(d$r, truth[\"r\"]) +\n  eff(interaction(d$p, d$t), truth[\"pt\"]) +\n  eff(interaction(d$p, d$r), truth[\"pr\"]) +\n  eff(interaction(d$t, d$r), truth[\"tr\"]) +\n  rnorm(nrow(d), 0, sqrt(truth[\"ptr\"]))\n\n# One random intercept per facet and per interaction; the residual is p x t x r.\nfit <- lmer(y ~ 1 + (1 | p) + (1 | t) + (1 | r) + (1 | p:t) + (1 | p:r) + (1 | t:r),\n            data = d)\nvc <- as.data.frame(VarCorr(fit))\nest <- setNames(vc$vcov, c(p = \"p\", t = \"t\", r = \"r\", \"p:t\" = \"pt\", \"p:r\" = \"pr\",\n                           \"t:r\" = \"tr\", Residual = \"ptr\")[vc$grp])[names(truth)]\nprint(round(cbind(true = truth, estimated = est), 3))\n\n# G coefficients for a D study with n_t tasks and n_r raters.\ng_coef <- function(v, n_t, n_r) {\n  rel <- v[\"pt\"] / n_t + v[\"pr\"] / n_r + v[\"ptr\"] / (n_t * n_r)\n  abs <- rel + v[\"t\"] / n_t + v[\"r\"] / n_r + v[\"tr\"] / (n_t * n_r)\n  c(relative = unname(v[\"p\"] / (v[\"p\"] + rel)), absolute = unname(v[\"p\"] / (v[\"p\"] + abs)))\n}\ncat(\"\\nG coefficients with\", nt, \"tasks and\", nr, \"raters\\n\")\nprint(round(rbind(true = g_coef(truth, nt, nr), estimated = g_coef(est, nt, nr)), 3))\n\n```\n:::\n\n\n[Download this code](code/g-theory-sim.R).\n\n## With real data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(lme4)\noptions(digits = 7, scipen = 5)  # R's default digits, in case a .Rprofile changes it; no e-notation\n# Variance components from a crossed random-effects fit, with their shares of the\n# total. `labels` renames lme4's grouping factors (id, item, rater and their\n# interactions) to the facets of the design.\ncomponents <- function(fit, labels) {\n  vc <- as.data.frame(VarCorr(fit))\n  v <- setNames(vc$vcov, labels[vc$grp])[labels]\n  data.frame(variance = round(v, 3), percent = round(100 * v / sum(v), 1))\n}\n# G coefficients for a D study that averages over n_i levels of the first facet\n# (tasks, or criteria) and n_r raters. v holds the seven components in the order\n# p, i, r, pi, pr, ir, residual.\ng_coef <- function(v, n_i, n_r) {\n  rel <- v[4] / n_i + v[5] / n_r + v[7] / (n_i * n_r)\n  abs <- rel + v[2] / n_i + v[3] / n_r + v[6] / (n_i * n_r)\n  c(relative = v[1] / (v[1] + rel), absolute = v[1] / (v[1] + abs))\n}\nlabels <- c(id = \"person\", item = \"task\", rater = \"rater\", \"id:item\" = \"person x task\",\n            \"id:rater\" = \"person x rater\", \"item:rater\" = \"task x rater\",\n            Residual = \"residual (p x t x r, e)\")\nform <- resp ~ 1 + (1 | id) + (1 | item) + (1 | rater) +\n  (1 | id:item) + (1 | id:rater) + (1 | item:rater)\n```\n:::\n\n\n### Cleverness ratings: tasks or raters?\n\nThe main example is [Forthmann-2024-cleverness_ratings](https://itemresponsewarehouse.org/tables/forthmann-2024-cleverness_ratings/), released by [Forthmann and Myszkowski (2024)](https://osf.io/a9qnc) for a special issue of the *Journal of Intelligence* (CC BY 4.0; [Forthmann et al., 2017](https://doi.org/10.1080/10400419.2017.1360059), is an earlier analysis). Respondents listed unusual uses for three objects (the alternate uses task), and five raters rated each list for cleverness, stored as 1 to 5, higher meaning cleverer ([Silvia et al., 2008](https://doi.org/10.1037/1931-3896.2.2.68), study the reliability of such ratings). [Download the code](code/g-theory-irw.R); it needs `lme4`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_2:v22_0.Forthmann-2024-cleverness_ratings/rows?format=csv\"\ncl <- read.csv(url)[, c(\"id\", \"item\", \"rater\", \"resp\")]\nc(respondents = length(unique(cl$id)), tasks = length(unique(cl$item)),\n  raters = length(unique(cl$rater)), ratings = nrow(cl),\n  missing = length(unique(cl$id)) * 3 * 5 - nrow(cl))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents       tasks      raters     ratings     missing \n        202           3           5        3020          10 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(cl$resp)   # cleverness, 1 to 5; higher = cleverer\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   1    2    3    4    5 \n 150  815 1115  760  180 \n```\n\n\n:::\n:::\n\n\nTen ratings are missing, all for one respondent; `lmer` handles the imbalance.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nfit_cl <- lmer(form, data = cl)\nvc_cl <- components(fit_cl, labels)\nvc_cl\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                        | variance| percent|\n|:-----------------------|--------:|-------:|\n|person                  |    0.310|    32.1|\n|task                    |    0.000|     0.0|\n|rater                   |    0.020|     2.1|\n|person x task           |    0.284|    29.4|\n|person x rater          |    0.053|     5.5|\n|task x rater            |    0.012|     1.2|\n|residual (p x t x r, e) |    0.286|    29.6|\n\n</div>\n:::\n:::\n\n\nPeople differ (person, 32.1% of the variance of one rating), but person × task is nearly as large (29.4%): being clever with a rope says only so much about being clever with a paperclip. Raters account for little: 2.1% for severity and 5.5% for disagreement about who is cleverer. The task component is estimated at zero, so the three objects are about equally hard to be clever with. How much did REML matter? Refit by plain maximum likelihood:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# REML against plain maximum likelihood, for the two facets with few levels.\nfit_ml <- lmer(form, data = cl, REML = FALSE)   # warns of a singular fit: task is 0\nfacet_var <- function(fit) {\n  v <- as.data.frame(VarCorr(fit))\n  setNames(v$vcov, v$grp)[c(\"item\", \"rater\")]\n}\nround(rbind(REML = facet_var(fit_cl), ML = facet_var(fit_ml)), 4)   # item = task\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       item  rater\nREML 0.0004 0.0199\nML   0.0000 0.0163\n```\n\n\n:::\n:::\n\n\nWith five raters, maximum likelihood puts rater severity at about four-fifths of the REML value, the downward bias REML removes.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"The design as run uses 3 tasks and 5 raters: 15 ratings per respondent. Suppose instead each respondent did 6 tasks, each scored by one rater: 6 ratings. What happens to the relative G coefficient?\",\n  choices: [\"It falls a lot\", \"It falls a little\", \"It rises\"],\n  answer: \"It falls a little\",\n  reveal: \"From 0.71 to 0.68, with fewer than half the ratings. Person × task (29.4% of a single rating's variance) is far larger than person × rater (5.5%), so tasks buy more than raters.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nv_cl <- vc_cl$variance\nround(g_coef(v_cl, 3, 5), 2)     # the design as run: 3 tasks, 5 raters\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrelative absolute \n    0.71     0.71 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(g_coef(v_cl, 3, 1), 2)     # 3 tasks, 1 rater\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrelative absolute \n    0.56     0.54 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(g_coef(v_cl, 6, 1), 2)     # 6 tasks, 1 rater\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrelative absolute \n    0.68     0.65 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(g_coef(v_cl, 3, 1e6), 2)   # 3 tasks, as many raters as you like\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrelative absolute \n    0.77     0.77 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nd_grid <- expand.grid(tasks = 1:10, raters = c(1, 2, 5))\nd_grid$relative <- mapply(function(t, r) g_coef(v_cl, t, r)[1], d_grid$tasks, d_grid$raters)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ncols <- c(\"1\" = \"#93c5fd\", \"2\" = \"#2780e3\", \"5\" = \"#c2410c\")\nplot(NULL, xlim = c(1, 10), ylim = c(0, 1), xlab = \"Tasks averaged over\",\n     ylab = \"Relative G coefficient\", las = 1, main = \"Cleverness ratings: a D study\")\nfor (r in c(1, 2, 5)) with(d_grid[d_grid$raters == r, ],\n                           lines(tasks, relative, type = \"b\", pch = 19, lwd = 2, col = cols[as.character(r)]))\nabline(h = 0.8, col = \"#999\", lty = 2)\nlegend(\"bottomright\", paste(c(1, 2, 5), c(\"rater\", \"raters\", \"raters\")), col = cols,\n       lwd = 2, pch = 19, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](g-theory_files/figure-html/plot-clever-1.png){width=672}\n:::\n:::\n\n\nThe design as run, 3 tasks and 5 raters, has a relative G coefficient of 0.71. One rater gives 0.56, but one rater with 6 tasks gives 0.68: 6 ratings per respondent instead of 15, for nearly the same coefficient. No number of raters takes 3 tasks past 0.77, the ceiling set by person × task. For this construct and these raters, the money goes on tasks. The absolute coefficient equals the relative one to two decimals (0.71), since the task and rater components are small.\n\nIf the tasks are fixed instead, as in the interrater coefficient of [Brennan (2001)](https://doi.org/10.1007/978-1-4757-3456-0), person × task joins the universe score:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Interrater reliability with the tasks fixed: raters score the same tasks, so the\n# person x task effect is part of the universe score. One rater, one task:\nround(c(tasks_fixed = (v_cl[1] + v_cl[4]) / (v_cl[1] + v_cl[4] + v_cl[5] + v_cl[7]),\n        tasks_random = unname(g_coef(v_cl, 1, 1)[1])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n tasks_fixed tasks_random \n        0.64         0.33 \n```\n\n\n:::\n:::\n\n\nA second rater would score the same list much as the first did (0.64), but a respondent's cleverness with one object says much less about their cleverness in general (0.33). Same ratings, two universes.\n\n### Essays: when raters matter\n\nThe contrast is [teacherjudgements_lohmann_2026_essayratings](https://itemresponsewarehouse.org/tables/teacherjudgements_lohmann_2026_essayratings/), from a study in which preservice English teachers rated essays by learners of English as a second language ([Lohmann et al., 2026](https://doi.org/10.1037/edu0000969); CC BY 4.0). Each teacher rated five essays on four criteria (language quality, structure, content, and a holistic rating), from 1 (very low quality) to 7 (very high quality). \"Person\" in the output now means essay, and criteria take the place of tasks. We set aside the table's expert benchmark scores.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_4:v7_0.teacherjudgements_lohmann_2026_essayratings/rows?format=csv\"\nes <- read.csv(url)\n# The table also holds an expert benchmark score for every essay and criterion;\n# the G study is about the teachers, so set it aside.\nes <- es[es$rater != \"expert_benchmark\", c(\"id\", \"item\", \"rater\", \"resp\")]\nc(essays = length(unique(es$id)), criteria = length(unique(es$item)),\n  teachers = length(unique(es$rater)), ratings = nrow(es))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  essays criteria teachers  ratings \n     881        4      315     6300 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(es$resp)   # 1 (very low quality) to 7 (very high quality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   1    2    3    4    5    6    7 \n 280  842 1142 1383 1310  948  395 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npairs <- unique(es[, c(\"id\", \"rater\")])\ntable(table(pairs$rater))   # essays per teacher\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  5 \n315 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(table(pairs$id))      # teachers per essay\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3   4   5   6   7 \n435 270 126  34  11   4   1 \n```\n\n\n:::\n:::\n\n\nThis design is sparse. Every teacher rated 5 essays, but 435 of the 881 essays were rated by a single teacher, and only 50 by four or more. Each essay has its own teachers, so raters are effectively nested within essays, though each teacher's five essays link the teachers to one another.\n\nHow does the fit handle the essay–teacher pairs never observed? Nothing is filled in. REML uses only the ratings that exist and learns each component where ratings overlap: a teacher's severity from how their five essays fare against other ratings of those essays, essay × rater from essays that two or more teachers read, essay × criterion from the four criteria of every rating. An essay read by one teacher informs the essay and criterion components but can't, alone, separate that teacher's view of it from the essay itself.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The default optimizer stops just short of lme4's convergence tolerance on this\n# fit; bobyqa converges and gives the same estimates to three decimals.\nfit_es <- lmer(form, data = es, control = lmerControl(optimizer = \"bobyqa\"))\nvc_es <- components(fit_es, sub(\"t x r\", \"c x r\", sub(\"task\", \"criterion\", labels)))\nvc_es\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                        | variance| percent|\n|:-----------------------|--------:|-------:|\n|person                  |    0.754|    29.7|\n|criterion               |    0.010|     0.4|\n|rater                   |    0.246|     9.7|\n|person x criterion      |    0.243|     9.6|\n|person x rater          |    0.640|    25.2|\n|criterion x rater       |    0.047|     1.8|\n|residual (p x c x r, e) |    0.602|    23.7|\n\n</div>\n:::\n:::\n\n\nThe picture reverses. Teachers differ in severity (rater, 9.7% of the variance, against 2.1% in the cleverness ratings), and essay × rater is 25.2%, against the essays' own 29.7%: teachers disagree about which essays are better. Criteria matter less (essay × criterion, 9.6%). Since each teacher rated an essay on all four criteria, essay × rater is an impression that carries across them, the pattern a halo effect (named in Lohmann et al.'s title) would produce. Teachers' severity has an SD of 0.50 points, against 0.87 for essays' universe scores.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nv_es <- vc_es$variance\nsapply(c(1, 2, 3, 5), function(r) round(g_coef(v_es, 4, r), 2))   # 4 criteria, 1-5 raters\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1] [,2] [,3] [,4]\nrelative 0.47 0.62 0.70 0.78\nabsolute 0.40 0.56 0.65 0.73\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(g_coef(v_es, 1e6, 1), 2)    # one rater, as many criteria as you like\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrelative absolute \n    0.54     0.46 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(sqrt(v_es[c(1, 3)]), 2)     # SD of essays' universe scores; SD of teachers' severity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.87 0.50\n```\n\n\n:::\n:::\n\n\nWith one teacher and four criteria, the relative coefficient is 0.47 and the absolute 0.40. A second teacher brings them to 0.62 and 0.56; five, to 0.78 and 0.73. One teacher on unlimited criteria reaches only 0.54: the lever is raters. Since each essay had its own teachers, the absolute coefficient describes these scores.\n\n#### A check: the balanced subset\n\nIs the sparse fit believable? Part of the data is balanced: the essays rated by exactly three teachers, each on all four criteria.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# A balanced part of the essay data: the essays rated by exactly three teachers,\n# each on all four criteria. Treating each essay's teachers as its own (raters\n# nested within essays) makes the design (r:p) x c, the classic balanced case.\nn_teach <- table(pairs$id)\nbal <- es[es$id %in% names(n_teach)[n_teach == 3], ]\nc(essays = length(unique(bal$id)), teachers = length(unique(bal$rater)), ratings = nrow(bal))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  essays teachers  ratings \n     126      241     1512 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(table(bal$id))   # ratings per essay: 3 teachers x 4 criteria = 12 for every essay\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 12 \n126 \n```\n\n\n:::\n:::\n\n\nTreating each essay's teachers as its own gives the design $(r{:}p) \\times t$ (criteria as $t$), with five components: essay, criterion, rater within essay, essay × criterion and the residual. The classic route works here: compute the mean squares and solve the expected-mean-squares equations (the callout gives them).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The classic route, by hand: sums of squares, mean squares, then the\n# expected-mean-squares equations solved for the five components (see the callout).\n# ave() returns each row's group mean, so the sums run over all ratings.\nn_p <- length(unique(bal$id)); n_r <- 3; n_c <- 4\nm    <- mean(bal$resp)\nm_p  <- ave(bal$resp, bal$id)                 # essay means\nm_c  <- ave(bal$resp, bal$item)               # criterion means\nm_rp <- ave(bal$resp, bal$id, bal$rater)      # teacher-within-essay means\nm_pc <- ave(bal$resp, bal$id, bal$item)       # essay x criterion means\nss <- c(p = sum((m_p - m)^2), c = sum((m_c - m)^2), \"r:p\" = sum((m_rp - m_p)^2),\n        pc = sum((m_pc - m_p - m_c + m)^2), \"rc:p,e\" = sum((bal$resp - m_rp - m_pc + m_p)^2))\ndf <- c(n_p - 1, n_c - 1, n_p * (n_r - 1), (n_p - 1) * (n_c - 1), n_p * (n_r - 1) * (n_c - 1))\nms <- ss / df\nround(cbind(df, ms), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        df     ms\np      125 14.251\nc        3 10.110\nr:p    252  4.205\npc     375  1.340\nrc:p,e 756  0.597\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nv_anova <- c(essay = (ms[[\"p\"]] - ms[[\"r:p\"]] - ms[[\"pc\"]] + ms[[\"rc:p,e\"]]) / (n_r * n_c),\n             criterion = (ms[[\"c\"]] - ms[[\"pc\"]]) / (n_p * n_r),\n             \"rater within essay\" = (ms[[\"r:p\"]] - ms[[\"rc:p,e\"]]) / n_c,\n             \"essay x criterion\" = (ms[[\"pc\"]] - ms[[\"rc:p,e\"]]) / n_r,\n             residual = ms[[\"rc:p,e\"]])\n```\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: expected mean squares for raters nested within essays\n\n**Assumptions:** $n_p$ essays, each rated by its own $n_r$ raters on the same $n_t$ criteria, one rating per cell, $X_{prt} = \\mu + \\nu_p + \\nu_t + \\nu_{r:p} + \\nu_{pt} + \\nu_{rt:p,e}$, with uncorrelated random effects ([Brennan, 2001](https://doi.org/10.1007/978-1-4757-3456-0)). Here $\\sigma^2_{r:p} = \\sigma^2_r + \\sigma^2_{pr}$ and $\\sigma^2_{rt:p,e} = \\sigma^2_{rt} + \\sigma^2_{prt,e}$ from the crossed design.\n\n$$\\begin{aligned}\nE(MS_p) &= \\sigma^2_{rt:p,e} + n_t\\sigma^2_{r:p} + n_r\\sigma^2_{pt} + n_r n_t\\sigma^2_p\\\\\nE(MS_t) &= \\sigma^2_{rt:p,e} + n_r\\sigma^2_{pt} + n_p n_r\\sigma^2_t\\\\\nE(MS_{r:p}) &= \\sigma^2_{rt:p,e} + n_t\\sigma^2_{r:p}\\\\\nE(MS_{pt}) &= \\sigma^2_{rt:p,e} + n_r\\sigma^2_{pt}\\\\\nE(MS_{rt:p,e}) &= \\sigma^2_{rt:p,e}\n\\end{aligned}$$\n\nSet each mean square equal to its expectation and solve from the bottom up: $\\hat\\sigma^2_{rt:p,e} = MS_{rt:p,e}$, $\\hat\\sigma^2_{pt} = (MS_{pt} - MS_{rt:p,e})/n_r$, $\\hat\\sigma^2_{r:p} = (MS_{r:p} - MS_{rt:p,e})/n_t$, $\\hat\\sigma^2_t = (MS_t - MS_{pt})/(n_p n_r)$, and $\\hat\\sigma^2_p = (MS_p - MS_{r:p} - MS_{pt} + MS_{rt:p,e})/(n_r n_t)$. These are the lines of `v_anova`, which writes `c` for criteria. Some teachers read more than one of these essays; the nested analysis ignores that and treats each essay's three as its own.\n:::\n\nNow the same design by REML, next to the full sparse fit with its components combined to match (rater within essay is rater plus essay × rater; the residual absorbs criterion × rater):\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same design by REML: id:rater is a teacher within an essay.\nfit_bal <- lmer(resp ~ 1 + (1 | id) + (1 | item) + (1 | id:rater) + (1 | id:item), data = bal)\nvb <- as.data.frame(VarCorr(fit_bal))\nv_reml <- setNames(vb$vcov, vb$grp)[c(\"id\", \"item\", \"id:rater\", \"id:item\", \"Residual\")]\n# The full sparse fit, its seven components combined to match the nested design:\n# rater within essay = rater + essay x rater; residual = criterion x rater + residual.\nvf <- as.data.frame(VarCorr(fit_es))\nvf <- setNames(vf$vcov, vf$grp)\nv_full <- c(vf[[\"id\"]], vf[[\"item\"]], vf[[\"rater\"]] + vf[[\"id:rater\"]], vf[[\"id:item\"]],\n            vf[[\"item:rater\"]] + vf[[\"Residual\"]])\nround(cbind(ANOVA = v_anova, REML = v_reml, \"full sparse fit\" = v_full), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   ANOVA  REML full sparse fit\nessay              0.775 0.775           0.754\ncriterion          0.023 0.023           0.010\nrater within essay 0.902 0.902           0.886\nessay x criterion  0.248 0.248           0.243\nresidual           0.597 0.597           0.648\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsignif(max(abs(v_anova - v_reml)), 2)   # largest gap between ANOVA and REML\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.000014\n```\n\n\n:::\n:::\n\n\nANOVA and REML agree to the third decimal: in a balanced design with no negative estimate, REML is the ANOVA solution. The full sparse fit is close: essay 0.754 against 0.775, rater within essay 0.886 against 0.902, residual 0.648 against 0.597. The gaps have three sources: a different set of essays (126 of 881, picked by how many teachers they got); a small sample, so noisy estimates (criterion, from four levels, most of all: 0.010 against 0.023); and a design that can't split rater within essay into severity and essay × rater, as the full fit can. Where the data allow the classical estimate, REML on the sparse design gives much the same answer.\n\nThe two tables call for different designs, and only their variance components could say so.\n\n## Problems\n\n1. **Derivation.** Fill in the sums of squares in the Go deeper callout to show that $1 - MS_{pi,e}/MS_p$ is alpha. Then show that the D-study coefficient for $m n_i$ items is the Spearman–Brown formula with multiplier $m$.\n2. **Real data with a twist.** From the cleverness components, find the combinations of tasks and raters that give a relative G coefficient of at least 0.8. Is there more than one? If a task costs a respondent five minutes and a rating costs a rater one minute per respondent, which design is cheapest for 200 respondents? Does the answer change for $\\Phi$?\n3. **Judgment: a sparse design.** Refit the essay model using only essays with at least two teachers. Which components change, and how do they compare with the balanced subset's? Suppose every essay had one teacher: which components could the data no longer separate, and what would that do to your D study?\n4. **Design.** Plan a G study for a performance assessment you know. What should the score generalize over? Name the facets, random or fixed, crossed or nested, and choose sample sizes. Which component do you expect to be largest?\n5. **Real data: two raters.** In the cleverness data, take raters 1 and 2 and the paperclip task. Compute the consistency and agreement ICCs from a `lmer` fit with random intercepts for respondent and rater. Which pair of raters agrees least?\n6. **Challenge (open).** G theory treats a harsh rater as a random effect to be averaged away. When should severity be estimated and adjusted for instead, and what would you need to know about the essays' teachers to decide? ([Rater models](rater-models.qmd) takes this up with the many-facet Rasch model.)\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Many%20sources%20of%20error%3A%20generalizability%20theory%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20generalizability%20theory%3A%20facets%20and%20universe%20scores%2C%20variance%20components%20for%20a%20persons%20x%20tasks%20x%20raters%20design%20estimated%20as%20crossed%20random%20effects%20with%20lme4%20%28and%2C%20for%20a%20balanced%20subset%20with%20raters%20nested%20within%20essays%2C%20by%20expected%20mean%20squares%29%2C%20relative%20and%20absolute%20error%20and%20the%20two%20G%20coefficients%20%28with%20the%20one-facet%20coefficient%20equal%20to%20Cronbach%27s%20alpha%20and%20an%20expected-mean-squares%20derivation%29%2C%20D%20studies%2C%20and%20interrater%20reliability%20as%20a%20G%20study%20%28consistency%20and%20agreement%20ICCs%29%2C%20with%20cleverness%20ratings%20of%20alternate-uses%20responses%20and%20teachers%27%20ratings%20of%20essays%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Shavelson, R. J., & Webb, N. M. (1991). *Generalizability theory: A primer*. Sage. No DOI; see [Sundre's (1993) review](https://doi.org/10.1177/109821409301400219). The most accessible first read, at book length.\n- Brennan, R. L. (2001). *Generalizability theory*. Springer. <https://doi.org/10.1007/978-1-4757-3456-0>. The reference: designs, nested and fixed facets, estimation and D studies, at book length.\n- Shavelson, R. J., Webb, N. M., & Rowley, G. L. (1989). Generalizability theory. *American Psychologist*, 44(6), 922–932. <https://doi.org/10.1037/0003-066X.44.6.922>. A short overview.\n- Brennan, R. L. (2000). Performance assessments from the perspective of generalizability theory. *Applied Psychological Measurement*, 24(4), 339–353. <https://doi.org/10.1177/01466210022031796>. Which facets matter for performance assessments, and how popular reliability estimates for them, interrater reliability among them, look from G theory.\n- Brennan, R. L. (1992). Generalizability theory. *Educational Measurement: Issues and Practice*, 11(4), 27–34. <https://doi.org/10.1111/j.1745-3992.1992.tb00260.x>. An instructional module on G and D studies.\n- Cronbach, L. J., Gleser, G. C., Nanda, H., & Rajaratnam, N. (1972). *The dependability of behavioral measurements: Theory of generalizability for scores and profiles*. Wiley. No DOI; see [Bock's (1972) review](https://doi.org/10.1126/science.178.4067.1275). The book-length statement of the theory.\n- Cronbach, L. J., Rajaratnam, N., & Gleser, G. C. (1963). Theory of generalizability: A liberalization of reliability theory. *British Journal of Statistical Psychology*, 16(2), 137–163. <https://doi.org/10.1111/j.2044-8317.1963.tb00206.x>. Where the theory starts.\n- McGraw, K. O., & Wong, S. P. (1996). Forming inferences about some intraclass correlation coefficients. *Psychological Methods*, 1(1), 30–46. <https://doi.org/10.1037/1082-989X.1.1.30>. The ICCs, sorted by design and by consistency versus agreement.\n- Bates, D., Mächler, M., Bolker, B., & Walker, S. (2015). Fitting linear mixed-effects models using lme4. *Journal of Statistical Software*, 67(1). <https://doi.org/10.18637/jss.v067.i01>. How `lmer` specifies and fits crossed random effects.\n- Eckes, T. (2011). *Introduction to many-facet Rasch measurement*. Peter Lang. <https://doi.org/10.3726/978-3-653-04844-5>. Raters as a facet in an item response model, which estimates each rater's severity and adjusts scores for it; [Rater models](rater-models.qmd) develops it on this lesson's two tables.\n- De Boeck, P. (2008). Random item IRT models. *Psychometrika*, 73(4), 533–559. <https://doi.org/10.1007/s11336-008-9092-x>. Items as random effects in an item response model, an idea [What is an item?](explanatory-irt.qmd) takes further.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`Forthmann-2024-cleverness_ratings`](https://itemresponsewarehouse.org/tables/forthmann-2024-cleverness_ratings/): Forthmann, Boris, and Nils Myszkowski. 2024. “Analysis of a Divergent Thinking Dataset.” OSF. April 22. osf.io/a9qnc. <https://doi.org/No DOI>. Licence: CC BY 4.0.\n- [`teacherjudgements_lohmann_2026_essayratings`](https://itemresponsewarehouse.org/tables/teacherjudgements_lohmann_2026_essayratings/): Lohmann, J. F., Lötscher, F., Junge, F., Keller, S., Jansen, T., Fleckenstein, J., & Möller, J. (2026). Testing teacher judgments comprehensively: Accuracy, halo, frame of reference, strategy, and personality effects in holistic and analytic assessments of student essays.Journal of Educational Psychology, 118(6), 941–960. <https://doi.org/10.1037/edu0000969>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** new material, not in EDUC 252. The course's landscape analysis (`notes/landscape-2026-09-24.md`, gap 2) put G theory and interrater reliability into one lesson.\n- **Estimation (#76):** the main line estimates variance components with `lme4` (REML); the ANOVA / expected-mean-squares route appears twice, in the Go deeper on alpha and in the balanced essay subset, where it matches REML. Comments on #76 asked for what the score generalizes over, the assumptions behind D-study projections, Brennan's interrater coefficient with tasks fixed, observed-score versus latent-trait theories, the universe of generalization, crossed versus nested designs, and how the sparse essay design is handled; those are in this version.\n- **Timing:** about 50 minutes for the core ideas and widgets; the two real-data analyses work as a 25-minute lab (the essay fit takes about half a minute in local R).\n- **Held back:** nested designs appear only in the balanced essay subset, and fixed facets only in the interrater coefficient (see Shavelson & Webb, 1991, and Brennan, 2001); multivariate G theory is not covered. Raters in item response models (many-facet Rasch) are left to [Rater models](rater-models.qmd); random item effects to [What is an item?](explanatory-irt.qmd); error near a cut to [What does a score mean?](score-meaning.qmd); occasions as a facet to [Measurement invariance under treatment and life events](invariance-experience.qmd).\n- **Solutions:** held back in `solutions/g-theory.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "g-theory_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}