{
  "hash": "e3fed3231bdca4441ad7bb0088f7c5c7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Where CTT breaks: toward item response models\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Classical test theory  \n**Tranche:** core (a first course)  \n**Before this:** [Classical test theory and reliability](ctt-reliability.qmd) · [The likelihood and logistic regression](likelihood.qmd)  \n**Builds toward:** [The Rasch model](rasch.qmd)  \n**Starts threads:** The sum score contains the item (→ [The Rasch model](rasch.qmd)); Item curves rise with the sum score (monotonicity) (→ [The Rasch model](rasch.qmd) · [Unfolding models](unfolding.qmd)); The sum score depends on which items were taken (→ [The Rasch model](rasch.qmd) · [Linking and equating](equating.qmd))  \n**Picks up threads:** Alpha is a lower bound on reliability (from [Classical test theory and reliability](ctt-reliability.qmd))  \n**IRW tables:** [`4thgrade_math_sirt`](https://itemresponsewarehouse.org/tables/4thgrade_math_sirt/), [`andrich_mudfold`](https://itemresponsewarehouse.org/tables/andrich_mudfold/)  \n**From EDUC 252:** slides c2; problem sets PS2#4, PS2#5; code [`ps2/ctt_failures.R`](https://github.com/ben-domingue/252/blob/main/ps2/ctt_failures.R), [`ps2/towards_irt.R`](https://github.com/ben-domingue/252/blob/main/ps2/towards_irt.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n```{ojs}\n//| echo: false\nimport {rng, cor, grid, logistic, kr20, sampleWeighted, logisticFit, palette} from \"./widgets/irt.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\n[Classical test theory and reliability](ctt-reliability.qmd) ended on a caveat: CTT is a model for the test score, $X = T + E$, and says nothing about how anyone answers a single item. For many jobs that is all we need. This lesson looks at two places where it isn't. The first is alpha. It is computed from item responses, yet the model behind it is silent about items, and a simulation that obeys $X = T + E$ exactly can put alpha far from the reliability built into it. The second is the items themselves. Plot the proportion correct on each item against the sum score and the curves differ: they rise at different points and at different rates, they bend, and a few don't rise at all. Swap the sum score in that picture for an unobserved ability and you have the item response model of [the next lesson](rasch.qmd).\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- explain why responses that are coin flips have an alpha near zero, however many items there are;\n- explain why alpha depends on assumptions about items that $X = T + E$ doesn't make, and show it with a simulation;\n- draw item curves (proportion correct against the sum score) and read an item's difficulty and discrimination from them;\n- fit a logistic regression of one item on the sum score and interpret its intercept and slope;\n- recognize an item whose curve doesn't rise with the score, and say what it means for keying and for the sum score;\n- say when the sum score and CTT are a reasonable choice.\n\n## Core ideas\n\n### Coin flips have no reliability\n\nSuppose every response on a test were a coin flip. What would alpha be? Recall the formula: for $k$ items,\n$$\\alpha = \\frac{k}{k-1}\\left(1 - \\frac{\\sum_i \\sigma^2_i}{\\sigma^2_X}\\right)$$\n([Cronbach, 1951](https://doi.org/10.1007/BF02310555)), which for 0/1 items is KR-20 ([Kuder & Richardson, 1937](https://doi.org/10.1007/BF02288391)). If the flips are independent, the variance of the total is the sum of the item variances, and alpha is about 0, however long the test.\n\nWhat would it take for alpha to rise? The items would have to share something. So give each respondent a coin of their own. With the last slider at 0, every coin is fair. Move it up and the coins become biased by different amounts, so that some respondents come up \"correct\" more often than others. A respondent's coin is now a true score: every item they answer shares it, and it differs from one respondent to the next. The dashed line is the reliability that spread implies; each dot is alpha from one simulated test.\n\n#### Try it: a test made of coins\n\n```{ojs}\n//| echo: false\nviewof cf_k = Inputs.range([5, 100], {value: 20, step: 5, label: \"Items\"})\nviewof cf_n = Inputs.range([50, 1000], {value: 200, step: 50, label: \"Respondents\"})\nviewof cf_s = Inputs.range([0, 1], {value: 0, step: 0.05, label: \"Spread of the coins\"})\n```\n\n```{ojs}\n//| echo: false\ncf_sim = {\n  const out = [];\n  for (let rep = 0; rep < 40; rep++) {\n    const r = rng(100 + rep), X = [];\n    for (let j = 0; j < cf_n; j++) {\n      const pj = 0.5 + cf_s * (r.unif() - 0.5);\n      X.push(Array.from({length: cf_k}, () => (r.unif() < pj ? 1 : 0)));\n    }\n    out.push({rep, alpha: kr20(X)});\n  }\n  return out;\n}\ncf_v = cf_s * cf_s / 12   // variance of the respondents' coin biases\ncf_rel = cf_k * cf_v / (cf_k * cf_v + 0.25 - cf_v)\nPlot.plot({\n  width: 700, height: 200, x: {label: \"Alpha (KR-20); each dot is one simulated test\", domain: [-0.6, 1]},\n  y: {axis: null},\n  marks: [\n    Plot.ruleX([0], {stroke: palette.rule}),\n    Plot.ruleX([cf_rel], {stroke: palette.contrast, strokeWidth: 2, strokeDasharray: \"5 3\"}),\n    Plot.dot(cf_sim, Plot.dodgeY({x: \"alpha\", r: 4, fill: palette.main, fillOpacity: 0.7}))\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`${cf_s === 0 ? \"Every coin is fair.\" : `Coins come up correct anywhere from ${(100 * (0.5 - cf_s / 2)).toFixed(0)}% to ${(100 * (0.5 + cf_s / 2)).toFixed(0)}% of the time, depending on the respondent.`} Reliability built in (dashed line): **${cf_rel.toFixed(2)}**. Alpha averaged over the 40 tests: **${(cf_sim.reduce((u, d) => u + d.alpha, 0) / 40).toFixed(2)}**, ranging from ${Math.min(...cf_sim.map(d => d.alpha)).toFixed(2)} to ${Math.max(...cf_sim.map(d => d.alpha)).toFixed(2)}.`\n```\n\nWith every coin fair, alpha scatters around zero, and some tests come out negative. More items don't move it off zero; more respondents only narrow the scatter. Now spread the coins. The items share something, each respondent's bias, and alpha climbs to the dashed line; now more items do raise it, as Spearman–Brown says they should. Reliability needs something shared across items: in a coin test, the respondent's coin; in a mathematics test, what the student knows.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A 200-item test is answered by 5,000 respondents, and every response is an independent fair coin flip. What is alpha, approximately?\",\n  options: [\n    {text: \"About 0\", correct: true, why: \"The total's variance is the sum of the item variances, so $1 - \\\\sum_i\\\\sigma^2_i/\\\\sigma^2_X \\\\approx 0$. With 5,000 respondents the estimate sits very close to it.\"},\n    {text: \"High, because the test is long\", correct: false, why: \"Length raises reliability only when items share something (Spearman–Brown assumes they do). Two hundred independent coins share nothing.\"},\n    {text: \"About 0.5, since each item is right half the time\", correct: false, why: \"The proportion correct sets each item's variance, not how the items covary. Alpha is about the covariances.\"}\n  ]\n})\n```\n\n### CTT doesn't say how item responses arise\n\nIf I asked you to simulate item responses that conform to CTT, what would you do? The model tells you how to make totals: draw a true score $T$, draw an error $E$, add them. It doesn't tell you how a total of 20 on a 50-item test comes about: which 20 items, or why those. Nothing in $X = T + E$ refers to an item (Lord & Novick, 1968; see [Guttman's 1969 review](https://doi.org/10.1017/s0033312300004622)).\n\nSo take the model literally. Here is a recipe for a 50-item test that obeys $X = T + E$ exactly and does nothing more:\n\n1. For each respondent, draw a true score $T$ (mean 25, variance $\\sigma^2_T$) and an error $E$ (mean 0, variance $\\sigma^2_E$), and add them to get the total $X$. The reliability, $\\sigma^2_T/(\\sigma^2_T + \\sigma^2_E)$, is whatever we chose.\n2. Give the respondent $X$ correct answers on items picked at random, with easier items more likely to be picked, so that the items' proportions correct spread out as they do on a real test.\n\nStep 1 is the classical model. Step 2 is one way of turning a total into item responses, and CTT has nothing to say against it. What does KR-20 make of the result?\n\n#### Try it: the recipe\n\nSet the two variances. Each light blue dot is one pair of settings from a grid, run through the recipe once; the orange dot is yours. If KR-20 reported the reliability we built in, every dot would sit on the dashed diagonal.\n\n```{ojs}\n//| echo: false\nviewof dv_t = Inputs.range([1, 50], {value: 10, step: 1, label: \"True-score variance\"})\nviewof dv_e = Inputs.range([1, 50], {value: 3, step: 1, label: \"Error variance\"})\n```\n\n```{ojs}\n//| echo: false\ndv_sim = (s2T, s2E, seed = 4) => {\n  const r = rng(seed), k = 50, n = 500;\n  const pr = Array.from({length: k}, () => 0.25 + 0.6 * r.unif());   // how often each item gets picked\n  const T = [], X = [], rows = [];\n  for (let j = 0; j < n; j++) {\n    const t = Math.round(k / 2 + Math.sqrt(s2T) * r.norm());\n    const x = Math.min(Math.max(t + Math.round(Math.sqrt(s2E) * r.norm()), 0), k);\n    const row = Array(k).fill(0);\n    for (const i of sampleWeighted(r, pr, x)) row[i] = 1;\n    T.push(t); X.push(x); rows.push(row);\n  }\n  const p = pr.map((_, i) => rows.reduce((u, row) => u + row[i], 0) / n);\n  const mx = X.reduce((u, v) => u + v, 0) / n;\n  return {s2T, s2E, rel: cor(T, X) ** 2, kr: kr20(rows), sumpq: p.reduce((u, v) => u + v * (1 - v), 0),\n          varX: X.reduce((u, v) => u + (v - mx) ** 2, 0) / (n - 1)};\n}\ndv_grid = [5, 10, 15, 20, 35, 50].flatMap(s2T => [5, 10, 15, 20, 35, 50].map(s2E => dv_sim(s2T, s2E)))\ndv_now = dv_sim(dv_t, dv_e)\nPlot.plot({\n  width: 700, height: 380, x: {label: \"Reliability built in\", domain: [0, 1]}, y: {label: \"KR-20\", domain: [Math.min(-0.4, dv_now.kr - 0.1), 1]},\n  marks: [\n    Plot.ruleY([0], {stroke: palette.rule}),\n    Plot.line([[0, 0], [1, 1]], {stroke: palette.guide, strokeDasharray: \"5 3\"}),\n    Plot.text([\"KR-20 above reliability\"], {x: 0.02, y: 0.95, textAnchor: \"start\", fill: palette.guide}),\n    Plot.text([\"KR-20 below reliability\"], {x: 0.98, y: -0.3, textAnchor: \"end\", fill: palette.guide}),\n    Plot.dot(dv_grid, {x: \"rel\", y: \"kr\", r: 4, fill: palette.light}),\n    Plot.dot([dv_now], {x: \"rel\", y: \"kr\", r: 7, fill: palette.contrast})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Reliability built in: **${dv_now.rel.toFixed(2)}**. KR-20: **${dv_now.kr.toFixed(2)}**. KR-20 uses two things from the data: the item variances, which add up to ${dv_now.sumpq.toFixed(1)}, and the variance of the total, ${dv_now.varX.toFixed(1)}.`\n```\n\nAt the defaults, a true-score variance of 10 and an error variance of 3, the reliability is about 0.75 and KR-20 is close to zero (0.05). Swap them (3 and 10) and the reliability drops to about 0.23 while KR-20 hardly moves (0.11). Now raise both: KR-20 climbs toward 0.9 whatever the reliability, and with a large error variance it lands well above the diagonal (5 and 25: reliability 0.23, KR-20 0.65). Push both variances very low and KR-20 goes far below zero, since the total then varies less than the items do. KR-20 is tracking the *sum* of the two variances; reliability is their *ratio*.\n\nThe formula says why. KR-20 needs only the item variances and the variance of the total. The recipe fixes the first (the item variances add up to about 12 whatever the settings), and the second is $\\sigma^2_T + \\sigma^2_E$. So, roughly,\n$$\\text{KR-20} \\approx \\frac{50}{49}\\left(1 - \\frac{12}{\\sigma^2_T + \\sigma^2_E}\\right), \\qquad \\rho = \\frac{\\sigma^2_T}{\\sigma^2_T + \\sigma^2_E}.$$\nNothing in the first expression can see how the total splits into true score and error.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd): alpha is a lower bound on reliability. The proof wrote each item as $X_i = T_i + E_i$ with errors uncorrelated with each other and with every true score, and showed $\\alpha \\le \\rho$, with equality for essentially tau-equivalent items ([Novick & Lewis, 1967](https://doi.org/10.1007/BF02289400)). It also noted that with correlated errors alpha can exceed reliability ([Green & Hershberger, 2000](https://doi.org/10.1207/S15328007SEM0702_6)).\n:::\n\nHow does that square with the lower bound? The proof assumed that item errors are uncorrelated, and the recipe breaks that in two directions. A respondent's error $E$ adds or removes correct answers all over the test, so the items share it: positively correlated errors, which push alpha up. And once the total is fixed, a correct answer on one item is one fewer for the others: negatively correlated errors, which push alpha down. With little error variance the second effect wins, and the bound holds but is loose by 0.7 or so. With a lot of error variance the first wins, and alpha is no longer a lower bound at all. $X = T + E$ allows both, since it makes no claim about items. [Sijtsma (2009)](https://doi.org/10.1007/s11336-008-9101-0) argues along related lines that alpha tells us little about how a test's items hang together.\n\nNo student answers a test this way: in the recipe, a student with 40 right is no more likely than one with 20 right to have solved a particular hard item. But CTT doesn't rule it out. What rules it out is an assumption CTT never writes down: respondents who score higher should be more likely to get *each item* right.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In the recipe, which change raises KR-20 while leaving the true reliability where it was?\",\n  options: [\n    {text: \"Scale the true-score and error variances up by the same factor\", correct: true, why: \"Reliability, $\\\\sigma^2_T/(\\\\sigma^2_T + \\\\sigma^2_E)$, is unchanged, but the variance of the total grows while the item variances don't, so KR-20 rises.\"},\n    {text: \"Add respondents\", correct: false, why: \"More respondents make both numbers more precise. They don't move either one systematically.\"},\n    {text: \"Nothing: KR-20 is tied to reliability\", correct: false, why: \"Only through assumptions about the items. Here the items' errors are correlated, so KR-20 follows the variance of the total instead.\"}\n  ]\n})\n```\n\n### Item curves against the sum score\n\nHow would we check that assumption in real data? We never see anyone's true score, but we do see their sum score, $r$. For each sum score, take the respondents with that score and compute the proportion who got a given item right. Plotted against $r$, those proportions trace an **item curve**. If higher scorers are more likely to get the item right, it rises. Estimating these curves directly, without a model for their shape, is the business of nonparametric item response theory ([Mokken, 1971](https://doi.org/10.1515/9783110813203); [Ramsay, 1991](https://doi.org/10.1007/BF02294494); [Sijtsma & Molenaar, 2002](https://doi.org/10.4135/9781412984676)).\n\nHere are the curves for a mathematics test taken by 664 German fourth graders (data [below](#items-differ-and-their-curves-bend)). Pick an item from the menu. The number beside each item, $p$, is its proportion correct: the share of all 664 students who got it right, the item's *p*-value from [Classical test theory and reliability](ctt-reliability.qmd). Items are listed from hardest (smallest $p$) to easiest.\n\n#### Try it: one item against the sum score\n\n```{ojs}\n//| echo: false\nmc_rows = math_curves.item.map((it, j) => ({item: it, r: math_curves.r[j], n: math_curves.n[j], prop: math_curves.prop[j], p: math_curves.p[j]}))\nmc_items = [...new Map(mc_rows.map(d => [d.item, d.p]))].map(([it, p]) => ({it, p})).sort((a, b) => a.p - b.p)\nviewof mc_pick = Inputs.select(mc_items.map(d => d.it), {value: \"MI3\", label: \"Item\", format: it => `${it} (p = ${mc_items.find(d => d.it === it).p.toFixed(2)})`})\nviewof mc_line = Inputs.toggle({label: \"Show a straight line\", value: false})\nviewof mc_all = Inputs.toggle({label: \"Show every item faintly\", value: false})\n```\n\n```{ojs}\n//| echo: false\nmc_sel = mc_rows.filter(d => d.item === mc_pick)\nmc_N = mc_sel.reduce((u, d) => u + d.n, 0)\nmc_rbar = mc_sel.reduce((u, d) => u + d.n * d.r, 0) / mc_N\nmc_fit = logisticFit(mc_sel.map(d => d.r - mc_rbar), mc_sel.map(d => d.prop), mc_sel.map(d => d.n))\nmc_lin = {\n  const my = mc_sel.reduce((u, d) => u + d.n * d.prop, 0) / mc_N;\n  const sxy = mc_sel.reduce((u, d) => u + d.n * (d.r - mc_rbar) * (d.prop - my), 0);\n  const sxx = mc_sel.reduce((u, d) => u + d.n * (d.r - mc_rbar) ** 2, 0);\n  const b1 = sxy / sxx; return {b0: my - b1 * mc_rbar, b1};\n}\nPlot.plot({\n  width: 700, height: 340, x: {label: \"Sum score (of 30)\", domain: [0, 30]}, y: {label: \"Proportion correct\", domain: [-0.3, 1.15]},\n  r: {range: [1.5, 7]},\n  marks: [\n    Plot.ruleY([0, 1], {stroke: palette.rule}),\n    ...(mc_all ? [Plot.line(mc_rows.filter(d => d.item !== mc_pick), {x: \"r\", y: \"prop\", z: \"item\", stroke: palette.light, strokeOpacity: 0.6})] : []),\n    Plot.dot(mc_sel, {x: \"r\", y: \"prop\", r: \"n\", fill: palette.main, fillOpacity: 0.6}),\n    Plot.line(grid(0, 30, 121).map(r => ({r, p: logistic(mc_fit.b0 + mc_fit.b1 * (r - mc_rbar))})), {x: \"r\", y: \"p\", stroke: palette.main, strokeWidth: 2.5}),\n    ...(mc_line ? [Plot.line([0, 30].map(r => ({r, p: mc_lin.b0 + mc_lin.b1 * r})), {x: \"r\", y: \"p\", stroke: palette.contrast, strokeWidth: 2, strokeDasharray: \"6 3\"})] : [])\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`**${mc_pick}**: ${(100 * mc_sel[0].p).toFixed(0)}% of students got it right. Logistic fit: log odds of success = ${mc_fit.b0.toFixed(2)} + ${mc_fit.b1.toFixed(2)} × (sum score − ${mc_rbar.toFixed(1)}), so a student with the average sum score has a ${(100 * logistic(mc_fit.b0)).toFixed(0)}% chance.${mc_line ? ` The straight line predicts ${(mc_lin.b0 + mc_lin.b1 * 1).toFixed(2)} at a sum score of 1 and ${(mc_lin.b0 + mc_lin.b1 * 30).toFixed(2)} at 30.` : \"\"} Dot size shows how many students had each sum score.`\n```\n\nStart with MI3, the hardest item: few students below a sum score of 10 get it right, and the curve takes off only in the top third. MA1, the easiest, is high from the start and flattens toward 1. Every curve rises, but where it rises depends on the item: that is difficulty in this picture. Some rise more sharply than others (compare MB4 with MI1). Turn on the straight line: for MA1 it predicts more than 100% correct at the top, for MB4 less than 0% at the bottom. The curves bend, which is why the fitted curve is logistic. Show every item and you see a family of S-shapes, shifted left and right.\n\nTwo more features matter later. First, a student with all 30 right got every item right, so every curve ends at exactly 1 (and would start at exactly 0, had anyone scored 0). The sum score contains the item, and near the ends that fixes the answer. Problem 3 swaps in the rest score, the sum of the *other* items, and [The Rasch model](rasch.qmd) meets the same fact when it compares observed and predicted proportions at each sum score. Second, the sum score depends on which items were taken. A student scores more on an easy half of this test than on a hard half, so a sum score doesn't locate a student until we know the items.\n\n### Logistic regression of an item on the sum score\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The likelihood and logistic regression](likelihood.qmd): we regressed success on each chess problem on the players' Elo ratings. Giving each problem its own intercept changed the slope, and the problems differed in their slopes too, from essentially zero (Y15) to about 2.\n:::\n\nThe fitted curve in the widget is that logistic regression, with the sum score where Elo was:\n$$\\Pr(x_{ij} = 1) = \\frac{\\exp(\\beta_{0i} + \\beta_{1i}(r_j - \\bar r))}{1 + \\exp(\\beta_{0i} + \\beta_{1i}(r_j - \\bar r))}.$$\nCentring the sum score at its mean, $\\bar r$, makes the intercept $\\beta_{0i}$ the log odds of success for a student of average score. Easy items have large intercepts and hard items small ones, so the intercept tracks difficulty. The slope $\\beta_{1i}$ says how sharply the item separates students with lower sum scores from those with higher ones: its discrimination.\n\nThat is one step from an item response model. The sum score is an observed stand-in with the problems above: it contains the item, depends on which items were taken, and has error in it. Replace it with an unknown ability $\\theta_j$ for each respondent, fix every slope at 1, and you have [the Rasch model](rasch.qmd); let the slopes differ and you have the 2PL of [From the 1PL to the 4PL](1pl-to-4pl.qmd).\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Two students in the math data got all 30 items right. Among students with a sum score of 30, what proportion got the hardest item, MI3, right?\",\n  options: [\n    {text: \"Exactly 1\", correct: true, why: \"A sum score of 30 means every item is right. The sum score contains the item, so at the ends of the scale the curve is fixed by construction.\"},\n    {text: \"About 0.7, since MI3 is hard even for strong students\", correct: false, why: \"That's roughly what students scoring in the upper 20s do. At 30 there's no room: every item, MI3 included, was answered correctly.\"},\n    {text: \"It can't be known from two students\", correct: false, why: \"Two students usually give a noisy proportion, but not here: a score of 30 settles every response.\"}\n  ]\n})\n```\n\n### Not every item rises\n\nSo far, more of the construct has meant a higher chance of a positive response. For attitudes it needn't. Consider the statement \"I think capital punishment is necessary but I wish it were not\" (item WISHNOTNEC in [Andrich, 1988](https://doi.org/10.1177/014662168801200105); wording as given in the `ANDRICH` help page of the [mudfold package](https://doi.org/10.32614/CRAN.package.mudfold)). Someone firmly against capital punishment disagrees; so, plausibly, does someone firmly in favour, who has no such wish. Items that work like this follow an **unfolding** response process (Coombs, 1964; see [Flament's 1966 review](https://doi.org/10.1007/bf02289474)), and they have their own models, the subject of [Unfolding models](unfolding.qmd). For CTT they pose a problem that keying can't solve: an item whose curve rises and then falls is neither forward nor reversed. The data section shows one.\n\n### When is CTT enough?\n\nThe sum score and alpha each rest on assumptions; the question is whether they hold for the job at hand. The sum score treats items as interchangeable, a reasonable summary when everyone takes the same items, when every item's curve rises with the construct, and when what we need is one number per respondent. Alpha estimates reliability well when the items' errors are unrelated and the items measure the true score about equally well. When respondents take different items, when we want to say something about an item rather than the total, or when precision has to vary from one score to another ([Information, precision, and short forms](information.qmd)), those assumptions carry more weight than CTT can check.\n\nWhere does that leave us? When we have a fixed form, taken by everyone, whose item curves all rise, the sum score and reliability may be sufficient for some purposes. Even then, the item curves are worth a look: they take a few lines of code, and they are where an item that doesn't rise, or rises only at the very top, shows itself. An item response model earns its keep when the design stops being a fixed form or the question stops being about the total.\n\n## Simulate\n\nThe code below is the widget's recipe in R: nine settings (three true-score variances crossed with three error variances), five data sets each, plotting the reliability built in against KR-20. It is base R and takes a second or two.\n\nWith the seed as written, KR-20 falls below reliability when the error variance is small (true-score variance 25, error variance 5: reliability 0.83, KR-20 0.62) and far above it when it is large (5 and 25: reliability 0.18, KR-20 0.61). The `sum_pq` column is about 12 in every setting; KR-20 moves with `var_X` alone. Then try the widget's default, `s2_true = 10` and `s2_error = 3` (reliability about 0.77). With `n_ppl <- 5000` the points tighten but don't move toward the diagonal.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-15\n# Where CTT breaks: a recipe that respects the classical model for the total\n# score, X = T + E, and nothing more. It sets the true reliability, then hands out\n# each respondent's correct answers across items at random (weighted so that some\n# items are easier than others). Base R only.\n# Adapted from ben-domingue/252: ps2/ctt_failures.R.\nset.seed(252)\nn_items <- 50\nn_ppl <- 500\nn_reps <- 5                                  # data sets per setting\n\nkr20 <- function(resp) {                     # KR-20: alpha for 0/1 items\n  k <- ncol(resp)\n  p <- colMeans(resp)\n  (k / (k - 1)) * (1 - sum(p * (1 - p)) / var(rowSums(resp)))\n}\n\nsim_ctt <- function(n_items, n_ppl, s2_true, s2_error) {\n  T <- round(rnorm(n_ppl, mean = n_items / 2, sd = sqrt(s2_true)))   # true scores\n  E <- round(rnorm(n_ppl, mean = 0, sd = sqrt(s2_error)))            # errors\n  X <- pmin(pmax(T + E, 0), n_items)         # observed sum scores, kept in 0..n_items\n  pr <- runif(n_items, 0.25, 0.85)           # how often each item gets picked\n  resp <- matrix(0, n_ppl, n_items)\n  for (j in 1:n_ppl)                         # respondent j gets X[j] items right,\n    if (X[j] > 0)                            # chosen at random, easier items more often\n      resp[j, sample(n_items, X[j], prob = pr)] <- 1\n  c(true_rel = cor(T, X)^2, kr20 = kr20(resp),\n    var_X = var(X), sum_pq = sum(colMeans(resp) * (1 - colMeans(resp))))\n}\n\n# Nine settings: true-score and error variances as shares of the number of items.\nsettings <- expand.grid(s2_true = n_items * c(0.1, 0.5, 0.9),\n                        s2_error = n_items * c(0.1, 0.25, 0.5))\nout <- do.call(rbind, lapply(seq_len(nrow(settings)), function(s)\n  t(replicate(n_reps, sim_ctt(n_items, n_ppl, settings$s2_true[s], settings$s2_error[s])))))\nout <- data.frame(settings[rep(seq_len(nrow(settings)), each = n_reps), ], out)\n\n# One row per setting: the reliability we built in, and what KR-20 reports.\nprint(aggregate(cbind(true_rel, kr20, var_X, sum_pq) ~ s2_true + s2_error, data = out,\n                FUN = function(x) round(mean(x), 2)))\n\ncols <- c(\"#2780e3\", \"#93c5fd\", \"#c2410c\")  # one colour per error variance\nerr <- factor(out$s2_error)\nplot(out$true_rel, out$kr20, xlim = c(0, 1), ylim = c(-0.2, 1), pch = 19,\n     col = cols[err], xlab = \"True reliability, cor(T, X)^2\",\n     ylab = \"KR-20\", main = \"Built-in reliability vs. KR-20\")\nabline(0, 1, lty = 2, col = \"grey50\")        # where KR-20 would equal reliability\nlegend(\"bottomright\", paste(\"error variance\", levels(err)), col = cols, pch = 19, bty = \"n\")\n\n```\n:::\n\n\n[Download this code](code/ctt-limits-sim.R).\n\n## With real data\n\n\n\nWe use two tables; all code is base R ([download it](code/ctt-limits-irw.R)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# IRW tables are long (one row per response); reshape to one row per respondent.\nlong2wide <- function(df) {\n  wide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\n  as.data.frame(wide[, order(colnames(wide))])\n}\n# KR-20 (Cronbach's alpha for 0/1 items).\nkr20 <- function(resp) {\n  k <- ncol(resp)\n  (k / (k - 1)) * (1 - sum(apply(resp, 2, var)) / var(rowSums(resp)))\n}\n# Correlation of each item with the sum of the *other* items.\nitem_rest <- function(resp) {\n  tot <- rowSums(resp)\n  sapply(names(resp), function(i) cor(resp[[i]], tot - resp[[i]]))\n}\n```\n:::\n\n\n### Items differ, and their curves bend\n\nThe main example is [4thgrade_math_sirt](https://itemresponsewarehouse.org/tables/4thgrade_math_sirt/), a mathematics test taken by German fourth graders and distributed with the sirt R package ([Robitzsch, 2022](https://CRAN.R-project.org/package=sirt)); its job is to show item curves that rise, bend and differ from item to item. A response is 1 if the answer was correct. The 30 items come from three domains, and most sit in testlets, groups of two to four items built around a shared task ([Wainer & Kiely, 1987](https://doi.org/10.1111/j.1745-3984.1987.tb00274.x)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nmath_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v59_0.4thgrade_math_sirt/rows?format=csv\"\ndf <- read.csv(math_url)\nhead(df)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|item |  id| resp|testlet |domain     |subdomain |\n|:----|---:|----:|:-------|:----------|:---------|\n|MA1  | 125|    0|MA      |arithmetic |addition  |\n|MA1  | 653|    0|MA      |arithmetic |addition  |\n|MA1  | 483|    0|MA      |arithmetic |addition  |\n|MA1  | 609|    0|MA      |arithmetic |addition  |\n|MA1  | 412|    0|MA      |arithmetic |addition  |\n|MA1  | 234|    0|MA      |arithmetic |addition  |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nresp <- long2wide(df)\nc(students = nrow(resp), items = ncol(resp), missing = sum(is.na(resp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstudents    items  missing \n     664       30        0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Each item belongs to one domain; most belong to a testlet of 2-4 items.\nitems <- unique(df[, c(\"item\", \"domain\", \"testlet\")])\ntable(items$domain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n arithmetic    geometry Measurement \n         16           7           7 \n```\n\n\n:::\n:::\n\n\nEvery student answered every item.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\np <- colMeans(resp)\nround(range(p), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.20 0.89\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(sort(p)[c(1, 30)], 2)          # the hardest and the easiest item\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n MI3  MA1 \n0.20 0.89 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsprintf(\"KR-20 = %.2f\", kr20(resp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"KR-20 = 0.88\"\n```\n\n\n:::\n:::\n\n\nProportions correct run from 0.20 (MI3) to 0.89 (MA1), and KR-20 is 0.88, close to the 0.90 of the reading test in [Classical test theory and reliability](ctt-reliability.qmd). By the usual CTT summaries this test holds together well. Here are the item curves behind the widget.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# For every sum score r, the proportion of students with that score who got each\n# item right: a nonparametric item curve.\nr <- rowSums(resp)\ntable(r)[c(1, length(table(r)))]      # the lowest and highest scores, and how many\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr\n 1 30 \n 6  2 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nprop <- aggregate(resp, by = list(r = r), FUN = mean)\nn_r <- as.vector(table(r))\nshow <- c(\"MA1\", \"MD2\", \"MA3\", \"MG4\", \"MI3\")   # five items from easy to hard\nop <- par(mar = c(5, 4, 1, 9), xpd = NA)   # room on the right for the legend\nplot(NULL, xlim = c(0, 30), ylim = c(0, 1), xlab = \"Sum score (of 30)\",\n     ylab = \"Proportion correct\")\nfor (i in names(resp)) lines(prop$r, prop[[i]], col = \"grey85\")\ncols <- colorRampPalette(c(\"#93c5fd\", \"#2780e3\", \"#c2410c\"))(length(show))\nfor (k in seq_along(show)) lines(prop$r, prop[[show[k]]], col = cols[k], lwd = 2.5)\nlegend(31.5, 1, sprintf(\"%s (p = %.2f)\", show, p[show]), col = cols, lwd = 2.5, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](ctt-limits_files/figure-html/curves-1.png){width=672}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npar(op)\n# At the top score every item is right, by construction: the sum contains the item.\nround(unlist(prop[prop$r == 30, show]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMA1 MD2 MA3 MG4 MI3 \n  1   1   1   1   1 \n```\n\n\n:::\n:::\n\n\nThe five highlighted items all rise, at different places, and at the top score of 30 (two students) every one is at 1, as it has to be.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Logistic regression of each item on the sum score, centred at the mean score so\n# that the intercept is the log odds of success for a student of average score.\nrc <- r - mean(r)\nfits <- t(sapply(names(resp), function(i) coef(glm(resp[[i]] ~ rc, family = binomial))))\ncolnames(fits) <- c(\"intercept\", \"slope\")\nfits <- data.frame(p = p, round(fits, 2))\nfits[order(fits$p), ][c(1:3, 28:30), ]            # the three hardest and three easiest\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    |         p| intercept| slope|\n|:---|---------:|---------:|-----:|\n|MI3 | 0.1972892|     -1.70|  0.16|\n|MI1 | 0.3298193|     -0.79|  0.10|\n|MH4 | 0.3328313|     -0.86|  0.16|\n|MD2 | 0.7500000|      1.47|  0.20|\n|MC1 | 0.7665663|      1.54|  0.18|\n|MA1 | 0.8855422|      2.30|  0.12|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsprintf(\"cor(intercept, log odds of p) = %.2f\", cor(fits$intercept, qlogis(p)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"cor(intercept, log odds of p) = 0.99\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nfits[c(which.min(fits$slope), which.max(fits$slope)), ]   # flattest and steepest\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    |         p| intercept| slope|\n|:---|---------:|---------:|-----:|\n|MI1 | 0.3298193|     -0.79|  0.10|\n|MB4 | 0.3524096|     -0.98|  0.26|\n\n</div>\n:::\n:::\n\n\nThe centred intercepts line up with the items' difficulty: they correlate 0.99 with the log odds of each item's proportion correct. The slopes differ too: MI1 rises by 0.10 on the log-odds scale per point of sum score, MB4 by 0.26. A straight line doesn't describe these curves:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same items with a straight line instead: predictions at the lowest and highest\n# possible sum scores.\nstraight <- sapply(c(\"MA1\", \"MB4\"), function(i)\n  predict(lm(resp[[i]] ~ r), data.frame(r = c(1, 30))))\nrownames(straight) <- c(\"r = 1\", \"r = 30\")\nround(straight, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        MA1   MB4\nr = 1  0.72 -0.23\nr = 30 1.06  0.95\n```\n\n\n:::\n:::\n\n\nFor MA1 the line predicts a proportion of 1.06 at a sum score of 30, and for MB4 −0.23 at a sum score of 1. No proportion can do either.\n\nFinally, which items a student takes changes their score:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The sum score depends on which items were taken. Split the test into its 15\n# easiest and 15 hardest items and score each half.\neasy <- names(sort(p, decreasing = TRUE))[1:15]\nhard <- setdiff(names(resp), easy)\nr_easy <- rowSums(resp[easy]); r_hard <- rowSums(resp[hard])\nround(c(mean_easy = mean(r_easy), mean_hard = mean(r_hard)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean_easy mean_hard \n     9.61      5.70 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nmean(r_easy > r_hard)                 # share of students who score higher on the easy half\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.871988\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nhard_given_easy <- tapply(r_hard, r_easy, mean)\nplot(jitter(r_easy), jitter(r_hard), pch = 16, col = rgb(0.15, 0.5, 0.89, 0.25),\n     xlab = \"Score on the 15 easiest items\", ylab = \"Score on the 15 hardest items\",\n     xlim = c(0, 15), ylim = c(0, 15))\nabline(0, 1, lty = 2, col = \"grey50\")\nlines(as.numeric(names(hard_given_easy)), hard_given_easy, col = \"#c2410c\", lwd = 2.5)\n```\n\n::: {.cell-output-display}\n![](ctt-limits_files/figure-html/halves-1.png){width=576}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(hard_given_easy[c(\"5\", \"10\", \"15\")], 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   5   10   15 \n 2.7  5.5 12.0 \n```\n\n\n:::\n:::\n\n\nThe same 664 students average 9.6 on the easy half and 5.7 on the hard half, and 87% score higher on the easy half. The relationship between the two halves is curved, not a constant shift: students with 5 of the easy items right average 2.7 on the hard ones, and those with all 15 average 12.0. No single constant converts one half's score into the other's. Putting scores from different items on one scale needs a model for the items, and that is where [The Rasch model](rasch.qmd) begins.\n\n### Statements that don't rise\n\nThe contrast is [andrich_mudfold](https://itemresponsewarehouse.org/tables/andrich_mudfold/): 54 graduate students in an introductory measurement course, each agreeing (1) or disagreeing (0) with eight statements about capital punishment ([Andrich, 1988](https://doi.org/10.1177/014662168801200105)). Its job is to show items whose curves don't rise with the score. The statements span opinion from strongly against to strongly in favour; we put them in Andrich's order. With 54 respondents every proportion below is noisy.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nmud_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v59_0.andrich_mudfold/rows?format=csv\"\nmud <- long2wide(read.csv(mud_url))\n# Andrich's order of the statements, from most against capital punishment to most in favour.\nstatements <- c(\"HIDEOUS\", \"LIFESACRED\", \"INEFFECTIV\", \"DONTBELIEV\",\n                \"WISHNOTNEC\", \"MUSTHAVEIT\", \"DETERRENT\", \"CRIMDESERV\")\nmud <- mud[, statements]\nc(respondents = nrow(mud), statements = ncol(mud), missing = sum(is.na(mud)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents  statements     missing \n         54           8           0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(colMeans(mud), 2)               # proportion agreeing with each statement\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   HIDEOUS LIFESACRED INEFFECTIV DONTBELIEV WISHNOTNEC MUSTHAVEIT  DETERRENT \n      0.44       0.65       0.67       0.46       0.48       0.44       0.35 \nCRIMDESERV \n      0.35 \n```\n\n\n:::\n:::\n\n\nUnkeyed, a higher total means agreeing with more statements, whatever they say, and KR-20 reflects that:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Agreement counted as it comes: 1 = agree.\nsprintf(\"KR-20 = %.2f\", kr20(mud))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"KR-20 = -0.85\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(item_rest(mud), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   HIDEOUS LIFESACRED INEFFECTIV DONTBELIEV WISHNOTNEC MUSTHAVEIT  DETERRENT \n     -0.39      -0.62      -0.59       0.05       0.25       0.14      -0.06 \nCRIMDESERV \n     -0.06 \n```\n\n\n:::\n:::\n\n\nKR-20 is −0.85, far below the zero of the coin flips, because the statements against capital punishment and those in favour pull in opposite directions.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd): CTT assumes every item is keyed so that a higher response means more of the construct. For the Mach IV, reversing the published key took alpha from 0.37 to 0.70, and one item (m19) couldn't be keyed either way from the data.\n:::\n\nKey so that a higher score means more in favour: reverse HIDEOUS, LIFESACRED and INEFFECTIV, the three statements against. Two statements sit in the middle of Andrich's order, WISHNOTNEC and DONTBELIEV (\"I do not believe in capital punishment but I am not sure it is not necessary\"; wording from the same help page). Leave them as they are for now.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"After keying, what will DONTBELIEV's item-rest correlation be? (Keyed, the six statements at either end of the order have item-rest correlations from 0.47 to 0.79.)\",\n  choices: [\"Similar to the others, around 0.6\", \"Strongly negative: it needs reversing too\", \"Near zero, whichever way it is keyed\"],\n  answer: \"Near zero, whichever way it is keyed\",\n  reveal: \"It is −0.09 as keyed and 0.09 reversed. An item whose agreement peaks in the middle of the scale doesn't correlate with the total in either direction. Check the output below.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Key so that higher = more in favour: reverse the three statements against.\nagainst <- c(\"HIDEOUS\", \"LIFESACRED\", \"INEFFECTIV\")\nkeyed <- mud\nkeyed[against] <- 1 - keyed[against]\nsprintf(\"KR-20 = %.2f\", kr20(keyed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"KR-20 = 0.85\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(item_rest(keyed), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   HIDEOUS LIFESACRED INEFFECTIV DONTBELIEV WISHNOTNEC MUSTHAVEIT  DETERRENT \n      0.47       0.73       0.74      -0.09       0.75       0.77       0.68 \nCRIMDESERV \n      0.79 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nflip <- keyed; flip$DONTBELIEV <- 1 - flip$DONTBELIEV\nround(item_rest(flip)[\"DONTBELIEV\"], 2)   # DONTBELIEV keyed the other way\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDONTBELIEV \n      0.09 \n```\n\n\n:::\n:::\n\n\nKeyed, KR-20 is 0.85, and seven of the eight item-rest correlations are between 0.47 and 0.79. DONTBELIEV is the exception: −0.09 as it stands, 0.09 reversed. Like m19 in the Mach IV, the data can't say which way to key it; its content, a qualified statement from the middle, suggests why. What do the two middle statements do as attitude changes? Score everyone on the six end statements alone (0 = against on all six, 6 = in favour on all six) and look.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Score respondents on the six end statements only (0 = against on all six,\n# 6 = in favour on all six) and see how the two middle statements behave.\nends <- setdiff(statements, c(\"DONTBELIEV\", \"WISHNOTNEC\"))\ns <- rowSums(keyed[ends])\ntable(s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ns\n 0  1  2  3  4  5  6 \n18 10  3  1  9  4  9 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ng <- cut(s, c(-1, 0, 1, 3, 4, 6), labels = c(\"0\", \"1\", \"2-3\", \"4\", \"5-6\"))   # pool thin cells\nrbind(n = table(g), round(sapply(split(mud[c(\"DONTBELIEV\", \"WISHNOTNEC\")], g), colMeans), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               0    1  2-3    4   5-6\nn          18.00 10.0 4.00 9.00 13.00\nDONTBELIEV  0.44  0.6 0.75 0.33  0.38\nWISHNOTNEC  0.00  0.3 0.75 1.00  0.85\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# A quadratic term in a logistic regression lets the curve turn over.\nround(summary(glm(mud$WISHNOTNEC ~ s + I(s^2), family = binomial))$coefficients, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error z value Pr(>|z|)\n(Intercept)    -4.21       1.32   -3.18     0.00\ns               3.53       1.22    2.89     0.00\nI(s^2)         -0.42       0.18   -2.36     0.02\n```\n\n\n:::\n:::\n\n\nNeighbouring scores are pooled where respondents are thin. DONTBELIEV rises from 0.44 among the most opposed to 0.75 in the 2–3 group, then falls back to 0.33 and 0.38: highest in the middle, though the peak rests on four respondents. WISHNOTNEC, the statement on the \"in favour\" side of the middle, rises from 0 to 1.00 at a score of 4 and then drops to 0.85 among the most in favour. A squared term in a logistic regression is negative (−0.42, standard error 0.18): the fitted curve turns over inside the range. Two respondents out of 13 make that dip, so WISHNOTNEC alone wouldn't settle it; together with DONTBELIEV and what the statements say, it is what an unfolding process looks like with 54 respondents. A sum score, keyed or not, treats each statement as pointing one way. [Unfolding models](unfolding.qmd) returns to these data with a model built for them.\n\n## Problems\n\n1. **Coins, on paper.** Suppose $n$ respondents answer $k$ items and every response is an independent fair coin flip. Show that the population variance of the total equals the sum of the item variances, and hence that KR-20 is approximately zero. Use the coin widget to see how KR-20's spread depends on $n$ and $k$.\n2. **The recipe, narrated.** Read `code/ctt-limits-sim.R` and write a paragraph on its logic. Which part of the classical model does it respect exactly? Which assumption behind alpha does it exploit, and which line of code does the exploiting?\n3. **Easy, hard and the rest score.** In `4thgrade_math_sirt`, fit logistic regressions of MA1 and MI3 on the sum score. Compare the intercepts with your sense of each item's difficulty. Now use the rest score, the sum of the other 29 items, as the predictor. What changes, and why?\n4. **Testlets.** The math items come in testlets (the `testlet` column). Compute the average correlation between items in the same testlet and between items in different testlets. What do you find, and what does it imply for alpha, given the first Recall above? (See the IRW [local dependence](https://itemresponsewarehouse.org/vignettes/local_dependence.html) vignette.)\n5. **Write an unfolding item.** Write one statement about a topic you know well whose agreement should peak in the middle of opinion, and one whose agreement should rise steadily. Sketch the curve you'd expect for each.\n6. **Challenge (open).** The item curves in this lesson use the sum score as the x-axis, and the sum score contains the item, depends on which items were taken, and has error in it. What would you need in order to replace it with something measured without error? Write down the properties you'd want, then see how many [The Rasch model](rasch.qmd) delivers.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Where%20CTT%20breaks%3A%20toward%20item%20response%20models%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20where%20classical%20test%20theory%20stops%20being%20enough%3A%20why%20coin-flip%20responses%20have%20alpha%20near%20zero%2C%20a%20simulation%20that%20obeys%20X%20%3D%20T%20%2B%20E%20but%20puts%20KR-20%20far%20from%20the%20true%20reliability%20because%20CTT%20says%20nothing%20about%20items%2C%20item%20curves%20%28proportion%20correct%20against%20the%20sum%20score%29%20and%20logistic%20regressions%20of%20an%20item%20on%20the%20sum%20score%20for%20a%20fourth-grade%20math%20test%2C%20and%20statements%20about%20capital%20punishment%20whose%20agreement%20peaks%20in%20the%20middle%20%28unfolding%29.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Lord, F. M., & Novick, M. R. (1968). *Statistical theories of mental test scores*. Addison-Wesley. The classical model in full, including what it assumes about items and what it doesn't. Guttman's review: <https://doi.org/10.1017/s0033312300004622>.\n- Sijtsma, K. (2009). On the use, the misuse, and the very limited usefulness of Cronbach's alpha. *Psychometrika*, 74(1), 107–120. <https://doi.org/10.1007/s11336-008-9101-0>. Argues that alpha says little about a test's internal structure, and proposes the greatest lower bound instead.\n- Green, S. B., & Hershberger, S. L. (2000). Correlated errors in true score models and their effect on coefficient alpha. *Structural Equation Modeling*, 7(2), 251–270. <https://doi.org/10.1207/S15328007SEM0702_6>. What correlated item errors, like the recipe's, do to alpha.\n- Ramsay, J. O. (1991). Kernel smoothing approaches to nonparametric item characteristic curve estimation. *Psychometrika*, 56(4), 611–630. <https://doi.org/10.1007/BF02294494>. Smooth item curves estimated without a parametric form, a more careful version of this lesson's plots.\n- Sijtsma, K., & Molenaar, I. W. (2002). *Introduction to nonparametric item response theory*. Sage. <https://doi.org/10.4135/9781412984676>. Rising item curves as an assumption you can test, following Mokken (1971).\n- Andrich, D. (1988). The application of an unfolding model of the PIRT type to the measurement of attitude. *Applied Psychological Measurement*, 12(1), 33–51. <https://doi.org/10.1177/014662168801200105>. The capital-punishment statements, and a model for them.\n- Wainer, H., & Kiely, G. L. (1987). Item clusters and computerized adaptive testing: A case for testlets. *Journal of Educational Measurement*, 24(3), 185–201. <https://doi.org/10.1111/j.1745-3984.1987.tb00274.x>. Where the testlet idea comes from (problem 4).\n- IRW vignette: [local dependence](https://itemresponsewarehouse.org/vignettes/local_dependence.html). How often items in IRW tables share more than the construct.\n\n\n::: {.cell}\n\n:::\n\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`4thgrade_math_sirt`](https://itemresponsewarehouse.org/tables/4thgrade_math_sirt/): Robitzsch A (2022). sirt: Supplementary Item Response Theory Models. R package version 3.12-66, <https://CRAN.R-project.org/package=sirt>. <https://cran.r-project.org/web/packages/sirt/index.html>. Licence: GPL-3.0.\n- [`andrich_mudfold`](https://itemresponsewarehouse.org/tables/andrich_mudfold/): Andrich, D. (1988). The application of an unfolding model of the PIRT type to the measurement of attitude. Applied psychological measurement, 12(1), 33-51. <https://doi.org/10.1177/014662168801200105>. Licence: GPL-3.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 2 (slides c2, \"Limitations of alpha\" through \"Looking ahead to next week\", including the closing question of how you would simulate item responses that conform to CTT) and problem set 2 (#4, \"CTT failures\", and #5, \"Towards IRT models\"); code in `ben-domingue/252`: `ps2/ctt_failures.R`, `ps2/towards_irt.R`.\n- **Timing:** the core ideas and widgets take about 45 minutes; the two real-data analyses work as a 30-minute lab.\n- **Changed from 252:** PS2#4 was a guided tour for students to narrate; here the recipe is the lesson's main argument, as a widget and in Simulate, and the lesson adds the settings where KR-20 overshoots reliability. PS2#5 used `chess_lnirt`; this lesson uses `4thgrade_math_sirt`, since chess is the main example in the neighbouring lessons. The unfolding analysis keys the six end statements and looks at the two middle ones against that score, rather than against the unkeyed total.\n- **Reuse:** `andrich_mudfold` returns in [Unfolding models](unfolding.qmd), where a model built for single-peaked curves is fit to it.\n- **Item text:** two of Andrich's (1988) eight statements are quoted, WISHNOTNEC and DONTBELIEV, from the mudfold package documentation; the others are named by their item codes.\n- **Solutions:** held back in `solutions/ctt-limits.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "ctt-limits_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script type=\"ojs-define\">\n{\"contents\":[{\"name\":\"math_curves\",\"value\":{\"item\":[\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA1\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA2\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA3\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MA4\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB1\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB2\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB3\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MB4\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC1\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC2\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC3\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MC4\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD1\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD2\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD3\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"MD4\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME1\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"ME2\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MF1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG1\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG2\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG3\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MG4\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH1\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH2\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH3\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MH4\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI1\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI2\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\",\"MI3\"],\"r\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],\"n\":[6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2,6,11,16,12,15,16,17,20,25,25,35,28,34,37,37,39,31,31,33,28,34,32,34,14,16,11,9,6,10,2],\"prop\":[0.5,0.8182,0.6875,0.5833,0.7333,0.8125,0.8235,0.85,0.68,0.92,0.9143,0.8929,0.8529,0.8649,0.8649,0.8718,0.9355,0.9355,0.9697,0.9643,0.9706,0.875,0.9706,1,1,1,1,1,1,1,0,0.0909,0.1875,0.3333,0.2667,0.3125,0.1765,0.4,0.36,0.32,0.4,0.4286,0.4706,0.6216,0.6486,0.641,0.6452,0.5806,0.6667,0.7857,0.6765,0.7812,0.7941,0.7857,0.8125,0.9091,0.6667,1,0.9,1,0,0,0.1875,0.0833,0,0.0625,0.1765,0.25,0.44,0.36,0.2571,0.4643,0.4118,0.4865,0.5405,0.6667,0.6774,0.5484,0.5758,0.7857,0.7059,0.75,0.8235,0.7857,0.875,0.9091,0.8889,1,1,1,0,0,0,0,0.0667,0.0625,0.1176,0.1,0.24,0.16,0.2286,0.25,0.3529,0.3514,0.4324,0.2564,0.7097,0.4194,0.4545,0.7143,0.6471,0.5312,0.6765,0.6429,0.625,0.8182,0.8889,1,1,1,0,0,0.125,0.0833,0.2667,0.25,0.4706,0.3,0.44,0.32,0.5429,0.3929,0.6765,0.5676,0.7838,0.6923,0.6129,0.7097,0.697,0.8929,0.7941,0.9688,0.9706,1,1,0.9091,1,1,1,1,0,0,0.1875,0,0.3333,0.25,0.2941,0.35,0.52,0.4,0.5429,0.4643,0.6176,0.5946,0.5946,0.641,0.7097,0.7419,0.5758,0.7857,0.8529,0.9062,0.9412,1,0.9375,0.9091,0.8889,1,0.9,1,0,0,0,0,0.1333,0,0,0.05,0.16,0.04,0.1143,0.2857,0.1765,0.2973,0.2973,0.1795,0.3871,0.4194,0.4545,0.4286,0.5588,0.75,0.6471,0.8571,0.75,0.8182,1,1,1,1,0,0,0.0625,0,0,0.0625,0,0,0.12,0.08,0.0857,0.1786,0.2059,0.1622,0.2703,0.3077,0.3871,0.5161,0.4242,0.4643,0.6176,0.75,0.7353,0.8571,0.75,1,0.6667,1,1,1,0,0.1818,0.0625,0.3333,0.4667,0.4375,0.4118,0.6,0.72,0.76,0.8,0.6429,0.7647,0.8378,0.8919,0.7949,0.871,0.871,0.9394,0.8214,0.9706,0.9375,0.8529,1,0.875,1,0.8889,1,1,1,0,0,0,0,0.1333,0.125,0.1176,0.15,0.4,0.08,0.3714,0.2857,0.5,0.4324,0.4054,0.4872,0.7097,0.5161,0.5455,0.7857,0.7353,0.75,0.7353,0.7143,0.875,1,0.7778,0.8333,0.9,1,0,0.1818,0.125,0.0833,0.2,0.3125,0.3529,0.4,0.68,0.48,0.6,0.6071,0.6765,0.6486,0.4865,0.7179,0.871,0.871,0.7879,0.8571,0.7941,0.9062,0.9118,0.8571,0.9375,0.7273,1,1,1,1,0,0,0,0,0.0667,0.25,0.3529,0.15,0.32,0.4,0.3429,0.4643,0.2941,0.4865,0.5405,0.7949,0.7742,0.6774,0.697,0.7857,0.7647,0.8438,0.8529,0.7143,0.8125,1,0.8889,1,1,1,0,0,0.0625,0.25,0.2667,0.3125,0.2353,0.3,0.44,0.52,0.5143,0.6071,0.7353,0.7568,0.7568,0.8974,0.6774,0.871,0.8788,0.8214,0.8824,0.8438,0.9706,1,0.9375,0.8182,1,1,1,1,0,0,0.1875,0.3333,0.4,0.375,0.5294,0.6,0.56,0.6,0.6857,0.6786,0.7647,0.7297,0.8378,0.8718,0.9355,0.9032,0.8788,0.8571,0.9706,1,0.8824,1,0.8125,1,0.8889,1,0.9,1,0,0,0,0.0833,0.0667,0.25,0.2941,0.3,0.48,0.4,0.5429,0.3929,0.6176,0.3784,0.6216,0.7436,0.7097,0.7742,0.8182,0.8214,0.8235,0.7812,0.9412,0.9286,0.875,1,1,0.8333,1,1,0,0.0909,0.0625,0.25,0.1333,0.375,0.3529,0.25,0.28,0.36,0.4571,0.6071,0.4706,0.6757,0.7297,0.6667,0.7097,0.8065,0.7576,0.8214,0.7353,0.7188,0.8235,0.9286,0.875,1,0.8889,1,1,1,0,0,0.25,0.3333,0.2,0.25,0.4706,0.4,0.48,0.48,0.6286,0.6429,0.6765,0.7568,0.6757,0.9487,0.9032,0.871,0.8485,0.8571,0.9118,0.75,0.7647,0.9286,1,1,1,1,1,1,0,0,0,0.0833,0,0,0.1176,0.1,0.04,0.12,0.2,0.2143,0.2647,0.4595,0.2973,0.359,0.5484,0.6129,0.5152,0.5357,0.6471,0.8438,0.7059,0.5,0.6875,0.7273,0.6667,0.6667,0.9,1,0,0.0909,0.0625,0.0833,0.2,0.1875,0.2353,0.15,0.32,0.48,0.4286,0.4643,0.5294,0.4865,0.6486,0.641,0.6452,0.6452,0.6667,0.75,0.8235,0.875,0.7647,0.9286,0.8125,0.9091,1,1,1,1,0,0,0,0.0833,0.0667,0,0.1176,0.1,0.12,0.24,0.2,0.2143,0.2941,0.2973,0.3243,0.4615,0.3548,0.5484,0.6364,0.6429,0.7941,0.625,0.7941,0.7857,0.8125,0.7273,1,1,1,1,0,0,0,0,0.0667,0,0.1176,0.05,0,0.08,0.0857,0.1786,0.2059,0.2162,0.2162,0.3846,0.2581,0.4839,0.5152,0.5357,0.6471,0.5312,0.6471,0.6429,0.9375,0.7273,1,1,1,1,0,0.0909,0,0,0,0.0625,0.1176,0.1,0.08,0.32,0.2286,0.2857,0.2647,0.2432,0.3243,0.4615,0.2903,0.5484,0.697,0.8214,0.7059,0.75,0.8235,0.7143,0.9375,1,1,0.6667,1,1,0,0,0,0,0.0667,0,0.0588,0,0.04,0.32,0.2,0.3571,0.2647,0.2162,0.2973,0.3846,0.3548,0.4516,0.6667,0.6429,0.6471,0.7188,0.7353,0.7857,0.875,0.9091,1,1,1,1,0.1667,0.2727,0.25,0.3333,0.2,0.25,0.2353,0.5,0.28,0.52,0.2857,0.4286,0.3824,0.4324,0.3514,0.4615,0.2903,0.5806,0.697,0.5357,0.5882,0.7812,0.8235,0.7857,0.6875,0.9091,0.7778,1,1,1,0,0,0.0625,0.0833,0.2667,0.0625,0.1176,0.25,0.24,0.24,0.1714,0.2143,0.2353,0.3514,0.2973,0.2308,0.3226,0.3226,0.6061,0.4286,0.3235,0.7188,0.7059,0.6429,0.875,0.8182,0.8889,1,0.9,1,0.3333,0.0909,0.125,0.1667,0.2,0.0625,0.1176,0.3,0.08,0.24,0.2857,0.2143,0.2353,0.4865,0.4595,0.4615,0.3548,0.3871,0.6364,0.3571,0.4412,0.75,0.7647,0.7143,0.875,0.8182,1,1,0.9,1,0,0.0909,0,0.0833,0,0.25,0.1765,0.2,0.12,0.24,0.2286,0.1786,0.2353,0.2432,0.1892,0.2564,0.2581,0.3871,0.3939,0.4286,0.4412,0.5938,0.6176,0.6429,0.75,0.6364,0.8889,0.8333,0.9,1,0,0,0.25,0.1667,0.0667,0.25,0.1765,0.25,0.04,0.2,0.2571,0.25,0.2941,0.3243,0.4595,0.1795,0.4194,0.4194,0.3333,0.3571,0.5,0.2188,0.4706,0.5,0.5,0.5455,0.7778,0.8333,1,1,0,0,0,0.1667,0.1333,0.3125,0.1765,0.4,0.28,0.24,0.3143,0.5357,0.3824,0.4324,0.5676,0.3846,0.4516,0.4839,0.5455,0.5,0.6471,0.5625,0.6765,0.7857,0.8125,1,1,0.8333,0.8,1,0,0,0.0625,0,0,0.0625,0.0588,0.15,0.04,0.08,0.0857,0.1786,0.1471,0.1622,0.1892,0.1538,0.2258,0.0968,0.1212,0.2143,0.3824,0.1875,0.1765,0.5714,0.6875,0.4545,0.6667,0.5,1,1],\"p\":[0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.8855,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5617,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.5256,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.634,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.616,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3494,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.3524,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.7666,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.4804,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.6627,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.6822,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6039,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6054,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.6973,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.3931,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.5678,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.4202,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.3419,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4352,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.4036,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.497,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.3705,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.4247,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3328,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.3298,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.4623,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973,0.1973]}}]}\n</script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}