{
  "hash": "8a76747c9e845a39ffac09d76ccdca66",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Competitions and paired comparisons: Bradley-Terry and Elo\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Beyond the standard models  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [The Rasch model](rasch.qmd)  \n**Builds toward:** none  \n**IRW tables:** [`nba_2012-2018`](https://itemresponsewarehouse.org/tables/nba_2012-2018/), [`friedman2019_risk_harm`](https://itemresponsewarehouse.org/tables/friedman2019_risk_harm/), [`friedman2019_risk_disaster`](https://itemresponsewarehouse.org/tables/friedman2019_risk_disaster/)  \n**From EDUC 252:** n/a  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.  \n**Comments:** [open an issue on GitHub](https://github.com/ben-domingue/irw-course/issues/new?title=Competitions%20and%20paired%20comparisons%3A%20Bradley-Terry%20and%20Elo%3A%20) about this lesson.\n:::\n\n```{ojs}\n//| echo: false\nimport {grid, logistic, palette} from \"./widgets/irt.js\"\nimport {btMM, divisionLeague, eloTrack} from \"./widgets/competitions.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nTwo basketball teams play; one wins. A survey respondent is shown two risks and picks the one that did more harm. Neither setting has items, only pairs set against each other, yet the model we need is one we already have. The Rasch model compares a person with an item. Replace the item with a second person and you have the **Bradley-Terry model** ([Bradley & Terry, 1952](https://doi.org/10.1093/biomet/39.3-4.324)), a model for games, tournaments and paired-comparison judgments alike. Its online cousin, the **Elo rating**, produced the chess ratings in [The likelihood and logistic regression](likelihood.qmd). This lesson builds both from the Rasch model, then asks a question item response data rarely force on us: what if the thing measured changes while we measure it?\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- write down the Bradley-Terry model, fit it as a logistic regression, and say what fixes its origin and when its estimates exist;\n- explain why win percentage and Bradley-Terry strength agree when every agent faces the same opponents, and why they part ways when schedules differ;\n- derive the Elo update from the Bradley-Terry likelihood and say what its step size $K$ trades off;\n- compare a static and a dynamic rating by how well each predicts games it hasn't seen;\n- build a scale from paired-comparison judgments and say what the question asked does to it.\n\n## Core ideas\n\n### Competition data: no items, only opponents\n\nIn a competition each row pairs two **agents**, and the outcome says which came out ahead. The IRW stores such data in its [competition standard](https://itemresponsewarehouse.org/comps_standard.html): `agent_a`, `agent_b`, a `winner` (`agent_a`, `agent_b` or `draw`), a `date`, which side had the home advantage, and scores where there are scores; `irw_fetch(name, source = \"comp\")` loads them. Each outcome measures both agents at once, on one scale, and tells us only about the gap between them. The same shape fits judgments: a judge asked \"which of these two is more harmful?\" also produces a winner and a loser ([Glickman & Jones, 2025](https://doi.org/10.1146/annurev-statistics-040722-061813), review models for both).\n\n### The Bradley-Terry model is a Rasch model in which the item is another agent\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd) (Go deeper: sufficiency): take two items and condition on a respondent getting exactly one of them right. The probability that it was item $i$ is $1/(1 + e^{b_i - b_k})$, whatever the respondent's $\\theta$. Swap the roles and compare two respondents on one item, and the comparison depends only on $\\theta_j - \\theta_l$.\n:::\n\nThat comparison of two respondents is already a model for a competition. Write $\\theta_j$ for the strength of agent $j$. The Bradley-Terry model says that when $j$ meets $k$,\n$$\\Pr(j \\text{ beats } k) = \\frac{\\exp(\\theta_j - \\theta_k)}{1 + \\exp(\\theta_j - \\theta_k)}.$$\nSet it beside the Rasch model: the opponent's strength $\\theta_k$ sits exactly where the item difficulty $b_i$ sat. [Zermelo (1929)](https://doi.org/10.1007/BF01180541) proposed this model for tournament results; [Bradley & Terry (1952)](https://doi.org/10.1093/biomet/39.3-4.324) arrived at it for paired comparisons in experiments, and [Luce (1959)](https://openlibrary.org/works/OL4319279W) reached the same form from a theory of choice behaviour. [Andrich (1978)](https://doi.org/10.1177/014662167800200319) set out its relation to the Rasch model.\n\nAnything else that tilts a game goes into the exponent. A home team has an advantage $h$, so $\\Pr(\\text{home } j \\text{ beats } k) = \\text{logistic}(h + \\theta_j - \\theta_k)$. In a judgment task, the same term captures a preference for whichever option is shown first.\n\n#### Try it: the opponent is the item\n\n```{ojs}\n//| echo: false\nviewof bt_k = Inputs.range([-3, 3], {value: 0.5, step: 0.1, label: \"Visitors' strength θk\"})\nviewof bt_j = Inputs.range([-3, 3], {value: 0, step: 0.1, label: \"Home team's strength θj\"})\nviewof bt_h = Inputs.range([0, 1.5], {value: 0.4, step: 0.05, label: \"Home advantage h\"})\n```\n\n```{ojs}\n//| echo: false\nbt_curve = grid(-4, 4).map(t => ({theta: t, p: logistic(bt_h + t - bt_k), curve: \"With home advantage\"}))\n  .concat(grid(-4, 4).map(t => ({theta: t, p: logistic(t - bt_k), curve: \"Neutral court\"})))\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Home team's strength θj\"}, y: {label: \"P(home team wins)\", domain: [0, 1]},\n  color: {legend: true, domain: [\"With home advantage\", \"Neutral court\"], range: [palette.main, palette.light]},\n  marks: [\n    Plot.ruleY([0.5], {stroke: palette.rule}),\n    Plot.ruleX([bt_k], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n    Plot.line(bt_curve, {x: \"theta\", y: \"p\", stroke: \"curve\", strokeWidth: 2.5}),\n    Plot.dot([{theta: bt_j, p: logistic(bt_h + bt_j - bt_k)}], {x: \"theta\", y: \"p\", r: 6, fill: palette.contrast})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`The home team wins with probability **${logistic(bt_h + bt_j - bt_k).toFixed(2)}** (on a neutral court, ${logistic(bt_j - bt_k).toFixed(2)}). The dashed line is the visitors' strength: on a neutral court, the curve crosses 0.5 there, just as an item characteristic curve crosses 0.5 at the item's difficulty.`\n```\n\nMove the visitors' strength and the curve slides without changing shape, as the Rasch curve did when we moved $b$. The home advantage slides it too, as if every visitor were $h$ logits weaker.\n\nTwo facts carry over from the Rasch model unchanged. The first is identification.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd): adding the same constant to every $\\theta$ and every $b$ leaves every probability unchanged, so the scale has no origin until we fix one.\n:::\n\nOnly differences $\\theta_j - \\theta_k$ appear, so we fix one agent at 0 or make the strengths average 0. The second fact is that the model is a logistic regression: one row per game, outcome 1 if the first-listed agent won, and one column per agent, $+1$ for the first agent, $-1$ for the second and 0 otherwise. The intercept is $h$. `glm()` fits it, as does the `BradleyTerry2` package ([Turner & Firth, 2012](https://doi.org/10.18637/jss.v048.i09)).\n\nWhen does the maximum exist? [Zermelo (1929)](https://doi.org/10.1007/BF01180541) and [Ford (1957)](https://doi.org/10.1080/00029890.1957.11989117) give the condition. Split the agents into any two groups; somebody in each group must have beaten somebody in the other. An agent who never loses fails it, and so does a league split into two halves that never meet.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The likelihood and logistic regression](likelihood.qmd) (Go deeper): if a predictor perfectly separates successes from failures, the log likelihood keeps rising as the slope grows and the MLE doesn't exist ([Albert & Anderson, 1984](https://doi.org/10.1093/biomet/71.1.1)).\n:::\n\n#### Try it: the undefeated team\n\nFour teams play each other twice; team A won five games and lost one, to D. The plot follows A's estimated strength as the fitting algorithm runs (Zermelo's iteration, which climbs the likelihood at every step; [Hunter, 2004](https://doi.org/10.1214/aos/1079120141)).\n\n```{ojs}\n//| echo: false\nviewof ud_case = Inputs.radio([\"A lost once, to D\", \"A won every game\", \"A won every game but drew once, with D\"], {value: \"A lost once, to D\", label: \"Team A's record\"})\n```\n\n```{ojs}\n//| echo: false\nud_iters = [1, 2, 3, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000]\nud_path = {\n  const n = [[0, 2, 2, 2], [2, 0, 2, 2], [2, 2, 0, 2], [2, 2, 2, 0]];\n  const w = [[0, 2, 2, 2], [0, 0, 1, 2], [0, 1, 0, 1], [0, 0, 1, 0]];\n  if (ud_case.startsWith(\"A lost\")) { w[0][3] = 1; w[3][0] = 1; }\n  if (ud_case.includes(\"drew\")) { w[0][3] = 1.5; w[3][0] = 0.5; }\n  return ud_iters.map(it => ({iterations: it, theta: btMM(n, w, it)[0]}));\n}\nPlot.plot({\n  width: 700, height: 260, x: {type: \"log\", label: \"Iterations\"}, y: {label: \"Estimated strength of team A\", domain: [0, 8]},\n  marks: [Plot.line(ud_path, {x: \"iterations\", y: \"theta\", stroke: palette.main, strokeWidth: 2.5}),\n          Plot.dot(ud_path, {x: \"iterations\", y: \"theta\", r: 3, fill: palette.main})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`After 100 iterations A's estimate is ${ud_path[7].theta.toFixed(2)}; after 10,000 it is ${ud_path[13].theta.toFixed(2)}.`\n```\n\nWith one loss, the estimate settles within a few dozen iterations. Without it, every round of the algorithm pushes A higher: the data are best explained by an A infinitely stronger than everyone else. A single draw, counted as half a win as chess scores it, brings the estimate back. The data must contain some evidence that A can be beaten.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Two analysts fit Bradley-Terry to the same season. One fixes the first team at 0; the other makes the strengths average 0. For two given teams, what is the same in both analyses?\",\n  options: [\n    {text: \"The difference between the teams' strengths, and so the predicted probability that one beats the other\", correct: true, why: \"The model only sees $\\\\theta_j - \\\\theta_k$. Changing the origin shifts every strength by the same amount, which leaves every difference, and every prediction, unchanged.\"},\n    {text: \"Each team's estimated strength\", correct: false, why: \"Those differ by a constant: the shift from one origin to the other.\"},\n    {text: \"Nothing: the two fits describe different models\", correct: false, why: \"They are the same model with a different origin, as with `mirt` centring abilities and a CML program centring difficulties in the Rasch lesson.\"}\n  ]\n})\n```\n\n### Wins are to Bradley-Terry what the sum score is to Rasch\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The likelihood and logistic regression](likelihood.qmd): in a logistic regression, the derivative of the log likelihood with respect to a coefficient is $\\sum_i (y_i - p_i)x_i$. For the intercept this says that at the maximum, the predicted number of successes equals the observed number.\n:::\n\nAgent $j$'s column is $+1$ in games where $j$ is listed first and $-1$ where it is listed second, so its derivative is zero exactly when $j$'s expected wins equal its actual wins. Given who played whom, the win total is sufficient for strength, as the sum score is for $\\theta$ under the Rasch model; in a round robin, ranking by strength and ranking by wins coincide. \"Given who played whom\" is where the two part ways.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Where CTT breaks](ctt-limits.qmd): the sum score depends on which items were taken. A student scored more on an easy half of a test than on a hard half.\n:::\n\nWin percentage ignores who you played; Bradley-Terry adjusts for strength of schedule, as the Rasch model adjusts for the items taken.\n\n#### Try it: strength of schedule\n\nSix teams in two divisions. Lions, Tigers and Bears are the three strongest; Wolves, Foxes and Hares the three weakest. Each team plays 40 games, a share of them within its own division. The widget uses the expected number of wins, with no chance in it, so that only the schedule differs.\n\n```{ojs}\n//| echo: false\nviewof ss_within = Inputs.range([0.4, 0.95], {value: 0.4, step: 0.05, label: \"Share of games within the division\"})\n```\n\n```{ojs}\n//| echo: false\nss_names = [\"Lions\", \"Tigers\", \"Bears\", \"Wolves\", \"Foxes\", \"Hares\"]\nss_theta = [1, 0.6, 0.2, -0.2, -0.6, -1]\nss_league = divisionLeague(ss_theta, ss_within)\nss_est = btMM(ss_league.n, ss_league.w, 3000)\nss_rows = ss_names.map((name, i) => ({\n  team: name, \"true strength\": ss_theta[i].toFixed(1),\n  \"win %\": (100 * ss_league.w[i].reduce((s, v) => s + v, 0) / 40).toFixed(0),\n  \"Bradley-Terry estimate\": ss_est[i].toFixed(2)\n}))\nInputs.table(ss_rows, {layout: \"auto\", rows: 7, height: 250})\n```\n\n```{ojs}\n//| echo: false\nPlot.plot({\n  width: 700, height: 240, x: {label: \"Win percentage\", domain: [0, 100]}, y: {domain: ss_names, label: null},\n  marks: [Plot.ruleX([50], {stroke: palette.rule}),\n          Plot.barX(ss_rows, {x: d => +d[\"win %\"], y: \"team\", fill: (d, i) => i < 3 ? palette.main : palette.contrast})]\n})\n```\n\nAt 0.4 the schedule is a balanced round robin, and win percentage orders the teams correctly. Push the slider up: the Bears, weakest of the strong division, lose more; the Wolves, best of the weak division, win more. From about 0.6 the Wolves have the better record, and at 0.9 they win 61% of their games to the Bears' 39%. The Bradley-Terry estimates recover the true strengths at every setting, because the model knows whom each team played.\n\nWin percentage is a reasonable summary when the schedule is balanced, and it needs no model; in the simulation below it does as well as Bradley-Terry on a near-random schedule. Bradley-Terry earns its keep when the schedule is lopsided, as in leagues with divisions or a comparative-judgment study where some essays meet only weak ones.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In a league where every team plays every other team the same number of times (and half of those games at home), team A finishes with more wins than team B. Under Bradley-Terry, whose estimated strength is higher?\",\n  options: [\n    {text: \"A's, always\", correct: true, why: \"In a round robin every team faces the same opponents, so the score equations leave the estimates in the same order as the win totals: wins are sufficient given the schedule.\"},\n    {text: \"It depends on whom A's wins came against\", correct: false, why: \"That would matter under a model where wins against strong teams count for more. Under Bradley-Terry, as under Rasch, only the total counts, given the schedule.\"},\n    {text: \"B's, if B beat A head to head\", correct: false, why: \"The head-to-head games are part of each team's total; they get no extra weight.\"}\n  ]\n})\n```\n\n### Elo is Bradley-Terry estimated one game at a time\n\nBradley-Terry fits a season at once. A chess federation has no season: games arrive daily, and a rating is wanted after each. [Elo (1978)](https://openlibrary.org/works/OL6807294W) proposed a rule. Before $j$ meets $k$, compute from the current ratings $\\hat p = \\text{logistic}(\\hat\\theta_j - \\hat\\theta_k)$. After the game, with $y = 1$ if $j$ won, $\\tfrac12$ for a draw and 0 for a loss,\n$$\\hat\\theta_j \\leftarrow \\hat\\theta_j + K\\,(y - \\hat p), \\qquad \\hat\\theta_k \\leftarrow \\hat\\theta_k - K\\,(y - \\hat p).$$\nA player who wins when expected to gains a little; a player who wins as an underdog gains a lot. One rating goes up by exactly what the other goes down, so the average rating never moves, which sets the origin.\n\nWhy this rule? $y - \\hat p$ is the derivative of one game's Bradley-Terry log likelihood with respect to $\\theta_j$ (see the Go deeper callout below), so Elo takes a step of size $K$ uphill on the likelihood of the latest game. A small $K$ averages over many games: stable, but slow to notice a player who improves. A large $K$ follows change quickly, and follows luck too.\n\n::: {.callout-note collapse=\"true\"}\n## Elo points and logits\n\nChess federations report ratings in points rather than logits. In the conversion table of the [FIDE Rating Regulations](https://handbook.fide.com/chapter/B022024) (§8.1.1), an expected score of 0.75, odds of 3 to 1 or $\\log 3 = 1.10$ logits, corresponds to a rating difference of 193 points, so a logit is about 175 points there. FIDE uses $K$ = 40, 20 or 10 depending on a player's experience and rating (§8.3.3); $K = 20$ points is about 0.11 logits.\n:::\n\n#### Try it: Elo following a change\n\nOne team plays 200 games against opponents of known strength; its true strength is 0, then jumps at game 100. Elo starts at 0 and sees only results.\n\n```{ojs}\n//| echo: false\nviewof el_K = Inputs.range([0.01, 0.8], {value: 0.1, step: 0.01, label: \"Step size K (logits)\"})\nviewof el_jump = Inputs.range([0, 2], {value: 1, step: 0.1, label: \"Size of the jump at game 100\"})\n```\n\n```{ojs}\n//| echo: false\nel_run = eloTrack(el_K, el_jump, 200, 1)\nel_mse = el_run.reduce((s, d) => s + (d.rating - d.truth) ** 2, 0) / el_run.length\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Game\"}, y: {label: \"Strength (logits)\", domain: [-1.2, 3]},\n  color: {legend: true, domain: [\"True strength\", \"Elo rating\"], range: [palette.guide, palette.main]},\n  marks: [\n    Plot.line(el_run, {x: \"game\", y: \"truth\", stroke: () => \"True strength\", strokeWidth: 2, strokeDasharray: \"4,3\"}),\n    Plot.line(el_run, {x: \"game\", y: \"rating\", stroke: () => \"Elo rating\", strokeWidth: 2})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Mean squared distance between the rating and the truth, over all 200 games: **${el_mse.toFixed(3)}**. At game 100 the rating is ${el_run[99].rating.toFixed(2)}; at game 200 it is ${el_run[199].rating.toFixed(2)} (truth ${el_jump.toFixed(1)}).`\n```\n\nWith $K = 0.02$ the rating creeps up and is still well short of the new strength 100 games after the jump. With $K = 0.6$ it passes 0.8 within three games of the jump but then swings by more than a logit either way. In between (here around $K = 0.15$) the mean squared distance is smallest. Set the jump to 0: now there is no change to follow, and the smallest $K$ does best, because all a larger $K$ adds is noise.\n\nThe same rule, with the item as the opponent, is used to track learners in adaptive practice systems ([Pelánek, 2016](https://doi.org/10.1016/j.compedu.2016.03.017)). [Glickman (1999)](https://doi.org/10.1111/1467-9876.00159) replaces the fixed $K$ with a step that depends on how uncertain each rating is, so a rating we know little about moves further. That is the Glicko system.\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: Elo as stochastic gradient ascent\n\n**Assumptions:** games are independent given the strengths; game $g$ between $j$ and $k$ follows Bradley-Terry with $p_g = \\text{logistic}(\\theta_j - \\theta_k)$; $y_g \\in \\{0, \\tfrac12, 1\\}$ (a draw enters as $\\tfrac12$, which is the chess convention rather than a model for draws).\n\n**One game's gradient.** The log likelihood of game $g$ is $\\ell_g = y_g \\log p_g + (1 - y_g)\\log(1 - p_g)$. As in [The likelihood and logistic regression](likelihood.qmd), with $\\partial p_g/\\partial\\theta_j = p_g(1-p_g)$,\n$$\\frac{\\partial \\ell_g}{\\partial \\theta_j} = y_g - p_g, \\qquad \\frac{\\partial \\ell_g}{\\partial \\theta_k} = -(y_g - p_g),$$\nand every other agent's derivative is 0. The Elo update adds $K$ times this gradient, evaluated at the current ratings. The full log likelihood is $\\sum_g \\ell_g$, so the Elo update is **stochastic gradient ascent** on the Bradley-Terry log likelihood: one game at a time, with learning rate $K$.\n\n**What the fixed step does.** [Robbins & Monro (1951)](https://doi.org/10.1214/aoms/1177729586) gave a procedure of this kind, with steps that shrink as observations accumulate, whose estimates converge in probability to the value sought. Elo keeps $K$ fixed, so its ratings never converge; they keep fluctuating around the strengths, and the fluctuations grow with $K$. If strengths are fixed, that is a cost. If they drift, it is the point: a fixed step weights recent games more than old ones, so the ratings forget.\n\n**Two consequences.** The ratings' sum is fixed (each update adds and subtracts the same amount), so Elo sets the origin by keeping the mean at its starting value. And a home advantage, or any other term in the exponent, gets its own gradient, $y_g - p_g$ for $h$; problem 1 asks what updating it would do. Seen this way, Elo is one-step estimation of $\\theta$ with the opponent, or the item, treated as known. [Aldous (2017)](https://doi.org/10.1214/17-STS628) studies by simulation how accurate such ratings are.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Under Elo, a player rated 1 logit above her opponent wins. With $K = 0.1$, about how much does her rating go up?\",\n  options: [\n    {text: \"About 0.03 logits\", correct: true, why: \"Her expected score was $\\\\text{logistic}(1) \\\\approx 0.73$, so she gains $0.1 \\\\times (1 - 0.73) \\\\approx 0.027$. An expected win moves the rating only a little.\"},\n    {text: \"0.1 logits\", correct: false, why: \"That would be the gain if her expected score had been 0. The step is $K$ times the surprise, $y - \\\\hat p$.\"},\n    {text: \"About 0.07 logits\", correct: false, why: \"That is $0.1 \\\\times 0.73$, $K$ times her expected score. The step is $K$ times the surprise, $1 - 0.73$.\"}\n  ]\n})\n```\n\n### Static or dynamic? Let prediction decide\n\nBradley-Terry assumes each agent has one strength for the whole period the data cover: plausible for one tournament or one survey, a strong assumption for six basketball seasons of trades and injuries. Elo assumes strength can drift, and pays for it with noise. Which assumption holds is a question the data can answer by prediction: fit on the past, predict games not yet seen, and compare the log likelihood of what happened ([Glickman & Jones, 2025](https://doi.org/10.1146/annurev-statistics-040722-061813)). In-sample fit can't settle it, since a model with a strength per team per season fits better by construction whether or not teams changed. The NBA analysis below makes the comparison.\n\n### Paired comparisons as measurement\n\n[Thurstone (1927)](https://doi.org/10.1037/h0070288) used paired comparisons to scale things with no natural unit. His law of comparative judgment, in its simplest form (Case V), is Bradley-Terry with the normal curve in place of the logistic. [Andrich (1978)](https://doi.org/10.1177/014662167800200319) showed that with the logistic it gives the same equations for the scale values as the Rasch model, except that the judge's own level drops out by design, because both options go to the same judge.\n\nWhat is measured here is the stimuli, not the people; the judges are instruments, and the question they were asked defines the scale. Ask \"which is more harmful?\" and \"which could cause a bigger disaster?\" of the same pairs and nothing obliges the two scales to agree. The same holds when teachers judge which of two essays is better ([Pollitt, 2012](https://doi.org/10.1080/0969594X.2012.665354)): the question put to the judges plays the part of the rubric.\n\n## Simulate\n\nThe code below simulates 30 agents with fixed strengths playing 1,200 games on a lopsided schedule (three divisions formed by strength, 80% of games inside the division), fits Bradley-Terry with `glm()` and compares the estimates, and win percentage, with the truth. The second part lets strengths drift and runs Elo at seven values of $K$, scoring each by the mean log likelihood of its predictions. It is base R and runs in about a second.\n\nWith the seed as written, win percentage correlates 0.65 with the true strengths and Bradley-Terry 0.94. Change `within` to 0.1, close to a random schedule, and win percentage (0.94) edges out the noisier Bradley-Terry estimates (0.90). Then try `drift_sd` at 0, 0.05 and 0.15: the best $K$ grows with the drift, from 0.1 to 0.1–0.2 to 0.4.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-18\n# Bradley-Terry and Elo, simulated. Part 1: 30 agents with fixed strengths play a\n# lopsided schedule; we fit Bradley-Terry with glm() and compare the estimates, and\n# win percentage, with the truth. Part 2: the strengths drift over time; we run Elo at several step\n# sizes K and ask which K predicts the next game best. Base R only; a few seconds.\n# New for this course. The irw package's irw_simdata_comp() simulates part 1 too.\nset.seed(86)\nn_agents <- 30\nn_games  <- 1200       # try 300, then 5000\nh        <- 0.4        # home advantage, in logits\n\n# ---- Part 1: fixed strengths ----\ntheta <- rnorm(n_agents, 0, 0.8)\ntheta <- theta - mean(theta)          # the model only sees differences; centre the truth\n# A lopsided schedule: three divisions of 10, formed by strength, and a share\n# `within` of each agent's games is against its own division.\nwithin <- 0.8          # try 0.1 (close to a random schedule)\ndivision <- ceiling(rank(theta) / 10)\nhome <- sample(n_agents, n_games, replace = TRUE)\naway <- sapply(home, function(j) {\n  pool <- if (runif(1) < within) which(division == division[j]) else which(division != division[j])\n  sample(setdiff(pool, j), 1)\n})\ny <- rbinom(n_games, 1, plogis(h + theta[home] - theta[away]))\n\nX <- matrix(0, n_games, n_agents)\nX[cbind(seq_len(n_games), home)] <- 1\nX[cbind(seq_len(n_games), away)] <- -1\nm <- glm(y ~ X[, -1], family = binomial)     # agent 1 fixed at 0, then re-centred\nest <- c(0, coef(m)[-1])\nest <- est - mean(est)\nround(c(home_advantage = unname(coef(m)[1]), correlation = cor(est, theta),\n        rmse = sqrt(mean((est - theta)^2))), 3)\nplot(theta, est, xlab = \"True strength\", ylab = \"Bradley-Terry estimate\", pch = 19)\nabline(0, 1, lty = 2)\n\n# Win percentage ignores who you played. How closely does it track the truth?\nwins  <- tabulate(home[y == 1], n_agents) + tabulate(away[y == 0], n_agents)\ngames <- tabulate(home, n_agents) + tabulate(away, n_agents)\nround(c(cor_winpct_truth = cor(wins / games, theta), cor_bt_truth = cor(est, theta)), 3)\n\n# ---- Part 2: drifting strengths and Elo ----\n# Each agent's strength takes a small random step after every round of games\n# (drift_sd per round). Elo predicts each game before it is played, so its log\n# likelihood is out of sample by construction.\ndrift_sd <- 0.05       # try 0, then 0.15\nrounds <- 100\ntheta_t <- matrix(0, rounds, n_agents)\ntheta_t[1, ] <- rnorm(n_agents, 0, 0.8)\nfor (t in 2:rounds) theta_t[t, ] <- theta_t[t - 1, ] + rnorm(n_agents, 0, drift_sd)\ngames <- do.call(rbind, lapply(seq_len(rounds), function(t) {\n  pairs <- matrix(sample(n_agents), ncol = 2)        # everyone plays once per round\n  data.frame(round = t, a = pairs[, 1], b = pairs[, 2])\n}))\ngames$y <- rbinom(nrow(games), 1,\n                  plogis(h + theta_t[cbind(games$round, games$a)] - theta_t[cbind(games$round, games$b)]))\n\nelo <- function(K) {\n  r <- rep(0, n_agents)\n  ll <- numeric(nrow(games))\n  for (g in seq_len(nrow(games))) {\n    a <- games$a[g]; b <- games$b[g]\n    p <- plogis(h + r[a] - r[b])\n    ll[g] <- games$y[g] * log(p) + (1 - games$y[g]) * log(1 - p)\n    r[a] <- r[a] + K * (games$y[g] - p)\n    r[b] <- r[b] - K * (games$y[g] - p)\n  }\n  mean(ll[games$round > 20])                         # skip a burn-in\n}\nKs <- c(0.01, 0.03, 0.05, 0.1, 0.2, 0.4, 0.8)\nround(setNames(sapply(Ks, elo), Ks), 4)              # mean log likelihood per game\n\n```\n:::\n\n\n[Download this code](code/competitions-sim.R) to run it in your own R session. The `irw` package's `irw_simdata_comp()` simulates competition data too.\n\n## With real data\n\n\n\n### Six NBA seasons\n\nOur main example is [nba_2012-2018](https://itemresponsewarehouse.org/tables/nba_2012-2018/), every regular-season NBA game from 2012-13 to 2017-18, from box scores compiled by [Rossotti (2018)](https://www.kaggle.com/datasets/pablote/nba-enhanced-stats). Its job is to show strengths that change over time. `agent_a` is always the home team, so the outcome is keyed as 1 when the home team wins. [Download the code](code/competitions-irw.R); it needs only base R.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Competition tables have no items. Each row is one game: agent_a, agent_b, the\n# winner (\"agent_a\", \"agent_b\" or \"draw\"), the date (seconds since 1970) and the\n# scores. In this table agent_a is always the home team (hometeam == \"agent_a\").\nnba_url <- \"https://redivis.com/api/v1/tables/datapages.irw_competitions:v3_2.nba_2012-2018/rows?format=csv\"\nnba <- read.csv(nba_url)\nhead(nba)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|agent_a | score_a|agent_b | score_b|       date|hometeam |winner  |\n|:-------|-------:|:-------|-------:|----------:|:--------|:-------|\n|LAL     |     101|CHA     |     100| 1355817600|agent_a  |agent_a |\n|SA      |     101|DAL     |     100| 1414479600|agent_a  |agent_a |\n|PHI     |     101|POR     |     100| 1363590000|agent_a  |agent_a |\n|POR     |     101|LAC     |     100| 1359187200|agent_a  |agent_a |\n|DEN     |     101|PHI     |     100| 1363849200|agent_a  |agent_a |\n|MEM     |     101|POR     |     100| 1447401600|agent_a  |agent_a |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nnrow(nba)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9839\n```\n\n\n:::\n:::\n\n\nThe 2016-17 and 2017-18 seasons appear twice, because two source files overlap; we keep one copy of each game.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The 2016-17 and 2017-18 seasons appear twice (the source files overlap), so we\n# keep one copy of each game. A season runs from October to April.\nnba <- nba[!duplicated(nba), ]\nnba$day <- as.Date(as.POSIXct(nba$date, origin = \"1970-01-01\", tz = \"UTC\"))\nnba$season <- as.integer(format(nba$day, \"%Y\")) - (as.integer(format(nba$day, \"%m\")) < 8)\nnba <- nba[order(nba$date), ]\nnba$y <- as.integer(nba$winner == \"agent_a\")     # 1 if the home team won; no draws\ntable(season = nba$season)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nseason\n2012 2013 2014 2015 2016 2017 \n1229 1230 1230 1230 1230 1230 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nteams <- sort(unique(c(nba$agent_a, nba$agent_b)))\nc(games = nrow(nba), teams = length(teams), home_win_rate = round(mean(nba$y), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        games         teams home_win_rate \n     7379.000        30.000         0.586 \n```\n\n\n:::\n:::\n\n\nThat leaves 7,379 games among 30 teams, 1,230 in each season but one. Home teams won 58.6% of them.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Bradley-Terry as a logistic regression: one row per game, a column per team,\n# +1 for the home team, -1 for the visitors. The intercept is the home advantage h.\n# Only differences are identified, so we drop the first team's column (its strength\n# is fixed at 0) and then re-centre the strengths to mean 0.\ndesign <- function(d) {\n  X <- matrix(0, nrow(d), length(teams), dimnames = list(NULL, teams))\n  X[cbind(seq_len(nrow(d)), match(d$agent_a, teams))] <- 1\n  X[cbind(seq_len(nrow(d)), match(d$agent_b, teams))] <- -1\n  X\n}\nfit_bt <- function(d) {\n  X <- design(d)\n  m <- glm(d$y ~ X[, -1], family = binomial)\n  theta <- c(0, coef(m)[-1])\n  names(theta) <- teams\n  list(h = unname(coef(m)[1]), theta = theta - mean(theta), model = m)\n}\nbt_all <- fit_bt(nba)\nround(c(home_advantage = bt_all$h, se = summary(bt_all$model)$coefficients[1, 2]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nhome_advantage             se \n         0.387          0.025 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(sort(bt_all$theta, decreasing = TRUE)[1:5], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  GS   SA  HOU  LAC  OKC \n1.11 0.98 0.65 0.64 0.63 \n```\n\n\n:::\n:::\n\n\nThe home advantage is 0.39 logits (standard error 0.025): between equal teams, the home team wins with probability $\\text{logistic}(0.39) \\approx 0.60$. Golden State (GS) and San Antonio (SA) are strongest over the six seasons. Does the schedule adjustment matter?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Win percentage against the Bradley-Terry strength, over all six seasons.\nwin_pct <- sapply(teams, function(t) mean(c(nba$y[nba$agent_a == t], 1 - nba$y[nba$agent_b == t])))\nround(c(correlation = cor(win_pct, bt_all$theta),\n        rank_correlation = cor(win_pct, bt_all$theta, method = \"spearman\")), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     correlation rank_correlation \n          0.9953           0.9947 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# At the maximum, each team's expected wins equal its actual wins:\np_hat <- fitted(bt_all$model)\nexp_wins <- sapply(teams, function(t) sum(p_hat[nba$agent_a == t]) + sum(1 - p_hat[nba$agent_b == t]))\nact_wins <- sapply(teams, function(t) sum(nba$y[nba$agent_a == t]) + sum(1 - nba$y[nba$agent_b == t]))\nround(head(cbind(actual = act_wins, expected = exp_wins)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    actual expected\nATL    257      257\nBKN    200      200\nBOS    262      262\nCHA    217      217\nCHI    253      253\nCLE    268      268\n```\n\n\n:::\n:::\n\n\nHardly: win percentage and strength correlate 0.995. Each team's expected wins equal its actual wins (the first six are shown), and the NBA schedule is close enough to balanced that the two rankings nearly coincide. Now fit each season on its own.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# One Bradley-Terry fit per season: who is strongest, and how far apart are teams?\nby_season <- t(sapply(sort(unique(nba$season)), function(s) {\n  b <- fit_bt(nba[nba$season == s, ])\n  c(season = s, home_adv = round(b$h, 2), sd_theta = round(sd(b$theta), 2),\n    top_theta = round(max(b$theta), 2))\n}))\ndata.frame(by_season, top_team = sapply(sort(unique(nba$season)), function(s)\n  names(which.max(fit_bt(nba[nba$season == s, ])$theta))))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| season| home_adv| sd_theta| top_theta|top_team |\n|------:|--------:|--------:|---------:|:--------|\n|   2012|     0.57|     0.77|      1.50|MIA      |\n|   2013|     0.41|     0.79|      1.36|SA       |\n|   2014|     0.39|     0.82|      1.69|GS       |\n|   2015|     0.46|     0.89|      2.30|GS       |\n|   2016|     0.40|     0.63|      1.59|GS       |\n|   2017|     0.38|     0.69|      1.43|HOU      |\n\n</div>\n:::\n:::\n\n\nThe strongest team changes: Miami, then San Antonio, then Golden State for three seasons, then Houston. The spread of strengths (SD 0.63 to 0.89 logits) and the home advantage (0.38 to 0.57) move less. A pooled fit gives each team one strength for all six seasons; how much does that cost when we predict?\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Fit on the first five seasons, predict every game of 2017-18. Which predicts best: Bradley-Terry pooled over five seasons, Bradley-Terry on 2016-17 alone, or Elo run through all the games? And does the pooled fit beat a constant that knows only the home advantage?\",\n  choices: [\"Pooled Bradley-Terry; yes\", \"Bradley-Terry on the last season; yes\", \"Elo; yes\", \"Elo; no\"],\n  answer: \"Elo; no\",\n  reveal: \"Elo is best (mean log likelihood −0.622 per game), then the last season alone (−0.658). The pooled fit, at −0.697, does worse than the constant (−0.681): its strengths average over teams that are no longer the teams they were.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Fit on 2012-13 to 2016-17, predict every game of 2017-18. The score is the mean\n# log likelihood per game (closer to 0 is better; always guessing 0.5 gives -0.693).\ntrain <- nba[nba$season < 2017, ]\ntest  <- nba[nba$season == 2017, ]\nmean_ll <- function(p, y) mean(y * log(p) + (1 - y) * log(1 - p))\nbt5 <- fit_bt(train)                                  # all five seasons pooled\nbt1 <- fit_bt(nba[nba$season == 2016, ])              # the last season only\np_const <- rep(mean(train$y), nrow(test))             # home advantage, nothing else\np_bt5 <- plogis(bt5$h + design(test) %*% bt5$theta)\np_bt1 <- plogis(bt1$h + design(test) %*% bt1$theta)\n\n# Elo on the logit scale: before each game, predict from the current ratings; after\n# it, move both ratings by K times the surprise. Ratings start at 0 and carry over\n# from season to season. The home advantage is the five-season estimate.\nelo <- function(d, K, h) {\n  r <- setNames(rep(0, length(teams)), teams)\n  p <- numeric(nrow(d))\n  for (g in seq_len(nrow(d))) {\n    a <- d$agent_a[g]; b <- d$agent_b[g]\n    p[g] <- plogis(h + r[a] - r[b])\n    r[a] <- r[a] + K * (d$y[g] - p[g])\n    r[b] <- r[b] - K * (d$y[g] - p[g])\n  }\n  list(p = p, ratings = r)\n}\n# Choose K on the training seasons only. Elo's predictions are made before each\n# game, so they are already out of sample; 2012-13 is a burn-in.\nKs <- c(0.01, 0.02, 0.05, 0.075, 0.1, 0.15, 0.2, 0.3, 0.5)\ntune <- sapply(Ks, function(K) {\n  e <- elo(train, K, bt5$h)\n  mean_ll(e$p[train$season > 2012], train$y[train$season > 2012])\n})\nround(setNames(tune, Ks), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   0.01    0.02    0.05   0.075     0.1    0.15     0.2     0.3     0.5 \n-0.6422 -0.6279 -0.6141 -0.6107 -0.6096 -0.6104 -0.6131 -0.6213 -0.6438 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nK <- Ks[which.max(tune)]\np_elo <- elo(nba, K, bt5$h)$p[nba$season == 2017]\n\nscores <- c(constant = mean_ll(p_const, test$y), bt_five_seasons = mean_ll(p_bt5, test$y),\n            bt_last_season = mean_ll(p_bt1, test$y), elo = mean_ll(p_elo, test$y))\nround(scores, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       constant bt_five_seasons  bt_last_season             elo \n         -0.681          -0.697          -0.658          -0.622 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Is Elo's edge over the pooled fit more than noise? A paired standard error over games.\nd_ll <- (test$y * log(p_elo) + (1 - test$y) * log(1 - p_elo)) -\n        (test$y * log(p_bt5) + (1 - test$y) * log(1 - p_bt5))\nround(c(K = K, difference = mean(d_ll), se = sd(d_ll) / sqrt(length(d_ll))), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         K difference         se \n     0.100      0.075      0.010 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# How much did the teams change? Strengths from the pooled fit against 2017-18 alone.\nround(cor(bt5$theta, fit_bt(test)$theta), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.33\n```\n\n\n:::\n:::\n\n\nThe step size was chosen on the training seasons only: $K = 0.1$ logits (about 17 FIDE points) predicted the 2013-14 to 2016-17 games best. On 2017-18, Elo's mean log likelihood is −0.622 per game, against −0.658 for Bradley-Terry on 2016-17 alone, −0.681 for the constant and −0.697 for the pooled fit. Elo's edge over the pooled fit is 0.075 per game (standard error 0.010). The last line says why: the pooled strengths correlate only 0.33 with the strengths 2017-18 alone produces. [Glickman & Jones (2025)](https://doi.org/10.1146/annurev-statistics-040722-061813) analyse NBA outcomes with dynamic models in more depth.\n\nWhere does that leave the choice? When the data span a period over which agents plausibly change, a rating that forgets, such as Elo with $K$ chosen by prediction, may be sufficient for some purposes where a pooled fit is not. Over a short, fixed window, such as one tournament or one survey, the Bradley-Terry fit, with its standard errors and explicit terms for home advantage or order, may be the more useful summary. The first question to ask of the data is whether strength stayed put.\n\n### One hundred risks\n\n[friedman2019_risk_harm](https://itemresponsewarehouse.org/tables/friedman2019_risk_harm/) comes from a survey in which Americans compared 100 public risks in pairs ([Friedman, 2019](https://doi.org/10.1111/ajps.12400); [replication data](https://doi.org/10.7910/DVN/ZSJA25)). Its job is to show paired comparisons measuring the things compared. Per the study's codebook, respondents picked the risk that caused more harm in the past year, so the scale is keyed toward more harm; the picked risk is `agent_a`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# 100 public risks. Each rater saw pairs and picked one: for harm, the risk that\n# caused more harm in the past year; for disaster, the one with more potential for\n# disaster (Friedman, 2019, codebook). agent_a is always the risk the rater picked.\nharm_url <- \"https://redivis.com/api/v1/tables/datapages.irw_competitions:v3_2.friedman2019_risk_harm/rows?format=csv\"\ndis_url  <- \"https://redivis.com/api/v1/tables/datapages.irw_competitions:v3_2.friedman2019_risk_disaster/rows?format=csv\"\nharm <- read.csv(harm_url)\ndisaster <- read.csv(dis_url)\nhead(harm, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|agent_a       |agent_b             | rater|winner  |\n|:-------------|:-------------------|-----:|:-------|\n|Air pollution |Air warfare         |  2125|agent_a |\n|Air pollution |Air warfare         |   889|agent_a |\n|Air pollution |Alzheimer's disease |   940|agent_a |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(judgments = nrow(harm), raters = length(unique(harm$rater)),\n  risks = length(unique(c(harm$agent_a, harm$agent_b))), picked_a = mean(harm$winner == \"agent_a\"),\n  median_per_rater = median(table(harm$rater)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       judgments           raters            risks         picked_a \n           21390             1194              100                1 \nmedian_per_rater \n              15 \n```\n\n\n:::\n:::\n\n\nThere are 21,390 judgments by 1,194 raters, 15 for the median rater. Since the chosen risk is always `agent_a`, the table can't say which risk was shown first, so there is no order effect to estimate: we fit with no intercept, flipping a coin for which risk is written first so the outcome varies.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The table records the chosen risk as agent_a, so we can't estimate an order\n# effect. We flip a coin for which risk is written first, so that the outcome\n# varies; with no intercept the fit is the same either way.\nfit_judgments <- function(d, seed = 1) {\n  risks <- sort(unique(c(d$agent_a, d$agent_b)))\n  set.seed(seed)\n  flip <- rbinom(nrow(d), 1, 0.5) == 1\n  first <- ifelse(flip, d$agent_b, d$agent_a)\n  second <- ifelse(flip, d$agent_a, d$agent_b)\n  y <- as.integer(!flip)                              # 1 if the first risk was picked\n  X <- matrix(0, nrow(d), length(risks), dimnames = list(NULL, risks))\n  X[cbind(seq_len(nrow(d)), match(first, risks))] <- 1\n  X[cbind(seq_len(nrow(d)), match(second, risks))] <- -1\n  m <- glm(y ~ 0 + X[, -1], family = binomial)\n  theta <- c(0, coef(m))\n  names(theta) <- risks\n  theta - mean(theta)\n}\nharm_theta <- fit_judgments(harm)\nround(sort(harm_theta, decreasing = TRUE)[1:6], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Alcohol use                      Cancer \n                       2.05                        1.96 \n                    Obesity               Drunk driving \n                       1.85                        1.81 \nPrescription drug overdoses                     Smoking \n                       1.75                        1.74 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(sort(harm_theta)[1:6], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Asteroid collision               Extraterrestrials \n                          -3.09                           -2.99 \n             Volcanic eruptions                    Solar flares \n                          -2.30                           -1.97 \n                    Nuclear war High-energy physics experiments \n                          -1.97                           -1.83 \n```\n\n\n:::\n:::\n\n\nAlcohol use (2.05), cancer (1.96) and obesity (1.85) are judged most harmful; asteroid collisions (−3.09) and extraterrestrials (−2.99) least. Nuclear war (−1.97) is near the bottom, consistent with a question about harm in the past year. How repeatable is the scale? Split the raters at random and fit each half.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Split the raters at random into two halves and fit each half separately.\nset.seed(2)\nraters <- unique(harm$rater)\nhalf <- sample(raters, length(raters) / 2)\nth1 <- fit_judgments(harm[harm$rater %in% half, ])\nth2 <- fit_judgments(harm[!harm$rater %in% half, ])\nround(cor(th1, th2), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.97\n```\n\n\n:::\n:::\n\n\nThe two halves' scale values correlate 0.97: each rater made about 15 judgments, but each half pools nearly 600 raters.\n\nOur contrast is [friedman2019_risk_disaster](https://itemresponsewarehouse.org/tables/friedman2019_risk_disaster/), from the same survey and so the same data source: respondents compared the same risks for their potential for disaster.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same 100 risks, judged for their potential for disaster.\ndis_theta <- fit_judgments(disaster)\nround(cor(harm_theta, dis_theta), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.63\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nshift <- dis_theta - harm_theta\nround(sort(shift, decreasing = TRUE)[1:5], 2)   # rise most on disaster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Nuclear war   Asteroid collision Biological terrorism \n                2.97                 2.32                 2.01 \n Pandemics / plagues    Nuclear meltdowns \n                1.78                 1.76 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(sort(shift)[1:5], 2)                      # fall most\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAlcohol use     Smoking     Obesity     Falling      Cancer \n      -1.25       -1.19       -1.08       -1.03       -1.00 \n```\n\n\n:::\n:::\n\n\nThe two scales correlate only 0.63. Nuclear war rises 2.97 logits, asteroid collisions 2.32 and biological terrorism 2.01; alcohol use falls 1.25, smoking 1.19 and obesity 1.08. The same hundred risks, ordered differently, because the scales answer different questions: a paired-comparison scale measures the stimuli with respect to a criterion, and the criterion belongs in its name. Friedman asked about eight criteria (problem 5 uses a third), and his argument concerns how Americans with different values judge the same risks differently, which one scale averages over (problem 6).\n\n## Problems\n\n1. **Derivation.** Add a home advantage to the Elo rule, $\\hat p = \\text{logistic}(\\hat h + \\hat\\theta_j - \\hat\\theta_k)$, and use the Go deeper callout to write an update for $\\hat h$ with its own step size. Show that the average rating still never moves. Run it on the NBA data: does $\\hat h$ settle near 0.39?\n2. **Real data with a twist.** Did the NBA home advantage change? Fit season-specific team strengths with one $h$, then with a separate $h$ per season, and compare by likelihood ratio. Would separate $h$s have improved the 2017-18 predictions?\n3. **Judgment.** A district scores teachers by the average Bradley-Terry strength of their students' essays, from judges' paired comparisons. What would you need to believe for these scores to be fair to teachers? Name three assumptions, and say which data like the Friedman tables could check.\n4. **Design.** You have 100 essays and budget for 1,000 comparisons. How would you choose the pairs? Consider when the estimates exist, how much each comparison tells you (information $p(1-p)$), and adaptive pairing ([Pollitt, 2012](https://doi.org/10.1080/0969594X.2012.665354)). Check your design with the simulation.\n5. **Real data.** Friedman's other criteria are IRW tables with the same layout, such as `friedman2019_risk_worry`. Fit one and compare it with the harm scale. Which risks move most, and why might they? Check the wording in the [codebook](https://doi.org/10.7910/DVN/ZSJA25) first.\n6. **Challenge (open).** The Friedman raters disagree. Split them by a feature you can justify (the replication data hold respondent covariates), fit a mixture of Bradley-Terry models, or give raters random effects. Is there one scale of harm, or several? What would count as evidence either way?\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Competitions%20and%20paired%20comparisons%3A%20Bradley-Terry%20and%20Elo%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20competition%20and%20paired-comparison%20data%20%28the%20IRW%20competition%20standard%29%2C%20the%20Bradley-Terry%20model%20as%20a%20Rasch%20model%20in%20which%20the%20item%20is%20another%20agent%2C%20fitting%20it%20as%20a%20logistic%20regression%20with%20glm%28%29%20in%20R%2C%20identification%20and%20when%20estimates%20exist%20%28the%20undefeated%20team%29%2C%20win%20percentage%20versus%20strength%20of%20schedule%2C%20home%20advantage%2C%20the%20Elo%20rating%20as%20stochastic%20gradient%20ascent%20on%20the%20Bradley-Terry%20likelihood%2C%20comparing%20static%20and%20dynamic%20ratings%20by%20out-of-sample%20prediction%20on%20six%20NBA%20seasons%2C%20and%20Thurstone%20scaling%20of%20100%20public%20risks%20judged%20for%20harm%20and%20for%20disaster%20potential.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Glickman, M. E., & Jones, A. C. (2025). Models and rating systems for head-to-head competition. *Annual Review of Statistics and Its Application*, 12, 259–282. <https://doi.org/10.1146/annurev-statistics-040722-061813>. A review of the whole lesson and much beyond it, from Bradley-Terry and ties to Glicko and systems for online games, with an NBA application.\n- Zermelo, E. (1929). Die Berechnung der Turnier-Ergebnisse als ein Maximumproblem der Wahrscheinlichkeitsrechnung. *Mathematische Zeitschrift*, 29, 436–460. <https://doi.org/10.1007/BF01180541>. The model, its fitting algorithm and the existence condition, for chess tournaments.\n- Bradley, R. A., & Terry, M. E. (1952). Rank analysis of incomplete block designs: I. The method of paired comparisons. *Biometrika*, 39(3–4), 324–345. <https://doi.org/10.1093/biomet/39.3-4.324>. Where the model gets its name.\n- Ford, L. R. (1957). Solution of a ranking problem from binary comparisons. *The American Mathematical Monthly*, 64(8), 28–33. <https://doi.org/10.1080/00029890.1957.11989117>. When the maximum likelihood estimates exist.\n- Luce, R. D. (1959). *Individual choice behavior: A theoretical analysis*. Wiley. <https://openlibrary.org/works/OL4319279W>. The choice axiom, from which the model follows.\n- Thurstone, L. L. (1927). A law of comparative judgment. *Psychological Review*, 34(4), 273–286. <https://doi.org/10.1037/h0070288>. Paired comparisons as psychological measurement.\n- Andrich, D. (1978). Relationships between the Thurstone and Rasch approaches to item scaling. *Applied Psychological Measurement*, 2(3), 451–462. <https://doi.org/10.1177/014662167800200319>. The Rasch model and paired comparisons side by side.\n- Davidson, R. R. (1970). On extending the Bradley-Terry model to accommodate ties in paired comparison experiments. *Journal of the American Statistical Association*, 65(329), 317–328. <https://doi.org/10.1080/01621459.1970.10481082>; and Rao, P. V., & Kupper, L. L. (1967). Ties in paired-comparison experiments: A generalization of the Bradley-Terry model. *Journal of the American Statistical Association*, 62(317), 194–204. <https://doi.org/10.1080/01621459.1967.10482901>. Two ways to model draws rather than score them as half a win; ordered response categories are the subject of [Models for polytomous responses](polytomous.qmd).\n- Hunter, D. R. (2004). MM algorithms for generalized Bradley-Terry models. *The Annals of Statistics*, 32(1). <https://doi.org/10.1214/aos/1079120141>. The fitting algorithm in the undefeated-team widget, and its extensions.\n- Turner, H., & Firth, D. (2012). Bradley-Terry models in R: The BradleyTerry2 package. *Journal of Statistical Software*, 48(9). <https://doi.org/10.18637/jss.v048.i09>. Fitting the model, with covariates, in R.\n- Elo, A. E. (1978). *The rating of chessplayers, past and present*. Arco. <https://openlibrary.org/works/OL6807294W>. The rating system, from its author.\n- Glickman, M. E. (1999). Parameter estimation in large dynamic paired comparison experiments. *Journal of the Royal Statistical Society, Series C*, 48(3), 377–394. <https://doi.org/10.1111/1467-9876.00159>. The Glicko system, which carries each rating's uncertainty; Glickman's [Glicko-2 note](http://www.glicko.net/glicko/glicko2.pdf) adds a volatility for each player.\n- Herbrich, R., Minka, T., & Graepel, T. (2006). TrueSkill: A Bayesian skill rating system. *Advances in Neural Information Processing Systems*, 19. <https://proceedings.neurips.cc/paper/2006/hash/f44ee263952e65b3610b8ba51229d1f9-Abstract.html>. A Bayesian rating system from online gaming, which also rates players who compete in teams.\n- Glickman, M. E., & Stern, H. S. (1998). A state-space model for National Football League scores. *Journal of the American Statistical Association*, 93(441), 25–35. <https://doi.org/10.1080/01621459.1998.10474084>. A full dynamic model, with strengths that evolve over time.\n- Aldous, D. (2017). Elo ratings and the sports model: A neglected topic in applied probability? *Statistical Science*, 32(4). <https://doi.org/10.1214/17-STS628>. Open questions about the model, and a simulation study of how accurate Elo ratings are.\n- Hvattum, L. M., & Arntzen, H. (2010). Using ELO ratings for match result prediction in association football. *International Journal of Forecasting*, 26(3), 460–470. <https://doi.org/10.1016/j.ijforecast.2009.10.002>. Elo ratings used for prediction.\n- Pelánek, R. (2016). Applications of the Elo rating system in adaptive educational systems. *Computers & Education*, 98, 169–179. <https://doi.org/10.1016/j.compedu.2016.03.017>. Elo with the item as the opponent.\n- Pollitt, A. (2012). The method of Adaptive Comparative Judgement. *Assessment in Education: Principles, Policy & Practice*, 19(3), 281–300. <https://doi.org/10.1080/0969594X.2012.665354>. Paired comparisons for grading open-ended work.\n- Robbins, H., & Monro, S. (1951). A stochastic approximation method. *The Annals of Mathematical Statistics*, 22(3), 400–407. <https://doi.org/10.1214/aoms/1177729586>. Stochastic approximation, for the Go deeper callout.\n- Friedman, J. A. (2019). Priorities for preventive action: Explaining Americans' divergent reactions to 100 public risks. *American Journal of Political Science*, 63(1), 181–196. <https://doi.org/10.1111/ajps.12400>. The source of the risk data, and an argument about why reactions to risks differ across people.\n- From the IRW: the [competition data standard](https://itemresponsewarehouse.org/comps_standard.html), with a worked Elo and Bradley-Terry example on NFL data.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`nba_2012-2018`](https://itemresponsewarehouse.org/tables/nba_2012-2018/): Rossotti, P. (2018). NBA enhanced box score and standings (2012–2018) (Version 27) [Data set]. Kaggle. <https://www.kaggle.com/datasets/pablote/nba-enhanced-stats>. Licence: CC BY-SA 4.0.\n- [`friedman2019_risk_harm`](https://itemresponsewarehouse.org/tables/friedman2019_risk_harm/): Friedman, Jeffrey, 2018, \"Replication Data for: Priorities for Preventive Action: Explaining Americans' Divergent Reactions to 100 Public Risks\", <https://doi.org/10.7910/DVN/ZSJA25>, Harvard Dataverse, V1, UNF:6:OJ7nZP2bzoQZoyzx8JvOFg== [fileUNF] Friedman, J. A. (2019). Priorities for preventive action: Explaining Americans’ divergent reactions to 100 public risks. American Journal of Political Science, 63(1), 181-196. <https://doi.org/10.1111/ajps.12400>. Licence: CC BY 4.0.\n- [`friedman2019_risk_disaster`](https://itemresponsewarehouse.org/tables/friedman2019_risk_disaster/): Friedman, Jeffrey, 2018, \"Replication Data for: Priorities for Preventive Action: Explaining Americans' Divergent Reactions to 100 Public Risks\", <https://doi.org/10.7910/DVN/ZSJA25>, Harvard Dataverse, V1, UNF:6:OJ7nZP2bzoQZoyzx8JvOFg== [fileUNF] Friedman, J. A. (2019). Priorities for preventive action: Explaining Americans’ divergent reactions to 100 public risks. American Journal of Political Science, 63(1), 181-196. <https://doi.org/10.1111/ajps.12400>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** new for this course (issue #86); there is no EDUC 252 class behind it. It is built on the IRW competition standard.\n- **Timing:** the core ideas and widgets take about 50 minutes; the NBA and risk analyses work as a 30-minute lab. The real-data code runs in about ten seconds, most of it the download.\n- **Data notes:** in `nba_2012-2018`, `agent_a` is always the home team (the column is `hometeam` in this table, `homefield` in the standard), and two seasons appear twice because of overlapping source files, so the code removes exact duplicates; the 2012-13 season has 1,229 games. In the Friedman tables `agent_a` is always the chosen risk, which rules out an order effect; the survey module and the position of each pair aren't in the table. The two Friedman tables are one data source, used as main example and contrast.\n- **Held back:** draws modelled properly (Davidson; ordinal models), intransitivity and multidimensional strength, rater-level covariates and mixtures (problem 6), Glicko-2 and TrueSkill (Going further). Elo in adaptive learning systems is picked up in [Item banks and adaptive testing](item-banks-cat.qmd).\n- **Solutions:** held back in `solutions/competitions.qmd` (not published). Problem 6 is open.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}