{
  "hash": "f3aa3e04d1c8fc0ff8d4f18c33f5cf49",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"What is an item? Explanatory item response models\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Beyond the standard models  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [The Rasch model](rasch.qmd)  \n**Builds toward:** [Latent classes and cognitive diagnosis](cdm.qmd) · [IRTree models](irtrees.qmd) · [Response time and the speed-accuracy tradeoff](response-time.qmd) · [Trials as items: tasks, shots, and rotations](trials.qmd) · [AI and psychometrics](ai-psychometrics.qmd)  \n**Picks up threads:** Responses are independent given θ (from [The Rasch model](rasch.qmd))  \n**IRW tables:** [`verbagg`](https://itemresponsewarehouse.org/tables/verbagg/), [`trog_brinchmann_2019`](https://itemresponsewarehouse.org/tables/trog_brinchmann_2019/), [`imps2025_hf`](https://itemresponsewarehouse.org/tables/imps2025_hf/)  \n**From EDUC 252:** slides c8; problem sets PS6#2, PS7#2; code [`ps6/hf.R`](https://github.com/ben-domingue/252/blob/main/ps6/hf.R), [`c8/lmer_example.R`](https://github.com/ben-domingue/252/blob/main/c8/lmer_example.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\nwebr::install(\"lme4\", quiet = TRUE)\nsuppressPackageStartupMessages(library(lme4))\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {grid, p2pl, dnorm, palette} from \"./widgets/irt.js\"\nimport {lltmWorld, pchisqUpper, formulaFor} from \"./widgets/explanatory-irt.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nThe Rasch model gives every item a difficulty and stops there. It says *that* shouting at a bus driver is harder to endorse than cursing, not *why*. Yet items are usually built from a design: a situation, a behaviour, a grammatical construct, a stimulus shown after another stimulus. If the design explains the difficulties, we have learned something about the construct and can say how hard an item will be before anyone answers it. This lesson writes the Rasch model as a regression, so that explaining becomes a change of formula: item features in place of item difficulties, respondent covariates, items as draws from a family. Along the way it asks what, exactly, an item is.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- write the Rasch model as a mixed logistic regression and fit it with `glmer()`;\n- say what distinguishes a descriptive model from an explanatory one, and fit the linear logistic test model (LLTM);\n- explain why item features can account for most of the variation in difficulty and still be rejected by a likelihood-ratio test, and what an item residual does about it;\n- decide whether items should be fixed or random effects, and read the variance between and within item families;\n- add respondent covariates to the same model, and treat a trial's context as a feature of the item.\n\n## Core ideas\n\n### An item response model is a regression\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The likelihood and logistic regression](likelihood.qmd): stacked long, the chess responses went into a logistic regression with one intercept per problem and Elo as the predictor, and the lesson ended by asking what would happen if each player got an unknown parameter of their own instead of Elo.\n:::\n\nEach row of a long IRW table is one response $x_{ij}$, and the Rasch model is\n$$\\text{logit}\\Pr(x_{ij} = 1) = \\theta_j + \\beta_i, \\qquad \\theta_j \\sim N(0, \\sigma^2_\\theta),$$\nwhere $\\beta_i = -b_i$ is item $i$'s *easiness*. The items are fixed effects, one indicator each; the respondents are a random intercept. That is a generalized linear mixed model ([Rijmen, Tuerlinckx, De Boeck & Kuppens, 2003](https://doi.org/10.1037/1082-989X.8.2.185)), and `lme4` ([Bates, Mächler, Bolker & Walker, 2015](https://doi.org/10.18637/jss.v067.i01)) fits it in one line ([Doran, Bates, Bliese & Dowling, 2007](https://doi.org/10.18637/jss.v020.i02); [De Boeck et al., 2011](https://doi.org/10.18637/jss.v039.i12)):\n\n```r\nglmer(resp ~ 0 + item + (1 | id), family = binomial, data = long_table)\n```\n\nThe `0 +` gives each item its own intercept; `(1 | id)` is $\\theta$. Why not stay with `mirt`? Because everything in this lesson is a change to that formula. The two programs' Rasch estimates agree to about a thousandth of a logit here (second Go deeper callout).\n\n#### Try it: build the formula\n\nTick the terms you want for the 24 verbal aggression items of [Item response data and the IRW](irw-data.qmd). (Trait anger is a respondent covariate in `lme4`'s copy of these data, not the IRW's.)\n\n```{ojs}\n//| echo: false\nviewof fb_terms = Inputs.checkbox(\n  [\"Item effects (one per item)\", \"Item features (behaviour, situation, want/do)\", \"Item residual\", \"A respondent covariate (trait anger)\"],\n  {value: [\"Item effects (one per item)\"], label: \"Terms\"})\n```\n\n```{ojs}\n//| echo: false\nfb = formulaFor({\n  itemEffects: fb_terms.includes(\"Item effects (one per item)\"),\n  design: fb_terms.includes(\"Item features (behaviour, situation, want/do)\"),\n  residual: fb_terms.includes(\"Item residual\"),\n  personCov: fb_terms.includes(\"A respondent covariate (trait anger)\")\n})\nmd`\\`${fb.formula}\\`\n\n**Parameters:** ${fb.params} (including the SD of θ). **Fixed-effect columns:** ${fb.columns.join(\", \")}.\n\n${fb.note ? `*${fb.note}*` : \"\"}`\n```\n\nThe Rasch model needs 25 parameters; swap the item effects for the three item features and it needs 6. Tick both and the model is not identified. An item residual adds one parameter, however many items there are.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In `glmer(resp ~ 0 + item + (1 | id), family = binomial)`, what plays the part of the Rasch model's $\\\\theta_j$?\",\n  options: [\n    {text: \"The random intercept for each `id`\", correct: true, why: \"Each respondent gets a deviation from zero, drawn from a normal distribution whose SD the model estimates. That is $\\\\theta_j$ with its mean fixed at 0.\"},\n    {text: \"The coefficient on each `item`\", correct: false, why: \"Those are the items' easinesses, $\\\\beta_i = -b_i$. They are fixed effects, one per item.\"},\n    {text: \"The residual\", correct: false, why: \"A logistic regression has no separate residual term: the randomness is in the Bernoulli draw of each response given its probability.\"}\n  ]\n})\n```\n\n### Descriptive and explanatory models\n\nA model with a parameter per item *describes* the items; one that replaces those parameters with predictors *explains* them ([Wilson & De Boeck, 2004](https://doi.org/10.1007/978-1-4757-3990-9_2)). Likewise for respondents.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Item response data and the IRW](irw-data.qmd): each verbal aggression item crosses a situation (someone else to blame, or yourself) with a behaviour (curse, scold, shout) and a mode (would you *want* to, would you *do* it). Wanting was reported more than doing for every behaviour, most of all for shouting.\n:::\n\nThe **linear logistic test model** ([Fischer, 1973](https://doi.org/10.1016/0001-6918(73)90003-6)) writes each item's easiness as a weighted sum of its features,\n$$\\beta_i = \\sum_k q_{ik}\\,\\eta_k,$$\nwhere $q_{ik}$ is 1 if item $i$ has feature $k$ and $\\eta_k$ is that feature's effect on easiness. For the verbal aggression items: an intercept, *scold*, *shout*, *self to blame* and *want*, five parameters in place of 24:\n\n```r\nglmer(resp ~ behav + situ + mode + (1 | id), family = binomial, data = long_table)\n```\n\nThe LLTM is a Rasch model with a constraint on the difficulties, so it keeps the Rasch model's properties (first Go deeper callout). And a feature means something that 24 difficulties don't: if *want* adds 0.7 logits whatever the situation or behaviour, that is a testable claim about how people report aggression. Written the other way round, with items built from the features, it becomes a tool for designing tests ([Embretson, 1998](https://doi.org/10.1037/1082-989X.3.3.380)).\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Differential item functioning](dif.qmd): DIF flags items one at a time. A group × feature interaction asks whether the flagged items share a feature.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"An LLTM for the 24 verbal aggression items has an intercept and four feature effects. The Rasch model has 24 item easinesses. Both have the SD of $\\\\theta$. How many degrees of freedom does the likelihood-ratio test of the LLTM against the Rasch model have?\",\n  options: [\n    {text: \"19\", correct: true, why: \"The Rasch model has 25 parameters and the LLTM 6. The LLTM is nested in the Rasch model (it confines the 24 easinesses to a five-dimensional subspace), so the test has $25 - 6 = 19$ df.\"},\n    {text: \"20\", correct: false, why: \"That compares 24 easinesses with four feature effects and forgets the LLTM's intercept.\"},\n    {text: \"The models aren't nested, so there is no likelihood-ratio test\", correct: false, why: \"They are nested: any set of LLTM parameters gives 24 easinesses the Rasch model could also have.\"}\n  ]\n})\n```\n\n### Explaining difficulty is not fitting it\n\nHow good is an LLTM? Two questions get mixed up. How much of the variation in difficulty do the features account for (the squared correlation of the LLTM's easinesses with the Rasch model's)? And do they account for *all* of it, which is what the likelihood-ratio test asks? With a few hundred respondents each easiness is estimated to within a tenth of a logit or so, so the test notices departures that barely dent the correlation.\n\n#### Try it: explained, and still rejected\n\nEach dot is an item on the verbal aggression design: its easiness is the design's prediction plus a residual whose SD the slider sets.\n\n```{ojs}\n//| echo: false\nviewof lw_sd = Inputs.range([0, 0.6], {value: 0.3, step: 0.02, label: \"SD of the item residual\"})\nviewof lw_np = Inputs.range([50, 2000], {value: 316, step: 1, label: \"Respondents\"})\n```\n\n```{ojs}\n//| echo: false\nlw = lltmWorld(lw_sd, lw_np)\nPlot.plot({\n  width: 700, height: 320, x: {label: \"Easiness predicted by the features\"}, y: {label: \"Item's easiness\"},\n  color: {legend: true, domain: [\"do\", \"want\"], range: [palette.main, palette.contrast]},\n  marks: [\n    Plot.line([[-2.2, -2.2], [2.2, 2.2]], {stroke: palette.guide, strokeDasharray: \"4 3\"}),\n    Plot.dot(lw.items, {x: \"pred\", y: \"easy\", r: 5, fill: \"mode\", title: \"name\"})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`The features explain **${(100 * lw.r2).toFixed(0)}%** of the variance in easiness. With ${lw_np} respondents, the likelihood-ratio test of the LLTM against the Rasch model would give a χ² of about **${lw.chisq.toFixed(0)}** on ${lw.df} df (p ≈ ${pchisqUpper(lw.chisq, lw.df).toPrecision(2)}).`\n```\n\nAt an SD of 0 the dots sit on the line and the expected χ² equals its 19 df. At 0.3 the features still explain more than nine tenths of the variance, and with 316 respondents the test rejects the LLTM overwhelmingly. More respondents raise the χ² and leave the share explained alone: the test weighs the distance from the line against the precision of each estimate. (The widget's χ² is its expected value: the df plus the squared residuals weighted by each item's information.)\n\nSo what should we conclude when the features explain nearly everything and the test says no? That items differ in ways the features don't capture, as items written by people almost always will. Rather than set those differences to zero, a model can give them a variance:\n$$\\beta_i = \\sum_k q_{ik}\\,\\eta_k + \\varepsilon_i, \\qquad \\varepsilon_i \\sim N(0, \\sigma^2_\\varepsilon).$$\nThis is the LLTM with an **item residual** ([Janssen, Schepers & Peres, 2004](https://doi.org/10.1007/978-1-4757-3990-9_6)): the items are now random effects around the design's prediction, and $\\sigma_\\varepsilon$ says how much the features leave unexplained. In `glmer` it is one more term, `(1 | item)`. Items and respondents are then both random, and **crossed**, since every respondent meets every item ([Van den Noortgate, De Boeck & Meulders, 2003](https://doi.org/10.3102/10769986028004369)).\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: the LLTM keeps the sum score sufficient\n\n**Assumptions:** respondents $j = 1, \\dots, J$ answer dichotomous items $i = 1, \\dots, I$; the Rasch model holds with easiness $\\beta_i = \\sum_{k=1}^K q_{ik}\\eta_k$ for a known $I \\times K$ matrix $Q$ of full column rank, $K < I$; responses are locally independent given $\\theta$; $\\eta$ and the $\\theta_j$ are fixed.\n\nWrite $r_j = \\sum_i x_{ij}$ for respondent $j$'s sum score and $s_i = \\sum_j x_{ij}$ for item $i$'s total. The probability of the whole data matrix is\n$$\\Pr(\\mathbf{X}) = \\prod_{j,i} \\frac{e^{x_{ij}(\\theta_j + \\beta_i)}}{1 + e^{\\theta_j + \\beta_i}} = \\frac{\\exp\\big(\\sum_j r_j \\theta_j + \\sum_i s_i \\beta_i\\big)}{\\prod_{j,i}\\big(1 + e^{\\theta_j + \\beta_i}\\big)}.$$\nSubstitute the constraint: $\\sum_i s_i \\beta_i = \\sum_i s_i \\sum_k q_{ik}\\eta_k = \\sum_k \\eta_k t_k$, with $t_k = \\sum_i q_{ik} s_i$ the number of 1s given to items with feature $k$. So\n$$\\Pr(\\mathbf{X}) = \\frac{\\exp\\big(\\sum_j r_j \\theta_j + \\sum_k t_k \\eta_k\\big)}{\\prod_{j,i}\\big(1 + e^{\\theta_j + \\beta_i}\\big)}.$$\nTwo things follow. The data meet $\\theta_j$ only through $r_j$, so the sum score is still sufficient for $\\theta$, and conditioning on it removes $\\theta$ exactly as in [The Rasch model](rasch.qmd); conditional maximum likelihood for the $\\eta_k$ follows ([Fischer, 1973](https://doi.org/10.1016/0001-6918(73)90003-6)). And the data meet the design effects only through the $K$ feature totals $t_k$: the LLTM uses the item totals only through their sums over the items that share a feature. That is the sense in which it is a Rasch model *with a linear constraint*, and why the likelihood-ratio test against the unconstrained Rasch model loses one degree of freedom for each item parameter the constraint removes ($I - K$ with this lesson's marginal fits, which estimate $\\sigma_\\theta$ in both models).\n\nAdding an item residual changes the second part and not the first. For the items actually drawn the model is still a Rasch model, so $r_j$ remains sufficient for $\\theta_j$; but the $\\varepsilon_i$ are random and integrated out of the likelihood, and the $t_k$ are no longer sufficient for $\\eta$.\n:::\n\n#### Try it: items in families\n\nItems often come in families: four items per grammatical construct, or clones from one template ([Glas & van der Linden, 2003](https://doi.org/10.1177/0146621603027004001)). Fixed or random? It depends on the question ([De Boeck, 2008](https://doi.org/10.1007/s11336-008-9092-x)): fixed if we care about *these* items, random if they stand for items that could have been written and a new form will draw new ones. Then what matters is how much variation lies between families and how much within.\n\n```{ojs}\n//| echo: false\nviewof fm_between = Inputs.range([0, 3], {value: 2.4, step: 0.05, label: \"SD of difficulty between families\"})\nviewof fm_within = Inputs.range([0.05, 1.5], {value: 0.6, step: 0.05, label: \"SD of difficulty within a family\"})\n```\n\n```{ojs}\n//| echo: false\nfm_new = Math.sqrt(fm_between ** 2 + fm_within ** 2)\nfm_data = grid(-7, 7, 281).flatMap(b => [\n  {b, density: dnorm(b, 0, fm_within), which: \"New item, known family\"},\n  {b, density: dnorm(b, 0, fm_new), which: \"New item, new family\"}])\nPlot.plot({\n  width: 700, height: 260, x: {label: \"Difficulty of the next item written (logits, from its family's or the test's average)\"}, y: {label: \"Density\"},\n  color: {legend: true, domain: [\"New item, known family\", \"New item, new family\"], range: [palette.main, palette.contrast]},\n  marks: [Plot.line(fm_data, {x: \"b\", y: \"density\", stroke: \"which\", strokeWidth: 2.5})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Share of item variance between families: **${(100 * fm_between ** 2 / (fm_between ** 2 + fm_within ** 2)).toFixed(0)}%**. A new item from a known family has a 95% range of ±${(1.96 * fm_within).toFixed(2)} logits around its family's difficulty; from a new family, ±${(1.96 * fm_new).toFixed(2)} around the test's average.`\n```\n\nThe defaults are close to the TROG grammar test below. Most of the variation is between families, so an item's family pins down its difficulty, and a new family is a far larger gamble. Set the between-family SD to 0 and the two curves meet.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"An LLTM explains 89% of the variance in 24 item easinesses, yet the likelihood-ratio test against the Rasch model gives $p < 10^{-20}$. What is the best reading?\",\n  options: [\n    {text: \"The features capture most of what makes items differ, but not all, and the data are precise enough to see the rest\", correct: true, why: \"Each easiness is estimated precisely, so small departures from the design add up to a large χ². An item residual puts a size on what is left.\"},\n    {text: \"The features are unrelated to difficulty\", correct: false, why: \"89% is most of the variance. The test rejects the claim that the features explain *all* of it.\"},\n    {text: \"The Rasch model doesn't fit\", correct: false, why: \"The test compares the LLTM with the Rasch model; it says nothing about whether the Rasch model itself fits.\"}\n  ]\n})\n```\n\n### Person predictors\n\nAdd a respondent covariate and the random intercept becomes a residual around a regression:\n$$\\theta_j = \\sum_m \\gamma_m z_{jm} + \\delta_j, \\qquad \\delta_j \\sim N(0, \\sigma^2_\\delta).$$\nThe $\\gamma_m$ are differences in $\\theta$, estimated inside the measurement model rather than by scoring everyone and then regressing the scores, which carries each score's error into the regression (a reasonable shortcut when scores are precise, as on a long test). This is **latent regression** ([Mislevy, 1987](https://doi.org/10.1177/014662168701100106); [Zwinderman, 1991](https://doi.org/10.1007/BF02294492)); in `glmer`, `resp ~ 0 + item + grade + (1 | id)`.\n\n### What is an item? Trials and local dependence\n\nIn a cognitive task, what counts as an item is less clear. In the hearts and flowers task ([Davidson, Amso, Anderson & Diamond, 2006](https://doi.org/10.1016/j.neuropsychologia.2006.02.006)), a child presses a key on the same side as a heart, or the side opposite a flower. The obvious items are shape × side, four of them, each met dozens of times. But a flower right after a heart means switching rules, which carries a cost ([Monsell, 2003](https://doi.org/10.1016/S1364-6613(03)00028-7)). Is it the same item as a flower after a flower?\n\n#### Try it: the switch cost\n\n```{ojs}\n//| echo: false\nviewof sw_cost = Inputs.range([0, 1.5], {value: 0.6, step: 0.05, label: \"Switch cost (logits)\"})\nviewof sw_theta = Inputs.range([-3, 3], {value: 0, step: 0.1, label: \"A child's θ\"})\n```\n\n```{ojs}\n//| echo: false\nsw_b = -1.8\nsw_data = grid(-4, 4).flatMap(t => [\n  {theta: t, p: p2pl(t, sw_b), trial: \"Flower after flower\"},\n  {theta: t, p: p2pl(t, sw_b + sw_cost), trial: \"Flower after heart\"}])\nPlot.plot({\n  width: 700, height: 280, x: {label: \"Ability θ\"}, y: {label: \"P(correct)\", domain: [0, 1]},\n  color: {legend: true, domain: [\"Flower after flower\", \"Flower after heart\"], range: [palette.main, palette.contrast]},\n  marks: [Plot.ruleX([sw_theta], {stroke: palette.guide, strokeDasharray: \"4 3\"}),\n          Plot.line(sw_data, {x: \"theta\", y: \"p\", stroke: \"trial\", strokeWidth: 2.5})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`At θ = ${sw_theta.toFixed(1)}: P(correct) is **${p2pl(sw_theta, sw_b).toFixed(2)}** after a flower and **${p2pl(sw_theta, sw_b + sw_cost).toFixed(2)}** after a heart, a gap of ${(p2pl(sw_theta, sw_b) - p2pl(sw_theta, sw_b + sw_cost)).toFixed(2)}.`\n```\n\nA switch cost shifts the curve to the right. The gap in probability shrinks toward the ceiling, where most children below sit, so a cost constant in logits looks smaller in proportions correct. A trial covariate such as *switch* is an item predictor that redefines the item as the stimulus in its context; an item late in a booklet may likewise not be the item it was elsewhere.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Linking and equating](equating.qmd): TIMSS items were 0.077 logits harder in a booklet's second block. In an explanatory model, position is one more item predictor.\n:::\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd): responses are assumed locally independent given $\\theta$. Two items that share a reading passage were the example of how this can fail.\n:::\n\nRandom effects give local dependence a model. A respondent may do better on one family than their $\\theta$ predicts, and all its items move together. A random effect for each respondent × family, `(1 | id:family)`, captures the shift: given $\\theta$ alone a family's items are dependent; given $\\theta$ and the family effect, independent again. This is the testlet model ([Bradlow, Wainer & Wang, 1999](https://doi.org/10.1007/BF02294533)) in a Rasch form, and its SD against the SD of $\\theta$ says how much of a respondent's standing is specific to a family.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Generalizability theory](g-theory.qmd): each facet and interaction was a random intercept in `lme4`. With a logit link the same formulas give the models here; `id:family` plays the part of person × task.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: crossed random effects and the marginal likelihood\n\n**Assumptions:** the Rasch model as a mixed model, $\\text{logit}\\Pr(x_{ij} = 1) = \\theta_j + \\beta_i$, with $\\theta_j \\sim N(0, \\sigma^2_\\theta)$ independent across respondents, and (for random items) $\\beta_i = \\mu + \\varepsilon_i$ with $\\varepsilon_i \\sim N(0, \\sigma^2_\\varepsilon)$ independent of $\\theta$.\n\n**Fixed items.** The random effects are integrated out, which leaves the *marginal* likelihood of the fixed parameters,\n$$L(\\beta, \\sigma_\\theta) = \\prod_j \\int \\prod_i \\Pr(x_{ij} \\mid \\theta, \\beta_i)\\, \\phi(\\theta; 0, \\sigma^2_\\theta)\\, d\\theta.$$\nIt factors into one-dimensional integrals, one per respondent. `mirt` evaluates each by quadrature inside the EM algorithm ([Bock & Aitkin, 1981](https://doi.org/10.1007/BF02293801)). `glmer` instead uses the **Laplace approximation**: find the peak of each integrand and replace the integrand by a normal curve with the same peak and curvature (the curvature is the information of [The likelihood and logistic regression](likelihood.qmd)). With 24 responses per respondent the integrand is close to normal and the approximation is good. On the verbal aggression data the two routes agree closely:\n\n\n::: {.cell}\n\n:::\n\n\nThe easinesses differ by at most 0.001, and the SDs of $\\theta$ are 1.385 (`mirt`) and 1.378 (`glmer`).\n\n**Random items.** Now the integral is over all the $\\theta_j$ and all the $\\varepsilon_i$ at once, $J + I$ dimensions, and it does not factor, because every response involves one of each. Quadrature over hundreds of dimensions is out of reach; the Laplace approximation, applied to the whole vector of random effects, is what makes crossed models practical ([Tuerlinckx, Rijmen, Verbeke & De Boeck, 2006](https://doi.org/10.1348/000711005X79857)). `glmer` offers adaptive quadrature (its `nAGQ` argument) only for models with a single scalar random effect ([lme4 documentation](https://rdrr.io/cran/lme4/man/glmer.html)). The Laplace approximation is least accurate for binary data with few observations per random effect, where it can understate variances ([Joe, 2008](https://doi.org/10.1016/j.csda.2008.05.002)). Here each respondent has 24 responses and each item 316, which is comfortable. A child × block effect in TROG rests on four responses each, so its SD is the estimate to hold most loosely.\n:::\n\n## Simulate\n\nThe code simulates the verbal aggression design with 300 respondents, easinesses following the LLTM plus a residual with SD `sd_item`, and fits the Rasch model, the LLTM and the LLTM with an item residual. The first run takes 30 to 45 seconds, most of it loading `lme4`; `nAGQ = 0` keeps the fits to seconds (delete it in your own R session for the full fit).\n\nWith the seed as written (`sd_item <- 0.3`), the features explain 88% of the Rasch easiness variance, the test gives χ² = 157 on 19 df, and the estimated residual SD is 0.33. Set `sd_item <- 0`: χ² falls to 13 (p = 0.82). At `sd_item <- 0.15` the features explain 96% and the test still rejects (χ² = 57, p ≈ 10⁻⁵). Then keep 0.15 and set `np <- 1000`: the share explained barely changes and the χ² grows.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-18\n# Simulate responses from an LLTM whose items also have a residual of their own,\n# then fit the Rasch model, the LLTM and the LLTM with random items with lme4.\n# The items follow a design like the verbal aggression items: two modes, three\n# behaviours, two situations, two items per cell.\n#\n# nAGQ = 0 makes glmer() skip its slowest step, so all three fits take seconds in\n# the browser; the estimates barely move. In your own R session, delete\n# \", nAGQ = 0\" to get the full Laplace fit (about a minute here).\nlibrary(lme4)\nset.seed(48)\nnp <- 300        # respondents\nsd_item <- 0.3   # SD of the item residual; 0 means the design explains the items fully\n\nitems <- expand.grid(rep = 1:2, mode = c(\"do\", \"want\"),\n                     behav = c(\"curse\", \"scold\", \"shout\"), situ = c(\"other\", \"self\"))\nitems$item <- sprintf(\"i%02d\", seq_len(nrow(items)))\nX <- model.matrix(~ mode + behav + situ, items)\neta <- c(1, 0.7, -1, -2, -1)   # true intercept and design effects (on easiness)\nitems$easy <- drop(X %*% eta) + rnorm(nrow(items), 0, sd_item)\n\ntheta <- rnorm(np, 0, 1.3)\nd <- merge(expand.grid(id = seq_len(np), item = items$item), items)\nd$resp <- rbinom(nrow(d), 1, plogis(theta[d$id] + d$easy))\n\nrasch  <- glmer(resp ~ 0 + item + (1 | id), d, binomial, nAGQ = 0)\nlltm   <- glmer(resp ~ mode + behav + situ + (1 | id), d, binomial, nAGQ = 0)\nlltm_r <- glmer(resp ~ mode + behav + situ + (1 | id) + (1 | item), d, binomial, nAGQ = 0)\n\ncat(\"Design effects: truth and estimates\\n\")\nprint(round(cbind(true = eta, LLTM = fixef(lltm), \"LLTM + residual\" = fixef(lltm_r)), 2))\n\ne <- fixef(rasch)[paste0(\"item\", items$item)]\ncat(\"\\nShare of the Rasch easiness variance the design explains:\",\n    round(cor(e, drop(X %*% fixef(lltm)))^2, 2), \"\\n\")\n\nlr <- anova(lltm, rasch)\ncat(sprintf(\"Likelihood-ratio test, LLTM against Rasch: chi-squared %.1f on %d df, p = %.3g\\n\",\n            lr$Chisq[2], lr$Df[2], lr$`Pr(>Chisq)`[2]))\ncat(sprintf(\"Item residual SD: true %.2f, estimated %.2f\\n\", sd_item,\n            attr(VarCorr(lltm_r)$item, \"stddev\")))\n\n```\n:::\n\n\n[Download this code](code/explanatory-irt-sim.R) to run it as large as you like in your own R session.\n\n## With real data\n\n\n\n[verbagg](https://itemresponsewarehouse.org/tables/verbagg/) is the main example: items built from a design, to be explained. [trog_brinchmann_2019](https://itemresponsewarehouse.org/tables/trog_brinchmann_2019/) is the contrast: items in families, for random items and local dependence. [imps2025_hf](https://itemresponsewarehouse.org/tables/imps2025_hf/) is the case where the obvious definition of an item leaves something out, with a respondent covariate. [Download the code](code/explanatory-irt-irw.R); it needs `lme4`.\n\n### Verbal aggression: explaining the items\n\nThe verbal aggression data come from [De Boeck and Wilson (2004)](https://doi.org/10.1007/978-1-4757-3990-9), who use them throughout their book on explanatory models. As in [Item response data and the IRW](irw-data.qmd), 1 means the reaction was reported (\"perhaps\" or \"yes\"), and one item is stored as `S4wantCurse`, so the code lower-cases the names, which carry the design.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(lme4)\noptions(digits = 7)  # R's default, in case a .Rprofile changes it\n# nloptwrap is much quicker than glmer's default optimizer when a model has many\n# fixed effects, as the Rasch model (one per item) does. The other models have few\n# fixed effects and use the default.\nctl <- glmerControl(optimizer = \"nloptwrap\")\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.verbagg/rows?format=csv\"\nva <- read.csv(url)\nva$item <- tolower(va$item)   # one item is stored as S4wantCurse\n# The item name carries the design: situation 1-4, want or do, and a behaviour.\nva$behav <- factor(sub(\".*(curse|scold|shout)$\", \"\\\\1\", va$item))\nva$mode  <- factor(ifelse(grepl(\"want\", va$item), \"want\", \"do\"), levels = c(\"do\", \"want\"))\nva$situ  <- factor(ifelse(grepl(\"^s[12]\", va$item), \"other\", \"self\"))  # who is to blame\nitems <- unique(va[, c(\"item\", \"situ\", \"mode\", \"behav\")])\nitems <- items[order(items$item), ]\nrownames(items) <- NULL\nc(respondents = length(unique(va$id)), items = nrow(items), responses = nrow(va))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents       items   responses \n        316          24        7584 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nhead(items, 6)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|item        |situ  |mode |behav |\n|:-----------|:-----|:----|:-----|\n|s1docurse   |other |do   |curse |\n|s1doscold   |other |do   |scold |\n|s1doshout   |other |do   |shout |\n|s1wantcurse |other |want |curse |\n|s1wantscold |other |want |scold |\n|s1wantshout |other |want |shout |\n\n</div>\n:::\n:::\n\n\nThe same data ship with `lme4` as `VerbAgg`, to which [De Boeck et al. (2011)](https://doi.org/10.18637/jss.v039.i12) fit these models, so first we check that the copies agree:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Sanity check: the same data ship with lme4 (VerbAgg, with r2 = \"Y\" when the\n# answer was perhaps or yes). If the item proportions agree, the models below\n# can be checked against De Boeck et al. (2011), who fit them to VerbAgg.\np_irw <- tapply(va$resp, va$item, mean)\np_lme4 <- tapply(VerbAgg$r2 == \"Y\", tolower(VerbAgg$item), mean)\nall.equal(p_irw, p_lme4[names(p_irw)], check.attributes = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nThey do, item for item. Now the Rasch model, as a regression:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The Rasch model as a mixed logistic regression: a fixed intercept for each item\n# (its easiness, so b = -coefficient) and a random intercept for each respondent\n# (theta, with mean 0 and an SD to estimate).\nrasch <- glmer(resp ~ 0 + item + (1 | id), data = va, family = binomial, control = ctl)\neasy <- fixef(rasch)\nnames(easy) <- sub(\"^item\", \"\", names(easy))\nround(head(sort(easy), 3), 2)   # the hardest items: all three about shouting\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  s3doshout   s4doshout s3wantshout \n      -2.97       -2.00       -1.52 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tail(sort(easy), 3), 2)   # the easiest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  s1docurse s1wantcurse s2wantcurse \n       1.22        1.22        1.75 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nVarCorr(rasch)                  # SD of theta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups Name        Std.Dev.\n id     (Intercept) 1.3787  \n```\n\n\n:::\n:::\n\n\nThe hardest items to endorse are about shouting, most of all *doing* it when you are to blame, and the easiest are about cursing. The SD of $\\theta$ is 1.38. Now the LLTM:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The LLTM: 24 easinesses replaced by an intercept and four design effects.\nlltm <- glmer(resp ~ behav + situ + mode + (1 | id), data = va, family = binomial)\nround(fixef(lltm), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  behavscold  behavshout    situself    modewant \n       1.07       -1.06       -2.04       -1.03        0.67 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nVarCorr(lltm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups Name        Std.Dev.\n id     (Intercept) 1.3389  \n```\n\n\n:::\n:::\n\n\nEach feature does what the descriptive look suggested: against cursing, scolding costs 1.06 logits and shouting 2.04; being to blame yourself costs 1.03; *want* adds 0.67 over *do*. How well do five parameters do in place of 24?\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"The five LLTM parameters reproduce the 24 Rasch easinesses with a correlation of 0.94, so they explain 89% of their variance. Will the likelihood-ratio test of the LLTM against the Rasch model accept it?\",\n  choices: [\"Yes, comfortably (p > 0.5)\", \"Borderline (p near 0.05)\", \"No, decisively\"],\n  answer: \"No, decisively\",\n  reveal: \"χ² = 159 on 19 df: the LLTM is rejected. With 316 respondents each easiness is estimated precisely enough that the 11% left over is far more than chance. The test comes first below, then the explained share.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nanova(lltm, rasch)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      | npar|      AIC|      BIC|    logLik| -2*log(L)|    Chisq| Df| Pr(>Chisq)|\n|:-----|----:|--------:|--------:|---------:|---------:|--------:|--:|----------:|\n|lltm  |    6| 8249.935| 8291.537| -4118.967|  8237.935|       NA| NA|         NA|\n|rasch |   25| 8128.511| 8301.855| -4039.255|  8078.511| 159.4241| 19|          0|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# How much of the Rasch easiness does the design account for?\nX <- model.matrix(~ behav + situ + mode, items)\npred <- drop(X %*% fixef(lltm))\ne <- easy[items$item]\nround(c(r = cor(e, pred), r_squared = cor(e, pred)^2), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        r r_squared \n     0.94      0.89 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nplot(pred, e, pch = 19, col = \"#2780e3\",\n     xlab = \"Easiness predicted by the design (LLTM)\", ylab = \"Easiness from the Rasch model\")\nabline(lm(e ~ pred), lty = 2)\nfar <- order(-abs(resid(lm(e ~ pred))))[1:3]\ntext(pred[far], e[far], items$item[far], pos = 4, cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](explanatory-irt_files/figure-html/explained-1.png){width=576}\n:::\n:::\n\n\nχ² = 159 on 19 df, and the AIC prefers the Rasch model (8,129 against 8,250), yet the design explains 89% of the variance in the Rasch easinesses (r = 0.94; the labelled items sit furthest from the line). As in the widget, both are true. An item residual gives the remainder a size:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The LLTM with an item residual: items scatter around the design's prediction\n# with an SD to estimate.\nlltm_r <- glmer(resp ~ behav + situ + mode + (1 | id) + (1 | item), data = va,\n                family = binomial)\nround(fixef(lltm_r), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  behavscold  behavshout    situself    modewant \n       1.07       -1.06       -2.10       -1.05        0.71 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nVarCorr(lltm_r)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups Name        Std.Dev.\n id     (Intercept) 1.37153 \n item   (Intercept) 0.34232 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nAIC(rasch, lltm, lltm_r)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|       | df|      AIC|\n|:------|--:|--------:|\n|rasch  | 25| 8128.511|\n|lltm   |  6| 8249.935|\n|lltm_r |  7| 8163.826|\n\n</div>\n:::\n:::\n\n\nThe residual SD is 0.34, against 1.37 for $\\theta$: items scatter around the design's prediction by about a quarter of the spread of respondents. The feature effects barely move, and the AIC (8,164, with 7 parameters) falls between the LLTM's and the Rasch model's.\n\nSo which would I fit? It turns on one assumption: that the features are all there is to an item, which holds only when items were generated from the features by rule. Otherwise I'd fit the LLTM with an item residual, not without it: real items always leave something over, and the residual SD says how much. The Rasch model describes these 24 items best; the LLTM with a residual says what makes them differ, and how far that account falls short.\n\n::: {.callout-note collapse=\"true\"}\n## Wanting, doing and inhibition: an interaction\n\nDoes the gap between wanting and doing depend on the behaviour, as it seemed to in [Item response data and the IRW](irw-data.qmd)? An interaction answers:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Is the gap between wanting and doing the same for every behaviour?\nlltm_ri <- glmer(resp ~ behav * mode + situ + (1 | id) + (1 | item), data = va,\n                 family = binomial)\nround(coef(summary(lltm_ri))[, 1:2], 2)   # estimates and standard errors\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Estimate Std. Error\n(Intercept)             1.17       0.19\nbehavscold             -1.03       0.23\nbehavshout             -2.45       0.24\nmodewant                0.50       0.23\nsituself               -1.05       0.13\nbehavscold:modewant    -0.06       0.33\nbehavshout:modewant     0.69       0.33\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nVarCorr(lltm_ri)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups Name        Std.Dev.\n id     (Intercept) 1.37152 \n item   (Intercept) 0.29731 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nanova(lltm_r, lltm_ri)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|        | npar|      AIC|      BIC|    logLik| -2*log(L)|   Chisq| Df| Pr(>Chisq)|\n|:-------|----:|--------:|--------:|---------:|---------:|-------:|--:|----------:|\n|lltm_r  |    7| 8163.826| 8212.362| -4074.913|  8149.826|      NA| NA|         NA|\n|lltm_ri |    9| 8162.174| 8224.578| -4072.087|  8144.174| 5.65189|  2|  0.0592526|\n\n</div>\n:::\n:::\n\n\nThe want–do gap for shouting is 0.69 logits larger than for cursing (SE 0.33); scolding matches cursing (−0.06). [Smits, De Boeck and Vansteelandt (2004)](https://doi.org/10.1002/per.529) study this gap as the inhibition of verbal aggression, and on that reading shouting is held back most. The evidence is modest: with the item residual in the model, the test of the two interaction terms gives p = 0.059, since four items per cell leave little to test with once items may differ.\n:::\n\n### TROG: items in families\n\nThe Test for Reception of Grammar ([Bishop, 1979](https://doi.org/10.1111/j.1469-8749.1979.tb01605.x)) tests the understanding of grammar in blocks of four items, one block per grammatical construct: the child hears a sentence and picks the matching picture. These are 210 Norwegian children at the first assessment of a longitudinal study ([Brinchmann, Braeken & Lyster, 2019](https://doi.org/10.1111/desc.12709)), distributed with the `mokken` R package ([van der Ark, 2007](https://doi.org/10.18637/jss.v020.i11)). The test is copyrighted, so we refer to blocks by their letters, a to t. Keying: 1 is correct.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl_trog <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_2:v24_0.trog_brinchmann_2019/rows?format=csv\"\ntr <- read.csv(url_trog)\n# item_family numbers the 20 blocks of four items; the item names (a1 to t4) use letters.\ntr$family <- factor(letters[tr$item_family], levels = letters[1:20])\nc(children = length(unique(tr$id)), items = length(unique(tr$item)),\n  families = nlevels(tr$family), missing = 210 * 80 - nrow(tr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchildren    items families  missing \n     210       80       20        0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(tr$resp, tr$family, mean), 2)   # proportion correct, block by block\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   a    b    c    d    e    f    g    h    i    j    k    l    m    n    o    p \n0.95 0.92 0.87 0.85 0.82 0.70 0.61 0.57 0.52 0.46 0.40 0.29 0.30 0.28 0.08 0.22 \n   q    r    s    t \n0.19 0.15 0.14 0.07 \n```\n\n\n:::\n:::\n\n\nNothing is missing; the blocks run roughly from easy (a, 0.95 correct) to hard. Treat items and blocks as random:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Items and blocks both random: how much of item difficulty lies between blocks?\ng1 <- glmer(resp ~ 1 + (1 | id) + (1 | family) + (1 | item), data = tr,\n            family = binomial)\nv1 <- as.data.frame(VarCorr(g1))\nv1 <- setNames(v1$vcov, v1$grp)\nround(v1, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    id   item family \n  3.79   0.35   5.90 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(share_between_blocks = v1[[\"family\"]] / (v1[[\"family\"]] + v1[[\"item\"]])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nshare_between_blocks \n                0.94 \n```\n\n\n:::\n:::\n\n\nThe variance of difficulty is 5.90 between blocks and 0.35 within them: 94% lies between blocks, as a test built from constructs should show. For new items written for the same constructs, the within-block SD of about 0.6 (the square root of 0.35) is the uncertainty about each.\n\nAre a block's four items independent given $\\theta$? Add a child × block effect:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# A child x block random effect: a child's standing can shift from block to\n# block, so the four items of a block are not independent given theta.\ng2 <- glmer(resp ~ 1 + (1 | id) + (1 | family) + (1 | item) + (1 | id:family),\n            data = tr, family = binomial)\nVarCorr(g2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups    Name        Std.Dev.\n id:family (Intercept) 1.06931 \n id        (Intercept) 2.20577 \n item      (Intercept) 0.67015 \n family    (Intercept) 2.80615 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nanova(g1, g2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   | npar|      AIC|      BIC|    logLik| -2*log(L)|    Chisq| Df| Pr(>Chisq)|\n|:--|----:|--------:|--------:|---------:|---------:|--------:|--:|----------:|\n|g1 |    4| 12041.89| 12072.81| -6016.946|  12033.89|       NA| NA|         NA|\n|g2 |    5| 11800.29| 11838.93| -5895.143|  11790.29| 243.6067|  1|          0|\n\n</div>\n:::\n:::\n\n\nThe AIC falls from 12,042 to 11,800 (χ² = 244 on 1 df), and the child × block SD is 1.07, against 2.21 for $\\theta$: some children understand a construct better or worse than their overall level predicts, and the block's four items move together. Local independence given $\\theta$ doesn't hold, and the model says by how much.\n\n### Hearts and flowers: what is an item?\n\n[Obradović, Sulik, Finch and Tirado-Strayer (2018)](https://doi.org/10.1016/j.appdev.2017.03.003) validated a tablet version of hearts and flowers for classrooms; the IRW table also holds preschool data from [DeJoseph, Merculief, Sulik and Obradović (2025)](https://doi.org/10.1080/10409289.2025.2578816). We use grades 3 to 5, in the block that mixes hearts and flowers. Keying: 1 is a correct key press.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl_hf <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_2:v24_0.imps2025_hf/rows?format=csv\"\nhf <- read.csv(url_hf)\n# The mixed block of the grades 3-5 cohort: hearts and flowers in random order.\nhf <- hf[hf$cohort == \"plus\" & hf$block == \"mixed test\", ]\nc(trials = nrow(hf), children = length(unique(hf$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  trials children \n   31394      806 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(grade = hf$cov_grade[!duplicated(hf$id)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngrade\n  3   4   5 \n275 356 175 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(hf$resp, hf$item, mean), 2)   # the four \"items\": shape x side\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n flower left flower right   heart left  heart right \n        0.86         0.84         0.83         0.82 \n```\n\n\n:::\n:::\n\n\nTaken as shape × side, the four items are nearly alike: 0.82 to 0.86 correct. But what came just before?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# What came just before? Look up trial n - 1 in the same session and block.\nkey <- paste(hf$id, hf$time, hf$trial_num)\nhf$prev <- hf$stim_shape[match(paste(hf$id, hf$time, hf$trial_num - 1), key)]\nhf$switch <- as.integer(hf$stim_shape != hf$prev)\ntable(switch = hf$switch, useNA = \"ifany\")   # NA: the previous trial isn't in the table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nswitch\n    0     1  <NA> \n11239 11109  9046 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(hf$resp, list(shape = hf$stim_shape, switch = hf$switch), mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        switch\nshape       0    1\n  flower 0.89 0.83\n  heart  0.87 0.80\n```\n\n\n:::\n:::\n\n\nA gentle note: trials with no response inside the time limit were dropped in processing, and the IRW holds back a random share of trials ([processing script](https://github.com/ben-domingue/irw/blob/main/data/imps2025_hf.R)), so for 9,046 trials (the first of each block among them) the previous trial isn't in the table; we set them aside. Among the rest, a switch lowers the proportion correct from 0.89 to 0.83 for flowers and from 0.87 to 0.80 for hearts. Now the model, with grade as a respondent covariate:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nhs <- hf[!is.na(hf$switch), ]\nhs$grade <- factor(hs$cov_grade)\nh0 <- glmer(resp ~ 0 + item + (1 | id), data = hs, family = binomial)\nh1 <- glmer(resp ~ 0 + item + switch + grade + (1 | id), data = hs, family = binomial)\nround(fixef(h1), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n itemflower left itemflower right   itemheart left  itemheart right \n            2.22             2.12             2.02             1.98 \n          switch           grade4           grade5 \n           -0.59             0.20             0.48 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nVarCorr(h1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups Name        Std.Dev.\n id     (Intercept) 0.8865  \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nAIC(h0, h1)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   | df|      AIC|\n|:--|--:|--------:|\n|h0 |  5| 18108.58|\n|h1 |  8| 17872.26|\n\n</div>\n:::\n:::\n\n\nA switch costs 0.59 logits, more than twice the whole spread among the four shape × side items (2.22 to 1.98), and the AIC falls from 18,109 to 17,872. Grade 4 is 0.20 logits above grade 3 and grade 5 is 0.48, estimated in the same model as the items. What came before moves the probability more than shape or side does: the item is the stimulus in its context. [Trials as items](trials.qmd) takes this further.\n\nFeatures coded by people are one way to explain difficulty. Could an item's text alone predict it? That is deep dive #25, which [AI and psychometrics](ai-psychometrics.qmd) takes across the IRW, with this lesson's LLTM as the human-coded baseline.\n\n## Problems\n\n1. **The LLTM as a constrained Rasch model.** Write the verbal aggression LLTM as $b_i = -\\sum_k q_{ik}\\eta_k$, give the $24 \\times 5$ matrix $Q$, and count both models' parameters. Why can't `glmer(resp ~ 0 + item + mode + (1 | id))` estimate an effect of *mode*?\n2. **Inhibition by situation.** Is the want–do gap larger when someone else is to blame? Fit `mode * situ` with the item residual and say what the interaction means for inhibition. Can two items per cell support the three-way interaction?\n3. **Fixed or random?** For TROG, argue for fixed items if the goal is these 210 children's scores on this form, and for random items if a new form will draw new items from the same 20 constructs. What changes in what you report? What if the new form uses new constructs?\n4. **Design a bank.** For 60 arithmetic word problems for grades 3 to 5, choose three to five features you expect to drive difficulty and say how you would code them. What model would you fit after piloting, and how would you judge whether the features predict new items' difficulty well enough to skip piloting them?\n5. **The time limit.** In the grades 3–5 data the time limit was 0.75 s in the fall and 1.25 s in the spring (`time_limit`). Does the switch cost depend on it? Why is this not a clean experiment on the time limit?\n6. **Challenge (open).** When is a trial \"the same item\" twice? A flower after two hearts may differ from a flower after one, and the fortieth trial from the fifth. Propose a criterion and test it on these data (say, items defined by shape × side, by shape × switch, and by shape × switch × run length). What would convince you that you had the right definition?\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22What%20is%20an%20item%3F%20Explanatory%20item%20response%20models%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20explanatory%20item%20response%20models%20fit%20as%20generalized%20linear%20mixed%20models%20with%20lme4%27s%20glmer%3A%20the%20Rasch%20model%20as%20a%20mixed%20logistic%20regression%2C%20the%20linear%20logistic%20test%20model%20%28LLTM%29%2C%20why%20item%20features%20can%20explain%20most%20of%20the%20variation%20in%20difficulty%20and%20still%20be%20rejected%20by%20a%20likelihood-ratio%20test%2C%20items%20as%20random%20effects%20%28an%20item%20residual%2C%20item%20families%29%2C%20latent%20regression%20with%20respondent%20covariates%2C%20and%20local%20dependence%20modelled%20with%20a%20person-by-family%20random%20effect%2C%20with%20verbal%20aggression%20items%2C%20the%20TROG%20grammar%20test%20and%20the%20hearts%20and%20flowers%20task%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- De Boeck, P., & Wilson, M. (Eds.). (2004). *Explanatory item response models: A generalized linear and nonlinear approach*. Springer. <https://doi.org/10.1007/978-1-4757-3990-9>. The book this lesson follows. Its chapters by [Wilson & De Boeck](https://doi.org/10.1007/978-1-4757-3990-9_2) and [Janssen, Schepers & Peres](https://doi.org/10.1007/978-1-4757-3990-9_6) cover descriptive vs. explanatory models and item predictors with a residual.\n- De Boeck, P., Bakker, M., Zwitser, R., Nivard, M., Hofman, A., Tuerlinckx, F., & Partchev, I. (2011). The estimation of item response models with the lmer function from the lme4 package in R. *Journal of Statistical Software*, 39(12). <https://doi.org/10.18637/jss.v039.i12>. The `lme4` formulas for the models here, fit to the same verbal aggression data.\n- Rijmen, F., Tuerlinckx, F., De Boeck, P., & Kuppens, P. (2003). A nonlinear mixed model framework for item response theory. *Psychological Methods*, 8(2), 185–205. <https://doi.org/10.1037/1082-989X.8.2.185>. Item response models as mixed models, in general.\n- Fischer, G. H. (1973). The linear logistic test model as an instrument in educational research. *Acta Psychologica*, 37(6), 359–374. <https://doi.org/10.1016/0001-6918(73)90003-6>. The LLTM and its conditional estimation.\n- De Boeck, P. (2008). Random item IRT models. *Psychometrika*, 73(4), 533–559. <https://doi.org/10.1007/s11336-008-9092-x>. When and why to treat items as random.\n- Van den Noortgate, W., De Boeck, P., & Meulders, M. (2003). Cross-classification multilevel logistic models in psychometrics. *Journal of Educational and Behavioral Statistics*, 28(4), 369–386. <https://doi.org/10.3102/10769986028004369>. Respondents and items as crossed random effects.\n- Embretson, S. E. (1998). A cognitive design system approach to generating valid tests: Application to abstract reasoning. *Psychological Methods*, 3(3), 380–396. <https://doi.org/10.1037/1082-989X.3.3.380>. Item features as a tool for writing items, not only for explaining them.\n- Bradlow, E. T., Wainer, H., & Wang, X. (1999). A Bayesian random effects model for testlets. *Psychometrika*, 64(2), 153–168. <https://doi.org/10.1007/BF02294533>. The testlet model for items that share a context.\n- Tuerlinckx, F., Rijmen, F., Verbeke, G., & De Boeck, P. (2006). Statistical inference in generalized linear mixed models: A review. *British Journal of Mathematical and Statistical Psychology*, 59(2), 225–255. <https://doi.org/10.1348/000711005X79857>. How the marginal likelihood is approximated, and what each approximation costs.\n- Janssen, R. (2016). Linear logistic models. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 211–224). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315374512>. A handbook chapter on the linear logistic test model and related models.\n- De Boeck, P., & Wilson, M. R. (2016). Explanatory response models. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 565–580). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315374512>. A handbook chapter on explanatory item response models.\n- Rabe-Hesketh, S., & Skrondal, A. (2016). Generalized linear latent and mixed modeling. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 503–526). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315374512>. A handbook chapter on item response models as generalized linear latent and mixed models.\n- From the IRW: the [item language and difficulty](https://itemresponsewarehouse.org/vignettes/item_text_difficulty.html) vignette asks how far item wording predicts difficulty across many tests, the question [AI and psychometrics](ai-psychometrics.qmd) takes up.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`verbagg`](https://itemresponsewarehouse.org/tables/verbagg/): De Boeck and Wilson (2004), Explanatory Item Response Models, Springer. <https://doi.org/10.1007/978-1-4757-3990-9>. Licence: GPL-3.0.\n- [`trog_brinchmann_2019`](https://itemresponsewarehouse.org/tables/trog_brinchmann_2019/): Brinchmann, E. I., Braeken, J., & Lyster, S.-A. H. (2019). Is there a direct relation between the development of vocabulary and grammar? Developmental Science, 22(1), e12709. <https://doi.org/10.1111/desc.12709>. Licence: GPL-2.0.\n- [`imps2025_hf`](https://itemresponsewarehouse.org/tables/imps2025_hf/): Obradović, J., Sulik, M. J., Finch, J. E., & Tirado-Strayer, N. (2018). Assessing students’ executive functions in the classroom: Validating a scalable group-based procedure. Journal of Applied Developmental Psychology, 55, 4–13. doi:10.1016/j.appdev.2017.03.003 DeJoseph, M. L., Merculief, A., Sulik, M. J., & Obradović, J. (2025). Understanding Learning Variability in Early Childhood: An Equity-Centered Assessment of Cognitive Regulation among Diverse Preschool Children. Early Education and Development, 1–25. <https://doi.org/10.1080/10409289.2025.2578816>. <https://doi.org/10.1016/j.appdev.2017.03.003\n\n10.1080/10409289.2025.2578816>. Licence: Permission via Email.\n\n## For instructors\n\n- **Source:** EDUC 252 class 8 (slides c8, 40–41, on whether we are interested in *these* items) and class 10 (slide 25), problem sets 6 (#2, hearts and flowers) and 7 (#2, part B), and the code in `ben-domingue/252`: `ps6/hf.R` and `ps7/cdm.R` (`c8/lmer_example.R` is empty).\n- **Timing:** the core ideas and widgets take about 45 minutes; the verbal aggression analysis is a 20-minute lab, and TROG and hearts and flowers another 20 between them. The TROG fits take a few minutes, so run them before class.\n- **Changed from 252:** models are fit with `lme4` throughout rather than `mirt`. The LLTM with an item residual on verbal aggression and the TROG families are new; hearts and flowers is PS6#2, with the switch defined from the trial just before in the same block.\n- **Held back:** the Q-matrix as an item design matrix goes to [Latent classes and cognitive diagnosis](cdm.qmd); IRTrees as explanatory models to [IRTree models](irtrees.qmd); continuous stimulus features to [Trials as items](trials.qmd); response time as a second outcome to [Response time and the speed-accuracy tradeoff](response-time.qmd); item text as a predictor of difficulty (deep dive #25) to [AI and psychometrics](ai-psychometrics.qmd). How much the item residual matters to respondents' scores is left open.\n- **Solutions:** held back in `solutions/explanatory-irt.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "explanatory-irt_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}