{
  "hash": "9d5ca83c78ae6caa7cab134b481db370",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Classical test theory and reliability\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Classical test theory  \n**Tranche:** core (a first course)  \n**Before this:** [Constructs and construct maps](constructs.qmd) · [Item response data and the IRW](irw-data.qmd)  \n**Builds toward:** [Where CTT breaks: toward item response models](ctt-limits.qmd) · [Validity as an argument](validity-argument.qmd) · [From construct map to items: building an instrument](instrument-building.qmd) · [Gathering validity evidence](validity-evidence.qmd) · [What does a score mean? Norms, error bands, and cut scores](score-meaning.qmd)  \n**Starts threads:** Alpha is a lower bound on reliability (→ [Where CTT breaks: toward item response models](ctt-limits.qmd) · [Factor analysis I: exploring dimensionality](fa-exploratory.qmd) · [Factor analysis II: confirmatory models, omega, and IRT as factor analysis](fa-confirmatory.qmd) · [Dimensionality and multidimensional IRT](dimensionality.qmd)); One standard error of measurement for everyone (→ [Information, precision, and short forms](information.qmd) · [What does a score mean? Norms, error bands, and cut scores](score-meaning.qmd)); Keying has to be checked; the data can't always tell (→ [From construct map to items: building an instrument](instrument-building.qmd) · [Factor analysis I: exploring dimensionality](fa-exploratory.qmd) · [Models for polytomous responses](polytomous.qmd) · [IRTree models](irtrees.qmd) · [Unfolding models](unfolding.qmd)); Unreliability attenuates correlations (→ [Gathering validity evidence](validity-evidence.qmd) · [Structural equation modeling with lavaan](sem.qmd) · [Fairness in testing: bias, impact, and measurement invariance](fairness.qmd))  \n**Picks up threads:** IRW tables are long: one row per response (from [Item response data and the IRW](irw-data.qmd)); Check keying in the documentation and in the data (from [Item response data and the IRW](irw-data.qmd))  \n**IRW tables:** [`gilbert_meta_1`](https://itemresponsewarehouse.org/tables/gilbert_meta_1/), [`lessR_Mach4`](https://itemresponsewarehouse.org/tables/lessr_mach4/)  \n**From EDUC 252:** slides c2; problem sets PS2#1, PS2#2, PS2#3; code [`c2/alpha.R`](https://github.com/ben-domingue/252/blob/main/c2/alpha.R), [`ps2/itemanalysis.R`](https://github.com/ben-domingue/252/blob/main/ps2/itemanalysis.R), [`ps2/parallel_tests.R`](https://github.com/ben-domingue/252/blob/main/ps2/parallel_tests.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n```{ojs}\n//| echo: false\nimport {rng, cor, grid, palette} from \"./widgets/irt.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nEvery score contains error. A student who scores 27 on a test today might score 25 or 29 tomorrow for reasons that have nothing to do with what the test is meant to measure: a lucky guess, a misread question, a bad night's sleep. [Constructs and construct maps](constructs.qmd) asked what a scale is meant to measure; this lesson asks how precisely it does so. Classical test theory (CTT) is the oldest and still the most widely used framework for thinking about that error. It is a theory of *test scores*, not of item responses: nothing in this lesson refers to the probability of answering any one item correctly. That is both its main convenience and its central limitation. The payoff is **reliability**, a single number that says how much of the variation in scores is signal.\n\nReliability estimates are everywhere. That doesn't mean they are always meaningful, and part of this lesson is about when they are not.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- write down the classical model and define reliability in terms of it;\n- explain why the correlation between two parallel forms estimates reliability;\n- compute Cronbach's alpha, and say why it is a lower bound on reliability (and when it is exact);\n- use split halves and the Spearman–Brown formula;\n- run a classical item analysis and use it to spot items that don't belong, including items that need to be reverse-keyed.\n\n## Core ideas\n\n### True scores and error\n\nCTT grew out of Spearman's attempt to correct correlations for the error in the measures being correlated ([Spearman, 1904](https://doi.org/10.2307/1412159)), and its standard statement is Lord and Novick's (1968). The foundational idea is that a respondent's observed score $X$ is the sum of a **true score** $T$ and an error $E$:\n$$X = T + E.$$\nThe true score is defined as the average score the respondent would get over (hypothetical) endless independent replications of the test; the error is whatever is left. From that definition, errors have mean zero and are uncorrelated with true scores, so the variance splits cleanly:\n$$\\sigma^2_X = \\sigma^2_T + \\sigma^2_E.$$\n**Reliability** is the share of observed-score variance that is true-score variance:\n$$\\rho_{XX'} = \\frac{\\sigma^2_T}{\\sigma^2_X} = \\frac{\\sigma^2_T}{\\sigma^2_T + \\sigma^2_E}.$$\nIt is also the squared correlation between observed and true scores (Lord & Novick, 1968). The trouble, of course, is that we never observe $T$, so this definition cannot be computed from data. The rest of CTT is a set of tricks for getting around that.\n\n### The first trick: parallel forms\n\nSuppose we have two forms of a test, $X$ and $X'$, that measure the same true score with the same error variance and independent errors. What can we say about the correlation between them? A little algebra (problem 1 asks you to do it) shows that\n$$\\text{cor}(X, X') = \\frac{\\sigma^2_T}{\\sigma^2_X} = \\rho_{XX'}.$$\nThe correlation between two observable things equals a quantity defined in terms of an unobservable one. Here is that fact in action.\n\n#### Try it: parallel forms\n\n```{ojs}\n//| echo: false\nviewof pf_se = Inputs.range([0.1, 2.5], {value: 0.7, step: 0.05, label: \"Error SD (true-score SD = 1)\"})\n```\n\n```{ojs}\n//| echo: false\npf = {\n  const r = rng(11), n = 400, T = [], X = [], X2 = [];\n  for (let i = 0; i < n; i++) { const t = r.norm(); T.push(t); X.push(t + pf_se * r.norm()); X2.push(t + pf_se * r.norm()); }\n  return {T, X, X2, pts: X.map((x, i) => ({x, x2: X2[i]}))};\n}\nPlot.plot({\n  width: 460, height: 400, aspectRatio: 1,\n  x: {label: \"Score on form X\", domain: [-6, 6]}, y: {label: \"Score on form X′\", domain: [-6, 6]},\n  marks: [Plot.dot(pf.pts, {x: \"x\", y: \"x2\", r: 2.5, fill: palette.main, fillOpacity: 0.45}), Plot.linearRegressionY(pf.pts, {x: \"x\", y: \"x2\", stroke: palette.contrast})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Reliability from the definition (true-score variance ÷ observed variance): **${(1 / (1 + pf_se ** 2)).toFixed(2)}**.\nCorrelation between the two forms in this sample of 400: **${cor(pf.X, pf.X2).toFixed(2)}**.\nStandard error of measurement (the SD of the errors): **${pf_se.toFixed(2)}**, so a respondent's observed score typically lands within about ±${(2 * pf_se).toFixed(1)} of their true score.`\n```\n\nThe two numbers at the top track each other as the slider moves, up to sampling error in 400 simulated respondents. The **standard error of measurement** in the last line is what reliability means for an individual. Reliability is a property of scores in a population; the standard error of measurement, $\\sigma_E = \\sigma_X\\sqrt{1 - \\rho_{XX'}}$, is the typical distance between one respondent's observed and true scores. A reliability of 0.8, between the two real scales below (0.70 and 0.90), still leaves each score with an error SD of $\\sqrt{1 - 0.8} \\approx 0.45$ times the SD of the scores, nearly half their spread. Note, too, that CTT gives one standard error of measurement for everyone, whatever their score. We will see in [Information, precision, and short forms](information.qmd) that item response models let it vary.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Two parallel forms of a reading test correlate 0.81 in a large sample. What is the reliability of *one* form?\",\n  options: [\n    {text: \"0.81\", correct: true, why: \"For parallel forms, the correlation between them *is* the reliability of each. No square or square root needed.\"},\n    {text: \"0.90, the square root of 0.81\", correct: false, why: \"0.90 is the correlation between observed and true scores, $\\\\sqrt{\\\\rho_{XX'}}$. Reliability itself is the correlation between parallel forms.\"},\n    {text: \"It can't be known without true scores\", correct: false, why: \"That is the point of the parallel-forms trick: two observable scores stand in for the unobservable true score.\"}\n  ]\n})\n```\n\n### Alpha: reliability from one administration\n\nParallel forms are expensive, and test-retest designs have their own problems (respondents remember items, and they change between occasions). The appeal of **Cronbach's alpha** ([Cronbach, 1951](https://doi.org/10.1007/BF02310555)) is that it gives a reliability estimate from a single administration, by treating the items themselves as a set of little parallel tests. For a test of $k$ items with item variances $\\sigma^2_i$ and total-score variance $\\sigma^2_X$,\n$$\\alpha = \\frac{k}{k-1}\\left(1 - \\frac{\\sum_i \\sigma^2_i}{\\sigma^2_X}\\right).$$\nWhen items are scored 0/1, this is the same thing as the Kuder–Richardson formula 20, KR-20 ([Kuder & Richardson, 1937](https://doi.org/10.1007/BF02288391)); Guttman's $\\lambda_3$ is alpha under another name ([Guttman, 1945](https://doi.org/10.1007/BF02288892)). The intuition: if items hang together, the total-score variance is much larger than the sum of the item variances, because the covariances between items add in; if they don't, the two are similar and alpha is small.\n\nAlpha rests on an assumption, though. Which one? Alpha equals reliability when every item measures the true score *equally well* (the items are \"tau-equivalent\"). When some items are better measures than others, which is to say nearly always, alpha is *smaller* than reliability ([Novick & Lewis, 1967](https://doi.org/10.1007/BF02289400)).\n\n#### Try it: when does alpha equal reliability?\n\nSix items, each an equally noisy measure of the same true score, but with loadings on it that you can pull apart.\n\n```{ojs}\n//| echo: false\nviewof al_spread = Inputs.range([0, 1.4], {value: 0, step: 0.05, label: \"How unequal the items are\"})\nviewof al_err = Inputs.range([0.3, 2], {value: 1, step: 0.05, label: \"Error SD per item\"})\n```\n\n```{ojs}\n//| echo: false\nal_calc = (spread, err) => {\n  const k = 6, lam = Array.from({length: k}, (_, i) => 1 + spread * (i - (k - 1) / 2) / ((k - 1) / 2));\n  const S = lam.reduce((u, v) => u + v, 0), varX = S * S + k * err * err;\n  const sumVar = lam.reduce((u, l) => u + l * l + err * err, 0);\n  return {lam, rel: S * S / varX, alpha: k / (k - 1) * (1 - sumVar / varX)};\n}\nal_now = al_calc(al_spread, al_err)\nal_curve = grid(0, 1.4, 71).flatMap(s => { const c = al_calc(s, al_err); return [{s, v: c.rel, what: \"Reliability\"}, {s, v: c.alpha, what: \"Alpha\"}]; })\nPlot.plot({\n  width: 700, height: 300, x: {label: \"How unequal the items are\"}, y: {label: null, domain: [0, 1]},\n  color: {legend: true, domain: [\"Reliability\", \"Alpha\"], range: [palette.main, palette.contrast]},\n  marks: [Plot.line(al_curve, {x: \"s\", y: \"v\", stroke: \"what\", strokeWidth: 2.5}), Plot.ruleX([al_spread], {stroke: palette.guide, strokeDasharray: \"4 3\"})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Item loadings: ${al_now.lam.map(l => l.toFixed(2)).join(\", \")}. Reliability **${al_now.rel.toFixed(3)}**; alpha **${al_now.alpha.toFixed(3)}**${al_spread === 0 ? \", identical, because the items are equally good measures.\" : `, which understates reliability by ${(al_now.rel - al_now.alpha).toFixed(3)}.`}`\n```\n\nWith the error SD at 1, the gap stays under 0.01 until \"How unequal\" passes about 0.5, where the loadings already run from 0.8 to 1.2. Against a reliability near 0.86, that is small, which is part of why alpha has survived. Push the loadings much further apart (at the far right one of them turns negative, an item pointing the wrong way) and the gap grows. But it only ever goes one way.\n\n::: {.callout-note collapse=\"true\"}\n## Proof: alpha is a lower bound on reliability\n\n**Assumptions:** the classical model for each item, $X_i = T_i + E_i$, with errors uncorrelated with each other and with every true score. The result is due to [Novick and Lewis (1967)](https://doi.org/10.1007/BF02289400); Guttman (1945) had shown it for $\\lambda_3$.\n\nWrite the total score as a sum of items, $X = \\sum_{i=1}^k X_i$. The test's true score is $T = \\sum_i T_i$, and its reliability is $\\rho = \\sigma^2_T / \\sigma^2_X$.\n\n**Step 1: rewrite alpha in terms of true scores.** Because errors are uncorrelated with everything else,\n$$\\sigma^2_X = \\sigma^2_T + \\sum_i \\sigma^2_{E_i} \\qquad\\text{and}\\qquad \\sigma^2_{X_i} = \\sigma^2_{T_i} + \\sigma^2_{E_i}.$$\nSubtracting, the error variances cancel:\n$$\\sigma^2_X - \\sum_i \\sigma^2_{X_i} = \\sigma^2_T - \\sum_i \\sigma^2_{T_i}.$$\nSo\n$$\\alpha = \\frac{k}{k-1}\\cdot\\frac{\\sigma^2_X - \\sum_i\\sigma^2_{X_i}}{\\sigma^2_X} = \\frac{k}{k-1}\\cdot\\frac{\\sigma^2_T - \\sum_i\\sigma^2_{T_i}}{\\sigma^2_X}.$$\n\n**Step 2: compare with reliability.** Both $\\alpha$ and $\\rho$ have $\\sigma^2_X$ in the denominator, so $\\alpha \\le \\rho$ exactly when\n$$\\frac{k}{k-1}\\left(\\sigma^2_T - \\sum_i\\sigma^2_{T_i}\\right) \\le \\sigma^2_T \\quad\\Longleftrightarrow\\quad \\sigma^2_T \\le k\\sum_i \\sigma^2_{T_i}.$$\n\n**Step 3: that inequality always holds.** Writing $\\sigma_i$ for the standard deviation of $T_i$,\n$$\\sigma^2_T = \\sum_i\\sum_j \\text{Cov}(T_i, T_j) \\le \\sum_i\\sum_j \\sigma_i\\sigma_j = \\Big(\\sum_i \\sigma_i\\Big)^2 \\le k\\sum_i\\sigma_i^2,$$\nwhere the first inequality uses $|\\text{Cov}(T_i,T_j)| \\le \\sigma_i\\sigma_j$ and the second is the Cauchy–Schwarz inequality. Hence $\\alpha \\le \\rho$. $\\blacksquare$\n\n**When is it exact?** Both inequalities in step 3 are equalities only when every pair of item true scores is perfectly correlated *and* every $\\sigma_i$ is the same, that is, when the items' true scores differ by at most a constant ($T_i = T_j + c_{ij}$). This is **essential tau-equivalence**, the case the widget shows at \"How unequal = 0\". The proof leans on the errors being uncorrelated; if they are correlated (items that share a passage, say), alpha can *overstate* reliability, and the lower-bound guarantee is gone ([Green & Hershberger, 2000](https://doi.org/10.1207/S15328007SEM0702_6)).\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A colleague reports alpha = 0.72 for a 12-item scale and concludes that 'at least 72% of the score variance is true-score variance.' When is that conclusion safe?\",\n  options: [\n    {text: \"Always: alpha is a lower bound\", correct: false, why: \"Only under the classical assumptions, in particular uncorrelated errors. Correlated errors (items sharing a stem, a passage, a method) can push alpha *above* reliability.\"},\n    {text: \"When the item errors are uncorrelated\", correct: true, why: \"That's the assumption the proof needs. Given it, alpha ≤ reliability, with equality only for (essentially) tau-equivalent items.\"},\n    {text: \"Only when the scale is unidimensional\", correct: false, why: \"Unidimensionality isn't what the proof uses. Alpha can be high for a multidimensional scale; it is not a test of unidimensionality.\"}\n  ]\n})\n```\n\n### Split halves and the Spearman–Brown formula\n\nAn older route to a single-administration estimate is to split the test into two halves, score each, and correlate them. The halves are only half as long as the test, though, and shorter tests are less reliable. The **Spearman–Brown** formula ([Spearman, 1910](https://doi.org/10.1111/j.2044-8295.1910.tb00206.x); [Brown, 1910](https://doi.org/10.1111/j.2044-8295.1910.tb00207.x)) says how reliability changes when a test is lengthened (or shortened) by a factor $m$ with comparable items:\n$$\\rho_{m} = \\frac{m\\,\\rho}{1 + (m-1)\\rho}.$$\nSetting $m = 2$ steps a half-test correlation up to full-test reliability. The same formula answers design questions: how long does a test need to be?\n\n#### Try it: lengthening a test\n\n```{ojs}\n//| echo: false\nviewof sb_rho = Inputs.range([0.1, 0.95], {value: 0.6, step: 0.01, label: \"Reliability of the current test\"})\nviewof sb_m = Inputs.range([0.25, 5], {value: 2, step: 0.25, label: \"Length multiplier m\"})\n```\n\n```{ojs}\n//| echo: false\nsb = (rho, m) => m * rho / (1 + (m - 1) * rho)\nPlot.plot({\n  width: 700, height: 280, x: {label: \"Length multiplier m\", domain: [0.25, 5]}, y: {label: \"Reliability\", domain: [0, 1]},\n  marks: [Plot.line(grid(0.25, 5, 96).map(m => ({m, r: sb(sb_rho, m)})), {x: \"m\", y: \"r\", stroke: palette.main, strokeWidth: 2.5}),\n          Plot.dot([{m: sb_m, r: sb(sb_rho, sb_m)}], {x: \"m\", y: \"r\", r: 6, fill: palette.contrast}), Plot.ruleY([sb_rho], {stroke: palette.rule})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`A test with reliability ${sb_rho.toFixed(2)}, made ${sb_m}× as long, would have reliability **${sb(sb_rho, sb_m).toFixed(2)}**. Notice the diminishing returns: each extra item buys less than the one before.`\n```\n\nWhich split should you use? There are a great many ways to split a test in half, and they give different answers. Cronbach (1951) showed that alpha is the *average* split-half coefficient over all possible splits (for the Spearman–Brown version, strictly, when the halves have equal variances). We check this with real data below.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A 10-item scale has reliability 0.70. Roughly how many comparable items would it need to reach 0.85?\",\n  options: [\n    {text: \"About 24\", correct: true, why: \"Solve $0.85 = 0.70m/(1 + 0.70(m-1))$ for $m$: $m = \\\\frac{0.85 \\\\times 0.30}{0.70 \\\\times 0.15} \\\\approx 2.4$, so about 24 items.\"},\n    {text: \"About 15\", correct: false, why: \"That assumes reliability rises in proportion to length. Spearman–Brown has diminishing returns: 15 items give only about 0.78.\"},\n    {text: \"About 40\", correct: false, why: \"Forty items (m = 4) would give about 0.90, more than needed.\"}\n  ]\n})\n```\n\n### Item analysis, and reading your items\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Item response data and the IRW](irw-data.qmd): IRW tables are *long*, one row per respondent–item response, so an item analysis starts by reshaping to one row per respondent; item means and sum scores are then column and row sums. Item means and item-rest correlations were two of that lesson's four first descriptives.\n:::\n\nCTT gives those two first-look numbers their classical roles. For each item we compute:\n\n- its **mean** (for 0/1 items, the proportion correct, often called the item's *p*-value), a first indication of difficulty, where larger values mean easier items;\n- its **item-rest correlation**: the correlation between the item and the sum of the *other* items. This tells us whether the item is hanging together with the rest. An item with a correlation near zero, or negative, is either measuring something else or is keyed backwards.\n\nThat last point is subtler than it sounds. CTT assumes every item is coded so that a higher response means more of the construct. Many scales deliberately include items worded in the opposite direction, and those have to be **reverse-keyed** before any of this makes sense. How do we know which ones? We will see below that the data take us most of the way but not all of it, and that the last step is to read the items.\n\n## Simulate\n\nHere is the lower-bound result from the proof above, on simulated data where we know the true scores. The code generates a six-item test from the classical model, then compares the true reliability, $\\text{cor}(X, T)^2$, with alpha. It is base R only, so it starts quickly.\n\nRun it as is: with equal loadings the two numbers agree up to sampling error (0.865 and 0.86 with the seed as written). Then swap in the line of unequal loadings and run it again. True reliability rises a little, to 0.879, because the steeper items carry more signal, while alpha falls to 0.829: the gap opens, and in the direction the proof says. Change `np` to 100000 and the sampling noise goes away but the gap doesn't.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-15\n# Is alpha a lower bound on reliability? Simulate a test from the classical model,\n# where we know the true scores, and compare. Change `loadings` and run again.\n# Base R only.\nset.seed(1)\nnp <- 1000                               # respondents\nloadings <- c(1, 1, 1, 1, 1, 1)          # equal: \"tau-equivalent\" items\n# loadings <- c(0.3, 0.6, 1, 1, 1.5, 2)  # unequal: try this line instead\nerr_sd <- 1                              # error SD for every item\n\ntrue <- rnorm(np)\nitems <- sapply(loadings, function(l) l * true + rnorm(np, sd = err_sd))\nX <- rowSums(items)                      # observed sum score\ntau <- sum(loadings) * true              # its true score, T\n\nalpha <- function(x) { k <- ncol(x); k / (k - 1) * (1 - sum(apply(x, 2, var)) / var(rowSums(x))) }\ncat(\"true reliability, cor(X, tau)^2:\", round(cor(X, tau)^2, 3), \"\\n\")\ncat(\"Cronbach's alpha:             \", round(alpha(items), 3), \"\\n\")\n\nplot(tau, X, pch = 16, col = rgb(0.15, 0.5, 0.89, 0.3),\n     xlab = \"True score T\", ylab = \"Observed score X\",\n     main = paste(\"reliability\", round(cor(X, tau)^2, 2), \"| alpha\", round(alpha(items), 2)))\n\n```\n:::\n\n\n[Download this code](code/ctt-reliability-sim.R).\n\n## With real data\n\n\n\nWe use two tables. The main example is [gilbert_meta_1](https://itemresponsewarehouse.org/tables/gilbert_meta_1/), the reading-comprehension outcome of a school-randomized trial of a literacy intervention for third graders ([Gilbert, Kim & Miratrix, 2023](https://doi.org/10.3102/10769986231171710); data at <https://doi.org/10.7910/DVN/QARRYT>): 30 items scored 0/1, where 1 is a correct answer. The contrast, for reverse keying, is the Mach IV, a 20-item attitude scale measuring Machiavellianism ([Christie & Geis, 1970](https://doi.org/10.1016/C2013-0-10497-7)), in responses collected by [Hunter, Gerbing and Boster (1982)](https://doi.org/10.1037/0022-3514.43.6.1293) and distributed with the lessR R package ([Gerbing, 2026](https://doi.org/10.32614/CRAN.package.lessR); IRW table [lessR_Mach4](https://itemresponsewarehouse.org/tables/lessr_mach4/)). All code is base R; [download it](code/ctt-reliability-irw.R).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# IRW tables are long (one row per response); reshape to one row per person.\nlong2wide <- function(df) {\n  wide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\n  as.data.frame(wide[, order(colnames(wide))])\n}\n# Cronbach's alpha (KR-20 when items are 0/1).\nalpha <- function(resp) {\n  resp <- resp[complete.cases(resp), ]\n  k <- ncol(resp)\n  (k / (k - 1)) * (1 - sum(apply(resp, 2, var)) / var(rowSums(resp)))\n}\n# Correlation of each item with the sum of the *other* items.\nitem_rest <- function(resp) {\n  tot <- rowSums(resp)\n  sapply(names(resp), function(i) cor(resp[[i]], tot - resp[[i]], use = \"complete.obs\"))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v57_0.gilbert_meta_1/rows?format=csv\"\ndf <- read.csv(url)\n# Treatment was assigned by school: each school (cluster_id) has one value of treat.\nc(students = length(unique(df$id)), schools = length(unique(df$cluster_id)),\n  schools_with_one_arm = sum(tapply(df$treat, df$cluster_id, function(x) length(unique(x))) == 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            students              schools schools_with_one_arm \n                7797                  110                  110 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nresp <- long2wide(df)\nresp <- resp[complete.cases(resp), ]   # keep students who answered all 30 items\ndim(resp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7322   30\n```\n\n\n:::\n:::\n\n\nThe 7,797 students come from 110 schools, and each school is entirely in one arm of the trial. We keep the 7,322 students who answered every item; the rest have at least one missing response.\n\n### Item analysis\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nia <- data.frame(p = colMeans(resp), r_rest = item_rest(resp))\nround(ia[order(ia$r_rest), ], 2)[1:6, ]   # the six weakest items\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|            |    p| r_rest|\n|:-----------|----:|------:|\n|s_read_7_4  | 0.38|  -0.01|\n|s_read_7_10 | 0.27|   0.15|\n|s_read_3_3  | 0.42|   0.27|\n|s_read_7_8  | 0.39|   0.30|\n|s_read_11_3 | 0.38|   0.34|\n|s_read_7_5  | 0.40|   0.40|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(quantile(ia$r_rest, c(0.1, 0.5, 0.9)), 2)   # the spread across all 30\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 10%  50%  90% \n0.30 0.49 0.55 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsum(ia$r_rest >= 0.4)                       # items at 0.40 or above\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nplot(ia$p, ia$r_rest, pch = 19, col = \"#2780e3\", xlim = c(0, 1),\n     xlab = \"Proportion correct (p)\", ylab = \"Item-rest correlation\")\ntext(ia$p, ia$r_rest, rownames(ia), pos = 3, cex = 0.6)\n```\n\n::: {.cell-output-display}\n![](ctt-reliability_files/figure-html/itemanalysis-1.png){width=672}\n:::\n:::\n\n\nWhat does a typical item look like here? The median item-rest correlation is 0.49, and 24 of the 30 items are at 0.40 or above. One is not: `s_read_7_4` has an item-rest correlation of −0.01, essentially zero, although its proportion correct, 0.38, sits among the others in the plot. Whatever that item measures, the total score doesn't share it. Since this test is the outcome in a randomized trial, that merits comment: an item that doesn't covary with the rest adds noise to the total and so to the treatment-effect estimate. Problem 3 asks what alpha does without it.\n\n### Alpha, and all the split halves\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nsprintf(\"%.3f\", alpha(resp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0.898\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nset.seed(252)\nsplit_half <- function(resp) {\n  k <- ncol(resp)\n  h <- sample(k, k / 2)\n  r <- cor(rowSums(resp[, h]), rowSums(resp[, -h]))\n  c(raw = r, spearman_brown = 2 * r / (1 + r))\n}\nhalves <- t(replicate(1000, split_half(resp)))\nplot(density(halves[, \"spearman_brown\"]), lwd = 2, xlim = range(halves),\n     main = \"1,000 random split halves of gilbert_meta_1\", xlab = \"Reliability estimate\")\nlines(density(halves[, \"raw\"]), col = \"#c2410c\", lwd = 2)\nabline(v = alpha(resp), lty = 2)\nlegend(\"topleft\", c(\"Split-half correlation\", \"Spearman-Brown adjusted\", \"Alpha\"),\n       col = c(\"#c2410c\", \"black\", \"black\"), lty = c(1, 1, 2), lwd = 2, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](ctt-reliability_files/figure-html/splithalf-1.png){width=672}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nprint(c(mean_adjusted = mean(halves[, \"spearman_brown\"]), alpha = alpha(resp),\n        lowest = min(halves[, \"spearman_brown\"]), highest = max(halves[, \"spearman_brown\"]),\n        share_below_alpha = mean(halves[, \"spearman_brown\"] < alpha(resp))), digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    mean_adjusted             alpha            lowest           highest \n            0.899             0.898             0.875             0.911 \nshare_below_alpha \n            0.330 \n```\n\n\n:::\n:::\n\n\nThe left-hand curve is the raw correlation between the two halves of each random split; the right-hand one steps each correlation up with Spearman–Brown. The adjusted estimates run from 0.875 to 0.911, and a third of them fall below alpha. But they average 0.899, against an alpha of 0.898 (the dashed line), as Cronbach's result says; the last digit is the price of 1,000 random splits rather than all of them, and of halves whose variances aren't quite equal. Any single split could have given a number a little above or below alpha.\n\n### Reverse keying: the Mach IV\n\nThe Mach IV is answered on a six-point scale, from 0 (strongly disagree) to 5 (strongly agree). Half its items are worded so that agreeing is the Machiavellian answer; for the other half, agreeing is the *less* Machiavellian answer. The IRW table stores the responses as given, unkeyed.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Item response data and the IRW](irw-data.qmd): the Mini-IPIP's ten reverse-worded items arrived already reverse-scored, although the deposit's codebook suggested otherwise; every within-trait correlation came out positive, and that settled it. The rule there: learn from the documentation which way each item should run, then check it in the data, because neither is enough alone.\n:::\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Half the Mach IV's items are worded so that agreeing is the *less* Machiavellian answer. If we compute alpha *without* reverse-keying them, roughly what do we get? (Keyed by the published key, alpha is 0.70.)\",\n  choices: [\"About 0.70\", \"About 0.55\", \"About 0.35\", \"Below 0\"],\n  answer: \"About 0.35\",\n  reveal: \"Alpha is 0.37 unkeyed. Items pulling in opposite directions partly cancel in the total, so the covariances that alpha relies on shrink. It doesn't go all the way to zero or below: most item-rest correlations stay slightly positive, as the output shows.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nmach <- long2wide(read.csv(\n  \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v57_0.lessR_Mach4/rows?format=csv\"))\ndim(mach)          # 351 respondents, 20 items, responses 0 (strongly disagree) to 5 (strongly agree)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 351  20\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsprintf(\"%.2f\", alpha(mach))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0.37\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(item_rest(mach), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  m01   m02   m03   m04   m05   m06   m07   m08   m09   m10   m11   m12   m13 \n 0.14  0.07  0.29  0.05  0.08  0.22  0.23  0.06  0.09  0.13  0.11 -0.02  0.10 \n  m14   m15   m16   m17   m18   m19   m20 \n 0.25  0.06  0.15 -0.02  0.05  0.03 -0.01 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsum(item_rest(mach) > 0)   # how many are positive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17\n```\n\n\n:::\n:::\n\n\nAn alpha of 0.37 is well below the 0.90 of the reading test. Now look at the item-rest correlations. They are small (none above 0.29, against a median of 0.49 in the reading test), and 17 of the 20 are *positive*, including m04 (\"Most people are basically good and kind\"), which points the opposite way from m01 (\"Never tell anyone the real reason you did something unless it is useful to do so\"; both items from [Christie & Geis, 1970, ch. 2](https://doi.org/10.1016/B978-0-12-174450-2.50007-5), worded as in the item labels that come with the data). Item-rest correlations can't tell us which items are reversed, because the total we correlate against is itself a mix of the two directions. The published key reverses ten of them:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The published key (Christie & Geis, 1970): these ten items are worded so that\n# agreeing is the *less* Machiavellian answer, so we reverse them.\nreversed <- sprintf(\"m%02d\", c(3, 4, 6, 7, 9, 10, 11, 14, 16, 17))\nmach_keyed <- mach\nmach_keyed[reversed] <- 5 - mach_keyed[reversed]\nsprintf(\"%.2f\", alpha(mach_keyed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0.70\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(sort(item_rest(mach_keyed)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  m19   m03   m14   m15   m08   m02   m17   m05   m18   m04   m20   m13   m16 \n-0.05  0.12  0.19  0.23  0.23  0.23  0.23  0.25  0.27  0.28  0.28  0.28  0.29 \n  m01   m11   m12   m09   m10   m06   m07 \n 0.30  0.36  0.37  0.39  0.41  0.43  0.46 \n```\n\n\n:::\n:::\n\n\nAlpha nearly doubles, to 0.70, and the item-rest correlations now look like a scale: all but one are between 0.12 and 0.46. The one that isn't is m19, an item about euthanasia, at −0.05.\n\nCould the data have found the key on their own? Automated keying, such as `check.keys = TRUE` in the psych package's `alpha()` ([Revelle, 2026](https://doi.org/10.32614/CRAN.package.psych)), splits the items by the sign of their loading on the first principal component. Here is that split in base R:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Can the data find the key? Automated keying (e.g. psych::alpha(check.keys = TRUE))\n# splits the items by the sign of their loading on the first principal component.\npc1 <- prcomp(mach)$rotation[, 1]\nauto <- names(pc1)[sign(pc1) != sign(pc1[\"m01\"])]  # items pointing away from m01\nauto\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m03\" \"m04\" \"m06\" \"m07\" \"m09\" \"m10\" \"m11\" \"m14\" \"m16\" \"m17\" \"m19\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsetdiff(auto, reversed)   # flipped by the data but not by the published key\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"m19\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsetdiff(reversed, auto)   # flipped by the published key but not by the data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncharacter(0)\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# m19 is weak whichever way it is keyed.\nmach_alt <- mach_keyed\nmach_alt$m19 <- 5 - mach_alt$m19\nround(c(m19_as_published = item_rest(mach_keyed)[[\"m19\"]],\n        m19_reversed = item_rest(mach_alt)[[\"m19\"]],\n        alpha_m19_reversed = alpha(mach_alt)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  m19_as_published       m19_reversed alpha_m19_reversed \n             -0.05               0.05               0.71 \n```\n\n\n:::\n:::\n\n\nIt recovers all ten published reversals, and adds m19. That is the one item the data can't settle: its item-rest correlation is −0.05 keyed one way and 0.05 keyed the other, and the documentation that comes with the lessR data also lists it among the reversed items. Either way, it doesn't covary with the rest of the scale. It is a reasonable question to ask respondents, but it is about something other than the other 19. I use automated keying as a prompt to read the items, not as a substitute for reading them: it got 19 of 20 items right here, and the 20th is exactly the one where a reader, not the data, has to decide.\n\n### Limitations worth remembering\n\nMany of these were known to Cronbach himself. Alpha is a lower bound only under uncorrelated errors, and there are better lower bounds, such as the greatest lower bound or \"glb\" ([Jackson & Agunwamba, 1977](https://doi.org/10.1007/BF02295979); [Ten Berge & Sočan, 2004](https://doi.org/10.1007/BF02289858)), and model-based alternatives such as McDonald's **omega** ([McDonald, 1999](https://doi.org/10.4324/9781410601087)), which we meet in [Factor analysis II](fa-confirmatory.qmd). Alpha is not a measure of unidimensionality ([Green, Lissitz & Mulaik, 1977](https://doi.org/10.1177/001316447703700403)). And reliability is a property of scores *in a population*: estimate it in a sample that is a poor proxy for the people you care about and the number may not mean much. For a clear example of that last point, see the IRW vignette on [the reliability paradox in cognitive-control tasks](https://itemresponsewarehouse.org/vignettes/hf_reliability_paradox.html), where tasks that produce robust experimental effects yield unreliable individual differences ([Hedge, Powell & Sumner, 2018](https://doi.org/10.3758/s13428-017-0935-1)).\n\nFinally, the limitation that motivates the rest of the course: CTT says nothing about individual item responses. It treats a test as a single score with a single error variance, the same for everyone. That is the assumption item response theory drops; [Where CTT breaks](ctt-limits.qmd) shows what it costs.\n\n## Problems\n\n1. **Parallel forms.** Suppose $X = T + E$ and $X' = T + E'$, where $E$ and $E'$ are uncorrelated with each other and with $T$, and have equal variances. Show that $\\text{cor}(X, X') = \\sigma^2_T/\\sigma^2_X$. Where exactly did you use each assumption?\n2. **Attenuation.** Let $Y$ be a criterion (a gold-standard measure, say) with its own reliability $\\rho_{YY'}$. Show that $\\text{cor}(X, Y) = \\text{cor}(T_X, T_Y)\\sqrt{\\rho_{XX'}\\,\\rho_{YY'}}$ ([Spearman, 1904](https://doi.org/10.2307/1412159)), and hence that a test's correlation with anything is bounded by $\\sqrt{\\rho_{XX'}}$. What does this imply for a new test whose validity is judged by its correlation with an established one? [Loevinger (1954)](https://doi.org/10.1037/h0058543) describes the \"attenuation paradox\" this creates for test construction; read it after you've tried the problem.\n3. **The weak item.** In `gilbert_meta_1`, drop `s_read_7_4` and recompute alpha. By how much does it change? Now use Spearman–Brown to predict the reliability of a 29-item test from the 30-item alpha. Why do the two answers differ, and in which direction?\n4. **Split halves.** In the split-half figure, about a third of the adjusted split-half estimates fall below alpha. Why is alpha not below *all* of them, given that alpha is a lower bound on reliability? (Hint: what is each split-half estimate a bound on, and what does it assume?) *Challenge (open):* is there anything about the splits that fall below alpha that suggests they are \"bad\" splits, halves that are not parallel?\n5. **Reading items.** Look at the item-rest correlations for the keyed Mach IV. Choose the two weakest items and, from their content and the construct, argue whether each should be dropped, rewritten, or kept. For m19, does it matter which way it is keyed? Would your decisions change if the scale were used to screen job applicants rather than in research? Read [Hunter, Gerbing and Boster (1982)](https://doi.org/10.1037/0022-3514.43.6.1293) alongside this problem.\n6. **Alpha at scale.** Using the `alpha()` function from this lesson, compute alpha for five IRW tables of your choosing with 0/1 responses. Before you do, predict which will be highest. What features of a table (number of items, type of construct, sample) seem to go with high alpha? What would make you distrust a high value?\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Classical%20test%20theory%20and%20reliability%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20classical%20test%20theory%3A%20true%20scores%20and%20error%2C%20reliability%2C%20parallel%20forms%2C%20the%20standard%20error%20of%20measurement%2C%20Cronbach%27s%20alpha%20and%20why%20it%20is%20a%20lower%20bound%20on%20reliability%2C%20split%20halves%20and%20the%20Spearman-Brown%20formula%2C%20and%20classical%20item%20analysis%20including%20reverse%20keying%2C%20with%20examples%20in%20base%20R.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Lord, F. M., & Novick, M. R. (1968). *Statistical theories of mental test scores*. Addison-Wesley. The canonical treatment of the classical model, true scores and parallel measurements.\n- Cronbach, L. J. (1951). Coefficient alpha and the internal structure of tests. *Psychometrika*, 16(3), 297–334. <https://doi.org/10.1007/BF02310555>. Where alpha gets its name, and the split-half result.\n- Novick, M. R., & Lewis, C. (1967). Coefficient alpha and the reliability of composite measurements. *Psychometrika*, 32(1), 1–13. <https://doi.org/10.1007/BF02289400>. The lower-bound proof and the conditions for equality.\n- Sijtsma, K. (2009). On the use, the misuse, and the very limited usefulness of Cronbach's alpha. *Psychometrika*, 74(1), 107–120. <https://doi.org/10.1007/s11336-008-9101-0>. Argues that alpha says little about a test's internal structure and is a weaker lower bound than the glb, which it proposes instead.\n- Revelle, W., & Zinbarg, R. E. (2009). Coefficients alpha, beta, omega, and the glb: Comments on Sijtsma. *Psychometrika*, 74(1), 145–154. <https://doi.org/10.1007/s11336-008-9102-z>. The reply, which argues for omega.\n- McNeish, D. (2018). Thanks coefficient alpha, we'll take it from here. *Psychological Methods*, 23(3), 412–433. <https://doi.org/10.1037/met0000144>. A readable survey of the alternatives.\n- Green, S. B., & Hershberger, S. L. (2000). Correlated errors in true score models and their effect on coefficient alpha. *Structural Equation Modeling*, 7(2), 251–270. <https://doi.org/10.1207/S15328007SEM0702_6>. When alpha overstates reliability.\n- Hunter, J. E., Gerbing, D. W., & Boster, F. J. (1982). Machiavellian beliefs and personality: Construct invalidity of the Machiavellianism dimension. *Journal of Personality and Social Psychology*, 43(6), 1293–1305. <https://doi.org/10.1037/0022-3514.43.6.1293>. The source of the Mach IV responses, and a study of what the scale measures.\n- IRW vignette: [the reliability paradox](https://itemresponsewarehouse.org/vignettes/hf_reliability_paradox.html). Reliability of experimental tasks across IRW tables.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`gilbert_meta_1`](https://itemresponsewarehouse.org/tables/gilbert_meta_1/): Gilbert, J. B., Kim, J. S., & Miratrix, L. W. (2023). Modeling item-level heterogeneous treatment effects with the explanatory item response model: Leveraging large-scale online assessments to pinpoint the impact of educational interventions. Journal of Educational and Behavioral Statistics, 48(6), 889-913. Gilbert, Josh, 2023, \"Replication Data for: Modeling Item-Level Heterogeneous Treatment Effects With the Explanatory Item Response Model: Leveraging Large-Scale Online Assessments to Pinpoint the Impact of Educational Interventions\", <https://doi.org/10.7910/DVN/QARRYT>, Harvard Dataverse, V2, UNF:6:r+hUHhEPWWtUbcqXyELTJw== [fileUNF]. Licence: CC BY-NC-SA 4.0.\n- [`lessR_Mach4`](https://itemresponsewarehouse.org/tables/lessr_mach4/): Hunter, J. E., Gerbing, D. W., & Boster, F. J. (1982). Machiavellian beliefs and personality: Construct invalidity of the Machiavellianism dimension. Journal of personality and social psychology, 43(6), 1293. <https://doi.org/10.1037/0022-3514.43.6.1293>. Licence: GPL-3.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 2 (slides c2, \"Classical Test Theory\" through \"Limitations of alpha\") and problem set 2 (#1–3); code in `ben-domingue/252`: `c2/alpha.R`, `ps2/itemanalysis.R`, `ps2/parallel_tests.R`.\n- **Timing:** the core ideas and widgets take about 50 minutes; the two real-data analyses work as a 25-minute lab.\n- **Held back:** constructs and construct maps (the first half of c2) are their own lesson; the \"CTT failures\" demonstration (PS2#4) and \"towards IRT\" (PS2#5) are in [Where CTT breaks](ctt-limits.qmd).\n- **Changed from 252:** PS2#1 contrasted `gilbert_meta_1` with `gilbert_meta_9`; this lesson uses the Mach IV instead, because `gilbert_meta_9` has repeated waves that complicate a first item analysis, and because the Mach IV carries the reverse-keying lesson.\n- **Deep dive:** problem 6 is the small version of deep dive #20 (alpha across the IRW corpus, and alpha against test length), planned for this lesson. The *Across the IRW* section is added when that result is computed.\n- **Item text:** the Mach IV is not openly licensed (Christie & Geis, 1970, Academic Press), so the lesson quotes two items, m01 and m04, for the keying argument and describes the rest.\n- **Solutions:** held back in `solutions/ctt-reliability.qmd` (not published). Problem 4's challenge is open (in 252 it was posed as an open question).\n",
    "supporting": [
      "ctt-reliability_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}