{
  "hash": "a17b75af2b851c2400cc6b3865e03904",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"IRTree models\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Beyond the standard models  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [Models for polytomous responses](polytomous.qmd) · [What is an item? Explanatory item response models](explanatory-irt.qmd)  \n**Builds toward:** none  \n**Picks up threads:** Keying has to be checked; the data can't always tell (from [Classical test theory and reliability](ctt-reliability.qmd))  \n**IRW tables:** [`bfi_goldberg_1992_conscientiousness`](https://itemresponsewarehouse.org/tables/bfi_goldberg_1992_conscientiousness/), [`introversion_extroversion`](https://itemresponsewarehouse.org/tables/introversion_extroversion/)  \n**From EDUC 252:** slides c8; problem sets PS8#4; code [`c8/irtree.R`](https://github.com/ben-domingue/252/blob/main/c8/irtree.R), [`c8/irtree2.R`](https://github.com/ben-domingue/252/blob/main/c8/irtree2.R), [`c8/irtree_sim.R`](https://github.com/ben-domingue/252/blob/main/c8/irtree_sim.R), [`ps8/fast.R`](https://github.com/ben-domingue/252/blob/main/ps8/fast.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\nwebr::install(\"lme4\", quiet = TRUE)\nsuppressPackageStartupMessages(library(lme4))\noptions(mc.cores = 1)\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {grid, palette} from \"./widgets/irt.js\"\nimport {trees, catProbsTree, expected15, treeLayout} from \"./widgets/irtrees.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nWhat does a 3 mean on a scale from 1 (disagree) to 5 (agree)? The graded response model reads it as a little more of the trait than a 2. But a respondent may choose the middle because they have no view, or prefer not to commit, and a 5 may say as much about a taste for the ends of a scale as about the trait. An **IRTree** writes the response as a sequence of decisions (take a side? which side? how far?) and gives each its own item response model and, if we want, its own $\\theta$. [Models for polytomous responses](polytomous.qmd) split a response into binary questions fixed by the model; a tree chooses the questions to match a process we have in mind, and fitting it is a recoding followed by a `glmer()` fit from [What is an item?](explanatory-irt.qmd). On ten conscientiousness items, leaving the middle and going to the ends turn out to be largely one tendency, which barely tracks conscientiousness.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- write a rating as a path through a tree of binary nodes, and its probability as a product along the path;\n- choose a tree's shape (linear or nested) and its abilities (one $\\theta$, or one per node), and say which choice gives the sequential model;\n- recode long response data into pseudo-items and fit a tree with `glmer()`;\n- separate content from midpoint and extreme responding, and say what the separation assumes;\n- use a first node for speed or skipping, and say what it protects the content estimate from.\n\n## Core ideas\n\n### A response as a sequence of decisions\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Models for polytomous responses](polytomous.qmd): ordinal models split a response into binary questions. The sequential model ([Tutz, 1990](https://doi.org/10.1111/j.2044-8317.1990.tb00925.x)) asks \"having reached category $k-1$, does the respondent go on to $k$?\", and a response answers only the questions it reaches.\n:::\n\nNothing requires the questions to follow the order of the categories. [Böckenholt (2012)](https://doi.org/10.1037/a0028111) proposed a tree for a five-point rating that asks three different questions. Does the respondent take a side or choose the middle? Which side? And do they go to its end? Each question is a **node**, and each node gets an item response model. With a Rasch model at every node,\n$$p^{(n)}_{ij} = \\Pr(\\text{node } n = 1) = \\frac{\\exp\\big(\\theta^{(n)}_j - b^{(n)}_i\\big)}{1 + \\exp\\big(\\theta^{(n)}_j - b^{(n)}_i\\big)}, \\qquad n \\in \\{\\text{side}, \\text{direction}, \\text{extreme}\\},$$\nand the probability of a response is the product of the node probabilities along its path. A 4 takes a side, the agree side, and stops short of the end:\n$$\\Pr(x_{ij} = 4) = p^{(\\text{side})}_{ij}\\; p^{(\\text{direction})}_{ij}\\,\\big(1 - p^{(\\text{extreme})}_{ij}\\big), \\qquad \\Pr(x_{ij} = 3) = 1 - p^{(\\text{side})}_{ij}.$$\nEach response becomes one binary **pseudo-item** per node it reaches; a node it doesn't reach is absent, not a 0 ([De Boeck & Partchev, 2012](https://doi.org/10.18637/jss.v048.c01)).\n\n#### Try it: build a tree\n\nPick a response and a tree; the highlighted path is the one it takes.\n\n```{ojs}\n//| echo: false\nviewof tb_x = Inputs.radio([1, 2, 3, 4, 5], {value: 4, label: \"Response x\"})\nviewof tb_kind = Inputs.radio([\"Nested (side, direction, extreme)\", \"Linear (sequential)\"], {value: \"Nested (side, direction, extreme)\", label: \"Tree\"})\n```\n\n```{ojs}\n//| echo: false\ntb_k = tb_kind.startsWith(\"Nested\") ? \"nested\" : \"linear\"\ntb_lay = treeLayout(tb_k, tb_x)\nPlot.plot({\n  width: 700, height: 400, margin: 30,\n  x: {domain: [-0.05, 1.05], axis: null}, y: {domain: [1.05, -0.02], axis: null},\n  marks: [\n    Plot.link(tb_lay.edges, {x1: \"x1\", y1: \"y1\", x2: \"x2\", y2: \"y2\", stroke: d => d.on ? palette.contrast : palette.rule, strokeWidth: d => d.on ? 3.5 : 1.5}),\n    Plot.text(tb_lay.edges, {x: d => (d.x1 + d.x2) / 2, y: d => (d.y1 + d.y2) / 2, text: \"lab\", fill: palette.guide, dx: 14, fontSize: 11}),\n    Plot.dot(tb_lay.nodes, {x: \"x\", y: \"y\", r: 32, fill: palette.white, stroke: d => d.on ? palette.contrast : palette.main, strokeWidth: 2}),\n    Plot.text(tb_lay.nodes, {x: \"x\", y: \"y\", text: \"text\", fontSize: 10, fill: palette.ink}),\n    Plot.dot(tb_lay.leaves, {x: \"x\", y: \"y\", r: 13, fill: d => d.on ? palette.contrast : palette.light}),\n    Plot.text(tb_lay.leaves, {x: \"x\", y: \"y\", text: \"text\", fontSize: 13, fontWeight: \"bold\", fill: d => d.on ? palette.white : palette.ink})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\ntb_rows = trees[tb_k].map(n => ({label: n.label, code: n.code(tb_x)})).filter(n => n.code !== null)\nmd`A response of ${tb_x} becomes **${tb_rows.length}** pseudo-item${tb_rows.length > 1 ? \"s\" : \"\"}: ${tb_rows.map(n => `\"${n.label}\" = ${n.code}`).join(\"; \")}. Its probability is the product of ${tb_rows.length > 1 ? `these ${tb_rows.length} node probabilities, each` : \"one node probability,\"} taken as P(1) where the code is 1 and 1 − P(1) where it is 0.`\n```\n\nUnder the nested tree a 3 is one pseudo-item and every other response three; under the linear tree a 1 is one and a 4 or 5 four. Each response follows exactly one path, so the five probabilities sum to one (problem 1).\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Under the nested tree, a respondent answers 2. Which pseudo-items does that response produce?\",\n  options: [\n    {text: \"Side = 1, direction = 0, extreme = 0\", correct: true, why: \"A 2 takes a side (not 3), the disagree side, and stops short of the end (not 1).\"},\n    {text: \"Side = 1, direction = 0\", correct: false, why: \"Every response that takes a side reaches both the direction and the extreme node; the extreme node is how the tree tells a 2 from a 1.\"},\n    {text: \"Side = 0, direction = 0, extreme = 0\", correct: false, why: \"Side = 0 means the respondent chose 3, and then the response stops: it never reaches the other two nodes.\"}\n  ]\n})\n```\n\n### Tree shape and node abilities are choices\n\nTwo choices define a tree. Its **shape**: a *linear* tree asks its questions in a chain, as the sequential model does; a *nested* tree branches, so that different responses pass through different nodes, as Böckenholt's does ([De Boeck & Partchev, 2012](https://doi.org/10.18637/jss.v048.c01)). And its **abilities**: one $\\theta$ shared by every node, or a correlated $\\theta$ per node. A linear tree with one $\\theta$ and Rasch steps is Tutz's sequential model. [Jeon and De Boeck (2016)](https://doi.org/10.3758/s13428-015-0631-y) extend trees further, with slopes at each node and more flexible links between nodes and dimensions.\n\n#### Try it: node abilities and the category curves\n\nTen items have node difficulties $b^{(\\text{side})} = -1.2$, $b^{(\\text{direction})} = -0.9$ and $b^{(\\text{extreme})} = 0.5$, close to the averages of the conscientiousness items below. The horizontal axis is the content $\\theta$, the one at the direction node. Set the other two, or tie all three together.\n\n```{ojs}\n//| echo: false\nviewof nc_mode = Inputs.radio([\"A θ per node\", \"One θ for all nodes\"], {value: \"A θ per node\", label: \"Abilities\"})\nviewof nc_side = Inputs.range([-3, 3], {value: 0, step: 0.1, label: \"θ at the side node\"})\nviewof nc_ext = Inputs.range([-3, 3], {value: 0, step: 0.1, label: \"θ at the extreme node\"})\n```\n\n```{ojs}\n//| echo: false\nnc_b = ({side: -1.2, direction: -0.9, extreme: 0.5})\nnc_th = t => nc_mode === \"One θ for all nodes\" ? {side: t, direction: t, extreme: t} : {side: nc_side, direction: t, extreme: nc_ext}\nnc_cols = [palette.contrast, palette.light, palette.guide, palette.main, palette.ink]\nnc_rows = grid(-4, 4, 161).flatMap(t => catProbsTree(nc_th(t), nc_b).map((p, k) => ({theta: t, p, cat: `x = ${k + 1}`})))\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Content θ (direction node)\"}, y: {label: \"P(x = k)\", domain: [0, 1]},\n  color: {legend: true, domain: [\"x = 1\", \"x = 2\", \"x = 3\", \"x = 4\", \"x = 5\"], range: nc_cols},\n  marks: [Plot.line(nc_rows, {x: \"theta\", y: \"p\", stroke: \"cat\", strokeWidth: 2.5})]\n})\n```\n\n```{ojs}\n//| echo: false\nnc_at = t => catProbsTree(nc_th(t), nc_b)\nmd`P(x = 3) at content θ = −2, 0 and 2: **${[-2, 0, 2].map(t => nc_at(t)[2].toFixed(2)).join(\", \")}**. P(x = 1 or 5) at the same points: **${[-2, 0, 2].map(t => (nc_at(t)[0] + nc_at(t)[4]).toFixed(2)).join(\", \")}**.${nc_mode === \"One θ for all nodes\" ? \" (The side and extreme sliders are ignored: every node uses the content θ.)\" : \"\"}`\n```\n\nWith a $\\theta$ per node, the curve for 3 is flat (0.23 at the defaults): choosing the middle depends only on the side node. Lower that $\\theta$ and the curve rises everywhere; raise the extreme node's and the 1s and 5s take over from the 2s and 4s. Now tie the nodes together: the respondents lowest on the trait choose 3 most (0.69 at $\\theta = -2$), because the $\\theta$ that pushes them toward disagreeing also keeps them from taking a side. A shared $\\theta$ suits a linear tree, whose steps all move up the scale; in a nested tree it forces different questions onto one dimension.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A linear tree for a 1–5 rating has four nodes, one per step, with a Rasch model at each and one $\\\\theta$ shared by all four. Which model is it?\",\n  options: [\n    {text: \"The sequential model\", correct: true, why: \"Each node asks whether a respondent who reached category $k-1$ goes on to $k$, with $\\\\theta$ and a step difficulty: Tutz's sequential model with slopes of 1.\"},\n    {text: \"The partial credit model\", correct: false, why: \"The PCM's binary questions compare adjacent categories ($k$ rather than $k-1$), among respondents in one of the two. The tree's questions condition on having reached $k-1$, which includes everyone above it.\"},\n    {text: \"The graded response model\", correct: false, why: \"The GRM's questions are cumulative ($x \\\\ge k$?) and every response answers all of them. In a tree, a response answers only the nodes on its path.\"}\n  ]\n})\n```\n\n### Fitting a tree is recoding, then a mixed model\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is an item?](explanatory-irt.qmd): the Rasch model is a mixed logistic regression, `glmer(resp ~ 0 + item + (1 | id), family = binomial)`, with one intercept per item (its easiness, $-b_i$) and a random intercept per respondent ($\\theta_j$). Item features and respondent covariates are changes to that formula.\n:::\n\nA tree is one of those regressions. Stack the pseudo-items long, one row per respondent, item and node reached, with a `node` column. Then\n```r\nglmer(resp ~ 0 + item:node + (0 + node | id), family = binomial, data = pseudo_items)\n```\ngives every item an easiness at every node (`item:node`) and every respondent a $\\theta$ at every node, with their SDs and correlations estimated (`(0 + node | id)`). The node is an item predictor, and it has to be a factor: stored as a number, `glmer` would treat it as one slope. One $\\theta$ for all nodes is `(1 | id)`. Any software for binary item response models can fit a tree, because the likelihood factors into one piece per node (Go deeper, below); `mirt` ([Chalmers, 2012](https://doi.org/10.18637/jss.v048.i06)) takes the pseudo-items as columns, missing where a response doesn't reach a node.\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: the tree likelihood factorizes over nodes\n\n**Assumptions:** a tree with nodes $n = 1, \\dots, N$; each response category corresponds to exactly one path; at each node, the probability of a 1 depends only on the respondent's node ability and the item's node parameters; given the node abilities, the node outcomes are independent, within and across items.\n\n**One response.** Write $y_{ijn} \\in \\{0, 1\\}$ for the pseudo-item of respondent $j$, item $i$ and node $n$, and $r_{ijn} = 1$ if the response reaches node $n$ (0 otherwise). The path of $x_{ij}$ fixes both, so\n$$\\Pr(x_{ij} \\mid \\boldsymbol\\theta_j) = \\prod_{n} \\Big[\\big(p^{(n)}_{ij}\\big)^{y_{ijn}} \\big(1 - p^{(n)}_{ij}\\big)^{1 - y_{ijn}}\\Big]^{r_{ijn}},$$\nwhere a node the response doesn't reach contributes a factor of 1.\n\n**All responses.** Multiplying over items and respondents,\n$$L = \\prod_j \\int \\prod_n \\prod_{i:\\, r_{ijn} = 1} \\big(p^{(n)}_{ij}\\big)^{y_{ijn}} \\big(1 - p^{(n)}_{ij}\\big)^{1 - y_{ijn}}\\; \\phi(\\boldsymbol\\theta_j; \\mathbf 0, \\boldsymbol\\Sigma)\\, d\\boldsymbol\\theta_j.$$\nGiven $\\boldsymbol\\theta_j$, this is the likelihood of an ordinary binary item response model for a data set with one column per item and node, and missing entries where $r_{ijn} = 0$. Whether a node is reached is fixed by the outcomes of earlier nodes, which are observed, so the missing pseudo-items are missing at random in the sense of [Rubin (1976)](https://doi.org/10.1093/biomet/63.3.581), and leaving them out loses nothing. That is why recoding followed by `glmer()` or `mirt` fits the tree, with no special software.\n\n**Two consequences.** If $\\boldsymbol\\Sigma$ is diagonal (node abilities uncorrelated), the integral splits and the tree is $N$ separate item response models, one per node. And if all nodes share one $\\theta$ and the tree is linear with Rasch nodes, the product is the sequential model of [Models for polytomous responses](polytomous.qmd), whose steps [Tutz (1990)](https://doi.org/10.1111/j.2044-8317.1990.tb00925.x) fits the same way.\n:::\n\n### Response styles\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [From construct map to items](instrument-building.qmd): acquiescence, agreeing whatever the statement, is one reason scales include reversed items. Once the reversed items are keyed, acquiescence pulls the two halves of the sum in opposite directions and largely cancels.\n:::\n\nAcquiescence is one **response style**, a tendency in how a respondent uses the scale. Two others are **midpoint responding**, choosing the middle, and **extreme responding**, choosing the ends ([Baumgartner & Steenkamp, 2001](https://doi.org/10.1509/jmkr.38.2.143.18840)). Reversed items don't balance these two, since reversing maps 5 to 1 and 3 to 3. In Böckenholt's tree they have their own nodes. The $\\theta$ at the side node is a respondent's tendency to leave the middle; the $\\theta$ at the extreme node is their tendency to go to the ends; and the content $\\theta$, at the direction node, is estimated net of both ([Böckenholt, 2017](https://doi.org/10.1037/met0000106)). [Khorramdel and von Davier (2014)](https://doi.org/10.1080/00273171.2013.866536) fit style dimensions shared across all five Big Five scales.\n\nThe separation rests on assumptions. The tree takes a 3 to carry no information about direction, and takes the side and extreme decisions to be related to content only through the correlations of the $\\theta$s. [Plieninger and Meiser (2014)](https://doi.org/10.1177/0013164413514998) checked the style dimensions against external measures of response style and found that they behaved as style; [Meiser, Plieninger and Henninger (2019)](https://doi.org/10.1111/bmsp.12158) relax the first assumption with nodes that are themselves ordinal. \n\n#### Try it: same conscientiousness, different styles\n\nTwo respondents with the same content $\\theta$ answer the ten items above. A leaves the middle and goes to the ends; B does neither. The lines are their expected sum scores.\n\n```{ojs}\n//| echo: false\nviewof ts_c = Inputs.range([-3, 3], {value: 1.5, step: 0.1, label: \"Content θ (both)\"})\nviewof ts_as = Inputs.range([-3, 3], {value: 1, step: 0.1, label: \"A: θ at the side node\"})\nviewof ts_ae = Inputs.range([-3, 3], {value: 1.5, step: 0.1, label: \"A: θ at the extreme node\"})\nviewof ts_bs = Inputs.range([-3, 3], {value: -1, step: 0.1, label: \"B: θ at the side node\"})\nviewof ts_be = Inputs.range([-3, 3], {value: -1.5, step: 0.1, label: \"B: θ at the extreme node\"})\n```\n\n```{ojs}\n//| echo: false\nts_b = ({side: -1.2, direction: -0.9, extreme: 0.5})\nts_sum = (c, s, e) => 10 * expected15(catProbsTree({side: s, direction: c, extreme: e}, ts_b))\nts_rows = grid(-4, 4, 161).flatMap(c => [\n  {c, r: ts_sum(c, ts_as, ts_ae), who: \"A\"}, {c, r: ts_sum(c, ts_bs, ts_be), who: \"B\"}])\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Content θ\"}, y: {label: \"Expected sum score (10 to 50)\", domain: [10, 50]},\n  color: {legend: true, domain: [\"A\", \"B\"], range: [palette.contrast, palette.main]},\n  marks: [Plot.ruleY([30], {stroke: palette.rule}), Plot.ruleX([ts_c], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n          Plot.line(ts_rows, {x: \"c\", y: \"r\", stroke: \"who\", strokeWidth: 2.5})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`At content θ = ${ts_c.toFixed(1)}: expected sum **${ts_sum(ts_c, ts_as, ts_ae).toFixed(1)}** for A and **${ts_sum(ts_c, ts_bs, ts_be).toFixed(1)}** for B, a gap of ${(ts_sum(ts_c, ts_as, ts_ae) - ts_sum(ts_c, ts_bs, ts_be)).toFixed(1)} points from style alone.`\n```\n\nAt the defaults A expects 43.0 and B 35.1, from the same conscientiousness. The lines cross at $-0.9$, the direction node's difficulty, and below it A scores *lower* than B. Extreme responding stretches sums away from the middle in whichever direction the content points, so no constant can correct for it.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Respondents C and D have the same content $\\\\theta$, well below the middle of the scale. C has a high $\\\\theta$ at the extreme node, D a low one. Whose sum score do you expect to be higher?\",\n  options: [\n    {text: \"D's\", correct: true, why: \"Below the middle, both lean to the disagree side. C turns 2s into 1s, which lowers the sum; D stays at 2.\"},\n    {text: \"C's\", correct: false, why: \"That holds above the middle, where going to the end turns 4s into 5s. Below it, going to the end turns 2s into 1s.\"},\n    {text: \"The same: the style doesn't change the sum\", correct: false, why: \"It doesn't change the content $\\\\theta$, but it changes the categories chosen and so the sum. Try it in the widget with the content θ below −0.9.\"}\n  ]\n})\n```\n\n### Trees for what the response hides: speed and skips\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Guessing and priors](guessing-priors.qmd): in a timed lexical decision task, responses under 0.3 seconds were correct at about chance, and a few respondents gave most of them. Rapid guessing there looked like a property of respondents, not items. Skipped responses were left for this lesson.\n:::\n\nA first node can record what the response doesn't show. A node for \"answered in under $t$ seconds\" gives every respondent a speed $\\theta$, correlated with the content $\\theta$, and the content node can then be fitted to slow responses only, or given separate item parameters for fast and slow ones ([Partchev & De Boeck, 2012](https://doi.org/10.1016/j.intell.2011.11.002); [DiTrapani, Jeon, De Boeck & Partchev, 2016](https://doi.org/10.1016/j.intell.2016.02.012)). Time as a continuous variable is the subject of [Response time and the speed-accuracy tradeoff](response-time.qmd).\n\nA skip is usually scored as wrong or left missing, both reasonable when skipping has nothing to do with ability. When lower-ability respondents skip more, skipping carries information about $\\theta$, and the missing responses are *not ignorable* ([Holman & Glas, 2005](https://doi.org/10.1348/000711005X47168); [Glas & Pimentel, 2008](https://doi.org/10.1177/0013164408315262)). A tree whose first node is \"answered?\" and second \"correct, given answered?\" puts that information into the model: the correlation between the two node $\\theta$s carries it to the content estimate ([Debeer, Janssen & De Boeck, 2017](https://doi.org/10.1111/jedm.12147)). None of the IRW tables with a tokenless download has enough skips to show this, so the simulation below does.\n\n## Simulate\n\nPart 1 generates 1–5 ratings from Böckenholt's tree (400 respondents, 10 items, correlated node $\\theta$s), fits one $\\theta$ and a $\\theta$ per node, and compares both with the truth. Part 2 simulates a 15-item right–wrong test on which lower-ability respondents skip more, and scores the skips as wrong, as missing, and with a skip node. The first run takes one to two minutes, most of it installing and loading `lme4`; `nAGQ = 0` keeps each fit to seconds.\n\nWith the seed as written, AIC prefers a $\\theta$ per node (11,234 against 11,679), and the node SDs and correlations come back within about 0.13 of the truth. The content estimates from the per-node tree correlate 0.88 with the true content $\\theta$, against 0.69 from the one-$\\theta$ tree, which mixes content with style. In part 2, the 77 respondents who skipped most skipped about half the items. Scored as wrong, their abilities come out 0.24 too low on average; left missing, 0.41 too high, since the model pulls respondents with few answers toward the mean, and these respondents are below it. With the skip node the error is 0.02. Try `R` with every correlation set to 0, a skip rate that doesn't depend on ability (`skipper <- rnorm(np2)`), or `np <- 2000` locally.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-16\n# Simulate from IRTree models and fit them with lme4.\n# Part 1: ratings from 1 to 5 generated by a three-node tree (take a side?\n#   which side? how far?) whose node abilities are correlated. Fit one theta for\n#   all nodes and one theta per node; compare with the truth.\n# Part 2: a test with skipped items, where lower-ability respondents skip more.\n#   Score the skips as wrong, as missing, or with a skip node, and see whose\n#   abilities come out biased.\n# nAGQ = 0 makes glmer() skip its slowest step, so the fits take seconds; delete\n# \", nAGQ = 0\" in your own R session for the full Laplace fit. Adapted from\n# ben-domingue/252: c8/irtree_sim.R.\nlibrary(lme4)\nset.seed(51)\n\n## Part 1: a three-node tree\nnp <- 400                                       # respondents (try 2000 locally)\nni <- 10                                        # items\nsds <- c(side = 0.8, direction = 1.7, extreme = 1.2)          # SDs of the node thetas\nR <- matrix(c(1, 0.6, 0.3,  0.6, 1, 0.2,  0.3, 0.2, 1), 3)   # their correlations\ntheta <- matrix(rnorm(np * 3), np) %*% chol(R) %*% diag(sds)\nb <- cbind(side = rnorm(ni, -1.2, 0.5), direction = rnorm(ni, -0.9, 0.8),\n           extreme = rnorm(ni, 0.5, 0.5))       # node difficulties, item by item\nx <- sapply(1:ni, function(i) {\n  side <- rbinom(np, 1, plogis(theta[, 1] - b[i, 1]))\n  up   <- rbinom(np, 1, plogis(theta[, 2] - b[i, 2]))\n  ext  <- rbinom(np, 1, plogis(theta[, 3] - b[i, 3]))\n  ifelse(side == 0, 3, ifelse(up == 1, 4 + ext, 2 - ext))  # walk down the tree\n})\n\n# Recode: one row per node reached.\nlong <- data.frame(id = rep(1:np, ni), item = rep(sprintf(\"i%02d\", 1:ni), each = np), x = c(x))\nsided <- long[long$x != 3, ]\ntree <- rbind(data.frame(long,  node = \"side\",      resp = as.integer(long$x != 3)),\n              data.frame(sided, node = \"direction\", resp = as.integer(sided$x > 3)),\n              data.frame(sided, node = \"extreme\",   resp = as.integer(sided$x %in% c(1, 5))))\ntree$node <- factor(tree$node, levels = c(\"side\", \"direction\", \"extreme\"))\n\none <- glmer(resp ~ 0 + item:node + (1 | id), tree, binomial, nAGQ = 0)\nper <- glmer(resp ~ 0 + item:node + (0 + node | id), tree, binomial, nAGQ = 0)\n\ncat(\"Share of responses in each category:\\n\")\nprint(round(prop.table(table(x)), 2))\ncat(\"\\nAIC, one theta and a theta per node:\", round(AIC(one)), round(AIC(per)), \"\\n\")\nvc <- VarCorr(per)$id\ncat(\"\\nSDs of the node thetas, true and estimated:\\n\")\nprint(round(rbind(true = sds, estimated = attr(vc, \"stddev\")), 2))\npairs <- rbind(c(2, 1), c(3, 1), c(3, 2))\ncat(\"\\nCorrelations between nodes, true and estimated:\\n\")\ncm <- rbind(true = R[pairs], estimated = attr(vc, \"correlation\")[pairs])\ncolnames(cm) <- c(\"side-direction\", \"side-extreme\", \"direction-extreme\")\nprint(round(cm, 2))\ncat(\"\\nHow well each model's estimates track the true content (direction) theta:\",\n    \"\\n  one theta:\", round(cor(ranef(one)$id[, 1], theta[, 2]), 2),\n    \"\\n  theta per node:\", round(cor(ranef(per)$id[, \"nodedirection\"], theta[, 2]), 2), \"\\n\")\n\n## Part 2: skipped items\nnp2 <- 600                                      # respondents\nni2 <- 15                                       # right/wrong items\nability <- rnorm(np2)\nskipper <- -0.6 * ability + sqrt(1 - 0.6^2) * rnorm(np2)  # lower ability, more skipping\nskipped <- matrix(rbinom(np2 * ni2, 1, plogis(1.2 * skipper - 2)), np2)\ncorrect <- matrix(rbinom(np2 * ni2, 1, plogis(outer(ability, seq(-2, 2, length = ni2), \"-\"))), np2)\nd <- data.frame(id = rep(1:np2, ni2), item = rep(sprintf(\"q%02d\", 1:ni2), each = np2),\n                skip = c(skipped), y = c(correct))\n\nas_wrong <- glmer(ifelse(skip == 1, 0, y) ~ 0 + item + (1 | id), d, binomial, nAGQ = 0)\nas_missing <- glmer(y ~ 0 + item + (1 | id), d[d$skip == 0, ], binomial, nAGQ = 0)\nanswered <- d[d$skip == 0, ]\nst <- rbind(data.frame(d, node = \"answer\", resp = 1 - d$skip),\n            data.frame(answered, node = \"correct\", resp = answered$y))\nst$node <- factor(st$node, levels = c(\"answer\", \"correct\"))\nskip_node <- glmer(resp ~ 0 + item:node + (0 + node | id), st, binomial, nAGQ = 0)\n\nest <- function(m, col = 1) {\n  r <- ranef(m)$id\n  setNames(r[, col], rownames(r))[as.character(1:np2)]\n}\ntheta_hat <- cbind(wrong = est(as_wrong), missing = est(as_missing),\n                   \"skip node\" = est(skip_node, \"nodecorrect\"))\nn_skip <- rowSums(skipped)\nmost <- n_skip >= quantile(n_skip, 0.9)         # the tenth who skipped most\ncat(\"\\nShare of items skipped:\", round(mean(skipped), 2),\n    \"; the\", sum(most), \"respondents who skipped most skipped\", round(mean(n_skip[most]), 1), \"of\", ni2, \"\\n\")\ncat(\"Mean error in estimated ability (estimate - truth):\\n\")\nprint(round(rbind(\"skipped most\" = colMeans(theta_hat[most, ] - ability[most], na.rm = TRUE),\n                  \"everyone else\" = colMeans(theta_hat[!most, ] - ability[!most], na.rm = TRUE)), 2))\ncat(\"Estimated correlation of the answer and correct nodes:\",\n    round(attr(VarCorr(skip_node)$id, \"correlation\")[1, 2], 2), \"(true 0.6)\\n\")\n\n```\n:::\n\n\n[Download this code](code/irtrees-sim.R) to run it as large as you like in your own R session.\n\n## With real data\n\n\n\n### Conscientiousness and response styles\n\nThe main example is [bfi_goldberg_1992_conscientiousness](https://itemresponsewarehouse.org/tables/bfi_goldberg_1992_conscientiousness/): the ten conscientiousness items of the IPIP Big-Five factor markers ([Goldberg, 1992](https://doi.org/10.1037/1040-3590.4.1.26); [Goldberg et al., 2006](https://doi.org/10.1016/j.jrp.2005.08.007)), answered online around 2012 through the [Open-Source Psychometrics Project](https://openpsychometrics.org/_rawdata/). Its job is to be a five-point scale on which response styles could be at work. The IRW's [item-text check](https://github.com/ben-domingue/irw/blob/main/itemtext/itemtables/batch_261/provenance.csv) confirmed that these are the IPIP markers rather than the Big Five Inventory. IPIP items are in the public domain, so we can quote them: C1 is \"I am always prepared\" and C2 \"I leave my belongings around\" ([Goldberg et al., 2006](https://doi.org/10.1016/j.jrp.2005.08.007); [IPIP key](https://ipip.ori.org/newBigFive5broadKey.htm)). Responses run from 1 (disagree) through 3 (neutral) to 5 (agree), with 2 and 4 unlabelled. [Download the code](code/irtrees-irw.R) to run every chunk yourself.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd): items worded against the construct have to be reverse-keyed before they are combined, and the key should come from the documentation and be checked in the data, since neither is enough alone.\n:::\n\nIn a tree, keying decides what the direction node means: keyed, it measures conscientiousness on every item; unkeyed, it asks \"agree?\", which mixes conscientiousness with acquiescence. The side and extreme nodes don't change. The IPIP key reverses C2, C4, C6 and C8, and the data agree:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(lme4)\noptions(digits = 7)  # R's default, in case a .Rprofile changes it\nset.seed(51)\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.bfi_goldberg_1992_conscientiousness/rows?format=csv\"\ndf <- read.csv(url)\ndf <- df[!is.na(df$resp), ]\nwide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\nwide <- wide[complete.cases(wide), paste0(\"C\", 1:10)]\nc(respondents = nrow(wide), items = ncol(wide))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents       items \n      19718          10 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The responses arrive as given: 1 = disagree, 3 = neutral, 5 = agree. C2, C4, C6\n# and C8 are worded against conscientiousness. Before keying, their correlations\n# with C1 (\"I am always prepared\") are negative:\nround(cor(wide)[1, ], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   C1    C2    C3    C4    C5    C6    C7    C8    C9   C10 \n 1.00 -0.26  0.30 -0.35  0.39 -0.31  0.31 -0.32  0.43  0.33 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Key them (reversing maps k to 6 - k), so that higher = more conscientious.\nreversed <- paste0(\"C\", c(2, 4, 6, 8))\nwide[, reversed] <- 6 - wide[, reversed]\nround(cor(wide)[1, ], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  C1   C2   C3   C4   C5   C6   C7   C8   C9  C10 \n1.00 0.26 0.30 0.35 0.39 0.31 0.31 0.32 0.43 0.33 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# A random 3,000 respondents keep the fits quick.\nx <- wide[sample(nrow(wide), 3000), ]\nround(prop.table(table(x)), 3)   # share of responses in each category\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nx\n    1     2     3     4     5 \n0.095 0.164 0.241 0.282 0.218 \n```\n\n\n:::\n:::\n\n\nBefore keying, the four reversed items correlate from $-0.26$ to $-0.35$ with C1; after, every item correlates positively with it (0.26 to 0.43). All 19,718 respondents answered all ten items. We take a random 3,000, whose responses lean to the agree side: 21.8% of responses are 5 and 9.5% are 1. Now the recoding:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# One row per node a response reaches. Node 1: took a side (1) or chose 3 (0).\n# Given a side, node 2: the agree side, 4 or 5 (1), or the disagree side (0); and\n# node 3: an extreme response, 1 or 5 (1), or a moderate one (0).\nlong <- data.frame(id = rep(seq_len(nrow(x)), ncol(x)),\n                   item = rep(colnames(x), each = nrow(x)), x = c(x))\nsided <- long[long$x != 3, ]\ntree <- rbind(\n  data.frame(long,  node = \"side\",      resp = as.integer(long$x != 3)),\n  data.frame(sided, node = \"direction\", resp = as.integer(sided$x > 3)),\n  data.frame(sided, node = \"extreme\",   resp = as.integer(sided$x %in% c(1, 5))))\ntree$node <- factor(tree$node, levels = c(\"side\", \"direction\", \"extreme\"))  # a factor, not text\ntree$item <- factor(tree$item, levels = colnames(x))\n# Respondent 1's answers to C1 and C2, and the pseudo-items they become:\nx[1, 1:2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nC1 C2 \n 3  5 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntree[tree$id == 1 & tree$item %in% c(\"C1\", \"C2\"), c(\"item\", \"x\", \"node\", \"resp\")]\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |item |  x|node      | resp|\n|:-----|:----|--:|:---------|----:|\n|1     |C1   |  3|side      |    0|\n|3001  |C2   |  5|side      |    1|\n|30011 |C2   |  5|direction |    1|\n|30012 |C2   |  5|extreme   |    1|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(tree$node)   # rows per node: every response reaches node 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     side direction   extreme \n    30000     22762     22762 \n```\n\n\n:::\n:::\n\n\nRespondent 1's 3 on C1 becomes one row; their keyed 5 on C2 (a raw 1) becomes three. All 30,000 responses reach the side node, and the 22,762 that took a side reach the other two. Now the two trees:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same tree with one theta for all three nodes, and with a theta per node.\n# Each item has its own easiness at each node (item:node); b = -easiness.\n# nAGQ = 0 skips glmer's slowest step; the estimates barely move.\none <- glmer(resp ~ 0 + item:node + (1 | id), data = tree, family = binomial, nAGQ = 0)\nper <- glmer(resp ~ 0 + item:node + (0 + node | id), data = tree, family = binomial, nAGQ = 0)\nAIC(one, per)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    | df|      AIC|\n|:---|--:|--------:|\n|one | 31| 85738.29|\n|per | 36| 82597.71|\n\n</div>\n:::\n:::\n\n\nA $\\theta$ per node improves the AIC by more than 3,000 points (82,598 against 85,738, for five more parameters). The three decisions are not one dimension. Are they three unrelated ones?\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Across respondents, does the tendency to take a side (avoid 3) go with the tendency to choose 1 or 5? And does either track conscientiousness (the direction node)?\",\n  choices: [\"All three correlate about 0.6\", \"Side and extreme correlate strongly; each correlates weakly with conscientiousness\", \"All three are nearly uncorrelated\"],\n  answer: \"Side and extreme correlate strongly; each correlates weakly with conscientiousness\",\n  reveal: \"Side and extreme correlate 0.68; with conscientiousness, 0.33 and 0.24. Leaving the middle and going to the ends are largely one habit, and it has little to do with how conscientious a respondent is. Check the output below.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nVarCorr(per)   # SDs of the three node thetas and their correlations\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups Name          Std.Dev. Corr        \n id     nodeside      0.77931              \n        nodedirection 1.74973  0.327       \n        nodeextreme   1.23659  0.680 0.241 \n```\n\n\n:::\n:::\n\n\nThe side and extreme $\\theta$s correlate 0.68: respondents who leave the middle also go to the ends. With conscientiousness they correlate only 0.33 and 0.24. The content $\\theta$ varies most (SD 1.75, against 0.78 and 1.24).\n\n::: {.callout-note collapse=\"true\"}\n## What the styles do to sum scores\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# What do the styles do to the sum score? theta estimates (conditional modes) for\n# each respondent, split by where they stand on conscientiousness.\nth <- ranef(per)$id\nr <- rowSums(x)\nhigh <- th$nodedirection > 1\nlow <- th$nodedirection < -1\nround(c(sum_with_content = cor(r, th$nodedirection),\n        sum_with_extreme_if_high = cor(r[high], th$nodeextreme[high]),\n        sum_with_extreme_if_low = cor(r[low], th$nodeextreme[low])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        sum_with_content sum_with_extreme_if_high  sum_with_extreme_if_low \n                    0.95                     0.88                    -0.55 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(high = sum(high), low = sum(low))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nhigh  low \n 825  785 \n```\n\n\n:::\n:::\n\n\nThe sum score and the content $\\theta$ correlate 0.95, so the sum orders respondents much as the content $\\theta$ does. But among the 825 respondents whose content $\\theta$ is above 1, the sum correlates 0.88 with the extreme $\\theta$, and among the 785 below $-1$, $-0.55$. As in the widget, extreme responding stretches the sum away from the middle: conscientious respondents who like the ends score higher than those who don't, and unconscientious ones lower. (These are estimates of each respondent's $\\theta$s, shrunk toward the mean, so treat the correlations as descriptive.)\n:::\n\nCan the tree's AIC be compared with the graded response model's? Only when both are computed the same way from the same responses. `glmer` with `nAGQ = 0` approximates the marginal likelihood and `mirt` integrates it by quadrature, so the same tree gets a different log likelihood from each; and a tree that drops categories, as the speed tree below drops the content of fast responses, describes different data. Böckenholt's tree describes all five categories, so we fit it and the GRM in `mirt`:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Can the tree's AIC be compared with the GRM's? Fit both by the same method: mirt,\n# which integrates over theta by quadrature. The tree becomes 30 pseudo-items (NA\n# where a response doesn't reach a node), each loading on its node's dimension with\n# a slope fixed at 1; the three dimensions have free variances and correlations.\npseudo <- data.frame(ifelse(x == 3, 0, 1),\n                     ifelse(x == 3, NA, 1 * (x > 3)),\n                     ifelse(x == 3, NA, 1 * (x == 1 | x == 5)))\nnames(pseudo) <- paste0(rep(c(\"side_\", \"dir_\", \"ext_\"), each = 10), colnames(x))\nspec <- mirt::mirt.model(\"side = 1-10\\n dir = 11-20\\n ext = 21-30\\n COV = side*dir*ext\")\ntree_mirt <- mirt::mirt(pseudo, spec, itemtype = \"Rasch\", verbose = FALSE)\ntree_mirt1 <- mirt::mirt(pseudo, 1, itemtype = \"Rasch\", verbose = FALSE)  # one theta\ngrm <- mirt::mirt(as.data.frame(x), 1, itemtype = \"graded\", verbose = FALSE)\nfits <- list(tree_mirt1, tree_mirt, grm)\ndata.frame(parameters = c(attr(logLik(one), \"df\"), attr(logLik(per), \"df\"),\n                          sapply(fits, mirt::extract.mirt, \"nest\")),\n           logLik = round(c(logLik(one), logLik(per), sapply(fits, mirt::extract.mirt, \"logLik\"))),\n           AIC = round(c(AIC(one), AIC(per), sapply(fits, mirt::extract.mirt, \"AIC\"))),\n           row.names = c(\"tree, one theta, glmer\", \"tree, theta per node, glmer\",\n                         \"tree, one theta, mirt\", \"tree, theta per node, mirt\", \"GRM, mirt\"))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                            | parameters| logLik|   AIC|\n|:---------------------------|----------:|------:|-----:|\n|tree, one theta, glmer      |         31| -42838| 85738|\n|tree, theta per node, glmer |         36| -41263| 82598|\n|tree, one theta, mirt       |         31| -42819| 85699|\n|tree, theta per node, mirt  |         36| -41144| 82361|\n|GRM, mirt                   |         50| -41571| 83242|\n\n</div>\n:::\n:::\n\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Model fit and out-of-sample prediction](fit-prediction.qmd): AIC compares models fitted to the same data by the same likelihood; it says which model is preferred, not how much better it predicts. The IMV puts that on a common scale.\n:::\n\nThe per-node tree's log likelihood is $-41{,}263$ from `glmer` and $-41{,}144$ from `mirt`: 119 apart from the approximation alone. Within `mirt`, that tree beats the GRM (AIC 82,361 against 83,242, with 36 parameters against 50), and the tree with one $\\theta$ falls far behind both (85,699). The tree wins because it has style dimensions the GRM lacks (problem 3 gives a rival the same advantage).\n\nSo when would I fit a tree? The case rests on an assumption about the response process: that choosing the middle, a side and the end are separate decisions. When I have such a process in mind (midpoint avoidance, extreme responding, speed, skipping), I'd fit the tree, because it gives the process a parameter and estimates the content net of it. As a general replacement for the graded response model, with one $\\theta$, I wouldn't: here it is the worst of the three. \n\n### Extraversion and fast responses\n\nFor contrast, [introversion_extroversion](https://itemresponsewarehouse.org/tables/introversion_extroversion/): 91 statements from the development of the Multidimensional Introversion-Extraversion Scales, answered online around 2012 through the same project ([MIES development data and codebook](http://openpsychometrics.org/_rawdata/MIES_Dev_Data.zip)), with the time spent on each. Its job is to ask whether fast responding says anything about the trait. Items 81–85 and 89–91 are eight of the ten IPIP extraversion markers ([Goldberg, 1992](https://doi.org/10.1037/1040-3590.4.1.26)), the same family as the conscientiousness items, and we use those. Responses run from 1 (disagree) to 5 (agree). Five of the eight are worded toward introversion (\"I keep in the background\", for one; [MIES codebook](http://openpsychometrics.org/_rawdata/MIES_Dev_Data.zip)), so we key them, higher meaning more extraverted.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl_ie <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.introversion_extroversion/rows?format=csv\"\nie <- read.csv(url_ie)\nc(respondents = length(unique(ie$id)), items = length(unique(ie$item)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents       items \n       7188          91 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(quantile(ie$rt, c(0.1, 0.5, 0.9)), 1)   # seconds per item, all 91 items\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n10% 50% 90% \n1.8 3.2 6.9 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Items 81-85 and 89-91 are eight of the ten IPIP extraversion markers. 81-85 are\n# worded toward introversion, so we key them: higher = more extraverted.\ne <- ie[ie$item %in% c(81:85, 89:91), ]\ne$x <- ifelse(e$item %in% 81:85, 6 - e$resp, e$resp)\ne$fast <- as.integer(e$rt < 2)\nround(c(share_fast = mean(e$fast),\n        median_rt = median(e$rt)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nshare_fast  median_rt \n      0.21       2.77 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(e$x == 3, e$fast, mean), 3)   # share choosing 3, slow (0) and fast (1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    0     1 \n0.157 0.082 \n```\n\n\n:::\n:::\n\n\nThe median response took 3.2 seconds across all 91 items and 2.77 on our eight, where 21% came in under 2 seconds; fast responses chose the middle less often (8.2% against 15.7%). A two-node tree on a random 1,500 respondents asks: was the response fast? If not, was it on the extraverted side?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Two nodes, after ps8/fast.R: was the response fast (under 2 seconds)? If not,\n# was it on the extraverted side (keyed 4 or 5)? Fast responses stop at node 1.\nids <- sample(unique(e$id), 1500)\ns <- e[e$id %in% ids, ]\nslow <- s[s$fast == 0, ]\nst <- rbind(data.frame(id = s$id, item = s$item, node = \"fast\", resp = s$fast),\n            data.frame(id = slow$id, item = slow$item, node = \"trait\",\n                       resp = as.integer(slow$x >= 4)))\nst$node <- factor(st$node, levels = c(\"fast\", \"trait\"))\nst$item <- factor(st$item)\nspeed <- glmer(resp ~ 0 + item:node + (0 + node | id), data = st, family = binomial, nAGQ = 0)\nVarCorr(speed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups Name      Std.Dev. Corr   \n id     nodefast  1.4853          \n        nodetrait 1.7392   -0.075 \n```\n\n\n:::\n:::\n\n\nRespondents differ in speed (SD 1.49 at the fast node), but the speed and extraversion $\\theta$s correlate $-0.075$: how quickly someone answers these items says next to nothing about how extraverted they are. Are fast responses careless, then?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Do fast responses carry the trait? Each respondent's mean keyed response on their\n# fast items against the mean on their slow items.\nm_fast <- tapply(e$x[e$fast == 1], e$id[e$fast == 1], mean)\nm_slow <- tapply(e$x[e$fast == 0], e$id[e$fast == 0], mean)\nboth <- intersect(names(m_fast), names(m_slow))\nc(respondents_with_both = length(both), r = round(cor(m_fast[both], m_slow[both]), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents_with_both                     r \n              4668.00                  0.73 \n```\n\n\n:::\n:::\n\n\nNo. For the 4,668 respondents with both fast and slow responses, the mean keyed response on the fast items correlates 0.73 with the mean on the slow ones. Rapid responses in [Guessing and priors](guessing-priors.qmd) were at chance; here a response under 2 seconds looks like a respondent who knew their answer.\n\n## Problems\n\n1. **The tree's probabilities.** For Böckenholt's tree, write $\\Pr(x = k)$ for $k = 1, \\dots, 5$ in terms of the three node probabilities, and show that they sum to 1. Then show that a linear tree with Rasch nodes and one $\\theta$ is the sequential model, and explain why it is not the partial credit model, although both have one parameter per category boundary.\n2. **The other four traits.** Fit Böckenholt's tree to the other four `bfi_goldberg_1992_*` tables (key each from the [IPIP key](https://ipip.ori.org/newBigFive5broadKey.htm), checked in the data). Are the side and extreme $\\theta$s as strongly correlated for every trait? Do one respondent's style $\\theta$s from different traits correlate, as a style should? (The five tables share respondent ids.)\n3. **Comparing the tree with the GRM.** When can you compare the tree's AIC with the GRM's? Then give a rival without a tree the same advantage: in `mirt`, a multidimensional GPCM whose second dimension scores categories 1 and 5 as 1 and the others as 0 (the `gpcm_mats` argument) has an extreme-response dimension of its own. Compare it with the tree. What does the comparison say about the tree's advantage over the GRM?\n4. **Two countries.** A survey is given in two countries whose respondents differ in how often they choose the ends of a scale. What can Böckenholt's tree correct for when you compare the countries' means, and what can't it? Would you change the instrument as well as the model?\n5. **The 2-second cut.** Refit the speed tree with cuts at 1, 1.5 and 3 seconds. How does the share of fast responses change, and the correlation between speed and extraversion? Is there a cut below which fast responses stop tracking the trait? (PS8#4)\n6. **Challenge (open): the skip $\\theta$.** On a low-stakes test, a skip node gives every respondent a second $\\theta$, their tendency to answer. Does it belong in the reported score? Consider what the score is for and whether a respondent could raise it by skipping less. I don't have a general answer.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22IRTree%20models%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20IRTree%20models%3A%20writing%20a%20polytomous%20response%20as%20a%20sequence%20of%20binary%20decisions%20%28nodes%29%20and%20its%20probability%20as%20a%20product%20along%20a%20path%3B%20linear%20and%20nested%20trees%3B%20one%20ability%20for%20all%20nodes%20or%20one%20per%20node%2C%20and%20the%20sequential%20model%20as%20a%20linear%20tree%3B%20fitting%20a%20tree%20by%20recoding%20responses%20into%20pseudo-items%20and%20using%20lme4%27s%20glmer%20or%20mirt%3B%20separating%20content%20from%20midpoint%20and%20extreme%20response%20styles%20with%20B%C3%B6ckenholt%27s%20tree%3B%20and%20nodes%20for%20fast%20responses%20and%20skipped%20items%2C%20with%20IPIP%20conscientiousness%20and%20extraversion%20items%20from%20the%20Open-Source%20Psychometrics%20Project%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- De Boeck, P., & Partchev, I. (2012). IRTrees: Tree-based item response models of the GLMM family. *Journal of Statistical Software*, 48(Code Snippet 1). <https://doi.org/10.18637/jss.v048.c01>. The recoding into pseudo-items and the `glmer` fit, with linear and nested trees.\n- Böckenholt, U. (2012). Modeling multiple response processes in judgment and choice. *Psychological Methods*, 17(4), 665–678. <https://doi.org/10.1037/a0028111>. The side, direction and extreme tree for rating scales.\n- Böckenholt, U. (2017). Measuring response styles in Likert items. *Psychological Methods*, 22(1), 69–83. <https://doi.org/10.1037/met0000106>. Trees for response styles, set beside other approaches.\n- Jeon, M., & De Boeck, P. (2016). A generalized item response tree model for psychological assessments. *Behavior Research Methods*, 48(3), 1070–1085. <https://doi.org/10.3758/s13428-015-0631-y>. Trees with slopes and more flexible links between nodes and dimensions.\n- Plieninger, H., & Meiser, T. (2014). Validity of multiprocess IRT models for separating content and response styles. *Educational and Psychological Measurement*, 74(5), 875–899. <https://doi.org/10.1177/0013164413514998>. Whether the style nodes measure style.\n- Meiser, T., Plieninger, H., & Henninger, M. (2019). IRTree models with ordinal and multidimensional decision nodes for response styles and trait-based rating responses. *British Journal of Mathematical and Statistical Psychology*, 72(3), 501–516. <https://doi.org/10.1111/bmsp.12158>. Ordinal nodes, relaxing the assumption that a midpoint says nothing about direction.\n- Khorramdel, L., & von Davier, M. (2014). Measuring response styles across the Big Five: A multiscale extension of an approach using multinomial processing trees. *Multivariate Behavioral Research*, 49(2), 161–177. <https://doi.org/10.1080/00273171.2013.866536>. Style dimensions shared across personality scales (problem 2).\n- Baumgartner, H., & Steenkamp, J.-B. E. M. (2001). Response styles in marketing research: A cross-national investigation. *Journal of Marketing Research*, 38(2), 143–156. <https://doi.org/10.1509/jmkr.38.2.143.18840>. Response styles across countries, and what they do to means and correlations (problem 4).\n- Debeer, D., Janssen, R., & De Boeck, P. (2017). Modeling skipped and not-reached items using IRTrees. *Journal of Educational Measurement*, 54(3), 333–363. <https://doi.org/10.1111/jedm.12147>. Skip and not-reached nodes in achievement tests.\n- Holman, R., & Glas, C. A. W. (2005). Modelling non-ignorable missing-data mechanisms with item response theory models. *British Journal of Mathematical and Statistical Psychology*, 58(1), 1–17. <https://doi.org/10.1348/000711005X47168>. Missingness as a second latent dimension, the idea behind a skip node.\n- Glas, C. A. W., & Pimentel, J. L. (2008). Modeling nonignorable missing data in speeded tests. *Educational and Psychological Measurement*, 68(6), 907–922. <https://doi.org/10.1177/0013164408315262>. The same idea for items not reached.\n- Partchev, I., & De Boeck, P. (2012). Can fast and slow intelligence be differentiated? *Intelligence*, 40(1), 23–32. <https://doi.org/10.1016/j.intell.2011.11.002>. Fast and slow responses as branches of a tree.\n- DiTrapani, J., Jeon, M., De Boeck, P., & Partchev, I. (2016). Attempting to differentiate fast and slow intelligence: Using generalized item response trees to examine the role of speed on intelligence tests. *Intelligence*, 56, 82–92. <https://doi.org/10.1016/j.intell.2016.02.012>. A speed node with its own dimension.\n- Tutz, G. (1990). Sequential item response models with an ordered response. *British Journal of Mathematical and Statistical Psychology*, 43(1), 39–55. <https://doi.org/10.1111/j.2044-8317.1990.tb00925.x>. The sequential model, a linear tree.\n- Rubin, D. B. (1976). Inference and missing data. *Biometrika*, 63(3), 581–592. <https://doi.org/10.1093/biomet/63.3.581>. Missing at random, and when missingness can be ignored.\n- Bates, D., Mächler, M., Bolker, B., & Walker, S. (2015). Fitting linear mixed-effects models using lme4. *Journal of Statistical Software*, 67(1). <https://doi.org/10.18637/jss.v067.i01>. The package for the tree fits.\n- Chalmers, R. P. (2012). mirt: A multidimensional item response theory package for the R environment. *Journal of Statistical Software*, 48(6). <https://doi.org/10.18637/jss.v048.i06>. The package for the tree and GRM fits compared by AIC.\n- Goldberg, L. R., Johnson, J. A., Eber, H. W., Hogan, R., Ashton, M. C., Cloninger, C. R., & Gough, H. G. (2006). The International Personality Item Pool and the future of public-domain personality measures. *Journal of Research in Personality*, 40(1), 84–96. <https://doi.org/10.1016/j.jrp.2005.08.007>. The public-domain item pool behind both examples.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`bfi_goldberg_1992_conscientiousness`](https://itemresponsewarehouse.org/tables/bfi_goldberg_1992_conscientiousness/): Goldberg, Lewis R. \"The development of markers for the Big-Five factor structure.\" Psychological assessment 4.1 (1992): 26. <https://doi.org/10.1037/1040-3590.4.1.26>. Licence: CC BY 4.0.\n- [`introversion_extroversion`](https://itemresponsewarehouse.org/tables/introversion_extroversion/): Development of the Multidimensional Introversion-Extraversion ScalesX [dataset and codebook]. <http://openpsychometrics.org/_rawdata/MIES_Dev_Data.zip>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 8 (slides c8, 31–42), problem set 8 (#4, fast responding), and the code in `ben-domingue/252`: `c8/irtree.R`, `c8/irtree2.R`, `c8/irtree_sim.R` and `ps8/fast.R`.\n- **Timing:** the core ideas and widgets take about 45 minutes; the conscientiousness analysis is a 20-minute lab and the speed tree another 10. The real-data code takes about three minutes in local R, most of it the `mirt` fit of the tree, so run it before class.\n- **Changed from 252:** the slides and PS8#4 use `ffm_CSN`, which has no tokenless download. The response-style analysis moves to `bfi_goldberg_1992_conscientiousness` (IPIP markers, like the ffm items) and the fast-responding analysis to eight IPIP extraversion markers in `introversion_extroversion`, which records response times. As in `c8/irtree2.R`, the fits use a random subsample. The keying uses the published IPIP key, checked in the data, rather than the sign of GRM slopes. The skipped-response example is simulated, since no tokenless IRW table has enough skips. The AIC comparison with the GRM is made in `mirt`, where both likelihoods are computed the same way.\n- **Held back:** response time as a continuous variable ([Response time and the speed-accuracy tradeoff](response-time.qmd)); whether style dimensions threaten a validity argument (not taken up in [Gathering validity evidence](validity-evidence.qmd), which comes earlier); choosing among trees for the same categories beyond AIC, for which the IMV is the tool.\n- **Solutions:** held back in `solutions/irtrees.qmd` (not published). Problem 6 is open.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}