{
  "hash": "786bbe641a7f1b681d0870086b4dd2b0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Constructs and construct maps\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Classical test theory  \n**Tranche:** core (a first course)  \n**Before this:** [What is measurement?](measurement.qmd)  \n**Builds toward:** [Classical test theory and reliability](ctt-reliability.qmd) · [Validity as an argument](validity-argument.qmd) · [From construct map to items: building an instrument](instrument-building.qmd)  \n**Picks up threads:** Constructs are measured through probes (from [What is measurement?](measurement.qmd)); Measurement as discovery; is the attribute quantitative? (from [What is measurement?](measurement.qmd))  \n**IRW tables:** [`himmelstein-number_series-2025`](https://itemresponsewarehouse.org/tables/himmelstein-number_series-2025/)  \n**From EDUC 252:** slides c2  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n```{ojs}\n//| echo: false\nimport {grid, logistic, palette} from \"./widgets/irt.js\"\nimport {simTwo, spearman} from \"./widgets/constructs.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nBefore we ask how well a test measures something, we have to say what the something is. [What is measurement?](measurement.qmd) called the attribute we are after a construct. This lesson asks what a statement of one should contain. The answer we build on is Mark Wilson's **construct map**: a line from less to more of the construct, with a description of what respondents at each point can do. A good map orders the items before anyone answers them, and it tells a teacher what to work on next. We try both tests, the first on nine number-series items from the IRW, and ask whether a construct has to be a continuum at all.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- say what a construct is, and write the kind of sentence that gives one its meaning;\n- draw a construct map for a construct you care about, with respondents and items on one line;\n- test a proposed construct: does it order items before data, and suggest what to teach next?\n- say why summary statistics find it hard to tell a continuous construct from latent classes;\n- contrast a test built from a construct map with one built from a blueprint, and say what each lets you claim.\n\n## Core ideas\n\n### What is a construct?\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is measurement?](measurement.qmd): a latent attribute can't be observed directly, so we present **probes** (questions, tasks, statements) that draw out responses bearing on it. A probe whose response is scored is an item, and from there on the course says \"item\".\n:::\n\nWe can't observe reading comprehension, so we need an account of it that tells us which items to write and how to read the responses. [Cronbach and Meehl (1955)](https://doi.org/10.1037/h0040957) gave the classic definition: a construct is an attribute of people that we *postulate*, and assume shows up in test performance. Its meaning, they argued, lies in claims of one form: \"Persons who possess this attribute will, in situation X, act in manner Y (with a stated probability)\" ([Cronbach & Meehl, 1955, p. 284](https://doi.org/10.1037/h0040957)).\n\nThat sentence carries much of this course. \"Situation X\" is the item; \"manner Y\" is the response. \"With a stated probability\" makes the link probabilistic, the premise of every item response model from [The Rasch model](rasch.qmd) on. And \"possess this attribute\" is left open: Cronbach and Meehl allow a *qualitative* attribute (their example is amnesia) as well as a *degree* of a quantitative one (cheerfulness). We come back to that choice below.\n\nThe definition also makes a construct something we propose and could be wrong about. Nobody finds anxiety lying on the pavement; we postulate it because it organizes what people do, and keep it while its predictions hold up. [Validity as an argument](validity-argument.qmd) turns this into a method.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A colleague proposes a construct, *statistics anxiety*, and writes: \\\"Students high in statistics anxiety, when asked to interpret a regression table under time pressure, will skip it or answer at random more often than other students.\\\" Which part of the Cronbach–Meehl sentence is *situation X*?\",\n  options: [\n    {text: \"Being asked to interpret a regression table under time pressure\", correct: true, why: \"The situation is what we present to the respondent: here, the task and its conditions. It plays the role of the item.\"},\n    {text: \"Skipping the table or answering at random\", correct: false, why: \"That is *manner Y*, the response we expect. It is what we record and score.\"},\n    {text: \"Being high in statistics anxiety\", correct: false, why: \"That is the attribute itself, which we postulate and never see. The sentence links it to a situation and a response.\"}\n  ]\n})\n```\n\n### A construct map\n\nThe Cronbach–Meehl definition says what a construct is for, but not what a statement of one should look like. [Wilson (2005, ch. 2)](https://doi.org/10.4324/9781410611697) supplies a simpler form. A **construct map** is a line. At one end are respondents with little of the construct, at the other end respondents with a lot, and along it are qualitatively described **levels**: what a respondent at each point typically knows, believes or can do. Beside the respondents, on the same line, sit the items, each placed at the level its response indicates. The map assumes the construct is a single continuum (one line, not two), an assumption [Factor analysis I](fa-exploratory.qmd) and [Dimensionality](dimensionality.qmd) put to the test.\n\nWhat does a map look like in practice? California's Desired Results Developmental Profile (DRDP), which early-childhood teachers use to rate children's development, is a set of them ([California Department of Social Services & California Department of Education, 2025](https://www.desiredresults.us/desired-results-system/drdp-2025-instrument-and-forms), developed with the Berkeley Evaluation and Assessment Research Center). Each measure is a continuum cut into named levels (Responding, Exploring, Building and, for older children, Integrating and Extending), each with a descriptor and examples. In problem solving, a child at the earliest level notices people and objects; later, the child copies a strategy an adult has shown; later still, the child stops to look at a problem before choosing how to tackle it. The teacher marks the latest level mastered.\n\n#### Try it: respondents and items on one line\n\nOn the left is a construct map for solving number series, the construct behind our real-data example. Move the respondent along the line; on the right is the chance that they solve an item at each level. The locations and curve are stylized.\n\n```{ojs}\n//| echo: false\nviewof cm_theta = Inputs.range([-3, 3], {value: 0.4, step: 0.1, label: \"Respondent's location\"})\n```\n\n```{ojs}\n//| echo: false\ncm_levels = [\n  {level: 1, b: -2, text: \"the same step every time\"},\n  {level: 2, b: -1, text: \"the step changes by a simple pattern\"},\n  {level: 3, b: 0, text: \"the step changes by multiplication\"},\n  {level: 4, b: 1, text: \"two sequences interleaved\"},\n  {level: 5, b: 2, text: \"two sequences as fractions\"}\n]\ncm_now = cm_levels.map(d => ({...d, p: logistic(cm_theta - d.b)}))\ncm_map = Plot.plot({\n  width: 400, height: 340, marginLeft: 10, marginRight: 10,\n  x: {domain: [0, 12], axis: null}, y: {domain: [-3.2, 3.2], label: \"More of the construct ↑\", ticks: []},\n  marks: [\n    Plot.ruleX([5], {y1: -3, y2: 3, stroke: palette.guide}),\n    Plot.dot(cm_levels, {x: 5, y: \"b\", r: 5, fill: palette.main}),\n    Plot.text(cm_levels, {x: 5.3, y: \"b\", text: d => `Level ${d.level}: ${d.text}`, textAnchor: \"start\", fontSize: 10, lineWidth: 14}),\n    Plot.dot([{y: cm_theta}], {x: 4.6, y: \"y\", r: 8, fill: palette.contrast}),\n    Plot.text([{y: cm_theta}], {x: 4.2, y: \"y\", text: () => \"respondent\", textAnchor: \"end\", fill: palette.contrast, fontSize: 10})\n  ]\n})\ncm_bars = Plot.plot({\n  width: 320, height: 340,\n  x: {domain: [0, 1], label: \"Chance of solving an item at this level\"}, y: {type: \"band\", domain: [5, 4, 3, 2, 1], label: \"Level\"},\n  marks: [\n    Plot.barX(cm_now, {x: \"p\", y: \"level\", fill: d => d.b <= cm_theta ? palette.main : palette.light, insetTop: 8, insetBottom: 8}),\n    Plot.ruleX([0.5], {stroke: palette.guide, strokeDasharray: \"4,3\"})\n  ]\n})\nhtl.html`<div style=\"display: flex; flex-wrap: wrap; gap: 1rem;\">${cm_map}${cm_bars}</div>`\n```\n\n```{ojs}\n//| echo: false\nmd`At this location the respondent is more likely than not to solve items at ${cm_now.filter(d => d.p > 0.5).length} of the five levels.`\n```\n\nItems below the respondent are likely to be solved and items above likely to be missed, and the chance changes gradually. Item response models draw this picture with estimated numbers: the Wright map in [The Rasch model](rasch.qmd) puts respondents and items on one scale, and [Information, precision, and short forms](information.qmd) asks where on the line a test measures well.\n\n#### Try it: map the number-series items\n\nHere are the nine items we analyse later; each asks for the missing number. Put each at the level where you think it belongs, reading only its text. The settings start at the lesson's map. The real-data section checks your map against the responses of 1,189 adults.\n\n```{ojs}\n//| echo: false\nns_text = [\n  {item: \"NS_1\", series: \"10, 4, __, -8, -14, -20\", mine: 1},\n  {item: \"NS_2\", series: \"3, 6, 10, 15, 21, __\", mine: 2},\n  {item: \"NS_3\", series: \"121, 100, 81, __, 49\", mine: 2},\n  {item: \"NS_4\", series: \"3, 10, 16, 23, __, 36\", mine: 2},\n  {item: \"NS_5\", series: \"3/21, __, 13/11, 18/6, 23/1, 28/-4\", mine: 5},\n  {item: \"NS_6\", series: \"200, 198, 192, 174, __\", mine: 3},\n  {item: \"NS_7\", series: \"3, 2, 10, 4, 19, 6, 30, 8, __\", mine: 4},\n  {item: \"NS_8\", series: \"10000, 9000, __, 8890, 8889\", mine: 3},\n  {item: \"NS_9\", series: \"3/4, 4/6, 6/8, 8/12, __\", mine: 5}\n]\nviewof ns_map = Inputs.form(Object.fromEntries(ns_text.map(d => [d.item,\n  Inputs.select([1, 2, 3, 4, 5], {value: d.mine, label: `${d.item}: ${d.series}`, format: v => `Level ${v}`})])))\n```\n\n```{ojs}\n//| echo: false\nns_placed = ns_text.map(d => ({...d, level: ns_map[d.item]}))\nPlot.plot({\n  width: 700, height: 150, marginLeft: 20,\n  x: {domain: [0.5, 5.9], label: \"Level on your map\", ticks: [1, 2, 3, 4, 5]}, y: {axis: null, domain: [0, 5]},\n  marks: [\n    Plot.dot(ns_placed, Plot.stackY({x: \"level\", y: () => 1, fill: palette.main, r: 6})),\n    Plot.text(ns_placed, Plot.stackY({x: \"level\", y: () => 1, text: \"item\", dx: 24, fontSize: 10}))\n  ]\n})\n```\n\nTwo readers can place an item differently for defensible reasons. What settles a disagreement is the first of the two tests below.\n\n### Two tests for a proposed construct\n\nHow do we know a construct map is any good before we have data? Two questions help.\n\n1. **Does the map order the items?** Items written for a higher level should be harder (on an attitude scale, less often endorsed) than items for a lower one. This is a prediction made before any data, and the data can refute it. [Gathering validity evidence](validity-evidence.qmd) treats the ordering as evidence about a test's internal structure.\n2. **Does the map suggest an intervention?** A well-articulated map should say how to move someone up it: what a respondent at level 2 has to learn, or give up, to reach level 3. If no plan for teaching can be read off the map, its levels probably describe performances rather than the construct behind them.\n\nThe second test is easiest to see by comparison. One description is a construct map for students' understanding of the Earth in the Solar System, from a project that wrote multiple-choice items whose answer options are each linked to a level ([Briggs, Alonzo, Schwab & Wilson, 2006, Figure 2](https://doi.org/10.1207/s15326977ea1101_2)). Another is the achievement-level descriptors for grade 4 NAEP geography, which say what Basic, Proficient and Advanced students should be able to do ([National Assessment Governing Board, 2001](https://www.nagb.gov/content/dam/nagb/en/documents/publications/achievement/naep-geography-achievement-levels-1992-1998.pdf)). The DRDP is the third. All three are summarized in our own words.\n\n#### Try it: what would you teach next?\n\nPick a description and a level to see what a student there knows, what holds them back (if the description says) and what the next level asks for.\n\n```{ojs}\n//| echo: false\ntd_maps = ({\n  \"Earth in the Solar System (Briggs et al., 2006)\": [\n    {level: \"1\", now: \"Doesn't yet see that objects in the sky appear and move in regular patterns.\", block: \"may not know that the Earth is a sphere\"},\n    {level: \"2\", now: \"Knows the Sun seems to cross the sky each day and the Moon's visible shape changes over about four weeks.\", block: \"may think the Sun travels around the Earth\"},\n    {level: \"3\", now: \"Knows the Earth goes around the Sun, the Moon around the Earth, and the Earth spins; hasn't used these facts to explain what we see.\", block: \"may not realize the Earth spins and orbits at the same time\"},\n    {level: \"4\", now: \"Connects how things appear to move in the sky with how they actually move, without yet a full model of the Solar System.\", block: null},\n    {level: \"5\", now: \"Uses the motions of the Earth and Moon together to explain day and night, the phases of the Moon and the seasons.\", block: null}\n  ],\n  \"NAEP geography, grade 4 (NAGB, 2001)\": [\n    {level: \"Basic\", now: \"Uses and defines basic geographic words; reads and draws simple maps with keys and legends; names major features on maps and globes; gives examples of people, goods and ideas moving between places.\", block: null},\n    {level: \"Proficient\", now: \"Uses geographic knowledge to identify patterns and processes; finds locations on letter-and-number grids; sketches simple maps; describes an issue from more than one point of view; explains how an event in one place can affect another.\", block: null},\n    {level: \"Advanced\", now: \"Describes global patterns and processes; builds models and draws labelled maps of their state, the country and the world; predicts what a change in one place will do to another; analyses how groups interact.\", block: null}\n  ],\n  \"DRDP problem-solving (CDSS & CDE, 2025)\": [\n    {level: \"Responding, earlier\", now: \"Turns toward people, sounds or objects.\", block: null},\n    {level: \"Responding, later\", now: \"Does things with people or objects and watches what happens.\", block: null},\n    {level: \"Exploring, earlier\", now: \"Tries more than one way to do something when it doesn't work.\", block: null},\n    {level: \"Exploring, later\", now: \"Uses a strategy that someone else showed or suggested.\", block: null},\n    {level: \"Building, earlier\", now: \"Thinks up ways to solve everyday problems, with an adult's help.\", block: null},\n    {level: \"Building, middle\", now: \"Picks out parts of an everyday problem and thinks up strategies to try.\", block: null},\n    {level: \"Building, later\", now: \"Stops to look at a problem before trying a strategy aimed at it.\", block: null}\n  ]\n})\nviewof td_which = Inputs.radio(Object.keys(td_maps), {value: Object.keys(td_maps)[0], label: \"Description\"})\n```\n\n```{ojs}\n//| echo: false\nviewof td_i = Inputs.range([1, td_maps[td_which].length], {value: 1, step: 1, label: \"Level (from the bottom)\"})\n```\n\n```{ojs}\n//| echo: false\ntd_rows = td_maps[td_which]\ntd_here = td_rows[Math.min(td_i, td_rows.length) - 1]\ntd_next = td_rows[Math.min(td_i, td_rows.length)]\nmd`**At ${td_here.level}:** ${td_here.now}\n\n**Holding the student back:** ${td_here.block ? td_here.block + \".\" : \"the description doesn't say.\"}\n\n${td_next ? `**The next level asks for:** ${td_next.now}` : \"**This is the top level.**\"}`\n```\n\nStep through the astronomy map from level 1 to level 3. Each level names a belief the student must give up to move on (that the Earth is flat, that the Sun circles the Earth, that the Earth can't spin and orbit at once), and that is a lesson plan: teach against the belief. The NAEP descriptors list performances; the Proficient list asks for more than the Basic list, but doesn't say what a Basic student is missing or what to teach first. The DRDP sits between them: its levels describe a progression, from trial and error to planning, but name no belief to overcome.\n\nWhich is the better construct map? The descriptions were written for different jobs. Achievement-level descriptors say what a score above a cut point means, for reporting to the public, and for that job they are a reasonable choice. A construct map describes the construct itself, and for that job I think the astronomy map comes much closer to the ideal: because each level names the misconception to overcome next, it implies what to teach, and the descriptors don't.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A reading test's levels are: *Level 1: can answer literal questions about a short passage. Level 2: can answer literal and inferential questions. Level 3: can answer literal, inferential and evaluative questions.* Does this pass the intervention test?\",\n  options: [\n    {text: \"Only partly: it orders kinds of question, but it doesn't say what a Level 1 reader lacks that stops them making inferences\", correct: true, why: \"The levels order performances, which helps with writing items (the first test). A plan for teaching needs an account of what changes in the reader between levels: vocabulary, background knowledge, a strategy for linking sentences.\"},\n    {text: \"Yes: it tells the teacher to teach inferential questions next\", correct: false, why: \"It says what to aim at, not how to get there. Compare the astronomy map, which names the belief a student at each level has to give up.\"},\n    {text: \"No: a construct map needs at least five levels\", correct: false, why: \"Nothing fixes the number of levels. Three well-described levels can pass both tests.\"}\n  ]\n})\n```\n\n### A continuum, or classes?\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is measurement?](measurement.qmd): the two thermometers agreed on the order of every bath and disagreed about spacing, and only a theory of temperature could say which was right. Whether an attribute can be measured, and what kind of scale it supports, depends on the attribute itself.\n:::\n\nA construct map assumes the construct varies continuously: anyone could sit anywhere on the line. That is a claim about the attribute, like the thermometers' question, and it could be false. Some influential theories are categorical. [Moffitt (1993)](https://doi.org/10.1037/0033-295X.100.4.674) proposed that young people who behave antisocially fall into two groups with different causes: a small group antisocial at every age, and a larger group antisocial only in adolescence. A follow-up of a New Zealand birth cohort to age 26 kept both and found a third, men aggressive as children but not very delinquent as adolescents ([Moffitt, Caspi, Harrington & Milne, 2002](https://doi.org/10.1017/S0954579402001104)). These are **latent classes**: unobserved groups inside each of which people are alike.\n\nWhich account fits is an empirical question. Taxometric analysis, developed by Meehl and colleagues, asks whether a latent variable is a category or a dimension ([Meehl, 1995](https://doi.org/10.1037/0003-066X.50.4.266)). A review of 311 taxometric findings estimated that about 14% were taxonic (categorical) once study design was accounted for, with little persuasive evidence for categories in normal personality or in mood or anxiety disorders ([Haslam, Holland & Kuppens, 2012](https://doi.org/10.1017/S0033291711001966)). My prior follows that review: the constructs we measure vary much more often continuously than categorically. It is a prior, though, and the widget shows why response data rarely settle it.\n\n#### Try it: continuum or classes?\n\nTwo samples of 1,000 respondents answer ten items. One comes from a continuum (locations drawn from a normal distribution with SD 1), the other from four ordered latent classes, with item locations set so that every item has the same expected proportion correct in both. Which is which? Decide before you reveal.\n\n```{ojs}\n//| echo: false\nviewof cc_sep = Inputs.range([0.5, 3], {value: 1, step: 0.25, label: \"Distance between the classes\"})\nviewof cc_seed = Inputs.range([1, 20], {value: 1, step: 1, label: \"Sample (seed)\"})\nviewof cc_show = Inputs.toggle({label: \"Reveal which is which\", value: false})\n```\n\n```{ojs}\n//| echo: false\ncc_sim = simTwo({seed: cc_seed, n: 1000, sep: cc_sep})\ncc_flip = cc_seed % 2 === 0\ncc_A = cc_flip ? cc_sim.classes : cc_sim.continuum\ncc_B = cc_flip ? cc_sim.continuum : cc_sim.classes\ncc_name = s => s === cc_sim.classes ? \"four classes\" : \"continuum\"\ncc_mean = a => a.reduce((u, v) => u + v, 0) / a.length\ncc_sd = a => { const m = cc_mean(a); return Math.sqrt(a.reduce((u, v) => u + (v - m) ** 2, 0) / (a.length - 1)); }\ncc_panel = (s, label) => Plot.plot({\n  width: 340, height: 230, title: cc_show ? `${label}: ${cc_name(s)}` : label,\n  x: {label: \"Sum score\", domain: [-0.5, 10.5]}, y: {label: \"Respondents\", domain: [0, 260]},\n  marks: [\n    Plot.rectY(s.sums, Plot.binX({y: \"count\"}, {x: d => d, thresholds: grid(-0.5, 10.5, 12), fill: cc_show && s === cc_sim.classes ? palette.contrast : palette.main, inset: 1})),\n    Plot.ruleY([0])\n  ]\n})\nhtl.html`<div style=\"display: flex; flex-wrap: wrap; gap: 1rem;\">${cc_panel(cc_A, \"Sample A\")}${cc_panel(cc_B, \"Sample B\")}</div>`\n```\n\n```{ojs}\n//| echo: false\nmd`Sum-score SD: A ${cc_sd(cc_A.sums).toFixed(2)}, B ${cc_sd(cc_B.sums).toFixed(2)}. Average item-rest correlation: A ${cc_mean(cc_A.itemRest).toFixed(2)}, B ${cc_mean(cc_B.itemRest).toFixed(2)}.${cc_show ? ` Sample ${cc_flip ? \"A\" : \"B\"} is the four classes.` : \"\"}`\n```\n\nWith the classes one unit apart, which gives them about the spread of the continuum, the histograms, SDs and item-rest correlations are close to indistinguishable; try a few seeds. Only when the classes are pulled well apart, around 2.5 or 3, do they show, as a flatter sum-score distribution with more respondents at the extremes. Ordered classes close together behave very much like a continuum cut into pieces, so data that fit one don't rule out the other. Telling them apart takes models fit to the item responses and predictions that differ between the accounts; [Latent classes and cognitive diagnosis](cdm.qmd) takes this up.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A study fits a four-class model to ten binary items and reports that the classes are ordered: the classes' proportions correct rise together on every item. What does that tell you about whether the construct is categorical?\",\n  options: [\n    {text: \"Not much: ordered classes are also what a continuum cut into four pieces looks like\", correct: true, why: \"In the widget, ordered classes close together gave almost the same data as a continuum. Evidence for categories needs something a continuum can't produce, such as classes that differ in *which* items they find hard.\"},\n    {text: \"It confirms the construct is categorical, since the four-class model fit\", correct: false, why: \"A model can fit without being the only model that fits. A continuum would likely fit these data about as well.\"},\n    {text: \"It shows the construct is continuous, since the classes are ordered\", correct: false, why: \"Ordered classes are consistent with a continuum, but they don't rule out real classes that happen to be ordered.\"}\n  ]\n})\n```\n\n### A different starting point: blueprints\n\nNot every test starts from a construct map. Licensure exams, admissions tests and many state school tests start from a **domain**, the knowledge and skills to be covered, and a **blueprint** (the test specifications) saying how many items of each kind to draw from each part of it. The *Standards for Educational and Psychological Testing* treat specifications as the first product of test design: content and its weighting, item formats, length and scoring ([AERA, APA & NCME, 2014, ch. 4](https://www.testingstandards.net/open-access-files.html)). The claim such a test supports is about the domain: this candidate answered 80% of a representative sample of what a new nurse should know. Sometimes the aim is a minimum standard: the written driving test checks that you know the rules of the road, and needs no theory of how that knowledge develops.\n\nA blueprint is a reasonable choice when the domain can be listed and the use is a decision about coverage, as in licensure. It doesn't offer the construct map's two tests: it predicts no item order and suggests nothing to teach beyond the list. It offers content evidence instead, the argument that the items represent the domain ([Validity as an argument](validity-argument.qmd)), and a view of items as a sample from a larger pool ([Many sources of error](g-theory.qmd)).\n\n## Simulate\n\nThe code below simulates 2,000 respondents twice: on a continuum with ten items at five levels, and from four ordered latent classes whose item locations give every item the same expected proportion correct. It prints item means, item-rest correlations and sum-score distributions side by side, in base R, in about a second.\n\nWith the seed as written and the classes one unit apart (`sep <- 1`), the item means agree to within 0.03, the item-rest correlations to within 0.04, and the sum-score SDs are 2.07 and 2.11. Now set `sep <- 3`. The item means still match (by construction), but the item-rest correlations under the classes run from 0.48 to 0.72, against 0.23 to 0.34 for the continuum, and the sum-score SD rises to 2.96. Try other class sizes in `share`, or two classes. How far apart must two classes be before you would bet on them from sum scores alone?\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-17\n# A continuum or latent classes? Simulate item responses from a construct map\n# (respondents on a continuum, items at five levels) and from four latent classes\n# built to have the same item means, then compare what we could see in the data.\n# Base R only. New for this course (EDUC 252 c2 raises the question; the\n# simulation is not in the 252 code).\nset.seed(30)\nn     <- 2000                               # respondents\nb     <- rep(c(-2, -1, 0, 1, 2), each = 2)  # item locations: two items at each of five levels\nshare <- c(0.2, 0.3, 0.3, 0.2)              # sizes of the four classes\nsep   <- 1                                  # distance between neighbouring classes (try 3)\n\n# Model 1, a continuum: theta ~ N(0, 1) and a logistic item curve,\n# P(x = 1) = exp(theta - b) / (1 + exp(theta - b)).\ntheta  <- rnorm(n)\nx_cont <- sapply(b, function(bi) rbinom(n, 1, plogis(theta - bi)))\n\n# Model 2, four ordered latent classes, `sep` apart and centred at 0. Within a\n# class, everyone has the same chance of success on an item.\nloc <- (seq_along(share) - mean(seq_along(share))) * sep\n# Each item's expected proportion correct under model 1 ...\ntarget <- sapply(b, function(bi) integrate(function(t) plogis(t - bi) * dnorm(t), -Inf, Inf)$value)\n# ... and the item location that gives the classes that same proportion.\nb_cls <- sapply(target, function(m) uniroot(function(bb) sum(share * plogis(loc - bb)) - m, c(-10, 10))$root)\ncls   <- sample(seq_along(share), n, replace = TRUE, prob = share)\nx_cls <- sapply(b_cls, function(bi) rbinom(n, 1, plogis(loc[cls] - bi)))\n\n# What could we see? Item means, item-rest correlations, the sum-score distribution.\nitem_rest <- function(x) sapply(seq_len(ncol(x)), function(i) cor(x[, i], rowSums(x[, -i])))\nround(rbind(mean_continuum     = colMeans(x_cont), mean_classes     = colMeans(x_cls),\n            itemrest_continuum = item_rest(x_cont), itemrest_classes = item_rest(x_cls)), 2)\nsums <- rbind(continuum = tabulate(rowSums(x_cont) + 1, 11),\n              classes   = tabulate(rowSums(x_cls) + 1, 11))\ncolnames(sums) <- 0:10\nsums\nround(c(sd_continuum = sd(rowSums(x_cont)), sd_classes = sd(rowSums(x_cls))), 2)\nbarplot(sums, beside = TRUE, col = c(\"#2780e3\", \"#c2410c\"), border = NA,\n        xlab = \"Sum score\", ylab = \"Respondents\", legend.text = c(\"continuum\", \"four classes\"))\n\n```\n:::\n\n\n[Download this code](code/constructs-sim.R) to run it in your own R session.\n\n## With real data\n\n\n\nOur table is [himmelstein-number_series-2025](https://itemresponsewarehouse.org/tables/himmelstein-number_series-2025/): nine number-series items from the Forecasting Proficiency Test, a battery built to identify people who forecast well ([Himmelstein et al., 2025](https://doi.org/10.31234/osf.io/a7kdx_v8); materials and data at [forecastingresearch/fpt](https://github.com/forecastingresearch/fpt)), which adapted the task from earlier work including [Dieckmann, Gregory, Peters & Hartman (2017)](https://doi.org/10.1111/risa.12639). Its job here is to test a construct map: does a map written from the items' text order them before we see responses? [Download the code](code/constructs-irw.R); it needs only base R.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The IRW table, from the CSV link on its landing page (pinned to one version).\nns_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_2:v22_0.himmelstein-number_series-2025/rows?format=csv\"\nns <- read.csv(ns_url)\nhead(ns[, c(\"id\", \"item\", \"resp\", \"rt\", \"wave\")])\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|id                   |item | resp| rt| wave|\n|:--------------------|:----|----:|--:|----:|\n|03spmysv917pRTSkTcj6 |NS_1 |    0| 11|    3|\n|03spmysv917pRTSkTcj6 |NS_8 |    0| 26|    3|\n|03spmysv917pRTSkTcj6 |NS_6 |    0| 31|    3|\n|03spmysv917pRTSkTcj6 |NS_9 |    0| 24|    3|\n|03spmysv917pRTSkTcj6 |NS_7 |    0| 31|    3|\n|0800TgdtDlffSfpuNw07 |NS_6 |    0| 25|    5|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The nine sequences, as shown to respondents, from the test's source code\n# (forecastingresearch/fpt, materials/js/number_series_task.js), with the answer\n# the scoring key accepts (data_cognitive_tasks/task_datasets/data_number_series.csv).\n# `level` is the construct map in the lesson, written from the text alone:\n#   1 the same step every time\n#   2 the step changes by a simple pattern (it alternates, or grows by one)\n#   3 the step changes by multiplication\n#   4 two sequences interleaved in one\n#   5 two sequences side by side, as fractions\nitems <- data.frame(\n  item   = paste0(\"NS_\", 1:9),\n  series = c(\"10, 4, __, -8, -14, -20\", \"3, 6, 10, 15, 21, __\", \"121, 100, 81, __, 49\",\n             \"3, 10, 16, 23, __, 36\", \"3/21, __, 13/11, 18/6, 23/1, 28/-4\",\n             \"200, 198, 192, 174, __\", \"3, 2, 10, 4, 19, 6, 30, 8, __\",\n             \"10000, 9000, __, 8890, 8889\", \"3/4, 4/6, 6/8, 8/12, __\"),\n  key    = c(\"-2\", \"28\", \"64\", \"29\", \"8/16\", \"165\", \"43\", \"8900\", \"12/16\"),\n  level  = c(1, 2, 2, 2, 5, 3, 4, 3, 5)\n)\nitems[, c(\"item\", \"series\", \"level\")]\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|item |series                             | level|\n|:----|:----------------------------------|-----:|\n|NS_1 |10, 4, __, -8, -14, -20            |     1|\n|NS_2 |3, 6, 10, 15, 21, __               |     2|\n|NS_3 |121, 100, 81, __, 49               |     2|\n|NS_4 |3, 10, 16, 23, __, 36              |     2|\n|NS_5 |3/21, __, 13/11, 18/6, 23/1, 28/-4 |     5|\n|NS_6 |200, 198, 192, 174, __             |     3|\n|NS_7 |3, 2, 10, 4, 19, 6, 30, 8, __      |     4|\n|NS_8 |10000, 9000, __, 8890, 8889        |     3|\n|NS_9 |3/4, 4/6, 6/8, 8/12, __            |     5|\n\n</div>\n:::\n:::\n\n\nResponses are scored 1 for correct, so higher means more of the construct. The `wave` column merits a look before we pool. Waves 3 and 5 of the seven-wave study held the cognitive tests, and each participant was randomly assigned to take this block in one of them ([Himmelstein et al., 2025, sec. 2.1](https://doi.org/10.31234/osf.io/a7kdx_v8)), so each respondent appears once and we can pool. Each item had a 30-second limit ([`number_series_task.js`](https://github.com/forecastingresearch/fpt/blob/main/materials/js/number_series_task.js)); an unanswered item is simply missing from the table.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Waves 3 and 5 were the two cognitive-test waves; each respondent took the number\n# series once, in whichever of the two waves it was randomly assigned to. Each item\n# had a 30-second limit, and an item left unanswered is simply absent from the table.\ntable(wave = tapply(ns$wave, ns$id, function(w) paste(unique(w), collapse = \"+\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwave\n  3   5 \n569 620 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nn_resp <- length(unique(ns$id))\nn_resp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1189\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(ns$resp)          # 1 = correct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1 \n4740 4359 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nanswered <- table(factor(ns$item, levels = items$item))\nanswered                # respondents who answered each item (out of n_resp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNS_1 NS_2 NS_3 NS_4 NS_5 NS_6 NS_7 NS_8 NS_9 \n1133 1154 1043 1070  855  877  816 1104 1047 \n```\n\n\n:::\n:::\n\n\nOf 1,189 respondents, 1,154 answered NS_2 but only 816 answered NS_7. The hard-looking items go unanswered most, so we compute proportions correct two ways: among those who answered, and counting unanswered as wrong. The map puts NS_6, whose steps triple (2, 6, 18), at level 3 with NS_8, whose steps shrink tenfold (1,000, 100, 10, 1).\n\n\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Which item will turn out hardest?\",\n  choices: [\"NS_6 (steps that triple)\", \"NS_7 (two sequences interleaved)\", \"NS_9 (fractions)\"],\n  answer: \"NS_6 (steps that triple)\",\n  reveal: \"NS_6, by far: 1.5% of the 877 respondents who answered it gave the keyed answer. The map puts it at level 3, and the other level-3 item, NS_8, was solved by 48%. The next section asks why.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Proportion correct among those who answered, and counting an unanswered item as\n# incorrect, next to the level the map gives each item. Spearman's correlation\n# compares the two orders: -1 would mean every higher level is harder.\nitems$answered <- as.vector(answered)\nitems$p <- as.vector(tapply(ns$resp, factor(ns$item, levels = items$item), mean))\nitems$p_all <- as.vector(tapply(ns$resp, factor(ns$item, levels = items$item), sum)) / n_resp\nmap <- items[order(items$level, -items$p), c(\"item\", \"series\", \"level\", \"answered\", \"p\", \"p_all\")]\nprint(transform(map, p = round(p, 3), p_all = round(p_all, 3)), row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n item                             series level answered     p p_all\n NS_1            10, 4, __, -8, -14, -20     1     1133 0.779 0.743\n NS_2               3, 6, 10, 15, 21, __     2     1154 0.839 0.814\n NS_4              3, 10, 16, 23, __, 36     2     1070 0.577 0.519\n NS_3               121, 100, 81, __, 49     2     1043 0.567 0.497\n NS_8        10000, 9000, __, 8890, 8889     3     1104 0.478 0.444\n NS_6             200, 198, 192, 174, __     3      877 0.015 0.011\n NS_7      3, 2, 10, 4, 19, 6, 30, 8, __     4      816 0.235 0.161\n NS_5 3/21, __, 13/11, 18/6, 23/1, 28/-4     5      855 0.371 0.267\n NS_9            3/4, 4/6, 6/8, 8/12, __     5     1047 0.239 0.210\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Three versions: all nine items; counting unanswered as wrong; leaving out NS_6.\nround(c(all_items = cor(items$level, items$p, method = \"spearman\"),\n        unanswered_wrong = cor(items$level, items$p_all, method = \"spearman\"),\n        without_NS_6 = cor(items$level[-6], items$p[-6], method = \"spearman\")), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       all_items unanswered_wrong     without_NS_6 \n           -0.76            -0.76            -0.85 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Items that share a level are spread a little sideways so their labels don't overlap.\nx <- items$level + (ave(items$p, items$level, FUN = function(v) rank(-v)) - 1) * 0.3\npar(mar = c(4.5, 4.5, 1, 1))\nplot(x, items$p, pch = 19, col = \"#2780e3\", xlim = c(0.8, 5.8), ylim = c(0, 1),\n     xlab = \"Level on the construct map\", ylab = \"Proportion correct\", xaxt = \"n\")\naxis(1, at = 1:5)\ntext(x, items$p, items$item, pos = ifelse(items$item == \"NS_3\", 1, 3), cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](constructs_files/figure-html/plot-1.png){width=576}\n:::\n:::\n\n\nThe map does fairly well: the rank correlation between level and proportion correct is −0.76 (−1 would mean every higher level is harder), unchanged when unanswered items count as wrong. Two items are out of place in the mild way a first draft should expect. NS_2 (3, 6, 10, 15, 21) is easier than the level-1 NS_1, perhaps because its step grows by exactly one each time, the gentlest change a step can make. NS_5, a fraction item at level 5, is easier than the interleaved NS_7: its numerators and denominators each change by a constant step, so it may belong lower. Without NS_6, the rank correlation is −0.85.\n\nNS_6 is out of place by a wide margin, and its text doesn't explain why: tripling steps are no harder in principle than steps that shrink tenfold. Is the map wrong about the item, or is something else going on? The IRW table keeps only the 0/1 score, so we read what respondents typed from the source data.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# What did respondents type for NS_6? The IRW table keeps only the 0/1 score, so we\n# read the answers from the source data (pinned to one commit of the FPT repository)\n# and keep the sessions that are in the IRW table.\nsrc_url <- paste0(\"https://raw.githubusercontent.com/forecastingresearch/fpt/\",\n                  \"fdbe605700cc172c03abe009bbd894a20f5cb69b/\",\n                  \"data_cognitive_tasks/task_datasets/data_number_series.csv\")\nsrc <- read.csv(src_url, colClasses = \"character\")\nns6 <- src$ns_response[src$ns_id == \"NS_6\" & src$session_id %in% ns$cov_session_id]\nns6 <- ns6[!is.na(ns6) & ns6 != \"\"]\nlength(ns6)                                # respondents who answered NS_6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 877\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nhead(sort(table(ns6), decreasing = TRUE), 5) # the most common answers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nns6\n150 120 164 160 156 \n106 101  73  64  52 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(answered_165 = sum(ns6 == \"165\"), answered_120 = sum(ns6 == \"120\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nanswered_165 answered_120 \n          13          101 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(p_as_keyed = mean(ns6 == \"165\"), p_if_120_were_keyed = mean(ns6 == \"120\")), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         p_as_keyed p_if_120_were_keyed \n              0.015               0.115 \n```\n\n\n:::\n:::\n\n\nThe scoring key accepts 165. Continuing the tripled steps (2, 6, 18, then 54) gives 174 − 54 = 120, and 101 respondents typed 120, against 13 who typed 165. I can't find the rule that leads to 165; the key may encode a pattern I haven't seen, or record a slip. Scored with 120, NS_6 would be solved by 11.5% of those who answered: still the hardest item, but at about half the rate of NS_7 and NS_9 (0.24) rather than a sixteenth. Either way, its place in the data is mostly a fact about its key, not the construct. The map is what made the item look wrong.\n\nMy working rule: when an item lands far from where the construct map puts it, I read the item and its key before I revise the map. [AI and psychometrics](ai-psychometrics.qmd) returns to these nine items as a check on its own pipeline.\n\n#### How does your map do?\n\n```{ojs}\n//| echo: false\nns_p = new Map(ns_pcorrect.item.map((d, i) => [d, ns_pcorrect.p[i]]))\nyours = ns_text.map(d => ({item: d.item, level: ns_map[d.item], mine: d.mine, p: ns_p.get(d.item)}))\nyours_no6 = yours.filter(d => d.item !== \"NS_6\")\nmd`Your map's rank correlation with the proportions correct is **${spearman(yours.map(d => d.level), yours.map(d => d.p)).toFixed(2)}**; the lesson's map gives ${spearman(yours.map(d => d.mine), yours.map(d => d.p)).toFixed(2)}. Without NS_6, yours gives ${spearman(yours_no6.map(d => d.level), yours_no6.map(d => d.p)).toFixed(2)}.`\n```\n\nThis uses your levels from *Try it: map the number-series items*. Moving NS_6 to level 5 improves the correlation, but only by fitting the map to a scoring key.\n\n## Problems\n\n1. **Two classes, one sum.** A proportion $\\pi$ of respondents are in class 1, the rest in class 2, and a respondent in class $k$ answers item $i$ correctly with probability $p_{ik}$, independently across items. Derive the item's mean and the covariance of items $i$ and $j$. Show that every covariance is positive when every item is easier in class 2. What does that imply for positive inter-item correlations as evidence of a continuum?\n2. **The out-of-place item.** Which item other than NS_6 is most out of place relative to your map? Propose a reason from its text, and say what data would test it (the `rt` column may help).\n3. **Your sentence.** Write the Cronbach–Meehl sentence for a construct you work with, for three different situations. Does your construct pass the intervention test?\n4. **Design a map.** Sketch a four-level construct map for a construct of your choice: a description at each level, what holds a respondent there, and one item per level. Ask someone to order your items before seeing your levels.\n5. **Blueprint or map?** A nursing board licenses nurses with an exam built from a blueprint; a hospital wants a scale of clinical judgment built from a construct map. For each, what can a score claim, what evidence would the claim need, and what question could it not answer?\n6. **Challenge: is antisocial behaviour a continuum?** What data would convince you that antisocial behaviour is a continuum rather than Moffitt's categories, and what would convince you it isn't? Consider predictions about change over time, not only the distribution at one age. This is open.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Constructs%20and%20construct%20maps%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20what%20a%20construct%20is%20%28Cronbach%20and%20Meehl%27s%20definition%29%2C%20Wilson%27s%20construct%20maps%2C%20two%20tests%20for%20a%20proposed%20construct%20%28does%20it%20order%20items%20before%20data%3B%20does%20it%20suggest%20an%20intervention%29%2C%20whether%20a%20construct%20is%20a%20continuum%20or%20a%20set%20of%20latent%20classes%2C%20and%20test%20blueprints%2C%20with%20nine%20number-series%20items%20from%20the%20Forecasting%20Proficiency%20Test%20as%20the%20worked%20example.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Cronbach, L. J., & Meehl, P. E. (1955). Construct validity in psychological tests. *Psychological Bulletin*, 52(4), 281–302. <https://doi.org/10.1037/h0040957>. Where the idea of a construct, and of validating one, comes from.\n- Wilson, M. (2005). *Constructing measures: An item response modeling approach*. Lawrence Erlbaum. <https://doi.org/10.4324/9781410611697>. Construct maps, and the steps from a map to items to a measurement model, at book length.\n- Briggs, D. C., Alonzo, A. C., Schwab, C., & Wilson, M. (2006). Diagnostic assessment with ordered multiple-choice items. *Educational Assessment*, 11(1), 33–63. <https://doi.org/10.1207/s15326977ea1101_2>. The astronomy construct map, and items whose answer options point to levels.\n- National Assessment Governing Board. (2001). *NAEP achievement levels 1992–1998 for geography*. <https://www.nagb.gov/content/dam/nagb/en/documents/publications/achievement/naep-geography-achievement-levels-1992-1998.pdf>. The descriptors compared with the astronomy map, with sample items at each level.\n- California Department of Social Services & California Department of Education. (2025). *DRDP (2025): An early childhood developmental continuum*. <https://www.desiredresults.us/desired-results-system/drdp-2025-instrument-and-forms>. A working instrument built as a set of construct maps.\n- Moffitt, T. E. (1993). Adolescence-limited and life-course-persistent antisocial behavior: A developmental taxonomy. *Psychological Review*, 100(4), 674–701. <https://doi.org/10.1037/0033-295X.100.4.674>. A categorical theory of an important construct, and the reasons for it.\n- Haslam, N., Holland, E., & Kuppens, P. (2012). Categories versus dimensions in personality and psychopathology: A quantitative review of taxometric research. *Psychological Medicine*, 42(5), 903–920. <https://doi.org/10.1017/S0033291711001966>. What taxometric studies have found, across 311 findings.\n- Bartholomew, D. J., Knott, M., & Moustaki, I. (2011). *Latent variable models and factor analysis: A unified approach* (3rd ed.). Wiley. <https://doi.org/10.1002/9781119970583>. Latent class and latent trait models as members of one family.\n- AERA, APA, & NCME. (2014). *Standards for educational and psychological testing*. American Educational Research Association. <https://www.testingstandards.net/open-access-files.html>. Chapter 4 covers test specifications; open access.\n\n\n::: {.cell}\n\n:::\n\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`himmelstein-number_series-2025`](https://itemresponsewarehouse.org/tables/himmelstein-number_series-2025/): Himmelstein, Mark, Sophie Ma Zhu, Nikolay Petrov, Ezra Karger, Jessica Helmer, Sivan Livnat, Amory Bennett, Page Hedley, and Phil Tetlock. “The Forecasting Proficiency Test: A General Use Assessment of Forecasting Ability”. PsyArXiv, November 23, 2025. doi:10.31234/osf.io/a7kdx_v8. <https://doi.org/10.31234/osf.io/a7kdx_v8>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 2 (slides c2, \"Constructs\" through \"A different view: Test 'blueprints'\", slides 3–17). The number-series analysis is new.\n- **Timing:** about 45 minutes for the core ideas and widgets; the real-data section works as a 20-minute lab, and problem 4 as a small-group activity.\n- **Changed from 252:** the slides show the astronomy map and the NAEP descriptors as images; here both are paraphrased (the astronomy figure is © WestEd 2002, in Briggs et al., 2006), and the DRDP example uses the current (2025) instrument. The Cronbach–Meehl definition is paraphrased except for its one key sentence. The slide's \"80s music\" example is left out. The slides list four Moffitt groups (abstainers, recoveries, life-course-persistent, adolescence-limited); here the lesson gives the two groups of Moffitt (1993) and the third found at age 26 (Moffitt et al., 2002).\n- **Held back:** writing items from a map (in [From construct map to items](instrument-building.qmd)); latent class models fit to data (in [Latent classes and cognitive diagnosis](cdm.qmd)); whether an intervention changes the construct or only some items (in [Measurement invariance under treatment and life events](invariance-experience.qmd)); the causal reading of a construct (in [Validity as causation](validity-causal.qmd)).\n- **Item text:** the nine sequences and their keys are from the test's public materials ([forecastingresearch/fpt](https://github.com/forecastingresearch/fpt): `materials/js/number_series_task.js` and `data_cognitive_tasks/task_datasets/data_number_series.csv`); the paper describing the test is CC BY 4.0.\n- **Solutions:** held back in `solutions/constructs.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "constructs_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script type=\"ojs-define\">\n{\"contents\":[{\"name\":\"ns_pcorrect\",\"value\":{\"item\":[\"NS_1\",\"NS_2\",\"NS_3\",\"NS_4\",\"NS_5\",\"NS_6\",\"NS_7\",\"NS_8\",\"NS_9\"],\"p\":[0.7793,0.8388,0.5666,0.5766,0.3708,0.0148,0.2353,0.4783,0.2388]}}]}\n</script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}