{
  "hash": "4c1ff6069071d6f874ff1b2ad62d0165",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Response time and the speed-accuracy tradeoff\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Beyond the standard models  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [What is an item? Explanatory item response models](explanatory-irt.qmd)  \n**Builds toward:** [Process models for response time: drift diffusion and race models](rt-process-models.qmd)  \n**IRW tables:** [`credentialform_lnirt`](https://itemresponsewarehouse.org/tables/credentialform_lnirt/), [`roar_lexical`](https://itemresponsewarehouse.org/tables/roar_lexical/), [`rapm_poulton_2022_timed`](https://itemresponsewarehouse.org/tables/rapm_poulton_2022_timed/), [`rapm_poulton_2022_untimed`](https://itemresponsewarehouse.org/tables/rapm_poulton_2022_untimed/)  \n**From EDUC 252:** slides c9; problem sets PS9#1; code [`ps9/sat.R`](https://github.com/ben-domingue/252/blob/main/ps9/sat.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\nwebr::install(\"lme4\", quiet = TRUE)\nsuppressPackageStartupMessages(library(lme4))\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {palette} from \"./widgets/irt.js\"\nimport {timeSample, betweenWithin, cafWorld, acceleration} from \"./widgets/response-time.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nA test given on a screen records two things for every response: whether it was right, and how long it took. What should we do with the second? One answer is a model in which each respondent has an ability and a speed, each item a difficulty and a time intensity, joined by correlations. It rests on two assumptions: each respondent works at one speed throughout, and once ability and speed are known, a response's time says nothing more about whether it was right. This lesson fits log time with the crossed random effects of [Explanatory item response models](explanatory-irt.qmd), separates what happens across people from what happens within a person, and asks four IRW tables whether the assumptions hold. They give different answers, and that is the lesson.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- fit the lognormal model for response times as a crossed random-effects model with `lmer()`, and read its variance components;\n- write down the hierarchical model for speed and accuracy and state its two central assumptions;\n- explain why the speed–accuracy tradeoff is a claim about a person that the correlation of speed and ability across people can't test;\n- compute a conditional accuracy function from residual log time and say what it would look like under conditional independence;\n- decide when a response-time model answers the question you have.\n\n## Core ideas\n\n### Response time is data, and it is skewed\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Explanatory item response models](explanatory-irt.qmd): `glmer(resp ~ 1 + (1 | id) + (1 | item))` is the Rasch model with respondents and items as crossed random effects.\n:::\n\nTimes are positive, and a few are very long (someone rereads a passage, or looks away), so their distribution has a long right tail, which taking logs removes (see the widget). The **lognormal model** ([van der Linden, 2006](https://doi.org/10.3102/10769986031002181)) writes\n$$\\log t_{ij} = \\beta_i - \\tau_j + \\varepsilon_{ij}, \\qquad \\varepsilon_{ij} \\sim N(0, \\sigma^2),$$\nwhere $\\beta_i$ is item $i$'s **time intensity** (how long it takes, in log seconds) and $\\tau_j$ is respondent $j$'s **speed**. (In [Explanatory item response models](explanatory-irt.qmd) $\\beta_i$ was an easiness; we keep van der Linden's notation, and accuracy keeps $b_i$.) Van der Linden gives each item its own residual SD, but reports that making them equal cost little fit, so we use one $\\sigma$. With items and respondents random, this is a linear mixed model, one line in `lme4` ([Bates, Mächler, Bolker & Walker, 2015](https://doi.org/10.18637/jss.v067.i01)):\n\n```r\nlmer(log(rt) ~ 1 + (1 | id) + (1 | item), data = long_table)\n```\n\nThe model is additive in log time, so it is multiplicative in seconds: a respondent whose $\\tau$ is 0.2 higher than another's takes $e^{-0.2} \\approx 0.82$ times as long on every item.\n\n#### Try it: raw and log time\n\nTimes for one item from the lognormal model, with defaults close to the licensure exam below.\n\n```{ojs}\n//| echo: false\nviewof ts_med = Inputs.range([1, 120], {value: 54, step: 1, label: \"Typical time on the item (s)\"})\nviewof ts_tau = Inputs.range([0, 0.6], {value: 0.17, step: 0.01, label: \"SD of speed across respondents\"})\nviewof ts_sig = Inputs.range([0.1, 1.2], {value: 0.5, step: 0.05, label: \"Residual SD of log time (σ)\"})\n```\n\n```{ojs}\n//| echo: false\nts = timeSample(Math.log(ts_med), ts_tau, ts_sig)\nhtml`<div style=\"display:flex;flex-wrap:wrap;gap:1rem\">${\n  Plot.plot({width: 340, height: 220, x: {label: \"Seconds\"}, y: {label: \"Responses\"},\n    marks: [Plot.rectY(ts.rows.filter(d => d.t < ts.p99 * 1.5), Plot.binX({y: \"count\"}, {x: \"t\", thresholds: 40, fill: palette.light})),\n            Plot.ruleX([ts.median], {stroke: palette.main, strokeWidth: 2}),\n            Plot.ruleX([ts.mean], {stroke: palette.contrast, strokeWidth: 2, strokeDasharray: \"4 3\"})]})\n}${\n  Plot.plot({width: 340, height: 220, x: {label: \"log seconds\"}, y: {label: \"Responses\"},\n    marks: [Plot.rectY(ts.rows, Plot.binX({y: \"count\"}, {x: \"lt\", thresholds: 40, fill: palette.main}))]})\n}</div>`\n```\n\n```{ojs}\n//| echo: false\nmd`Median **${ts.median.toFixed(1)} s** (solid line), mean **${ts.mean.toFixed(1)} s** (dashed); 1% of responses take longer than ${ts.p99.toFixed(0)} s.`\n```\n\nThe seconds have a long tail; the log times don't. Raise σ and the mean pulls away from the median, which stays put: the gap is the tail (problem 1).\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Under the lognormal model, respondent A's speed $\\\\tau$ is 0.2 above respondent B's. What does the model say about their times?\",\n  options: [\n    {text: \"A takes about 18% less time than B on every item\", correct: true, why: \"Log time is 0.2 lower on every item, so time is multiplied by $e^{-0.2} \\\\approx 0.82$ whatever the item's time intensity.\"},\n    {text: \"A is 0.2 seconds faster on every item\", correct: false, why: \"The model is additive in log time, so a difference in speed is a ratio of times, not a difference in seconds. On a 60-second item 18% is about 11 seconds.\"},\n    {text: \"A is faster on long items and slower on short ones\", correct: false, why: \"There is no respondent × item term in the model: the same ratio applies to every item. A model that allowed this would need one.\"}\n  ]\n})\n```\n\n### The hierarchical model, and what it assumes\n\nNow join the halves. Accuracy gets an item response model, here the Rasch model,\n$$\\text{logit}\\Pr(x_{ij} = 1) = \\theta_j - b_i,$$\nand time gets the lognormal model. At a second level, each respondent's $(\\theta_j, \\tau_j)$ is drawn from a bivariate normal distribution with correlation $\\rho$, and each item's $(b_i, \\beta_i)$ from another. This is the **hierarchical model** for speed and accuracy ([van der Linden, 2007](https://doi.org/10.1007/s11336-006-1478-z); [Klein Entink, Fox & van der Linden, 2009](https://doi.org/10.1007/s11336-008-9075-y)), which the R package `LNIRT` fits jointly ([Fox, Klotzke & Simsek, 2023](https://doi.org/10.7717/peerj-cs.1232)).\n\nWhat does it buy? Estimates of $\\rho$ (are abler respondents faster?) and of how difficulty and time intensity go together; and, through $\\rho$, times that sharpen the estimate of $\\theta$. Both rest on two assumptions, which we take as questions for the data:\n\n1. **One speed per respondent.** $\\tau_j$ has no item subscript: respondent $j$ works at the same speed on the first item and the last.\n2. **Conditional independence.** Given $\\theta_j$, $\\tau_j$ and the item parameters, $x_{ij}$ and $t_{ij}$ are independent. A response slower than expected is no more and no less likely to be right.\n\n[Bolsinova, De Boeck and Tijmstra (2017)](https://doi.org/10.1007/s11336-016-9537-6) relax the second: on a low-stakes test, slow responses were more often right on hard items and less often on easy ones. Below, we fit the halves separately with `lme4` and correlate their estimates: a rough version of the joint model, but one that makes each assumption visible.\n\n### The speed–accuracy tradeoff is a claim about a person\n\nPush people to go faster and they make more errors: the **speed–accuracy tradeoff** (SAT), seen in insects, rodents and primates ([Heitz, 2014](https://doi.org/10.3389/fnins.2014.00150)). But it describes what happens *within* a person when their speed changes. Whether faster *people* are more accurate is $\\rho$, and the link between time and success can take either sign: [Goldhammer et al. (2014)](https://doi.org/10.1037/a0034716) found more time on task going with success on an adult skills survey's problem-solving tasks, and with failure on its reading tasks.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Item response data and the IRW](irw-data.qmd): in the brightness experiment of `rr98_accuracy`, errors were slower than correct responses (median 0.65 s against 0.56 s), but within a brightness level by only about 0.02 s, because errors crowd into the hard levels, which are slow for every response.\n:::\n\nThe pooled comparison mixed a difference *between items* (hard conditions are slow and error-prone) with one *within* them. In the hierarchical model the item-level part is the correlation of $b$ and $\\beta$, and the person-level part is $\\rho$. Neither is the tradeoff.\n\n#### Try it: between people and within them\n\nEach line is one respondent: how their chance of success changes when a response takes longer than usual. The dots are their averages over 30 items.\n\n```{ojs}\n//| echo: false\nviewof bw_rho = Inputs.range([-0.9, 0.9], {value: 0.3, step: 0.05, label: \"Correlation of ability and speed (ρ)\"})\nviewof bw_delta = Inputs.range([-2, 2], {value: 1, step: 0.1, label: \"Within-person effect of taking longer (logits per SD)\"})\n```\n\n```{ojs}\n//| echo: false\nbw = betweenWithin(bw_rho, bw_delta)\nPlot.plot({\n  width: 700, height: 320, x: {label: \"Log seconds\"}, y: {label: \"P(correct)\", domain: [0, 1]},\n  marks: [\n    Plot.line(bw.lines, {x: \"lt\", y: \"p\", z: \"id\", stroke: palette.light, strokeWidth: 1.5}),\n    Plot.dot(bw.people, {x: \"lt\", y: \"p\", fill: palette.main, r: 3.5})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Across 400 simulated respondents, average log time and proportion correct correlate **${bw.rBetween.toFixed(2)}**. Within each respondent, taking one SD longer than usual changes the log odds by **${bw_delta.toFixed(1)}**.`\n```\n\nWith the defaults, abler respondents are faster, so the dots slope down; yet every line slopes up, because each respondent does better when they slow down. Set ρ to −0.4 and the effect to −1 and both signs flip. The dots can't tell you the slope of the lines.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In a class, students who finish a quiz faster tend to score higher. A teacher concludes that urging everyone to hurry would raise scores. What is the problem?\",\n  options: [\n    {text: \"The pattern is between students; hurrying changes each student's own speed, a within-person question the pattern doesn't answer\", correct: true, why: \"Faster students may simply know more. For a given student, the speed–accuracy tradeoff predicts that hurrying *lowers* accuracy.\"},\n    {text: \"The class is too small to see a correlation\", correct: false, why: \"Size isn't the issue: even in a very large class, a correlation across students says nothing about what one student does when made to go faster.\"},\n    {text: \"Scores and times should be log-transformed first\", correct: false, why: \"A transformation changes the scale, not the level of the comparison. The pattern would still be between students.\"}\n  ]\n})\n```\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: what the pooled slope estimates under the hierarchical model\n\n**Assumptions:** the hierarchical model with conditional independence: $\\text{logit}\\Pr(x_{ij} = 1) = \\theta_j - b_i$ and $\\log t_{ij} = \\beta_i - \\tau_j + \\varepsilon_{ij}$, with $\\varepsilon_{ij} \\sim N(0, \\sigma^2)$ independent of everything else; $(\\theta_j, \\tau_j)$ bivariate normal with correlation $\\rho$ and SDs $\\sigma_\\theta, \\sigma_\\tau$; $(b_i, \\beta_i)$ bivariate normal with correlation $\\rho_I$ and SDs $\\sigma_b, \\sigma_\\beta$; persons and items independent.\n\nCondition on respondent $j$ and item $i$. Then $\\log t_{ij}$ varies only through $\\varepsilon_{ij}$, and $\\Pr(x_{ij} = 1 \\mid \\varepsilon_{ij}, j, i) = \\text{logistic}(\\theta_j - b_i)$ doesn't involve $\\varepsilon_{ij}$. So a regression of $x$ on the residual $\\varepsilon$ with person and item effects has slope zero. The within-person slope is identified, and conditional independence says it is 0.\n\nNow pool. Across all responses, log time and the logit of accuracy covary through the random effects:\n$$\\text{Cov}(\\log t_{ij},\\ \\theta_j - b_i) = \\text{Cov}(-\\tau_j, \\theta_j) + \\text{Cov}(\\beta_i, -b_i) = -\\rho\\,\\sigma_\\tau\\sigma_\\theta - \\rho_I\\,\\sigma_\\beta\\sigma_b.$$\nA pooled regression of accuracy on log time therefore has a slope whose sign depends on $\\rho$ and $\\rho_I$, even though no one's accuracy depends on their time. With $\\rho > 0$ (abler respondents faster) and $\\rho_I > 0$ (harder items slower), both terms are negative and slow responses look less accurate; with $\\rho < 0$ the two terms pull in opposite directions. The Simulate section shows a pooled slope of −0.55 when the within-person slope is zero.\n\nWhat $\\rho$ is not: the effect of speed on accuracy. It describes a population of respondents. A within-person tradeoff concerns one respondent at two speeds, which experiments produce by instruction or deadline ([Heitz, 2014](https://doi.org/10.3389/fnins.2014.00150)). Neither quantity constrains the other, as the widget shows.\n:::\n\n### Does conditional independence hold? The conditional accuracy function\n\nTo see the within-person relation, keep the lognormal model's residual, $\\hat\\varepsilon_{ij} = \\log t_{ij} - \\hat\\beta_i + \\hat\\tau_j$: how much slower (positive) or faster (negative) than expected this respondent was on this item. Plot accuracy against it, by deciles. This is a **conditional accuracy function** ([Heitz, 2014](https://doi.org/10.3389/fnins.2014.00150)). Under conditional independence it is flat. [Domingue et al. (2022)](https://doi.org/10.3102/10769986221099906) asked the question of 29 datasets from cognitive tasks and found no single shape: a respondent's marginal increases in time went with higher accuracy in some and lower in others. They also found time a weak predictor of accuracy.\n\n#### Try it: shapes of the conditional accuracy function\n\nSimulated data (300 respondents, 20 items) in which residual log time changes the log odds of a correct response, in the shape you choose.\n\n```{ojs}\n//| echo: false\nviewof cf_shape = Inputs.radio([\"none\", \"rising\", \"falling\", \"inverted U\"], {value: \"inverted U\", label: \"Shape\"})\nviewof cf_s = Inputs.range([0, 1.5], {value: 0.5, step: 0.05, label: \"Strength (logits)\"})\n```\n\n```{ojs}\n//| echo: false\ncw = cafWorld(cf_shape, cf_s)\nPlot.plot({\n  width: 700, height: 280, x: {label: \"Decile of residual log time (1 = much faster than expected)\", ticks: 10}, y: {label: \"Proportion correct\", domain: [0.2, 0.8]},\n  marks: [Plot.ruleY([cw.overall], {stroke: palette.guide, strokeDasharray: \"4 3\"}),\n          Plot.line(cw.deciles, {x: \"decile\", y: \"p\", stroke: palette.main, strokeWidth: 2.5}),\n          Plot.dot(cw.deciles, {x: \"decile\", y: \"p\", fill: palette.main, r: 4})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`A straight-line logistic regression of the response on residual log time gives a slope of **${cw.slope.toFixed(2)}**.`\n```\n\nWith \"none\", the curve wobbles around the dashed line: the sampling noise of 600 responses per decile. With \"inverted U\", responses near the expected time do best, and the linear slope is close to zero. A single slope summarises a curve that only rises or only falls; it can report no relation when there plainly is one.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"The widget's inverted U gives a linear slope near 0. Does conditional independence hold in those data?\",\n  options: [\n    {text: \"No: accuracy depends on residual time, just not linearly\", correct: true, why: \"Conditional independence says the curve is flat everywhere. A curve that rises and falls violates it, and a straight line through it averages the two halves to about zero.\"},\n    {text: \"Yes: the slope is zero\", correct: false, why: \"A flat curve gives a zero *linear* slope, but so does a symmetric one. Look at the deciles, not only at the slope.\"},\n    {text: \"We can't tell without the person parameters\", correct: false, why: \"The residual already removes each respondent's speed and each item's time intensity; the pattern across deciles is the evidence.\"}\n  ]\n})\n```\n\n### Is speed constant?\n\nChecking the first assumption needs the order in which items were given. [Domingue, Kanopka, Stenhaug, Soland, Kuhfeld, Wise and Piech (2021)](https://doi.org/10.1111/jedm.12291) had it for an adaptive reading test and found **response acceleration**: a response ten positions later took about 88% as long, and one thirty positions later about $0.88^3 \\approx 68\\%$ as long. Respondents with lower ability estimates accelerated more, and for them faster responses were less accurate than expected. Very fast responses at chance are the extreme case, **rapid guesses** ([Wise & Kong, 2005](https://doi.org/10.1207/s15324818ame1802_2)).\n\n#### Try it: response acceleration\n\nA respondent speeds up over 40 items of equal time intensity.\n\n```{ojs}\n//| echo: false\nviewof ac_ratio = Inputs.range([0.7, 1], {value: 0.88, step: 0.01, label: \"Time ratio per 10 positions\"})\n```\n\n```{ojs}\n//| echo: false\nac = acceleration(ac_ratio)\nPlot.plot({\n  width: 700, height: 260, x: {label: \"Position in the test\"}, y: {label: \"Seconds\", domain: [0, 65]},\n  marks: [Plot.ruleY([ac.level], {stroke: palette.guide, strokeDasharray: \"4 3\"}),\n          Plot.line(ac.rows, {x: \"position\", y: \"t\", stroke: palette.main, strokeWidth: 2.5})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`A response 30 positions later takes **${(100 * ac.after30).toFixed(0)}%** as long. A model with one speed fits the dashed line (${ac.level.toFixed(1)} s), so its residual log time runs from **${ac.first.toFixed(2)}** at the first item to **${ac.last.toFixed(2)}** at the last.`\n```\n\nWith one speed per respondent, the change lands in the residuals: early responses look slow, late ones fast. If accuracy also changes over the test, the conditional accuracy function picks that up, and the two assumptions fail together.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Guessing and priors](guessing-priors.qmd): in `roar_lexical`, 3.1% of responses came in under 0.3 seconds, at an accuracy of 0.51 on a task where chance is 0.5, and a handful of respondents gave most of them.\n:::\n\n## Simulate\n\nThe code generates 200 respondents × 20 items from the hierarchical model with $\\rho = 0.4$ and conditional independence (`delta <- 0`), and fits log time with `lmer()` and accuracy with `glmer()`. The first run takes 30 to 45 seconds, most of it loading `lme4`.\n\nWith the seed as written, the estimated abilities and speeds correlate 0.38 (truth 0.40). The pooled slope of accuracy on log time is −0.55, yet the within-person slope is −0.09 (SE 0.07) and the deciles are flat: the pooled slope is all between people and items. Set `delta <- -1` and the within-person slope comes back at −1.01, with deciles falling from 0.71 to 0.36. Set `rho <- -0.4` with `delta <- 0`: the pooled slope shrinks to −0.16, as able-and-slow respondents offset hard-and-slow items, and the within-person slope stays near zero.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-19\n# Simulate responses and response times from the hierarchical model: a Rasch model\n# for accuracy, the lognormal model for time, correlated person parameters (theta,\n# speed) and correlated item parameters (difficulty, time intensity). Then fit the\n# two halves with lme4 and ask what the data say about speed and accuracy.\n#\n# delta is a within-person speed-accuracy tradeoff: the change in the log odds of a\n# correct response when a response takes one unit of log time longer than expected.\n# The hierarchical model has delta = 0 (conditional independence).\n#\n# nAGQ = 0 makes glmer() skip its slowest step, so the fits take seconds in the\n# browser. In your own R session, delete \", nAGQ = 0\" and raise np and ni.\nlibrary(lme4)\nset.seed(53)\nnp <- 200      # respondents\nni <- 20       # items\nrho <- 0.4     # correlation of theta and speed across respondents\ndelta <- 0     # within-person effect of taking longer than expected (log odds)\n\n# Person parameters: theta (SD 1) and speed tau (SD 0.3), correlated rho.\nz1 <- rnorm(np); z2 <- rnorm(np)\ntheta <- z1\ntau <- 0.3 * (rho * z1 + sqrt(1 - rho^2) * z2)\n# Item parameters: difficulty b and time intensity beta (log seconds), correlated 0.5.\nw1 <- rnorm(ni); w2 <- rnorm(ni)\nb <- w1\nbeta <- log(30) + 0.3 * (0.5 * w1 + sqrt(1 - 0.5^2) * w2)\n\nd <- expand.grid(id = factor(1:np), item = factor(1:ni))\ne <- rnorm(nrow(d), 0, 0.5)                          # residual log time\nd$lrt <- beta[d$item] - tau[d$id] + e\nd$resp <- rbinom(nrow(d), 1, plogis(theta[d$id] - b[d$item] + delta * e))\n\nm_time <- lmer(lrt ~ 1 + (1 | id) + (1 | item), d)\nm_acc <- glmer(resp ~ 1 + (1 | id) + (1 | item), d, binomial, nAGQ = 0)\ntau_hat <- -ranef(m_time)$id[, 1]\ntheta_hat <- ranef(m_acc)$id[, 1]\ncat(sprintf(\"Correlation of theta and speed: true %.2f, estimates %.2f\\n\",\n            rho, cor(theta_hat, tau_hat)))\ncat(sprintf(\"Correlation of b and time intensity: in these items %.2f, estimates %.2f\\n\",\n            cor(b, beta), cor(-ranef(m_acc)$item[, 1], ranef(m_time)$item[, 1])))\n\n# Pooled: accuracy on raw log time, ignoring who and what.\npooled <- glm(resp ~ lrt, binomial, d)\n# Within: accuracy on residual log time, with person and item effects.\nd$res <- residuals(m_time)\nwithin <- glmer(resp ~ res + (1 | id) + (1 | item), d, binomial, nAGQ = 0)\ncat(sprintf(\"Pooled slope on log time: %.2f\\n\", coef(pooled)[\"lrt\"]))\ncat(sprintf(\"Within-person slope on residual log time: %.2f (SE %.2f); true delta %.2f\\n\",\n            fixef(within)[\"res\"], sqrt(vcov(within)[2, 2]), delta))\nd$decile <- cut(d$res, quantile(d$res, 0:10 / 10), include.lowest = TRUE, labels = FALSE)\ncat(\"Proportion correct by decile of residual log time:\\n\")\nprint(round(tapply(d$resp, d$decile, mean), 2))\n\n```\n:::\n\n\n[Download this code](code/response-time-sim.R) to run it as large as you like in your own R session.\n\n## With real data\n\n\n\n[credentialform_lnirt](https://itemresponsewarehouse.org/tables/credentialform_lnirt/) is the main example: a long, high-stakes test. [roar_lexical](https://itemresponsewarehouse.org/tables/roar_lexical/) is the contrast: a task answered in under a second, reused from [Guessing and priors](guessing-priors.qmd) for its rapid responses. [rapm_poulton_2022_timed](https://itemresponsewarehouse.org/tables/rapm_poulton_2022_timed/) and [rapm_poulton_2022_untimed](https://itemresponsewarehouse.org/tables/rapm_poulton_2022_untimed/) do one job together: the same 12 items with and without a clock, the nearest these tables come to forcing speed. [Download the code](code/response-time-irw.R); it needs `lme4`.\n\n### A licensure exam\n\nOne form of a credentialing exam, a dataset with suspected cheating from the [*Handbook of quantitative methods for detecting cheating on tests*](https://doi.org/10.4324/9781315743097) (Cizek & Wollack, 2016) and distributed with [`LNIRT`](https://cran.r-project.org/web/packages/LNIRT/index.html). Keying: 1 is a correct answer.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(lme4)\noptions(digits = 7)  # R's default, in case a .Rprofile changes it\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.credentialform_lnirt/rows?format=csv\"\ncf <- read.csv(url)\n# One row per response; resp is 1 for a correct answer, rt the time on the item in\n# whole seconds. Items iraw.1-170 are the scored items, which everyone answered.\n# iraw.171-200 hold pilot items, and which pilot items sit under a name depends on\n# the respondent's pilot set (Pretest), so we keep the scored items only.\ncf$inum <- as.integer(sub(\"iraw.\", \"\", cf$item))\ncf <- cf[cf$inum <= 170, ]\nc(respondents = length(unique(cf$id)), items = length(unique(cf$item)),\n  missing = sum(is.na(cf$resp)), time_zero = sum(cf$rt == 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents       items     missing   time_zero \n       1636         170           0         105 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# A time of 0 means under a second; log(0) is undefined, so those rows are set aside.\ncf <- cf[cf$rt > 0, ]\ncf$lrt <- log(cf$rt)\nround(c(accuracy = mean(cf$resp), median_s = median(cf$rt), mean_s = mean(cf$rt),\n        max_s = max(cf$rt)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\naccuracy median_s   mean_s    max_s \n    0.73    54.00    63.83  1216.00 \n```\n\n\n:::\n:::\n\n\nA gentle note on processing: items 171 to 200 are pilot items, and which one sits under each name depends on the respondent's pilot set ([processing script](https://github.com/ben-domingue/irw/blob/main/data/lnirt.R)), so we keep the 170 scored items. Times are whole seconds; 105 zeros are set aside. The median is 54 s, the mean 64 s, the longest 1,216 s:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nop <- par(mfrow = c(1, 2), mar = c(4, 4, 1, 1))\nhist(cf$rt, breaks = 100, col = \"#93c5fd\", border = NA, main = \"\",\n     xlab = \"Seconds on an item\", xlim = c(0, 400))\nhist(cf$lrt, breaks = 60, col = \"#2780e3\", border = NA, main = \"\",\n     xlab = \"log seconds\")\n```\n\n::: {.cell-output-display}\n![](response-time_files/figure-html/hist-cf-1.png){width=672}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npar(op)\n```\n:::\n\n\nOn the log scale the tail is gone. The lognormal model:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The lognormal model with crossed random effects: log t = beta_i - tau_j + e.\n# lme4 writes it as an intercept plus an item effect (time intensity) and a\n# respondent effect (minus speed).\nm_time <- lmer(lrt ~ 1 + (1 | id) + (1 | item), cf)\nvc <- as.data.frame(VarCorr(m_time))\ndata.frame(component = vc$grp, variance = round(vc$vcov, 3),\n           share = round(vc$vcov / sum(vc$vcov), 2))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|component | variance| share|\n|:---------|--------:|-----:|\n|id        |    0.029|  0.07|\n|item      |    0.109|  0.28|\n|Residual  |    0.255|  0.65|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(exp(fixef(m_time)), 1)   # the typical time on a typical item, in seconds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n       52.8 \n```\n\n\n:::\n:::\n\n\nMost of the variation in log time (65%) is residual; items account for 28%, respondents for 7%. Now accuracy, and the correlations of the two models' estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The Rasch model as a GLMM with random items (explanatory-irt). nAGQ = 0 skips\n# glmer's slowest step; the estimates barely move.\nm_acc <- glmer(resp ~ 1 + (1 | id) + (1 | item), cf, binomial, nAGQ = 0)\n# Person and item estimates from the two models. Speed is minus the respondent effect\n# on log time; difficulty b is minus the item effect on the logit.\nperson_item <- function(m_time, m_acc) {\n  tau <- setNames(-ranef(m_time)$id[, 1], rownames(ranef(m_time)$id))\n  theta <- setNames(ranef(m_acc)$id[, 1], rownames(ranef(m_acc)$id))\n  beta <- setNames(ranef(m_time)$item[, 1], rownames(ranef(m_time)$item))\n  b <- setNames(-ranef(m_acc)$item[, 1], rownames(ranef(m_acc)$item))\n  list(tau = tau[names(theta)], theta = theta, beta = beta[names(b)], b = b)\n}\npi_cf <- person_item(m_time, m_acc)\nround(c(r_theta_speed = cor(pi_cf$theta, pi_cf$tau), r_b_beta = cor(pi_cf$b, pi_cf$beta)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr_theta_speed      r_b_beta \n         0.30          0.48 \n```\n\n\n:::\n:::\n\n\nAbler respondents are faster ($r = 0.30$), and harder items take longer ($r = 0.48$): rough versions of $\\rho$ and its item-level counterpart.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd) (problem 2): an observed correlation is the correlation of true scores times the square root of the two reliabilities ([Spearman, 1904](https://doi.org/10.2307/1412159)). Estimated abilities and speeds have errors too, so their correlation understates $\\rho$, most with few items; a joint fit estimates $\\rho$ directly.\n:::\n\nIs conditional independence plausible here?\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"On this exam, when a respondent takes longer than expected on an item (given their speed and the item's time intensity), are they more or less likely to get it right?\",\n  choices: [\"More likely\", \"No difference\", \"Less likely\"],\n  answer: \"Less likely\",\n  reveal: \"Less likely, and by a lot: 0.83 correct in the decile of responses that were fastest relative to expectation, 0.56 in the slowest, a slope of −1.0 logits per unit of residual log time. Conditional independence would put every decile near the overall accuracy of 0.73.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The conditional accuracy function. The residual of the time model is how much\n# slower (positive) or faster (negative) than expected a response was, for this\n# respondent on this item. Under conditional independence, accuracy doesn't depend on it.\ncaf <- function(d, m_time) {\n  d$res <- residuals(m_time)\n  d$decile <- cut(d$res, quantile(d$res, 0:10 / 10), include.lowest = TRUE, labels = FALSE)\n  m <- glmer(resp ~ res + (1 | id) + (1 | item), d, binomial, nAGQ = 0)\n  list(by_decile = round(tapply(d$resp, d$decile, mean), 2),\n       slope = round(unname(fixef(m)[\"res\"]), 2), se = round(sqrt(diag(vcov(m)))[2], 2))\n}\ncaf_cf <- caf(cf, m_time)\ncaf_cf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$by_decile\n   1    2    3    4    5    6    7    8    9   10 \n0.83 0.82 0.80 0.78 0.76 0.73 0.70 0.66 0.61 0.56 \n\n$slope\n[1] -1.03\n\n$se\n res \n0.01 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nplot(1:10, caf_cf$by_decile, type = \"b\", pch = 19, col = \"#2780e3\", ylim = c(0.5, 0.9),\n     xlab = \"Decile of residual log time (1 = much faster than expected)\",\n     ylab = \"Proportion correct\")\nabline(h = mean(cf$resp), lty = 2, col = \"#999\")\n```\n\n::: {.cell-output-display}\n![](response-time_files/figure-html/caf-cf-1.png){width=576}\n:::\n:::\n\n\nThe curve falls through every decile, from 0.83 to 0.56, and the slope with person and item effects is −1.0. A slow response signals difficulty that neither $b$ nor $\\theta$ captures. And the first assumption? The table doesn't record item order, so we can't look for acceleration, but we can ask whether a respondent's speed is the same on two halves of the items.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# One speed per respondent? Give each respondent a speed on items 1-85 and another\n# on items 86-170, and let the model estimate their correlation.\ncf$half <- factor(ifelse(cf$inum <= 85, \"items 1-85\", \"items 86-170\"))\nm_half <- lmer(lrt ~ half + (0 + half | id) + (1 | item), cf)\nround(attr(VarCorr(m_half)$id, \"correlation\")[1, 2], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\nIt is: the two speeds correlate at 1 (to two decimals). Whether one speed holds across time, these data can't say.\n\n### Lexical decision\n\nIn the ROAR lexical decision task ([Yeatman et al., 2021](https://doi.org/10.1038/s41598-021-85907-x)), children and adolescents judged whether a string of letters was a real word. Keying: 1 is a correct classification.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.roar_lexical/rows?format=csv\"\nroar <- read.csv(url)\n# One response per respondent per item; resp is 1 for a correct classification of\n# the string (real word or made-up word); rt in seconds. No waves.\nroar$lrt <- log(roar$rt)\nround(c(respondents = length(unique(roar$id)), items = length(unique(roar$item)),\n        accuracy = mean(roar$resp), median_s = median(roar$rt),\n        share_under_0.3s = mean(roar$rt < 0.3),\n        accuracy_under_0.3s = mean(roar$resp[roar$rt < 0.3])), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        respondents               items            accuracy            median_s \n            123.000             500.000               0.797               0.851 \n   share_under_0.3s accuracy_under_0.3s \n              0.031               0.508 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nt_roar <- lmer(lrt ~ 1 + (1 | id) + (1 | item), roar)\na_roar <- glmer(resp ~ 1 + (1 | id) + (1 | item), roar, binomial, nAGQ = 0)\npi_roar <- person_item(t_roar, a_roar)\nround(c(r_theta_speed = cor(pi_roar$theta, pi_roar$tau), r_b_beta = cor(pi_roar$b, pi_roar$beta)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr_theta_speed      r_b_beta \n        -0.09          0.63 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncaf_roar <- caf(roar, t_roar)\ncaf_roar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$by_decile\n   1    2    3    4    5    6    7    8    9   10 \n0.63 0.77 0.83 0.85 0.86 0.86 0.85 0.82 0.78 0.70 \n\n$slope\n[1] 0.09\n\n$se\n res \n0.02 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# One speed for real words and made-up words?\nm_kind <- lmer(lrt ~ realpseudo + (0 + realpseudo | id) + (1 | item), roar)\nround(attr(VarCorr(m_kind)$id, \"correlation\")[1, 2], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.98\n```\n\n\n:::\n:::\n\n\nThe median response takes 0.85 s, and the picture changes. Speed and ability are nearly unrelated ($r = -0.09$), though harder strings again take longer ($r = 0.63$). The conditional accuracy function is an inverted U: 0.63 in the fastest decile, 0.86 in the middle, 0.70 in the slowest. Its fast end holds the rapid responses. The linear slope, 0.09, is as uninformative as the widget's. One speed per respondent looks reasonable across kinds of string: speeds on real and made-up words correlate 0.98.\n\n### Raven's matrices, with and without a clock\n\n[Poulton et al. (2022)](https://doi.org/10.1080/13803395.2022.2080185) gave a 12-item online form of Raven's Advanced Progressive Matrices untimed in one study and with 60 seconds per item in another. Keying: 1 is correct. We use the first administration (a retest is stored as wave 2). The studies drew different samples, the timed one younger, so this compares groups, not a within-person experiment.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Two studies (Poulton et al., 2022), each with a retest (wave 2) for some\n# respondents. We keep the first administration. rt is in seconds; the timed version\n# stopped each item at 60 s.\nget_raven <- function(table) {\n  url <- sprintf(\"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_2:v24_0.%s/rows?format=csv\", table)\n  d <- read.csv(url)\n  d <- d[d$wave == 1 & !is.na(d$resp), ]\n  d$item <- factor(d$item, levels = paste0(\"RAPM_\", 1:12))\n  d\n}\ntimed <- get_raven(\"rapm_poulton_2022_timed\")\nuntimed <- get_raven(\"rapm_poulton_2022_untimed\")\nrbind(timed = c(respondents = length(unique(timed$id)), accuracy = round(mean(timed$resp), 2),\n                median_s = median(timed$rt, na.rm = TRUE), time_missing = sum(is.na(timed$rt))),\n      untimed = c(length(unique(untimed$id)), round(mean(untimed$resp), 2),\n                  median(untimed$rt, na.rm = TRUE), sum(is.na(untimed$rt))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        respondents accuracy median_s time_missing\ntimed           479     0.55   35.915            0\nuntimed         608     0.65   46.910          492\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# How often did the clock run out, and how accurate were those responses?\nat_limit <- timed$rt >= 59.9\nround(c(share_at_limit = mean(at_limit), accuracy_at_limit = mean(timed$resp[at_limit]),\n        untimed_share_over_60s = mean(untimed$rt > 60, na.rm = TRUE)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        share_at_limit      accuracy_at_limit untimed_share_over_60s \n                  0.11                   0.29                   0.36 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Accuracy item by item: which items lose most under the clock?\nround(rbind(untimed = tapply(untimed$resp, untimed$item, mean),\n            timed = tapply(timed$resp, timed$item, mean)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        RAPM_1 RAPM_2 RAPM_3 RAPM_4 RAPM_5 RAPM_6 RAPM_7 RAPM_8 RAPM_9 RAPM_10\nuntimed   0.83   0.81    0.9   0.82   0.82   0.68   0.59   0.52   0.50    0.45\ntimed     0.71   0.75    0.8   0.70   0.74   0.65   0.41   0.51   0.41    0.25\n        RAPM_11 RAPM_12\nuntimed    0.47    0.38\ntimed      0.28    0.33\n```\n\n\n:::\n:::\n\n\nWithout a clock, 36% of responses take longer than 60 s. With one, 11% hit the limit, and those are right 29% of the time. Accuracy is 0.55 timed against 0.65 untimed, and hard items lose most: item 10 falls from 0.45 to 0.25, item 3 only from 0.90 to 0.80. That fits a tradeoff forced by the deadline, as far as two samples can show it.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Responses without a time (and two timed responses under 0.5 s) are set aside.\ntimed <- timed[!is.na(timed$rt) & timed$rt >= 0.5, ]\nuntimed <- untimed[!is.na(untimed$rt), ]\ntimed$lrt <- log(timed$rt); untimed$lrt <- log(untimed$rt)\nfits <- lapply(list(timed = timed, untimed = untimed), function(d) {\n  mt <- lmer(lrt ~ 1 + (1 | id) + (1 | item), d)\n  ma <- glmer(resp ~ 1 + (1 | id) + (1 | item), d, binomial, nAGQ = 0)\n  p <- person_item(mt, ma)\n  list(r = round(c(r_theta_speed = cor(p$theta, p$tau), r_b_beta = cor(p$b, p$beta)), 2),\n       caf = caf(d, mt))\n})\nfits\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$timed\n$timed$r\nr_theta_speed      r_b_beta \n        -0.36          0.74 \n\n$timed$caf\n$timed$caf$by_decile\n   1    2    3    4    5    6    7    8    9   10 \n0.49 0.66 0.68 0.67 0.59 0.55 0.48 0.49 0.46 0.39 \n\n$timed$caf$slope\n[1] -0.64\n\n$timed$caf$se\n res \n0.08 \n\n\n\n$untimed\n$untimed$r\nr_theta_speed      r_b_beta \n        -0.45          0.82 \n\n$untimed$caf\n$untimed$caf$by_decile\n   1    2    3    4    5    6    7    8    9   10 \n0.52 0.67 0.71 0.70 0.69 0.66 0.68 0.64 0.63 0.59 \n\n$untimed$caf$slope\n[1] -0.04\n\n$untimed$caf$se\n res \n0.05 \n```\n\n\n:::\n:::\n\n\nHere abler respondents are *slower*: $r = -0.36$ timed and $-0.45$ untimed, much as [Goldhammer et al. (2014)](https://doi.org/10.1037/a0034716) found for problem solving. Within a respondent, the timed version's curve rises over the fastest few deciles and then falls, to 0.39 in the slowest (slope −0.64); the untimed version's is nearly flat (slope −0.04) apart from its fastest decile, 0.52 against 0.68 in the middle. (Timed log times are cut off at 60 s, which the lognormal model doesn't know.)\n\n### Four tables, four answers\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\ntab <- data.frame(\n  table = c(\"licensure exam\", \"lexical decision\", \"Raven's, timed\", \"Raven's, untimed\"),\n  median_s = c(median(cf$rt), median(roar$rt), median(timed$rt), median(untimed$rt)),\n  r_theta_speed = c(cor(pi_cf$theta, pi_cf$tau), cor(pi_roar$theta, pi_roar$tau),\n                    fits$timed$r[1], fits$untimed$r[1]),\n  fastest = c(caf_cf$by_decile[1], caf_roar$by_decile[1], fits$timed$caf$by_decile[1],\n              fits$untimed$caf$by_decile[1]),\n  middle = c(mean(caf_cf$by_decile[5:6]), mean(caf_roar$by_decile[5:6]),\n             mean(fits$timed$caf$by_decile[5:6]), mean(fits$untimed$caf$by_decile[5:6])),\n  slowest = c(caf_cf$by_decile[10], caf_roar$by_decile[10], fits$timed$caf$by_decile[10],\n              fits$untimed$caf$by_decile[10]),\n  slope = c(caf_cf$slope, caf_roar$slope, fits$timed$caf$slope, fits$untimed$caf$slope))\ntab[, -1] <- round(tab[, -1], 2)\ntab\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|table            | median_s| r_theta_speed| fastest| middle| slowest| slope|\n|:----------------|--------:|-------------:|-------:|------:|-------:|-----:|\n|licensure exam   |    54.00|          0.30|    0.83|   0.74|    0.56| -1.03|\n|lexical decision |     0.85|         -0.09|    0.63|   0.86|    0.70|  0.09|\n|Raven's, timed   |    35.92|         -0.36|    0.49|   0.57|    0.39| -0.64|\n|Raven's, untimed |    46.91|         -0.45|    0.52|   0.68|    0.59| -0.04|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncols <- c(\"#2780e3\", \"#c2410c\", \"#1a1a1a\", \"#93c5fd\")\nall_caf <- rbind(caf_cf$by_decile, caf_roar$by_decile, fits$timed$caf$by_decile,\n                 fits$untimed$caf$by_decile)\nmatplot(1:10, t(all_caf), type = \"b\", pch = 19, lty = 1, col = cols, ylim = c(0.3, 0.95),\n        xlab = \"Decile of residual log time (1 = much faster than expected)\",\n        ylab = \"Proportion correct\")\nlegend(\"bottomleft\", tab$table, col = cols, pch = 19, lty = 1, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](response-time_files/figure-html/compare-1.png){width=576}\n:::\n:::\n\n\nBack to the two questions. One speed per respondent held across the item sets we could compare; these tables can't test it across time. Conditional independence fails in all four, in different shapes, least in the untimed Raven's. How speed and accuracy go together is a property of the task, not a constant of nature.\n\nSo when would I model response time? When the question is about how people take the test: rapid guessing, speededness, whether a time limit changes what is measured, or unusual timing ([van der Linden & Guo, 2008](https://doi.org/10.1007/s11336-007-9046-8)). There the hierarchical model is a reasonable starting point, with the conditional accuracy function as the first check on it. I wouldn't model response time to sharpen $\\theta$. The IRW's [response time and accuracy vignette](https://itemresponsewarehouse.org/vignettes/rt_imv.html) added log time, centred within items, to a Rasch model for 18 tables: the median gain in out-of-sample prediction (IMV) was 0.0054, positive in 78% of tables; with a flexible curve, 0.0091 (94%).\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Model fit and out-of-sample prediction](fit-prediction.qmd): the IMV is the expected gain from betting on one model's predictions against another's. For the 2PL over the Rasch model when slopes vary substantially, it is about 0.01 ([Domingue et al., 2024](https://doi.org/10.1007/s11336-024-09977-2)).\n:::\n\nSo in a typical table response time adds to prediction about half what the 2PL does (0.0054 against 0.01), though in some, the licensure exam among them, it adds more (*Across the IRW*). It says more about how people took the test than about what they know.\n\n## Problems\n\n1. **Medians and means.** Under the lognormal model, show that the median of $t_{ij}$ is $\\exp(\\beta_i - \\tau_j)$ and that the mean is larger by the factor $\\exp(\\sigma^2/2)$. With $\\sigma = 0.5$, how much larger? Why do response-time summaries report medians?\n2. **Which slope? (PS9#1)** On `roar_lexical`, fit `glmer(resp ~ lrt + (1 | item) + (1 | id))` with `lrt` the raw log time. Then replace `lrt` with log time centred within person and item. Which slope answers the speed–accuracy question? Add a squared term: what does it show?\n3. **Flagged respondents.** `credentialform_lnirt` marks 46 respondents whom the test vendor suspected of inappropriate behaviour (`Flagged`). Compare their accuracy and speed with everyone else's. What would preknowledge of some items leave in the data that averages can't show, and how would you look for it?\n4. **A speed score?** Should a program report estimated speed $\\hat\\tau_j$ beside $\\hat\\theta_j$? Argue both sides from the four tables. What would the score mean on the licensure exam, and on Raven's matrices?\n5. **Design a time limit.** To study the speed–accuracy tradeoff with a 20-item reasoning test, compare a limit per item, a limit for the whole test, and a deadline on a random half of each respondent's items. Which lets you estimate a within-person tradeoff, and what does each assume?\n6. **Challenge (open).** Propose one process that gives an inverted U in lexical decision and a falling curve on the licensure exam. What does it predict for Raven's matrices? [Process models for response time](rt-process-models.qmd) takes one route; I don't know of a single account that fits all three.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Response%20time%20and%20the%20speed-accuracy%20tradeoff%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20response%20times%20in%20item%20response%20data%3A%20the%20lognormal%20model%20for%20log%20response%20time%20fit%20as%20a%20crossed%20random-effects%20model%20with%20lme4%2C%20van%20der%20Linden%27s%20hierarchical%20model%20for%20speed%20and%20accuracy%20and%20its%20two%20assumptions%20%28one%20speed%20per%20respondent%2C%20conditional%20independence%20of%20time%20and%20accuracy%29%2C%20the%20speed-accuracy%20tradeoff%20as%20a%20within-person%20claim%20distinct%20from%20the%20correlation%20of%20speed%20and%20ability%20across%20people%2C%20conditional%20accuracy%20functions%20built%20from%20residual%20log%20time%2C%20and%20response%20acceleration%20and%20rapid%20guessing%2C%20with%20a%20licensure%20exam%2C%20a%20lexical%20decision%20task%20and%20timed%20and%20untimed%20Raven%27s%20matrices%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Across the IRW\n\nHow are speed and accuracy related across the IRW's timed tables? For each table with 0/1 responses, response times and at least 150 respondents, [`compute.R`](https://github.com/ben-domingue/irw-course/blob/main/deepdives/response-time/compute.R) runs this lesson's analysis (the two correlations and the conditional accuracy function) and the IMV of adding log time, centred within items, to the accuracy model, on held-out responses.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndd_path <- file.path(\"..\", \"deepdives\", \"response-time\", \"results.rds\")\ndd <- if (file.exists(dd_path)) readRDS(dd_path) else NULL\nif (!is.null(dd)) {\n  s <- dd$summary[order(dd$summary$r_theta_speed), ]\n  print(data.frame(table = s$table, respondents = s$n_resp, items = s$n_items,\n                   median_s = signif(s$median_rt, 2), r_theta_speed = round(s$r_theta_speed, 2),\n                   r_b_beta = round(s$r_b_beta, 2), caf_fastest = round(s$caf_fastest, 2),\n                   caf_slowest = round(s$caf_slowest, 2), caf_slope = round(s$caf_slope, 2),\n                   imv_linear = round(s$imv_linear, 4), imv_spline = round(s$imv_spline, 4)),\n        row.names = FALSE)\n  cols <- c(\"#2780e3\", \"#c2410c\", \"#1a1a1a\", \"#93c5fd\", \"#999999\")\n  tabs <- unique(dd$caf$table)\n  plot(NA, xlim = c(1, 10), ylim = range(dd$caf$accuracy),\n       xlab = \"Decile of residual log time (1 = much faster than expected)\", ylab = \"Proportion correct\")\n  for (k in seq_along(tabs)) {\n    x <- dd$caf[dd$caf$table == tabs[k], ]\n    lines(x$decile, x$accuracy, type = \"b\", pch = 19, col = cols[(k - 1) %% length(cols) + 1])\n  }\n  legend(\"bottomleft\", tabs, col = cols[(seq_along(tabs) - 1) %% length(cols) + 1], pch = 19,\n         lty = 1, bty = \"n\", cex = 0.8)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                table respondents items median_s r_theta_speed\n                      knight_2026_crt         999     7     43.0         -0.29\n himmelstein-impossible_question-2025        1188    90      8.4          0.06\n                 credentialform_lnirt        1636   170     54.0          0.30\n                          chess_lnirt         256    40     13.0          0.50\n r_b_beta caf_fastest caf_slowest caf_slope imv_linear imv_spline\n    -0.43        0.26        0.50      0.67     0.0164     0.0178\n     0.46        0.71        0.54     -1.00     0.0071     0.0076\n     0.48        0.83        0.56     -1.03     0.0199     0.0204\n     0.86        0.52        0.34     -0.96     0.0090     0.0114\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](response-time_files/figure-html/across-1.png){width=576}\n:::\n:::\n\n\n::: {.callout-warning}\n## Partial run: 4 of 20 tables\n\nThis is a pilot run of `compute.R`, on `credentialform_lnirt`, `chess_lnirt` and 2 others drawn at random, to check the pipeline. The full run replaces it.\n:::\n\nRun on 25 September 2026: 4 tables fitted, 0 failed. The correlation of ability and speed runs from -0.29 to 0.50; the linear IMV of log time from 0.0071 to 0.0199 (median 0.0127).\n\nThe licensure row reproduces the lesson's numbers. Its IMV (0.0199) is well above the median of 0.0054 in the IRW's [response time and accuracy vignette](https://itemresponsewarehouse.org/vignettes/rt_imv.html), which reports the whole set and has 0.0188 for this table: the verdict is about the typical table, not every one.\n\n## Going further\n\n- van der Linden, W. J. (2006). A lognormal model for response times on test items. *Journal of Educational and Behavioral Statistics*, 31(2), 181–204. <https://doi.org/10.3102/10769986031002181>. The lognormal model, with a time discrimination for each item.\n- van der Linden, W. J. (2007). A hierarchical framework for modeling speed and accuracy on test items. *Psychometrika*, 72(3), 287–308. <https://doi.org/10.1007/s11336-006-1478-z>. The hierarchical model and its levels.\n- Klein Entink, R. H., Fox, J.-P., & van der Linden, W. J. (2009). A multivariate multilevel approach to the modeling of accuracy and speed of test takers. *Psychometrika*, 74(1), 21–48. <https://doi.org/10.1007/s11336-008-9075-y>. The same model with covariates for speed and accuracy.\n- Fox, J.-P., Klotzke, K., & Simsek, A. S. (2023). R-package LNIRT for joint modeling of response accuracy and times. *PeerJ Computer Science*, 9, e1232. <https://doi.org/10.7717/peerj-cs.1232>. The package that fits the joint model, and that distributes the licensure data.\n- Bolsinova, M., De Boeck, P., & Tijmstra, J. (2017). Modelling conditional dependence between response time and accuracy. *Psychometrika*, 82(4), 1126–1148. <https://doi.org/10.1007/s11336-016-9537-6>. Relaxes conditional independence by letting residual time change an item's intercept and slope.\n- De Boeck, P., & Jeon, M. (2019). An overview of models for response times and processes in cognitive tests. *Frontiers in Psychology*, 10, 102. <https://doi.org/10.3389/fpsyg.2019.00102>. A map of the models: time alone, time jointly with accuracy, local dependence, and time as a covariate.\n- Domingue, B. W., Kanopka, K., Stenhaug, B., Sulik, M. J., Beverly, T., Brinkhuis, M., Circi, R., Faul, J., Liao, D., McCandliss, B., Obradović, J., Piech, C., Porter, T., Project iLEAD Consortium, Soland, J., Weeks, J., Wise, S. L., & Yeatman, J. (2022). Speed–accuracy trade-off? Not so fast: Marginal changes in speed have inconsistent relationships with accuracy in real-world settings. *Journal of Educational and Behavioral Statistics*, 47(5), 576–602. <https://doi.org/10.3102/10769986221099906>. Conditional accuracy functions across 29 datasets, with the method this lesson simplifies.\n- Domingue, B. W., Kanopka, K., Stenhaug, B., Soland, J., Kuhfeld, M., Wise, S., & Piech, C. (2021). Variation in respondent speed and its implications: Evidence from an adaptive testing scenario. *Journal of Educational Measurement*, 58(3), 335–363. <https://doi.org/10.1111/jedm.12291>. Response acceleration in an adaptive reading test.\n- Heitz, R. P. (2014). The speed-accuracy tradeoff: History, physiology, methodology, and behavior. *Frontiers in Neuroscience*, 8, 150. <https://doi.org/10.3389/fnins.2014.00150>. The tradeoff in experimental psychology, and how experiments manipulate it.\n- Goldhammer, F., Naumann, J., Stelter, A., Tóth, K., Rölke, H., & Klieme, E. (2014). The time on task effect in reading and problem solving is moderated by task difficulty and skill. *Journal of Educational Psychology*, 106(3), 608–626. <https://doi.org/10.1037/a0034716>. Time on task going with success on one kind of task and failure on another.\n- Wise, S. L., & Kong, X. (2005). Response time effort: A new measure of examinee motivation in computer-based tests. *Applied Measurement in Education*, 18(2), 163–183. <https://doi.org/10.1207/s15324818ame1802_2>. Rapid guesses as a measure of effort.\n- van der Linden, W. J., & Guo, F. (2008). Bayesian procedures for identifying aberrant response-time patterns in adaptive testing. *Psychometrika*, 73(3), 365–384. <https://doi.org/10.1007/s11336-007-9046-8>. Response times for detecting unusual behaviour (problem 3).\n- Cizek, G. J., & Wollack, J. A. (Eds.). (2016). *Handbook of quantitative methods for detecting cheating on tests*. Routledge. <https://doi.org/10.4324/9781315743097>. The handbook whose credentialing dataset is the licensure exam here.\n- Thissen, D. (1983). Timed testing: An approach using item response theory. In D. J. Weiss (Ed.), *New horizons in testing* (pp. 179–203). Academic Press. <https://doi.org/10.1016/b978-0-12-742780-5.50019-6>. An early item response treatment of timed tests.\n- van der Linden, W. J. (2016). Lognormal response-time model. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 261–282). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315374512>. A handbook chapter on the lognormal model for response times.\n- van der Linden, W. J., & Fox, J.-P. (2016). Joint hierarchical modeling of responses and response times. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 481–500). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315374512>. A handbook chapter on modelling responses and response times together.\n- van der Linden, W. J. (2017). Test speededness and time limits. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 3. Applications* (pp. 249–266). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315117430>. A handbook chapter on test speededness and time limits.\n- From the IRW: the [response time and accuracy](https://itemresponsewarehouse.org/vignettes/rt_imv.html) vignette, the corpus question of *Across the IRW*.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`credentialform_lnirt`](https://itemresponsewarehouse.org/tables/credentialform_lnirt/): Cizek, G. J., & Wollack, J. A. (Eds.). (2016). Handbook of quantitative methods for detecting cheating on tests. Abingdon, England: Routledge. <https://cran.r-project.org/web/packages/LNIRT/index.html>. Licence: GPL-3.0.\n- [`roar_lexical`](https://itemresponsewarehouse.org/tables/roar_lexical/): Yeatman, J. D., Tang, K. A., Donnelly, P. M., Yablonski, M., Ramamurthy, M., Karipidis, I. I., ... & Domingue, B. W. (2021). Rapid online assessment of reading ability. Scientific reports, 11(1), 6396. <https://doi.org/10.1038/s41598-021-85907-x>. Licence: CC BY 4.0.\n- [`rapm_poulton_2022_timed`](https://itemresponsewarehouse.org/tables/rapm_poulton_2022_timed/): Poulton, A., Rutherford, K., Boothe, S., Brygel, M., Crole, A., Dali, G., ... & Hester, R. (2022). Evaluating untimed and timed abridged versions of Raven’s Advanced Progressive Matrices. Journal of Clinical and Experimental Neuropsychology, 44(1), 73-84. <https://doi.org/10.1080/13803395.2022.2080185>. Licence: CC BY 4.0.\n- [`rapm_poulton_2022_untimed`](https://itemresponsewarehouse.org/tables/rapm_poulton_2022_untimed/): Poulton, A., Rutherford, K., Boothe, S., Brygel, M., Crole, A., Dali, G., ... & Hester, R. (2022). Evaluating untimed and timed abridged versions of Raven’s Advanced Progressive Matrices. Journal of Clinical and Experimental Neuropsychology, 44(1), 73-84. <https://doi.org/10.1080/13803395.2022.2080185>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 9 (slides c9, 24–54 and 57), problem set 9 (#1), and the code in `ben-domingue/252`: `ps9/sat.R`.\n- **Timing:** about 45 minutes for the core ideas and widgets, and a 30-minute lab. Run the licensure fits (a minute each) before class.\n- **Changed from 252:** PS9#1's `pisa2018_read` has no tokenless CSV; the licensure exam replaces it. The hierarchical model is set out as two assumptions the tables test, in place of the slides' aside. Raven's and the one-speed checks are new; the conditional accuracy function uses deciles, not splines.\n- **Held back:** process models to [Process models for response time](rt-process-models.qmd); aberrant timing and rapid guessing as a latent class to problems 3 and 6; timing in adaptive tests to [Item banks and adaptive testing](item-banks-cat.qmd). The joint `LNIRT` fit isn't run.\n- **Across the IRW:** `deepdives/response-time/compute.R` is run by hand (it needs a Redivis token); the page reads its `results.rds`, so far a pilot.\n- **Solutions:** held back in `solutions/response-time.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "response-time_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}