{
  "hash": "91ca5b326fadf3f0c446558f4450ffdf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Estimating abilities: MLE and EAP\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Item response theory  \n**Tranche:** core (a first course)  \n**Before this:** [Information, precision, and short forms](information.qmd)  \n**Builds toward:** [Estimating item parameters: JML and EM](item-estimation.qmd) · [Guessing and priors](guessing-priors.qmd) · [Item banks and adaptive testing](item-banks-cat.qmd)  \n**Starts threads:** EAP estimates shrink toward the mean (→ [Item banks and adaptive testing](item-banks-cat.qmd) · [Guessing and priors](guessing-priors.qmd)); No maximum-likelihood estimate for all-right or all-wrong patterns (→ [Item banks and adaptive testing](item-banks-cat.qmd))  \n**Picks up threads:** The sum score is sufficient under the Rasch model (from [The Rasch model](rasch.qmd)); Under the 2PL the weighted score is sufficient (from [From the 1PL to the 4PL](1pl-to-4pl.qmd))  \n**IRW tables:** [`c19prc_uk_mcbride_2021_wordsum`](https://itemresponsewarehouse.org/tables/c19prc_uk_mcbride_2021_wordsum/)  \n**From EDUC 252:** slides c4, c5; problem sets PS3#2, PS5#2; code [`ps3/1_abilities.R`](https://github.com/ben-domingue/252/blob/main/ps3/1_abilities.R), [`ps5/eap_versus_mle.R`](https://github.com/ben-domingue/252/blob/main/ps5/eap_versus_mle.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\noptions(mc.cores = 1)\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {grid, loglik, palette} from \"./widgets/irt.js\"\nimport {wsB, logLikR, mleR, seR, wleR, mapR, posteriorR} from \"./widgets/ability-estimation.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nA respondent answers all ten items of a vocabulary test correctly. What is their ability? The likelihood, which has given us every estimate so far, says it is larger than any number you care to name. Abilities come to us only through an estimator, and the estimators disagree most for the respondents a test measures worst, at the top and the bottom. With the item parameters known, this lesson starts from maximum likelihood, shows where it has no answer, brings in a prior to get the expected a posteriori (EAP) estimate, and fits four estimators to the Wordsum vocabulary test, where 12% of respondents have no maximum-likelihood estimate at all.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- write down the likelihood for one respondent's $\\theta$ with the item parameters known, find its maximum, and give its standard error;\n- explain why a perfect pattern has no maximum-likelihood estimate, and how the alternatives stay finite;\n- compute an EAP estimate on a grid of nodes, and explain why it is pulled toward the mean and by how much;\n- say what the MLE, WLE, MAP and EAP each assume, and choose among them for reporting scores to individuals and for comparing groups;\n- show that under the Rasch model every one of these estimates is a function of the sum score, and that under the 2PL it isn't.\n\n## Core ideas\n\n### One respondent, one unknown\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd): `mirt` estimates the item parameters first, then abilities treating them as known.\n:::\n\nThis lesson is the second step. With the item parameters known, a respondent's answers are independent Bernoulli trials whose probabilities depend on one unknown, $\\theta$: a logistic regression with the respondent's items as the observations ([Lord, 1980](https://doi.org/10.4324/9780203056615)). For the 2PL,\n$$\\ell(\\theta) = \\sum_{i} \\Big[x_i \\log P_i(\\theta) + (1 - x_i)\\log\\big(1 - P_i(\\theta)\\big)\\Big], \\qquad \\frac{\\partial \\ell}{\\partial \\theta} = \\sum_i a_i\\big(x_i - P_i(\\theta)\\big),$$\nand the Rasch model sets every $a_i = 1$.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The likelihood and logistic regression](likelihood.qmd): at the maximum the derivative of the log likelihood (the score equation) is zero, and the curvature gives the standard error. With an intercept, the score equation says the predicted number of successes equals the observed number.\n:::\n\nHere $\\theta$ is that intercept. Under the Rasch model the maximum-likelihood estimate (MLE) solves $\\sum_i P_i(\\hat\\theta) = r$: the expected number correct equals the observed number. Software solves it by Newton–Raphson, stepping from a guess by the ratio of the derivative to the curvature ([Baker & Kim, 2004](https://doi.org/10.1201/9781482276725)).\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Information, precision, and short forms](information.qmd): the negative curvature of the log likelihood is the test information, $I(\\theta) = \\sum_i a_i^2 P_i(1 - P_i)$, and the conditional standard error of measurement is $SE(\\theta) = 1/\\sqrt{I(\\theta)}$. For one respondent's estimate, evaluate it at their $\\hat\\theta$.\n:::\n\nSo the standard error of the MLE is $1/\\sqrt{I(\\hat\\theta)}$, a large-sample approximation that holds up better in the middle of a test than at its ends.\n\n#### Try it: the likelihood of a response pattern\n\nThree Rasch items ($b$ = −1, 0, 1.5). Choose which the respondent gets right; the bold curve is that pattern's likelihood, the pale ones the other seven.\n\n```{ojs}\n//| echo: false\nlp_b = [-1, 0, 1.5]\nlp_labels = lp_b.map((b, i) => `Item ${i + 1} (b = ${b})`.replace(\"-\", \"−\"))\nviewof lp_x = Inputs.checkbox(lp_labels, {label: \"Correct on\", value: [lp_labels[0], lp_labels[1]]})\n```\n\n```{ojs}\n//| echo: false\nlp_pattern = lp_labels.map(l => lp_x.includes(l) ? 1 : 0)\nlp_r = lp_pattern.reduce((s, v) => s + v, 0)\nlp_all = [0, 1, 2, 3, 4, 5, 6, 7].map(m => lp_b.map((_, i) => (m >> i) & 1))\nlp_th = grid(-5, 5, 301)\nlp_curves = lp_all.flatMap(x => lp_th.map(t => ({theta: t, L: Math.exp(loglik(t, x, lp_b)), pat: x.join(\"\"),\n  mine: x.join(\"\") === lp_pattern.join(\"\")})))\nlp_mle = mleR(lp_r, lp_b)\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Ability θ\", domain: [-5, 5]}, y: {label: \"Likelihood\", domain: [0, 1]},\n  marks: [\n    Plot.ruleX(lp_b, {stroke: palette.rule}),\n    Plot.line(lp_curves.filter(d => !d.mine), {x: \"theta\", y: \"L\", z: \"pat\", stroke: palette.light, strokeWidth: 1.2}),\n    Plot.line(lp_curves.filter(d => d.mine), {x: \"theta\", y: \"L\", stroke: palette.main, strokeWidth: 3}),\n    ...(Number.isFinite(lp_mle) ? [Plot.dot([{theta: lp_mle, L: Math.exp(loglik(lp_mle, lp_pattern, lp_b))}], {x: \"theta\", y: \"L\", r: 6, fill: palette.contrast})] : [])\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Pattern **${lp_pattern.join(\"-\")}** (sum score ${lp_r}). ${Number.isFinite(lp_mle) ?\n  `The likelihood peaks at θ = **${lp_mle.toFixed(2)}**, where the information is ${(1 / seR(lp_mle, lp_b) ** 2).toFixed(2)} and the standard error 1 / √${(1 / seR(lp_mle, lp_b) ** 2).toFixed(2)} = **${seR(lp_mle, lp_b).toFixed(2)}**.` :\n  `The likelihood keeps ${lp_r === 0 ? \"rising as θ falls\" : \"rising as θ grows\"}: it has no peak, so there is no maximum-likelihood estimate.`} Item difficulties are the grey lines.`\n```\n\nThe default pattern, 1-1-0, peaks at 1.02, with a standard error of 1.37: three items locate a respondent only roughly. The other two-right patterns peak at the same place, though lower. Tick all three: the likelihood climbs toward 1 and never turns over.\n\n### Perfect patterns have no maximum\n\nWhy does the all-correct pattern never peak? Each item's probability of a correct answer rises with $\\theta$, so their product does too. The score equation asks the expected number correct to equal the number of items, which it approaches but never reaches. The MLE is $+\\infty$, and for an all-wrong pattern $-\\infty$.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The likelihood and logistic regression](likelihood.qmd), its Go deeper callout: if a predictor perfectly separates successes from failures, the logistic regression MLE doesn't exist ([Albert & Anderson, 1984](https://doi.org/10.1093/biomet/71.1.1)). It named a respondent who answers every item correctly as the item-response version.\n:::\n\nIt is the coin with ten heads in ten flips: $\\hat p = 1$, whose log odds is infinite. `mirt` reports $\\pm$`Inf`; `optimize()` on $[-10, 10]$ returns the bound, a number that looks like an estimate (the simulation below shows it). One fix that needs no prior is the weighted likelihood estimate (WLE), which is finite for every pattern under the Rasch model, the 2PL and even the 3PL and 4PL ([Magis & Verhelst, 2017](https://doi.org/10.1007/s11336-016-9518-9)); it has its own subsection below.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A respondent answers all three items in the widget correctly. You give them a fourth item, much harder ($b = 3$), and they get it wrong. What happens to their maximum-likelihood estimate?\",\n  options: [\n    {text: \"It becomes finite\", correct: true, why: \"With 3 of 4 right, the score equation $\\\\sum_i P_i(\\\\theta) = 3$ has a solution: the expected score climbs from 0 to 4 and passes 3 on the way. One wrong answer is enough for the likelihood to turn over. (Here the estimate is 2.49.)\"},\n    {text: \"It stays at $+\\\\infty$, because the respondent still got every easy item right\", correct: false, why: \"Under the Rasch model only the sum score matters, and 3 of 4 is not a perfect score. The wrong answer makes very large values of $\\\\theta$ less likely, so the likelihood peaks.\"},\n    {text: \"It becomes finite, and it must be below 3, the new item's difficulty\", correct: false, why: \"It does become finite (2.49 here), but nothing ties it to the new item's $b$. Had all four items sat at $b = 3$, 3 of 4 would give $3 + \\\\log 3 \\\\approx 4.1$.\"}\n  ]\n})\n```\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: why perfect patterns have no MLE, and what keeps the alternatives finite\n\n**Assumptions:** one respondent answers $I$ dichotomous items under the 2PL (the Rasch model is $a_i = 1$), with the item parameters known and responses locally independent given $\\theta$. Write $P_i = \\text{logit}^{-1}\\big(a_i(\\theta - b_i)\\big)$.\n\n**No maximum.** If every $x_i = 1$, the log likelihood is $\\ell(\\theta) = \\sum_i \\log P_i(\\theta)$, and\n$$\\frac{d\\ell}{d\\theta} = \\sum_i a_i\\,\\big(1 - P_i(\\theta)\\big) > 0 \\quad\\text{for every } \\theta.$$\nThe log likelihood is strictly increasing, bounded above by 0, and approaches 0 as $\\theta \\to \\infty$. It has a least upper bound but no maximum. The all-wrong pattern is the mirror image. This is separation in the sense of [Albert and Anderson (1984)](https://doi.org/10.1093/biomet/71.1.1): with $\\theta$ as the only parameter, a pattern with no variation is perfectly separated.\n\n**The WLE stays finite.** [Warm (1989)](https://doi.org/10.1007/bf02294627) adds a term to the score equation that removes the first-order bias of the MLE. For the Rasch model it is\n$$\\sum_i (x_i - P_i) + \\frac{J(\\theta)}{2I(\\theta)} = 0, \\qquad J(\\theta) = \\sum_i P_i(1 - P_i)(1 - 2P_i),\\quad I(\\theta) = \\sum_i P_i(1 - P_i).$$\nFor a perfect score the first term is $\\sum_i (1 - P_i)$, which falls to 0 as $\\theta$ grows, while the second tends to $-1/2$: as every $P_i \\to 1$, $1 - 2P_i \\to -1$ and $J \\to -I$. As $\\theta$ falls, the first term tends to $I$, the number of items, and the second to $+1/2$. The left-hand side is positive at the bottom of the scale and negative at the top, so it has a root: the WLE is finite. [Magis and Verhelst (2017)](https://doi.org/10.1007/s11336-016-9518-9) prove this for every response pattern under the one- to four-parameter logistic models.\n\n**The EAP and MAP stay finite.** With a normal prior, the log posterior is $\\ell(\\theta) - (\\theta - \\mu)^2/(2\\sigma^2)$ plus a constant. The first term is bounded above by 0 and the second falls without limit, so the log posterior has a maximum (the MAP). The posterior is a bounded function times a normal density, so it has a finite mean (the EAP).\n\n**Why it matters later.** Joint maximum likelihood, which estimates items and respondents together, has to set perfect patterns aside before it starts ([Estimating item parameters](item-estimation.qmd)). An adaptive test estimates $\\theta$ after one or two items, when all-correct patterns are the rule ([Item banks and adaptive testing](item-banks-cat.qmd)). And a reported score has to say something about everyone at the ceiling ([What does a score mean?](score-meaning.qmd)).\n:::\n\n### Bring in a prior: the EAP estimate\n\nThe likelihood lesson set aside the Bayesian reading, in which $\\theta$ gets a **prior** distribution, $g(\\theta)$, and the data turn it into a **posterior**,\n$$p(\\theta \\mid \\mathbf{x}) = \\frac{L(\\theta \\mid \\mathbf{x})\\,g(\\theta)}{\\int L(t \\mid \\mathbf{x})\\,g(t)\\,dt}.$$\nFor ability, the natural prior is the distribution of $\\theta$ in the respondent's population, which `mirt` estimates with the items (a normal with mean 0 and an SD fixed at 1 or estimated). The **expected a posteriori** (EAP) estimate is the posterior mean, and its standard error is the posterior SD ([Bock & Mislevy, 1982](https://doi.org/10.1177/014662168200600405)). The integral needs no closed form: evaluate likelihood × prior at nodes $t_1, \\dots, t_Q$ and average,\n$$\\hat\\theta_{\\text{EAP}} = \\frac{\\sum_q t_q\\,L(t_q)\\,g(t_q)}{\\sum_q L(t_q)\\,g(t_q)}.$$\nNothing iterates and nothing fails: a normal prior times a bounded likelihood always has a mean, even when the likelihood never peaks. The posterior's peak is the **maximum a posteriori** (MAP) estimate, also called Bayes modal ([Mislevy, 1986](https://doi.org/10.1007/bf02293979)).\n\n#### Try it: prior × likelihood = posterior\n\nThe ten Wordsum items analysed below, with their Rasch difficulties. Choose a sum score and the prior's SD (the fitted value is 1.88); each curve is scaled to a peak of 1.\n\n```{ojs}\n//| echo: false\nviewof pp_r = Inputs.range([0, 10], {value: 9, step: 1, label: \"Sum score (of 10)\"})\nviewof pp_sd = Inputs.range([0.3, 4], {value: 1.88, step: 0.01, label: \"Prior SD\"})\n```\n\n```{ojs}\n//| echo: false\npp = posteriorR(pp_r, wsB, 0, pp_sd, grid(-7, 7, 561))\npp_ll = pp.nodes.map(t => logLikR(t, pp_r, wsB))\npp_llmax = Math.max(...pp_ll)\npp_pmax = Math.max(...pp.post)\npp_data = pp.nodes.flatMap((t, k) => [\n  {theta: t, y: Math.exp(pp_ll[k] - pp_llmax), curve: \"Likelihood\"},\n  {theta: t, y: Math.exp(-0.5 * (t / pp_sd) ** 2), curve: \"Prior\"},\n  {theta: t, y: pp.post[k] / pp_pmax, curve: \"Posterior\"}])\npp_mle = mleR(pp_r, wsB)\npp_map = mapR(pp_r, wsB, 0, pp_sd)\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Ability θ\", domain: [-7, 7]}, y: {label: \"Scaled to a peak of 1\", domain: [0, 1.05]},\n  color: {legend: true, domain: [\"Prior\", \"Likelihood\", \"Posterior\"], range: [palette.guide, palette.light, palette.main]},\n  marks: [\n    Plot.line(pp_data, {x: \"theta\", y: \"y\", stroke: \"curve\", strokeWidth: 2.5}),\n    ...(Number.isFinite(pp_mle) ? [Plot.ruleX([pp_mle], {stroke: palette.light, strokeDasharray: \"4,3\"})] : []),\n    Plot.ruleX([pp.eap], {stroke: palette.contrast, strokeWidth: 2})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Sum score ${pp_r} of 10. MLE: **${Number.isFinite(pp_mle) ? pp_mle.toFixed(2) : (pp_mle > 0 ? \"+∞\" : \"−∞\")}**${Number.isFinite(pp_mle) ? ` (SE ${seR(pp_mle, wsB).toFixed(2)}; dashed line)` : \" (no peak)\"}. MAP: **${pp_map.toFixed(2)}**. EAP: **${pp.eap.toFixed(2)}** (posterior SD ${pp.psd.toFixed(2)}; solid line).`\n```\n\nAt a score of 9 the MLE is 2.55, the MAP 1.95 and the EAP 2.08: the prior pulls about half a logit toward 0. At 10 the likelihood never falls, yet the posterior has a peak (2.83) and a mean (3.05). With a prior SD of 1 the EAP for a score of 9 is 1.34; with 4 it is 2.66, just beyond the MLE, as the posterior is skewed toward the open end. At a score of 6 the EAP stays within about 0.1 of the MLE at any prior SD. That pull toward the prior mean is **shrinkage**, largest where the likelihood is flattest: at the ends of the scale, and on short tests.\n\n#### Try it: shrinkage by score, and by test length\n\nEstimates for every score on the Wordsum items. \"Test length\" repeats the ten items (40 items is four copies of each); the horizontal axis is the proportion correct.\n\n```{ojs}\n//| echo: false\nviewof sh_k = Inputs.radio(new Map([[\"10 items\", 1], [\"20 items\", 2], [\"40 items\", 4]]), {value: 1, label: \"Test length\"})\nviewof sh_sd = Inputs.range([0.5, 4], {value: 1.88, step: 0.01, label: \"Prior SD\"})\n```\n\n```{ojs}\n//| echo: false\nsh_b = Array.from({length: sh_k}, () => wsB).flat()\nsh_n = sh_b.length\nsh_rows = Array.from({length: sh_n + 1}, (_, r) => ({r, prop: r / sh_n, mle: mleR(r, sh_b), wle: wleR(r, sh_b), eap: posteriorR(r, sh_b, 0, sh_sd).eap}))\nsh_long = sh_rows.flatMap(d => [\n  ...(Number.isFinite(d.mle) ? [{prop: d.prop, est: d.mle, which: \"MLE\"}] : []),\n  {prop: d.prop, est: d.wle, which: \"WLE\"}, {prop: d.prop, est: d.eap, which: \"EAP\"}])\nPlot.plot({\n  width: 700, height: 320, x: {label: \"Proportion correct\", domain: [0, 1]}, y: {label: \"Estimate of θ\", domain: [-6, 6]},\n  color: {legend: true, domain: [\"MLE\", \"WLE\", \"EAP\"], range: [palette.light, palette.guide, palette.main]},\n  marks: [\n    Plot.ruleY([0], {stroke: palette.rule}),\n    Plot.line(sh_long, {x: \"prop\", y: \"est\", stroke: \"which\", strokeWidth: 2}),\n    Plot.dot(sh_long, {x: \"prop\", y: \"est\", fill: \"which\", r: sh_k === 1 ? 4 : 2.5})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nsh_90 = sh_rows[Math.round(0.9 * sh_n)]\nmd`At 90% correct (${sh_90.r} of ${sh_n}): MLE **${sh_90.mle.toFixed(2)}**, WLE ${sh_90.wle.toFixed(2)}, EAP **${sh_90.eap.toFixed(2)}**. At 100%: no MLE, WLE ${sh_rows[sh_n].wle.toFixed(2)}, EAP ${sh_rows[sh_n].eap.toFixed(2)}.`\n```\n\nThe MLE at 90% correct is 2.55 whatever the length, because repeating every item multiplies both sides of the score equation by the same number. The EAP moves toward it as the test grows, from 2.08 with 10 items to 2.42 with 40, as the likelihood sharpens. The WLE, taken up below, sits nearer the MLE and gives a perfect score a finite value (3.59 with 10 items).\n\nShrinkage carries into anything computed from the estimates. If you've done [Model fit and out-of-sample prediction](fit-prediction.qmd), it is why outfit computed from `mirt`'s default EAP abilities averaged about 0.9 on simulated 20-item data where the model was true.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Two respondents each answer 90% of their items correctly, one on a 10-item test and one on a 40-item version with four copies of each item. Both are scored by EAP with the same prior. Whose estimate is pulled further toward the prior mean?\",\n  options: [\n    {text: \"The respondent on the 10-item test\", correct: true, why: \"With fewer items the likelihood is flatter, so the prior carries more weight in the posterior. In the widget, the EAP at 90% correct is 2.08 with 10 items and 2.42 with 40, against an MLE of 2.55 for both.\"},\n    {text: \"The respondent on the 40-item test, since more items give the prior more to work with\", correct: false, why: \"The prior is the same in both cases; what changes is the likelihood. Forty items give a sharper likelihood, which outweighs the prior.\"},\n    {text: \"Neither: the same proportion correct gives the same estimate\", correct: false, why: \"That's true of the MLE here, whose score equation scales with the number of items. The EAP also depends on how sharp the likelihood is.\"}\n  ]\n})\n```\n\n### MAP, EAP and plausible values\n\nThe MAP sits close to the EAP; it is found by Newton–Raphson with the prior adding a term to the score equation, and suits software that finds modes more easily than means. If the prior describes the population, the EAP has the smallest mean squared error averaged over that population, since squared error is what a posterior mean minimizes; shrinkage is the other side of that coin.\n\nNo individual estimate carries the spread of $\\theta$ itself (EAPs vary too little, MLEs too much), so variances, correlations and regressions built on them are off. Large-scale assessments such as NAEP use **plausible values** ([Mislevy, 1991](https://doi.org/10.1007/bf02294457); [Mislevy, Beaton, Kaplan & Sheehan, 1992](https://doi.org/10.1111/j.1745-3984.1992.tb00371.x)): several random draws from each respondent's posterior, under a prior that is a regression of $\\theta$ on background variables. Each set has the spread and group differences of $\\theta$; the analysis is run on each and combined as in multiple imputation. They are a tool for population quantities, not scores to report for individuals ([Wu, 2005](https://doi.org/10.1016/j.stueduc.2005.05.005)). [What does a score mean?](score-meaning.qmd) takes them up in full.\n\n### The weighted likelihood estimate\n\nWhat if we want an estimate that borrows nothing from the population but exists for every pattern? [Warm (1989)](https://doi.org/10.1007/bf02294627) weights the likelihood by a function of $\\theta$ chosen to cancel the leading term of the MLE's bias, the bias that [Lord (1983)](https://doi.org/10.1007/BF02294018) derives. This adds $J(\\theta)/2I(\\theta)$ to the score equation (the Go deeper callout writes it out). The WLE has the MLE's large-sample variance, less bias, and a finite value for every pattern ([Magis & Verhelst, 2017](https://doi.org/10.1007/s11336-016-9518-9)). It is [Firth's (1993)](https://doi.org/10.1093/biomet/80.1.27) bias reduction, which penalizes the likelihood by the Jeffreys prior and also gives finite logistic regressions under separation ([Heinze & Schemper, 2002](https://doi.org/10.1002/sim.1047)); for the Rasch model and 2PL the WLE is the peak of the likelihood times that prior, while under the 3PL the two part ([Magis & Raîche, 2012](https://doi.org/10.1007/s11336-011-9233-5)).\n\nHow does it compare? Warm's Monte Carlo studies favoured it over the MLE and Bayes modal estimates on several criteria across a wide range of abilities, and [Kim and Nicewander (1993)](https://doi.org/10.1007/bf02294829) found the WLE, MAP and EAP all close to unbiased where the test's items are. That is the evidence: less bias than the MLE at the same variance, and finiteness, not optimality in general. The cost is the EAP's lower error. The WLE doesn't shrink, so in the simulation below its RMSE is 0.77 against the EAP's 0.61, and its SD 1.28 against a true 1. It suits estimates that must not depend on a population prior, as when respondents come from different populations.\n\n### Sufficiency, revisited\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd): under the Rasch model the sum score $r$ is sufficient for $\\theta$. The likelihood factorizes into $e^{r\\theta}$, times a term free of $\\theta$, over a term free of the pattern.\n:::\n\nEvery estimator here uses the responses only through the likelihood, so under the Rasch model every one depends on them only through $r$: the score equations contain the data only as $r$, and in the posterior the pattern's own factor cancels. Ten Wordsum items give eleven possible EAPs, which is how the widgets above could list every estimate.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [From the 1PL to the 4PL](1pl-to-4pl.qmd): under the 2PL the likelihood depends on the pattern only through the weighted score $\\sum_i a_i x_i$, which is therefore sufficient; the score equation is $\\sum_i a_i (x_i - P_i) = 0$.\n:::\n\nSo respondents with the same sum score but different items right get different estimates, ordered by $\\sum_i a_i x_i$.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [From the 1PL to the 4PL](1pl-to-4pl.qmd), its Go deeper callout: under the 3PL the weight of each correct answer depends on $\\theta$, so no simple statistic is sufficient. There an estimate depends on the whole pattern, not on a weighted sum.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Under a 2PL, two respondents each answer 5 of 10 items correctly, and one gets a higher EAP than the other. What can you say about their responses?\",\n  options: [\n    {text: \"The one with the higher EAP answered items with larger total slope correctly\", correct: true, why: \"Under the 2PL the posterior depends on the pattern only through $\\\\sum_i a_i x_i$, and the EAP increases with it. Same sum score, different weighted score.\"},\n    {text: \"The one with the higher EAP answered harder items correctly\", correct: false, why: \"Difficulty enters the likelihood only in a term without $\\\\theta$, which cancels in the posterior. What matters is the slopes of the items answered correctly.\"},\n    {text: \"Nothing: EAPs contain random error\", correct: false, why: \"An EAP is a fixed function of the pattern, the item parameters and the prior. Two patterns with the same weighted score get the same EAP.\"}\n  ]\n})\n```\n\n## Simulate\n\nWhich estimator lands closest to the truth? The code below simulates Rasch responses to ten items ($b$ from −2 to 2) from 5,000 respondents in two groups whose means differ by 1 (overall mean 0, SD 1), estimates every $\\theta$ four ways with the difficulties known and a normal(0, 1) prior, and reports bias and root mean squared error (RMSE) by true $\\theta$, the SD of the estimates and the group difference. It is base R and runs in a second.\n\nWith the seed as written, 112 of the 5,000 respondents (2.2%) have no finite MLE, and `optimize()` on a perfect score returns 10, its upper bound. The MLE and WLE are close to unbiased across the middle; the EAP and MAP are pulled toward 0, by about 0.16 within one SD of the mean, 0.5 one to two SDs out, and 1 beyond. In return the EAP's RMSE is 0.52 in the middle, against 0.78 to 0.80 for the MLE, and 0.61 overall against 0.79 (without the 112). At the ends the order reverses. The SDs are 1.26 (MLE) and 0.80 (EAP) against a true 1, and the group difference is 0.98 (MLE), 1.03 (WLE) and 0.65 (EAP). With `length.out` at 20 or 40, the EAP's group difference rises to 0.80 and 0.89.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-16\n# Four ways to estimate a respondent's ability from Rasch responses, with the item\n# difficulties treated as known: maximum likelihood (MLE), weighted likelihood (WLE),\n# the posterior mode (MAP) and the posterior mean (EAP), the last two with a\n# normal(0, 1) prior. Compare each with the true abilities: bias and root mean squared\n# error (RMSE) along the scale, the spread of the estimates, and a group difference.\n# Base R only; runs in a second or two. Adapted from ben-domingue/252: ps5/eap_versus_mle.R.\nset.seed(37)\nnp <- 5000                          # respondents\nb  <- seq(-2, 2, length.out = 10)   # item difficulties: try 20 or 40 items\ng  <- rep(0:1, each = np / 2)       # two groups whose true means differ by 1\nth <- rnorm(np, -0.5 + g, sqrt(0.75))   # overall mean 0, SD 1: the prior is right\n\np    <- plogis(outer(th, b, \"-\"))\nresp <- matrix(rbinom(length(p), 1, p), np, length(b))\nr    <- rowSums(resp)\nn    <- length(b)\n\n# Under the Rasch model every estimator depends on the responses only through the\n# sum score r, so we need one estimate per possible score, 0 to n.\nP    <- function(t) plogis(t - b)\ninfo <- function(t) sum(P(t) * (1 - P(t)))\nsolve <- function(f) uniroot(f, c(-12, 12))$root\nmle <- sapply(0:n, function(s) if (s == 0) -Inf else if (s == n) Inf else\n  solve(function(t) s - sum(P(t))))                           # score equation\nwle <- sapply(0:n, function(s)                                 # Warm's correction\n  solve(function(t) s - sum(P(t)) + sum(P(t) * (1 - P(t)) * (1 - 2 * P(t))) / (2 * info(t))))\nmap <- sapply(0:n, function(s) solve(function(t) s - sum(P(t)) - t))   # prior N(0, 1)\nnodes <- seq(-6, 6, length.out = 121)                          # EAP by quadrature\neap <- sapply(0:n, function(s) {\n  post <- dnorm(nodes) * sapply(nodes, function(t) exp(s * t) / prod(1 + exp(t - b)))\n  sum(nodes * post) / sum(post)\n})\nest <- data.frame(MLE = mle[r + 1], WLE = wle[r + 1], MAP = map[r + 1], EAP = eap[r + 1])\ncat(\"Respondents with no finite MLE:\", sum(!is.finite(est$MLE)), \"of\", np, \"\\n\")\n# A bounded optimizer doesn't say so: for a perfect score it returns the bound.\ncat(\"optimize() on a perfect score:\",\n    round(optimize(function(t) sum(log(P(t))), c(-10, 10), maximum = TRUE)$maximum, 2), \"\\n\\n\")\n\n# Bias and RMSE within bins of true ability (MLE: finite estimates only).\nbins <- cut(th, c(-Inf, -2, -1, 0, 1, 2, Inf))\nsumm <- function(f) sapply(est, function(e) tapply(seq_along(th), bins, function(k) {\n  ok <- k[is.finite(e[k])]; round(f(e[ok] - th[ok]), 2) }))\ncat(\"Bias (estimate - truth) by true ability:\\n\"); print(summ(mean))\ncat(\"\\nRMSE by true ability:\\n\");                  print(summ(function(d) sqrt(mean(d^2))))\n\n# Overall RMSE, the spread of the estimates, and the difference between the two\n# groups' mean estimates (true: 1). The MLE column leaves out the respondents it has\n# no estimate for; the other three include everyone.\nfin <- is.finite(est$MLE)\ncat(\"\\nSD of true abilities:\", round(sd(th), 2), \"\\n\")\nprint(round(rbind(\n  RMSE = sapply(est, function(e) sqrt(mean((e - th)[is.finite(e)]^2))),\n  SD = sapply(est, function(e) sd(e[is.finite(e)])),\n  group_difference = sapply(est, function(e) { k <- is.finite(e); mean(e[k & g == 1]) - mean(e[k & g == 0]) })), 2))\n\nplot(th, est$EAP, pch = \".\", col = \"#2780e3\", xlab = \"True ability\", ylab = \"Estimate\",\n     ylim = c(-4, 4), main = paste(n, \"items\"))\npoints(th[fin], est$MLE[fin], pch = \".\", col = \"#c2410c\")\nabline(0, 1, lty = 2)\nlegend(\"topleft\", c(\"EAP\", \"MLE\"), pch = 19, col = c(\"#2780e3\", \"#c2410c\"), bty = \"n\")\n\n```\n:::\n\n\n[Download this code](code/ability-estimation-sim.R) to run it in your own R session.\n\n## With real data\n\n\n\nOur main example is [c19prc_uk_mcbride_2021_wordsum](https://itemresponsewarehouse.org/tables/c19prc_uk_mcbride_2021_wordsum/): the Wordsum vocabulary test as answered by 2,058 UK adults in the sixth wave of the COVID-19 Psychological Research Consortium study ([Bentall et al., 2022](https://doi.org/10.5255/UKDA-SN-855552); the study's design is described by [McBride et al., 2021](https://doi.org/10.1002/mpr.1861)). Wordsum is the ten-item vocabulary test of the US General Social Survey, drawn from [Thorndike (1942)](https://doi.org/10.1037/h0060053) and analysed with item response theory by [Cor, Haertel, Krosnick and Malhotra (2012)](https://doi.org/10.1016/j.ssresearch.2012.05.007): for each target word, choose the closest in meaning from five words, or \"don't know\". Its job here is to be a short test on which many respondents reach the floor or the ceiling. A response is 1 for the right word and 0 otherwise, \"don't know\" included. [Download the code](code/ability-estimation-irw.R) to run every chunk yourself; it needs `mirt` ([Chalmers, 2012](https://doi.org/10.18637/jss.v048.i06)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(mirt)\n# Each IRW table has a landing page (itemresponsewarehouse.org/tables/<name>/) with a\n# CSV download. This link is pinned to one version of the data.\nws_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_4:v7_0.c19prc_uk_mcbride_2021_wordsum/rows?format=csv\"\ndf <- read.csv(ws_url)\ntable(df$wave)   # one wave (6), so one response per respondent and item\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    6 \n20580 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# resp is 1 when the respondent chose the listed word closest in meaning to the target\n# word, and 0 for any other choice, including \"don't know\".\nwide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\nwide <- as.data.frame(wide[, order(as.numeric(gsub(\"\\\\D\", \"\", colnames(wide))))])\nc(respondents = nrow(wide), items = ncol(wide), complete = sum(complete.cases(wide)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents       items    complete \n       2058          10        2058 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(colMeans(wide), 2)   # proportion correct, item by item\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Wordsum_1  Wordsum_2  Wordsum_3  Wordsum_4  Wordsum_5  Wordsum_6  Wordsum_7  Wordsum_8 \n      0.69       0.78       0.27       0.84       0.67       0.82       0.37       0.30 \n Wordsum_9 Wordsum_10 \n      0.67       0.29 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nr <- rowSums(wide)          # sum score, 0 to 10\ntable(r)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr\n  0   1   2   3   4   5   6   7   8   9  10 \n 95  83 114 152 176 282 333 253 211 203 156 \n```\n\n\n:::\n:::\n\n\nThere is one wave, every respondent answered all ten items, and the items run from 27% to 84% correct.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The Rasch model. mirt fixes every slope at 1 and the mean ability at 0, and\n# estimates the SD of ability; its d is an easiness, so our difficulty is b = -d.\nm <- mirt(wide, 1, itemtype = \"Rasch\", verbose = FALSE)\nb <- -coef(m, simplify = TRUE)$items[, \"d\"]\nround(sort(b), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Wordsum_4  Wordsum_6  Wordsum_2  Wordsum_1  Wordsum_9  Wordsum_5  Wordsum_7  Wordsum_8 \n     -2.51      -2.32      -1.98      -1.24      -1.13      -1.10       0.88       1.37 \nWordsum_10  Wordsum_3 \n      1.39       1.55 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(sd_theta = round(sqrt(coef(m)$GroupPars[, \"COV_11\"]), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd_theta \n    1.88 \n```\n\n\n:::\n:::\n\n\nThe difficulties fall in two groups, six easy items from −2.51 to −1.10 and four hard ones from 0.88 to 1.55, with nothing between. The SD of ability, 1.88, is the prior's SD for the EAP and MAP estimates below.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"What share of the 2,058 Wordsum respondents have no finite maximum-likelihood estimate?\",\n  choices: [\"Under 1%\", \"About 5%\", \"About 12%\", \"About 25%\"],\n  answer: \"About 12%\",\n  reveal: \"About 12%: the 95 respondents who answered no item correctly and the 156 who answered all ten, 251 in all (12.2%). With ten items and abilities spread with an SD of 1.88, many respondents sit beyond the easiest or the hardest item. Check the output below.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# How many respondents have no finite maximum-likelihood estimate?\nml <- fscores(m, method = \"ML\", full.scores.SE = TRUE)\ndata.frame(zero = sum(r == 0), perfect = sum(r == 10), no_mle = sum(r %in% c(0, 10)),\n           share = round(mean(r %in% c(0, 10)), 3))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| zero| perfect| no_mle| share|\n|----:|-------:|------:|-----:|\n|   95|     156|    251| 0.122|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(ml[, \"F1\"][r %in% c(0, 10)])   # mirt reports them as -Inf and Inf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n-Inf  Inf \n  95  156 \n```\n\n\n:::\n:::\n\n\nThe 251 respondents with a score of 0 or 10 are 12.2% of the sample, and `mirt` gives them $-\\infty$ and $+\\infty$. The simulation above, with an ability SD of 1, had 2.2%.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Four estimators. Under the Rasch model each is a function of the sum score alone,\n# so one row per score says everything (the last line checks it).\nmeth <- c(\"ML\", \"WLE\", \"MAP\", \"EAP\")\nest <- lapply(meth, function(k) fscores(m, method = k, full.scores.SE = TRUE))\nnames(est) <- meth\nby_r <- function(col) sapply(est, function(e) tapply(e[, col], r, function(z) z[1]))\ntab <- data.frame(score = 0:10, n = as.vector(table(r)), round(by_r(\"F1\"), 2),\n                  SE = round(by_r(\"SE_F1\"), 2), check.names = FALSE)\nprint(tab, row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n score   n    ML   WLE   MAP   EAP SE.ML SE.WLE SE.MAP SE.EAP\n     0  95  -Inf -4.48 -3.49 -3.65    NA   1.48   0.96   0.94\n     1  83 -3.48 -3.17 -2.72 -2.83  1.11   0.95   0.82   0.86\n     2 114 -2.53 -2.41 -2.10 -2.16  0.88   0.81   0.76   0.79\n     3 152 -1.83 -1.79 -1.55 -1.57  0.81   0.77   0.73   0.75\n     4 176 -1.20 -1.21 -1.02 -1.02  0.79   0.77   0.73   0.74\n     5 282 -0.57 -0.60 -0.48 -0.47  0.80   0.80   0.74   0.75\n     6 333  0.09  0.07  0.08  0.10  0.83   0.83   0.76   0.76\n     7 253  0.79  0.76  0.66  0.69  0.85   0.83   0.77   0.78\n     8 211  1.56  1.46  1.27  1.33  0.91   0.85   0.80   0.82\n     9 203  2.55  2.26  1.95  2.07  1.13   0.96   0.86   0.91\n    10 156   Inf  3.59  2.83  3.03    NA   1.49   1.03   1.05\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(largest_spread_within_a_score = round(max(sapply(est, function(e)\n  max(tapply(e[, \"F1\"], r, function(z) diff(range(z))), na.rm = TRUE))), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlargest_spread_within_a_score \n                            0 \n```\n\n\n:::\n:::\n\n\nEach estimator gives one value per sum score (the largest spread within a score is 0). In the middle they nearly agree: a score of 5 gives −0.57 (MLE), −0.60 (WLE), −0.48 (MAP) and −0.47 (EAP). They part at the ends. A score of 9 gives 2.55, 2.26, 1.95 and 2.07, and a score of 10 gives $+\\infty$, 3.59, 2.83 and 3.03. The MLE's standard error is 0.79 at a score of 4 and 1.13 at 9; the posterior SDs are smaller everywhere.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The ML standard error is 1 / sqrt(test information) at the estimate.\nfin <- is.finite(ml[, \"F1\"])\nall.equal(unname(ml[fin, \"SE_F1\"]), 1 / sqrt(testinfo(m, ml[fin, \"F1\", drop = FALSE])),\n          tolerance = 1e-4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n`mirt`'s MLE standard errors are $1/\\sqrt{I(\\hat\\theta)}$, the test information evaluated at each estimate (`all.equal` returns `TRUE`).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# EAPs are pulled toward the mean: their SD is below the model's SD of ability.\n# The posterior variances make up the difference.\neap <- est$EAP\nsd_model <- sqrt(coef(m)$GroupPars[, \"COV_11\"])\nround(c(sd_model = sd_model, sd_eap = sd(eap[, \"F1\"]), sd_wle = sd(est$WLE[, \"F1\"])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd_model   sd_eap   sd_wle \n    1.88     1.69     1.96 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(var_model = sd_model^2, var_eap = var(eap[, \"F1\"]),\n        mean_posterior_var = mean(eap[, \"SE_F1\"]^2),\n        sum = var(eap[, \"F1\"]) + mean(eap[, \"SE_F1\"]^2)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         var_model            var_eap mean_posterior_var                sum \n              3.54               2.86               0.67               3.53 \n```\n\n\n:::\n:::\n\n\nThe EAPs have an SD of 1.69, below the model's 1.88; the WLEs, at 1.96, are above it. The shortfall isn't lost: the variance of the EAPs (2.86) plus the average posterior variance (0.67) is 3.53, the model's variance (3.54) to rounding.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The 2PL. Now the weighted score sum(a * x) carries the information about theta,\n# so respondents with the same sum score can get different estimates.\nm2 <- mirt(wide, 1, itemtype = \"2PL\", verbose = FALSE)\nc(BIC_Rasch = round(extract.mirt(m, \"BIC\")), BIC_2PL = round(extract.mirt(m2, \"BIC\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBIC_Rasch   BIC_2PL \n    19887     19398 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\na <- coef(m2, simplify = TRUE)$items[, \"a1\"]\nround(a, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Wordsum_1  Wordsum_2  Wordsum_3  Wordsum_4  Wordsum_5  Wordsum_6  Wordsum_7  Wordsum_8 \n      1.62       3.75       1.21       5.20       3.64       3.94       1.09       1.21 \n Wordsum_9 Wordsum_10 \n      1.59       2.20 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\neap2 <- fscores(m2, method = \"EAP\")[, \"F1\"]\nfive <- r == 5\nw <- as.matrix(wide) %*% a   # weighted score\ndata.frame(respondents = sum(five),\n  patterns = nrow(unique(wide[five, ])),\n  weighted_scores = length(unique(round(w[five], 6))),\n  EAPs = length(unique(round(eap2[five], 6))),\n  lowest = round(min(eap2[five]), 2), highest = round(max(eap2[five]), 2),\n  rank_cor = round(cor(w[five], eap2[five], method = \"spearman\"), 3))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| respondents| patterns| weighted_scores| EAPs| lowest| highest| rank_cor|\n|-----------:|--------:|---------------:|----:|------:|-------:|--------:|\n|         282|       40|              40|   40|  -1.05|   -0.04|        1|\n\n</div>\n:::\n:::\n\n\nBIC ([Schwarz, 1978](https://doi.org/10.1214/aos/1176344136)) prefers the 2PL to the Rasch model (19,398 against 19,887), and the slopes run from 1.09 to 5.20. The 282 respondents with a score of 5 gave 40 different response patterns, which have 40 different weighted scores and get 40 different EAPs, from −1.05 to −0.04, in exactly the order of their weighted scores (rank correlation 1). Under the Rasch model all 282 shared one EAP, −0.47: a full logit of difference among respondents with the same number right comes from the choice of model.\n\n### Which estimate to report\n\nThe choice rests on what we'll assume and on what the numbers are for.\n\n- The MLE and WLE assume nothing about the population: the estimate comes from the respondent's own responses, which suits comparisons across populations. The price is noise: on Wordsum the MLE's standard errors run from 0.79 to 1.13, and 12% of respondents have no MLE.\n- The EAP and MAP assume the respondent comes from the population the prior describes. If so, they are closer to the truth on average (in the simulation, an RMSE of 0.61 against 0.79). The price is shrinkage toward that population's mean, largest at the ends and on short tests, which carries into spreads and group differences.\n\nWhen I report a score to an individual from a test like this one, I report the EAP with its posterior SD, and I say that it is pulled toward the mean of the population the prior describes. It always exists, it is the most accurate on average for the people the test was given to, and its standard error grows where the items run out. What I don't do is average EAPs to compare groups: the simulation's group difference of 1 came back as 0.65. The MLEs and WLEs came closer, but they vary too much for spreads and correlations. If a prior is unwelcome, say because respondents come from different populations, I'd use the WLE rather than the MLE, which loses everyone at the floor and the ceiling. For group questions I'd put the groups into the model, or use plausible values. And if the Rasch model fits and everyone took the same items, [The Rasch model](rasch.qmd) has already argued for the sum score: every estimator in the table above is a relabelling of it.\n\n## Problems\n\n1. **Three items by hand.** For Rasch items with $b = -1, 0, 1.5$, plot the likelihood of 1-1-0. At what $\\theta$ does 1-1-0 become more likely than 1-0-0, and why is that a difficulty? (PS4#1)\n2. **The Rasch score equation.** Show that the Rasch MLE solves $\\sum_i P_i(\\theta) = r$. Then use the factorization from the Rasch lesson's Go deeper callout to show that the EAP depends on the pattern only through $r$ too.\n3. **Change the prior.** Rescore Wordsum by EAP with a prior SD of 1 instead of 1.88 (`fscores(m, method = \"EAP\", mean = 0, cov = 1)`). Which respondents move most? What happens to the SD of the EAPs, and why?\n4. **Classroom averages.** A school compares classroom means of students' EAPs from a 15-item test, with one normal prior for everyone. What goes wrong, in which direction, and what would you report instead?\n5. **Does EAP reduce error?** Extend the simulation: 1,000 respondents at each true $\\theta$ from −3 to 3 in steps of 0.5. Where does the EAP's RMSE beat the MLE's, and where not? Then score normal(0, 1) respondents with a prior of mean 1. What changes? (PS5#2)\n6. **Challenge (open): the floor and the ceiling.** A survey analyst wants Wordsum as a predictor of, say, trust in science. What should they do with the 251 respondents at 0 or 10: drop them, use WLEs, EAPs or plausible values, or fit the regression inside the item response model? Does it depend on the question? I don't think there is a single answer; make the case for yours.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Estimating%20abilities%3A%20MLE%20and%20EAP%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20estimating%20one%20respondent%27s%20ability%20with%20the%20item%20parameters%20known%3A%20maximum%20likelihood%20by%20the%20score%20equation%20and%20its%20standard%20error%20from%20information%2C%20why%20all-correct%20and%20all-wrong%20patterns%20have%20no%20MLE%2C%20EAP%20estimation%20with%20a%20prior%20on%20a%20grid%20of%20nodes%20and%20the%20shrinkage%20it%20brings%2C%20MAP%20and%20Warm%27s%20weighted%20likelihood%20estimator%2C%20plausible%20values%20in%20brief%2C%20and%20why%20under%20the%20Rasch%20model%20every%20estimator%20is%20a%20function%20of%20the%20sum%20score%20while%20under%20the%202PL%20it%20follows%20the%20weighted%20score%2C%20with%20mirt%20analyses%20of%20the%20Wordsum%20vocabulary%20test.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Bock, R. D., & Mislevy, R. J. (1982). Adaptive EAP estimation of ability in a microcomputer environment. *Applied Psychological Measurement*, 6(4), 431–444. <https://doi.org/10.1177/014662168200600405>. The EAP estimate on a grid of nodes, and its posterior SD as a standard error.\n- Warm, T. A. (1989). Weighted likelihood estimation of ability in item response theory. *Psychometrika*, 54(3), 427–450. <https://doi.org/10.1007/bf02294627>. The WLE, compared with the MLE and Bayes modal estimates.\n- Magis, D., & Verhelst, N. (2017). On the finiteness of the weighted likelihood estimator of ability. *Psychometrika*, 82(3), 637–647. <https://doi.org/10.1007/s11336-016-9518-9>. The WLE is finite for every pattern under the 1PL to 4PL and many polytomous models.\n- Magis, D., & Raîche, G. (2012). On the relationships between Jeffreys modal and weighted likelihood estimation of ability under logistic IRT models. *Psychometrika*, 77(1), 163–169. <https://doi.org/10.1007/s11336-011-9233-5>. Where the WLE and the Jeffreys-prior mode coincide, and where they part.\n- Firth, D. (1993). Bias reduction of maximum likelihood estimates. *Biometrika*, 80(1), 27–38. <https://doi.org/10.1093/biomet/80.1.27>. The general form of Warm's correction.\n- Heinze, G., & Schemper, M. (2002). A solution to the problem of separation in logistic regression. *Statistics in Medicine*, 21(16), 2409–2419. <https://doi.org/10.1002/sim.1047>. Firth's correction as a fix for separation, the logistic-regression version of perfect patterns.\n- Kim, J. K., & Nicewander, W. A. (1993). Ability estimation for conventional tests. *Psychometrika*, 58(4), 587–599. <https://doi.org/10.1007/bf02294829>. Five estimators compared for bias, standard error and reliability.\n- Lord, F. M. (1983). Unbiased estimators of ability parameters, of their variance, and of their parallel-forms reliability. *Psychometrika*, 48(2), 233–245. <https://doi.org/10.1007/BF02294018>. The bias of the MLE, and estimators without it.\n- Mislevy, R. J. (1986). Bayes modal estimation in item response models. *Psychometrika*, 51(2), 177–195. <https://doi.org/10.1007/bf02293979>. Priors in item response models.\n- Mislevy, R. J. (1991). Randomization-based inference about latent variables from complex samples. *Psychometrika*, 56(2), 177–196. <https://doi.org/10.1007/bf02294457>. Plausible values as multiple imputation, with NAEP data.\n- Mislevy, R. J., Beaton, A. E., Kaplan, B., & Sheehan, K. M. (1992). Estimating population characteristics from sparse matrix samples of item responses. *Journal of Educational Measurement*, 29(2), 133–161. <https://doi.org/10.1111/j.1745-3984.1992.tb00371.x>. Plausible values, from the concepts to NAEP.\n- Wu, M. (2005). The role of plausible values in large-scale surveys. *Studies in Educational Evaluation*, 31(2–3), 114–128. <https://doi.org/10.1016/j.stueduc.2005.05.005>. Plausible values and individual estimates, side by side.\n- Baker, F. B., & Kim, S.-H. (2004). *Item response theory: Parameter estimation techniques* (2nd ed.). Marcel Dekker. <https://doi.org/10.1201/9781482276725>. Newton–Raphson for abilities, and the rest of the machinery, step by step.\n- Lord, F. M. (1980). *Applications of item response theory to practical testing problems*. Erlbaum. <https://doi.org/10.4324/9780203056615>. The likelihood for ability with the items known.\n- Albert, A., & Anderson, J. A. (1984). On the existence of maximum likelihood estimates in logistic regression models. *Biometrika*, 71(1), 1–10. <https://doi.org/10.1093/biomet/71.1.1>. Separation, of which perfect patterns are an instance.\n- Andersen, E. B. (1977). Sufficient statistics and latent trait models. *Psychometrika*, 42(1), 69–81. <https://doi.org/10.1007/BF02293746>. Why only the Rasch model makes the sum score sufficient.\n- Cor, M. K., Haertel, E., Krosnick, J. A., & Malhotra, N. (2012). Improving ability measurement in surveys by following the principles of IRT: The Wordsum vocabulary test in the General Social Survey. *Social Science Research*, 41(5), 1003–1016. <https://doi.org/10.1016/j.ssresearch.2012.05.007>. Wordsum analysed with item response theory.\n- Thorndike, R. L. (1942). Two screening tests of verbal intelligence. *Journal of Applied Psychology*, 26(2), 128–135. <https://doi.org/10.1037/h0060053>. Where the Wordsum items come from.\n- McBride, O., Murphy, J., Shevlin, M., Gibson-Miller, J., Hartman, T. K., Hyland, P., et al. (2021). Monitoring the psychological, social, and economic impact of the COVID-19 pandemic in the population: Context, design and conduct of the longitudinal COVID-19 Psychological Research Consortium (C19PRC) Study. *International Journal of Methods in Psychiatric Research*, 30(1), e1861. <https://doi.org/10.1002/mpr.1861>. The study that gave Wordsum to these respondents.\n- Schwarz, G. (1978). Estimating the dimension of a model. *The Annals of Statistics*, 6(2), 461–464. <https://doi.org/10.1214/aos/1176344136>. The BIC.\n- Chalmers, R. P. (2012). mirt: A multidimensional item response theory package for the R environment. *Journal of Statistical Software*, 48(6). <https://doi.org/10.18637/jss.v048.i06>. `fscores()` computes every estimator in this lesson.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`c19prc_uk_mcbride_2021_wordsum`](https://itemresponsewarehouse.org/tables/c19prc_uk_mcbride_2021_wordsum/): Bentall, Richard and Shevlin, Mark and McBride, Orla and Murphy, Jamie and Hartman, Todd K and Levita, Liat and Gibson-Miller, Jilly and Mason, Liam and Bennett, Kate (2022). The COVID-19 Psychological Research Consortium Study, 2020-2021. [Data Collection]. Colchester, Essex: UK Data Service. 10.5255/UKDA-SN-855552. <https://osf.io/v2zur/>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 4 (slides c4, 44–48) and class 5 (slides c5, 64–66), problem sets 3 (#2), 4 (#1) and 5 (#2), and the code in `ben-domingue/252`: `ps3/1_abilities.R`, `ps5/eap_versus_mle.R`.\n- **Timing:** the core ideas and widgets take about 60 minutes; the Wordsum analysis works as a 25-minute lab. Every fit takes a few seconds in local R.\n- **Changed from 252:** the 252 code finds the MLE with `optim()` on a bounded interval, which returns the bound for a perfect pattern; the simulation here solves the score equation, counts the perfect patterns, and adds the WLE, the MAP and a group difference to PS5#2's comparison of MLE and EAP. The real data (Wordsum) are new.\n- **Held back:** where the item parameters come from, and the EAP's nodes and weights as the E step of EM ([Estimating item parameters](item-estimation.qmd)); EAP in adaptive testing ([Item banks and adaptive testing](item-banks-cat.qmd)); priors on item parameters ([Guessing and priors](guessing-priors.qmd)); plausible values in full, and which estimate to put on a reported score scale ([What does a score mean?](score-meaning.qmd)). Out-of-sample prediction with MLE and EAP abilities (PS5#2b) is left as an extension of problem 5.\n- **Solutions:** held back in `solutions/ability-estimation.qmd` (not published).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}