{
  "hash": "23ce72b8c92bcb12de5fb12db40e6517",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Structural equation modeling with lavaan\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Factor analysis  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [Factor analysis II: confirmatory models, omega, and IRT as factor analysis](fa-confirmatory.qmd)  \n**Builds toward:** none  \n**Picks up threads:** Unreliability attenuates correlations (from [Classical test theory and reliability](ctt-reliability.qmd)); Comparing group means needs scalar invariance (from [Factor analysis II: confirmatory models, omega, and IRT as factor analysis](fa-confirmatory.qmd))  \n**IRW tables:** [`florida_twins_grit`](https://itemresponsewarehouse.org/tables/florida_twins_grit/), [`florida_twins_panas`](https://itemresponsewarehouse.org/tables/florida_twins_panas/)  \n**From EDUC 252:** n/a  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\nsuppressWarnings(webr::install(\"lavaan\", quiet = TRUE))\noptions(mc.cores = 1)\n# webR can't count CPU cores (detectCores() is NA), and lavaan's option checks then\n# never finish; report one core. Not needed in local R.\nlocal({\n  ns <- asNamespace(\"parallel\")\n  unlockBinding(\"detectCores\", ns)\n  assign(\"detectCores\", function(...) 1L, envir = ns)\n  lockBinding(\"detectCores\", ns)\n})\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {palette} from \"./widgets/irt.js\"\nimport {observedPaths, pathModel, structuralDf} from \"./widgets/sem.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nDoes grit go with feeling good? A regression of one sum score on another answers a smaller question than it seems to: it relates two error-laden measures, and error shrinks and shuffles the coefficients. [Factor analysis II](fa-confirmatory.qmd) modelled each construct as a factor behind its items. A **structural equation model** (SEM) keeps those factors and adds regressions between them, so the relations are estimated between the constructs rather than between their scores ([Jöreskog, 1970](https://doi.org/10.1002/j.2333-8504.1970.tb00783.x); [Bollen, 1989](https://doi.org/10.1002/9781118619179)). That buys a correction for measurement error, and it costs assumptions: a measurement model that must be right before the paths mean anything, and paths that look causal whether or not they are. We use the Grit-O and the PANAS, answered by the same children and adolescents in the Florida Twin Project.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- say what the measurement and structural parts of an SEM are, and write both in `lavaan` syntax;\n- explain how measurement error biases regressions on sum scores, including with two correlated predictors, and why a latent regression doesn't carry that bias when its model holds;\n- check by counting whether a structural model can be identified, and say which part of the model a fit index describes;\n- fit and inspect a measurement model before the structural one, and compare latent paths with sum-score regressions on real data;\n- say why a well-fitting path model is not evidence for its causal direction, and write down an equivalent model.\n\n## Core ideas\n\n### A measurement model and a structural model\n\nAn SEM has two parts. The **measurement model** is a confirmatory factor model: each factor $\\eta$ is measured by its items, $x_i = \\nu_i + \\lambda_i \\eta + \\varepsilon_i$. The **structural model** relates the factors to each other with regressions,\n$$\\eta_{\\text{outcome}} = \\beta_1 \\eta_1 + \\beta_2 \\eta_2 + \\zeta,$$\nwhere $\\zeta$ is the part of the outcome the predictors leave unexplained. Path analysis, regressions among observed variables drawn as arrows, goes back to [Wright (1934)](https://doi.org/10.1214/aoms/1177732676); [Jöreskog (1970)](https://doi.org/10.1002/j.2333-8504.1970.tb00783.x) joined it to the factor model and fitted both by maximum likelihood.\n\nOur model has four factors: two facets of grit (perseverance of effort, consistency of interest) and two kinds of affect (positive, negative). The question is how the grit facets relate to affect, with each construct measured by its items.\n\n### Why a latent path differs from a regression on sum scores\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd), problem 2: a correlation between two error-laden scores is attenuated, $\\text{cor}(X, Y) = \\text{cor}(T_X, T_Y)\\sqrt{\\rho_{XX'}\\,\\rho_{YY'}}$ ([Spearman, 1904](https://doi.org/10.2307/1412159)). If you've done [Gathering validity evidence](validity-evidence.qmd), you corrected validity coefficients for it by dividing by that square root.\n:::\n\nWith one predictor, the standardized regression slope is the correlation, so it shrinks by the same factor. Error in the outcome and error in the predictor act differently on the unstandardized slope, though: error in $Y$ adds noise around the line without tilting it, while error in $X$ flattens it by the factor $\\rho_{XX'}$ (problem 1).\n\nWith two correlated predictors the damage is no longer a simple shrinkage. Controlling for a predictor measured with error controls for it only in part, so what is left of it leaks into the other predictor's coefficient ([Cole & Preacher, 2014](https://doi.org/10.1037/a0033805); [Westfall & Yarkoni, 2016](https://doi.org/10.1371/journal.pone.0152719)). An SEM avoids both problems when its model holds: the paths run between the factors, which carry no measurement error, and the correction for attenuation is built into the model rather than applied by hand. A regression on sum scores remains a reasonable choice when the scores are highly reliable, or when the score itself, not the construct, is what will be used, as with a cut score.\n\n#### Try it: two predictors, measured with error\n\nSet the true standardized paths from two latent predictors to a latent outcome, and the reliability of the sum score that measures each. The bars compare the true paths with the standardized coefficients of the regression on sum scores.\n\n```{ojs}\n//| echo: false\nviewof at_b1 = Inputs.range([0, 0.7], {value: 0.5, step: 0.05, label: \"True path, predictor 1\"})\nviewof at_b2 = Inputs.range([-0.4, 0.4], {value: 0, step: 0.05, label: \"True path, predictor 2\"})\nviewof at_phi = Inputs.range([0, 0.8], {value: 0.5, step: 0.05, label: \"Correlation of the predictors\"})\nviewof at_r1 = Inputs.range([0.3, 1], {value: 0.7, step: 0.05, label: \"Reliability, predictor 1\"})\nviewof at_r2 = Inputs.range([0.3, 1], {value: 0.7, step: 0.05, label: \"Reliability, predictor 2\"})\nviewof at_ry = Inputs.range([0.3, 1], {value: 1, step: 0.05, label: \"Reliability, outcome\"})\n```\n\n```{ojs}\n//| echo: false\nat = observedPaths(at_b1, at_b2, at_phi, at_r1, at_r2, at_ry)\nat_rows = at === null ? [] : [\n  {p: \"Predictor 1\", k: \"True (latent) path\", v: at_b1}, {p: \"Predictor 1\", k: \"Sum-score regression\", v: at.b1},\n  {p: \"Predictor 2\", k: \"True (latent) path\", v: at_b2}, {p: \"Predictor 2\", k: \"Sum-score regression\", v: at.b2}]\nat === null ? md`*These paths explain more than all of the outcome's variance at this correlation; lower one of them.*` :\nPlot.plot({\n  width: 600, height: 230, marginLeft: 150, x: {domain: [-0.5, 0.8], label: \"Standardized coefficient\", grid: true},\n  y: {label: null, axis: null}, fy: {label: null},\n  color: {legend: true, domain: [\"True (latent) path\", \"Sum-score regression\"], range: [palette.main, palette.contrast]},\n  marks: [Plot.ruleX([0], {stroke: palette.rule}),\n          Plot.barX(at_rows, {fy: \"p\", y: \"k\", x: \"v\", fill: \"k\"}),\n          Plot.text(at_rows.filter(d => d.v >= 0), {fy: \"p\", y: \"k\", x: \"v\", text: d => d.v.toFixed(2), textAnchor: \"start\", dx: 4}),\n          Plot.text(at_rows.filter(d => d.v < 0), {fy: \"p\", y: \"k\", x: \"v\", text: d => d.v.toFixed(2), textAnchor: \"end\", dx: -4})]\n})\n```\n\nAt the start, predictor 2 has no effect at all, yet its sum score gets a coefficient of 0.07, and predictor 1's path of 0.5 comes out at 0.39. Lower predictor 1's reliability to 0.5 and predictor 2's spurious coefficient doubles, to 0.14: the less well predictor 1 is measured, the more of it predictor 2 absorbs. Set the correlation to 0 and the leak stops, leaving plain attenuation. Set every reliability to 1 and the bars agree whatever the paths.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A sum score for anxiety (reliability 0.7) predicts a perfectly measured outcome. Now the outcome is measured with error too, with reliability 0.7, and the predictor is unchanged. What happens to the *unstandardized* slope, in expectation?\",\n  options: [\n    {text: \"Nothing: error in the outcome widens the scatter around the line but doesn't tilt it\", correct: true, why: \"The outcome's error is uncorrelated with the predictor, so it adds to the residual variance only. The standardized slope, a correlation here, does shrink, by a factor of $\\\\sqrt{0.7}$.\"},\n    {text: \"It shrinks by the factor 0.7\", correct: false, why: \"That is what error in the *predictor* does to the slope. Error in the outcome leaves it unbiased.\"},\n    {text: \"It shrinks by a factor of $\\\\sqrt{0.7}$\", correct: false, why: \"That is the shrinkage of the correlation (and the standardized slope), which divides by the outcome's inflated SD. The unstandardized slope is unbiased.\"}\n  ]\n})\n```\n\n### Specifying the model in lavaan\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Factor analysis II](fa-confirmatory.qmd): in `lavaan` ([Rosseel, 2012](https://doi.org/10.18637/jss.v048.i02)), `=~` reads \"is measured by\", and each factor's scale is set by fixing one loading or its variance. The degrees of freedom are the variances and covariances the data supply minus the parameters the model spends.\n:::\n\nTwo more operators finish the language: `~` reads \"is regressed on\", and `~~` declares a variance or covariance. The structural part of our model is two lines added under the four `=~` lines:\n\n```r\nmodel <- \"per =~ g1 + g4 + g6 + g9 + g10 + g12\n          con =~ g2 + g3 + g5 + g7 + g8 + g11\n          pa  =~ p1 + p3 + p5 + p9 + p10 + p12 + p14 + p16 + p17 + p19\n          na  =~ p2 + p4 + p6 + p7 + p8 + p11 + p13 + p15 + p18 + p20\n          pa ~ per + con\n          na ~ per + con\"\nfit <- sem(model, data = d, estimator = \"MLR\")\n```\n\n`sem()` lets the two predictors correlate and, by default, lets the two outcomes' residuals $\\zeta$ correlate too.\n\nCan the structural part be identified? The measurement model already estimates the six correlations among four factors. The structural model re-expresses them with the predictors' correlation, the paths and any residual covariance. With more than six such parameters, some can't be recovered from the data. Counting is necessary but not sufficient for identification ([Bollen, 1989](https://doi.org/10.1002/9781118619179)).\n\nThe estimator matters as it did in CFA. Maximum likelihood assumes multivariate normal items. **MLR** keeps the ML estimates and makes the standard errors and the test statistic robust to non-normality ([Yuan & Bentler, 2000](https://doi.org/10.1111/0081-1750.00078)); **WLSMV** treats items as ordered categories and suits items with few or skewed categories ([Rhemtulla, Brosseau-Liard & Savalei, 2012](https://doi.org/10.1037/a0029315)).\n\n#### Try it: build the structural model\n\nChoose the paths. The widget draws them, writes the `lavaan` lines (the measurement lines above stay the same) and counts the structural degrees of freedom.\n\n```{ojs}\n//| echo: false\nviewof sb_paths = Inputs.checkbox([\"pa ~ per\", \"pa ~ con\", \"na ~ per\", \"na ~ con\", \"na ~ pa\"], {value: [\"pa ~ per\", \"pa ~ con\", \"na ~ per\", \"na ~ con\"], label: \"Paths\"})\nviewof sb_cov = Inputs.toggle({label: \"Outcome residuals correlate (pa ~~ na)\", value: true})\n```\n\n```{ojs}\n//| echo: false\nsb = {\n  const has = p => sb_paths.includes(p);\n  const line = y => {\n    const cand = y === \"pa\" ? [\"per\", \"con\"] : [\"per\", \"con\", \"pa\"];\n    const terms = cand.filter(x => has(`${y} ~ ${x}`)).concat(cand.filter(x => x !== \"pa\" && !has(`${y} ~ ${x}`)).map(x => `0*${x}`));\n    return `${y} ~ ${terms.join(\" + \")}`;\n  };\n  const lines = [line(\"pa\"), line(\"na\"), sb_cov ? \"pa ~~ na\" : \"pa ~~ 0*na\"];\n  return {syntax: lines.join(\"\\n\"), df: structuralDf(sb_paths.length, sb_cov)};\n}\nsb_svg = {\n  const pos = {per: [90, 50], con: [90, 190], pa: [390, 50], na: [390, 190]};\n  const r = 30;\n  const arrow = (a, b) => {\n    const [x1, y1] = pos[a], [x2, y2] = pos[b], L = Math.hypot(x2 - x1, y2 - y1), ux = (x2 - x1) / L, uy = (y2 - y1) / L;\n    return htl.svg`<line x1=${x1 + ux * r} y1=${y1 + uy * r} x2=${x2 - ux * (r + 6)} y2=${y2 - uy * (r + 6)} stroke=${palette.main} stroke-width=\"2.5\" marker-end=\"url(#sb-head)\"/>`;\n  };\n  const arcs = [htl.svg`<path d=\"M 62 64 Q 10 120 62 176\" fill=\"none\" stroke=${palette.guide} stroke-width=\"2\" stroke-dasharray=\"5,3\"/>`];\n  if (sb_cov) arcs.push(htl.svg`<path d=\"M 418 64 Q 470 120 418 176\" fill=\"none\" stroke=${palette.contrast} stroke-width=\"2\" stroke-dasharray=\"5,3\"/>`);\n  const ps = sb_paths.map(p => { const [y, x] = p.split(\" ~ \"); return arrow(x, y); });\n  return htl.svg`<svg width=\"480\" height=\"240\" viewBox=\"0 0 480 240\" style=\"max-width:100%;height:auto\">\n    <defs><marker id=\"sb-head\" viewBox=\"0 0 10 10\" refX=\"5\" refY=\"5\" markerWidth=\"6\" markerHeight=\"6\" orient=\"auto-start-reverse\"><path d=\"M0,0 L10,5 L0,10 z\" fill=${palette.main}/></marker></defs>\n    ${arcs}${ps}\n    ${Object.entries(pos).map(([k, [x, y]]) => htl.svg`<circle cx=${x} cy=${y} r=${r} fill=${palette.white} stroke=${palette.ink} stroke-width=\"1.5\"/><text x=${x} y=${y + 5} text-anchor=\"middle\" font-size=\"15\" fill=${palette.ink}>${k}</text>`)}\n  </svg>`;\n}\n```\n\n```{ojs}\n//| echo: false\nhtml`<pre style=\"margin:0.4rem 0\">${sb.syntax}</pre>`\n```\n\n```{ojs}\n//| echo: false\nmd`Structural parameters: **${6 - sb.df}** in place of the 6 factor correlations · structural degrees of freedom: **${sb.df}**${sb.df < 0 ? \". **Not identified**: more parameters than the correlations can pin down.\" : sb.df === 0 ? \". The structural part is saturated: it reproduces the factor correlations exactly, so any misfit belongs to the measurement model.\" : `. The structural part makes ${sb.df} testable claim${sb.df > 1 ? \"s\" : \"\"}: each path left out is fixed at zero.`}`\n```\n\nDashed curves are correlations: grey between the predictors, orange between the outcomes' residuals. With all four paths and the residual covariance, the count is 0: the structural model is only a new way of writing the six factor correlations, and it fits exactly as well as the measurement model alone. Drop \"pa ~ con\" and a structural claim appears that the data can test. Add \"na ~ pa\" with everything else on and the count goes to −1: the direct path and the residual covariance can't both be recovered.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"You fit the four-factor measurement model and get CFI 0.84 and RMSEA 0.059. You then fit the SEM with the four paths above and correlated outcome residuals. What will its CFI and RMSEA be?\",\n  options: [\n    {text: \"Exactly the same\", correct: true, why: \"The structural part has 0 degrees of freedom: it reproduces the six factor correlations exactly, so the SEM and the measurement model imply the same covariance matrix.\"},\n    {text: \"Better, because the paths explain the outcomes\", correct: false, why: \"Explaining the outcomes' variance ($R^2$) is not fit. The saturated structural part can't bring the implied covariances any closer to the data than the correlated factors already did.\"},\n    {text: \"Worse, because the regressions add constraints\", correct: false, why: \"They add none here: 1 correlation + 4 paths + 1 residual covariance = 6, the number of factor correlations they replace.\"}\n  ]\n})\n```\n\n### Fit, and fit of which part\n\nA global fit index compares the whole implied covariance matrix with the data. In an SEM most of that matrix is the measurement model: in ours, 32 items supply 528 variances and covariances, and the structural claims concern at most six factor correlations. Misfit among the items can swamp the structure, and a structural part with few degrees of freedom of its own can be wrong without the global indices showing it. [Anderson and Gerbing (1988)](https://doi.org/10.1037/0033-2909.103.3.411) proposed two steps: fit the measurement model alone, with every factor correlated, and settle it; then fit the structural model and test its constraints against the measurement model. The cutoffs of [Hu and Bentler (1999)](https://doi.org/10.1080/10705519909540118) come from simulations of factor models, and a structural model inherits whatever misfit its measurement model carries.\n\nFitting everything in one step gives the same estimates. It is a reasonable choice when the measurement model is well established in similar samples; what it can't do is say which part a misfit belongs to.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Factor analysis II](fa-confirmatory.qmd): fit indices say how far off a model is, and the residuals and modification indices show where. [Zhang et al. (2026)](https://doi.org/10.1080/00273171.2026.2645212) add prediction on held-out respondents, measured by the IMV, as a complement to fit for CFA with binary items.\n:::\n\nSo which comes first? I fit and inspect the measurement model before I read a single structural path. A path between factors that the items don't measure well is an estimate of something, but not of the relation the diagram names, and the structural fit indices won't say so.\n\n**Factors or composites?** Everything here models a construct as a common factor, the source of what its items share. Composite-based SEM (partial least squares, consistent PLS, generalized structured component analysis) models a construct as a weighted sum of its items instead. It is a different model with different assumptions, and a reasonable choice when a construct is defined by its indicators, as an index of socioeconomic status is. In R it is fitted by `cSEM` ([Rademaker & Schuberth, 2020](https://doi.org/10.32614/cran.package.csem); on the model, [Schuberth, Henseler & Dijkstra, 2018](https://doi.org/10.3389/fpsyg.2018.02541)), and in jamovi by the [Composite-SEM module](https://github.com/AbdullahAlarfaj101/Composite-SEM), a small project without a licence file as of September 2026. For point-and-click factor-based SEM, jamovi's [SEMLj](https://semlj.github.io/) module builds `lavaan` models from menus.\n\n### What a path can't tell you\n\nAn arrow in a path diagram is a regression coefficient. Whether it is a causal effect depends on assumptions the fit doesn't test: no omitted common causes, the right direction, and a design that supports both ([Bollen & Pearl, 2013](https://doi.org/10.1007/978-94-007-6094-3_15)). And for most models there are **equivalent models**, with different arrows, that imply exactly the same covariance matrix and so fit identically on any data ([MacCallum, Wegener, Uchino & Fabrigar, 1993](https://doi.org/10.1037/0033-2909.114.1.185)).\n\n#### Try it: reverse an arrow\n\nThree observed, standardized variables with the correlations you set, and 500 respondents. Each model leaves out one link and so makes one testable claim (1 degree of freedom).\n\n```{ojs}\n//| echo: false\nviewof eq_xm = Inputs.range([-0.8, 0.8], {value: 0.5, step: 0.05, label: \"Correlation X–M\"})\nviewof eq_my = Inputs.range([-0.8, 0.8], {value: 0.4, step: 0.05, label: \"Correlation M–Y\"})\nviewof eq_xy = Inputs.range([-0.8, 0.8], {value: 0.3, step: 0.05, label: \"Correlation X–Y\"})\nviewof eq_m = Inputs.radio(new Map([[\"X → M → Y\", \"chain\"], [\"Y → M → X\", \"reverse\"], [\"X ← M → Y\", \"fork\"], [\"X → M ← Y (X, Y independent)\", \"collider\"]]), {value: \"chain\", label: \"Model\"})\n```\n\n```{ojs}\n//| echo: false\neq = pathModel(eq_xm, eq_my, eq_xy, eq_m, 500)\neq_svg = {\n  const pos = {X: 70, M: 240, Y: 410}, r = 26;\n  const dir = {chain: [[\"X\", \"M\"], [\"M\", \"Y\"]], reverse: [[\"Y\", \"M\"], [\"M\", \"X\"]], fork: [[\"M\", \"X\"], [\"M\", \"Y\"]], collider: [[\"X\", \"M\"], [\"Y\", \"M\"]]}[eq_m];\n  const arr = ([a, b]) => { const x1 = pos[a], x2 = pos[b], s = Math.sign(x2 - x1);\n    return htl.svg`<line x1=${x1 + s * r} y1=\"50\" x2=${x2 - s * (r + 6)} y2=\"50\" stroke=${palette.main} stroke-width=\"2.5\" marker-end=\"url(#eq-head)\"/>`; };\n  return htl.svg`<svg width=\"480\" height=\"100\" viewBox=\"0 0 480 100\" style=\"max-width:100%;height:auto\">\n    <defs><marker id=\"eq-head\" viewBox=\"0 0 10 10\" refX=\"5\" refY=\"5\" markerWidth=\"6\" markerHeight=\"6\" orient=\"auto-start-reverse\"><path d=\"M0,0 L10,5 L0,10 z\" fill=${palette.main}/></marker></defs>\n    ${dir.map(arr)}\n    ${Object.entries(pos).map(([k, x]) => htl.svg`<rect x=${x - r} y=${50 - r} width=${2 * r} height=${2 * r} fill=${palette.white} stroke=${palette.ink} stroke-width=\"1.5\"/><text x=${x} y=\"55\" text-anchor=\"middle\" font-size=\"16\" fill=${palette.ink}>${k}</text>`)}\n  </svg>`;\n}\n```\n\n```{ojs}\n//| echo: false\neq === null ? md`*These three correlations can't occur together; move one.*` :\nmd`χ² = **${eq.chisq.toFixed(1)}** on 1 df · implied correlation X–Y: **${eq.implied.toFixed(2)}** (observed ${eq_xy.toFixed(2)}) · paths: ${eq_m === \"collider\" ? `X → M **${eq.paths.XM.toFixed(2)}**, Y → M **${eq.paths.YM.toFixed(2)}**` : `between X and M **${eq.paths.XM.toFixed(2)}**, between M and Y **${eq.paths.MY.toFixed(2)}**`}`\n```\n\nThe chain, the reversed chain and the fork all give χ² = 8.0 on 1 df, and they stay equal wherever the sliders sit: each says only that X and Y are unrelated given M. Set the X–Y correlation to 0.20, the product of the other two, and all three fit perfectly. They tell three causal stories (M a mediator one way, M a mediator the other way, M a common cause) that no amount of data of this kind can separate. The collider claims instead that X and Y are unrelated, and its χ² of 47.2 differs.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"An SEM with grit → positive affect fits well. A colleague fits positive affect → grit, with the measurement model the same and no other paths into either factor. What do you expect?\",\n  options: [\n    {text: \"The same fit: the two models are equivalent\", correct: true, why: \"Both let the two factors covary through one free coefficient, so they imply the same covariance matrix. Only design or theory can choose between them.\"},\n    {text: \"Worse fit, because grit is the more stable trait\", correct: false, why: \"Stability is an argument about design, not about fit. The data give both models the same χ².\"},\n    {text: \"Better fit, because affect has more reliable items\", correct: false, why: \"Reliability belongs to the measurement model, which is the same in both. The structural parts are equivalent.\"}\n  ]\n})\n```\n\n## Simulate\n\nThe code simulates a latent predictor and a latent outcome with a standardized path of 0.5, each measured by five items, at three levels of item quality. For each it compares the correlation of the sum scores (the standardized slope of a one-predictor regression), Spearman's prediction of it, and the path from `sem()`. The first run takes 20–30 seconds while `lavaan` loads.\n\nWith the seed as written, the sum-score slope falls from 0.45 to 0.24 as the loadings drop from 0.8 to 0.4, within 0.01 of Spearman's prediction each time, while the SEM path stays between 0.50 and 0.56. The SEM estimate is unbiased, not free: with loadings of 0.4 it moves more from sample to sample. Change the seed, or set `np <- 200`, to see how much; with `np <- 5000` (locally) it settles near 0.5.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-16\n# Simulate a latent predictor X and a latent outcome Y with a known standardized\n# path, each measured by five items with error. Compare the regression on sum\n# scores with the SEM estimate of the path, at three levels of item quality.\n# Needs the lavaan package.\nlibrary(lavaan)\nset.seed(64)\nnp    <- 500                  # respondents (try 200, or 5000 locally)\nbeta  <- 0.5                  # true standardized path from X to Y\nloads <- c(0.4, 0.6, 0.8)     # one loading for every item, per scenario\nk     <- 5                    # items per factor\n\nmodel <- \"X =~ x1 + x2 + x3 + x4 + x5\n          Y =~ y1 + y2 + y3 + y4 + y5\n          Y ~ X\"\nrows <- lapply(loads, function(l) {\n  X <- rnorm(np)\n  Y <- beta * X + sqrt(1 - beta^2) * rnorm(np)\n  items <- function(eta, name) {\n    m <- sapply(1:k, function(i) l * eta + sqrt(1 - l^2) * rnorm(np))\n    colnames(m) <- paste0(name, 1:k); m\n  }\n  dat <- as.data.frame(cbind(items(X, \"x\"), items(Y, \"y\")))\n  sx <- rowSums(dat[1:k]); sy <- rowSums(dat[k + 1:k])\n  fit <- sem(model, data = dat, std.lv = TRUE)\n  ss <- standardizedSolution(fit)\n  # Reliability of a sum of k items with equal loadings l (omega = alpha here).\n  rel <- (k * l)^2 / ((k * l)^2 + k * (1 - l^2))\n  data.frame(loading = l, reliability = round(rel, 2), true_path = beta,\n             sum_score_slope = round(cor(sx, sy), 2),       # standardized slope = correlation\n             predicted_by_spearman = round(beta * rel, 2),  # beta * sqrt(rel_x * rel_y)\n             sem_path = round(ss$est.std[ss$op == \"~\"], 2))\n})\nprint(do.call(rbind, rows))\n\n```\n:::\n\n\n[Download this code](code/sem-sim.R).\n\n## With real data\n\n\n\n### Two tables from one study\n\nThe Florida Twin Project on Reading, Behavior, and Environment surveyed twins in Florida over three waves ([Hart, Schatschneider & Taylor, 2021](https://doi.org/10.33009/ldbase.1624481381.d9ec); on the project, [Hart et al., 2013](https://doi.org/10.1037/a0031348)). Our tables are [florida_twins_grit](https://itemresponsewarehouse.org/tables/florida_twins_grit/), the 12-item Grit-O ([Duckworth, Peterson, Matthews & Kelly, 2007](https://doi.org/10.1037/0022-3514.92.6.1087)), and [florida_twins_panas](https://itemresponsewarehouse.org/tables/florida_twins_panas/), the 20-item PANAS ([Watson, Clark & Tellegen, 1988](https://doi.org/10.1037/0022-3514.54.6.1063)): ten adjectives for positive affect and ten for negative, each rated from 1 (very slightly or not at all) to 5 (extremely) for how the respondent feels in general. They are one data source, joined by respondent, with one job: grit supplies the predictors and affect the outcomes of the structural model. [Download the code](code/sem-irw.R) to run every chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(lavaan)\n# Each IRW table has a landing page (itemresponsewarehouse.org/tables/<name>/)\n# with a CSV download. These links are pinned to one version of the data.\nbase <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.\"\ngrit_long  <- read.csv(paste0(base, \"florida_twins_grit/rows?format=csv\"))\npanas_long <- read.csv(paste0(base, \"florida_twins_panas/rows?format=csv\"))\ntable(grit = grit_long$wave[!duplicated(grit_long$id)])     # grit was asked in wave 2 only\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngrit\n  2 \n782 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npanas_long <- panas_long[panas_long$wave == 2, ]            # so we use PANAS from wave 2\n\nwide <- function(df, items) {\n  w <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\n  as.data.frame(w[, items])\n}\ngrit  <- wide(grit_long, paste0(\"qgrit\", 1:12));      names(grit)  <- paste0(\"g\", 1:12)\npanas <- wide(panas_long, paste0(\"panas\", 1:20, \"t\")); names(panas) <- paste0(\"p\", 1:20)\n\n# Keying. Grit runs 1 = \"Very much like me\" to 5 = \"Not like me at all\" (the IRW's\n# option text). The consistency-of-interest items are worded against grit (\"My\n# interests change...\"), so \"not like me\" already means more grit; the six\n# perseverance items are reversed. Higher = more grit on every item.\nper <- paste0(\"g\", c(1, 4, 6, 9, 10, 12))   # perseverance of effort\ncon <- paste0(\"g\", c(2, 3, 5, 7, 8, 11))    # consistency of interest\ngrit[per] <- 6 - grit[per]\n# PANAS: 1 = \"very slightly or not at all\" to 5 = \"extremely\"; no keying needed.\n# Scales as in Watson, Clark & Tellegen (1988).\npa <- paste0(\"p\", c(1, 3, 5, 9, 10, 12, 14, 16, 17, 19))   # positive affect\nna <- paste0(\"p\", c(2, 4, 6, 7, 8, 11, 13, 15, 18, 20))    # negative affect\n\nd <- merge(grit, panas, by = \"row.names\")\nd$id <- as.numeric(d$Row.names)\n# Twins: IRW ids come in pairs ending 00 and 01 (31700, 31701), so id %/% 100 is\n# the family. Inferred from the id pattern, not from a codebook.\nd$family <- d$id %/% 100\nd$age <- tapply(grit_long$cov_age, grit_long$id, function(x) x[1])[as.character(d$id)]\nc(both_tables = nrow(d), complete = sum(complete.cases(d[c(per, con, pa, na)])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nboth_tables    complete \n        778         618 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nd <- d[complete.cases(d[c(per, con, pa, na)]), ]\ntable(twins_in_family = table(d$family))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntwins_in_family\n  1   2 \n110 254 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nr <- cor(d[c(per, con)])\nround(r[per, c(\"g3\", \"g11\")], 2)   # the two items that don't line up with the rest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       g3   g11\ng1  -0.06 -0.21\ng4  -0.10 -0.07\ng6  -0.05 -0.18\ng9  -0.02 -0.19\ng10 -0.01 -0.33\ng12  0.00 -0.25\n```\n\n\n:::\n:::\n\n\nGrit was asked in wave 2 only, so we use the wave-2 PANAS. The grit items run from 1 = \"Very much like me\" to 5 = \"Not like me at all\". The six consistency items are worded against grit, so their high end already means more grit, and we reverse the six perseverance items. (The Open Psychometrics `grit` table in [Factor analysis II](fa-confirmatory.qmd) arrives with its consistency items already reversed, so there all twelve are reversed; the result, higher = more grit, is the same.) After keying, two consistency items sit apart: item 11, on taking up new interests every few months, correlates negatively with every perseverance item, and item 3 barely correlates with them (−0.10 to 0.00). [Dimensionality and multidimensional IRT](dimensionality.qmd) meets item 11 again.\n\nTwins share a family, and the IRW ids come in pairs (31700 and 31701), so we take `id %/% 100` as the family. That is read off the pattern of the ids, not a codebook.\n\n### Step 1: the measurement model\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Step 1: the measurement model alone. Four factors, each item on one, all four\n# factors correlated. MLR: maximum likelihood with standard errors and a test\n# statistic that are robust to non-normal responses; cluster = \"family\" makes them\n# robust to twins' responses being correlated as well.\nmm <- paste0(\"per =~ \", paste(per, collapse = \" + \"), \"\\n\",\n             \"con =~ \", paste(con, collapse = \" + \"), \"\\n\",\n             \"pa  =~ \", paste(pa,  collapse = \" + \"), \"\\n\",\n             \"na  =~ \", paste(na,  collapse = \" + \"))\ncat(mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nper =~ g1 + g4 + g6 + g9 + g10 + g12\ncon =~ g2 + g3 + g5 + g7 + g8 + g11\npa  =~ p1 + p3 + p5 + p9 + p10 + p12 + p14 + p16 + p17 + p19\nna  =~ p2 + p4 + p6 + p7 + p8 + p11 + p13 + p15 + p18 + p20\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nm1 <- cfa(mm, data = d, estimator = \"MLR\", cluster = \"family\")\nidx <- c(\"chisq.scaled\", \"df\", \"cfi.robust\", \"rmsea.robust\", \"srmr\")\nround(fitMeasures(m1, idx), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchisq.scaled           df   cfi.robust rmsea.robust         srmr \n    1297.385      458.000        0.842        0.059        0.064 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(lavInspect(m1, \"cor.lv\"), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      per   con    pa    na\nper  1.00                  \ncon  0.36  1.00            \npa   0.65  0.23  1.00      \nna  -0.26 -0.33 -0.17  1.00\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nstd <- standardizedSolution(m1)\nstd <- std[std$op == \"=~\", ]\nround(tapply(std$est.std, std$lhs, range)[c(\"per\", \"con\", \"pa\", \"na\")] |> do.call(what = rbind), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    [,1] [,2]\nper 0.42 0.76\ncon 0.16 0.68\npa  0.43 0.73\nna  0.49 0.75\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nstd[std$est.std < 0.4, c(\"lhs\", \"rhs\", \"est.std\")]\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |lhs |rhs |  est.std|\n|:--|:---|:---|--------:|\n|8  |con |g3  | 0.346920|\n|12 |con |g11 | 0.156222|\n\n</div>\n:::\n:::\n\n\nThe fit is modest: CFI 0.842, short of the 0.95 that [Hu and Bentler (1999)](https://doi.org/10.1080/10705519909540118) found was needed, while RMSEA (0.059) and SRMR (0.064) are inside their cutoffs. The other loadings run from 0.42 to 0.76; consistency items 3 and 11 load 0.35 and 0.16.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Where does the measurement model strain? The largest modification indices: the\n# drop in chi-square if one fixed parameter were freed.\nmi <- modindices(m1, sort. = TRUE)\nhead(mi[, c(\"lhs\", \"op\", \"rhs\", \"mi\")], 6)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    |lhs |op |rhs |        mi|\n|:---|:---|:--|:---|---------:|\n|687 |p7  |~~ |p20 | 155.21223|\n|116 |per |=~ |g11 |  84.60861|\n|688 |p8  |~~ |p11 |  49.90510|\n|124 |per |=~ |p16 |  49.62030|\n|115 |per |=~ |g8  |  47.35594|\n|551 |p5  |~~ |p10 |  44.45408|\n\n</div>\n:::\n:::\n\n\nWhere is the misfit? The largest modification index is a shared error between PANAS items 7 and 20, *scared* and *afraid* ([Watson et al., 1988](https://doi.org/10.1037/0022-3514.54.6.1063)); items 8 and 11 (*hostile*, *irritable*) and 5 and 10 (*strong*, *proud*) follow. Next is item 11 loading on perseverance, negatively. The strain is among the items: adjectives that share meaning beyond their factor, and a grit item that relates to the other facet. None of it concerns the relations between the constructs, and I read the paths below with that in mind.\n\n### Step 2: the paths\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"The two grit facets correlate 0.36. Which will be the stronger predictor of positive affect, each controlling for the other?\",\n  choices: [\"Perseverance of effort\", \"Consistency of interest\", \"About equal\"],\n  answer: \"Perseverance of effort\",\n  reveal: \"Perseverance, with a standardized path of 0.66. Consistency adds nothing to positive affect once perseverance is in the model (−0.01), though it is the stronger predictor of *lower* negative affect.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Step 2: replace the four factor correlations with regressions. \"~\" reads \"is\n# regressed on\"; lavaan correlates the two outcomes' residuals by default.\nsm <- paste(mm, \"\n  pa ~ per + con\n  na ~ per + con\")\ns1 <- sem(sm, data = d, estimator = \"MLR\", cluster = \"family\")\nround(rbind(measurement = fitMeasures(m1, idx), structural = fitMeasures(s1, idx)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            chisq.scaled  df cfi.robust rmsea.robust  srmr\nmeasurement     1297.385 458      0.842        0.059 0.064\nstructural      1297.385 458      0.842        0.059 0.064\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npaths <- standardizedSolution(s1)\npaths <- paths[paths$op == \"~\", c(\"lhs\", \"rhs\", \"est.std\", \"se\", \"pvalue\")]\npaths$est.std <- round(paths$est.std, 2); paths$se <- round(paths$se, 3); paths$pvalue <- round(paths$pvalue, 3)\npaths\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |lhs |rhs | est.std|    se| pvalue|\n|:--|:---|:---|-------:|-----:|------:|\n|33 |pa  |per |    0.66| 0.064|  0.000|\n|34 |pa  |con |   -0.01| 0.065|  0.842|\n|35 |na  |per |   -0.16| 0.076|  0.032|\n|36 |na  |con |   -0.27| 0.072|  0.000|\n\n</div>\n:::\n:::\n\n\nThe fit is identical to the measurement model's, to the last digit: the structural part is saturated, as the builder widget said. Perseverance predicts positive affect strongly (0.66) and lower negative affect a little (−0.16); consistency predicts lower negative affect (−0.27) and nothing about positive affect (−0.01). In words: respondents who say they finish what they begin report feeling more interested, enthusiastic and alert, and those whose interests stay put report somewhat less distress.\n\n### What the sum scores would have said\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same regressions on mean scores, all standardized so the coefficients are on\n# the same footing as the standardized latent paths.\nalpha <- function(x) { k <- ncol(x); k / (k - 1) * (1 - sum(apply(x, 2, var)) / var(rowSums(x))) }\nround(c(per = alpha(d[per]), con = alpha(d[con]), pa = alpha(d[pa]), na = alpha(d[na])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n per  con   pa   na \n0.74 0.69 0.85 0.87 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsc <- as.data.frame(scale(sapply(list(per = per, con = con, pa = pa, na = na),\n                                 function(v) rowMeans(d[v]))))\nols <- rbind(coef(lm(pa ~ per + con, sc))[-1], coef(lm(na ~ per + con, sc))[-1])\ncbind(paths[, c(\"lhs\", \"rhs\")], sum_scores = round(as.vector(t(ols)), 2),\n      latent = paths$est.std)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |lhs |rhs | sum_scores| latent|\n|:--|:---|:---|----------:|------:|\n|33 |pa  |per |       0.51|   0.66|\n|34 |pa  |con |       0.03|  -0.01|\n|35 |na  |per |      -0.18|  -0.16|\n|36 |na  |con |      -0.24|  -0.27|\n\n</div>\n:::\n:::\n\n\nWith alphas from 0.69 to 0.87, the sum-score regression puts perseverance's path to positive affect at 0.51, against 0.66 between the factors. The small paths move less, and not all toward zero: perseverance's path to negative affect is −0.18 on sum scores and −0.16 between factors, the leak the first widget showed. Set the widget to these values (paths 0.66 and 0, correlation 0.36, reliabilities 0.74, 0.69 and 0.85) and it gives 0.51 and 0.04, against the 0.51 and 0.03 printed here.\n\n### Twins, and ordered categories\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# What the family clustering does to the standard errors of the paths (unstandardized).\ns0 <- sem(sm, data = d, estimator = \"MLR\")\npe1 <- parameterEstimates(s1); pe0 <- parameterEstimates(s0)\ndata.frame(pe1[pe1$op == \"~\", c(\"lhs\", \"rhs\")], est = round(pe1$est[pe1$op == \"~\"], 2),\n           se_ignoring_families = round(pe0$se[pe0$op == \"~\"], 3),\n           se_clustered = round(pe1$se[pe1$op == \"~\"], 3))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |lhs |rhs |   est| se_ignoring_families| se_clustered|\n|:--|:---|:---|-----:|--------------------:|------------:|\n|33 |pa  |per |  0.72|                0.109|        0.113|\n|34 |pa  |con | -0.01|                0.052|        0.053|\n|35 |na  |per | -0.25|                0.115|        0.119|\n|36 |na  |con | -0.30|                0.086|        0.087|\n\n</div>\n:::\n:::\n\n\nIgnoring the families understates the standard errors, but only slightly here: 0.109 against 0.113 for the largest path (problem 3).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# A check: the items as ordered categories (WLSMV, polychoric correlations).\n# Negative-affect items pile up at 1, which is where the two routes could part.\ntable(negative_affect = unlist(d[na]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnegative_affect\n   1    2    3    4    5 \n3114 1732  763  382  189 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ns_ord <- sem(sm, data = d, ordered = TRUE)\npo <- standardizedSolution(s_ord)\nround(setNames(po$est.std[po$op == \"~\"], paste(po$lhs, \"~\", po$rhs)[po$op == \"~\"]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npa ~ per pa ~ con na ~ per na ~ con \n    0.67    -0.03    -0.15    -0.27 \n```\n\n\n:::\n:::\n\n\nThe negative-affect items are skewed (3,114 of the 6,180 responses are 1), so we refit with the items as ordered categories. The paths barely move (0.67, −0.03, −0.15, −0.27).\n\n### Children and adolescents\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Factor analysis II](fa-confirmatory.qmd): comparing factor correlations or regressions across groups needs metric invariance (equal loadings), and comparing means needs scalar invariance.\n:::\n\nDo the paths hold for children aged 9–13 and adolescents aged 14–18? A **multigroup SEM** fits the model in both groups at once and adds constraints: first on the loadings, then on the paths.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Does the structural model hold for children and for adolescents? Multigroup SEM:\n# configural (same model in both), metric (loadings equal), then the four paths equal.\nd$ages <- ifelse(d$age < 14, \"9-13\", \"14-18\")\ntable(d$ages, useNA = \"ifany\")   # one respondent has no age and sits this out\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n14-18  9-13  <NA> \n  334   283     1 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ndg <- d[!is.na(d$ages), ]\ng_cfg <- sem(sm, data = dg, group = \"ages\", estimator = \"MLR\", cluster = \"family\")\ng_met <- sem(sm, data = dg, group = \"ages\", estimator = \"MLR\", cluster = \"family\",\n             group.equal = \"loadings\")\ng_pth <- sem(sm, data = dg, group = \"ages\", estimator = \"MLR\", cluster = \"family\",\n             group.equal = c(\"loadings\", \"regressions\"))\nround(rbind(configural = fitMeasures(g_cfg, idx), metric = fitMeasures(g_met, idx),\n            equal_paths = fitMeasures(g_pth, idx)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            chisq.scaled  df cfi.robust rmsea.robust  srmr\nconfigural      1856.982 916      0.833        0.062 0.073\nmetric          1920.782 944      0.825        0.062 0.078\nequal_paths     1920.164 948      0.826        0.062 0.079\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nlavTestLRT(g_cfg, g_met, g_pth)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |  Df|      AIC|      BIC|    Chisq| Chisq diff|     RMSEA| Df diff| Pr(>Chisq)|\n|:-----|---:|--------:|--------:|--------:|----------:|---------:|-------:|----------:|\n|g_cfg | 916| 53031.96| 53934.64| 2110.282|         NA|        NA|      NA|         NA|\n|g_met | 944| 53058.53| 53837.31| 2192.848|  62.881554| 0.0728168|      28|  0.0001723|\n|g_pth | 948| 53052.03| 53813.11| 2194.348|   1.060536| 0.0000000|       4|  0.9004820|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Which equal loading strains most? One score test per equality constraint.\nst <- lavTestScore(g_met)$uni\npt <- parTable(g_met)\nst$constraint <- sapply(st$lhs, function(l) with(pt[pt$plabel == l, ], paste(lhs, op, rhs)))\nst <- st[order(-st$X2), c(\"constraint\", \"X2\", \"df\", \"p.value\")]\nhead(st, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |constraint |        X2| df|   p.value|\n|:--|:----------|---------:|--:|---------:|\n|10 |con =~ g11 | 10.761952|  1| 0.0010361|\n|17 |pa =~ p16  |  8.831104|  1| 0.0029614|\n|28 |na =~ p20  |  6.461775|  1| 0.0110219|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The paths, by age group (unstandardized, under equal loadings).\npg <- parameterEstimates(g_met)\npg <- pg[pg$op == \"~\", ]\ndata.frame(path = paste(pg$lhs, \"~\", pg$rhs), ages = lavInspect(g_met, \"group.label\")[pg$group],\n           est = round(pg$est, 2), se = round(pg$se, 2))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|path     |ages  |   est|   se|\n|:--------|:-----|-----:|----:|\n|pa ~ per |14-18 |  0.70| 0.12|\n|pa ~ con |14-18 | -0.02| 0.07|\n|na ~ per |14-18 | -0.25| 0.15|\n|na ~ con |14-18 | -0.38| 0.12|\n|pa ~ per |9-13  |  0.72| 0.13|\n|pa ~ con |9-13  | -0.02| 0.08|\n|na ~ per |9-13  | -0.30| 0.15|\n|na ~ con |9-13  | -0.23| 0.11|\n\n</div>\n:::\n:::\n\n\nEqual loadings cost something by the test (a scaled Δχ² of 62.9 on 28 df, $p < 0.001$), though CFI moves only from 0.833 to 0.825, within the change of 0.01 that [Chen (2007)](https://doi.org/10.1080/10705510701301834) suggests tolerating. The loading under most strain is, again, item 11's. Given equal loadings, equal paths cost nothing (1.1 on 4 df, $p = 0.90$): perseverance predicts positive affect about as strongly at 14–18 as at 9–13 (0.70 and 0.72, unstandardized). That comparison rests on metric invariance, which holds approximately here, not exactly.\n\n## Problems\n\n1. **Attenuation of a slope.** Let $X = T_X + E_X$ and $Y = \\beta T_X + \\zeta + E_Y$, with each error uncorrelated with everything else. Show that the population slope of $Y$ on $X$ is $\\beta \\rho_{XX'}$ and that $E_Y$ doesn't bias it. Then find the standardized slope and compare it with Spearman's formula.\n2. **Factor scores, with a twist.** Refit the sum-score regressions with factor scores from the measurement model (`lavPredict(m1)`) in place of the sum scores. Are the paths closer to the latent ones or to the sum-score ones? Why doesn't using factor scores remove the bias, and which kind of factor score for the predictors and which for the outcome would ([Skrondal & Laake, 2001](https://doi.org/10.1007/bf02296196))?\n3. **Twins.** The participants come in pairs. What does clustering do to standard errors, and why did it do so little here? Compute the correlation of twins' sum scores within families. What would a model that used the pairing as information, rather than a nuisance, look like?\n4. **Design.** Draw an SEM for a question you care about, with at least two latent predictors and one latent outcome. Count its structural degrees of freedom. Which path would you most like to read causally, and what design would let you?\n5. **Mend the measurement model.** Free the error covariance between PANAS items 7 and 20 (and, if you like, 8 and 11). How much does fit improve, and do the structural paths change? Then drop items 3 and 11 from consistency of interest. Which change matters more for the paths, and which would you defend in a paper?\n6. **Challenge (open).** Write down a model equivalent to ours in which affect predicts grit, and one in which a third factor causes both. What evidence (waves, twins, an intervention) could separate them? The PANAS was asked in all three waves, grit in one; I don't know how far these data can go.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Structural%20equation%20modeling%20with%20lavaan%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20structural%20equation%20modeling%20with%20lavaan%3A%20measurement%20and%20structural%20models%2C%20why%20latent%20regressions%20differ%20from%20regressions%20on%20sum%20scores%20%28attenuation%2C%20and%20leakage%20between%20correlated%20predictors%20measured%20with%20error%29%2C%20lavaan%20syntax%20%28%3D~%2C%20~%2C%20~~%29%2C%20identification%20by%20counting%2C%20estimators%20%28MLR%2C%20WLSMV%29%2C%20the%20two-step%20approach%20to%20fit%20%28measurement%20model%20first%29%2C%20clustered%20data%2C%20multigroup%20SEM%2C%20equivalent%20models%20and%20causal%20interpretation%2C%20with%20grit%20and%20positive%20and%20negative%20affect%20in%20the%20Florida%20Twin%20Project%20as%20the%20example.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Bollen, K. A. (1989). *Structural equations with latent variables*. Wiley. <https://doi.org/10.1002/9781118619179>. The standard reference: the model, identification, estimation and fit.\n- Jöreskog, K. G. (1970). A general method for estimating a linear structural equation system. *ETS Research Bulletin Series*, 1970(2). <https://doi.org/10.1002/j.2333-8504.1970.tb00783.x>. Where factors and paths were first put together and fitted by maximum likelihood.\n- Rosseel, Y. (2012). lavaan: An R package for structural equation modeling. *Journal of Statistical Software*, 48(2). <https://doi.org/10.18637/jss.v048.i02>. The package; its [tutorial](https://lavaan.ugent.be/tutorial/) covers everything used here.\n- Anderson, J. C., & Gerbing, D. W. (1988). Structural equation modeling in practice: A review and recommended two-step approach. *Psychological Bulletin*, 103(3), 411–423. <https://doi.org/10.1037/0033-2909.103.3.411>. The case for fitting the measurement model first.\n- Cole, D. A., & Preacher, K. J. (2014). Manifest variable path analysis: Potentially serious and misleading consequences due to uncorrected measurement error. *Psychological Methods*, 19(2), 300–315. <https://doi.org/10.1037/a0033805>. What error does to path models on observed scores, in larger models than ours.\n- Westfall, J., & Yarkoni, T. (2016). Statistically controlling for confounding constructs is harder than you think. *PLOS ONE*, 11(3), e0152719. <https://doi.org/10.1371/journal.pone.0152719>. The leak in the first widget, and the false positives it produces.\n- MacCallum, R. C., Wegener, D. T., Uchino, B. N., & Fabrigar, L. R. (1993). The problem of equivalent models in applications of covariance structure analysis. *Psychological Bulletin*, 114(1), 185–199. <https://doi.org/10.1037/0033-2909.114.1.185>. Rules for generating equivalent models, and how many published models have them.\n- Bollen, K. A., & Pearl, J. (2013). Eight myths about causality and structural equation models. In S. L. Morgan (Ed.), *Handbook of causal analysis for social research* (pp. 301–328). Springer. <https://doi.org/10.1007/978-94-007-6094-3_15>. What the arrows in an SEM do and don't claim.\n- Muthén, B., & Satorra, A. (1995). Complex sample data in structural equation modeling. *Sociological Methodology*, 25, 267–316. <https://doi.org/10.2307/271070>. Standard errors for clustered samples, the idea behind `cluster =`.\n- Schuberth, F., Henseler, J., & Dijkstra, T. K. (2018). Confirmatory composite analysis. *Frontiers in Psychology*, 9, 2541. <https://doi.org/10.3389/fpsyg.2018.02541>. Composites as a model in their own right.\n- Zhang, L., Rahal, C., Kanopka, K., Ulitzsch, E., Zhang, Z., & Domingue, B. W. (2026). Evaluating model predictive performance in confirmatory factor analysis with binary outcomes using the InterModel Vigorish. *Multivariate Behavioral Research*, 61(5), 745–764. <https://doi.org/10.1080/00273171.2026.2645212>. Prediction as a complement to fit for the measurement model.\n- Muthén, B., & Asparouhov, T. (2016). Multidimensional, multilevel, and multi-timepoint item response modeling. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 527–539). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315374512>. The same ideas with item response models as the measurement model, including longitudinal ones.\n- Regressions of ability on covariates inside an item response model come up in [Explanatory item response models](explanatory-irt.qmd).\n- From the IRW: the [CFA walkthrough with lavaan](https://itemresponsewarehouse.org/vignettes/cfa.html), whose measurement models this lesson extends.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`florida_twins_grit`](https://itemresponsewarehouse.org/tables/florida_twins_grit/): Hart, S. A., Schatschneider, C., & Taylor, J. E. (2021). Wave 1, Wave 2, Wave 3 Child Survey Measures. LDbase. <https://doi.org/10.33009/ldbase.1624481381.d9ec>. Licence: CC BY 4.0.\n- [`florida_twins_panas`](https://itemresponsewarehouse.org/tables/florida_twins_panas/): Hart, S. A., Schatschneider, C., & Taylor, J. E. (2021). Wave 1, Wave 2, Wave 3 Child Survey Measures. LDbase. <https://doi.org/10.33009/ldbase.1624481381.d9ec>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** new material (Ben's suggestion, #64). EDUC 252 did not cover SEM; the IRW's lavaan CFA vignette was the starting point.\n- **Timing:** about 50 minutes for the core ideas and widgets; the real-data section is a 30-minute lab (each fit takes seconds locally, and the whole script about a minute).\n- **Placement:** an extension after [Factor analysis II](fa-confirmatory.qmd), which introduces `lavaan`, fit indices and multigroup invariance; this lesson adds `~`, `~~`, paths and the two-step approach.\n- **Held back:** longitudinal SEM (the Florida twins have three waves of PANAS; problem 6 points at it); twin models that use the pairs to separate genetic and environmental variance; mediation and indirect effects; latent interactions.\n- **Data:** grit and PANAS come from one study and count as one data source. Grit keying was checked against the IRW option text: the perseverance items are reversed and the consistency items are not, unlike the `grit` table in [Factor analysis II](fa-confirmatory.qmd). The family variable is inferred from the id pattern (ids in pairs ending 00 and 01), not from a codebook. The PANAS items are single adjectives from a published scale (Watson et al., 1988); the lesson names six of them. The grit items are described, not reproduced.\n- **Solutions:** held back in `solutions/sem.qmd` (not published).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}