{
  "hash": "12e710d741782b6a48b4b6c009e5244d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Process models for response time: drift diffusion and race models\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Beyond the standard models  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [Response time and the speed-accuracy tradeoff](response-time.qmd) · [From the 1PL to the 4PL](1pl-to-4pl.qmd)  \n**Builds toward:** none  \n**Picks up threads:** Errors are slower than correct responses, partly because of where errors happen (from [Item response data and the IRW](irw-data.qmd))  \n**IRW tables:** [`mturkddm_lexical`](https://itemresponsewarehouse.org/tables/mturkddm_lexical/), [`motion`](https://itemresponsewarehouse.org/tables/motion/), [`credentialform_lnirt`](https://itemresponsewarehouse.org/tables/credentialform_lnirt/)  \n**From EDUC 252:** n/a  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n```{ojs}\n//| echo: false\nimport {palette} from \"./widgets/irt.js\"\nimport {diffusionTrials, bins, satCurves, diffusionIRT} from \"./widgets/rt-process-models.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\n[Response time and the speed-accuracy tradeoff](response-time.qmd) modelled time and accuracy separately, joined by a correlation, and then found in four tables that a response's time said something about whether it was right. Where does that dependence come from? A process model answers by describing the decision itself: evidence builds up, noisily, until there is enough to act on, and that one process produces both the choice and the time. This lesson builds the **diffusion model** from a random walk, finds the 2PL inside it, and fits it to three IRW tables: a lexical decision task where its simple form roughly holds, a motion task whose errors are slower than it allows, and a licensure exam whose items it wasn't built for.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- describe the diffusion model's four parameters and simulate trials from it;\n- predict what a harder stimulus and a speed instruction do, and estimate the parameters with EZ-diffusion;\n- derive the 2PL from the diffusion model and say what discrimination means as a process;\n- explain why errors can be slower than correct responses, and why that has to be checked within a condition;\n- say when a diffusion model, or a race model, suits the data in hand.\n\n## Core ideas\n\n### A decision as a random walk\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Response time and the speed-accuracy tradeoff](response-time.qmd): the hierarchical model assumes **conditional independence**. Given ability, speed and the item parameters, a response's time says nothing more about whether it was right. In all four tables the conditional accuracy function said otherwise, in a different shape each time.\n:::\n\nA respondent is deciding whether a string of letters is a word. Keep a running total of the evidence, $x$, that starts at $z$ and moves upward on average when the string is a word. When it reaches an upper boundary at $\\alpha$ the respondent says \"word\"; when it falls to 0 they say \"nonword\". The time to get there plus a **non-decision time** $T_{er}$, for seeing the string and pressing the key, is the response time. Formally, over each small interval $dt$ the total moves by $v\\,dt$ plus normal noise with SD $s\\sqrt{dt}$. This is the diffusion model ([Ratcliff, 1978](https://doi.org/10.1037/0033-295X.85.2.59); [Ratcliff & McKoon, 2008](https://doi.org/10.1162/neco.2008.12-06-420)), with four parameters:\n\n- the **drift** $v$: the quality of the evidence, how fast the total moves toward the correct boundary;\n- the **boundary separation** $\\alpha$: how much evidence the respondent requires, their caution;\n- the **starting point** $z$: a bias toward one response ($z = \\alpha/2$ is unbiased);\n- the **non-decision time** $T_{er}$.\n\nThe noise $s$ only sets the scale ([Ratcliff & McKoon, 2008](https://doi.org/10.1162/neco.2008.12-06-420)). We fix $s = 1$; the documentation of the R package `rtdists` ([Singmann et al., 2014](https://doi.org/10.32614/CRAN.package.rtdists)) notes that Ratcliff and others often use $s = 0.1$, which makes $v$ and $\\alpha$ ten times smaller. The diffusion literature calls the boundary $a$; we write $\\alpha$ to keep $a$ for the item slope, though the two turn out to be the same thing.\n\n#### Try it: the random walk\n\nEach thin line is one trial (blue ends correct, orange in an error). Below, times for 1,500 trials: correct responses above the axis, errors below.\n\n```{ojs}\n//| echo: false\nviewof rw_v = Inputs.range([-1, 4], {value: 1.5, step: 0.1, label: \"Drift v\"})\nviewof rw_a = Inputs.range([0.4, 3], {value: 1.2, step: 0.1, label: \"Boundary separation α\"})\nviewof rw_z = Inputs.range([0.2, 0.8], {value: 0.5, step: 0.05, label: \"Starting point (share of α)\"})\nviewof rw_t = Inputs.range([0.1, 0.6], {value: 0.3, step: 0.05, label: \"Non-decision time (s)\"})\n```\n\n```{ojs}\n//| echo: false\nrw = diffusionTrials(rw_v, rw_a, rw_z, rw_t)\nrw_max = Math.max(1.5, 1.1 * rw.rows.map(d => d.rt).sort((x, y) => x - y)[Math.floor(0.99 * rw.rows.length)])\nrw_cb = bins(rw.rows.filter(d => d.resp === 1).map(d => d.rt), 0, rw_max, 50)\nrw_eb = bins(rw.rows.filter(d => d.resp === 0).map(d => d.rt), 0, rw_max, 50)\nhtml`<div style=\"display:flex;flex-direction:column;gap:0.5rem\">${\n  Plot.plot({width: 700, height: 240, x: {label: \"Seconds\", domain: [0, rw_max]}, y: {label: \"Evidence\", domain: [-0.05 * rw_a, 1.05 * rw_a]},\n    marks: [Plot.ruleY([0, rw_a], {stroke: palette.ink}),\n            Plot.ruleX([rw_t], {stroke: palette.guide, strokeDasharray: \"4 3\"}),\n            Plot.line(rw.paths.filter(d => d.t <= rw_max), {x: \"t\", y: \"x\", z: \"trial\", stroke: d => d.resp === 1 ? palette.main : palette.contrast, strokeWidth: 1})]})\n}${\n  Plot.plot({width: 700, height: 200, x: {label: \"Seconds\", domain: [0, rw_max]}, y: {label: \"Trials (errors below)\"},\n    marks: [Plot.rectY(rw_cb, {x1: \"x1\", x2: \"x2\", y: \"count\", fill: palette.main}),\n            Plot.rectY(rw_eb, {x1: \"x1\", x2: \"x2\", y: d => -d.count, fill: palette.contrast}),\n            Plot.ruleY([0], {stroke: palette.rule})]})\n}</div>`\n```\n\n```{ojs}\n//| echo: false\nmd`Accuracy **${rw.acc.toFixed(2)}**. Median time: correct **${rw.medCorrect.toFixed(2)} s**, errors **${isNaN(rw.medError) ? \"none\" : rw.medError.toFixed(2) + \" s\"}**.`\n```\n\nBoth histograms have the long right tail that the lognormal model assumed, here produced by the walk. With the start halfway, the two medians agree to within sampling noise (0.53 and 0.55 s as the widget loads). Move the starting point to 0.3 and errors become common and fast: a walk that starts near the error boundary gets there quickly.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"With an unbiased start ($z = \\\\alpha/2$) and the same drift on every trial, correct responses and errors have the same distribution of times. Why?\",\n  options: [\n    {text: \"Mirroring a path about the midpoint turns a correct response into an error at the same time, and the two paths' probabilities differ by a factor that doesn't depend on the time\", correct: true, why: \"For a walk with drift, the ratio of a path's probability to its mirror image's depends only on where the path ends. So conditioning on the boundary reached leaves the same distribution of times.\"},\n    {text: \"Errors are rare, so their times are noisy and happen to match\", correct: false, why: \"The equality is exact in the model, whatever the accuracy. The widget's small differences are sampling noise.\"},\n    {text: \"The non-decision time is added to both\", correct: false, why: \"$T_{er}$ shifts both distributions by the same amount, but it can't make the decision times equal. The symmetry of the walk does that.\"}\n  ]\n})\n```\n\nSo the simple model assumes conditional independence, trial by trial. [Kang, De Boeck and Ratcliff (2022)](https://doi.org/10.1007/s11336-021-09819-5) show that letting drift vary across persons and items, and the starting point vary too, produces the positive, negative and curved conditional accuracy functions found in test data, shapes like the inverted U in the response-time lesson's lexical task.\n\n### What the parameters mean, and EZ-diffusion\n\nWith an unbiased start and $s = 1$ the model gives two closed forms:\n$$\\Pr(\\text{correct}) = \\frac{1}{1 + e^{-\\alpha v}}, \\qquad \\text{mean decision time} = \\frac{\\alpha}{2v}\\,\\tanh\\!\\left(\\frac{\\alpha v}{2}\\right).$$\nA harder stimulus lowers the drift, so the respondent is less accurate *and* slower. An instruction to hurry lowers the boundary, so they are faster but less accurate. The response-time lesson's speed–accuracy tradeoff becomes one parameter, $\\alpha$, and moving along it leaves the drift alone. [Ratcliff and McKoon (2008)](https://doi.org/10.1162/neco.2008.12-06-420) review experiments in which stimulus difficulty moved the drift and speed or accuracy instructions moved the boundaries.\n\n#### Try it: drift or boundary?\n\nAccuracy against mean response time ($T_{er}$ = 0.3 s) as the boundary changes (blue) or the drift changes (orange); the dot is the current setting.\n\n```{ojs}\n//| echo: false\nviewof sa_v = Inputs.range([0.2, 4], {value: 1.5, step: 0.1, label: \"Drift v\"})\nviewof sa_a = Inputs.range([0.3, 3], {value: 1.2, step: 0.1, label: \"Boundary separation α\"})\n```\n\n```{ojs}\n//| echo: false\nsa = satCurves(sa_v, sa_a)\nPlot.plot({\n  width: 700, height: 320, x: {label: \"Mean response time (s)\", domain: [0.3, 1.6]}, y: {label: \"P(correct)\", domain: [0.5, 1]},\n  color: {legend: true, domain: [\"change the boundary\", \"change the drift\"], range: [palette.main, palette.contrast]},\n  marks: [Plot.line(sa.curves.filter(d => d.rt <= 1.6), {x: \"rt\", y: \"p\", stroke: \"which\", strokeWidth: 2.5}),\n          Plot.dot([sa.point], {x: \"rt\", y: \"p\", r: 6, fill: palette.ink})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Accuracy **${sa.point.p.toFixed(3)}**, mean response time **${sa.point.rt.toFixed(2)} s**.`\n```\n\nLower α and the dot slides down the blue curve, toward faster and less accurate responses. Lower the drift and it slides down the orange curve, toward slower *and* less accurate ones. The two leave different marks on time and accuracy together, which is how a model tells them apart.\n\nThe closed forms can be run backwards. **EZ-diffusion** ([Wagenmakers, van der Maas & Grasman, 2007](https://doi.org/10.3758/BF03194023)) takes three numbers from a set of trials (the proportion correct and the mean and variance of the correct response times) and returns $v$, $\\alpha$ and $T_{er}$ in closed form. It assumes the simple model (an unbiased start, no variability across trials) and ignores the error times. [Ratcliff (2008)](https://doi.org/10.3758/PBR.15.6.1218) shows that it is sensitive to outlying times and can mislead when its assumptions don't hold, and suggests it for exploration rather than final estimates. EZ is a reasonable choice for a first look at many respondents with many trials each, and it is a few lines of base R; full fits are in *Going further*.\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: the EZ equations\n\n**Assumptions:** the diffusion model with $s = 1$, an unbiased start $z = \\alpha/2$, and no across-trial variability in drift, start or non-decision time; one condition, with proportion correct $P_c$ (not 0.5 or 1) and mean $M$ and variance $V$ of the correct response times.\n\nAccuracy gives the product: $L = \\text{logit}(P_c) = \\alpha v$. The variance of the decision time (which is also the variance of the response time, since $T_{er}$ is constant) is a second function of $\\alpha$ and $v$; eliminating $\\alpha$ gives\n$$v = \\text{sign}\\!\\left(P_c - \\tfrac12\\right)\\left[\\frac{L\\left(P_c^2 L - P_c L + P_c - \\tfrac12\\right)}{V}\\right]^{1/4}, \\qquad \\alpha = \\frac{L}{v}.$$\nThe mean decision time then follows from the closed form in the main text, and $T_{er} = M - \\frac{\\alpha}{2v}\\,\\frac{1 - e^{-\\alpha v}}{1 + e^{-\\alpha v}}$ ([Wagenmakers et al., 2007](https://doi.org/10.3758/BF03194023)). With $s = 0.1$, multiply $v$ and $\\alpha$ by 0.1.\n\nTwo edge cases need care. At $P_c = 1$ the logit is infinite; the code replaces $P_c$ with $1 - 1/(2n)$ for $n$ trials, counting half an error. At $P_c = 0.5$ the drift is zero and $\\alpha$ is undefined. The Simulate section checks the equations by recovery: data generated with known parameters give them back.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In a lexical decision experiment, the same respondents are told on some blocks to respond as fast as they can. Accuracy falls from 0.92 to 0.85 and responses get faster. Under the diffusion model, which parameter changed?\",\n  options: [\n    {text: \"The boundary separation $\\\\alpha$\", correct: true, why: \"An instruction changes how much evidence the respondent waits for, not the quality of the evidence. A lower $\\\\alpha$ gives faster, less accurate responses, as observed.\"},\n    {text: \"The drift $v$\", correct: false, why: \"The strings haven't changed, so the evidence they carry hasn't either. And a lower drift would make responses slower, not faster.\"},\n    {text: \"The non-decision time $T_{er}$\", correct: false, why: \"A shorter $T_{er}$ speeds every response but leaves accuracy alone. It can't explain the drop from 0.92 to 0.85.\"}\n  ]\n})\n```\n\n### The diffusion model is an item response model\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [From the 1PL to the 4PL](1pl-to-4pl.qmd): the 2PL is $\\Pr(x_{ij} = 1) = \\text{logit}^{-1}\\big(a_i(\\theta_j - b_i)\\big)$, where the slope or discrimination $a_i$ says how quickly the probability rises as $\\theta$ passes $b_i$.\n:::\n\nNow let the drift depend on who meets which item: $v_{ij} = \\theta_j - b_i$, the respondent's ability minus the item's difficulty. Put that into the accuracy formula:\n$$\\Pr(x_{ij} = 1) = \\frac{1}{1 + e^{-\\alpha(\\theta_j - b_i)}}.$$\nThat is a 2PL whose slope is the boundary separation. [Tuerlinckx and De Boeck (2005)](https://doi.org/10.1007/s11336-000-0810-3) read discrimination this way: the amount of information collected before responding. Whose boundary is it? If it belongs to the item (a time limit, a format that invites care), $\\alpha_i$ is an ordinary item slope. If it belongs to the respondent, a cautious respondent's answers discriminate more: a slope that varies by person, which the 2PL doesn't have. [Van der Maas et al. (2011)](https://doi.org/10.1037/a0022749) follow this line to a new model for accuracy and speed, and `diffIRT` fits diffusion item response models ([Molenaar, Tuerlinckx & van der Maas, 2015](https://doi.org/10.18637/jss.v066.i04)).\n\n#### Try it: the 2PL inside the walk\n\nDrift is θ − b. Curves are the closed forms for two boundaries; dots are proportions correct in 200 simulated walks at each ability (first boundary).\n\n```{ojs}\n//| echo: false\nviewof ir_b = Inputs.range([-2, 2], {value: 0, step: 0.1, label: \"Item difficulty b\"})\nviewof ir_a1 = Inputs.range([0.4, 3], {value: 1, step: 0.1, label: \"First boundary α\"})\nviewof ir_a2 = Inputs.range([0.4, 3], {value: 2, step: 0.1, label: \"Second boundary α\"})\n```\n\n```{ojs}\n//| echo: false\nir = diffusionIRT(ir_b, ir_a1, ir_a2)\nir_dom = [`boundary ${ir_a1.toFixed(1)}`, `boundary ${ir_a2.toFixed(1)}`]\nhtml`<div style=\"display:flex;flex-wrap:wrap;gap:1rem\">${\n  Plot.plot({width: 340, height: 280, x: {label: \"Ability θ\"}, y: {label: \"P(correct)\", domain: [0, 1]},\n    color: {legend: true, domain: ir_dom, range: [palette.main, palette.contrast]},\n    marks: [Plot.ruleX([ir_b], {stroke: palette.rule}),\n            Plot.line(ir.curves, {x: \"theta\", y: \"p\", stroke: \"curve\", strokeWidth: 2.5}),\n            Plot.dot(ir.dots, {x: \"theta\", y: \"p\", fill: palette.ink, r: 3.5})]})\n}${\n  Plot.plot({width: 340, height: 280, x: {label: \"Ability θ\"}, y: {label: \"Mean decision time (s)\"},\n    color: {domain: ir_dom, range: [palette.main, palette.contrast]},\n    marks: [Plot.ruleX([ir_b], {stroke: palette.rule}),\n            Plot.line(ir.curves, {x: \"theta\", y: \"mdt\", stroke: \"curve\", strokeWidth: 2.5})]})\n}</div>`\n```\n\nThe dots, from nothing but random walks, sit on a logistic curve, steeper for the wider boundary, as for a larger slope. The right panel is what a 2PL can't see: decisions take longest for respondents near the item's difficulty, where the drift is near zero, and the wider boundary takes longer everywhere. The model predicts which responses should be slow, not only which should be right.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Two respondents have the same ability. One sets a boundary of 2, the other of 1. On an item with $b$ one logit below their ability, what are their chances of a correct response?\",\n  options: [\n    {text: \"About 0.88 for the cautious one and 0.73 for the other\", correct: true, why: \"The drift is $\\\\theta - b = 1$, so $1/(1 + e^{-2}) \\\\approx 0.88$ and $1/(1 + e^{-1}) \\\\approx 0.73$. The cautious respondent pays for the extra accuracy in time.\"},\n    {text: \"The same, 0.73, because they have the same ability\", correct: false, why: \"Under the diffusion model accuracy depends on the product $\\\\alpha v$, not on $v$ alone. Equal abilities give equal drifts, not equal accuracies.\"},\n    {text: \"About 0.98 and 0.73\", correct: false, why: \"$1/(1+e^{-4}) \\\\approx 0.98$ would need $\\\\alpha v = 4$. Here it is $2 \\\\times 1 = 2$.\"}\n  ]\n})\n```\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: from the random walk to the 2PL\n\n**Assumptions:** a diffusion process with drift $v$ and noise SD $s$ per unit time, absorbing boundaries at 0 and $\\alpha$, a start at $z$, and no across-trial variability. The process ends at one boundary or the other with probability 1.\n\nLet $h(x)$ be the probability of reaching $\\alpha$ before 0 from position $x$. Over a short step, $h(x) = \\mathbb{E}\\,h(x + v\\,dt + s\\,dW)$; expanding to second order gives $v\\,h'(x) + \\tfrac{s^2}{2} h''(x) = 0$, with $h(0) = 0$ and $h(\\alpha) = 1$. The solution is\n$$h(z) = \\frac{1 - e^{-2vz/s^2}}{1 - e^{-2v\\alpha/s^2}}.$$\nAt $z = \\alpha/2$ the numerator is $1 - e^{-v\\alpha/s^2}$ and the denominator factors as $(1 - e^{-v\\alpha/s^2})(1 + e^{-v\\alpha/s^2})$, so\n$$h(\\alpha/2) = \\frac{1}{1 + e^{-\\alpha v/s^2}}.$$\nWith $v = \\theta_j - b_i$ this is a 2PL with slope $\\alpha/s^2$ ([Tuerlinckx & De Boeck, 2005](https://doi.org/10.1007/s11336-000-0810-3)). Two assumptions did the work. A biased start ($z \\ne \\alpha/2$) moves the curve, so it no longer passes through 0.5 at $\\theta = b$. Across-trial variability in drift averages logistic curves with different arguments, which flattens the curve. Either way the model is still an item response model, just not exactly a 2PL.\n:::\n\n### Slow errors\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Item response data and the IRW](irw-data.qmd): in the brightness experiment of `rr98_accuracy`, errors were slower than correct responses (median 0.65 s against 0.56 s), but within a brightness level by only about 0.02 s. Most of the gap came from errors crowding into the hard levels, which are slow for every response.\n:::\n\nThe simple model predicts no gap within a condition, as the first widget showed. Data can have one (the motion task below does), and [Ratcliff and Rouder (1998)](https://doi.org/10.1111/1467-9280.00067) account for it with variability *across* trials. If the drift varies from trial to trial (SD $\\eta$), errors come mostly from trials whose drift happened to be low, and those trials are slow however they end: errors are slower. If the starting point varies, errors come mostly from trials that began near the wrong boundary, and those end quickly: errors are faster ([Ratcliff & McKoon, 2008](https://doi.org/10.1162/neco.2008.12-06-420)).\n\nThe pooled `rr98_accuracy` gap is the same mechanism one level up, with conditions of different difficulty playing the part of trials with different drift. So before reading slow errors as drift variability, compare error and correct times *within* a condition, and within a respondent.\n\n#### Try it: variability across trials\n\n3,000 trials with drift 1.5 and boundary 2 on average.\n\n```{ojs}\n//| echo: false\nviewof se_eta = Inputs.range([0, 2], {value: 0, step: 0.1, label: \"Across-trial SD of drift (η)\"})\nviewof se_sz = Inputs.range([0, 0.9], {value: 0, step: 0.05, label: \"Across-trial range of the start (share of α)\"})\n```\n\n```{ojs}\n//| echo: false\nse = diffusionTrials(1.5, 2, 0.5, 0.3, se_eta, se_sz, 3000, 7, 0)\nse_cb = bins(se.rows.filter(d => d.resp === 1).map(d => d.rt), 0, 3, 50)\nse_eb = bins(se.rows.filter(d => d.resp === 0).map(d => d.rt), 0, 3, 50)\nPlot.plot({width: 700, height: 240, x: {label: \"Seconds\", domain: [0, 3]}, y: {label: \"Trials (errors below)\"},\n  marks: [Plot.rectY(se_cb, {x1: \"x1\", x2: \"x2\", y: \"count\", fill: palette.main}),\n          Plot.rectY(se_eb, {x1: \"x1\", x2: \"x2\", y: d => -d.count, fill: palette.contrast}),\n          Plot.ruleX([se.medCorrect], {stroke: palette.main, strokeDasharray: \"4 3\"}),\n          Plot.ruleX([se.medError], {stroke: palette.contrast, strokeDasharray: \"4 3\"}),\n          Plot.ruleY([0], {stroke: palette.rule})]})\n```\n\n```{ojs}\n//| echo: false\nmd`Accuracy **${se.acc.toFixed(2)}**. Median time: correct **${se.medCorrect.toFixed(2)} s**, errors **${se.medError.toFixed(2)} s** (a gap of ${(se.medError - se.medCorrect).toFixed(2)} s, from ${se.nError} errors).`\n```\n\nWith both sliders at 0 the dashed medians nearly coincide (a gap of 0.03 s). Raise η to 1 and errors become slower by about a quarter of a second, and accuracy falls. Put η back to 0 and raise the start's range to 0.8: now errors are *faster*, by about as much.\n\n### Race models for more than two options\n\nOne accumulator with two boundaries suits two responses. With three or more (the ink colours in a Stroop task, the options of a multiple-choice item) the natural extension is a **race**: each option has its own accumulator, and the first to reach its threshold gives the response and the time ([Heathcote & Matzke, 2022](https://doi.org/10.1177/09637214221095852)). [Tuerlinckx and De Boeck (2005)](https://doi.org/10.1007/s11336-000-0810-3) derive the 2PL from a race model too. The **linear ballistic accumulator** ([Brown & Heathcote, 2008](https://doi.org/10.1016/j.cogpsych.2007.12.002)) is the tractable case: independent accumulators rise in straight lines, without noise within a trial, toward a common threshold, which gives closed-form solutions for any number of options. Problem 6 sketches one.\n\n## Simulate\n\nThe code generates 100 respondents × 200 trials as plain random walks in base R (a second or two), each respondent with their own drift, boundary and non-decision time. It recovers them with EZ-diffusion and compares an accuracy-only ability, the logit of the proportion correct, with the truth.\n\nWith the seed as written, EZ's average drift matches the truth (1.47), and its estimates correlate 0.97 with the true drifts, 0.97 with the boundaries and 0.93 with the non-decision times (boundaries run slightly wide, 1.32 against 1.29, from the walk's step size). The accuracy-only ability correlates 0.86 with drift and 0.47 with the boundary: judged by accuracy alone, a careful respondent looks abler. Now set `eta <- 1`. EZ's average drift falls to 1.18 against a true 1.47, though it still orders respondents well (0.95), and errors become slower than correct responses (0.67 against 0.64 s).\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-17\n# Simulate two-choice decisions from the diffusion model and recover its parameters\n# with EZ-diffusion (Wagenmakers, van der Maas & Grasman, 2007).\n#\n# Each respondent j has a drift theta_j (their ability: the drift on an item of\n# difficulty 0), a boundary separation alpha_j (caution) and a non-decision time ter_j.\n# Every trial is a random walk that starts halfway between 0 and alpha_j and moves by\n# v * dt plus Gaussian noise with SD sqrt(dt) (so s = 1) until it crosses a boundary.\n# eta is the across-trial SD of drift: 0 is the simple model; try eta <- 1.\n#\n# Base R only. The walk takes a second or two in the browser; raise np and ntr as\n# you like in your own R session. (rtdists::rdiffusion samples the same model\n# without the small error from the size of the steps.)\nset.seed(65)\nnp  <- 100     # respondents\nntr <- 200     # trials per respondent\neta <- 0       # across-trial SD of drift\n\ntheta <- rnorm(np, 1.5, 0.5)       # drift\nbound <- runif(np, 0.8, 1.8)       # boundary separation\nter   <- runif(np, 0.3, 0.5)       # non-decision time (s)\n\nwalk <- function(v, a, ter, dt = 0.001, maxt = 10) {\n  n <- length(v); x <- a / 2; t <- numeric(n); resp <- rep(NA_integer_, n)\n  live <- seq_len(n)\n  while (length(live) && t[live[1]] < maxt) {\n    x[live] <- x[live] + v[live] * dt + sqrt(dt) * rnorm(length(live))\n    t[live] <- t[live] + dt\n    up <- x[live] >= a[live]; lo <- x[live] <= 0\n    resp[live[up]] <- 1L; resp[live[lo]] <- 0L\n    live <- live[!(up | lo)]\n  }\n  data.frame(rt = ter + t, resp = resp)\n}\n\nd <- data.frame(id = rep(1:np, each = ntr))\nd$v <- theta[d$id] + eta * rnorm(nrow(d))      # this trial's drift\nd <- cbind(d, walk(d$v, bound[d$id], ter[d$id]))\n\n# EZ-diffusion from the proportion correct and the mean and variance of correct RTs.\nez <- function(pc, vrt, mrt, s = 1) {\n  L <- qlogis(pc)\n  x <- L * (L * pc^2 - L * pc + pc - 0.5) / vrt\n  v <- sign(pc - 0.5) * s * x^(1/4)\n  a <- s^2 * L / v\n  y <- -v * a / s^2\n  mdt <- (a / (2 * v)) * (1 - exp(y)) / (1 + exp(y))\n  c(v = v, alpha = a, ter = mrt - mdt)\n}\nest <- as.data.frame(t(sapply(split(d, d$id), function(x) {\n  pc <- mean(x$resp); if (pc == 1) pc <- 1 - 1 / (2 * nrow(x))\n  rc <- x$rt[x$resp == 1]\n  c(pc = pc, ez(pc, var(rc), mean(rc)))\n})))\n\n# Everyone takes the same trials, so the sum score is sufficient and the logit of the\n# proportion correct orders respondents as a Rasch ability estimate would.\nacc_ability <- qlogis(est$pc)\n\nround(c(accuracy = mean(d$resp),\n        median_correct = median(d$rt[d$resp == 1]), median_error = median(d$rt[d$resp == 0])), 2)\nround(rbind(truth = c(v = mean(theta), alpha = mean(bound), ter = mean(ter)),\n            EZ = colMeans(est[, c(\"v\", \"alpha\", \"ter\")]),\n            r = c(cor(est$v, theta), cor(est$alpha, bound), cor(est$ter, ter))), 2)\nround(c(r_accuracy_drift = cor(acc_ability, theta), r_accuracy_boundary = cor(acc_ability, bound)), 2)\n\nop <- par(mfrow = c(1, 2), mar = c(4, 4, 1, 1))\nplot(theta, est$v, pch = 19, col = \"#2780e3\", xlab = \"True drift\", ylab = \"EZ drift\")\nabline(0, 1, lty = 2, col = \"#999999\")\nplot(bound, acc_ability, pch = 19, col = \"#c2410c\",\n     xlab = \"True boundary separation\", ylab = \"Logit of proportion correct\")\npar(op)\n\n```\n:::\n\n\n[Download this code](code/rt-process-models-sim.R) to run it as large as you like in your own R session.\n\n## With real data\n\n\n\n[mturkddm_lexical](https://itemresponsewarehouse.org/tables/mturkddm_lexical/) is the main example: fast two-choice decisions, many trials per respondent. [motion](https://itemresponsewarehouse.org/tables/motion/) is the contrast: stimulus strength is varied by design, and errors are slow. [credentialform_lnirt](https://itemresponsewarehouse.org/tables/credentialform_lnirt/), the licensure exam from the response-time lesson, is the failure case: items that take most of a minute. [Download the code](code/rt-process-models-irw.R); it needs `lme4`. EZ and the trimming rule are shared by all three:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# EZ-diffusion: drift v, boundary separation alpha and non-decision time Ter from three\n# numbers, the proportion correct and the mean and variance of correct response times.\n# s is the SD of the within-trial noise; we use s = 1 (see the lesson).\nez <- function(pc, vrt, mrt, s = 1) {\n  L <- qlogis(pc)\n  x <- L * (L * pc^2 - L * pc + pc - 0.5) / vrt\n  v <- sign(pc - 0.5) * s * x^(1/4)\n  a <- s^2 * L / v\n  y <- -v * a / s^2\n  mdt <- (a / (2 * v)) * (1 - exp(y)) / (1 + exp(y))   # mean decision time\n  c(v = v, alpha = a, ter = mrt - mdt)\n}\n# EZ for one set of trials. A perfect score has no logit, so it gets the usual\n# edge correction (half an error); at exactly 0.5 accuracy EZ is undefined (NaN).\nez_trials <- function(resp, rt) {\n  n <- length(resp); pc <- mean(resp)\n  if (pc == 1) pc <- 1 - 1 / (2 * n)\n  rc <- rt[resp == 1]\n  c(n = n, pc = pc, ez(pc, var(rc), mean(rc)))\n}\n# Set aside responses under 0.3 s (fast guesses: accuracy is near chance below that\n# in both speeded tables) and the slowest 1% of each table.\ntrim <- function(d) d[d$rt >= 0.3 & d$rt <= quantile(d$rt, 0.99), ]\n# Error minus correct median time within each group of trials (a respondent, an item,\n# a respondent at one condition), for groups with at least 5 errors.\nwithin_gap <- function(d, by) {\n  g <- sapply(split(d, by), function(x)\n    if (sum(x$resp == 0) >= 5) median(x$rt[x$resp == 0]) - median(x$rt[x$resp == 1]) else NA)\n  g[!is.na(g)]\n}\n```\n:::\n\n\n### Lexical decision online\n\n[Ratcliff and Hendrickson (2021)](https://doi.org/10.3758/s13428-021-01573-x) repeated a lexical decision experiment with respondents recruited on Amazon Mechanical Turk to see whether online data reproduce laboratory results. Each respondent judged 480 strings, real words and made-up ones. Keying: 1 is a correct judgement.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(lme4)\noptions(digits = 7)  # R's default, in case a .Rprofile changes it\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.mturkddm_lexical/rows?format=csv\"\nlx <- read.csv(url)\n# One row per trial; item is the letter string shown, resp is 1 for a correct\n# word/nonword judgement, rt is in seconds. 136 invalid keypresses have no response.\nlx <- lx[!is.na(lx$resp), ]\nc(respondents = length(unique(lx$id)), strings = length(unique(lx$item)),\n  trials_per_respondent = median(table(lx$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          respondents               strings trials_per_respondent \n                  142                  4588                   480 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(accuracy = mean(lx$resp), median_s = median(lx$rt),\n        share_under_0.3s = mean(lx$rt < 0.3), accuracy_under_0.3s = mean(lx$resp[lx$rt < 0.3]),\n        slowest_1pct_from_s = unname(quantile(lx$rt, 0.99))), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           accuracy            median_s    share_under_0.3s accuracy_under_0.3s \n              0.885               0.638               0.010               0.527 \nslowest_1pct_from_s \n              1.995 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nlx <- trim(lx)\n```\n:::\n\n\nResponses under 0.3 s (1% of trials) are right about half the time, like guesses, so we set them aside with the slowest 1% (over 2 s). Does the simple model's symmetry hold?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Are errors slower than correct responses? Pooled, and within each respondent.\ngap_lx <- within_gap(lx, lx$id)\nround(c(median_correct = median(lx$rt[lx$resp == 1]), median_error = median(lx$rt[lx$resp == 0]),\n        within_respondent_gap = median(gap_lx), share_slower = mean(gap_lx > 0)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       median_correct          median_error within_respondent_gap \n                0.639                 0.633                 0.014 \n         share_slower \n                0.606 \n```\n\n\n:::\n:::\n\n\nRoughly. Errors take 0.633 s and correct responses 0.639 s; within a respondent, errors are slower by 0.014 s, in 61% of respondents. Against responses of about 0.64 s the gap is small, so EZ's simple model is a fair approximation. EZ for each respondent:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# EZ for each respondent, over all 480 of their trials (words and nonwords together).\npp <- as.data.frame(do.call(rbind, lapply(split(lx, lx$id), function(x) ez_trials(x$resp, x$rt))))\npp$id <- as.integer(names(split(lx, lx$id)))\nround(sapply(pp[, c(\"pc\", \"v\", \"alpha\", \"ter\")], quantile, c(0.1, 0.5, 0.9)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      pc    v alpha  ter\n10% 0.80 1.27  0.94 0.37\n50% 0.90 1.98  1.13 0.44\n90% 0.97 2.63  1.46 0.54\n```\n\n\n:::\n:::\n\n\nThe median respondent has drift 1.98, boundary 1.13 and non-decision time 0.44 s. EZ pools each respondent's words and nonwords into one drift, a simplification problem 2 undoes. Set these beside the response-time lesson's estimates: an ability from a Rasch-type `glmer` fit and a speed from the lognormal `lmer` fit.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Across respondents, which EZ parameter will correlate most strongly with the Rasch-type ability estimated from accuracy alone?\",\n  choices: [\"Drift v\", \"Boundary separation α\", \"Non-decision time\", \"None: all below 0.3\"],\n  answer: \"Drift v\",\n  reveal: \"Drift, at 0.82. But the boundary correlates 0.50 with ability too: the accuracy-only ability mixes skill with caution, as the Simulate section predicted. Speed is mostly boundary (−0.71) and non-decision time (−0.77).\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# A Rasch-type ability (glmer with crossed random effects) and a speed (minus the\n# respondent effect on log time, lmer), as in response-time. nAGQ = 0 skips glmer's\n# slowest step.\nm_acc <- glmer(resp ~ 1 + (1 | id) + (1 | item), lx, binomial, nAGQ = 0)\nm_time <- lmer(log(rt) ~ 1 + (1 | id) + (1 | item), lx)\npp$theta <- ranef(m_acc)$id[as.character(pp$id), 1]\npp$speed <- -ranef(m_time)$id[as.character(pp$id), 1]\nround(cor(pp[, c(\"v\", \"alpha\", \"ter\", \"theta\", \"speed\")]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          v alpha   ter theta speed\nv      1.00 -0.06  0.07  0.82  0.19\nalpha -0.06  1.00  0.19  0.50 -0.71\nter    0.07  0.19  1.00  0.14 -0.77\ntheta  0.82  0.50  0.14  1.00 -0.19\nspeed  0.19 -0.71 -0.77 -0.19  1.00\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nop <- par(mfrow = c(1, 2), mar = c(4, 4, 1, 1))\nplot(pp$v, pp$theta, pch = 19, col = \"#2780e3\", xlab = \"EZ drift v\", ylab = \"Ability (glmer)\")\nplot(pp$alpha, pp$speed, pch = 19, col = \"#c2410c\", xlab = \"EZ boundary separation alpha\", ylab = \"Speed (lmer)\")\n```\n\n::: {.cell-output-display}\n![](rt-process-models_files/figure-html/plot-lex-1.png){width=672}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\npar(op)\n```\n:::\n\n\nAbility tracks drift ($r = 0.82$), and the boundary as well ($r = 0.50$): a respondent who waits for more evidence gets more right, and a model of accuracy alone credits that to ability. Speed from the lognormal model is mostly the boundary ($r = -0.71$) and the non-decision time ($r = -0.77$), and barely relates to drift ($r = 0.19$). Ability and speed are nearly unrelated ($r = -0.19$), much as in the ROAR lexical task of the response-time lesson. The diffusion model reads that near-zero as speed and ability being built from different parts of the process.\n\n### Random-dot motion: the model's story, and slow errors\n\nIn [O'Brien and Yeatman's (2021)](https://doi.org/10.1111/desc.13039) study of dyslexia, 106 school-aged children reported the direction of a field of moving dots, of which 6%, 12%, 24%, 48% or 100% moved together (the coherence). An IRW item is a block of the session and a coherence level, met 10 times, so each child has 60 trials per level ([processing script](https://github.com/ben-domingue/irw/blob/main/data/motion_discrimination.R)). Keying: 1 is correct.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.motion/rows?format=csv\"\nmo <- read.csv(url)\n# item is \"<block> <coherence>\": block 1-6 of the session, and the percentage of dots\n# moving together (6, 12, 24, 48 or 100). Each respondent saw each item 10 times\n# (trialnum), so 60 trials per coherence level. resp is 1 for the right direction.\nmo$block <- as.integer(sub(\" .*\", \"\", mo$item))\nmo$coherence <- as.integer(sub(\".* \", \"\", mo$item))\nc(respondents = length(unique(mo$id)), items = length(unique(mo$item)),\n  trials_per_respondent = median(table(mo$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          respondents                 items trials_per_respondent \n                  106                    30                   300 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(accuracy = mean(mo$resp), median_s = median(mo$rt),\n        share_under_0.3s = mean(mo$rt < 0.3), accuracy_under_0.3s = mean(mo$resp[mo$rt < 0.3]),\n        slowest_1pct_from_s = unname(quantile(mo$rt, 0.99))), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           accuracy            median_s    share_under_0.3s accuracy_under_0.3s \n              0.801               1.151               0.017               0.460 \nslowest_1pct_from_s \n              7.503 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nmo <- trim(mo)\n```\n:::\n\n\nAgain, responses under 0.3 s are at chance (0.46), and we set them aside with the slowest 1% (over 7.5 s). EZ for each child at each coherence level, and the medians across children:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# EZ for each respondent at each coherence level (about 60 trials), then the median\n# across respondents. Alongside: accuracy, and median correct and error times.\ncells <- split(mo, list(mo$id, mo$coherence))\npl <- as.data.frame(do.call(rbind, lapply(cells, function(x)\n  c(id = x$id[1], coherence = x$coherence[1], ez_trials(x$resp, x$rt)))))\nby_coh <- aggregate(cbind(pc, v, alpha, ter) ~ coherence, pl, median)\nby_coh$median_correct <- tapply(mo$rt[mo$resp == 1], mo$coherence[mo$resp == 1], median)\nby_coh$median_error <- tapply(mo$rt[mo$resp == 0], mo$coherence[mo$resp == 0], median)\nround(by_coh, 2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| coherence|   pc|    v| alpha|  ter| median_correct| median_error|\n|---------:|----:|----:|-----:|----:|--------------:|------------:|\n|         6| 0.67| 0.28|  2.52| 0.42|           1.43|         1.61|\n|        12| 0.78| 0.57|  2.49| 0.31|           1.23|         1.48|\n|        24| 0.90| 0.95|  2.46| 0.35|           1.08|         1.33|\n|        48| 0.95| 1.12|  2.39| 0.30|           0.99|         1.22|\n|       100| 0.88| 0.85|  2.35| 0.35|           0.93|         1.59|\n\n</div>\n:::\n:::\n\n\nFrom 6% to 48% coherence the median drift rises from 0.28 to 1.12, while the boundary barely moves (2.52 to 2.39). That is the model's story: the stimulus changed, so the evidence changed, and the children's caution didn't. At 100% the drift falls back to 0.85; the authors report that many children found full coherence difficult, and they left it out of their analysis. The last two columns hold something the simple model doesn't allow: errors are slower than correct responses at every level. Is that composition again, as in `rr98_accuracy`?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Error minus correct median time within each respondent at each coherence level\n# (cells with at least 5 errors), summarised by level.\nmo$cell <- paste(mo$id, mo$coherence)\ngap_mo <- within_gap(mo, mo$cell)\ncoh_of <- as.integer(sub(\".* \", \"\", names(gap_mo)))\nround(rbind(within_gap = tapply(gap_mo, coh_of, median),\n            share_slower = tapply(gap_mo > 0, coh_of, mean),\n            cells = tapply(gap_mo, coh_of, length)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  6    12    24    48   100\nwithin_gap     0.17  0.26  0.13  0.14  0.34\nshare_slower   0.71  0.79  0.66  0.64  0.77\ncells        106.00 99.00 61.00 44.00 64.00\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nop <- par(mfrow = c(1, 2), mar = c(4, 4, 1, 1))\nlev <- factor(by_coh$coherence)\nplot(seq_along(lev), by_coh$v, type = \"b\", pch = 19, col = \"#2780e3\", xaxt = \"n\",\n     ylim = c(0, 3.2), xlab = \"Coherence (%)\", ylab = \"EZ estimate (median)\")\nlines(seq_along(lev), by_coh$alpha, type = \"b\", pch = 17, col = \"#c2410c\")\naxis(1, at = seq_along(lev), labels = levels(lev))\nlegend(\"topright\", c(\"boundary alpha\", \"drift v\"), col = c(\"#c2410c\", \"#2780e3\"), pch = c(17, 19), bty = \"n\", horiz = TRUE)\nplot(seq_along(lev), by_coh$median_error, type = \"b\", pch = 19, col = \"#c2410c\", xaxt = \"n\",\n     ylim = c(0.8, 1.8), xlab = \"Coherence (%)\", ylab = \"Median time (s)\")\nlines(seq_along(lev), by_coh$median_correct, type = \"b\", pch = 19, col = \"#2780e3\")\naxis(1, at = seq_along(lev), labels = levels(lev))\nlegend(\"bottomleft\", c(\"errors\", \"correct\"), col = c(\"#c2410c\", \"#2780e3\"), pch = 19, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](rt-process-models_files/figure-html/plot-motion-1.png){width=672}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\npar(op)\n```\n:::\n\n\nNo. Within a child and a coherence level, errors are slower by 0.13 to 0.34 s, in 64% to 79% of cells. These are slow errors that one drift per condition can't produce and across-trial variability in drift can; O'Brien and Yeatman's own fits included it. EZ leaves it out, so by the Simulate section's result its drifts here are probably too low, though their order should hold.\n\n### A licensure exam: where the reading runs out\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Response time and the speed-accuracy tradeoff](response-time.qmd): on this exam's 170 scored items the median response takes 54 s, and responses slower than expected are less often right.\n:::\n\nNothing in the EZ equations refuses seconds:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.credentialform_lnirt/rows?format=csv\"\ncf <- read.csv(url)\n# As in response-time: the 170 scored items (171-200 are pilot items whose names\n# depend on the pilot set), and times of 0 (under a second) set aside.\ncf$inum <- as.integer(sub(\"iraw.\", \"\", cf$item))\ncf <- cf[cf$inum <= 170 & cf$rt > 0, ]\nround(c(respondents = length(unique(cf$id)), accuracy = mean(cf$resp),\n        median_s = median(cf$rt)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents    accuracy    median_s \n    1636.00        0.73       54.00 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# EZ for each respondent over their 170 items: seconds, not fractions of a second.\npc_cf <- as.data.frame(do.call(rbind, lapply(split(cf, cf$id), function(x) ez_trials(x$resp, x$rt))))\nround(c(median_v = median(pc_cf$v, na.rm = TRUE), median_alpha = median(pc_cf$alpha, na.rm = TRUE),\n        median_ter_s = median(pc_cf$ter, na.rm = TRUE),\n        share_ter_negative = mean(pc_cf$ter < 0, na.rm = TRUE),\n        undefined_at_0.5 = sum(is.na(pc_cf$ter))), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          median_v       median_alpha       median_ter_s share_ter_negative \n             0.074             14.050             12.822              0.067 \n  undefined_at_0.5 \n             5.000 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Errors against correct responses, within each item.\ngap_cf <- within_gap(cf, cf$item)\nround(c(within_item_gap_s = median(gap_cf), share_slower = mean(gap_cf > 0)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwithin_item_gap_s      share_slower \n            19.00              0.95 \n```\n\n\n:::\n:::\n\n\nThe numbers come out, but not with the model's meaning. The median non-decision time is 12.8 s, and it is negative, which is impossible, for 6.7% of respondents; five respondents at exactly half right get no estimate at all. On 95% of items errors are slower than correct responses, by a median 19 s. A 54-second item is not one accumulation of evidence toward two boundaries but reading, working and choosing among several options. The failure is in the model's assumptions for these items, not in the data.\n\nSo when would I reach for a diffusion model? When each response is a single fast decision between two options and each respondent gives many trials, as in lexical decision, motion and brightness judgements. There it separates what accuracy alone mixes, ability and caution, and in the lexical data the mixing is substantial (ability and boundary correlate 0.50). For test items that take most of a minute I wouldn't: the licensure exam gives parameters with no process to belong to. A model of the decision needs data made of decisions.\n\n## Problems\n\n1. **Discrimination as a boundary.** From the absorption probability in the second *Go deeper* callout, show that with $z = \\alpha/2$, $\\Pr(\\text{correct}) = 1/(1 + e^{-\\alpha v/s^2})$. With $v = \\theta - b$, read off the 2PL's discrimination. What is it for a paper that reports $\\alpha = 0.12$ with $s = 0.1$? Why does the non-decision time not enter?\n2. **Words and nonwords.** The IRW table doesn't say which strings are words; the original deposit does: `Experiment1.data` at [osf.io/za9y8](https://osf.io/za9y8/) ([Ratcliff & Hendrickson, 2021](https://doi.org/10.3758/s13428-021-01573-x); CC BY 4.0) has `column_7_value` (1 = word, 2 = nonword) for each `test_word_string`, which is the IRW's `item`, and `column_8_value` (the frequency pool). Run EZ separately on words and nonwords for each respondent. Which parameter differs, and is that what the model says should change? Repeat for high- and low-frequency words.\n3. **Slow errors in the motion task.** Errors are slower within a child and a coherence level. Which extension of the diffusion model produces that, and what else does it predict about accuracy and about the error distribution? Check one prediction in the data. Why might the gap be largest at 100% coherence?\n4. **A non-decision time per respondent?** A colleague wants to report each respondent's $T_{er}$ from a 12-item untimed reasoning test, as a measure of processing speed. Advise them, using what EZ did on the licensure exam and what the diffusion model assumes a response is.\n5. **Separating drift from caution.** For a two-choice screening task in schools, what would you vary within respondents so that each child's drift and boundary are separately identified? How many trials per condition would you want, and how would you check by simulation that EZ recovers individual differences well enough?\n6. **Challenge (open).** Sketch a race model for a Stroop task ([Stroop, 1935](https://doi.org/10.1037/h0054651)) with three or more ink colours. What would the word's meaning do to the accumulators? How would an item's difficulty and a respondent's ability enter, and what item response model for the *choice* among colours falls out? I don't know of a derivation that gives a standard polytomous model exactly.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Process%20models%20for%20response%20time%3A%20drift%20diffusion%20and%20race%20models%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20process%20models%20for%20response%20times%3A%20the%20drift%20diffusion%20model%20%28drift%2C%20boundary%20separation%2C%20starting%20point%20and%20non-decision%20time%29%20as%20a%20random%20walk%2C%20what%20harder%20stimuli%20and%20speed%20instructions%20do%20to%20it%2C%20EZ-diffusion%20as%20a%20closed-form%20estimator%2C%20the%20derivation%20of%20the%202PL%20from%20the%20diffusion%20model%20with%20the%20boundary%20as%20discrimination%2C%20slow%20and%20fast%20errors%20from%20across-trial%20variability%20in%20drift%20and%20starting%20point%2C%20and%20race%20models%20such%20as%20the%20linear%20ballistic%20accumulator%2C%20with%20a%20lexical%20decision%20task%2C%20a%20random-dot%20motion%20task%20and%20a%20licensure%20exam%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Ratcliff, R. (1978). A theory of memory retrieval. *Psychological Review*, 85(2), 59–108. <https://doi.org/10.1037/0033-295X.85.2.59>. Where the diffusion model starts.\n- Ratcliff, R., & McKoon, G. (2008). The diffusion decision model: Theory and data for two-choice decision tasks. *Neural Computation*, 20(4), 873–922. <https://doi.org/10.1162/neco.2008.12-06-420>. A review of the model, its variability parameters and the experiments that move each parameter.\n- Ratcliff, R., & Rouder, J. N. (1998). Modeling response times for two-choice decisions. *Psychological Science*, 9(5), 347–356. <https://doi.org/10.1111/1467-9280.00067>. The brightness experiment, with fast and slow errors explained by variability across trials.\n- Ratcliff, R., & Tuerlinckx, F. (2002). Estimating parameters of the diffusion model: Approaches to dealing with contaminant reaction times and parameter variability. *Psychonomic Bulletin & Review*, 9(3), 438–481. <https://doi.org/10.3758/BF03196302>. Fitting the full model, variability and outlying times included.\n- Wagenmakers, E.-J., van der Maas, H. L. J., & Grasman, R. P. P. P. (2007). An EZ-diffusion model for response time and accuracy. *Psychonomic Bulletin & Review*, 14(1), 3–22. <https://doi.org/10.3758/BF03194023>. The EZ equations and their recovery in simulation.\n- Ratcliff, R. (2008). The EZ diffusion method: Too EZ? *Psychonomic Bulletin & Review*, 15(6), 1218–1228. <https://doi.org/10.3758/PBR.15.6.1218>. Where EZ's estimates can mislead, and what the full fits do instead.\n- Vandekerckhove, J., Tuerlinckx, F., & Lee, M. D. (2011). Hierarchical diffusion models for two-choice response times. *Psychological Methods*, 16(1), 44–62. <https://doi.org/10.1037/a0021765>. The diffusion model as a hierarchical Bayesian model, with persons and conditions as levels.\n- Wiecki, T. V., Sofer, I., & Frank, M. J. (2013). HDDM: Hierarchical Bayesian estimation of the drift-diffusion model in Python. *Frontiers in Neuroinformatics*, 7, 14. <https://doi.org/10.3389/fninf.2013.00014>. Software for hierarchical fits.\n- Tuerlinckx, F., & De Boeck, P. (2005). Two interpretations of the discrimination parameter. *Psychometrika*, 70(4), 629–650. <https://doi.org/10.1007/s11336-000-0810-3>. The 2PL from a diffusion model and from a race model.\n- van der Maas, H. L. J., Molenaar, D., Maris, G., Kievit, R. A., & Borsboom, D. (2011). Cognitive psychology meets psychometric theory: On the relation between process models for decision making and latent variable models for individual differences. *Psychological Review*, 118(2), 339–356. <https://doi.org/10.1037/a0022749>. What a diffusion process implies for measuring abilities and attitudes.\n- Molenaar, D., Tuerlinckx, F., & van der Maas, H. L. J. (2015). Fitting diffusion item response theory models for responses and response times using the R package diffIRT. *Journal of Statistical Software*, 66(4). <https://doi.org/10.18637/jss.v066.i04>. Software for diffusion item response models.\n- Kang, I., De Boeck, P., & Ratcliff, R. (2022). Modeling conditional dependence of response accuracy and response time with the diffusion item response theory model. *Psychometrika*, 87(2), 725–748. <https://doi.org/10.1007/s11336-021-09819-5>. Variability in drift and starting point as a source of conditional dependence.\n- Brown, S. D., & Heathcote, A. (2008). The simplest complete model of choice response time: Linear ballistic accumulation. *Cognitive Psychology*, 57(3), 153–178. <https://doi.org/10.1016/j.cogpsych.2007.12.002>. The linear ballistic accumulator.\n- Heathcote, A., & Matzke, D. (2022). Winner takes all! What are race models, and why and how should psychologists use them? *Current Directions in Psychological Science*, 31(5), 383–394. <https://doi.org/10.1177/09637214221095852>. A short introduction to race models.\n- Singmann, H., Brown, S., Gretton, M., Heathcote, A., & Fernandez, A. (2014). *rtdists: Response time distributions* [R package]. <https://doi.org/10.32614/CRAN.package.rtdists>. Densities and random draws for the diffusion model and the LBA.\n- Tuerlinckx, F., Molenaar, D., & van der Maas, H. L. J. (2016). Diffusion-based response-time models. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 283–300). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315374512>. A handbook chapter on diffusion models for responses and response times.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`mturkddm_lexical`](https://itemresponsewarehouse.org/tables/mturkddm_lexical/): Ratcliff, R., Hendrickson, A.T. Do data from mechanical Turk subjects replicate accuracy, response time, and diffusion modeling results?. Behav Res 53, 2302–2325 (2021). <https://doi.org/10.3758/s13428-021-01573-x>. Licence: CC BY 4.0.\n- [`motion`](https://itemresponsewarehouse.org/tables/motion/): O’Brien, G., & Yeatman, J. D. (2021). Bridging sensory and language theories of dyslexia: Toward a multifactorial model. Developmental Science, 24(3), e13039. <https://doi.org/10.1111/desc.13039>. Licence: CC BY 4.0.\n- [`credentialform_lnirt`](https://itemresponsewarehouse.org/tables/credentialform_lnirt/): Cizek, G. J., & Wollack, J. A. (Eds.). (2016). Handbook of quantitative methods for detecting cheating on tests. Abingdon, England: Routledge. <https://cran.r-project.org/web/packages/LNIRT/index.html>. Licence: GPL-3.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 9, slides 55–56, which sketch diffusion and race models; the rest is new.\n- **Timing:** about 45 minutes for the core ideas and widgets, and a 30-minute lab. The licensure table takes a minute to download.\n- **Software:** EZ and the random walk are base R. `rtdists` is in the webR repository, but drawing 20,000 trials with a drift per respondent–item pair ran over two minutes locally; the plain walk takes a second or two.\n- **Changed from the outline:** boundary separation is written $\\alpha$, keeping $a$ for the item slope.\n- **Held back:** full or hierarchical fits with across-trial variability (*Going further*); diffusion item response models for test items (problem 4); rapid guessing as a separate process.\n- **Solutions:** held back in `solutions/rt-process-models.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "rt-process-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}