{
  "hash": "b0876783e4a63d3c3bb3084a7153de9d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Item response data and the IRW\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Foundations  \n**Tranche:** preliminary (sets up the course)  \n**Before this:** none  \n**Builds toward:** [The likelihood and logistic regression](likelihood.qmd) · [Classical test theory and reliability](ctt-reliability.qmd)  \n**Starts threads:** IRW tables are long: one row per response (→ [The likelihood and logistic regression](likelihood.qmd) · [Classical test theory and reliability](ctt-reliability.qmd)); Check keying in the documentation and in the data (→ [Classical test theory and reliability](ctt-reliability.qmd)); Errors are slower than correct responses, partly because of where errors happen (→ [Process models for response time: drift diffusion and race models](rt-process-models.qmd) · [Trials as items: tasks, shots, and rotations](trials.qmd))  \n**IRW tables:** [`verbagg`](https://itemresponsewarehouse.org/tables/verbagg/), [`manolika_2021_mini_ipip`](https://itemresponsewarehouse.org/tables/manolika_2021_mini_ipip/), [`rr98_accuracy`](https://itemresponsewarehouse.org/tables/rr98_accuracy/), [`cdm_timss11`](https://itemresponsewarehouse.org/tables/cdm_timss11/), [`pirlsmissing_sirt`](https://itemresponsewarehouse.org/tables/pirlsmissing_sirt/)  \n**From EDUC 252:** slides c1; problem sets PS1#3; code [`c1/irw_data_exploration.R`](https://github.com/ben-domingue/252/blob/main/c1/irw_data_exploration.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n\n```{ojs}\n//| echo: false\nimport {rng, palette} from \"./widgets/irt.js\"\nimport {itemRest} from \"./widgets/irw-data.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nEvery analysis in this course starts from a record of which respondent gave which response to which item. Before fitting a model, we should know how it is stored, what is missing, what rides along, and what a few simple numbers say. Item response data have their surprises (an item scored the opposite way from its neighbours, a respondent who appears hundreds of times, a missing response that was never asked for), and they are far cheaper to find now than after a model has been fit. This lesson introduces the data, the Item Response Warehouse (IRW) that supplies them, and a first look at three IRW tables: yes/no answers on verbal aggression, a five-point Big Five inventory, and thousands of timed perceptual judgements.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- say what item response data are, and what the IRW holds;\n- read an IRW table: what one row is, and what `id`, `item`, `resp` and the optional columns hold;\n- move between long and wide formats, and say what needs a decision along the way;\n- compute and interpret four first descriptives for 0/1 and Likert items;\n- check which way each item runs before adding items up;\n- recognise when a table records more than responses: response times, repeated trials, design columns and covariates.\n\n## Core ideas\n\n### Item response data, and the IRW\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [What is measurement?](measurement.qmd): psychological measurement works through standardized *probes* (items, stimuli, tasks) that draw out responses. From here on every probe is an **item**, whatever its form, and we take the items as given.\n:::\n\nRespondents (usually people) meet items, and each meeting produces a response: a right or wrong answer, a rating from 1 to 5, a key pressed on seeing a patch of pixels. Judging whether items are well written or constructs well defined is a separate job, but a measure's quality rests on it; [Constructs and construct maps](constructs.qmd) and the Validity module take them up.\n\nThe **Item Response Warehouse** ([Domingue et al., 2025](https://doi.org/10.3758/s13428-025-02796-y)) collects such data. (I lead the team that builds it.) The data are open: each table's licence permits reuse, and the code that converted the original files is public ([ben-domingue/irw](https://github.com/ben-domingue/irw)). They are harmonized: every table follows one standard, so code written for one runs on the others. It holds more than 4,000 tables ([index](https://itemresponsewarehouse.org/tables/)), most with metadata and many with item text; [Nadela et al. (2026)](https://doi.org/10.59863/CIJG4549) describe how to use it. This course cites each table's original study in the text and in each lesson's Data sources block.\n\nWhat is in it? A tour, with the lesson that uses each table:\n\n- Achievement tests: [`cdm_timss11`](https://itemresponsewarehouse.org/tables/cdm_timss11/), TIMSS mathematics from Austria, 174 items in 14 booklets ([Linking and equating](equating.qmd)).\n- Personality: [`bfi2_zhang_2025`](https://itemresponsewarehouse.org/tables/bfi2_zhang_2025/), the BFI-2 in four response formats ([Factor analysis I](fa-exploratory.qmd)).\n- Clinical screening: [`c19prc_uk_mcbride_2021_phq9`](https://itemresponsewarehouse.org/tables/c19prc_uk_mcbride_2021_phq9/), the PHQ-9 depression screener in six waves of a UK COVID-19 panel ([What does a score mean?](score-meaning.qmd)).\n- Randomized trials: [`gilbert_meta_12`](https://itemresponsewarehouse.org/tables/gilbert_meta_12/), vocabulary after a grade 2 literacy intervention, with treatment status ([What is measurement?](measurement.qmd)).\n- Cognitive experiments: [`enkavi_2019_stroop`](https://itemresponsewarehouse.org/tables/enkavi_2019_stroop/), the Stroop task, trial by trial, with response times ([Trials as items](trials.qmd)).\n- Child development: [`vocab_assessment_3_to_8_year_old_children`](https://itemresponsewarehouse.org/tables/vocab_assessment_3_to_8_year_old_children/), German receptive vocabulary in children aged 3 to 8 ([Validity as causation](validity-causal.qmd)).\n- Games: [`chess_lnirt`](https://itemresponsewarehouse.org/tables/chess_lnirt/), the Amsterdam Chess Test, with each player's Elo rating ([The likelihood](likelihood.qmd), [The Rasch model](rasch.qmd)).\n- Human judges: [`Forthmann-2024-cleverness_ratings`](https://itemresponsewarehouse.org/tables/forthmann-2024-cleverness_ratings/), five raters scoring the cleverness of uses for everyday objects ([Generalizability theory](g-theory.qmd)).\n- Items written by AI: [`gpt4mcq_young_2025`](https://itemresponsewarehouse.org/tables/gpt4mcq_young_2025/), a multiple-choice quiz written by ChatGPT-4 ([AI and psychometrics](ai-psychometrics.qmd)).\n\n### The data standard\n\nWhat does an IRW table look like? It has three essential columns ([the IRW data standard](https://itemresponsewarehouse.org/standard.html)): `id`, the thing being measured (usually a respondent, sometimes, say, a word); `item`; and `resp`, the response, always a number.\n\nWithin an item, responses are ordinal: higher means more of something (more correct, more agreement). **Dichotomous** responses are 0 or 1; **polytomous** ones have more categories, such as a 1–5 Likert scale. The standard does *not* promise that higher means the same thing on every item: a reverse-worded item, where agreeing means *less* of the trait, may be stored as answered (see *A first look*).\n\nTables are stored **long**: one row per respondent–item response, so 24 answers occupy 24 rows. Why not the familiar spreadsheet, one row per respondent (**wide**)? Because a response can carry information of its own (how long it took, when, which attempt), and in long format each is one more column beside `resp`, while in wide format each would need a second grid. This is what [Wickham (2014)](https://doi.org/10.18637/jss.v059.i10) calls *tidy* data, each observation a row; here the observation is the response.\n\n::: {.callout-note collapse=\"true\"}\n## The optional columns\nWhen a table has them, other columns use fixed names ([the IRW data standard](https://itemresponsewarehouse.org/standard.html)): `rt` (response time, in seconds); `date`; `wave` (the occasion in a longitudinal study, also used for before and after an intervention); `treat` (1 for the treatment group in an experiment); `rater`; `cov_` for respondent covariates, constant within `id` (such as `cov_age`); `itemcov_` for item covariates; and occasion columns such as `block`, `trialnum` or `trial_number`, which tell apart repeated responses by one respondent to one item.\n:::\n\n#### Try it: long and wide\n\nThree respondents, three items, each response timed. Pick a row of the long table, find its cell in the wide one, then delete it.\n\n```{ojs}\n//| echo: false\nlw_long = [\n  {id: 1, item: \"A\", resp: 1, rt: 4.2}, {id: 1, item: \"B\", resp: 0, rt: 9.1}, {id: 1, item: \"C\", resp: 1, rt: \"5.0\"},\n  {id: 2, item: \"A\", resp: 0, rt: 7.7}, {id: 2, item: \"B\", resp: 0, rt: 12.3}, {id: 2, item: \"C\", resp: 1, rt: 6.1},\n  {id: 3, item: \"A\", resp: 1, rt: 3.8}, {id: 3, item: \"B\", resp: 1, rt: 8.4}, {id: 3, item: \"C\", resp: 1, rt: 4.9}\n]\nviewof lw_pick = Inputs.range([1, 9], {value: 5, step: 1, label: \"Row of the long table\"})\nviewof lw_drop = Inputs.toggle({label: \"Delete that row (a missing response)\", value: false})\n```\n\n```{ojs}\n//| echo: false\n{\n  const sel = lw_long[lw_pick - 1];\n  const kept = lw_long.filter((d, i) => !(lw_drop && i === lw_pick - 1));\n  const td = (x, on) => `<td style=\"padding:2px 12px;text-align:center;${on ? `background:${palette.light};font-weight:600` : \"\"}\">${x}</td>`;\n  const th = cols => `<tr>${cols.map(c => `<th style=\"padding:2px 12px;text-align:center\">${c}</th>`).join(\"\")}</tr>`;\n  const longRows = lw_long.map((d, i) => {\n    const on = i === lw_pick - 1;\n    if (on && lw_drop) return `<tr><td colspan=\"5\" style=\"padding:2px 12px;text-align:center;color:${palette.guide}\">(row ${i + 1} deleted)</td></tr>`;\n    return `<tr>${td(i + 1, on)}${td(d.id, on)}${td(d.item, on)}${td(d.resp, on)}${td(d.rt, on)}</tr>`;\n  }).join(\"\");\n  const wideRows = [1, 2, 3].map(id => `<tr>${td(id, false)}${[\"A\", \"B\", \"C\"].map(it => {\n    const r = kept.find(d => d.id === id && d.item === it);\n    return td(r ? r.resp : \"NA\", id === sel.id && it === sel.item);\n  }).join(\"\")}</tr>`).join(\"\");\n  const div = document.createElement(\"div\");\n  div.innerHTML = `<div style=\"display:flex;gap:3rem;flex-wrap:wrap;align-items:flex-start\">\n    <div><strong>Long</strong>: ${kept.length} rows<table>${th([\"row\", \"id\", \"item\", \"resp\", \"rt\"])}${longRows}</table></div>\n    <div><strong>Wide</strong>: 3 rows, one per respondent<table>${th([\"id\", \"A\", \"B\", \"C\"])}${wideRows}</table>\n    <p style=\"max-width:22rem;font-size:0.9em\">The response times have no place in this grid; keeping them would take a second 3 × 3 table.</p></div></div>`;\n  return div;\n}\n```\n\nEach row of the long table is one cell of the wide one. Delete a row and the long table gets shorter, while the wide table keeps its shape and shows an empty (NA) cell. And `rt` has nowhere to go in the wide table.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"An IRW table has 12,205 rows, 30 distinct values of `id` and 33 of `item`. What must be true?\",\n  options: [\n    {text: \"Some respondents answered some items more than once\", correct: true, why: \"There are only $30 \\\\times 33 = 990$ respondent–item pairs, so some pairs have many rows. That is a design with repeated trials, and a column such as `block` or `trialnum` should say which attempt each row is.\"},\n    {text: \"Many responses are missing\", correct: false, why: \"Missing responses make a long table *shorter* than the number of pairs, not longer.\"},\n    {text: \"The table is stored wide\", correct: false, why: \"A wide table with 30 respondents would have 30 rows. IRW tables are always long.\"}\n  ]\n})\n```\n\n### Long to wide, and how lessons read data\n\nMany tools want the wide layout. The reshape is mechanical (base R's `tapply()` or `reshape()`, or `irw_long2resp()` in the irw package), but three things happen along the way.\n\n1. **Missing rows become empty cells**, which need a decision: leave out, score as wrong, or model. Skipping an item differs from never being shown it; when the design decides what is missing, the gaps can often be set aside ([Rubin, 1976](https://doi.org/10.1093/biomet/63.3.581), gives the conditions), as [Linking and equating](equating.qmd) and [Item banks and adaptive testing](item-banks-cat.qmd) do.\n2. **Respondents with no responses carry no information.** A respondent whose every `resp` is empty becomes a row of NAs; every lesson drops them.\n3. **Repeated responses need a rule.** If a respondent met an item a dozen times, the reshape must keep one attempt, average them, or redefine the respondent or item. None is neutral; [Trials as items](trials.qmd) takes this up.\n\n#### Try it: patterns of missingness\n\nThirty respondents and twelve items; dark cells are responses, pale cells missing ones.\n\n```{ojs}\n//| echo: false\nviewof ms_kind = Inputs.radio([\"None\", \"Skipped at random\", \"Two booklets (by design)\", \"Stopped early\"], {value: \"Skipped at random\", label: \"How responses go missing\"})\nviewof ms_share = Inputs.range([0, 0.5], {value: 0.2, step: 0.05, label: \"Share missing (random or stopping)\"})\n```\n\n```{ojs}\n//| echo: false\nms_cells = {\n  const r = rng(28), out = [];\n  const stop = Array.from({length: 30}, () => r.unif());   // each respondent's stopping propensity\n  for (let j = 1; j <= 30; j++) for (let i = 1; i <= 12; i++) {\n    let seen = true;\n    if (ms_kind === \"Skipped at random\") seen = r.unif() >= ms_share;\n    if (ms_kind === \"Two booklets (by design)\") seen = i <= 4 || (j <= 15 ? i <= 8 : i > 8);\n    if (ms_kind === \"Stopped early\") seen = i <= 12 - Math.floor(stop[j - 1] * ms_share * 2 * 12);\n    out.push({respondent: j, item: i, seen});\n  }\n  return out;\n}\nms_neverTogether = {\n  const seen = (j, i) => ms_cells[(j - 1) * 12 + (i - 1)].seen;\n  let n = 0;\n  for (let a = 1; a <= 12; a++) for (let b = a + 1; b <= 12; b++) {\n    let both = false;\n    for (let j = 1; j <= 30; j++) if (seen(j, a) && seen(j, b)) both = true;\n    if (!both) n++;\n  }\n  return n;\n}\nPlot.plot({\n  width: 700, height: 260, padding: 0.05,\n  x: {label: \"Respondent\", tickFormat: d => (d % 5 === 0 ? d : \"\")}, y: {label: \"Item\"},\n  marks: [Plot.cell(ms_cells, {x: \"respondent\", y: \"item\", fill: d => (d.seen ? palette.main : palette.light), inset: 0.5})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Missing: **${(100 * ms_cells.filter(d => !d.seen).length / ms_cells.length).toFixed(0)}%** of cells. The long table would have **${ms_cells.filter(d => d.seen).length}** rows instead of 360. Pairs of items that no respondent answered together: **${ms_neverTogether}** of 66.`\n```\n\nRandom skips scatter the gaps, and every pair of items is still answered together by someone. Two booklets leave a third of the cells empty, and 16 pairs of items are never seen together, so the data say nothing directly about how they relate; linking designs are built this way. Stopping early piles the gaps at the end, for a reason that has to do with the respondent. Real tables show these patterns (checked below). In [`cdm_timss11`](https://itemresponsewarehouse.org/tables/cdm_timss11/), each student took one of 14 booklets and each item sits in two, so 11,886 of the 15,051 pairs of items are never answered by the same student. In [`pirlsmissing_sirt`](https://itemresponsewarehouse.org/tables/pirlsmissing_sirt/), one PIRLS booklet, skips are far from random: items are left blank by anywhere from 1% to 25% of students. And for 134 of its students the blanks in the second passage run to its last item, which looks like stopping early. I found no IRW table I could verify as an adaptive test.\n\n::: {.callout-note collapse=\"true\"}\n## Check these patterns\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Missingness patterns in two more tables (helpers from the top of this file).\n# cdm_timss11: each student took one of 14 booklets; each item is in two booklets.\ntm <- irw_csv(\"cdm_timss11\")\nib <- table(tm$item, tm$booklet) > 0           # item x booklet: does the booklet carry it?\nc(booklets = ncol(ib), items = nrow(ib), booklets_per_item = unique(rowSums(ib)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         booklets             items booklets_per_item \n               14               174                 2 \n```\n\n\n:::\n\n```{.r .cell-code}\ntogether <- ib %*% t(ib)                        # booklets shared by each pair of items\nc(item_pairs = sum(upper.tri(together)), never_together = sum(together[upper.tri(together)] == 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    item_pairs never_together \n         15051          11886 \n```\n\n\n:::\n\n```{.r .cell-code}\n# pirlsmissing_sirt: one PIRLS booklet; missing responses are rows with an empty resp.\npr <- irw_csv(\"pirlsmissing_sirt\")\npr_w <- long2wide(pr)\nround(range(colMeans(is.na(pr_w))), 2)          # share left blank, least and most skipped items\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01 0.25\n```\n\n\n:::\n\n```{.r .cell-code}\n# Respondents whose blanks in the second passage (the last 16 items) run to its end\np2 <- is.na(pr_w[, grep(\"^R31P\", names(pr_w))])\ntrailing <- apply(p2, 1, function(r) any(r) && all(r[which(r)[1]:length(r)]))\nsum(trailing)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 134\n```\n\n\n:::\n:::\n\n:::\n\n**How lessons read data.** Each IRW table's landing page ([`verbagg`'s](https://itemresponsewarehouse.org/tables/verbagg/), for example) has a *Download CSV* link that needs no account; the lessons read it with `read.csv()`. The link names the data version (`v59_0`), so an analysis can be pinned to a release. The real-data code's `irw_csv()` finds the link. The [irw R package](https://itemresponsewarehouse.github.io/Rpkg/) does more but needs a free Redivis account (see *Going further*).\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In a long table, respondent 17 has no row for item 5. After reshaping to wide, what is in that cell, and what does it mean?\",\n  options: [\n    {text: \"NA; the table alone doesn't say whether item 5 was skipped or never shown\", correct: true, why: \"The long table records only the responses that exist. Why one is absent (a skip, a booklet design, running out of time) has to come from the documentation or the pattern of gaps.\"},\n    {text: \"0, because no response counts as wrong\", correct: false, why: \"Scoring an omission as wrong is a decision an analyst may make, but the reshape itself doesn't make it, and for an item that was never shown it would misstate what happened.\"},\n    {text: \"The reshape fails, because the matrix is incomplete\", correct: false, why: \"Wide layouts allow empty cells, and most real datasets have some.\"}\n  ]\n})\n```\n\n### A first look\n\nWith the data wide, one row per respondent, four descriptives give a first look at any table (item means are column means; sum scores are row sums):\n\n1. **Missingness and categories, by item.** An item everyone answered alike says nothing about differences between respondents; an unused category can trouble polytomous models ([Polytomous items](polytomous.qmd)).\n2. **Item means.** For 0/1 items, the proportion of 1s; on a test, a first measure of how easy an item is (the *p*-value of [Classical test theory and reliability](ctt-reliability.qmd), which [The Rasch model](rasch.qmd) replaces with a difficulty). A Likert mean is on the response scale, not a proportion.\n3. **The sum-score distribution.** The simplest score: classical test theory is built on it, and the Rasch model needs nothing more. Its distribution shows any pile-up at floor or ceiling.\n4. **Item-rest correlations**: each item against the sum of the *other* items, positive if the items share something. Including the item itself would inflate the correlation, more so on short tests (problem 1).\n\nAll four assume the items run the same way. Each lesson states its keying once: higher means more of the construct. Reverse-worded items must be flipped (on a 1–5 scale, $x \\to 6 - x$) before sums or item-rest correlations mean anything.\n\n#### Try it: keying\n\nSix invented respondents rate four Mini-IPIP Extraversion items from 1 (strongly disagree) to 5 (strongly agree): \"Am the life of the party\", \"Don't talk a lot\", \"Talk to a lot of different people at parties\" and \"Keep in the background\" ([Donnellan et al., 2006](https://doi.org/10.1037/1040-3590.18.2.192); wording from the public-domain [IPIP key](https://ipip.ori.org/MiniIPIPKey.htm)). The second and fourth are worded in reverse.\n\n```{ojs}\n//| echo: false\nviewof ky_key = Inputs.toggle({label: \"Key the reversed items (6 − x)\", value: false})\n```\n\n```{ojs}\n//| echo: false\n{\n  const items = [\"Life of the party\", \"Don't talk a lot (R)\", \"Talk to many at parties\", \"Keep in the background (R)\"];\n  const raw = [[5, 1, 4, 2], [4, 2, 5, 3], [4, 3, 3, 2], [3, 2, 3, 4], [2, 4, 3, 4], [2, 5, 1, 4]];\n  const X = raw.map(r => r.map((x, j) => (ky_key && j % 2 ? 6 - x : x)));\n  const ir = itemRest(X);\n  const cell = (x, on, bold) => `<td style=\"padding:3px 12px;text-align:center;${on ? `background:${palette.light};` : \"\"}${bold ? \"font-weight:600;\" : \"\"}\">${x}</td>`;\n  const head = `<tr><th style=\"padding:3px 12px\">Respondent</th>${items.map(t => `<th style=\"padding:3px 12px;text-align:center\">${t}</th>`).join(\"\")}<th style=\"padding:3px 12px\">Sum</th></tr>`;\n  const rows = X.map((r, i) => `<tr>${cell(i + 1)}${r.map((x, j) => cell(x, ky_key && j % 2)).join(\"\")}${cell(r.reduce((a, b) => a + b, 0), false, true)}</tr>`).join(\"\");\n  const irRow = `<tr><td style=\"padding:3px 12px\"><em>Item-rest r</em></td>${ir.map(v => `<td style=\"padding:3px 12px;text-align:center;font-weight:600;color:${v < 0 ? palette.contrast : palette.main}\">${v.toFixed(2)}</td>`).join(\"\")}<td></td></tr>`;\n  const div = document.createElement(\"div\");\n  div.innerHTML = `<table>${head}${rows}${irRow}</table>`;\n  return div;\n}\n```\n\nUnkeyed, the sums barely differ (12 to 14), because agreeing with one kind of item cancels disagreeing with the other, and every item-rest correlation is negative. Keyed, the sums spread from 6 to 18, ordering respondents from most to least extraverted, and every item-rest correlation is positive.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A 1–5 Likert item has mean 4.5. What can you conclude?\",\n  options: [\n    {text: \"Most respondents chose 4 or 5\", correct: true, why: \"A mean of 4.5 on a 1–5 scale is possible only if responses pile up at the top: at least half must be 5s, and at least three in four must be 4s or 5s.\"},\n    {text: \"90% of respondents agreed\", correct: false, why: \"The mean of a Likert item is on the response scale, not a proportion. It is a proportion only for 0/1 items.\"},\n    {text: \"The item measures the construct well\", correct: false, why: \"The mean says how the item is answered, not whether it measures the construct. An item nearly everyone agrees with may tell us little about differences between respondents.\"}\n  ]\n})\n```\n\n### More than responses\n\nMany tables record more than `resp`. **Response time** is one: how long someone took is data too ([Response times](response-time.qmd)). Design columns (`treat`, `wave`, sometimes `cluster_id` for a school) say how data were collected ([Invariance and experience](invariance-experience.qmd)). Covariates (`cov_`) let us compare groups item by item ([Differential item functioning](dif.qmd)) or explain responses ([Explanatory item response models](explanatory-irt.qmd)). And many tables have [item text](https://itemresponsewarehouse.org/itemtext.html).\n\nNor are items always questions. In a perception experiment the item is a condition, a stimulus of a given strength, met many times as trials ([Ratcliff & Rouder, 1998](https://doi.org/10.1111/1467-9280.00067)). The brightness experiment below is of that kind.\n\n## Simulate\n\nThe code builds a long table (each respondent with a propensity to say yes, each item with its own popularity), deletes 5% of rows, reshapes, and takes the first look, in base R.\n\nWith the seed as written, item means run from 0.23 to 0.80 and the median item-rest correlation is 0.28. Set `spread <- 0`, so every respondent has the same propensity: the means barely move, but the correlations collapse (median 0.03), since nothing about a respondent carries over between items. With `spread <- 2` the median rises to 0.54. Positive item-rest correlations are the first sign that items measure something in common.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-15\n# Simulate item responses in IRW format, reshape them, and take a first look.\n# Each respondent has a propensity to say yes; each item has its own popularity.\n# With a spread of propensities, items hang together; with none, they don't.\n# Base R only. Adapted from ben-domingue/252: c1/irw_data_exploration.R.\nset.seed(252)\nn_resp  <- 500    # respondents\nn_items <- 10     # items\nspread  <- 1      # SD of the respondents' propensities (try 0, then 2)\n\npropensity <- rnorm(n_resp, 0, spread)\npopularity <- seq(-1.5, 1.5, length.out = n_items)   # easy-to-endorse items at the top\n\n# Long format, as the IRW stores it: one row per response.\ndf <- expand.grid(id = 1:n_resp, item = sprintf(\"item%02d\", 1:n_items), stringsAsFactors = FALSE)\np  <- plogis(propensity[df$id] + popularity[match(df$item, sprintf(\"item%02d\", 1:n_items))])\ndf$resp <- rbinom(nrow(df), 1, p)\ndf <- df[sample(nrow(df)), ]                       # row order carries no information\nhead(df)\n\n# Delete 5% of responses at random: in long format, a missing response is a missing row.\ndf <- df[runif(nrow(df)) > 0.05, ]\n\n# Wide format: one row per respondent. The deleted rows reappear as NA cells.\nwide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\nwide <- as.data.frame(wide[, order(colnames(wide))])\ncat(\"long rows:\", nrow(df), \"  wide:\", nrow(wide), \"x\", ncol(wide),\n    \"  empty cells:\", sum(is.na(wide)), \"\\n\")\n\n# The first look: missingness, item means, sum scores, item-rest correlations.\n# (With missing cells, the sum counts only the items a respondent answered.)\ntot <- rowSums(wide, na.rm = TRUE)\nlook <- data.frame(\n  missing   = colMeans(is.na(wide)),\n  mean      = colMeans(wide, na.rm = TRUE),\n  item_rest = sapply(names(wide), function(i)\n    cor(wide[[i]], tot - ifelse(is.na(wide[[i]]), 0, wide[[i]]), use = \"complete.obs\")))\nprint(round(look, 2))\nhist(tot, breaks = seq(-0.5, n_items + 0.5, 1), col = \"#2780e3\", border = \"white\",\n     main = paste(\"Sum scores, spread =\", spread), xlab = \"Number of yes responses\")\ncat(\"median item-rest correlation:\", round(median(look$item_rest), 2), \"\\n\")\n\n```\n:::\n\n\n[Download this code](code/irw-data-sim.R) to run it in your own R session.\n\n## With real data\n\n[verbagg](https://itemresponsewarehouse.org/tables/verbagg/) is the main example, with 0/1 responses; [manolika_2021_mini_ipip](https://itemresponsewarehouse.org/tables/manolika_2021_mini_ipip/) is the contrast for Likert responses and keying; [rr98_accuracy](https://itemresponsewarehouse.org/tables/rr98_accuracy/) is the contrast for response times and trials. The code is base R ([download it](code/irw-data-irw.R)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Every IRW table has a landing page, itemresponsewarehouse.org/tables/<name>/,\n# with a \"Download CSV\" link that needs no account. The link names the version\n# of the data (e.g. v59_0), so reading it off the page gets the current release.\nirw_csv_url <- function(table) {\n  page <- readLines(paste0(\"https://itemresponsewarehouse.org/tables/\", tolower(table), \"/\"),\n                    warn = FALSE)\n  hit <- regmatches(page, regexpr('https://redivis\\\\.com/api/v1/tables/[^\"]+format=csv', page))\n  hit[[1]]\n}\nirw_csv <- function(table) read.csv(irw_csv_url(table))\n\n# Long (one row per response) to wide (one row per respondent, one column per\n# item). A respondent-item pair with no row becomes an empty (NA) cell.\nlong2wide <- function(df) {\n  wide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\n  as.data.frame(wide[, order(colnames(wide))])\n}\n# Correlation of each item with the sum of the *other* items.\nitem_rest <- function(resp) {\n  tot <- rowSums(resp)\n  sapply(names(resp), function(i) cor(resp[[i]], tot - resp[[i]], use = \"complete.obs\"))\n}\n```\n:::\n\n\n### Verbal aggression: 0/1 responses\n\nThe verbal aggression data, from [De Boeck and Wilson (2004)](https://doi.org/10.1007/978-1-4757-3990-9) and distributed with the lme4 R package ([Bates et al., 2015](https://doi.org/10.18637/jss.v067.i01)), come from 316 Belgian psychology students (per the [psychotools](https://doi.org/10.32614/CRAN.package.psychotools) documentation). Each item pairs one of four frustrating situations (two where someone else is to blame, such as a bus that fails to stop; two where you are) with a reaction (cursing, scolding, shouting), in two modes: would you *want* to, and would you *do* it? `S2WantCurse` is situation 2, want, curse. Keying: 1 means the reaction was reported.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nirw_csv_url(\"verbagg\")        # the version-pinned link on the landing page\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v59_0.verbagg/rows?format=csv\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nva <- irw_csv(\"verbagg\")\nhead(va)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| resp|item        | id|\n|----:|:-----------|--:|\n|    0|S1DoScold   |  1|\n|    0|S2DoScold   |  1|\n|    0|S2DoShout   |  1|\n|    0|S3DoScold   |  1|\n|    0|S3WantScold |  1|\n|    0|S1WantScold |  1|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(rows = nrow(va), respondents = length(unique(va$id)), items = length(unique(va$item)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       rows respondents       items \n       7584         316          24 \n```\n\n\n:::\n:::\n\n\nOne row per response: 316 × 24 = 7,584. Two gentle notes. Respondents answered no, perhaps or yes, and the IRW stores lme4's two-category version, with \"perhaps\" and \"yes\" both 1 ([processing script](https://github.com/ben-domingue/irw/blob/main/data/verbagg.R)); lme4's covariates (trait anger, gender) aren't carried over. And one item is spelled `S4wantCurse`, so match item names ignoring case.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nva_w <- long2wide(va)\ndim(va_w)                     # one row per respondent, one column per item\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 316  24\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nva_w[1:4, 1:5]\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| S1DoCurse| S1DoScold| S1DoShout| S1WantCurse| S1WantScold|\n|---------:|---------:|---------:|-----------:|-----------:|\n|         1|         0|         1|           0|           0|\n|         0|         0|         0|           0|           0|\n|         0|         1|         1|           1|           1|\n|         1|         1|         1|           1|           1|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsum(is.na(va_w))              # empty cells: respondent-item pairs with no row\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# 1. Missingness and categories, item by item\ntable(missing = colSums(is.na(va_w)), categories = sapply(va_w, function(x) length(unique(na.omit(x)))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       categories\nmissing  2\n      0 24\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# 2. Item means (for 0/1 items, the proportion who said yes)\np <- sort(colMeans(va_w, na.rm = TRUE))\nround(c(head(p, 3), tail(p, 3)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  S3DoShout   S4DoShout S3WantShout   S1DoCurse S1WantCurse S2WantCurse \n       0.09        0.18        0.24        0.71        0.71        0.79 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# 3. The sum-score distribution\nr <- rowSums(va_w)\nround(c(mean = mean(r), sd = sd(r), min = min(r), max = max(r)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean   sd  min  max \n11.4  5.7  0.0 24.0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(at_0 = sum(r == 0), at_24 = sum(r == 24))   # respondents at the floor and the ceiling\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n at_0 at_24 \n    4     5 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# 4. Item-rest correlations\nir <- item_rest(va_w)\nround(c(min = min(ir), median = median(ir), max = max(ir)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   min median    max \n  0.28   0.46   0.58 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nop <- par(mfrow = c(1, 3), mar = c(4, 4, 2, 1))\nhist(p, breaks = seq(0, 1, 0.1), col = \"#2780e3\", border = \"white\",\n     main = \"Item means\", xlab = \"Proportion saying yes\")\nhist(r, breaks = seq(-0.5, 24.5, 1), col = \"#2780e3\", border = \"white\",\n     main = \"Sum scores\", xlab = \"Number of yes responses (of 24)\")\nhist(ir, breaks = seq(0, 1, 0.05), col = \"#2780e3\", border = \"white\",\n     main = \"Item-rest correlations\", xlab = \"Correlation\")\n```\n\n::: {.cell-output-display}\n![](irw-data_files/figure-html/verbagg-look-1.png){width=864}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npar(op)\n```\n:::\n\n\nNo cell is empty; every item has both categories; item means run from 0.09 to 0.79. Sum scores span 0 to 24 (mean 11.4), with only 4 respondents at the floor and 5 at the ceiling. Every item-rest correlation is positive (0.28 to 0.58, median 0.46). Against the simulation's 0.28 and 0.54, these items hang together fairly well.\n\nWhich items are reported most? The design lets us ask.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Across the 24 items, which do respondents report more often: *wanting* to react aggressively, or actually *doing* so? And which of the three behaviours (curse, scold, shout) is reported least?\",\n  choices: [\"Want more; shout least\", \"Want more; curse least\", \"Do more; shout least\", \"Do more; curse least\"],\n  answer: \"Want more; shout least\",\n  reveal: \"Wanting is reported more than doing (item means 0.53 against 0.42), and shouting least (0.30, against 0.47 for scolding and 0.65 for cursing). The gap between want and do is largest for shouting, as the table below shows.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Item names encode the design: situation (S1-S4), want or do, and the behaviour.\n# One item is spelled S4wantCurse, so match the mode ignoring case.\nmode <- ifelse(grepl(\"want\", names(p), ignore.case = TRUE), \"want\", \"do\")\nbehaviour <- sub(\".*(Curse|Scold|Shout)$\", \"\\\\1\", names(p))\nround(tapply(p, mode, mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  do want \n0.42 0.53 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(p, behaviour, mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCurse Scold Shout \n 0.65  0.47  0.30 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(p, list(behaviour, mode), mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        do want\nCurse 0.61 0.70\nScold 0.43 0.51\nShout 0.22 0.39\n```\n\n\n:::\n:::\n\n\nWanting beats doing for every behaviour, most of all for shouting (0.39 against 0.22). [Smits, De Boeck and Vansteelandt (2004)](https://doi.org/10.1002/per.529) study this gap as the *inhibition* of verbal aggression; [Explanatory item response models](explanatory-irt.qmd) models it.\n\n### The Mini-IPIP: Likert responses, and keying\n\nThe Mini-IPIP ([Donnellan et al., 2006](https://doi.org/10.1037/1040-3590.18.2.192)) measures the Big Five traits with four items each from the International Personality Item Pool, which is in the public domain ([Goldberg et al., 2006](https://doi.org/10.1016/j.jrp.2005.08.007); [IPIP permissions](https://ipip.ori.org/newPermission.htm)). These responses, rated 1 (strongly disagree) to 5 (strongly agree), come from a study of personality and taste in films and books ([Manolika, 2023](https://doi.org/10.1037/ppm0000394); data: [Manolika, 2021](https://doi.org/10.7910/DVN/23NDKX)), with `cov_gender` and `cov_age`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nip <- irw_csv(\"manolika_2021_mini_ipip\")\nhead(ip)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| id|item     | resp|cov_gender | cov_age|\n|--:|:--------|----:|:----------|-------:|\n|  1|IPIP_06R |    1|woman      |      19|\n|  1|IPIP_08R |    1|woman      |      19|\n|  1|IPIP_15R |    1|woman      |      19|\n|  1|IPIP_18R |    1|woman      |      19|\n|  1|IPIP_01  |    1|woman      |      19|\n|  1|IPIP_20R |    1|woman      |      19|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(rows = nrow(ip), respondents = length(unique(ip$id)), items = length(unique(ip$item)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       rows respondents       items \n       7720         386          20 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(ip$resp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   1    2    3    4    5 \n 310 1006 1675 2737 1992 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nip_w <- long2wide(ip)\nround(sort(colMeans(ip_w)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIPIP_16R IPIP_09R  IPIP_03 IPIP_08R  IPIP_14 IPIP_19R IPIP_15R IPIP_10R IPIP_06R  IPIP_04 \n     3.0      3.0      3.0      3.4      3.5      3.5      3.5      3.5      3.6      3.6 \nIPIP_18R  IPIP_01  IPIP_11  IPIP_05  IPIP_13 IPIP_20R  IPIP_12  IPIP_02 IPIP_07R IPIP_17R \n     3.7      3.7      3.8      3.8      3.9      3.9      4.0      4.1      4.3      4.5 \n```\n\n\n:::\n:::\n\n\nNothing is missing (386 × 20 = 7,720). Item means run from 3.0 to 4.5, the highest for `IPIP_17R`, \"Am not really interested in others\" ([Donnellan et al., 2006](https://doi.org/10.1037/1040-3590.18.2.192); wording checked against the [IPIP scoring key](https://ipip.ori.org/MiniIPIPKey.htm)). Taken at face value, most respondents strongly agree that they aren't interested in other people.\n\nThe ten items ending in `R` are worded in reverse. Stored as answered, or already reversed? The deposit's SPSS file labels every item, `R` items included, 1 = strongly disagree to 5 = strongly agree, suggesting the former. If so, each `R` item would correlate *negatively* with its trait's forward items.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The Mini-IPIP's scoring key (Donnellan et al., 2006): four items per trait,\n# two worded each way. Items whose names end in R are the reverse-worded ones.\ntraits <- list(\n  Extraversion      = c(\"IPIP_01\", \"IPIP_06R\", \"IPIP_11\", \"IPIP_16R\"),\n  Agreeableness     = c(\"IPIP_02\", \"IPIP_07R\", \"IPIP_12\", \"IPIP_17R\"),\n  Conscientiousness = c(\"IPIP_03\", \"IPIP_08R\", \"IPIP_13\", \"IPIP_18R\"),\n  Neuroticism       = c(\"IPIP_04\", \"IPIP_09R\", \"IPIP_14\", \"IPIP_19R\"),\n  Intellect         = c(\"IPIP_05\", \"IPIP_10R\", \"IPIP_15R\", \"IPIP_20R\"))\n# If the R items were stored as answered, each would correlate negatively with\n# the forward items of its own trait. Are any within-trait correlations negative?\nwithin <- unlist(lapply(traits, function(t) {\n  R <- cor(ip_w[, t]); R[upper.tri(R)]\n}))\nround(range(within), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.18 0.59\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Item-rest correlations within each trait, as stored\nround(unlist(lapply(traits, function(t) item_rest(ip_w[, t]))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Extraversion.IPIP_01      Extraversion.IPIP_06R       Extraversion.IPIP_11 \n                      0.58                       0.56                       0.38 \n     Extraversion.IPIP_16R      Agreeableness.IPIP_02     Agreeableness.IPIP_07R \n                      0.51                       0.59                       0.49 \n     Agreeableness.IPIP_12     Agreeableness.IPIP_17R  Conscientiousness.IPIP_03 \n                      0.50                       0.51                       0.28 \nConscientiousness.IPIP_08R  Conscientiousness.IPIP_13 Conscientiousness.IPIP_18R \n                      0.44                       0.46                       0.48 \n       Neuroticism.IPIP_04       Neuroticism.IPIP_09R        Neuroticism.IPIP_14 \n                      0.42                       0.31                       0.46 \n      Neuroticism.IPIP_19R          Intellect.IPIP_05         Intellect.IPIP_10R \n                      0.36                       0.49                       0.40 \n        Intellect.IPIP_15R         Intellect.IPIP_20R \n                      0.38                       0.48 \n```\n\n\n:::\n:::\n\n\nEvery within-trait correlation is positive (0.18 to 0.59), as is every within-trait item-rest correlation. The ten `R` items arrive **already reverse-scored**: higher means more of the trait on all 20, and `IPIP_17R`'s 4.5 means most respondents *disagreed*. (The IRW's [item-text notes](https://github.com/ben-domingue/irw/blob/main/itemtext/itemtables/batch_342/notes.csv) agree, and record that respondents answered a Greek translation.) Keying: higher means more Extraversion, Agreeableness, Conscientiousness, Neuroticism (not emotional stability) or Intellect.\n\nHow should an analyst decide which way items run? One route trusts the documentation, the scoring key and codebook; the other reads the direction off the data, from signs like these. My rule: before summing a scale, I find out from the documentation which way each item should run, and then I check it in the data, because neither is enough alone. Here the codebook would have had us reverse ten items twice; [Classical test theory and reliability](ctt-reliability.qmd) meets an item the data can't settle.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# One sum score per trait (4 items each, so 4 to 20), not one for all 20 items.\nsums <- sapply(traits, function(t) rowSums(ip_w[, t]))\nround(apply(sums, 2, function(s) c(mean = mean(s), sd = sd(s))), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Extraversion Agreeableness Conscientiousness Neuroticism Intellect\nmean         14.0          17.0              14.0          14      14.7\nsd            3.3           2.4               3.1           3       2.8\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Covariates ride along in every row; one value per respondent.\ncov <- ip[!duplicated(ip$id), c(\"id\", \"cov_gender\", \"cov_age\")]\ntable(cov$cov_gender, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n        man woman \n    1   107   278 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsummary(cov$cov_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.     NAs \n   18.0    19.0    21.0    21.5    22.0    35.0       2 \n```\n\n\n:::\n:::\n\n\nFive traits means five sums of four items (4 to 20), not one of 20; Agreeableness is highest and least spread (17.0, SD 2.4). Covariates repeat on each of a respondent's rows, so we keep one row per `id`: most respondents are women, median age 21.\n\n### Brightness judgements: response times and trials\n\nIn [Ratcliff and Rouder's (1998)](https://doi.org/10.1111/1467-9280.00067) first experiment, observers judged whether a square of pixels was bright or dark. Brightness, the share of white pixels, had 33 levels from all black (0) to all white (32), and each display came from one of two overlapping distributions; a response was correct if it named the right one. The data come with the rtdists R package ([Singmann et al., 2014](https://doi.org/10.32614/CRAN.package.rtdists)); the IRW keeps the blocks with accuracy instructions ([processing script](https://github.com/ben-domingue/irw/blob/main/data/rr98.R)). Keying: 1 is correct.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nrr <- irw_csv(\"rr98_accuracy\")\nhead(rr)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|id    |item | resp|   rt| block| trialnum|\n|:-----|:----|----:|----:|-----:|--------:|\n|kr 8  |i 0  |    1| 0.41|     1|       25|\n|nh 6  |i 0  |    1| 0.46|     3|       44|\n|jf 4  |i 0  |    1| 0.59|     6|      102|\n|jf 11 |i 10 |    1| 0.45|     1|      102|\n|jf 4  |i 10 |    1| 0.68|     1|       61|\n|kr 2  |i 10 |    1| 1.94|     2|       96|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(rows = nrow(rr), respondents = length(unique(rr$id)), items = length(unique(rr$item)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       rows respondents       items \n      12205          30          33 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# id is observer plus session (\"jf 2\" is observer jf's session 2)\ntable(observer = sub(\" .*\", \"\", unique(rr$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nobserver\njf kr nh \n10 10 10 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Each respondent meets each item many times: rows per id-item pair\nsummary(as.vector(table(rr$id, rr$item)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    0.0     5.0    12.0    12.3    18.0    62.0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# block and trialnum say which meeting a row is: no id-item-block-trial repeats\nsum(duplicated(rr[, c(\"id\", \"item\", \"block\", \"trialnum\")]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nHere `id` is not a person but one of three observers' sessions (\"jf 2\" is jf's second), 30 in all. The 33 items are brightness levels, repeated as trials: a median of 12 rows per respondent–item pair, told apart by `block` and `trialnum`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlevel <- as.numeric(sub(\"i \", \"\", rr$item))     # brightness level, 0 to 32\nacc <- tapply(rr$resp, level, mean)\nround(acc[c(\"0\", \"1\", \"15\", \"16\", \"31\", \"32\")], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   0    1   15   16   31   32 \n0.95 0.93 0.50 0.52 0.98 0.95 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(rr$resp, sub(\" .*\", \"\", rr$id), mean), 2)   # by observer\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  jf   kr   nh \n0.72 0.72 0.73 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nplot(as.numeric(names(acc)), acc, pch = 19, col = \"#2780e3\", ylim = c(0.4, 1),\n     xlab = \"Brightness level (proportion of white pixels x 32)\", ylab = \"Proportion correct\")\nabline(h = 0.5, lty = 2, col = \"#999\")\n```\n\n::: {.cell-output-display}\n![](irw-data_files/figure-html/rr98-accuracy-1.png){width=576}\n:::\n:::\n\n\nAccuracy is about 0.95 at the extremes and 0.50 in the middle, where either distribution is equally likely. The observers are almost indistinguishable (0.72 to 0.73).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Response time in seconds. The distribution has a long right tail, so compare medians.\nround(quantile(rr$rt, c(0.5, 0.99, 1)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  50%   99%  100% \n 0.58  3.66 14.07 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Ratcliff and Rouder set aside responses faster than 0.2 s or slower than 2.5 s\n# (rtdists documentation); the IRW table keeps every response.\nmean(rr$rt < 0.2 | rr$rt > 2.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.033\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(rr$rt, factor(rr$resp, labels = c(\"error\", \"correct\")), median), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  error correct \n   0.65    0.56 \n```\n\n\n:::\n:::\n\n\nResponse times have a long right tail (median 0.58 s, maximum 14 s). Ratcliff and Rouder set aside responses outside 0.2–2.5 s ([rtdists documentation](https://search.r-project.org/CRAN/refmans/rtdists/html/rr98.html)); the IRW keeps them (3.3% of rows), so we compare medians. **Errors are slower than correct responses**: 0.65 s against 0.56 s.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same comparison within each brightness level\nmed <- sapply(split(rr, level), function(d)\n  c(error = median(d$rt[d$resp == 0]), correct = median(d$rt[d$resp == 1]),\n    n_error = sum(d$resp == 0)))\ngap <- med[\"error\", ] - med[\"correct\", ]\nsum(gap > 0)                                         # levels where errors are slower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(weighted.mean(gap, med[\"n_error\", ]), 2)       # average gap, weighted by errors\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(cor(1 - acc, tapply(rr$rt, level, median)), 2) # harder levels are slower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nplot(as.numeric(colnames(med)), med[\"correct\", ], type = \"b\", pch = 19, col = \"#2780e3\",\n     ylim = range(med[1:2, ]), xlab = \"Brightness level\", ylab = \"Median response time (s)\")\nlines(as.numeric(colnames(med)), med[\"error\", ], type = \"b\", pch = 17, col = \"#c2410c\")\nlegend(\"topright\", c(\"Correct\", \"Error\"), col = c(\"#2780e3\", \"#c2410c\"), pch = c(19, 17), lty = 1, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](irw-data_files/figure-html/rr98-bylevel-1.png){width=576}\n:::\n:::\n\n\nWithin a brightness level, though, errors are slower by only about 0.02 s (at 22 of the 33 levels), so most of the pooled gap comes from errors crowding into the hard levels, which are slow for every response (across levels, error rate and median time correlate at 0.95). [Response time and the speed-accuracy tradeoff](response-time.qmd) takes up that aggregation, and [Trials as items](trials.qmd) and [Response-time process models](rt-process-models.qmd) return to this table.\n\n## Problems\n\n1. **Item-total against item-rest.** For $k$ items with equal variances and pairwise correlation $\\rho$, derive the item-total and item-rest correlations. How much does including the item inflate the correlation when $k = 5$? When $k = 40$? Check on `verbagg`.\n2. **Response time and difficulty (PS1#3a).** In `rr98_accuracy` (or another timed table; with a Redivis account, `irw::irw_filter(var = \"rt\", n_categories = 2, density = NULL)` lists them), compute each item's median response time for correct and incorrect responses, and its proportion correct. Are harder items slower? What complicates the inference?\n3. **Long or wide?** Give two situations where wide format is the better store, and two things long format makes easy.\n4. **Your own data.** A 12-item Likert questionnaire, four items reverse-worded, is answered before and after an intervention by two randomized groups, with each respondent's age. Give the IRW-format columns and three example rows, and say how you would record which items are reverse-worded and whether they have been reversed.\n5. **A first look of your own (PS1#3c).** Pick an IRW table, compute the four descriptives, and write a paragraph on what they show, ending with a question they can't answer.\n6. **Challenge: wording and endorsement (PS1#3b).** Using the Mini-IPIP's item text ([IPIP scoring key](https://ipip.ori.org/MiniIPIPKey.htm)), relate a feature of the wording (length, negation) to the item means, as stored and with the reverse-scoring undone. With 20 items, what could this show, and what not? The IRW vignette on [item language and difficulty](https://itemresponsewarehouse.org/vignettes/item_text_difficulty.html) asks a similar question across many tests.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Item%20response%20data%20and%20the%20IRW%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20item%20response%20data%20and%20the%20Item%20Response%20Warehouse%20%28IRW%29%3A%20the%20IRW%20data%20standard%20%28id%2C%20item%2C%20resp%2C%20stored%20long%2C%20with%20optional%20columns%20such%20as%20rt%2C%20wave%2C%20treat%20and%20cov_%20covariates%29%2C%20reshaping%20long%20to%20wide%20and%20what%20can%20go%20missing%2C%20four%20first%20descriptives%20%28missingness%20and%20categories%2C%20item%20means%2C%20sum%20scores%2C%20item-rest%20correlations%29%2C%20checking%20the%20keying%20of%20reverse-worded%20items%2C%20and%20response%20times%20and%20repeated%20trials%2C%20with%20examples%20in%20base%20R%20on%20verbal%20aggression%2C%20the%20Mini-IPIP%20and%20a%20brightness-discrimination%20experiment.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Domingue, B. W., et al. (2025). An introduction to the Item Response Warehouse (IRW): A resource for enhancing data usage in psychometrics. *Behavior Research Methods*, 57(10), 276. <https://doi.org/10.3758/s13428-025-02796-y>. The IRW and its data standard. The IRW asks users to cite the original data, and invites them to cite this paper.\n- Nadela, S., Lee, H., Jain, N., Gupta, A., Zhang, X., & Domingue, B. (2026). The Item Response Warehouse: What it is, how to use it, and targets for potential improvements. *Chinese/English Journal of Educational Measurement and Evaluation*, 7(1). <https://doi.org/10.59863/CIJG4549>. A practical guide.\n- The [irw R package](https://itemresponsewarehouse.github.io/Rpkg/). With a free Redivis account, `irw::irw_fetch(\"verbagg\")` fetches a table, `irw_filter()` finds tables by metadata and `irw_itemtext()` fetches item text. `irw_long2resp()` reshapes, but by default drops `cov_` columns and respondents who answered under 10% of items.\n- Wickham, H. (2014). Tidy data. *Journal of Statistical Software*, 59(10). <https://doi.org/10.18637/jss.v059.i10>. Why one observation per row.\n- Rubin, D. B. (1976). Inference and missing data. *Biometrika*, 63(3), 581–592. <https://doi.org/10.1093/biomet/63.3.581>. When missingness can be ignored.\n- De Boeck, P., & Wilson, M. (Eds.). (2004). *Explanatory item response models*. Springer. <https://doi.org/10.1007/978-1-4757-3990-9>. The book the verbal aggression data illustrate.\n- Donnellan, M. B., Oswald, F. L., Baird, B. M., & Lucas, R. E. (2006). The Mini-IPIP scales. *Psychological Assessment*, 18(2), 192–203. <https://doi.org/10.1037/1040-3590.18.2.192>. The Mini-IPIP and its key.\n- Goldberg, L. R., et al. (2006). The international personality item pool and the future of public-domain personality measures. *Journal of Research in Personality*, 40(1), 84–96. <https://doi.org/10.1016/j.jrp.2005.08.007>. Why IPIP items are free to quote.\n- Ratcliff, R., & Rouder, J. N. (1998). Modeling response times for two-choice decisions. *Psychological Science*, 9(5), 347–356. <https://doi.org/10.1111/1467-9280.00067>. The brightness experiment and a model for it.\n- IRW vignettes: [response time and accuracy](https://itemresponsewarehouse.org/vignettes/rt_imv.html) across many tables; [item language and difficulty](https://itemresponsewarehouse.org/vignettes/item_text_difficulty.html).\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`verbagg`](https://itemresponsewarehouse.org/tables/verbagg/): De Boeck and Wilson (2004), Explanatory Item Response Models, Springer. <https://doi.org/10.1007/978-1-4757-3990-9>. Licence: GPL-3.0.\n- [`manolika_2021_mini_ipip`](https://itemresponsewarehouse.org/tables/manolika_2021_mini_ipip/): Manolika, M. (2021). The Big Five and Beyond: Which Personality Traits Do Predict Movie and Reading Preferences? [Data set]. Harvard Dataverse. <https://doi.org/10.7910/DVN/23NDKX>. Licence: CC0 1.0.\n- [`rr98_accuracy`](https://itemresponsewarehouse.org/tables/rr98_accuracy/): Ratcliff, R., & Rouder, J. N. (1998). Modeling Response Times for Two-Choice Decisions. Psychological Science, 9(5), 347-356. <http://doi.org/10.1111/1467-9280.00067>. Licence: GPL-3.0.\n- [`cdm_timss11`](https://itemresponsewarehouse.org/tables/cdm_timss11/): George, A. C., & Robitzsch, A. (2014). Multiple group cognitive diagnosis models, with an emphasis on differential item functioning. Psychological Test and Assessment Modeling, 56(4), 405-432. <https://cran.r-project.org/web/packages/CDM/index.html>. Licence: GPL-3.0.\n- [`pirlsmissing_sirt`](https://itemresponsewarehouse.org/tables/pirlsmissing_sirt/): Robitzsch A (2022). sirt: Supplementary Item Response Theory Models. R package version 3.12-66, <https://CRAN.R-project.org/package=sirt>. <https://cran.r-project.org/web/packages/sirt/index.html>. Licence: GPL-3.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 1 (slides c1, \"How does psychological measurement work in practice?\" through \"A descriptive look at IRW data\"), PS1#3, and `c1/irw_data_exploration.R` in `ben-domingue/252`.\n- **Timing:** core ideas and widgets about 40 minutes; the three tables a 30-minute lab.\n- **Changed from 252:** the script used `chess_lnirt`, `irw::irw_fetch()` and item-*total* correlations. This lesson uses three tables for three kinds of response, reads the tokenless CSV (no account needed), uses item-rest correlations and turns item-total into problem 1. The composition effect in `rr98_accuracy` is new.\n- **Held back:** probes are in [What is measurement?](measurement.qmd); item analysis proper in [Classical test theory and reliability](ctt-reliability.qmd); `irw_filter()` in the deep dives.\n- **Item text:** IPIP items are public domain, so the lesson quotes one; the verbal aggression items are not openly licensed, so their situations are described.\n- **Solutions:** held back in `solutions/irw-data.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "irw-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}