{
  "hash": "972ab0064a680b4faeef6633cc2da752",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Measurement invariance under treatment and life events\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Fairness and invariance  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [Differential item functioning](dif.qmd)  \n**Builds toward:** none  \n**Picks up threads:** A group difference is impact unless the measure works differently (from [Fairness in testing: bias, impact, and measurement invariance](fairness.qmd)); Items can function differently by treatment (from [Differential item functioning](dif.qmd))  \n**IRW tables:** [`gilbert_meta_20`](https://itemresponsewarehouse.org/tables/gilbert_meta_20/), [`gilbert_meta_37`](https://itemresponsewarehouse.org/tables/gilbert_meta_37/)  \n**From EDUC 252:** problem sets PS5#4, PS7#1; code [`ps5/rctdif.R`](https://github.com/ben-domingue/252/blob/main/ps5/rctdif.R), [`ps7/ilhte.R`](https://github.com/ben-domingue/252/blob/main/ps7/ilhte.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\nwebr::install(\"lme4\", quiet = TRUE)\nsuppressPackageStartupMessages(library(lme4))\n```\n:::\n\n\n\n\n```{ojs}\n//| echo: false\nimport {palette} from \"./widgets/irt.js\"\nimport {itemEffects, expectedCorrect, placeboTrial, spuriousInteraction} from \"./widgets/invariance-experience.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nA fractions program for struggling fifth graders raises its students' test scores by more than a standard deviation. Did it raise every item, or a handful? [Differential item functioning](dif.qmd) ended on a vocabulary trial in which one word, *expedition*, carried over a quarter of the raw effect. This lesson takes that finding further. Experience, whether a program, the loss of a spouse or a second sitting of the same test, can change how a measure works, and a randomized trial is the one setting where we can separate that change from a change in the respondents. We read treatment as a grouping variable, use the pretest as a placebo, fit a model that gives every item its own treatment effect, and ask what the spread of those effects does to the average effect we report.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- say how experience can change a measure (alpha, beta and gamma change; response shift) as well as respondents' standing on it;\n- use randomization to read treatment DIF as caused by the treatment, and a pretest as a placebo check on the whole analysis;\n- write down and fit the item-level heterogeneous treatment effects (IL-HTE) model with `lme4`, and interpret $\\sigma_\\zeta$ and $\\rho$;\n- explain what item-level effects do to the precision and generalizability of an average effect, and how they can produce a treatment-by-pretest interaction that no respondent has;\n- decide, for a given use of the scores, whether the items that move most are a threat or the signal.\n\n## Core ideas\n\n### When experience changes the measure\n\nAfter a spouse dies, older adults in the Health and Retirement Study report more depressive symptoms on an eight-item, yes/no version of the CES-D ([Radloff, 1977](https://doi.org/10.1177/014662167700100306)), and the rise fades within about a year ([Domingue, Duncan, Harrati & Belsky, 2021](https://doi.org/10.1093/geronb/gbaa044)). The items don't share the rise equally: loneliness and sadness carry most of it (the preprint, [Domingue et al., 2019](https://doi.org/10.1101/19009878), Supplemental Figures S7–S8). Is that more depression, or depression measured differently? A widow who now reports feeling lonely may be no more depressed, in the sense the other items capture, than a year earlier; the loneliness item is also answering a question about her circumstances. The IRW has no item-level data from this study, so the result stays a cited figure.\n\nThe possibility has names. [Golembiewski, Billingsley and Yeager (1976)](https://doi.org/10.1177/002188637601200201) distinguished three kinds of change. **Alpha** change is a change in level on an instrument that stays the same; **beta** change, a change in the scale respondents use to answer; **gamma** change, a redefinition of the construct itself ([Livingston et al., 2022](https://doi.org/10.1007/s41542-022-00122-y), give a short account). In health research, [Sprangers and Schwartz (1999)](https://doi.org/10.1016/S0277-9536(99)00045-3) call the last two **response shift**: a change in what a self-evaluation means, from new internal standards, new values or a new conception of the construct. Each is a failure of invariance across occasions. Gamma change is a change in the factor structure; beta change, unequal loadings or intercepts ([Jabrayilov, Emons, de Jong & Sijtsma, 2017](https://doi.org/10.1007/s11136-017-1500-1); [Oort, 2005](https://doi.org/10.1007/s11136-004-0830-y); [Widaman, Ferrer & Conger, 2010](https://doi.org/10.1111/j.1750-8606.2009.00110.x)).\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Fairness in testing](fairness.qmd): impact is a difference in the attribute itself; bias is a difference in scores that comes from something else. Invariance is always relative to the other items: a shift shared by every item looks like impact.\n:::\n\nSwap \"group\" for \"occasion\" and the fairness lesson carries over: a change in level is impact across time, and an item whose meaning shifts is DIF across time. A program, a bereavement and a second sitting are all experiences between two measurements, and each can change the measure along with the person.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Factor analysis II](fa-confirmatory.qmd): longitudinal invariance is the multigroup ladder (configural, metric, scalar) with occasions in place of groups. [Generalizability theory](g-theory.qmd) treats the occasion as a facet, a source of error to average over; here it is a condition that may change what is measured. [Factor analysis I](fa-exploratory.qmd) used BFI-2 data in which students were randomly assigned a response format, the same design with the format as the treatment. And [What does a score mean?](score-meaning.qmd) computed a reliable change index, which assumes the scale measures the same thing at both waves ([Jacobson & Truax, 1991](https://doi.org/10.1037/0022-006x.59.1.12)).\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"After a mindfulness course, participants' scores on a stress scale fall. Nearly all of the fall is on one item, about feeling unable to control what matters in one's life. What is the most careful reading?\",\n  options: [\n    {text: \"Stress fell, or the course changed how participants read that item; the item-level pattern is a reason to check before reporting a general fall in stress\", correct: true, why: \"A change concentrated in one item is what beta or gamma change would produce. It is also what a real but narrow change in stress would produce. The pattern calls for a check, not a verdict.\"},\n    {text: \"Stress fell: the total went down and the scale is reliable\", correct: false, why: \"Reliability at each occasion says nothing about whether the items mean the same thing at both. The item-level pattern is exactly what invariance across occasions asks about.\"},\n    {text: \"The item is biased and should be dropped\", correct: false, why: \"A flag isn't a verdict. A sense of control may be precisely what the course teaches, in which case the item is carrying the effect, not distorting it.\"}\n  ]\n})\n```\n\n### Treatment as the grouping, and the pretest as a placebo\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Differential item functioning](dif.qmd): in a randomized trial, treatment assignment is a grouping too. Among children with the same total, the vocabulary item *expedition* was far easier for treated children, and DIF by treatment is variation in the treatment effect from item to item.\n:::\n\nAfter a bereavement we can't separate change in the person from change in the measure, since who is bereaved isn't random. A randomized trial removes the problem. At the pretest, treated and control respondents come from the same population, so there is no impact and, since the program hasn't happened yet, no reason for any item to work differently. Any treatment DIF found then is a false positive, and the pretest becomes a **placebo test** for the whole analysis, from the handling of waves to the matching score. At the posttest the arms differ only by assignment, so an item that works differently for treated respondents does so *because* of the treatment ([Gilbert, Kim & Miratrix, 2023](https://doi.org/10.3102/10769986231171710); [Ahmed et al., 2025](https://doi.org/10.1080/19345747.2024.2361337)).\n\nWhat the treatment causes is still relative. If the program raised every item by the same amount, the matched comparison would find nothing: that is impact, the average effect. Treatment DIF is each item's departure from the average.\n\n#### Try it: the pretest as a placebo\n\nA simulated trial: respondents in each arm answer the same Rasch items twice. At the pretest nobody has been treated. At the posttest everyone has grown by 0.5 logits, treated respondents by a further 0.5 on average, and each item's effect departs from that average with the spread you set. Each dot is an item's Mantel–Haenszel delta by treatment (positive: easier for treated respondents with the same total), orange when $p < .05$.\n\n```{ojs}\n//| echo: false\nviewof pl_n = Inputs.range([50, 500], {value: 200, step: 50, label: \"Respondents per arm\"})\nviewof pl_items = Inputs.range([10, 60], {value: 30, step: 5, label: \"Items\"})\nviewof pl_sz = Inputs.range([0, 1], {value: 0.5, step: 0.05, label: \"Spread of item effects (logits)\"})\nviewof pl_seed = Inputs.range([1, 20], {value: 1, step: 1, label: \"Sample\"})\n```\n\n```{ojs}\n//| echo: false\npl = placeboTrial({seed: pl_seed, nPer: pl_n, nItems: pl_items, beta1: 0.5, sigmaZeta: pl_sz})\n{\n  const rows = [...pl.pre.map(d => ({...d, wave: \"pretest\"})), ...pl.post.map(d => ({...d, wave: \"posttest\"}))];\n  return Plot.plot({\n    width: 700, height: 260, x: {label: \"Item\", tickFormat: d => d + 1, ticks: []}, y: {label: \"MH delta by treatment\"},\n    fx: {label: null, domain: [\"pretest\", \"posttest\"]},\n    marks: [\n      Plot.ruleY([0], {stroke: palette.rule}),\n      Plot.ruleY([-1, 1], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n      Plot.dot(rows, {x: \"item\", y: \"delta\", fx: \"wave\", r: 4, fill: d => (d.p < 0.05 ? palette.contrast : palette.main)})\n    ]\n  });\n}\n```\n\n```{ojs}\n//| echo: false\nmd`Pretest: **${pl.pre.filter(d => d.p < 0.05).length}** of ${pl_items} items significant at .05 (chance alone would give about ${(0.05 * pl_items).toFixed(1)}). Posttest: **${pl.post.filter(d => d.p < 0.05).length}** of ${pl_items}.`\n```\n\nStep through the samples: the pretest flags hover around what chance allows, while the posttest, with the spread at 0.5, flags about a third of the items. Now set the spread to 0. Every item moves by the same amount and the posttest looks like the pretest again: a treatment that lifts all items equally shows up as impact, not DIF.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A trial's pretest has 40 items. Checked for treatment DIF at $\\\\alpha = .05$, 11 are flagged. What does that suggest?\",\n  options: [\n    {text: \"Something outside the program: about 2 flags are expected, so check randomization, the data (are the waves what you think?) and the matching score\", correct: true, why: \"Before treatment the arms come from the same population and no item can respond to a program that hasn't happened. Eleven flags, against about 2 expected, point to a problem in the design or the analysis.\"},\n    {text: \"The program works on those 11 items\", correct: false, why: \"At the pretest the program hasn't happened yet. Whatever produced the flags, it wasn't the treatment.\"},\n    {text: \"Nothing unusual; with 40 items some DIF is expected\", correct: false, why: \"Some is: about $40 \\\\times .05 = 2$. Eleven is well beyond that, which is what makes the pretest useful as a placebo.\"}\n  ]\n})\n```\n\n### A treatment effect for every item\n\nRather than test items one at a time, we can model the variation. The **IL-HTE model** ([Gilbert, Kim & Miratrix, 2023](https://doi.org/10.3102/10769986231171710); [Gilbert, Himmelsbach, Soland, Joshi & Domingue, 2025](https://doi.org/10.1002/pam.70025)) is the Rasch model with persons and items both random ([De Boeck & Wilson, 2004](https://doi.org/10.1007/978-1-4757-3990-9)) and a random item slope on treatment, $T_j$:\n$$\\begin{aligned}\n\\text{logit}\\Pr(x_{ij} = 1) &= \\theta_j - b_i + \\zeta_i T_j,\\\\\n\\theta_j &= \\beta_0 + \\beta_1 T_j + \\varepsilon_j, \\qquad \\varepsilon_j \\sim N(0, \\sigma_\\theta^2),\\\\\n\\begin{pmatrix} b_i \\\\ \\zeta_i \\end{pmatrix} &\\sim N\\!\\left(\\begin{pmatrix} 0 \\\\ 0 \\end{pmatrix}, \\begin{pmatrix} \\sigma_b^2 & \\rho\\sigma_b\\sigma_\\zeta \\\\ \\rho\\sigma_b\\sigma_\\zeta & \\sigma_\\zeta^2 \\end{pmatrix}\\right).\n\\end{aligned}$$\n$\\beta_1$ is the average effect on $\\theta$; item $i$'s effect is $\\beta_1 + \\zeta_i$. $\\sigma_\\zeta$ is the spread of item effects around the average. At zero every item moves by $\\beta_1$, which is what a Rasch model fitted to both arms assumes: treatment changes $\\theta$ and nothing else. $\\rho$ says whether harder items (positive) or easier items (negative) move more. Dividing $\\beta_1$ and $\\sigma_\\zeta$ by $\\sigma_\\theta$ puts them in standard deviations of ability.\n\nIt is a generalized linear mixed model, so `lme4` fits it ([Bates, Mächler, Bolker & Walker, 2015](https://doi.org/10.18637/jss.v067.i01); [De Boeck et al., 2011](https://doi.org/10.18637/jss.v039.i12)):\n\n```r\nglmer(resp ~ treat + (1 | id) + (treat | item), data, family = binomial)\n```\n\n`lme4`'s item intercept is an easiness, $-b_i$, so the correlation it prints is $-\\rho$. Is $\\sigma_\\zeta$ zero? Compare this model with one that has `(1 | item)` by a likelihood ratio. A variance can't be negative, so the null value sits on the boundary of the parameter space, and halving the $\\chi^2$ $p$-value is the usual correction ([Self & Liang, 1987](https://doi.org/10.1080/01621459.1987.10478472)).\n\n#### Try it: item effects around an average\n\nTwenty items with difficulties spread around the average respondent. Set the average effect $\\beta_1$, the spread $\\sigma_\\zeta$ and the correlation $\\rho$ between difficulty and effect. The five items that respond most are orange.\n\n```{ojs}\n//| echo: false\nviewof ie_b1 = Inputs.range([0, 1], {value: 0.5, step: 0.05, label: \"Average effect β₁ (logits)\"})\nviewof ie_sz = Inputs.range([0, 1], {value: 0.5, step: 0.05, label: \"Spread of item effects (logits)\"})\nviewof ie_rho = Inputs.range([-0.9, 0.9], {value: 0, step: 0.1, label: \"Correlation ρ (difficulty, effect)\"})\n```\n\n```{ojs}\n//| echo: false\nie = {\n  const {b, zeta} = itemEffects({nItems: 20, sigmaZeta: ie_sz, rho: ie_rho});\n  const eff = zeta.map(z => ie_b1 + z);\n  const order = eff.map((e, i) => i).sort((i, j) => eff[j] - eff[i]);\n  const avg = (ix) => ix.reduce((u, i) => u + eff[i], 0) / ix.length;\n  const ec = expectedCorrect(b, zeta, ie_b1);\n  return {items: b.map((bi, i) => ({b: bi, effect: eff[i], top: ie_sz > 0 && order.slice(0, 5).includes(i)})),\n          top: avg(order.slice(0, 5)), bottom: avg(order.slice(-5)),\n          pp: 100 * ec.reduce((u, d) => u + d.treated - d.control, 0) / ec.length};\n}\nPlot.plot({\n  width: 700, height: 270, x: {label: \"Item difficulty b (logits)\", domain: [-2.2, 2.2]},\n  y: {label: \"Item's treatment effect (logits)\", domain: [-2, 3]},\n  marks: [\n    Plot.ruleY([0], {stroke: palette.rule}),\n    Plot.ruleY([ie_b1], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n    Plot.dot(ie.items, {x: \"b\", y: \"effect\", r: 5, fill: d => (d.top ? palette.contrast : palette.main)})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Average item effect over all 20 items: **${ie_b1.toFixed(2)}** logits; over the 5 that respond most, **${ie.top.toFixed(2)}**; over the 5 that respond least, **${ie.bottom.toFixed(2)}**. On the expected proportion correct over all 20 items, the effect is **${ie.pp.toFixed(1)}** percentage points.`\n```\n\nWith $\\sigma_\\zeta$ at 0 every dot sits on the dashed line, and a test built from any five items would show the same effect in logits. At the default, the five most responsive items average more than twice the overall effect and the five least about zero: two short forms of one test, one program, two conclusions. Move $\\rho$ to −0.8 and the orange dots move left, among the easy items.\n\n### What item-level effects do to the estimate\n\nDoes the spread change the average? Not by itself: the sum score, a constant-effect model and the IL-HTE model estimate much the same average, as the fractions trial below shows. It changes three other things.\n\n**Precision.** The items are a sample from those that could have been written, and if they respond unequally, a different sample would give a different average. Treating the items as fixed leaves that variation out, which understates standard errors and inflates false positives ([Gilbert, Kim & Miratrix, 2023](https://doi.org/10.3102/10769986231171710)). Across 15 trials, [Ahmed et al. (2025)](https://doi.org/10.1080/19345747.2024.2361337) found one item driving nearly 40% of an effect, and item-level patterns that could make 31% of the significant effects null once counted as uncertainty.\n\n**Generalizability.** $\\sigma_\\zeta$ says how far the effect on a fresh set of items from the same domain could fall from the one observed. A claim about the construct, rather than about these items, needs it ([Gilbert, Himmelsbach, et al., 2025](https://doi.org/10.1002/pam.70025)).\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Validity as an argument](validity-argument.qmd): an interpretation/use argument has a generalization link, from the observed score to the score over all the tasks it stands for. $\\sigma_\\zeta$ is evidence on that link for an effect rather than a score.\n:::\n\n**Interactions.** Trialists ask who benefits most by interacting treatment with a pretest. Suppose every respondent gains the same amount on $\\theta$, but easier items respond more. In the treated arm the items' effective difficulties, $b_i - \\zeta_i$, are more spread out than in the control arm, the sum score rises less steeply with $\\theta$, and a sum-score regression finds a negative treatment-by-pretest interaction that no respondent has. From sum scores alone the two stories can't be told apart; item-level data can tell them apart ([Gilbert, Miratrix, Joshi & Domingue, 2025](https://doi.org/10.3102/10769986241240085)).\n\n#### Try it: an interaction nobody has\n\nTreatment adds 0.5 logits to every respondent's $\\theta$, whatever their pretest; the 20 items' effects have the spread and correlation you set. The curves are the expected sum score at each pretest level in each arm, computed from the model, so there is no sampling noise.\n\n```{ojs}\n//| echo: false\nviewof si_sz = Inputs.range([0, 1], {value: 0.8, step: 0.05, label: \"Spread of item effects (logits)\"})\nviewof si_rho = Inputs.range([-0.9, 0.9], {value: -0.8, step: 0.1, label: \"Correlation ρ (difficulty, effect)\"})\n```\n\n```{ojs}\n//| echo: false\nsi = spuriousInteraction({...itemEffects({nItems: 20, sigmaZeta: si_sz, rho: si_rho}), beta1: 0.5})\nsi0 = spuriousInteraction({...itemEffects({nItems: 20, sigmaZeta: 0, rho: 0}), beta1: 0.5})\nPlot.plot({\n  width: 700, height: 270, x: {label: \"Pretest (SDs)\"}, y: {label: \"Expected sum score (of 20)\", domain: [0, 20]},\n  color: {legend: true, domain: [\"control\", \"treated\"], range: [palette.main, palette.contrast]},\n  marks: [Plot.line(si.rows.map(d => ({...d, arm: d.T ? \"treated\" : \"control\"})), {x: \"pre\", y: \"s\", stroke: \"arm\", strokeWidth: 2.5})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Slope on the pretest: control **${si.control.slope.toFixed(2)}**, treated **${si.treated.slope.toFixed(2)}** points per SD. Treatment-by-pretest interaction: **${si.interaction.toFixed(2)}**; with every item moving equally it would be ${si0.interaction.toFixed(2)}.`\n```\n\nWith every item moving equally the interaction is already slightly negative, from the sum score's bounded range. At the default, where easier items move more, it is five times that, with no heterogeneity among respondents at all. Set $\\rho$ to +0.8 and it changes sign.\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: why the interaction appears\n\n**Assumptions:** the IL-HTE model above; no person-level heterogeneity (every respondent's $\\theta$ rises by $\\beta_1$); the outcome analysed is the sum score $S = \\sum_i x_i$.\n\n**Two tests in one.** In the control arm item $i$ has difficulty $b_i$. In the treated arm it behaves as if its difficulty were $b_i - \\zeta_i$, on top of the shift of $\\beta_1$ in $\\theta$. The spread of effective difficulties in the treated arm is\n$$\\text{Var}(b_i - \\zeta_i) = \\sigma_b^2 + \\sigma_\\zeta^2 - 2\\rho\\sigma_b\\sigma_\\zeta,$$\nwhich exceeds $\\sigma_b^2$ whenever $\\rho \\le 0$, and can fall below it when $\\rho$ is positive and large enough.\n\n**What spread does to the sum score.** The expected sum score is the test characteristic curve, $E(S \\mid \\theta) = \\sum_i P_i(\\theta)$ with $P_i(\\theta) = \\text{logit}^{-1}(\\theta - b_i)$. Its slope at $\\theta$ is $\\sum_i P_i(1 - P_i)$, the test information under the Rasch model. An item near $\\theta$ contributes close to the maximum of 1/4; spreading the items out moves some of them where they contribute little. So in the middle of the ability range the treated arm's curve is flatter when $\\rho < 0$.\n\n**The interaction.** A regression of $S$ on treatment, pretest and their product estimates the slope of $S$ on the pretest in each arm. The pretest predicts $\\theta$ equally well in both arms, but the treated arm's flatter curve turns a unit of $\\theta$ into fewer points, so its slope is smaller and the interaction is negative, although every respondent gained the same. [Gilbert, Miratrix, Joshi and Domingue (2025)](https://doi.org/10.3102/10769986241240085) show analytically and by simulation that a sum score cannot distinguish this from a true interaction, and that a model with item-specific effects can. The bounded range of $S$ adds a smaller effect of its own, which is why the widget's interaction is not quite zero when $\\sigma_\\zeta = 0$.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"An IL-HTE model gives an average effect of 0.40 SD and $\\\\sigma_\\\\zeta$ = 0.50 SD on a 10-item outcome. A colleague plans to replicate with 10 different items written to the same blueprint. What should she expect?\",\n  options: [\n    {text: \"An average effect that could differ noticeably from 0.40, since items respond unequally and hers are a new sample\", correct: true, why: \"The mean of 10 new item effects varies around the true average with an SD of roughly $0.50/\\\\sqrt{10} \\\\approx 0.16$ SD, before any sampling of respondents. That is the generalizability question $\\\\sigma_\\\\zeta$ answers.\"},\n    {text: \"0.40 again, up to sampling error in respondents\", correct: false, why: \"That holds only if every item responds alike ($\\\\sigma_\\\\zeta = 0$). With a spread of 0.50 SD, which items she writes matters too.\"},\n    {text: \"An effect about 0.50 SD larger\", correct: false, why: \"$\\\\sigma_\\\\zeta$ is a spread around the average, not a shift. Her items' average effect is as likely to fall below 0.40 as above it.\"}\n  ]\n})\n```\n\n### Bias, or what the program taught?\n\nIs an item that moves most a biased item? It may be the item closest to what an intervention taught. For evaluating the intervention, that can be the signal: the program changed what it set out to change, and the near items show it. For a claim of general gain, it is a threat: a test made mostly of near items overstates transfer, in the sense of [Barnett and Ceci's (2002)](https://doi.org/10.1037/0033-2909.128.4.612) taxonomy of near and far transfer. Whether item-level heterogeneity is bias depends on the interpretation and the use, as [Validity as an argument](validity-argument.qmd) would lead you to expect. Group-specific item parameters can also be judged by prediction: do they predict new responses better than shared ones? The InterModel Vigorish measures that ([Domingue et al., 2024](https://doi.org/10.1007/s11336-024-09977-2)). Explaining *which* items move, with features such as alignment to the curriculum, is a job for [What is an item?](explanatory-irt.qmd).\n\n## Simulate\n\nThe code simulates a trial with 800 respondents and 20 items. Treatment raises every respondent's $\\theta$ by 0.5, whatever their pretest; the items' departures have $\\sigma_\\zeta = 0.8$ and $\\rho = -0.8$ (easier items move more). It fits a sum-score regression, a constant-effect model and the IL-HTE model, each with treatment, pretest and their product. Loading `lme4` takes 10 to 20 seconds the first time the page runs code; the fits take a few seconds more.\n\nWith the seed as written, the IL-HTE model recovers $\\sigma_\\zeta$ = 0.78 and $\\rho$ = −0.78, and its item effects correlate 0.99 with the true ones. The interaction, 0 in truth, is −0.08 SD in the sum-score regression and −0.10 logits in the constant-effect model; the IL-HTE model puts it at 0.04. Its standard error is about 0.06 in both models, so a single run is noisy: try other seeds. Set `rho <- 0.8` and the constant-effect interaction turns positive (0.03); set `sigma_zeta <- 0` and the three models agree.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-17\n# Simulate a randomized trial whose outcome items respond unequally to treatment\n# (item-level heterogeneous treatment effects, IL-HTE), then fit a sum-score model,\n# a constant-effect item response model and the IL-HTE model with lme4, and compare\n# each with the truth. There is no person-level heterogeneity: the treatment raises\n# every respondent's theta by the same amount. Runs in the browser in well under a minute.\nlibrary(lme4)\nset.seed(3)\n\nn <- 800            # respondents, half treated\nI <- 20             # items\nbeta1 <- 0.5        # average treatment effect on theta (theta has SD 1 within arm)\nsigma_zeta <- 0.8   # SD of the item-specific departures zeta_i from beta1\nrho <- -0.8         # correlation of item difficulty b_i with zeta_i (negative: easier items move more)\n\n# Respondents: a standardized pretest, and theta built from it plus noise. The\n# treatment adds beta1 to everyone, whatever their pretest.\ntreat <- rep(0:1, each = n / 2)\npre <- rnorm(n)\ntheta <- 0.7 * pre + sqrt(1 - 0.7^2) * rnorm(n) + beta1 * treat\n\n# Items: difficulties b_i spread evenly (normal quantiles, SD about 1) and departures\n# zeta_i with SD sigma_zeta and correlation rho with b_i. Building them exactly (rather\n# than drawing them) keeps the item sample from adding its own noise: the zeta_i\n# average exactly 0, so beta1 is the effect on these items too.\nb <- qnorm((1:I - 0.5) / I)\nz1 <- (b - mean(b)) / sd(b)\nw <- resid(lm(rnorm(I) ~ z1)); w <- w / sd(w)\nzeta <- sigma_zeta * (rho * z1 + sqrt(1 - rho^2) * w)\n\n# Responses: logit P(x_ij = 1) = theta_j - b_i + zeta_i T_j.\nd <- expand.grid(id = 1:n, item = 1:I)\nd$treat <- treat[d$id]\nd$pre <- pre[d$id]\nd$resp <- rbinom(nrow(d), 1, plogis(theta[d$id] - b[d$item] + zeta[d$item] * d$treat))\n\n# 1. The sum score, standardized, regressed on treatment, pretest and their product.\ns <- tapply(d$resp, d$id, sum)\nm_sum <- lm(scale(s) ~ treat * pre)\n\n# 2. A constant effect for every item (the Rasch model as a mixed model).\n# nAGQ = 0 uses a faster, slightly rougher approximation to the likelihood, which\n# keeps the browser run to seconds; drop it locally for the default Laplace fit.\nm_const <- glmer(resp ~ treat * pre + (1 | id) + (1 | item), d, family = binomial, nAGQ = 0)\n\n# 3. The IL-HTE model: each item gets its own treatment effect. lme4's item intercept\n#    is an easiness (-b_i), so the correlation it reports is -rho.\nm_ilhte <- glmer(resp ~ treat * pre + (1 | id) + (treat | item), d, family = binomial, nAGQ = 0)\nvc <- VarCorr(m_ilhte)$item\n\nround(rbind(\n  truth           = c(effect = beta1, sigma_zeta = sigma_zeta, rho = rho, interaction = 0),\n  sum_score       = c(coef(m_sum)[\"treat\"], NA, NA, coef(m_sum)[\"treat:pre\"]),\n  constant_effect = c(fixef(m_const)[\"treat\"], NA, NA, fixef(m_const)[\"treat:pre\"]),\n  ilhte           = c(fixef(m_ilhte)[\"treat\"], sqrt(vc[2, 2]), -attr(vc, \"correlation\")[1, 2],\n                      fixef(m_ilhte)[\"treat:pre\"])), 2)\n# (The sum-score row is in SDs of the sum score, the others in logits.)\n\n# Standard errors of the interaction: the constant-effect model against IL-HTE.\nround(c(constant_effect = summary(m_const)$coef[\"treat:pre\", 2],\n        ilhte = summary(m_ilhte)$coef[\"treat:pre\", 2]), 3)\n\n# How well does the IL-HTE model recover each item's effect?\nest <- fixef(m_ilhte)[\"treat\"] + ranef(m_ilhte)$item[, \"treat\"]\nround(c(correlation_with_truth = cor(est, beta1 + zeta)), 2)\n\n```\n:::\n\n\n[Download this code](code/invariance-experience-sim.R) to run it with more respondents, or many replications, in your own R session.\n\n## With real data\n\n[Download the code](code/invariance-experience-irw.R); it needs `lme4`, and the model fits take about a minute.\n\n### A fractions trial, before and after\n\nOur main table is [gilbert_meta_20](https://itemresponsewarehouse.org/tables/gilbert_meta_20/), from a randomized trial of a small-group fractions intervention for fifth graders performing well below grade level ([Jayanthi et al., 2021](https://doi.org/10.1177/00144029211008851); data at [doi:10.7910/DVN/Z4WMFE](https://doi.org/10.7910/DVN/Z4WMFE)), part of the trial collection of [Gilbert, Himmelsbach, et al. (2025)](https://doi.org/10.1002/pam.70025). Its job is to be a trial with a pretest, so the placebo check is real. Students who scored between the 15th and 37th percentiles on a fractions screener were randomized within teacher, and the table holds the final analytic sample of 186 ([data description](https://doi.org/10.7910/DVN/Z4WMFE)). Items are scored 1 for correct.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The IRW table, from the CSV link on its landing page (pinned to one version).\nurl20 <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.gilbert_meta_20/rows?format=csv\"\nf20 <- read.csv(url20)\nf20 <- f20[!is.na(f20$resp), ]\n# Waves: 0 = pretest, 1 = posttest. How many items and students in each?\nt(sapply(split(f20, f20$wave), function(x) c(items = length(unique(x$item)),\n                                            students = length(unique(x$id)))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  items students\n0    37      186\n1    93      186\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npre_items <- unique(f20$item[f20$wave == 0])\npost_items <- unique(f20$item[f20$wave == 1])\nc(pretest_items_also_at_posttest = sum(pre_items %in% post_items))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npretest_items_also_at_posttest \n                            37 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Items come in four blocks (by the prefix of their names):\ntable(wave = f20$wave[!duplicated(f20[, c(\"wave\", \"item\")])],\n      block = sub(\"_+q.*$\", \"\", f20$item[!duplicated(f20[, c(\"wave\", \"item\")])]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    block\nwave procedures trans_math tuf4 tuf5\n   0         11          0   26    0\n   1         24         25   26   18\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nkids20 <- f20[!duplicated(f20$id), c(\"id\", \"treat\")]\ntable(treat = kids20$treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntreat\n 0  1 \n99 87 \n```\n\n\n:::\n:::\n\n\nOn waves: wave 0 is the pretest and wave 1 the posttest. The posttest repeats all 37 pretest items (26 from the fourth-grade Test for Understanding of Fractions, `tuf4`, and 11 fractions procedures) and adds 56: the fifth-grade form (`tuf5`), more procedures, and a block the dataset labels TransMath (`trans_math`). Eighteen posttest responses are missing, all from one student, who drops out of the complete-case analyses.\n\nWe match on the total score and test uniform DIF, the kind a shift in one item's treatment effect produces, with the logistic regression of the DIF lesson ([Swaminathan & Rogers, 1990](https://doi.org/10.1111/j.1745-3984.1990.tb00754.x)). With 37 or 93 tests, we also control the false discovery rate ([Benjamini & Hochberg, 1995](https://doi.org/10.1111/j.2517-6161.1995.tb02031.x)), and give the $\\Delta R^2$ categories of [Jodoin and Gierl (2001)](https://doi.org/10.1207/S15324818AME1404_2).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# One wide matrix per wave: a row per student, a column per item (1 = correct).\nwide <- function(long, items) {\n  x <- long[long$item %in% items, ]\n  A <- tapply(x$resp, list(x$id, x$item), function(v) v[1])\n  A <- A[complete.cases(A), items]\n  list(X = A, treat = kids20$treat[match(rownames(A), kids20$id)])\n}\n# Logistic-regression DIF for one item, matching on the total score, as in the DIF\n# lesson but for uniform DIF only, the kind a shift in one item's treatment effect\n# produces: the 1-df likelihood-ratio test of M0 (total) against M1 (total and\n# treatment), and the change in Nagelkerke's R^2 between them.\nnagelkerke <- function(m, ll0, n) {\n  cs <- 1 - exp(2 * (ll0 - as.numeric(logLik(m))) / n)\n  cs / (1 - exp(2 * ll0 / n))\n}\nlr_item <- function(y, g, total) {\n  d <- data.frame(y = y, g = g, total = total)\n  ll0 <- as.numeric(logLik(glm(y ~ 1, binomial, d)))\n  m0 <- glm(y ~ total, binomial, d)\n  m1 <- glm(y ~ total + g, binomial, d)\n  c(beta_treat = unname(coef(m1)[\"g\"]),\n    p = anova(m0, m1, test = \"LRT\")[2, \"Pr(>Chi)\"],\n    dR2 = nagelkerke(m1, ll0, nrow(d)) - nagelkerke(m0, ll0, nrow(d)))\n}\n# Every item; p-values also after the Benjamini-Hochberg false-discovery-rate\n# correction; Jodoin-Gierl categories (A below .035, B to .07, C above, and A\n# whenever the test is not significant).\ntreatment_dif <- function(W) {\n  tot <- rowSums(W$X)\n  out <- as.data.frame(t(sapply(colnames(W$X), function(i) lr_item(W$X[, i], W$treat, tot))))\n  out$p_BH <- p.adjust(out$p, \"BH\")\n  out$jg <- ifelse(out$p >= 0.05 | out$dR2 < 0.035, \"A\", ifelse(out$dR2 < 0.07, \"B\", \"C\"))\n  out\n}\ncount_flags <- function(r) c(items = nrow(r), p_below_05 = sum(r$p < 0.05),\n                             expected_by_chance = round(0.05 * nrow(r), 1),\n                             after_BH = sum(r$p_BH < 0.05), B = sum(r$jg == \"B\"), C = sum(r$jg == \"C\"))\n```\n:::\n\n\nThe pretest is also our sanity table: before treatment, its flags estimate the false-positive rate. It has 3 flags at .05 among 37 items, about what chance allows, and none survives the correction (the table below).\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"On the same 37 items at the posttest, how many will show treatment DIF after the false-discovery correction?\",\n  choices: [\"None, as at the pretest\", \"One or two\", \"Five or more\"],\n  answer: \"Five or more\",\n  reveal: \"Five of the 37 survive the correction at the posttest (9 are significant before it), against none at the pretest. Across all 93 posttest items, 12 are significant and 5 survive. Check the table below.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nW0 <- wide(f20[f20$wave == 0, ], pre_items)    # pretest: before any instruction\nW1 <- wide(f20[f20$wave == 1, ], post_items)   # posttest: all 93 items\nW1s <- wide(f20[f20$wave == 1, ], pre_items)   # posttest, the pretest's 37 items only\ndif0 <- treatment_dif(W0); dif1 <- treatment_dif(W1); dif1s <- treatment_dif(W1s)\nrbind(pretest = count_flags(dif0), posttest = count_flags(dif1),\n      \"posttest, same 37 items\" = count_flags(dif1s))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        items p_below_05 expected_by_chance after_BH B C\npretest                    37          3                1.9        0 3 0\nposttest                   93         12                4.7        5 8 2\nposttest, same 37 items    37          9                1.9        5 3 1\n```\n\n\n:::\n:::\n\n\nWith 186 students the $\\Delta R^2$ categories are generous: all three pretest flags reach B, so here the correction is the better guide. After the program the same 37 items give 9 flags, 5 of which survive; across all 93, 12 and 5, with 8 items in B and 2 in C.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The posttest items in B or C, largest first. beta_treat > 0: easier for treated\n# students with the same total.\nd1 <- dif1[dif1$jg != \"A\", ]\nd1$p_control <- colMeans(W1$X[W1$treat == 0, rownames(d1)])\nd1$p_treated <- colMeans(W1$X[W1$treat == 1, rownames(d1)])\nround(d1[order(-d1$dR2), c(\"beta_treat\", \"p\", \"dR2\", \"p_control\", \"p_treated\")], 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                | beta_treat|     p|   dR2| p_control| p_treated|\n|:---------------|----------:|-----:|-----:|---------:|---------:|\n|trans_math__q10 |      1.287| 0.000| 0.083|     0.384|     0.767|\n|tuf4_q21        |     -1.466| 0.001| 0.072|     0.333|     0.337|\n|procedures__q1h |     -1.803| 0.004| 0.066|     0.111|     0.151|\n|tuf4_q04        |      1.133| 0.005| 0.052|     0.556|     0.872|\n|trans_math__q2  |      0.996| 0.006| 0.050|     0.515|     0.802|\n|procedures__q1b |      1.266| 0.002| 0.042|     0.172|     0.628|\n|procedures__q2d |      1.617| 0.001| 0.039|     0.172|     0.674|\n|procedures__q2b |      1.546| 0.001| 0.038|     0.212|     0.721|\n|tuf4_q07        |     -0.860| 0.020| 0.038|     0.374|     0.326|\n|tuf5_q02        |     -0.937| 0.014| 0.036|     0.515|     0.570|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(block = sub(\"_+q.*$\", \"\", rownames(d1)), sign = ifelse(d1$beta_treat > 0, \"favours treated\", \"favours control\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            sign\nblock        favours control favours treated\n  procedures               1               3\n  trans_math               0               2\n  tuf4                     2               1\n  tuf5                     1               0\n```\n\n\n:::\n:::\n\n\nMost items that favour treated students come from the procedures and TransMath blocks; several from the understanding tests (`tuf4`, `tuf5`) go the other way, moved less than the rest of the test.\n\nThe IL-HTE model summarizes all of this in a few numbers:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsuppressPackageStartupMessages(library(lme4))\n# The IL-HTE model (Gilbert, Kim & Miratrix, 2023), in lme4's parameterization:\n#   logit P(x_ij = 1) = beta0 + beta1 T_j + theta_j + e_i + zeta_i T_j,\n# with theta_j ~ N(0, s_theta^2) and (e_i, zeta_i) bivariate normal. lme4's item\n# intercept e_i is an easiness, the negative of the lesson's difficulty b_i, so the\n# correlation it reports has the opposite sign to rho in the lesson; we flip it.\n# Following the IRW vignette, effects are standardized by s_theta from the model with\n# a constant effect, and sigma_zeta is tested by a likelihood-ratio test against\n# that model, halving the p-value because a variance of zero sits on the boundary\n# (Self & Liang, 1987).\nilhte <- function(long) {\n  m0 <- glmer(resp ~ treat + (1 | id) + (1 | item), long, family = binomial)\n  m1 <- glmer(resp ~ treat + (1 | id) + (treat | item), long, family = binomial)\n  s_theta <- sqrt(VarCorr(m0)$id[1])\n  vc <- VarCorr(m1)$item\n  lr <- as.numeric(2 * (logLik(m1) - logLik(m0)))\n  list(m0 = m0, m1 = m1, s_theta = s_theta,\n       summary = c(students = length(unique(long$id)), items = length(unique(long$item)),\n                   effect_constant_SD = unname(fixef(m0)[\"treat\"]) / s_theta,\n                   effect_average_SD = unname(fixef(m1)[\"treat\"]) / s_theta,\n                   sigma_zeta_SD = sqrt(vc[2, 2]) / s_theta,\n                   rho_difficulty = -attr(vc, \"correlation\")[1, 2],\n                   LR = lr, p = 0.5 * pchisq(lr, 2, lower.tail = FALSE)))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nfit0 <- ilhte(f20[f20$wave == 0, ])\nfit1 <- ilhte(f20[f20$wave == 1, ])\nfit1s <- ilhte(f20[f20$wave == 1 & f20$item %in% pre_items, ])\ntab <- rbind(pretest = fit0$summary, posttest = fit1$summary,\n             \"posttest, same 37 items\" = fit1s$summary)\ndata.frame(round(tab[, 1:7], 2), p = sprintf(\"%.2g\", tab[, \"p\"]))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                        | students| items| effect_constant_SD| effect_average_SD| sigma_zeta_SD| rho_difficulty|     LR|p       |\n|:-----------------------|--------:|-----:|------------------:|-----------------:|-------------:|--------------:|------:|:-------|\n|pretest                 |      186|    37|               0.18|              0.24|          0.59|           0.43|   1.65|0.22    |\n|posttest                |      186|    93|               1.11|              1.13|          0.70|           0.05| 140.41|1.6e-31 |\n|posttest, same 37 items |      186|    37|               1.19|              1.23|          0.83|           0.21|  97.58|3.2e-22 |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# sigma_zeta in logits, and the SD of theta it is divided by:\nround(sapply(list(pretest = fit0, posttest = fit1), function(f)\n  c(sigma_zeta_logits = sqrt(VarCorr(f$m1)$item[2, 2]), s_theta = f$s_theta)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  pretest posttest\nsigma_zeta_logits    0.18     0.59\ns_theta              0.31     0.84\n```\n\n\n:::\n:::\n\n\nAt the pretest $\\sigma_\\zeta$ is not distinguishable from zero ($p$ = 0.22). Its 0.59 SD looks large only because $\\sigma_\\theta$ is small there: the screener selected students from a narrow band, so a logit is a large share of an SD (in logits, $\\sigma_\\zeta$ is 0.18 at the pretest and 0.59 at the posttest). At the posttest the average effect is 1.13 SD, $\\sigma_\\zeta$ is 0.70 SD and the likelihood ratio is 140. On the 37 repeated items alone, $\\sigma_\\zeta$ is 0.83 SD.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same posttest effect three ways, each in within-arm SDs: the sum score, and\n# theta from the constant-effect and IL-HTE models.\ntot1 <- rowSums(W1$X)\ngap <- mean(tot1[W1$treat == 1]) - mean(tot1[W1$treat == 0])\nsd_within <- sqrt(mean(tapply(tot1, W1$treat, var)))   # pooled within-arm SD, like s_theta\nsum_effect <- gap / sd_within\nround(c(sum_score = sum_effect, theta_constant = unname(fit1$summary[\"effect_constant_SD\"]),\n        theta_ilhte = unname(fit1$summary[\"effect_average_SD\"])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sum_score theta_constant    theta_ilhte \n          1.08           1.11           1.13 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Item-specific effects (beta1 + zeta_i, in SDs of theta), by block.\neff1 <- (fixef(fit1$m1)[\"treat\"] + ranef(fit1$m1)$item[, \"treat\"]) / fit1$s_theta\nnames(eff1) <- rownames(ranef(fit1$m1)$item)\nround(t(sapply(split(eff1, sub(\"_+q.*$\", \"\", names(eff1))), function(e)\n  c(items = length(e), mean = mean(e), min = min(e), max = max(e)))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           items mean   min  max\nprocedures    24 1.43  0.39 2.49\ntrans_math    25 1.14  0.24 2.14\ntuf4          26 1.01 -0.64 2.19\ntuf5          18 0.85  0.01 1.91\n```\n\n\n:::\n:::\n\n\nThe sum score, $\\theta$ with a constant effect and $\\beta_1$ from the IL-HTE model agree on the average: 1.08, 1.11 and 1.13 SD. The spread sits underneath. Procedures items moved most, 1.43 SD on average against 0.85 for the fifth-grade understanding form, as the paper's own effects by measure would suggest: largest for fractions procedures ($g$ = 1.07), 0.66 to 0.78 for proficiency and understanding ([Jayanthi et al., 2021](https://doi.org/10.1177/00144029211008851), abstract). Within every block, item effects span more than a standard deviation.\n\n### Health knowledge in India\n\nFor contrast, [gilbert_meta_37](https://itemresponsewarehouse.org/tables/gilbert_meta_37/): health knowledge ten months after an entertainment-education programme in India. Respondents in the programme watched short films on hygiene, midwives and child health, condoms and AIDS, and night blindness; the control arm watched films on financial planning ([Carpena, 2024](https://doi.org/10.1080/00220388.2024.2312832), Supplementary Material A; data at [doi:10.7910/DVN/EJ03JR](https://doi.org/10.7910/DVN/EJ03JR)). Its job: item-level effects whose content we can read. Items are knowledge questions scored 1 for a correct answer, and several are options of one select-all-that-apply question (ways to contract AIDS, times to wash hands). The table's `treat` pools the paper's two film arms, with and without cash incentives for the test, against the control arm. There is one wave, and nothing is missing.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl37 <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.gilbert_meta_37/rows?format=csv\"\nf37 <- read.csv(url37)\np37 <- f37[!duplicated(f37$id), ]\nc(respondents = nrow(p37), items = length(unique(f37$item)), missing = sum(is.na(f37$resp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents       items     missing \n        839          21           0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(treat = p37$treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntreat\n  0   1 \n414 425 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nfit37 <- ilhte(f37)\ndata.frame(t(round(fit37$summary[1:7], 2)), p = sprintf(\"%.2g\", fit37$summary[[\"p\"]]))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| students| items| effect_constant_SD| effect_average_SD| sigma_zeta_SD| rho_difficulty|   LR|p       |\n|--------:|-----:|------------------:|-----------------:|-------------:|--------------:|----:|:-------|\n|      839|    21|               0.49|              0.48|          0.28|           0.33| 15.7|0.00019 |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Item-specific effects in logits (beta1 + zeta_i), with the proportion correct in\n# each arm, largest effect first.\nre <- ranef(fit37$m1)$item\nitems37 <- data.frame(effect_logits = fixef(fit37$m1)[\"treat\"] + re[, \"treat\"],\n                      p_control = tapply(f37$resp[f37$treat == 0], f37$item[f37$treat == 0], mean)[rownames(re)],\n                      p_treated = tapply(f37$resp[f37$treat == 1], f37$item[f37$treat == 1], mean)[rownames(re)],\n                      row.names = rownames(re))\nround(items37[order(-items37$effect_logits), ], 2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                          | effect_logits| p_control| p_treated|\n|:-------------------------|-------------:|---------:|---------:|\n|nightblindness_nutrition  |          0.81|      0.12|      0.27|\n|nightblindness_heard      |          0.75|      0.61|      0.78|\n|nightblindness_curable    |          0.68|      0.46|      0.63|\n|aids_pregnant             |          0.61|      0.02|      0.04|\n|pregnancy_breastmilk      |          0.53|      0.62|      0.73|\n|aids_needle               |          0.50|      0.23|      0.33|\n|aids_pregnant_baby        |          0.45|      0.25|      0.34|\n|condom_hiv                |          0.43|      0.83|      0.89|\n|pregnancy_dai_certificate |          0.41|      0.69|      0.77|\n|aids_sex                  |          0.39|      0.71|      0.77|\n|diar_know                 |          0.34|      0.31|      0.38|\n|aids_heard                |          0.31|      0.86|      0.88|\n|wash_defecation           |          0.31|      0.91|      0.93|\n|aids_touch                |          0.30|      0.84|      0.87|\n|condom_std                |          0.29|      0.85|      0.87|\n|aids_blood                |          0.29|      0.21|      0.25|\n|wash_eating               |          0.29|      0.86|      0.88|\n|aids_curable              |          0.24|      0.46|      0.49|\n|condom_disease            |          0.19|      0.20|      0.20|\n|wash_cooking              |          0.17|      0.36|      0.37|\n|condom_pregnancy          |          0.12|      0.93|      0.91|\n\n</div>\n:::\n:::\n\n\nThe average effect is 0.48 SD and $\\sigma_\\zeta$ is 0.28 SD ($p$ = 0.00019), a much smaller spread than in the fractions trial. The three items that moved most are the three about night blindness (0.68 to 0.81 logits), the subject of one of the programme's five modules: a single film about a boy who can't see at dusk (Supplementary Material A). The paper's own results by topic agree: night blindness had the largest effect of the four topics, and the lowest knowledge in the control arm ([Carpena, 2024](https://doi.org/10.1080/00220388.2024.2312832), longer-term knowledge by topic). Knowing to wash hands before cooking and knowing that condoms prevent pregnancy moved least (0.17 and 0.12 logits). $\\rho$ = 0.33: harder items moved somewhat more.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Who gains most? The treatment-by-baseline interaction, with a constant effect for\n# every item and with IL-HTE (std_baseline: the IRW's standardized baseline score).\nmB <- glmer(resp ~ treat * std_baseline + (1 | item) + (1 | id), f37, family = binomial)\nmC <- glmer(resp ~ treat * std_baseline + (treat | item) + (1 | id), f37, family = binomial)\nround(rbind(constant_items = summary(mB)$coef[\"treat:std_baseline\", 1:2],\n            ilhte = summary(mC)$coef[\"treat:std_baseline\", 1:2]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error\nconstant_items    0.024      0.065\nilhte             0.020      0.066\n```\n\n\n:::\n:::\n\n\nDoes IL-HTE change the answer to \"who gained most?\" here? Barely: the treatment-by-baseline interaction is 0.024 logits with a constant effect for every item and 0.020 with IL-HTE, both well inside their standard errors. With a spread of 0.28 SD, against 0.70 in the fractions trial, and a moderate $\\rho$, there is little for the constant-effect model to misread.\n\nWhat should a trialist take from this? Two positions rest on different assumptions. If the outcome's items *are* the target (the state test a program will be judged on), the average over these items is the estimand, and the sum score answers it. If the items stand for a domain (fractions, health knowledge), the effect on the domain is the estimand, and the spread of item effects is part of its uncertainty. My practice, when a trial's outcome comes with item-level data, is to fit the IL-HTE model beside the sum-score analysis, report $\\sigma_\\zeta$ next to the average effect, and use the pretest as a placebo when there is one. In the fractions trial that means reporting an effect of about 1.1 SD together with the fact that items on the same test moved by amounts more than a standard deviation apart. An average effect is a claim about items as well as people.\n\n## Problems\n\n1. **Raw effects and difficulty.** Under the IL-HTE model with every $\\zeta_i = 0$, and $\\theta \\sim N(0, 1)$ in control and $N(\\beta_1, 1)$ in the treated arm, write the effect on item $i$'s expected proportion correct as a function of $b_i$. Show that it is largest for items near the average ability and small for very easy or very hard items. Why, then, can raw differences in proportion correct and item effects on the logit scale rank the items differently, and which would you use to say which items a program moved?\n2. **How much do the flagged items carry? (PS5#4).** In `gilbert_meta_20` at the posttest, drop the 10 items in B or C and re-estimate the effect on the sum score and on $\\theta$. How much of the effect did they carry? Now drop instead the 10 items with the smallest estimated IL-HTE effects. Which short form would a program developer prefer, and which would you report?\n3. **The interaction, with and without item slopes (PS7#1).** In `gilbert_meta_37`, estimate the treatment-by-baseline interaction on the sum score, with a constant-effect model and with IL-HTE. From the IL-HTE fit, compute the SD of the items' effective difficulties in each arm. Using the Go deeper, explain why the three estimates are so close here.\n4. **Bereavement.** After spousal loss, the CES-D items on loneliness and sadness carry most of the rise in symptoms ([Domingue et al., 2019](https://doi.org/10.1101/19009878)). Set out what you would have to assume to report \"depression rose\", and what you would have to assume to report \"the CES-D measured something different\". Given item-level data from waves before and after the loss, which model would you fit, and what result would lead you to each report?\n5. **Near and far.** You are designing the outcome measure for a vocabulary intervention that teaches 40 words. Design a test that can separate near transfer (taught words) from far transfer (untaught words of similar frequency), and say how you would model item-level effects so that the two can be compared. What would you report if the near items moved and the far items didn't?\n6. **Challenge: evidence for or against?** Suppose the items that move most in a trial are exactly those most aligned with the intervention's content. Is item-level heterogeneity then evidence against the measure's validity for evaluating the intervention, evidence for it, or neither? Does your answer change if the same test is also used to report students' general proficiency? This one is open.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Measurement%20invariance%20under%20treatment%20and%20life%20events%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20measurement%20invariance%20under%20experience%3A%20alpha%2C%20beta%20and%20gamma%20change%20and%20response%20shift%2C%20the%20spousal-loss%20finding%20on%20the%20CES-D%2C%20treatment%20as%20a%20DIF%20grouping%20in%20a%20randomized%20trial%20with%20the%20pretest%20as%20a%20placebo%2C%20the%20item-level%20heterogeneous%20treatment%20effects%20%28IL-HTE%29%20model%20fitted%20with%20lme4%20%28sigma_zeta%2C%20rho%2C%20the%20boundary%20likelihood-ratio%20test%29%2C%20what%20item-level%20effects%20do%20to%20precision%2C%20generalizability%20and%20treatment-by-pretest%20interactions%2C%20and%20whether%20the%20items%20that%20move%20most%20are%20bias%20or%20signal%2C%20with%20a%20fractions%20trial%20%28gilbert_meta_20%29%20and%20a%20health-knowledge%20trial%20in%20India%20%28gilbert_meta_37%29.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Across the IRW\n\nHow common are item-level treatment effects across the trials in the warehouse? Following the IRW's [IL-HTE vignette](https://itemresponsewarehouse.org/vignettes/il_hte.html), [`compute.R`](https://github.com/ben-domingue/irw-course/blob/main/deepdives/invariance-experience/compute.R) takes every table with a treatment indicator and at least 100 respondents, keeps the dichotomous items (at least 3), samples at most 5,000 respondents, and fits this lesson's two models. It departs from the vignette on waves: the outcome is the first wave after randomization, read from the processing notes where they have been checked and otherwise by a stated rule, and any pretest wave is fitted too, as a placebo.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndd_path <- file.path(\"..\", \"deepdives\", \"invariance-experience\", \"results.rds\")\ndd <- if (file.exists(dd_path)) readRDS(dd_path) else NULL\nif (!is.null(dd)) {\n  s <- dd$summary[order(-dd$summary$sigma_zeta_sd), ]\n  print(data.frame(table = s$table, wave = s$wave, respondents = s$n_persons, items = s$n_items,\n                   effect_SD = round(s$ate_sd, 2), sigma_zeta_SD = round(s$sigma_zeta_sd, 2),\n                   rho = round(s$rho, 2), p = signif(s$p, 2)), row.names = FALSE)\n  if (!is.null(dd$placebo)) {\n    cat(\"\\nPlacebo (pretest waves):\\n\")\n    print(data.frame(table = dd$placebo$table, wave = dd$placebo$wave,\n                     sigma_zeta_SD = round(dd$placebo$sigma_zeta_sd, 2), p = signif(dd$placebo$p, 2)),\n          row.names = FALSE)\n  }\n  if (nrow(dd$failed)) { cat(\"\\nFailed:\\n\"); print(dd$failed, row.names = FALSE) }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           table wave respondents items effect_SD sigma_zeta_SD   rho       p\n gilbert_meta_20    1         186    93      1.13          0.70  0.05 1.6e-31\n gilbert_meta_37   NA         839    21      0.48          0.28  0.33 1.9e-04\n gilbert_meta_89    1        1789    80     -0.02          0.02 -1.00 4.4e-01\n\nPlacebo (pretest waves):\n           table wave sigma_zeta_SD    p\n gilbert_meta_20    0          0.59 0.22\n gilbert_meta_89    0          0.01 0.47\n\nFailed:\n                          table                          error\n               wekker_2018_mfsq fewer than 3 dichotomous items\n buczel_2022_inoculation_belief fewer than 3 dichotomous items\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Partial run: 3 of 157 tables\n\nThis is a pilot run of `compute.R`, on two tables whose answers are known (`gilbert_meta_20` and `gilbert_meta_37`) and 3 others drawn at random, to check the pipeline. The full run replaces it.\n:::\n\nRun on 25 September 2026: 3 tables analysed, 2 failed. Item-level variation is significant at .05 in 2 of the 3.\n\nThe pilot checks the pipeline. `gilbert_meta_20` and `gilbert_meta_37` reproduce this lesson's estimates, and `gilbert_meta_20`'s pretest again shows no item-level variation. In `gilbert_meta_89` the arms end up level, and so do the items: the average effect and $\\sigma_\\zeta$ are both near zero, at the pretest and after. The two tables that failed have no dichotomous items. The full run will say how often items respond unequally across the IRW's trials, and whether the pretest placebo passes where there is one. The vignette itself is the place to read more.\n\n## Going further\n\n- Gilbert, J. B., Kim, J. S., & Miratrix, L. W. (2023). Modeling item-level heterogeneous treatment effects with the explanatory item response model: Leveraging large-scale online assessments to pinpoint the impact of educational interventions. *Journal of Educational and Behavioral Statistics*, 48(6), 889–913. <https://doi.org/10.3102/10769986231171710>. The IL-HTE model, and what ignoring it does to standard errors.\n- Gilbert, J. B., Himmelsbach, Z., Soland, J., Joshi, M., & Domingue, B. W. (2025). Estimating heterogeneous treatment effects with item-level outcome data: Insights from item response theory. *Journal of Policy Analysis and Management*, 44(4), 1417–1449. <https://doi.org/10.1002/pam.70025>. The model across 75 datasets from 48 trials, the collection this lesson's tables come from.\n- Gilbert, J. B., Miratrix, L. W., Joshi, M., & Domingue, B. W. (2025). Disentangling person-dependent and item-dependent causal effects: Applications of item response theory to the estimation of treatment effect heterogeneity. *Journal of Educational and Behavioral Statistics*, 50(1), 72–101. <https://doi.org/10.3102/10769986241240085>. The interaction of the Go deeper, derived and simulated.\n- Ahmed, I., Bertling, M., Zhang, L., Ho, A. D., Loyalka, P., Xue, H., Rozelle, S., & Domingue, B. W. (2025). Heterogeneity of item-treatment interactions masks complexity and generalizability in randomized controlled trials. *Journal of Research on Educational Effectiveness*, 18(4), 854–877. <https://doi.org/10.1080/19345747.2024.2361337>. DIF by treatment across 15 trials.\n- Sprangers, M. A. G., & Schwartz, C. E. (1999). Integrating response shift into health-related quality of life research: A theoretical model. *Social Science & Medicine*, 48(11), 1507–1515. <https://doi.org/10.1016/S0277-9536(99)00045-3>. Response shift, defined, with a model of how it arises.\n- Oort, F. J. (2005). Using structural equation modeling to detect response shifts and true change. *Quality of Life Research*, 14(3), 587–598. <https://doi.org/10.1007/s11136-004-0830-y>. Response shift as non-invariance across occasions.\n- Widaman, K. F., Ferrer, E., & Conger, R. D. (2010). Factorial invariance within longitudinal structural equation models: Measuring the same construct across time. *Child Development Perspectives*, 4(1), 10–18. <https://doi.org/10.1111/j.1750-8606.2009.00110.x>. Longitudinal invariance in a few pages.\n- Fischer, G. H. (2017). Measuring change using Rasch models. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 3. Applications* (pp. 387–404). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315117430>. A handbook chapter on measuring change with Rasch models.\n- De Boeck, P., & Wilson, M. (Eds.). (2004). *Explanatory item response models: A generalized linear and nonlinear approach*. Springer. <https://doi.org/10.1007/978-1-4757-3990-9>. Item response models as mixed models, the frame the IL-HTE model sits in.\n- Domingue, B. W., Duncan, L., Harrati, A., & Belsky, D. W. (2021). Short-term mental health sequelae of bereavement predict long-term physical health decline in older adults: U.S. Health and Retirement Study analysis. *The Journals of Gerontology: Series B*, 76(6), 1231–1240. <https://doi.org/10.1093/geronb/gbaa044>. The spousal-loss example; the item-level figures are in the supplement to the preprint (<https://doi.org/10.1101/19009878>).\n- From the IRW: the [IL-HTE vignette](https://itemresponsewarehouse.org/vignettes/il_hte.html), the corpus question of *Across the IRW*.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`gilbert_meta_20`](https://itemresponsewarehouse.org/tables/gilbert_meta_20/): Jayanthi, M., Gersten, R., Schumacher, R. F., Dimino, J., Smolkowski, K., & Spallone, S. (2021). Improving struggling fifth-grade students’ understanding of fractions: A randomized controlled trial of an intervention that stresses both concepts and procedures. Exceptional Children, 88(1), 81-100. Gersten, Russell; Jayanthi, Madhavi; Dimino, Joseph; Karp, Karen, 2019, \"Impact of a Tier 2 Fractions Intervention on 5th Grade At-Risk Students’ Fractions Achievement\", <https://doi.org/10.7910/DVN/Z4WMFE>, Harvard Dataverse, V1, UNF:6:8pMQK/5+cfpvcr4ACTvAmQ== [fileUNF]. Licence: CC0 1.0.\n- [`gilbert_meta_37`](https://itemresponsewarehouse.org/tables/gilbert_meta_37/): Carpena, F. (2024). Entertainment-Education for Better Health: Insights from a Field Experiment in India. The Journal of Development Studies, 60(5), 745-762. Carpena, Fenella, 2024, \"Replication Data for: Entertainment-Education for Better Health: Insights from a Field Experiment in India\", <https://doi.org/10.7910/DVN/EJ03JR>, Harvard Dataverse, V1, UNF:6:pX0ZhtBxkRpvQC6AOfVg4g== [fileUNF]. Licence: CC0 1.0.\n\n## For instructors\n\n- **Source:** EDUC 252 problem sets 5 (#4: treatment DIF in `gilbert_meta_20`, and the spousal-loss question) and 7 (#1: the treatment-by-baseline interaction with and without random item slopes), with the code in `ben-domingue/252`: `ps5/rctdif.R` and `ps7/ilhte.R` (which used `gilbert_meta_2`). There are no slides; the widgets, the simulation and the two-table analysis are new.\n- **Timing:** about 50 minutes for the core ideas and widgets; the real-data section works as a 30-minute lab (the model fits take about a minute locally). Problems 4 and 6 work as small-group discussions.\n- **Held back:** explaining which items move with item features (in [What is an item?](explanatory-irt.qmd)); then-tests and other designs for response shift are named only; item-level effects in polytomous outcomes are left out, as in the deep dive; life events with real data wait for an IRW table with item-level data around a bereavement.\n- **Data:** `gilbert_meta_20` has a pretest (wave 0, 37 items) and a posttest (wave 1, the same 37 items and 56 more); the table doesn't say what the `trans_math` block is beyond its label. `gilbert_meta_37` is the endline survey only, and its `treat` pools two film arms against the control arm. Its `std_baseline` closely tracks the number right on three knowledge questions asked at baseline (Carpena, 2024, baseline summary statistics), from our check against the replication data.\n- **Across the IRW:** `deepdives/invariance-experience/compute.R` is run by hand (it needs a Redivis token); the page reads its `results.rds`. The pilot took about three minutes for five tables.\n- **Solutions:** held back in `solutions/invariance-experience.qmd` (not published). Problem 6 is open.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}