{
  "hash": "a21a87511ba74a78198f386ac1faa671",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"What does a score mean? Norms, error bands, and cut scores\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Using calibrated items  \n**Tranche:** core (a first course)  \n**Before this:** [Classical test theory and reliability](ctt-reliability.qmd) · [Information, precision, and short forms](information.qmd)  \n**Builds toward:** none  \n**Picks up threads:** One standard error of measurement for everyone (from [Classical test theory and reliability](ctt-reliability.qmd)); Whether a scale has an equal unit changes group comparisons (from [What is measurement?](measurement.qmd))  \n**IRW tables:** [`c19prc_uk_mcbride_2021_phq9`](https://itemresponsewarehouse.org/tables/c19prc_uk_mcbride_2021_phq9/), [`coroiu_2018_phq9`](https://itemresponsewarehouse.org/tables/coroiu_2018_phq9/)  \n**From EDUC 252:** n/a  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\noptions(mc.cores = 1)\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {grid, rng, palette} from \"./widgets/irt.js\"\nimport {percentileRank, momentsFromCounts, qnorm, expectedScore, rawSem, testInfoGraded, invert, angoffPanel, diffReliability} from \"./widgets/score-meaning.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nA respondent scores 12 on the PHQ-9, a nine-item depression screener. What does the 12 mean? On its own, not much. It means something once we say whom it is compared with, how far it might move, and which side of a decision it falls on. [Classical test theory and reliability](ctt-reliability.qmd) gave every score one standard error; [Information, precision, and short forms](information.qmd) let the error change along the scale. This lesson puts both to work on the numbers respondents are given. The example is the PHQ-9 in a UK panel surveyed in the first week of the 2020 lockdown, with a German sample for contrast.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- turn a raw score into a percentile rank, z score, linear T and normalized T, and say what each assumes;\n- put an error band around a score, from one SEM or a conditional SEM, and say when the two differ;\n- compute the reliability of a difference score and a reliable change threshold;\n- treat a cut score as a decision, do an Angoff calculation, and say why classification near a cut is uncertain;\n- say what a score report should carry, and why group statistics use plausible values.\n\n## Core ideas\n\n### A score needs a reference\n\nA raw score becomes interpretable in one of two ways ([Glaser, 1963](https://doi.org/10.1037/h0049294)). A **norm-referenced** reading compares it with other people's scores; a **criterion-referenced** reading compares it with a standard fixed in advance, such as the screener's cut of 10. The *Standards* ask that users be told what a reported score means and where its meaning runs out ([AERA, APA & NCME, 2014](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf), open access, Standard [5.1](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf#page=112)). Cut scores come later; first, norms.\n\nThe standard norm-referenced scores are ([Angoff, 1971](https://openlibrary.org/works/OL3700878W); [Kolen & Brennan, 2014, ch. 9](https://doi.org/10.1007/978-1-4939-0317-7_9)):\n\n- the **percentile rank**: the percentage of the reference group scoring below, plus half of those scoring the same;\n- the **z score**, $(x - \\bar x)/s$, and the **linear T score**, $50 + 10z$;\n- the **normalized T score**, $50 + 10\\,\\Phi^{-1}(\\text{percentile rank}/100)$, which puts the percentile rank on a normal scale. PROMIS reports its measures as T scores centred on a reference population ([Cella et al., 2010](https://doi.org/10.1016/j.jclinepi.2010.04.011)).\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is measurement?](measurement.qmd): if a score is only ordinal, any order-preserving rescaling of it is as legitimate as the original, and only conclusions that survive every such rescaling are safe.\n:::\n\nA percentile rank uses nothing but order, so it survives every rescaling and needs no claim about equal units. A linear T keeps the raw distribution's shape and spacing; a normalized T imposes a normal shape. On a skewed distribution, such as PHQ-9 scores in the general population, the two part in the tail.\n\nEach is a comparison with one group at one time; the *Standards* ask that norms describe that group clearly and be renewed often enough to stay accurate (Standards [5.8](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf#page=114) and [5.9](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf#page=114)).\n\n#### Try it: one score, four reference groups\n\nThe PHQ-9 sum scores analysed below: UK adults in March 2020, two UK age bands, and German adults in 2012. The table converts one score; the panels draw each group, with a movable cut.\n\n```{ojs}\n//| echo: false\nnm_groups = [\"UK 2020, all adults\", \"UK 2020, ages 18–34\", \"UK 2020, ages 55+\", \"Germany 2012\"]\nviewof nm_score = Inputs.range([0, 27], {value: 10, step: 1, label: \"PHQ-9 score\"})\n```\n\n```{ojs}\n//| echo: false\nnm_rows = transpose(sm_norms)\nnm_counts = Object.fromEntries(nm_groups.map(g => [g, Array.from({length: 28}, (_, s) => nm_rows.find(d => d.group === g && d.score === s)?.n ?? 0)]))\nnm_table = nm_groups.map(g => {\n  const c = nm_counts[g], mo = momentsFromCounts(c), pr = percentileRank(nm_score, c), z = (nm_score - mo.mean) / mo.sd;\n  return {\"Reference group\": g, n: mo.n, \"Percentile rank\": pr.toFixed(1), z: z.toFixed(2),\n          \"Linear T\": (50 + 10 * z).toFixed(1), \"Normalized T\": (50 + 10 * qnorm(pr / 100)).toFixed(1)};\n})\nInputs.table(nm_table, {layout: \"auto\", select: false})\n```\n\n```{ojs}\n//| echo: false\nviewof nm_cut = Inputs.range([1, 27], {value: 10, step: 1, label: \"Cut score (screen positive at or above)\"})\n```\n\n```{ojs}\n//| echo: false\nnm_bars = nm_groups.flatMap(g => { const n = momentsFromCounts(nm_counts[g]).n;\n  return nm_counts[g].map((c, s) => ({group: g, x1: s - 0.45, x2: s + 0.45, pct: 100 * c / n, side: s >= nm_cut ? \"at or above the cut\" : \"below the cut\"})); })\nnm_share = nm_groups.map(g => { const c = nm_counts[g], n = momentsFromCounts(c).n;\n  return {group: g, share: 100 * c.slice(nm_cut).reduce((u, v) => u + v, 0) / n}; })\nPlot.plot({\n  width: 700, height: 460, marginRight: 10, x: {label: \"PHQ-9 sum score\", domain: [-0.5, 27.5]}, y: {label: \"Percent of the group\"},\n  fy: {label: null, domain: nm_groups}, facet: {data: nm_bars, y: \"group\"},\n  color: {legend: true, domain: [\"below the cut\", \"at or above the cut\"], range: [palette.light, palette.main]},\n  marks: [\n    Plot.rectY(nm_bars, {x1: \"x1\", x2: \"x2\", y: \"pct\", fill: \"side\", fy: \"group\"}),\n    Plot.ruleX([nm_cut - 0.5], {stroke: palette.contrast, strokeWidth: 2}),\n    Plot.text(nm_share, {fy: \"group\", x: 27, frameAnchor: \"top-right\", dy: 6, textAnchor: \"end\", text: d => `${d.group}: ${d.share.toFixed(1)}% at or above ${nm_cut}`, fill: palette.ink}),\n    Plot.ruleY([0])\n  ]\n})\n```\n\nA 10 has a percentile rank of 79.0 among all UK adults, 64.7 among 18–34-year-olds, 90.1 among those 55 and over, and 96.2 in the German sample: one score, four meanings. At 20, the UK linear T is 73.5 and the normalized T 68.6; the long right tail stretches one and not the other. At 0, 28.5% of the UK sample are tied at a percentile rank of 14.2.\n\nIn the panels, the same cut of 10 flags 36.9% of UK 18–34-year-olds, 22.1% of all UK adults, 10.5% of those 55 and over and 4.1% of the German sample. Slide it to 15 and the four shares are 18.5%, 10.9%, 4.6% and 1.2%. A fixed cut flags very different shares of different groups.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Respondent A's percentile rank rises from 50 to 60 between two surveys; respondent B's rises from 90 to 95. With the same reference group both times, what can you conclude without assuming the scale has equal units?\",\n  options: [\n    {text: \"Both moved up relative to the reference group; nothing about who changed more on the construct\", correct: true, why: \"Percentile ranks carry order only. A 10-point rise near the middle and a 5-point rise in the tail can correspond to any sizes of change on the construct, depending on the spacing of the scale there.\"},\n    {text: \"A changed twice as much as B\", correct: false, why: \"That treats differences in percentile ranks as equal units. Near the middle of a distribution a small change in score moves many percentile points; in the tail a large one moves few.\"},\n    {text: \"B changed more, because moving up in the tail is harder\", correct: false, why: \"That is a claim about the spacing of the scale in the tail, which order alone doesn't give you.\"}\n  ]\n})\n```\n\n### Error bands: one SEM, or a conditional one\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd): the standard error of measurement, $\\sigma_E = \\sigma_X\\sqrt{1 - \\rho_{XX'}}$, is the typical distance between a respondent's observed and true scores, and CTT gives the same one to everyone, whatever their score.\n:::\n\nThe simplest band is $x \\pm 1.96\\,\\sigma_E$, the true scores consistent with what we observed ([Lord & Novick, 1968](https://openlibrary.org/works/OL6568286W)). With the PHQ-9's SD of 6.22 and alpha of 0.92 in the UK sample below, the SEM is 1.74 and the band ±3.4 points around every score: a 12 has a band from 8.6 to 15.4, which straddles the cut.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Information, precision, and short forms](information.qmd): test information $I(\\theta)$ is the sum of item information, and the conditional SEM, $1/\\sqrt{I(\\theta)}$, is small where many informative items sit and grows where they run out. A screening scale spends its precision where it makes its decisions.\n:::\n\nThe conditional SEM gives bands that change width along the scale, and the *Standards* ask for the standard error near each cut score (Standard [2.14](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf#page=56); [Kolen, Zeng & Hanson, 1996](https://doi.org/10.1111/j.1745-3984.1996.tb00485.x), carry conditional SEMs to a reported scale). The PHQ-9's items have four categories, so the model below is the graded response model ([Samejima, 1969](https://doi.org/10.1007/BF03372160)), with one slope per item and a boundary between adjacent categories ([Models for polytomous responses](polytomous.qmd) develops it). All we need here is that its information adds over items, and that it says how much the sum score varies across replications at a given $\\theta$.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Factor analysis II](fa-confirmatory.qmd): omega can stand in for alpha in $\\sigma_X\\sqrt{1 - \\rho}$. It changes the size of the one SEM, not the fact that there is one.\n:::\n\n#### Try it: bands around a PHQ-9 score\n\nFrom the graded model fitted below. The upper panel is in PHQ-9 score points: for each sum score, the light bar is CTT's band and the dark bar the model's, using the spread of the sum score at the $\\theta$ whose expected score is that sum. The lower panel is the conditional SEM on the $\\theta$ scale.\n\n```{ojs}\n//| echo: false\nviewof eb_score = Inputs.range([1, 26], {value: 12, step: 1, label: \"Observed PHQ-9 score\"})\nviewof eb_level = Inputs.radio([\"68%\", \"95%\"], {value: \"95%\", label: \"Band\"})\n```\n\n```{ojs}\n//| echo: false\neb_items = transpose(sm_items).map(d => ({a: d.a, d: [d.d1, d.d2, d.d3]}))\neb_z = eb_level === \"95%\" ? 1.96 : 1\neb_rows = grid(1, 26, 26).map(s => {\n  const t = invert(u => expectedScore(u, eb_items), s);\n  return {s, theta: t, raw: rawSem(t, eb_items), csem: 1 / Math.sqrt(testInfoGraded(t, eb_items))};\n})\neb_now = eb_rows[eb_score - 1]\neb_cut = invert(u => expectedScore(u, eb_items), 10)\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Observed PHQ-9 score\", domain: [0, 27]}, y: {label: `${eb_level} band, in PHQ-9 score points`, domain: [-5, 32]},\n  color: {legend: true, domain: [\"CTT: one SEM (score points)\", \"Model: conditional SEM (score points)\"], range: [palette.light, palette.main]},\n  marks: [\n    Plot.ruleY([9.5], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n    Plot.ruleX(eb_rows, {x: d => d.s - 0.18, y1: d => d.s - eb_z * sm_sem, y2: d => d.s + eb_z * sm_sem, stroke: () => \"CTT: one SEM (score points)\", strokeWidth: 4}),\n    Plot.ruleX(eb_rows, {x: d => d.s + 0.18, y1: d => d.s - eb_z * d.raw, y2: d => d.s + eb_z * d.raw, stroke: () => \"Model: conditional SEM (score points)\", strokeWidth: 4}),\n    Plot.dot([eb_now], {x: \"s\", y: \"s\", r: 6, fill: palette.contrast})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nPlot.plot({\n  width: 700, height: 200, x: {label: \"θ (logits)\", domain: [-3, 3]}, y: {label: \"Conditional SEM, in θ units (logits)\", domain: [0, 3]},\n  marks: [\n    Plot.ruleX([eb_cut], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n    Plot.line(grid(-3, 3, 241).map(t => ({t, se: Math.min(3, 1 / Math.sqrt(testInfoGraded(t, eb_items)))})), {x: \"t\", y: \"se\", stroke: palette.main, strokeWidth: 2.5}),\n    Plot.dot([eb_now], {x: \"theta\", y: \"csem\", r: 6, fill: palette.contrast})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`A score of ${eb_score}: the CTT band runs from **${(eb_score - eb_z * sm_sem).toFixed(1)}** to **${(eb_score + eb_z * sm_sem).toFixed(1)}**; the model's from **${(eb_score - eb_z * eb_now.raw).toFixed(1)}** to **${(eb_score + eb_z * eb_now.raw).toFixed(1)}** (raw-score SEM ${eb_now.raw.toFixed(2)}, against CTT's ${sm_sem.toFixed(2)}). ${(eb_score - eb_z * eb_now.raw <= 9.5 && eb_score + eb_z * eb_now.raw >= 9.5) ? \"The model's band crosses the cut (the dashed line, between 9 and 10).\" : \"The model's band stays on one side of the cut (the dashed line, between 9 and 10).\"} On the θ scale this score sits at ${eb_now.theta.toFixed(2)}, where the conditional SEM is ${eb_now.csem.toFixed(2)}; the cut is at θ = ${eb_cut.toFixed(2)} (dashed line, lower panel).`\n```\n\nNear the cut the model's band is wider than CTT's (7.2 to 16.8 at a score of 12); at a score of 1 it is narrower, because a sum at the floor can't move far. Yet on the $\\theta$ scale (lower panel) the conditional SEM grows with distance from the middle. Both are right: the expected-score curve flattens near the floor and ceiling, so there one score point covers a wide stretch of $\\theta$, and the error in points divided by the curve's slope approximates the error in $\\theta$ (shown below). A low score is precise about the score and imprecise about how far below the cut the respondent is.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A scale has reliability 0.84 and SD 5. A respondent scores 22, and the cut is 18. Does the 95% CTT band around 22 reach the cut?\",\n  options: [\n    {text: \"No, but only just: the band runs from 18.08 to 25.92\", correct: true, why: \"SEM $= 5\\\\sqrt{0.16} = 2$, and $1.96 \\\\times 2 = 3.92$. The band stops 0.08 above the cut, which is one reason to report the band itself rather than only a verdict.\"},\n    {text: \"Yes: the band runs from 21.2 to 22.8\", correct: false, why: \"That uses $5 \\\\times 0.16 = 0.8$ as the SEM. The SEM takes the square root: $\\\\sigma_X\\\\sqrt{1 - \\\\rho}$.\"},\n    {text: \"Yes: the band runs from 12.2 to 31.8\", correct: false, why: \"That is $\\\\pm 1.96$ SDs, the spread of scores across respondents, not the error in one respondent's score.\"}\n  ]\n})\n```\n\n### Difference scores and reliable change\n\nWhen the question is whether a respondent changed, the score of interest is a difference, $D = X_2 - X_1$. For two occasions with equal variances, reliabilities $\\rho_1$ and $\\rho_2$ and correlation $r_{12}$, its reliability is\n$$\\rho_D = \\frac{(\\rho_1 + \\rho_2)/2 - r_{12}}{1 - r_{12}}$$\n([Lord, 1956](https://doi.org/10.1177/001316445601600401)). The higher the occasions correlate, the less of the difference is true change. [Cronbach and Furby (1970)](https://doi.org/10.1037/h0029382) asked whether change should be measured this way at all; [Rogosa and Willett (1983)](https://doi.org/10.1111/j.1745-3984.1983.tb00211.x) showed that when respondents differ appreciably in how much their true scores change, the difference can be quite reliable. Which applies depends on the data.\n\nFor one respondent, does the change exceed what error alone would produce? The **reliable change index** of [Jacobson and Truax (1991)](https://doi.org/10.1037/0022-006x.59.1.12) divides the change by the standard error of a difference, $\\sqrt 2\\,\\sigma_E$, so a change counts as reliable at the 5% level when $|x_2 - x_1| \\ge 1.96\\sqrt{2}\\,\\sigma_E$. The *Standards* ask for precision data for such differences (Standard [2.4](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf#page=53)).\n\n#### Try it: how reliable is a change?\n\n```{ojs}\n//| echo: false\nviewof rc_rel = Inputs.range([0.5, 0.99], {value: 0.92, step: 0.01, label: \"Reliability at each occasion\"})\nviewof rc_r = Inputs.range([0, 0.95], {value: 0.70, step: 0.01, label: \"Correlation between occasions\"})\nviewof rc_sd = Inputs.range([1, 15], {value: 6.2, step: 0.1, label: \"SD of the scores\"})\n```\n\n```{ojs}\n//| echo: false\nrc_now = diffReliability(rc_rel, rc_rel, rc_r)\nPlot.plot({\n  width: 700, height: 260, x: {label: \"Correlation between occasions\", domain: [0, 1]}, y: {label: \"Reliability of the difference\", domain: [0, 1]},\n  marks: [\n    Plot.line(grid(0, rc_rel, 101).map(r => ({r, rel: diffReliability(rc_rel, rc_rel, r)})), {x: \"r\", y: \"rel\", stroke: palette.main, strokeWidth: 2.5}),\n    Plot.ruleX([rc_rel], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n    ...(rc_r <= rc_rel ? [Plot.dot([{r: rc_r, rel: rc_now}], {x: \"r\", y: \"rel\", r: 6, fill: palette.contrast})] : [])\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`${rc_r > rc_rel ? \"The occasions correlate more than either is reliable, which the classical model doesn't allow (the dashed line is the limit). \" : `Reliability of the difference: **${rc_now.toFixed(2)}**. `}SEM ${(rc_sd * Math.sqrt(1 - rc_rel)).toFixed(2)}; a change counts as reliable when it is at least **${(1.96 * Math.SQRT2 * rc_sd * Math.sqrt(1 - rc_rel)).toFixed(1)}** points.`\n```\n\nAt the PHQ-9's values the difference has reliability 0.73, and a change must be 4.9 points to count. Raise the correlation to 0.85 and the reliability falls to 0.47 while the threshold stays put: the threshold depends only on the SEM. Lower the reliability to 0.80 and the threshold grows to 7.7 points, over a quarter of the scale.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A scale has reliability 0.80 and SD 10. How large must a change between two occasions be to count as reliable at the 5% level?\",\n  options: [\n    {text: \"About 12.4 points\", correct: true, why: \"SEM $= 10\\\\sqrt{0.2} \\\\approx 4.47$; the standard error of a difference is $\\\\sqrt 2 \\\\times 4.47 \\\\approx 6.32$; and $1.96 \\\\times 6.32 \\\\approx 12.4$.\"},\n    {text: \"About 8.8 points\", correct: false, why: \"That is $1.96 \\\\times$ SEM, the band for one score. A difference carries error from both occasions, so its standard error is $\\\\sqrt 2$ times larger.\"},\n    {text: \"About 6.3 points\", correct: false, why: \"That is the standard error of the difference itself. For the 5% level it still needs multiplying by 1.96.\"}\n  ]\n})\n```\n\n### Cut scores are decisions\n\nA cut score turns a score into a category. Where does the number come from? There are two routes, and both end in a choice.\n\nThe **empirical** route sets the cut against an outside criterion. The PHQ-9's 10 was chosen against diagnostic interviews: in its first validation a score of 10 or more had a sensitivity and a specificity of 88% for major depression ([Kroenke, Spitzer & Williams, 2001](https://doi.org/10.1046/j.1525-1497.2001.016009606.x)), and an individual-participant meta-analysis found that 10 maximized the two combined ([Levis, Benedetti & Thombs, 2019](https://doi.org/10.1136/bmj.l1476)). An earlier meta-analysis, though, found no substantial differences in pooled sensitivity and specificity across cuts from 8 to 11 ([Manea, Gilbody & McMillan, 2012](https://doi.org/10.1503/cmaj.110829)). The data narrow the range; choosing within it trades missed cases against false alarms. Accuracy against the criterion belongs to [Validity evidence](validity-evidence.qmd).\n\nThe **judgmental** route asks experts. In the **Angoff method** ([Angoff, 1971](https://openlibrary.org/works/OL3700878W); [Cizek & Bunch, 2007, ch. 6](https://doi.org/10.4135/9781412985918.n6)) each judge pictures a borderline respondent, just good enough to pass, and estimates for every item the probability that this respondent gets it right. A judge's cut is the sum of their probabilities; the panel's is the mean over judges, with a standard error from their spread. The **bookmark method** orders items by difficulty and asks where the borderline respondent's mastery stops ([Cizek & Bunch, 2007, ch. 10](https://doi.org/10.4135/9781412985918.n10)).\n\n#### Try it: an Angoff panel\n\nTen Rasch items, difficulties −2 to 2. Each judge's borderline respondent is scattered around the panel's, and ratings carry a little noise.\n\n```{ojs}\n//| echo: false\nviewof an_n = Inputs.range([3, 15], {value: 5, step: 1, label: \"Number of judges\"})\nviewof an_theta = Inputs.range([-1.5, 1.5], {value: 0.5, step: 0.1, label: \"The panel's borderline θ\"})\nviewof an_spread = Inputs.range([0, 1], {value: 0.4, step: 0.05, label: \"How much judges disagree (SD)\"})\n```\n\n```{ojs}\n//| echo: false\nan_bs = [-2, -1.5, -1, -0.5, 0, 0.25, 0.5, 1, 1.5, 2]\nan = angoffPanel(an_bs, an_n, an_theta, an_spread, 0.05, rng(61))\nan_cells = an.panel.flatMap(j => j.ratings.map((p, i) => ({judge: `Judge ${j.judge}`, item: `b = ${an_bs[i]}`.replace(\"-\", \"−\"), p})))\nPlot.plot({\n  width: 700, height: 60 + 28 * an_n, marginLeft: 70, padding: 0.05,\n  x: {label: \"Item\", domain: an_bs.map(b => `b = ${b}`.replace(\"-\", \"−\"))}, y: {label: null, domain: an.panel.map(j => `Judge ${j.judge}`)},\n  color: {type: \"linear\", domain: [0, 1], range: [palette.white, palette.main], legend: true, label: \"Rated probability\"},\n  marks: [\n    Plot.cell(an_cells, {x: \"item\", y: \"judge\", fill: \"p\"}),\n    Plot.text(an_cells, {x: \"item\", y: \"judge\", text: d => d.p.toFixed(2), fill: d => d.p > 0.6 ? palette.white : palette.ink})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Judges' cuts: ${an.panel.map(j => j.sum.toFixed(2)).join(\", \")}. The panel's cut is **${an.cut.toFixed(2)}** of 10, with a standard error of **${an.se.toFixed(2)}**. Through the test characteristic curve that is θ = **${an.thetaCut.toFixed(2)}** (95% interval ${an.thetaLo.toFixed(2)} to ${an.thetaHi.toFixed(2)}).`\n```\n\nAt the defaults judge 4 (a cut of 3.41, against 5.48 to 6.10) pulls the panel's cut, 5.39 (standard error 0.51), down to θ = 0.24, below the intended 0.5. With no disagreement the standard error is 0.07 and the cut lands at θ = 0.50. With disagreement 1 it is 1.01, and 15 judges bring it to 0.50, roughly the square-root law.\n\nEither way, the *Standards* ask that a cut's rationale be documented and, where feasible, informed by data on the criterion (Standards [5.21](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf#page=117) and [5.23](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf#page=118)). And a respondent whose true score sits at the cut would screen positive on about half of hypothetical replications; the Go deeper callout turns that into a number for a test.\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: classification consistency at a cut\n\n**Assumptions:** an item response model holds with known item parameters; responses are locally independent given $\\theta$; two administrations are independent given $\\theta$ (parallel forms, or the same form with no memory of the first); respondents are classified by their sum score $X$ against a cut $C$.\n\n**Given $\\theta$.** Local independence lets us compute the sum score's distribution at each $\\theta$ exactly, by adding items one at a time ([Lord & Wingersky, 1984](https://doi.org/10.1177/014662168400800409)). Start with $f_0(0) = 1$; after item $i$, with category probabilities $P_{ik}(\\theta)$ for scores $k = 0, 1, \\dots$,\n$$f_i(s) = \\sum_k f_{i-1}(s - k)\\,P_{ik}(\\theta).$$\nThen $p(\\theta) = \\Pr(X \\ge C \\mid \\theta) = \\sum_{s \\ge C} f_I(s)$, and two independent administrations agree with probability\n$$\\kappa(\\theta) = p(\\theta)^2 + \\big(1 - p(\\theta)\\big)^2,$$\nwhich is near 1 far from the cut and falls to 1/2 where $p(\\theta) = 1/2$.\n\n**Over respondents.** The test's **classification consistency** is the average of $\\kappa(\\theta)$ over the ability distribution, $\\int \\kappa(\\theta)\\,g(\\theta)\\,d\\theta$, with $g$ the fitted distribution, which needs only one administration. [Lee (2010)](https://doi.org/10.1111/j.1745-3984.2009.00096.x) sets out this approach for tests that mix dichotomous and polytomous items. The average is high when most respondents sit far from the cut, whatever happens near it, so a consistency above 0.9 can coexist with near coin-flip classification for the respondents closest to the cut. The Simulate section checks both against two simulated administrations.\n\n**Without an item response model.** [Livingston and Lewis (1995)](https://doi.org/10.1111/j.1745-3984.1995.tb00462.x) build the same quantity from classical ingredients: the reliability gives an effective test length, a four-parameter beta distribution stands in for the true scores, and a binomial for the error around them.\n:::\n\n### What goes in a score report\n\nReviews of how score reports are designed and read suggest giving the score with its band, the reference group and its date, the cut and what crossing it means, and what the score does not show ([Goodman & Hambleton, 2004](https://doi.org/10.1207/s15324818ame1702_3); [Zenisky & Hambleton, 2012](https://doi.org/10.1111/j.1745-3992.2012.00231.x); Standard [6.10](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf#page=129)). A PHQ-9 report would add that the manual treats 10 or more as a flag for a possible clinically significant condition, not a diagnosis ([PHQ instruction manual, n.d., p. 2](https://www.phqscreeners.com/images/sites/g/files/g10016261/f/201412/instructions.pdf)).\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Estimating abilities](ability-estimation.qmd): EAP estimates shrink toward the mean, so averaging them understates differences between groups. That lesson's simulation makes the point with numbers.\n:::\n\nReports about groups differ: the best estimate for each respondent is not the best input for describing the group. Estimates that borrow from a prior, such as the posterior mean (EAP; [Estimating abilities](ability-estimation.qmd)), are pulled toward the centre, most where the test is imprecise, so their spread is smaller than the population's. **Plausible values** are draws from each respondent's posterior instead of its mean; a statistic computed on each set of draws and combined recovers the population's spread and carries measurement error into its standard error ([Mislevy, Beaton, Kaplan & Sheehan, 1992](https://doi.org/10.1111/j.1745-3984.1992.tb00371.x); [Wu, 2005](https://doi.org/10.1016/j.stueduc.2005.05.005)). They are for group statistics only.\n\n## Simulate\n\n5,000 respondents take a PHQ-like graded test twice, with a cut at 10. How often does a respondent land on the same side both times? Compare the model's prediction (the Go deeper callout) and CTT's, which treats the two scores as normal with correlation alpha. Base R; seconds.\n\nWith the seed as written, 92.7% are classified the same way twice; the model predicts 93.1% and CTT's normal approximation 90.4%, because the scores pile up at the floor, where a normal curve puts too few. Among the 10.4% whose chance of screening positive is between 0.2 and 0.8, only 55.6% are classified the same way twice. Try `cut <- 5` and `cut <- 20`.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-21\n# Classification consistency at a cut score: simulate two administrations of a\n# nine-item graded test, count how often a respondent lands on the same side of\n# the cut twice, and compare with what the model and CTT predict from one\n# administration. Base R only. Part of the IRW course lesson \"What does a score\n# mean?\".\nset.seed(61)\nn   <- 5000                       # respondents\ncut <- 10                         # screen positive at a sum score of cut or more\na   <- c(3.2, 3.6, 2.2, 2.7, 2.6, 3.4, 3.5, 3.1, 3.4)   # slopes, close to the PHQ-9 fit\nd   <- rbind(c(-0.6, -3.2, -5.6), c(-0.3, -3.7, -5.9), c( 0.1, -2.1, -3.7),\n             c( 0.1, -2.6, -4.2), c(-1.3, -3.1, -4.9), c(-1.9, -3.8, -6.0),\n             c(-1.5, -3.9, -6.1), c(-3.3, -4.7, -6.8), c(-3.4, -5.0, -6.9))\n# mirt's graded model: P(x >= k) = 1 / (1 + exp(-(a * theta + d_k))), k = 1, 2, 3\n\n# Category probabilities (0, 1, 2, 3) for one item at each theta\ncat_probs <- function(theta, a, d) {\n  star <- cbind(1, matrix(sapply(d, function(dk) plogis(a * theta + dk)), ncol = 3), 0)\n  star[, 1:4] - star[, 2:5]\n}\n# One administration: nine responses per respondent, returned as sum scores\nadminister <- function(theta) {\n  x <- sapply(1:9, function(i) {\n    p <- cat_probs(theta, a[i], d[i, ])\n    u <- runif(length(theta))\n    rowSums(u > t(apply(p, 1, cumsum)))    # 0..3\n  })\n  list(items = x, sum = rowSums(x))\n}\n# The distribution of the sum score given theta (Lord & Wingersky, 1984)\nsum_dist <- function(theta) {\n  f <- 1\n  for (i in 1:9) {\n    p <- cat_probs(theta, a[i], d[i, ])\n    g <- numeric(length(f) + 3)\n    for (k in 0:3) g[(1:length(f)) + k] <- g[(1:length(f)) + k] + f * p[k + 1]\n    f <- g\n  }\n  f                                       # f[s + 1] = P(sum = s | theta)\n}\n\ntheta  <- rnorm(n)\nfirst  <- administer(theta)\nsecond <- administer(theta)               # same respondents, fresh errors\n\n# 1. Observed: same side of the cut on both administrations\nobserved <- mean((first$sum >= cut) == (second$sum >= cut))\n\n# 2. The model's prediction, from each respondent's theta:\n#    P(same side) = p^2 + (1 - p)^2, where p = P(sum >= cut | theta)\np_pos <- sapply(theta, function(t) sum(sum_dist(t)[(cut:27) + 1]))\nirt   <- mean(p_pos^2 + (1 - p_pos)^2)\n\n# 3. CTT's prediction, from one administration: two normal scores with the\n#    first administration's mean and SD, correlated at alpha\nalpha <- function(X) { k <- ncol(X); k / (k - 1) * (1 - sum(apply(X, 2, var)) / var(rowSums(X))) }\nrel   <- alpha(first$items)\nz1    <- rnorm(1e5); z2 <- rel * z1 + sqrt(1 - rel^2) * rnorm(1e5)\nm <- mean(first$sum); s <- sd(first$sum)\nctt   <- mean(((m + s * z1) >= cut - 0.5) == ((m + s * z2) >= cut - 0.5))\n\nround(c(positive_first = mean(first$sum >= cut), alpha = rel,\n        observed = observed, irt = irt, ctt = ctt), 3)\n\n# Near the cut: respondents whose chance of screening positive is between 0.2 and 0.8\nnear <- p_pos > 0.2 & p_pos < 0.8\nround(c(share_near = mean(near),\n        observed_near = mean(((first$sum >= cut) == (second$sum >= cut))[near])), 3)\n\n```\n:::\n\n\n[Download this code](code/score-meaning-sim.R) to run it in your own R session.\n\n## With real data\n\n\n\nThe main example is [c19prc_uk_mcbride_2021_phq9](https://itemresponsewarehouse.org/tables/c19prc_uk_mcbride_2021_phq9/): the PHQ-9 in the COVID-19 Psychological Research Consortium's UK panel ([Bentall et al., 2022](https://doi.org/10.5255/UKDA-SN-855552)). Wave 1 is an online sample of 2,025 adults with quotas on age, sex and household income, surveyed from 23 to 28 March 2020, the first week of lockdown; 1,406 were followed up a month later ([McBride et al., 2021](https://doi.org/10.1002/mpr.1861)). Its job is to supply real norms, a real cut and two waves. The PHQ-9 asks how often in the last two weeks the respondent was bothered by each of nine symptoms, beginning with \"Little interest or pleasure in doing things\" ([PHQ instruction manual, n.d., p. 5](https://www.phqscreeners.com/images/sites/g/files/g10016261/f/201412/instructions.pdf); [Kroenke, Spitzer & Williams, 2001](https://doi.org/10.1046/j.1525-1497.2001.016009606.x)). Items are scored 0 (not at all) to 3 (nearly every day), none reversed. The code needs `mirt` ([Chalmers, 2012](https://doi.org/10.18637/jss.v048.i06)); [download it](code/score-meaning-irw.R).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(mirt)\n# Each IRW table has a landing page (itemresponsewarehouse.org/tables/<name>/) with a\n# CSV download. These links are pinned to one version of the data.\nuk_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_4:v7_0.c19prc_uk_mcbride_2021_phq9/rows?format=csv\"\nde_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_6:v3_4.coroiu_2018_phq9/rows?format=csv\"\nuk <- read.csv(uk_url)\n# Keying: every item is 0 (not at all) to 3 (nearly every day); higher = more\n# frequent symptoms, and none is reversed. The panel has six waves; wave 1 is the\n# March 2020 baseline and wave 2 the follow-up a month later.\ntable(uk$wave[!duplicated(paste(uk$id, uk$wave))])     # respondents per wave\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   1    2    3    4    5    6 \n2025 1406 2019 3867 2520 2058 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nlong2wide <- function(df) {\n  wide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\n  as.data.frame(wide[, order(colnames(wide))])\n}\nw1 <- long2wide(uk[uk$wave == 1, ])\nage <- tapply(uk$cov_age, uk$id, function(x) x[1])[rownames(w1)]\nc(respondents = nrow(w1), complete = sum(complete.cases(w1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents    complete \n       2025        2025 \n```\n\n\n:::\n:::\n\n\nEveryone answered all nine items. A check against [Shevlin et al. (2020)](https://doi.org/10.1192/bjo.2020.109), who report that 22.1% of this sample scored 10 or more, with alpha 0.92:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Check the pipeline against the published figures for wave 1 (Shevlin et al., 2020).\nx <- rowSums(w1)\nalpha <- function(X) { k <- ncol(X); k / (k - 1) * (1 - sum(apply(X, 2, var)) / var(rowSums(X))) }\nskew <- function(v) mean((v - mean(v))^3) / sd(v)^3\nround(c(mean = mean(x), sd = sd(x), skew = skew(x), share_zero = mean(x == 0),\n        share_10_plus = mean(x >= 10), alpha = alpha(w1)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         mean            sd          skew    share_zero share_10_plus \n        5.378         6.220         1.291         0.285         0.221 \n        alpha \n        0.921 \n```\n\n\n:::\n:::\n\n\nWe get 22.1% and 0.921. The mean is 5.38, the SD 6.22 and the skew 1.29; 28.5% score 0.\n\n### Norms: what is a 10?\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"22% of this sample score 10 or more. What percentile rank does a score of 10 have, and is it the same for 18–34-year-olds as for those 55 and over?\",\n  choices: [\"About the 50th, at every age\", \"About the 80th, and about the same in each age band\", \"About the 80th overall; lower for the young, higher for the old\", \"About the 95th overall\"],\n  answer: \"About the 80th overall; lower for the young, higher for the old\",\n  reveal: \"A 10 is at the 79th percentile overall, the 65th among 18–34-year-olds and the 90th among those 55 and over. The younger respondents reported more symptoms (a mean of 7.8 against 3.4), so the same score is less unusual among them. The table below shows it.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Percentile rank: the percentage scoring below, plus half of those scoring exactly\n# the same (the midpoint convention). It uses only the order of the scores.\npr <- function(score, ref) 100 * (mean(ref < score) + mean(ref == score) / 2)\nband <- cut(age, c(17, 34, 54, Inf), labels = c(\"18-34\", \"35-54\", \"55+\"))\ngroups <- c(list(\"UK, all\" = x), split(x, band))\nround(t(sapply(groups, function(g) c(n = length(g), mean = mean(g),\n  share_10_plus = mean(g >= 10), pr_of_10 = pr(10, g)))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           n mean share_10_plus pr_of_10\nUK, all 2025 5.38          0.22    78.96\n18-34    626 7.82          0.37    64.70\n35-54    763 5.05          0.20    81.39\n55+      636 3.37          0.11    90.09\n```\n\n\n:::\n:::\n\n\nA 10 has a percentile rank of 79.0 overall, 64.7 among 18–34-year-olds and 90.1 among those 55 and over. \"Unusual for a UK adult in March 2020\" and \"unusual for your age\" are both reasonable norms, and they give different answers.\n\nThe contrast is [coroiu_2018_phq9](https://itemresponsewarehouse.org/tables/coroiu_2018_phq9/), the same items in German, from adults representative by age and sex, interviewed at home in 2012 ([Coroiu et al., 2018](https://doi.org/10.1371/journal.pone.0190771)). Its job is to show how much a norm depends on its reference group.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nde <- read.csv(de_url)\nwde <- long2wide(de)\nxde <- rowSums(wde[complete.cases(wde), ])    # 43 respondents skipped an item\nround(c(n = length(xde), mean = mean(xde), sd = sd(xde),\n        share_10_plus = mean(xde >= 10), pr_of_10 = pr(10, xde)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            n          mean            sd share_10_plus      pr_of_10 \n     2404.000         2.290         3.213         0.041        96.215 \n```\n\n\n:::\n:::\n\n\nOf the 2,404 respondents who answered every item, 4.1% score 10 or more, and a 10 has a percentile rank of 96.2. An earlier German household survey found a similar share, 5.6% ([Kocalevent, Hinz & Brähler, 2013](https://doi.org/10.1016/j.genhosppsych.2013.04.006)). Is the UK's 22% the pandemic's doing, then? These data can't say. The samples differ in country, language, year, sampling (an online quota panel against a household sample) and mode (a screen against an interviewer), and any of these can move a symptom count. What the comparison shows is how much a percentile rank depends on its reference group: the same 10 is the 79th percentile in one and the 96th in the other.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# A linear T keeps the raw distribution's shape; a normalized T forces it to be normal.\nlinear_T     <- function(score, ref) 50 + 10 * (score - mean(ref)) / sd(ref)\nnormalized_T <- function(score, ref) 50 + 10 * qnorm(pr(score, ref) / 100)\nround(sapply(c(0, 5, 10, 20), function(s)\n  c(raw = s, pr = pr(s, x), linear_T = linear_T(s, x), normalized_T = normalized_T(s, x))), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             [,1] [,2] [,3] [,4]\nraw           0.0  5.0 10.0 20.0\npr           14.2 61.7 79.0 96.8\nlinear_T     41.4 49.4 57.4 73.5\nnormalized_T 39.3 53.0 58.1 68.6\n```\n\n\n:::\n:::\n\n\nThe two T scores are 49.4 and 53.0 at a raw 5, but 73.5 and 68.6 at a raw 20: the skew separates them in the tail.\n\n\n::: {.cell}\n\n:::\n\n\n### Error near the cut\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# One SEM for everyone, and a 95% band of 1.96 SEM either side of each score.\nsem <- sd(x) * sqrt(1 - alpha(w1))\npos <- x >= 10                                     # screened positive\nround(c(sem = sem, half_width = 1.96 * sem,\n        positives = sum(pos), band_reaches_cut = mean(x[pos] - 1.96 * sem <= 10)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             sem       half_width        positives band_reaches_cut \n           1.745            3.420          448.000            0.420 \n```\n\n\n:::\n:::\n\n\nCTT's band is ±3.42 points. Of the 448 who screened positive, 42.0% have a band reaching down to 10: the data are consistent with a true score under the cut.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The graded response model: one slope per item and a boundary between each pair of\n# adjacent categories. mirt writes each boundary as a*theta + d_k.\nset.seed(61)\ngrm <- mirt(w1, 1, itemtype = \"graded\", verbose = FALSE)\nround(coef(grm, simplify = TRUE)$items, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        a1    d1    d2    d3\nDep_1 3.24 -0.62 -3.21 -5.61\nDep_2 3.61 -0.28 -3.65 -5.86\nDep_3 2.21  0.05 -2.06 -3.67\nDep_4 2.71  0.08 -2.56 -4.23\nDep_5 2.60 -1.27 -3.09 -4.87\nDep_6 3.39 -1.88 -3.84 -5.95\nDep_7 3.45 -1.48 -3.94 -6.10\nDep_8 3.12 -3.32 -4.71 -6.81\nDep_9 3.36 -3.43 -5.04 -6.94\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The cut on the theta scale: where the expected PHQ-9 score (the test characteristic\n# curve) reaches 10.\ntcc <- function(t) expected.test(grm, matrix(t))\ntheta_cut <- uniroot(function(t) tcc(t) - 10, c(-4, 4))$root\ncsem <- function(t) 1 / sqrt(testinfo(grm, matrix(t)))\nround(c(theta_cut = theta_cut, csem_at_cut = csem(theta_cut),\n        csem_at_0 = csem(0), csem_at_minus_1 = csem(-1), csem_at_minus_2 = csem(-2)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      theta_cut     csem_at_cut       csem_at_0 csem_at_minus_1 csem_at_minus_2 \n           0.86            0.21            0.27            0.77            2.80 \n```\n\n\n:::\n:::\n\n\nThe slopes run from 2.21 (`Dep_3`) to 3.61 (`Dep_2`), all above the 1 to 2.2 where most financial-literacy slopes fell in [Information](information.qmd). The cut sits at $\\theta = 0.86$, where the conditional SEM is 0.21; it is 0.27 at $\\theta = 0$, 0.77 at $-1$ and 2.80 at $-2$. It is precise where the decision is made and says little about how far below it the 28.5% who scored 0 sit.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same precision on the raw-score scale: the SD of the PHQ-9 sum for respondents\n# at a given theta, from the model's category probabilities.\nraw_csem <- function(t) {\n  v <- sapply(1:9, function(i) {\n    p <- probtrace(extract.item(grm, i), matrix(t))\n    sum((0:3)^2 * p) - sum((0:3) * p)^2\n  })\n  sqrt(sum(v))\n}\nat <- sapply(c(1, 3, 5, 10, 15, 20, 25), function(s) uniroot(function(t) tcc(t) - s, c(-6, 6))$root)\n# The two scales are linked by the slope of the test characteristic curve: an error of\n# SE points in the score is an error of about SE / slope on theta. Where the curve is\n# flat (near the floor and the ceiling), a small band in points is a wide band in theta.\nslope <- sapply(at, function(t) (tcc(t + 0.001) - tcc(t - 0.001)) / 0.002)\nround(rbind(raw = c(1, 3, 5, 10, 15, 20, 25), theta = at,\n            model_sem_raw = sapply(at, raw_csem), ctt_sem_raw = sem,\n            tcc_slope = slope, sem_raw_over_slope = sapply(at, raw_csem) / slope,\n            csem_theta = sapply(at, csem)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    [,1] [,2] [,3]  [,4]  [,5]  [,6]  [,7]\nraw                 1.00 3.00 5.00 10.00 15.00 20.00 25.00\ntheta              -0.48 0.03 0.33  0.86  1.28  1.71  2.33\nmodel_sem_raw       1.03 1.60 1.90  2.36  2.51  2.31  1.49\nctt_sem_raw         1.74 1.74 1.74  1.74  1.74  1.74  1.74\ntcc_slope           2.36 5.70 7.67 11.04 12.33 10.90  4.84\nsem_raw_over_slope  0.44 0.28 0.25  0.21  0.20  0.21  0.31\ncsem_theta          0.41 0.26 0.23  0.21  0.20  0.20  0.29\n```\n\n\n:::\n:::\n\n\nOn the raw-score scale the model's SEM is 2.36 at 10, 1.03 at 1 and 1.49 at 25, against CTT's 1.74 everywhere. Divided by the expected-score curve's slope (2.36 points per logit at a score of 1, 11.04 at 10), they become 0.44 and 0.21 on $\\theta$, close to the conditional SEMs of 0.41 and 0.21: narrow in points at the extremes, wide in $\\theta$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Bands on the theta scale: each respondent's estimate (EAP, mirt's default) plus or\n# minus 1.96 conditional SEMs. How many positives have a band that reaches the cut?\nth <- fscores(grm, verbose = FALSE)[, 1]\nround(c(band_reaches_cut = mean(th[pos] - 1.96 * csem(th[pos]) <= theta_cut)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nband_reaches_cut \n           0.562 \n```\n\n\n:::\n:::\n\n\nWith conditional-SEM bands on $\\theta$, 56.2% of the positives reach the cut, against 42.0% with CTT's. Which should a report use? CTT's band assumes the same error at every score; the model's assumes its item curves and one $\\theta$ describe the data. At the cut the model's SEM is about a third larger (2.36 points against 1.74). When a score will be read against a cut, I report the band from the conditional SEM at the cut, and give the one SEM only as a summary of the scale as a whole.\n\n\n::: {.cell}\n\n:::\n\n\n### Change between waves\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nw2 <- long2wide(uk[uk$wave == 2, ])\nboth <- intersect(rownames(w1), rownames(w2))\nx1 <- rowSums(w1[both, ]); x2 <- rowSums(w2[both, ])\nr12 <- cor(x1, x2); a1 <- alpha(w1[both, ]); a2 <- alpha(w2[both, ])\n# Reliability of the difference x2 - x1 (true-score variance of the difference over\n# its observed variance)\nrel_diff <- (a1 * var(x1) + a2 * var(x2) - 2 * cov(x1, x2)) / var(x2 - x1)\nrci <- 1.96 * sqrt(2) * sem              # reliable change: |x2 - x1| at least this\ndx <- x2 - x1\ncrossed <- (x1 >= 10) != (x2 >= 10)\nround(c(n = length(both), r = r12, alpha_1 = a1, alpha_2 = a2, rel_diff = rel_diff,\n        rci_threshold = rci, reliable_change = mean(abs(dx) >= rci),\n        crossed_cut = mean(crossed), crossed_by_less = mean(crossed & abs(dx) < rci)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              n               r         alpha_1         alpha_2        rel_diff \n       1406.000           0.703           0.917           0.919           0.723 \n  rci_threshold reliable_change     crossed_cut crossed_by_less \n          4.836           0.196           0.139           0.038 \n```\n\n\n:::\n:::\n\n\nFor the 1,406 seen twice, the waves correlate 0.70 and the change score has reliability 0.72. 19.6% changed by 4.8 points or more, the reliable change threshold. 13.9% crossed the cut, and 3.8% crossed it by less than 4.8 points: about a quarter of the crossings are within what error alone could produce. All this assumes the PHQ-9 measures the same thing at both waves, which [Invariance and experience](invariance-experience.qmd) asks how to check.\n\n### Estimates and plausible values\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Estimates versus plausible values. EAPs are pulled toward the mean; plausible values\n# are draws from each respondent's posterior, so across respondents they keep the\n# spread of the population.\nset.seed(61)\npv <- fscores(grm, plausible.draws = 20, verbose = FALSE)\nround(c(sd_eap = sd(th), sd_pv = mean(sapply(pv, function(p) sd(p[, 1]))),\n        above_cut_eap = mean(th >= theta_cut),\n        above_cut_pv = mean(sapply(pv, function(p) mean(p[, 1] >= theta_cut))),\n        observed_10_plus = mean(x >= 10)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          sd_eap            sd_pv    above_cut_eap     above_cut_pv \n           0.921            1.001            0.199            0.205 \nobserved_10_plus \n           0.221 \n```\n\n\n:::\n:::\n\n\nThe EAPs have an SD of 0.921 and put 19.9% above the cut; plausible values have an SD of 1.001 and put 20.5% above. The gap is small because the PHQ-9 is precise near the cut.\n\n## Problems\n\n1. **Derivation.** Show that for two occasions with equal variances, reliabilities $\\rho_1$ and $\\rho_2$ and correlation $r_{12}$, the difference score has reliability $\\big((\\rho_1 + \\rho_2)/2 - r_{12}\\big)/(1 - r_{12})$ ([Lord, 1956](https://doi.org/10.1177/001316445601600401)). When is it zero? Can it be negative, and what would that say about the classical assumptions?\n2. **Which SEM for change?** Recompute the reliable change threshold with the wave-2 alpha, and with the test–retest correlation (0.70) in place of alpha. How many respondents change reliably under each? Which would you use, and why?\n3. **Old norms.** A clinic in 2026 reads patients' PHQ-9 scores against the UK spring-2020 percentiles. What would you tell them? Use Standard [5.9](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf#page=114) and what the German comparison showed about reference groups.\n4. **A report for one respondent.** Design a one-page PHQ-9 report for a respondent who scored 12: score, band, percentile rank with reference group and date, and the cut. What would you leave out, and why?\n5. **Another reference group.** Add [kohlmann_2016_phq9](https://itemresponsewarehouse.org/tables/kohlmann_2016_phq9/), PHQ-9 responses from patients with coronary heart disease ([Kohlmann et al., 2016](https://doi.org/10.1371/journal.pone.0156167)). Where does a 10 fall there? Which reference group should a cardiologist use for a new patient, and for which question?\n6. **Challenge (open): prevalence from a screener.** The cut of 10 was chosen against diagnostic interviews. Should a population survey report the share scoring 10 or more as the prevalence of depression? Think about the positive predictive value at a low base rate. I don't know of an agreed answer.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22What%20does%20a%20score%20mean%3F%20Norms%2C%20error%20bands%2C%20and%20cut%20scores%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20what%20makes%20a%20test%20score%20interpretable%3A%20norm-referenced%20and%20criterion-referenced%20meaning%2C%20percentile%20ranks%2C%20z%20scores%20and%20linear%20and%20normalized%20T%20scores%2C%20reference%20groups%2C%20error%20bands%20from%20the%20classical%20SEM%20and%20from%20the%20IRT%20conditional%20SEM%2C%20the%20reliability%20of%20difference%20scores%20and%20the%20reliable%20change%20index%2C%20cut%20scores%20%28empirical%2C%20and%20judgmental%20with%20the%20Angoff%20method%29%2C%20classification%20consistency%2C%20score%20reports%20and%20plausible%20values%2C%20with%20the%20PHQ-9%20in%20a%20UK%202020%20panel%20and%20a%20German%20general-population%20sample%20as%20examples%2C%20analysed%20in%20R%20with%20mirt.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- AERA, APA, & NCME. (2014). *Standards for educational and psychological testing*. American Educational Research Association. Open access: [full text (PDF)](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf); [the open-access page](https://www.testingstandards.net/open-access-files.html). Chapter 5 covers scores, scales, norms and cut scores; chapter 2, standard errors near cuts and for differences.\n- Kolen, M. J., & Brennan, R. L. (2014). Score scales. In *Test equating, scaling, and linking* (3rd ed., pp. 371–485). Springer. <https://doi.org/10.1007/978-1-4939-0317-7_9>. Percentile ranks, normalized scores and the construction of score scales.\n- Angoff, W. H. (1971). Scales, norms, and equivalent scores. In R. L. Thorndike (Ed.), *Educational measurement* (2nd ed., pp. 508–600). American Council on Education. <https://openlibrary.org/works/OL3700878W>. The classic chapter on norms, and the source of the Angoff method.\n- Cizek, G. J., & Bunch, M. B. (2007). *Standard setting: A guide to establishing and evaluating performance standards on tests*. SAGE. <https://doi.org/10.4135/9781412985918>. One chapter per standard-setting method, including Angoff (ch. 6) and bookmark (ch. 10).\n- Rogosa, D. R., & Willett, J. B. (1983). Demonstrating the reliability of the difference score in the measurement of change. *Journal of Educational Measurement*, 20(4), 335–343. <https://doi.org/10.1111/j.1745-3984.1983.tb00211.x>. When a difference score is reliable.\n- Jacobson, N. S., & Truax, P. (1991). Clinical significance: A statistical approach to defining meaningful change in psychotherapy research. *Journal of Consulting and Clinical Psychology*, 59(1), 12–19. <https://doi.org/10.1037/0022-006x.59.1.12>. The reliable change index.\n- Livingston, S. A., & Lewis, C. (1995). Estimating the consistency and accuracy of classifications based on test scores. *Journal of Educational Measurement*, 32(2), 179–197. <https://doi.org/10.1111/j.1745-3984.1995.tb00462.x>. Classification consistency without an item response model.\n- Lee, W.-C. (2010). Classification consistency and accuracy for complex assessments using item response theory. *Journal of Educational Measurement*, 47(1), 1–17. <https://doi.org/10.1111/j.1745-3984.2009.00096.x>. The IRT route of the Go deeper callout, for mixed item formats.\n- Levis, B., Benedetti, A., & Thombs, B. D. (2019). Accuracy of Patient Health Questionnaire-9 (PHQ-9) for screening to detect major depression: Individual participant data meta-analysis. *BMJ*, 365, l1476. <https://doi.org/10.1136/bmj.l1476>. How the PHQ-9's cuts perform, with data from 58 studies.\n- Zenisky, A. L., & Hambleton, R. K. (2012). Developing test score reports that work: The process and best practices for effective communication. *Educational Measurement: Issues and Practice*, 31(2), 21–26. <https://doi.org/10.1111/j.1745-3992.2012.00231.x>. How to design a report that readers read correctly.\n- Wu, M. (2005). The role of plausible values in large-scale surveys. *Studies in Educational Evaluation*, 31(2–3), 114–128. <https://doi.org/10.1016/j.stueduc.2005.05.005>. What plausible values are for, with worked comparisons.\n- Kroenke, K., Spitzer, R. L., & Williams, J. B. W. (2001). The PHQ-9: Validity of a brief depression severity measure. *Journal of General Internal Medicine*, 16(9), 606–613. <https://doi.org/10.1046/j.1525-1497.2001.016009606.x>. The PHQ-9's first validation, with the cut of 10 and the severity bands.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`c19prc_uk_mcbride_2021_phq9`](https://itemresponsewarehouse.org/tables/c19prc_uk_mcbride_2021_phq9/): Bentall, Richard and Shevlin, Mark and McBride, Orla and Murphy, Jamie and Hartman, Todd K and Levita, Liat and Gibson-Miller, Jilly and Mason, Liam and Bennett, Kate (2022). The COVID-19 Psychological Research Consortium Study, 2020-2021. [Data Collection]. Colchester, Essex: UK Data Service. 10.5255/UKDA-SN-855552. <https://osf.io/v2zur/>. Licence: CC BY 4.0.\n- [`coroiu_2018_phq9`](https://itemresponsewarehouse.org/tables/coroiu_2018_phq9/): Coroiu A, Kwakkenbos L, Moran C, Thombs B, Albani C, Bourkas S, et al. (2018). Structural validation of the Self-Compassion Scale with a German general population sample. PLOS ONE 13(2): e0190771. <https://doi.org/10.1371/journal.pone.0190771>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** new material, not in EDUC 252: norms, error bands, change scores, cut scores and score reports, following chapters 2 and 5 of the *Standards* ([AERA, APA & NCME, 2014](https://www.testingstandards.net/uploads/7/6/6/4/76643089/standards_2014edition.pdf), open access).\n- **Timing:** the core ideas and widgets take about 60 minutes; the PHQ-9 analysis works as a 30-minute lab. The graded model fits in a few seconds in local R.\n- **Changed from the outline:** the cut on $\\theta$ is where the test characteristic curve reaches 10. The Simulate section compares the model's prediction with CTT's normal approximation rather than with Livingston and Lewis's beta-binomial model, which the Go deeper callout describes. The German cardiac sample appears only in problem 5.\n- **Held back:** the accuracy of a cut against a criterion ([Validity evidence](validity-evidence.qmd)); norms on a new form, which need the forms linked first ([Equating and linking](equating.qmd)); whether a unit means the same across the scale ([Scale properties](scale-properties.qmd)); precision at a cut in adaptive testing ([Item banks and adaptive testing](item-banks-cat.qmd)); estimating $\\theta$ for individuals ([Estimating abilities](ability-estimation.qmd)). The fairness of cut scores across groups isn't treated anywhere in the course.\n- **Item text:** the PHQ-9 is in the public domain: its instruction manual says no permission is required to reproduce, translate, display or distribute it ([PHQ instruction manual, n.d., p. 8](https://www.phqscreeners.com/images/sites/g/files/g10016261/f/201412/instructions.pdf); the [PHQ Screeners site](https://www.phqscreeners.com/select-screener) says the same). The lesson still quotes only the first item.\n- **Sensitivity:** item 9 asks about thoughts of self-harm. The lesson doesn't analyse it on its own; if students do, a reminder of where support is available is appropriate.\n- **Solutions:** held back in `solutions/score-meaning.qmd` (not published). Problem 6 is open.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script type=\"ojs-define\">\n{\"contents\":[{\"name\":\"sm_norms\",\"value\":{\"group\":[\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, all adults\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 18–34\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"UK 2020, ages 55+\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\",\"Germany 2012\"],\"score\":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27],\"n\":[577,182,183,147,110,99,85,66,52,76,44,50,46,48,39,31,29,32,43,19,6,12,9,7,12,4,4,13,101,50,42,36,29,33,30,26,23,25,20,26,23,25,21,15,14,19,19,9,4,8,3,5,8,2,3,7,244,68,72,53,35,30,28,15,10,14,8,8,5,11,6,4,5,1,7,2,1,2,3,1,2,0,0,1,963,340,325,228,160,88,80,53,35,34,14,18,13,14,10,8,8,4,4,1,1,1,0,1,0,0,1,0]}}]}\n</script>\n<script type=\"ojs-define\">\n{\"contents\":[{\"name\":\"sm_items\",\"value\":{\"a\":[3.2447,3.6102,2.2119,2.7091,2.5998,3.3893,3.452,3.1248,3.3615],\"d1\":[-0.6161,-0.2792,0.0543,0.0778,-1.2687,-1.8755,-1.4778,-3.3242,-3.4259],\"d2\":[-3.2104,-3.6509,-2.0603,-2.5559,-3.0875,-3.8402,-3.9429,-4.709,-5.0389],\"d3\":[-5.6139,-5.8566,-3.6713,-4.2308,-4.8744,-5.9546,-6.0972,-6.814,-6.9351],\"_row\":[\"Dep_1\",\"Dep_2\",\"Dep_3\",\"Dep_4\",\"Dep_5\",\"Dep_6\",\"Dep_7\",\"Dep_8\",\"Dep_9\"]}},{\"name\":\"sm_sem\",\"value\":1.7447}]}\n</script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}