{
  "hash": "5c18eaa4c009e12e76d8f83f83ea1589",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"From construct map to items: building an instrument\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Classical test theory  \n**Tranche:** core (a first course)  \n**Before this:** [Constructs and construct maps](constructs.qmd) · [Classical test theory and reliability](ctt-reliability.qmd)  \n**Builds toward:** [Many sources of error: generalizability theory](g-theory.qmd) · [Factor analysis I: exploring dimensionality](fa-exploratory.qmd) · [Gathering validity evidence](validity-evidence.qmd)  \n**Picks up threads:** Keying has to be checked; the data can't always tell (from [Classical test theory and reliability](ctt-reliability.qmd)); Constructs are measured through probes (from [What is measurement?](measurement.qmd))  \n**IRW tables:** [`song_2023_rses`](https://itemresponsewarehouse.org/tables/song_2023_rses/)  \n**From EDUC 252:** slides c2  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n```{ojs}\n//| echo: false\nimport {palette} from \"./widgets/irt.js\"\nimport {simWording, simAcquiescence, spearmanBrown} from \"./widgets/instrument-building.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nMost of the work of building an instrument happens before anyone answers it. [Constructs and construct maps](constructs.qmd) ended with a map or a blueprint; [Classical test theory and reliability](ctt-reliability.qmd) gave us tools for judging items once there are responses. This lesson sits between the two. It walks through the steps from a map to a pilot, gives the item-writing rules that carry the most weight, and spends most of its time on one design choice that looks harmless and isn't: writing some items in the reverse direction. The worked example is the Rosenberg Self-Esteem Scale, answered by 1,238 medical students in China, where the reversed items form a second cluster and one of them appears to have been read the other way.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- lay out the steps from a construct map or blueprint to a piloted instrument, and say what each step can catch that the others can't;\n- choose between selected-response and constructed-response formats for a construct, and say what each costs;\n- spot and repair the item-writing faults that matter most (two ideas in one item, double negatives, unbalanced options, implausible distractors);\n- explain why scales include reverse-worded items, and show how they can bring in a second, wording-related dimension that alpha does not reveal;\n- read a pilot's item analysis alongside the items' text and decide whether to keep, rewrite or drop each item.\n\n## Core ideas\n\n### From a map to a pilot\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is measurement?](measurement.qmd): a **probe** is anything we present to a respondent to draw out a response that bears on the construct (a question, a task, a statement to agree or disagree with), and an item is a probe whose response is scored. Probes are standardized: the same items, given and scored the same way for everyone.\n:::\n\nThat lesson took probes as given. Where do they come from? [Wilson (2005)](https://doi.org/10.4324/9781410611697) describes instrument building as a cycle, and the *Standards* treat much the same sequence as the core of test development ([AERA, APA & NCME, 2014, ch. 4](https://www.testingstandards.net/open-access-files.html)). In outline:\n\n1. **Construct map or blueprint.** What the instrument is for, and what a score should mean ([Constructs and construct maps](constructs.qmd)).\n2. **Items.** Written to the map's levels, or to the blueprint's cells.\n3. **Review.** Content experts check that each item belongs where it was written; others look for wording that some groups would find harder for reasons unrelated to the construct.\n4. **Cognitive interviews.** A handful of respondents answer the items aloud, saying what they took each to ask and how they arrived at an answer ([Willis, 2005](https://doi.org/10.4135/9781412983655)).\n5. **Pilot.** A larger sample answers the draft instrument, and we run an item analysis.\n6. **Revise**, and go round again.\n\nOnly steps 5 and 6 produce data, and every later lesson works on their output. Why bother with the rest? [Tourangeau, Rips and Rasinski (2000)](https://doi.org/10.1017/CBO9780511819322) break answering a question into understanding the item, recalling what is relevant, forming a judgment, and fitting it to the response options. A pilot sees only the result. If everyone misreads an item in the same way, it can correlate well with the rest and still ask something we didn't mean; a cognitive interview is where that shows up. And the blueprint fixes something no pilot can change: how many items each part of the domain gets.\n\n#### Try it: a blueprint and its cells\n\nA fractions test has three content areas and two kinds of task (recall, and applying to a new problem). Set its length and weights. Given the reliability of one item (last slider), the Spearman–Brown formula from [Classical test theory and reliability](ctt-reliability.qmd) gives the reliability of the whole test and of a score on each cell.\n\n```{ojs}\n//| echo: false\nviewof bp_len = Inputs.range([10, 60], {value: 30, step: 1, label: \"Items on the test\"})\nviewof bp_w1 = Inputs.range([0, 100], {value: 40, step: 5, label: \"Weight: comparing fractions\"})\nviewof bp_w2 = Inputs.range([0, 100], {value: 40, step: 5, label: \"Weight: adding fractions\"})\nviewof bp_w3 = Inputs.range([0, 100], {value: 20, step: 5, label: \"Weight: fractions on a number line\"})\nviewof bp_apply = Inputs.range([0, 100], {value: 50, step: 10, label: \"Share of items that ask to apply (%)\"})\nviewof bp_rel1 = Inputs.range([0.05, 0.4], {value: 0.15, step: 0.01, label: \"Reliability of one item\"})\n```\n\n```{ojs}\n//| echo: false\nbp_cells = {\n  const areas = [\"Comparing\", \"Adding\", \"Number line\"], w = [bp_w1, bp_w2, bp_w3];\n  const tot = w.reduce((u, v) => u + v, 0) || 1;\n  const want = [];\n  areas.forEach((a, i) => [\"Recall\", \"Apply\"].forEach(p => {\n    const share = (w[i] / tot) * (p === \"Apply\" ? bp_apply / 100 : 1 - bp_apply / 100);\n    want.push({area: a, task: p, exact: share * bp_len});\n  }));\n  // Round to whole items, keeping the total (the largest remainders get the spare items).\n  want.forEach(d => d.n = Math.floor(d.exact));\n  const spare = bp_len - want.reduce((u, d) => u + d.n, 0);\n  [...want].sort((a, b) => (b.exact - b.n) - (a.exact - a.n)).slice(0, spare).forEach(d => d.n += 1);\n  return want.map(d => ({...d, rel: d.n > 0 ? spearmanBrown(bp_rel1, d.n) : null}));\n}\nPlot.plot({\n  width: 520, height: 200, marginLeft: 90,\n  x: {domain: [\"Recall\", \"Apply\"], label: null, axis: \"top\"}, y: {domain: [\"Comparing\", \"Adding\", \"Number line\"], label: null},\n  color: {domain: [0, 1], range: [palette.white, palette.main]},\n  marks: [\n    Plot.cell(bp_cells, {x: \"task\", y: \"area\", fill: d => d.rel ?? 0, stroke: palette.rule, inset: 1}),\n    Plot.text(bp_cells, {x: \"task\", y: \"area\", text: d => d.n > 0 ? `${d.n} items, reliability ${d.rel.toFixed(2)}` : \"no items\", fill: d => (d.rel ?? 0) > 0.6 ? palette.white : palette.ink, fontSize: 11})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nbp_filled = bp_cells.filter(d => d.n > 0)\nbp_min = bp_filled.reduce((a, b) => (b.rel < a.rel ? b : a))\nmd`Whole test: ${bp_len} items, reliability **${spearmanBrown(bp_rel1, bp_len).toFixed(2)}**. The least reliable cell score is ${bp_min.area.toLowerCase()} × ${bp_min.task.toLowerCase()}, with ${bp_min.n} item${bp_min.n === 1 ? \"\" : \"s\"} and reliability **${bp_min.rel.toFixed(2)}**.${bp_cells.some(d => d.n === 0) ? \" Some cells have no items at all, so the test can say nothing about them.\" : \"\"}`\n```\n\nAt the starting values the whole test reaches 0.84 while the three-item cells sit at 0.35. A blueprint can guarantee coverage without supporting a score for each cell; a subscore needs enough items in its cell, and that is settled before any item is written.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A team has drafted 40 items and plans to pilot them on 2,000 respondents next week, skipping cognitive interviews because 'the item analysis will flag any bad items'. What could the pilot miss?\",\n  options: [\n    {text: \"An item that every respondent reads in the same unintended way\", correct: true, why: \"If the misreading is shared, the item can still correlate with the rest, so its item-rest correlation looks fine. Only asking respondents what they understood reveals it.\"},\n    {text: \"An item that nobody endorses\", correct: false, why: \"The pilot catches that directly: the item's mean sits at the floor.\"},\n    {text: \"An item keyed in the wrong direction\", correct: false, why: \"A negative or near-zero item-rest correlation usually flags that, as with the Mach IV. The pilot's statistics do this well; the harder case is a misreading that leaves the correlations intact.\"}\n  ]\n})\n```\n\n### Formats: selected and constructed responses\n\nWhat form should the response take? In a **selected-response** item the respondent picks from a list: multiple-choice options, or the steps of a Likert scale from \"strongly disagree\" to \"strongly agree\". In a **constructed-response** item the respondent produces the answer: a typed number (the number-series items in [Constructs and construct maps](constructs.qmd)), a short answer, an essay.\n\nEvery model in this course needs each response to fall in exactly one of a fixed set of categories, usually ordered. A selected response arrives that way; a constructed response has to be put there by **scoring**, with a key or with a rubric and a rater. Scoring is where constructed responses get expensive, and the rater is a new source of error; [Many sources of error](g-theory.qmd) treats raters as a facet of measurement. Selected response is a reasonable choice when recognition or judgment reaches the construct and many items are needed cheaply. Constructed response is a reasonable choice when producing the answer is the construct: writing, explaining a proof, carrying out a procedure.\n\n### Writing items\n\nGuidance on writing items fills whole books, and it mostly agrees. [Haladyna, Downing and Rodriguez (2002)](https://doi.org/10.1207/S15324818AME1503_5) distilled 31 guidelines for multiple-choice items from 27 measurement textbooks and 27 research studies and reviews; [Haladyna and Rodriguez (2013)](https://doi.org/10.4324/9780203850381) cover item development at book length; and [Clark and Watson (2019)](https://doi.org/10.1037/pas0000626) do the same for rating-scale instruments. A few rules do most of the work:\n\n- **One idea per item.** An item that asks about two things (a *double-barrelled* item) leaves a respondent who agrees with one and not the other nowhere to go ([Clark & Watson, 2019](https://doi.org/10.1037/pas0000626)).\n- **No negatives stacked on negatives.** A \"not\" in the stem makes the respondent do extra work; two of them invite errors that have nothing to do with the construct. [Haladyna et al. (2002)](https://doi.org/10.1207/S15324818AME1503_5) advise wording the stem positively and, where a negative is needed, making it stand out.\n- **Options that fit the question.** Response labels should cover the range the construct needs, in an order and spacing respondents can read. If most labels sit on one side of neutral, the middle option isn't neutral.\n- **Plausible distractors.** A multiple-choice distractor that nobody would choose adds only reading time. Distractors built from specific errors earn their place ([Haladyna et al., 2002](https://doi.org/10.1207/S15324818AME1503_5)), and [Nominal response and multiple-choice models](nominal.qmd) shows that which distractor a respondent picks carries information of its own.\n\n#### Try it: fix this item\n\nEach item below breaks one rule. Decide what is wrong before you reveal the diagnosis and a rewrite. (The items are invented for this lesson.)\n\n```{ojs}\n//| echo: false\nfx_items = ({\n  \"I enjoy reading novels and writing poetry.\": {\n    fault: \"Two ideas in one item. A respondent who reads novels but never writes poetry has no accurate answer.\",\n    fix: \"Two items: \\\"I enjoy reading novels.\\\" and \\\"I enjoy writing poetry.\\\"\"},\n  \"It is not true that I never feel nervous before a test.\": {\n    fault: \"A double negative. To agree, the respondent has to unpack \\\"not true that ... never\\\", which is a reading task, not a question about nerves.\",\n    fix: \"\\\"I feel nervous before a test.\\\"\"},\n  \"How would you rate your teacher's feedback? (Poor / Good / Very good / Excellent / Outstanding)\": {\n    fault: \"Unbalanced options. Four of the five labels are positive, so the middle option, \\\"Very good\\\", is not neutral. That can be deliberate when nearly everyone rates highly and the aim is to separate the top, but then it should be a stated choice.\",\n    fix: \"(Very poor / Poor / Fair / Good / Very good), or keep the positive skew on purpose and say so in the scoring guide.\"},\n  \"What is 1/2 + 1/3?  (a) 5/6  (b) 2/5  (c) 1/6  (d) A triangle\": {\n    fault: \"An implausible distractor. Nobody who reads the question chooses (d), so the item is in effect a three-option item. Options (b) (adding tops and bottoms) and (c) (multiplying) each come from a specific error.\",\n    fix: \"Replace (d) with another answer produced by an error, such as 2/6 (adding the numerators over the product of the denominators).\"}\n})\nviewof fx_which = Inputs.radio(Object.keys(fx_items), {value: Object.keys(fx_items)[0], label: \"Item\"})\nviewof fx_show = Inputs.toggle({label: \"Reveal\", value: false})\n```\n\n```{ojs}\n//| echo: false\nmd`${fx_show ? `**What's wrong:** ${fx_items[fx_which].fault}\n\n**A rewrite:** ${fx_items[fx_which].fix}` : \"*Decide what is wrong, then reveal.*\"}`\n```\n\nEach fault puts something between the respondent and the construct, and none need show in an item analysis: a double-barrelled item can correlate well with the rest, because respondents who like one of its two things tend to like the other.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A job-satisfaction scale includes \\\"My manager is supportive and I am paid fairly.\\\" In the pilot its item-rest correlation is 0.55, in line with the others. Keep it as is?\",\n  options: [\n    {text: \"No: split it into two items, even though the statistics look fine\", correct: true, why: \"The item is double-barrelled. A respondent with a supportive manager and low pay can't answer it cleanly, and the score can't say which half they were answering. Good statistics don't repair the item's meaning.\"},\n    {text: \"Yes: an item-rest correlation of 0.55 shows the item works\", correct: false, why: \"It shows the item goes along with the total. Support and pay are both parts of job satisfaction, so the item correlates with the rest whichever half a respondent answers.\"},\n    {text: \"Drop it: double-barrelled items always have low item-rest correlations\", correct: false, why: \"They needn't. This one doesn't, which is why the fault has to be caught by reading the item.\"}\n  ]\n})\n```\n\n### Reverse-worded items\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd): half the Mach IV's items are worded so that agreeing is the *less* Machiavellian answer, and they must be reverse-keyed before sums, alpha or item-rest correlations mean anything. Keying had to be checked: automated keying found all ten published reversals and added m19, the one item the data couldn't settle.\n:::\n\nHere we write reversed items on purpose. Why? The usual answer is **acquiescence**, a respondent's tendency to agree with statements whatever they say ([Paulhus, 1991](https://doi.org/10.1016/B978-0-12-590241-0.50006-X); [Baumgartner & Steenkamp, 2001](https://doi.org/10.1509/jmkr.38.2.143.18840)). If every item is worded so that agreeing means more of the construct, a respondent who agrees easily gets a higher score for reasons unrelated to the construct. If half the items are reversed, the extra agreement raises the forward items and, once keyed, lowers the reversed ones, and the two cancel in the sum.\n\n#### Try it: agreeing with everything\n\nSix hundred simulated respondents answer ten four-point items, each loading 0.6 on the trait. Each respondent also has a tendency to agree, added to their raw agreement with every item; the slider sets how much it varies between respondents. The two designs are an all-forward scale and a balanced one with five items reversed (and then keyed).\n\n```{ojs}\n//| echo: false\nviewof aq_sd = Inputs.range([0, 1.5], {value: 0.5, step: 0.1, label: \"Spread of acquiescence (SD)\"})\n```\n\n```{ojs}\n//| echo: false\naq = simAcquiescence({seed: 7, n: 600, acq: aq_sd})\naq_rows = [\n  {design: \"All forward\", what: \"Alpha\", v: aq.forward.alpha}, {design: \"All forward\", what: \"Trait's share of the sum score\", v: aq.forward.r2},\n  {design: \"Balanced\", what: \"Alpha\", v: aq.balanced.alpha}, {design: \"Balanced\", what: \"Trait's share of the sum score\", v: aq.balanced.r2}\n]\nPlot.plot({\n  width: 620, height: 220, marginLeft: 100, marginRight: 40,\n  x: {domain: [0, 1], label: null, grid: true}, y: {label: null, axis: null}, fy: {label: null},\n  color: {legend: true, domain: [\"Alpha\", \"Trait's share of the sum score\"], range: [palette.contrast, palette.main]},\n  marks: [Plot.barX(aq_rows, {x: \"v\", y: \"what\", fy: \"design\", fill: \"what\"}),\n          Plot.text(aq_rows, {x: \"v\", y: \"what\", fy: \"design\", text: d => d.v.toFixed(2), dx: 16})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`All forward: alpha **${aq.forward.alpha.toFixed(2)}**, trait's share of the sum score's variance **${aq.forward.r2.toFixed(2)}**. Balanced: alpha **${aq.balanced.alpha.toFixed(2)}**, trait's share **${aq.balanced.r2.toFixed(2)}**.`\n```\n\nWith no acquiescence the designs are alike (alpha 0.80 and 0.82). As the slider moves right, the all-forward scale's alpha *rises*, because acquiescence is shared by every item and alpha counts anything shared as signal, while the trait's share of the sum score falls, to 0.44 at the starting value. The balanced scale keeps the trait's share near 0.8 and its alpha falls instead. The simulation assumes respondents read a reversed item as exactly the opposite of a forward one.\n\nDo they? Not always. [Marsh (1996)](https://doi.org/10.1037/0022-3514.70.4.810), analysing the Rosenberg Self-Esteem Scale in a large US longitudinal study of school students, found that the negatively worded items shared a method effect beyond the general factor, and later studies modelled such effects for the same scale and others ([Tomás & Oliver, 1999](https://doi.org/10.1080/10705519909540120); [DiStefano & Motl, 2006](https://doi.org/10.1207/s15328007sem1303_6)). [Weijters, Baumgartner and Schillewaert (2013)](https://doi.org/10.1037/a0032121) model three mechanisms that can produce one: acquiescence, careless responding, and confirmation bias (reading a reversed item in the light of the items before it). [Swain, Weathers and Niedrich (2008)](https://doi.org/10.1509/jmkr.45.1.116) found about a fifth of responses to reversed items landing on the same side of the scale as the forward items, and trace it to the extra work of checking a reversed statement against one's belief. Whatever the mechanism, reversed items correlate more with each other than their content predicts, and wording direction becomes a second dimension.\n\n#### Try it: a wording factor\n\nThe same ten items, keyed. Each loads 0.6 on the trait; the reversed items (R1–R5) also load on a wording factor unrelated to the trait, and a second slider gives the forward items (F1–F5) a wording factor of their own. The heat map is the correlation matrix for 600 simulated respondents.\n\n```{ojs}\n//| echo: false\nviewof wf_g = Inputs.range([0, 0.7], {value: 0.6, step: 0.05, label: \"Reversed items' wording loading\"})\nviewof wf_gf = Inputs.range([0, 0.7], {value: 0, step: 0.05, label: \"Forward items' wording loading\"})\n```\n\n```{ojs}\n//| echo: false\nwf = simWording({seed: 56, n: 600, lambda: 0.6, gamma: wf_g, gammaF: wf_gf})\nwf_lab = [\"F1\", \"F2\", \"F3\", \"F4\", \"F5\", \"R1\", \"R2\", \"R3\", \"R4\", \"R5\"]\nwf_cells = wf.R.flatMap((row, i) => row.map((v, j) => ({i: wf_lab[i], j: wf_lab[j], v: i === j ? null : v})))\nPlot.plot({\n  width: 420, height: 420, marginLeft: 40, x: {domain: wf_lab, label: null, axis: \"top\"}, y: {domain: wf_lab, label: null},\n  color: {domain: [0, 1], range: [palette.white, palette.main], legend: true, label: \"Correlation\"},\n  marks: [Plot.cell(wf_cells, {x: \"j\", y: \"i\", fill: d => d.v ?? 1, stroke: palette.rule}),\n          Plot.text(wf_cells.filter(d => d.v !== null), {x: \"j\", y: \"i\", text: d => d.v.toFixed(2), fontSize: 9, fill: d => d.v > 0.55 ? palette.white : palette.ink})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Average correlation among forward items **${wf.withinF.toFixed(2)}**, among reversed items **${wf.withinR.toFixed(2)}**, across the two **${wf.across.toFixed(2)}**. Alpha **${wf.alpha.toFixed(2)}**. The trait's share of the sum score's variance **${wf.r2.toFixed(2)}**. Largest eigenvalues of the correlation matrix: ${wf.eig.slice(0, 3).map(v => v.toFixed(2)).join(\", \")}.`\n```\n\nAt a reversed loading of 0 the matrix is one even block, with alpha 0.83 and the trait accounting for 0.83 of the sum score's variance. At 0.6 the reversed items form their own block (0.65 among themselves, 0.32 with the forward items), alpha *rises* to 0.87, and the trait's share falls to 0.69. Give the forward items a wording factor too and there are two blocks, alpha 0.90 and the trait's share 0.59. The wording factor acts like the correlated errors that [Classical test theory and reliability](ctt-reliability.qmd) warned can push alpha above reliability. The second eigenvalue passing 1 is a first hint of the extra dimension; [Factor analysis I](fa-exploratory.qmd) explains eigenvalues and how to count dimensions with them.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A ten-item scale with five reversed items has alpha 0.90. A colleague concludes that wording effects can't be a concern, since they would have lowered alpha. What does the widget say?\",\n  options: [\n    {text: \"That doesn't follow: a wording factor shared by the reversed items can raise alpha\", correct: true, why: \"In the widget alpha went from 0.83 to 0.87 as the reversed items' wording loading rose from 0 to 0.6, while the trait's share of the sum score fell from 0.83 to 0.69. Alpha counts shared wording variance as if it were signal.\"},\n    {text: \"It's right: wording effects always lower alpha\", correct: false, why: \"Only when they work against the trait. A shared wording factor adds covariance within the reversed block, and alpha goes up.\"},\n    {text: \"It's right only if the scale is balanced\", correct: false, why: \"The widget's scale is balanced (five and five), and alpha still rose with the wording loading.\"}\n  ]\n})\n```\n\nShould a scale include reversed items, then? Including them assumes acquiescence is a large enough source of variance, for this population and format, to guard against; the first widget shows its cost. Treating them as plain opposites of the forward items assumes respondents read them that way; the second widget shows what happens when they don't. [Suárez-Álvarez et al. (2018)](https://doi.org/10.7334/psicothema2018.33), giving a self-efficacy test in forward, reversed and mixed forms, found lower reliability and extra variance in the mixed form. [Weijters and Baumgartner (2012)](https://doi.org/10.1509/jmr.11.0368) review both sides, distinguish items reversed in meaning from items reversed by a negation, and recommend using reversed items with care. My own practice is this: I include reversed items when acquiescence is a real risk, as with agree–disagree formats and respondents who may answer quickly; I write them as opposites in meaning (\"I am often bored\") rather than negations (\"I am not often interested\"); and I plan the analysis expecting a wording factor rather than hoping it away.\n\n### The pilot, and reading the items\n\nThe pilot's item analysis uses the tools of [Classical test theory and reliability](ctt-reliability.qmd): item means, item-rest correlations, alpha with each item removed. What this lesson adds is the reading. A weak item may be keyed backwards, measure something else, or be read in a sense we didn't intend, and those call for different decisions: rekey, drop, rewrite. The number flags the item; the text and the cognitive interviews decide.\n\nTwo later lessons carry this further. Content review is the first kind of validity evidence in [Gathering validity evidence](validity-evidence.qmd), which picks up where steps 1 to 4 leave off. And an item can work well on average but differently for groups of respondents at the same level of the construct; [Differential item functioning](dif.qmd) shows how to find such items.\n\n## Simulate\n\nThe code below generates ten four-point items from one trait, with a wording factor on the five reversed items, and prints the correlation matrix, alpha, the block averages, the largest eigenvalues, and the trait's share of the sum score's variance. It is base R and runs in a second.\n\nWith the seed as written (`gamma <- 0.6`), alpha is 0.87, the reversed items correlate 0.66 on average with each other and 0.33 with the forward items, the second eigenvalue is 1.17, and the trait accounts for 0.72 of the sum score's variance. Set `gamma <- 0` and alpha falls to 0.83 while the trait's share rises to 0.82. Then set `gamma <- 0.6` and `gamma_f <- 0.6`: alpha reaches 0.90, the second eigenvalue 1.95, and the trait's share falls to 0.63. Keep that last setting in mind for the real data. Then try `n <- 100`: how noisy are the block averages in a small pilot?\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-17\n# A wording factor: ten four-point items, five worded forward and five reversed.\n# Every item reflects one trait (self-esteem, say); the reversed items also share\n# a second, \"method\" factor that has nothing to do with the trait. The responses are\n# generated already keyed (higher = more of the trait). What do alpha, the\n# correlation matrix and its eigenvalues show? Base R only. New for this course\n# (EDUC 252 c2 describes the problem; the simulation is not in the 252 code).\nset.seed(56)\nn       <- 1000                 # respondents\nlambda  <- 0.6                  # loading of every item on the trait\ngamma   <- 0.6                  # loading of the reversed items on the wording factor (try 0)\ngamma_f <- 0                    # a wording factor of the forward items' own (try 0.6)\nrev     <- rep(c(FALSE, TRUE), each = 5)   # items 6 to 10 are reverse-worded\n\ntrait   <- rnorm(n)\nwording <- rnorm(n)             # independent of the trait\nwording_f <- rnorm(n)           # independent of both\n# A continuous response for each item, with variance 1, cut into four categories.\nlatent  <- sapply(seq_along(rev), function(i) {\n  g <- if (rev[i]) gamma else gamma_f\n  w <- if (rev[i]) wording else wording_f\n  lambda * trait + g * w + sqrt(1 - lambda^2 - g^2) * rnorm(n)\n})\nx <- apply(latent, 2, cut, breaks = c(-Inf, -1, 0, 1, Inf), labels = FALSE)\ncolnames(x) <- paste0(ifelse(rev, \"R\", \"F\"), c(1:5, 1:5))\n\nalpha <- function(m) { k <- ncol(m); k / (k - 1) * (1 - sum(apply(m, 2, var)) / var(rowSums(m))) }\nr <- cor(x)\nsame_fwd <- mean(r[!rev, !rev][upper.tri(diag(5))])\nsame_rev <- mean(r[rev, rev][upper.tri(diag(5))])\nacross   <- mean(r[!rev, rev])\n\nround(r, 2)                                   # two blocks when gamma > 0\nround(c(alpha = alpha(x),\n        mean_r_forward = same_fwd, mean_r_reversed = same_rev, mean_r_across = across), 2)\nround(eigen(r)$values[1:3], 2)                # a second eigenvalue above 1 when gamma is large\n# How well does the sum score track the trait itself? Squared correlation,\n# the share of the sum's variance the trait accounts for.\nround(cor(rowSums(x), trait)^2, 2)\n\n```\n:::\n\n\n[Download this code](code/instrument-building-sim.R) to run it in your own R session.\n\n## With real data\n\n\n\nOur table is [song_2023_rses](https://itemresponsewarehouse.org/tables/song_2023_rses/): the Rosenberg Self-Esteem Scale ([Rosenberg, 1965](https://doi.org/10.1515/9781400876136)) as answered by 1,238 medical students in China, in a study of anxiety about writing in English ([Song et al., 2023](https://doi.org/10.1371/journal.pone.0284335); data CC BY 4.0). Its job is to be our pilot: five items worded for self-esteem and five against, so we can see what reverse wording does. Responses run from 1 to 4, and every respondent answered all ten items. [Download the code](code/instrument-building-irw.R); it needs only base R.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The IRW table, from the CSV link on its landing page (pinned to one version).\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_3:v7_0.song_2023_rses/rows?format=csv\"\ndf <- read.csv(url)\nx <- tapply(df$resp, list(df$id, df$item), function(v) v[1])\nx <- x[, paste0(\"RSES\", 1:10)]         # items in the order of the published scale\nc(respondents = nrow(x), complete = sum(complete.cases(x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents    complete \n       1238        1238 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(df$resp)                         # 1 to 4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   1    2    3    4 \n 355 2412 6592 3021 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Rosenberg's wording: items 3, 5, 8, 9 and 10 are worded against self-esteem.\nneg <- paste0(\"RSES\", c(3, 5, 8, 9, 10))\n```\n:::\n\n\nRosenberg wrote items 3, 5, 8, 9 and 10 against self-esteem. Item 3, for example, is \"All in all, I am inclined to feel that I am a failure\" (wording from the scale as published by the [University of Maryland Department of Sociology](https://socy.umd.edu/about-us/using-rosenberg-self-esteem-scale), which states that the scale is in the public domain). The respondents answered a Chinese version, so the English wording is the original the translation starts from, not what they read. Song et al. say the negatively worded items were reverse-scored. Are the stored responses already keyed?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nalpha <- function(m) { k <- ncol(m); k / (k - 1) * (1 - sum(apply(m, 2, var)) / var(rowSums(m))) }\n# Summed as stored, the table gives the mean, SD and alpha Song et al. report\n# (29.92, 4.79 and 0.863), so what we have are the authors' scored responses.\ns <- rowSums(x)\nsprintf(\"mean %.2f, SD %.2f, alpha %.3f\", mean(s), sd(s), alpha(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"mean 29.92, SD 4.79, alpha 0.863\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# If items 3, 5, 9 and 10 had *not* been reversed, alpha would be far lower:\nflip <- function(m, items) { m[, items] <- 5 - m[, items]; m }\nsprintf(\"alpha with items 3, 5, 9 and 10 un-reversed: %.3f\", alpha(flip(x, paste0(\"RSES\", c(3, 5, 9, 10)))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"alpha with items 3, 5, 9 and 10 un-reversed: 0.658\"\n```\n\n\n:::\n:::\n\n\nSummed as stored, the table reproduces the mean, SD and alpha Song et al. report (29.92, 4.79 and 0.863), and un-reversing items 3, 5, 9 and 10 drops alpha to 0.658. So the table holds the authors' scored responses, and on those four items higher means more self-esteem. Item 8 we come back to.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nitem_rest <- sapply(colnames(x), function(i) cor(x[, i], rowSums(x[, colnames(x) != i])))\ndata.frame(mean = round(colMeans(x), 2), item_rest = round(item_rest, 2),\n           worded = ifelse(colnames(x) %in% neg, \"against\", \"for\"))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|       | mean| item_rest|worded  |\n|:------|----:|---------:|:-------|\n|RSES1  |  3.1|      0.64|for     |\n|RSES2  |  3.1|      0.65|for     |\n|RSES3  |  2.8|      0.50|against |\n|RSES4  |  3.1|      0.63|for     |\n|RSES5  |  2.5|      0.41|against |\n|RSES6  |  3.1|      0.69|for     |\n|RSES7  |  3.1|      0.64|for     |\n|RSES8  |  3.2|      0.47|against |\n|RSES9  |  2.9|      0.63|against |\n|RSES10 |  3.0|      0.64|against |\n\n</div>\n:::\n:::\n\n\nEvery item-rest correlation is between 0.41 and 0.69. By the standard of [Classical test theory and reliability](ctt-reliability.qmd), where 24 of the 30 reading items reached 0.40, the scale hangs together, and an item analysis would stop here. But as one set, or as two?\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Keyed, the five positively worded items correlate 0.71 on average with each other, and four of the negatively worded items (3, 5, 9, 10) correlate 0.61 with each other. What is the average correlation between a positively worded item and one of those four?\",\n  choices: [\"About 0.65: they measure the same thing\", \"About 0.45\", \"About 0.2\"],\n  answer: \"About 0.2\",\n  reveal: \"0.23, with all 20 cross-correlations between 0.11 and 0.33. Items correlate about three times as strongly with items worded in their own direction as with items worded the other way.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nr <- cor(x)\npos  <- paste0(\"RSES\", c(1, 2, 4, 6, 7))\nneg4 <- paste0(\"RSES\", c(3, 5, 9, 10))     # the negatively worded items other than 8\nmean_r <- function(a, b) { v <- r[a, b]; if (identical(a, b)) mean(v[upper.tri(v)]) else mean(v) }\nround(c(within_positive = mean_r(pos, pos), within_negative = mean_r(neg4, neg4),\n        across = mean_r(pos, neg4)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwithin_positive within_negative          across \n           0.71            0.61            0.23 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(range(r[pos, neg4]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.11 0.33\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nord <- c(pos, \"RSES8\", neg4)\nimage(1:10, 1:10, r[ord, rev(ord)], zlim = c(0, 1), axes = FALSE, xlab = \"\", ylab = \"\",\n      col = colorRampPalette(c(\"white\", \"#2780e3\"))(50),\n      main = \"Inter-item correlations, RSES (song_2023_rses)\")\naxis(1, 1:10, sub(\"RSES\", \"\", ord)); axis(2, 1:10, sub(\"RSES\", \"\", rev(ord)), las = 1)\ntext(rep(1:10, 10), rep(1:10, each = 10), sprintf(\"%.2f\", r[ord, rev(ord)]), cex = 0.6)\nabline(v = c(5.5, 6.5), h = c(4.5, 5.5), lty = 2, col = \"grey40\")\n```\n\n::: {.cell-output-display}\n![](instrument-building_files/figure-html/heatmap-1.png){width=576}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(eigen(r)$values[1:3], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.89 2.32 0.55\n```\n\n\n:::\n:::\n\n\nTwo blocks, as in the simulation with wording factors on both sets of items, but sharper: 0.71 and 0.61 within, 0.23 across, and a second eigenvalue of 2.32, above any of the simulation's settings. [Marsh (1996)](https://doi.org/10.1037/0022-3514.70.4.810) reported the same pattern for this scale in a very different population. Are the blocks one construct seen through two wordings, or two constructs (feeling good and feeling bad about oneself)? The correlations alone can't say; problem 6 takes it up, and [Factor analysis II](fa-confirmatory.qmd) gives the models.\n\nNow item 8. Rosenberg wrote it against self-esteem: \"I wish I could have more respect for myself\" ([UMD Department of Sociology](https://socy.umd.edu/about-us/using-rosenberg-self-esteem-scale)). In the heat map it sits with the positive items, not the negative ones.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Item 8 was written against self-esteem. Where does it sit?\nround(rbind(with_positive = range(r[\"RSES8\", pos]), with_negative = range(r[\"RSES8\", neg4])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              [,1] [,2]\nwith_positive 0.54 0.59\nwith_negative 0.01 0.16\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(x[, \"RSES8\"])                    # how the stored values are spread\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3   4 \n 14  96 798 330 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Reversing item 8 as stored would put it at odds with every other item:\nsprintf(\"alpha as stored %.3f; with item 8 reversed %.3f\", alpha(x), alpha(flip(x, \"RSES8\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"alpha as stored 0.863; with item 8 reversed 0.793\"\n```\n\n\n:::\n:::\n\n\nItem 8 correlates 0.54 to 0.59 with the positively worded items and 0.01 to 0.16 with the other negatively worded ones. Its stored values rise with self-esteem, so it points the right way for the sum: reversing it would drop alpha from 0.863 to 0.793. But it doesn't share the wording factor the other four negatively worded items share. Why not?\n\nThe likeliest answer is the translation. [Peng et al. (2024)](https://doi.org/10.2147/PRBM.S494452) report that in the Chinese version of the scale item 8 is understood in a positive sense, and so is scored as a positively worded item. Read that way the item isn't reversed at all, and respondents who think well of themselves agree with it; here 798 + 330 = 1,128 of the 1,238 stored responses are 3 or 4. The IRW's own check of this table's item text reaches the same reading ([`verify_song_2023_rses.R`](https://github.com/ben-domingue/irw/blob/main/itemtext/itemtables/batch_177/verify_song_2023_rses.R)). Song et al. list item 8 among the negatively rated items, following Rosenberg, while the stored scores appear to follow the Chinese version. That is a question of documentation, not a fault in the data, which reproduce the published results exactly. And the data can't settle it: whether a stored 4 means \"strongly agree\" or \"strongly disagree\", every correlation is the same, and only the wording respondents read says which. The respondent answers the item they read, not the item we wrote.\n\n## Problems\n\n1. **Two factors in a correlation.** Let each keyed item be $y_i = \\lambda f + \\gamma_i w + e_i$, with trait $f$ and wording factor $w$ of variance 1, everything uncorrelated, $\\gamma_i = \\gamma$ for reversed items and 0 otherwise, and $\\text{Var}(y_i) = 1$. Derive the correlation between two forward items, two reversed items, and one of each. What $\\lambda$ and $\\gamma$ would the RSES block averages (0.71, 0.61, 0.23) need? What goes wrong, and what does that suggest?\n2. **Alpha if deleted.** Compute alpha for the RSES with each item removed in turn. Which item's removal raises alpha? Read its wording on the [UMD page](https://socy.umd.edu/about-us/using-rosenberg-self-esteem-scale): does anything about how it is worded suggest why? Would you drop it, and does your answer depend on what the scale is used for?\n3. **Choose a format.** For a construct of your choice, sketch one selected-response and one constructed-response item. For each, what does it cost to write, to administer and to score? What would a rater have to decide, and how could two raters disagree?\n4. **Write six items.** Take the construct map you drew in [Constructs and construct maps](constructs.qmd) (its problem 4), or draw one. Write six rating-scale items for it, two of them reverse-worded as opposites in meaning rather than negations. For each, say which level of the map it targets and which item-writing rules it follows.\n5. **A cognitive interview.** Choose two of your items from problem 4, one of them reversed. Write the questions you would ask in a cognitive interview to find out whether respondents read them as intended. What answer would make you rewrite the reversed item?\n6. **Challenge: nuisance or construct?** Is the RSES's second dimension a nuisance of wording, or a real distinction between feeling good about oneself and feeling bad about oneself? [Marsh (1996)](https://doi.org/10.1037/0022-3514.70.4.810) proposes ways to test this. What data would decide it: a translation experiment, a version with every item worded positively, relations with other variables, change over time? This is open.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22From%20construct%20map%20to%20items%3A%20building%20an%20instrument%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20building%20an%20instrument%20from%20a%20construct%20map%20or%20blueprint%3A%20the%20steps%20from%20items%20through%20review%2C%20cognitive%20interviews%20and%20a%20pilot%20to%20revision%3B%20selected-%20and%20constructed-response%20formats%3B%20rules%20for%20writing%20items%3B%20why%20scales%20use%20reverse-worded%20items%20%28acquiescence%29%20and%20how%20reverse%20wording%20can%20add%20a%20second%20dimension%20that%20alpha%20doesn%27t%20reveal%3B%20with%20the%20Rosenberg%20Self-Esteem%20Scale%20answered%20by%20Chinese%20medical%20students%20as%20the%20worked%20example.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Wilson, M. (2005). *Constructing measures: An item response modeling approach*. Lawrence Erlbaum. <https://doi.org/10.4324/9781410611697>. The cycle from construct map to items to a measurement model, at book length.\n- Haladyna, T. M., & Rodriguez, M. C. (2013). *Developing and validating test items*. Routledge. <https://doi.org/10.4324/9780203850381>. Item formats and item writing for tests, with the research behind the guidelines.\n- Haladyna, T. M., Downing, S. M., & Rodriguez, M. C. (2002). A review of multiple-choice item-writing guidelines for classroom assessment. *Applied Measurement in Education*, 15(3), 309–333. <https://doi.org/10.1207/S15324818AME1503_5>. The 31 guidelines, and where each comes from.\n- Clark, L. A., & Watson, D. (2019). Constructing validity: New developments in creating objective measuring instruments. *Psychological Assessment*, 31(12), 1412–1427. <https://doi.org/10.1037/pas0000626>. Developing rating-scale instruments, updating [Clark & Watson (1995)](https://doi.org/10.1037/1040-3590.7.3.309).\n- Willis, G. B. (2005). *Cognitive interviewing: A tool for improving questionnaire design*. Sage. <https://doi.org/10.4135/9781412983655>. How to run cognitive interviews, and what they turn up.\n- Tourangeau, R., Rips, L. J., & Rasinski, K. (2000). *The psychology of survey response*. Cambridge University Press. <https://doi.org/10.1017/CBO9780511819322>. What a respondent does between reading a question and answering it.\n- Weijters, B., & Baumgartner, H. (2012). Misresponse to reversed and negated items in surveys: A review. *Journal of Marketing Research*, 49(5), 737–747. <https://doi.org/10.1509/jmr.11.0368>. The case for and against reversed items, with recommendations.\n- Marsh, H. W. (1996). Positive and negative global self-esteem: A substantively meaningful distinction or artifactors? *Journal of Personality and Social Psychology*, 70(4), 810–819. <https://doi.org/10.1037/0022-3514.70.4.810>. The wording factor in the RSES, and how to ask what it is.\n- Weijters, B., Baumgartner, H., & Schillewaert, N. (2013). Reversed item bias: An integrative model. *Psychological Methods*, 18(3), 320–334. <https://doi.org/10.1037/a0032121>. Acquiescence, carelessness and confirmation bias as sources of the wording factor, in one model.\n- Peng, W., Zhou, Y., Chu, J., Liu, Z., Zheng, K., Yao, S., & Yi, J. (2024). Factorial and criterion validities of the Chinese version of Rosenberg Self-Esteem Scale among undergraduate students. *Psychology Research and Behavior Management*, 17, 4135–4144. <https://doi.org/10.2147/PRBM.S494452>. The Chinese RSES, including how item 8 is scored.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`song_2023_rses`](https://itemresponsewarehouse.org/tables/song_2023_rses/): Song Y, Sznajder K, Bai Q, Xu Y, Dong Y, Yang X (2023). English as a foreign language writing anxiety and its relationship with self-esteem and mobile phone addiction among Chinese medical students-A structural equation model analysis. PLOS ONE, 18(4), e0284335. <https://doi.org/10.1371/journal.pone.0284335>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 2 (slides c2, \"Constructs to items\" and \"Items & responses\", slides 18–25). The point that every response must end up in a fixed set of ordered categories comes from the slides, in new words; the item-writing rules, the reverse-wording material and the RSES analysis are new.\n- **Timing:** about 40 minutes for the core ideas and widgets; the RSES analysis works as a 20-minute lab. Problems 4 and 5 work as a small-group activity, with partners interviewing each other.\n- **Held back:** raters and constructed-response scoring (in [Many sources of error](g-theory.qmd)); wording direction as a dimension, modelled (in [Factor analysis I](fa-exploratory.qmd), [Factor analysis II](fa-confirmatory.qmd) and [Dimensionality and multidimensional IRT](dimensionality.qmd)); response styles such as acquiescence and extreme responding, modelled (in [IRTree models](irtrees.qmd)); distractors as information (in [Nominal response and multiple-choice models](nominal.qmd)); item features that predict difficulty (in [What is an item?](explanatory-irt.qmd)); content evidence (in [Gathering validity evidence](validity-evidence.qmd)); items that work differently across groups (in [Differential item functioning](dif.qmd)).\n- **Item text:** the RSES is in the public domain according to the [University of Maryland Department of Sociology](https://socy.umd.edu/about-us/using-rosenberg-self-esteem-scale), which publishes it. The lesson still quotes only items 3 and 8, the two the argument needs. The Chinese wording respondents saw is in the IRW's item-text table (Redivis login needed) and is not reproduced.\n- **Solutions:** held back in `solutions/instrument-building.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "instrument-building_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}