{
  "hash": "94ec80a3d9c86d1e4d7060b79d8164e4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AI and psychometrics\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Beyond the standard models  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [From the 1PL to the 4PL](1pl-to-4pl.qmd) · [What is an item? Explanatory item response models](explanatory-irt.qmd)  \n**Builds toward:** none  \n**IRW tables:** [`himmelstein-impossible_question-2025`](https://itemresponsewarehouse.org/tables/himmelstein-impossible_question-2025/), [`gpt4mcq_young_2025`](https://itemresponsewarehouse.org/tables/gpt4mcq_young_2025/), [`genpsych_russell_2024_gpt4o`](https://itemresponsewarehouse.org/tables/genpsych_russell_2024_gpt4o/)  \n**From EDUC 252:** slides c10; code [`c10/model.R`](https://github.com/ben-domingue/252/blob/main/c10/model.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n```{ojs}\n//| echo: false\nimport {grid, palette} from \"./widgets/irt.js\"\nimport {scoringWorld, worthInRespondents, simulatedRespondents, optionCurves, optionShares} from \"./widgets/ai-psychometrics.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nLanguage models now score essays, write items, predict item difficulty, and answer questionnaires in place of people. Each is a claim about measurement that the tools of this course can check. The lesson starts from the question [What is an item?](explanatory-irt.qmd) handed on: that lesson explained difficulty with features that people coded, so can an item's text alone predict it? My answer depends on the yardstick. I judge a difficulty prediction by how many respondents it is worth, and on the general-knowledge items below the best text features are worth about three.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- compute exact agreement, Cohen's kappa and quadratic weighted kappa from two raters' scores, and say what an automated scorer's agreement with human raters does and doesn't show;\n- add text features to the LLTM and report how much of the variation in difficulty they explain;\n- convert the error of a difficulty prediction into the number of respondents it is worth;\n- say why more simulated respondents don't fix a language model's own view of the items;\n- check machine-written items as you would any others: difficulty, distractors, keying, and whether each item goes with the construct it was written for.\n\n## Core ideas\n\n### Two intersections\n\nAI and psychometrics meet in two directions. One uses AI to measure people. The other uses psychometrics to measure AI: a benchmark is a set of items and a model is a respondent, and [Martínez-Plumed, Prudêncio, Martínez-Usó and Hernández-Orallo (2019)](https://doi.org/10.1016/j.artint.2018.09.004) fit item response models to machine-learning classifiers, one item per test instance. The IRW holds no table of models answering questions yet, so that direction gets problem 6; the rest of the lesson is about the first.\n\n### Automated scoring is an agreement problem\n\nAn essay-scoring engine is trained to reproduce the scores human raters give; e-rater is a long-running example ([Attali & Burstein, 2006](https://ejournals.bc.edu/index.php/jtla/article/view/1650)). How do we know it works? The first evidence is agreement with human raters, read from the table that crosses the engine's scores with a human's. Three statistics summarize that table:\n\n- **exact agreement**, the share of responses on the diagonal;\n- **Cohen's kappa**, exact agreement corrected for the agreement two raters would reach by chance with the same margins, $\\kappa = (p_o - p_e)/(1 - p_e)$;\n- **quadratic weighted kappa** (QWK; [Cohen, 1968](https://doi.org/10.1037/h0026256)), which charges each disagreement by its squared distance: with weights $w_{ik} = (i - k)^2$, observed counts $O_{ik}$ and the counts $E_{ik}$ expected from the margins,\n$$\\text{QWK} = 1 - \\frac{\\sum_{i,k} w_{ik} O_{ik}}{\\sum_{i,k} w_{ik} E_{ik}}.$$\n\nAgreement with what? The baseline is the agreement of two human raters scoring the same responses. [Williamson, Xi and Breyer (2012)](https://doi.org/10.1111/j.1745-3992.2011.00223.x) make human–machine agreement one strand of the evidence for an engine, beside its fit to the purpose, its relations with independent measures, its generalizability across tasks and forms, and its consequences for subgroups.\n\n#### Try it: agreement by hand\n\nFive hundred essays have a true quality. Two human raters score it on a scale from 1 to 4 with the same noise; an engine adds noise of its own, may shift, and may compress its scores toward the middle.\n\n```{ojs}\n//| echo: false\nviewof sc_noise = Inputs.range([0.05, 1.2], {value: 0.55, step: 0.05, label: \"Engine's noise (humans: 0.55)\"})\nviewof sc_shift = Inputs.range([-1, 1], {value: 0, step: 0.05, label: \"Engine's shift (score points)\"})\nviewof sc_comp = Inputs.range([0.3, 1.2], {value: 1, step: 0.05, label: \"Engine's use of the scale (1 = like the humans)\"})\n```\n\n```{ojs}\n//| echo: false\nsc = scoringWorld({machineNoise: sc_noise, shift: sc_shift, compress: sc_comp})\nsc_cells = sc.machine.table.flatMap((row, i) => row.map((n, k) => ({human: i + 1, engine: k + 1, n})))\nPlot.plot({\n  width: 380, height: 320, padding: 0.05, x: {label: \"Engine's score\", domain: [1, 2, 3, 4]}, y: {label: \"Human 1's score\", domain: [4, 3, 2, 1]},\n  color: {range: [palette.white, palette.main]},\n  marks: [\n    Plot.cell(sc_cells, {x: \"engine\", y: \"human\", fill: \"n\", stroke: palette.rule}),\n    Plot.text(sc_cells, {x: \"engine\", y: \"human\", text: \"n\", fill: d => d.n > 60 ? palette.white : palette.ink, fontSize: 13})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`| | Exact agreement | Kappa | QWK | Mean score |\n|---|---|---|---|---|\n| Human 1 with human 2 | ${sc.human.exact.toFixed(2)} | ${sc.human.kappa.toFixed(2)} | ${sc.human.qwk.toFixed(2)} | ${sc.human.meanY.toFixed(2)} |\n| Human 1 with the engine | ${sc.machine.exact.toFixed(2)} | ${sc.machine.kappa.toFixed(2)} | **${sc.machine.qwk.toFixed(2)}** | ${sc.machine.meanY.toFixed(2)} |`\n```\n\nAs the widget loads, the engine agrees with human 1 about as well as human 2 does (QWK 0.70 against 0.65; the gap is sampling noise). Shift it up half a point: exact agreement falls from 0.54 to 0.47, QWK only to 0.65. Compress its scale to 0.6 and QWK drops to 0.55. Then cut its noise to 0.3 with the scale at 0.7: it matches the human baseline (0.66) while still hugging the middle. The same QWK can come from quite different engines.\n\nQWK depends on the margins of the table and the length of the scale ([Lewis & Casabianca, 2026](https://doi.org/10.1111/emip.70017)). The proportional reduction in mean squared error (PRMSE) judges an engine against the human raters' *true* scores, allowing for their unreliability, and can reach a different conclusion from QWK on the same data ([McCaffrey, Casabianca & Johnson, 2025](https://doi.org/10.1111/jedm.70011)). And agreement says nothing about what the engine responds to: in 240,000 admission essays, content and style correlated more strongly with household income than SAT scores did ([Alvero et al., 2021](https://doi.org/10.1126/sciadv.abi9031)). An engine could agree with human raters and carry that signal too; Williamson et al.'s subgroup evidence is how you would find out.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Rater models](rater-models.qmd): an engine is one more rater, with a severity of its own. [Casabianca, Donoghue, Shin, Chao and Choi (2023)](https://doi.org/10.1111/jedm.12360) found that two human ratings connected raters better than one human rating plus an engine's, and that engine scores alone did not connect raters adequately.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"An engine gives every essay exactly one point more than rater A does (A never uses the top score). What are the exact agreement and the QWK?\",\n  options: [\n    {text: \"Exact agreement 0; QWK well above 0\", correct: true, why: \"No essay gets the same score, so exact agreement is 0. But the two sets of scores move together perfectly, and QWK charges a one-point gap only $1^2 = 1$ against the larger squared gaps chance would produce. With A's scores spread with variance 1, QWK is $2/(2 + 1) \\\\approx 0.67$ (Go deeper below).\"},\n    {text: \"Both 0\", correct: false, why: \"Kappa-type statistics compare the observed disagreement with what chance would give. Chance pairs essays scored far apart; this engine is never more than a point away.\"},\n    {text: \"Exact agreement 0; QWK 1\", correct: false, why: \"QWK is 1 only when every essay gets the same score from both. The constant gap is charged: that is what separates agreement from correlation, which would be 1 here.\"}\n  ]\n})\n```\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: QWK is a correlation that charges for differences in mean and spread\n\n**Assumptions:** two raters score the same $n$ responses on an integer scale; $p_{ik}$ is the observed share with scores $(i, k)$; the expected shares are the products of the margins, $p_{i\\cdot}\\,p_{\\cdot k}$; weights are $(i - k)^2$; means, variances and the covariance are computed with divisor $n$.\n\nThe numerator of the fraction in QWK is the mean squared difference between the two scores, $\\sum_{i,k} (i-k)^2 p_{ik} = E[(X - Y)^2]$. The denominator is the same expectation for two *independent* raters with the same margins. Expanding the square,\n$$E[(X-Y)^2] = \\sigma_X^2 + \\sigma_Y^2 - 2\\sigma_{XY} + (\\mu_X - \\mu_Y)^2,$$\nand under independence the covariance term is 0. So\n$$\\text{QWK} = 1 - \\frac{\\sigma_X^2 + \\sigma_Y^2 - 2\\sigma_{XY} + (\\mu_X - \\mu_Y)^2}{\\sigma_X^2 + \\sigma_Y^2 + (\\mu_X - \\mu_Y)^2} = \\frac{2\\sigma_{XY}}{\\sigma_X^2 + \\sigma_Y^2 + (\\mu_X - \\mu_Y)^2}.$$\nThis is exact, and it is [Lin's (1989)](https://doi.org/10.2307/2532051) concordance correlation coefficient. Three things follow. With equal means and variances, QWK is the Pearson correlation. A difference in means lowers it (the widget's shift), and so does a difference in spread even when the correlation is 1 (the widget's compression). And [Fleiss and Cohen (1973)](https://doi.org/10.1177/001316447303300309) showed that weighted kappa with these weights is, apart from terms of order $1/n$, the intraclass correlation that counts rater differences as error: the absolute-agreement coefficient of [Many sources of error](g-theory.qmd), if you've done it.\n:::\n\n### Can the text of an item predict its difficulty?\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is an item?](explanatory-irt.qmd): the LLTM writes each item's easiness as a weighted sum of its features, and an item residual with SD $\\sigma_\\varepsilon$ gives a size to what the features leave out. For the verbal aggression items, features coded from the design explained 89% of the variance in easiness, and the residual SD was 0.34.\n:::\n\nWhere do the features come from? Some are counts from the text, such as word count and sentence length, the stuff of readability measures like the Lexile framework ([Stenner, Burdick, Sanford & Burdick, 2006](https://pubmed.ncbi.nlm.nih.gov/16807496/)). Some are coded by experts from a model of how items are solved: for paragraph-comprehension items from the GRE, variables describing the decision among options accounted for difficulty and those describing the text did not ([Gorin & Embretson, 2006](https://doi.org/10.1177/0146621606288554)). And some are representations of the text from a language model ([Benedetto et al., 2023](https://doi.org/10.1145/3556538), survey the methods). [Kapoor, Truong, Haber, Ruiz-Primo and Domingue (2025)](https://arxiv.org/abs/2502.20663) predicted the difficulty of state reading items from annotated linguistic, test and context features: a correlation of 0.77 with the true difficulties, and a root mean squared error of 0.59 against 0.92 for predicting the mean. Embeddings from language models improved the prediction only marginally, and either kind of feature alone did about as well.\n\nIs a correlation of 0.77 good? Two yardsticks assume different uses. **Accuracy** (a correlation, an RMSE) assumes the prediction is the product, as when sorting a bank. **Respondents** assumes the point is to calibrate items with fewer people. A calibration on $n$ respondents estimates $b$ with a standard error of about $1/\\sqrt{n\\,E[p(1-p)]}$, since each respondent adds $p(1-p)$ to the information about the item's location (the curvature of [The likelihood and logistic regression](likelihood.qmd)). A prediction whose errors have SD $\\sigma$ is therefore as precise as a calibration on\n$$n^* = \\frac{1}{\\sigma^2\\,E[p(1-p)]}$$\nrespondents.\n\nI use the second yardstick. The prize in predicting difficulty is skipping or shrinking the field test, so I want to know how many respondents a prediction is worth; accuracy statistics don't say.\n\n#### Try it: what a prediction is worth\n\n```{ojs}\n//| echo: false\nviewof wp_r = Inputs.range([0, 0.995], {value: 0.77, step: 0.005, label: \"Correlation of predicted and true difficulty\"})\nviewof wp_sdb = Inputs.range([0.3, 2], {value: 0.92, step: 0.01, label: \"SD of the items' difficulties\"})\nviewof wp_sdt = Inputs.range([0.3, 2], {value: 1, step: 0.05, label: \"SD of respondents' θ\"})\n```\n\n```{ojs}\n//| echo: false\nwp = worthInRespondents({r: wp_r, sdB: wp_sdb, sdTheta: wp_sdt})\nPlot.plot({\n  width: 700, height: 300, x: {type: \"log\", label: \"Respondents in the field test\", domain: [5, 1000]},\n  y: {label: \"Standard error of the calibrated difficulty\", domain: [0, 1]},\n  marks: [\n    Plot.line(wp.curve, {x: \"n\", y: \"se\", stroke: palette.main, strokeWidth: 2.5}),\n    Plot.ruleY([wp.sigma], {stroke: palette.contrast, strokeDasharray: \"4 3\"}),\n    Plot.dot(Number.isFinite(wp.nStar) && wp.nStar >= 5 && wp.nStar <= 1000 ? [{n: wp.nStar, se: wp.sigma}] : [], {x: \"n\", y: \"se\", r: 6, fill: palette.contrast})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Prediction error SD: **${wp.sigma.toFixed(2)}** logits (dashed). It is worth a field test of about **${Number.isFinite(wp.nStar) ? Math.round(wp.nStar) : \"∞\"}** respondents.`\n```\n\nWith Kapoor et al.'s correlation and spread of difficulties, the prediction is worth about 14 respondents, if their difficulties are logits on a scale where $\\theta$ has SD 1 (an assumption here). A correlation of 0.9 is worth 30; 0.95 is worth 59; matching a 200-person field test needs about 0.986. [Liu, Bhandari and Pardos (2025)](https://doi.org/10.1111/bjet.13570) report their result on this yardstick: the item parameters from their language-model respondents were about as good as those from 50 undergraduates.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Model fit and out-of-sample prediction](fit-prediction.qmd): the IMV put a predictive gain on a scale that compares across datasets. Respondents do the same job here, in the unit a test developer pays for.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A new text model halves the SD of the prediction errors. How many more respondents is its prediction worth?\",\n  options: [\n    {text: \"Four times as many\", correct: true, why: \"$n^* = 1/(\\\\sigma^2 E[p(1-p)])$ depends on $\\\\sigma^2$, so halving $\\\\sigma$ multiplies $n^*$ by 4.\"},\n    {text: \"Twice as many\", correct: false, why: \"Standard errors shrink with the square root of $n$, so halving an error takes four times the respondents.\"},\n    {text: \"It depends on the correlation, not the error SD\", correct: false, why: \"The correlation matters only through the error SD it implies, $\\\\sigma = \\\\text{SD}(b)\\\\sqrt{1 - r^2}$.\"}\n  ]\n})\n```\n\n### Language models as simulated respondents\n\n[Argyle et al. (2023)](https://doi.org/10.1017/pan.2023.2) conditioned GPT-3 on the backgrounds of real survey participants and found that it reproduced the response patterns of many subgroups. For items, [Liu et al. (2025)](https://doi.org/10.1111/bjet.13570) had six models answer college algebra items: each model's abilities were narrowly spread, an ensemble of models came closer to students, and the item parameters correlated above 0.8 with those from students for GPT-3.5. [Scarlatos, Fernandez, Ormerod, Lottridge and Lan (2025)](https://arxiv.org/abs/2507.05129) train a model so that simulated students at an instructed ability answer as an item response model says they should, and use the simulated answers to predict the difficulty of open-ended items.\n\nDoes simulation beat the simpler route of the last section? A simulator is a difficulty predictor, so it answers to the same yardstick, and it has to get each item right: a model may find an item easy or hard for reasons of its own.\n\n#### Try it: simulated respondents\n\nThirty items with known difficulties, answered by a model playing simulated students.\n\n```{ojs}\n//| echo: false\nviewof sr_n = Inputs.range([20, 2000], {value: 200, step: 10, label: \"Simulated respondents\"})\nviewof sr_spread = Inputs.range([0.1, 1.5], {value: 0.4, step: 0.05, label: \"Spread of their abilities (people: 1)\"})\nviewof sr_bias = Inputs.range([0, 1.5], {value: 0.5, step: 0.05, label: \"Item-specific bias (SD, logits)\"})\n```\n\n```{ojs}\n//| echo: false\nsr = simulatedRespondents({nSim: sr_n, spread: sr_spread, itemBias: sr_bias})\nsr_worth = worthInRespondents({sigma: sr.rmse})\nPlot.plot({\n  width: 700, height: 320, x: {label: \"True difficulty\", domain: [-3, 3]}, y: {label: \"Difficulty implied by the simulation\", domain: [-3.5, 3.5]},\n  marks: [\n    Plot.line([[-3, -3], [3, 3]], {stroke: palette.guide, strokeDasharray: \"4 3\"}),\n    Plot.dot(sr.items, {x: \"truth\", y: \"implied\", r: 5, fill: palette.main})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Correlation with the truth: **${sr.r.toFixed(2)}**; RMSE ${sr.rmse.toFixed(2)} logits, worth about **${Math.round(sr_worth.nStar)}** real respondents.`\n```\n\nAt the defaults the correlation is 0.91 and the simulation is worth about 30 respondents. Raise the simulated respondents to 2,000 and the correlation stays at 0.91. Set the bias to 0 instead and it rises to 0.98, worth about 144 respondents. More simulated respondents remove sampling noise, not the model's own view of the items. (The widget rescales implied difficulties to the truth's spread, so the narrow spread matters little here.)\n\n### Automatic item generation, and checking what it makes\n\nItems have been generated by rule for decades. A cognitive design system builds in the features that make an item hard and calibrates the design principles rather than each item ([Embretson, 1999](https://doi.org/10.1007/BF02294564)); item models are templates with slots filled by rule ([Gierl & Haladyna, 2012](https://doi.org/10.4324/9780203803912); for medical multiple-choice items, [Gierl, Lai & Turner, 2012](https://doi.org/10.1111/j.1365-2923.2012.04289.x)). Language models write items without a template. AI-GENIE generates a pool with a language model and prunes it with network psychometrics before anyone answers ([Russell-Lasalandra, Christensen & Golino, 2024](https://doi.org/10.31234/osf.io/fgbj4)).\n\nWhoever writes the items, the questions are the same: does each measure its construct, how hard is it, do the wrong options draw anyone? Distractors that draw almost nobody are common in human-written tests too: [Haladyna and Downing (1993)](https://doi.org/10.1177/0013164493053004013) found that items seldom had more than three options that performed acceptably, and a meta-analysis of 80 years of studies supports three options ([Rodriguez, 2005](https://doi.org/10.1111/j.1745-3992.2005.00006.x)).\n\n#### Try it: distractors that work, and dead ones\n\nA four-option item. The key's pull rises with $\\theta$; each distractor has a fixed pull of its own.\n\n```{ojs}\n//| echo: false\nviewof dd_key = Inputs.range([-1, 4], {value: 0.5, step: 0.1, label: \"Key: how easy\"})\nviewof dd_a = Inputs.range([-4, 1], {value: 0, step: 0.1, label: \"Distractor A's pull\"})\nviewof dd_b = Inputs.range([-4, 1], {value: -2.5, step: 0.1, label: \"Distractor B's pull\"})\nviewof dd_c = Inputs.range([-4, 1], {value: -2.5, step: 0.1, label: \"Distractor C's pull\"})\n```\n\n```{ojs}\n//| echo: false\ndd_pulls = [dd_a, dd_b, dd_c]\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Ability θ\"}, y: {label: \"P(choosing the option)\", domain: [0, 1]},\n  color: {legend: true, domain: [\"Key\", \"Distractor A\", \"Distractor B\", \"Distractor C\"], range: [palette.main, palette.contrast, palette.light, palette.guide]},\n  marks: [\n    Plot.ruleY([0.25], {stroke: palette.rule, strokeDasharray: \"4 3\"}),\n    Plot.line(optionCurves(dd_pulls, dd_key, grid(-4, 4)), {x: \"theta\", y: \"p\", stroke: \"option\", strokeWidth: 2.5})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\ndd_sh = optionShares(dd_pulls, dd_key)\nmd`In a group with θ ~ N(0, 1): ${dd_sh.map(d => `${d.option} **${(100 * d.share).toFixed(0)}%**`).join(\", \")}. Distractors chosen by fewer than 5%: **${dd_sh.slice(1).filter(d => d.share < 0.05).length}** of 3.`\n```\n\nAt the defaults distractor A draws 38% of the group and B and C draw 3% each: two dead distractors. Respondents far below the item choose A, so the key's curve falls below chance (dashed). Make the key easier (2.5) and even A falls to 13%. On an easy item, dead distractors alone don't show that they were badly written.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [From the 1PL to the 4PL](1pl-to-4pl.qmd): with four options, chance is 0.25, yet the 3PL's lower asymptotes for the RMET were mostly near 0, because almost nobody sat near chance. A working distractor is one more reason the floor needn't be at chance.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A language model writes a four-option item. Of 190 students, 93% choose the key and the distractors draw 3%, 2% and 2%. What does this show?\",\n  options: [\n    {text: \"The item is easy for this group, and these data say little about its distractors\", correct: true, why: \"With only 7% choosing any distractor, there are too few wrong answers to tell a dead distractor from a working one. In a weaker group the same distractors might draw many.\"},\n    {text: \"The distractors are badly written\", correct: false, why: \"They may be, but an easy item leaves little for any distractor to draw, as the widget's easy key showed. Try the item on a group for whom it is harder, or look at who chooses each option.\"},\n    {text: \"The key is ambiguous\", correct: false, why: \"An ambiguous key would split strong respondents between the key and a distractor. Here nearly everyone agrees on the key.\"}\n  ]\n})\n```\n\n## Simulate\n\nThe code simulates 200 items whose difficulties follow two text features plus a residual with SD `sd_resid`, fits the feature model on 150, predicts the other 50, converts the error to respondents, and compares a field test of the 50 with `n_field` respondents. Base R; a second.\n\nWith the seed as written, the prediction correlates 0.68 with the new difficulties (RMSE 0.57), worth about 16 respondents; a 25-person field test does better (RMSE 0.43). Set `n_field <- 16` and the field test's RMSE is 0.58, matching the prediction. Try `sd_resid <- 0.2` (worth about 142) and `sd_resid <- 1` (about 6).\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-18\n# What is a difficulty prediction worth? Simulate items whose difficulties depend on\n# two text features plus an item-specific part the features miss, predict the\n# difficulties of new items from the features, and convert the prediction error into\n# the number of respondents a field test would need to do as well. Base R only; runs\n# in a second or two. New for this course (EDUC 252 c10 poses the question).\nset.seed(55)\nn_items  <- 200    # items written, with known text features\nn_train  <- 150    # items already calibrated; the other 50 are new\nsd_resid <- 0.6    # SD of what the features miss (try 0.2 and 1)\nn_field  <- 25     # respondents in a small field test of the new items\n\n# Two standardized text features (think: word count, and a rating of how rare the\n# words are), and difficulties that follow them up to an item residual.\nf1 <- rnorm(n_items); f2 <- rnorm(n_items)\nb  <- 0.3 * f1 + 0.5 * f2 + rnorm(n_items, 0, sd_resid)\n\n# Fit the feature model on the calibrated items; predict the new ones.\ntrain <- 1:n_train; test <- (n_train + 1):n_items\nfit  <- lm(b ~ f1 + f2, data = data.frame(b, f1, f2)[train, ])\npred <- predict(fit, newdata = data.frame(f1, f2)[test, ])\nc(cor_new_items = cor(pred, b[test]), rmse_prediction = sqrt(mean((pred - b[test])^2)))\n\n# How many respondents is that worth? One respondent with theta ~ N(0, 1) carries\n# E[p(1 - p)] units of information about an item's difficulty (Rasch model), so a\n# calibration on n respondents has SE about 1 / sqrt(n * E[p(1 - p)]). A prediction\n# with error SD sigma matches n* = 1 / (sigma^2 * E[p(1 - p)]).\nepq <- function(bi) integrate(function(t) plogis(t - bi) * (1 - plogis(t - bi)) * dnorm(t), -Inf, Inf)$value\ninfo  <- mean(sapply(b[test], epq))\nsigma <- sqrt(mean((pred - b[test])^2))\nc(information_per_respondent = info, respondents_worth = 1 / (sigma^2 * info))\n\n# Check against an actual field test: n_field respondents answer the new items, and we\n# estimate each difficulty by maximum likelihood from their responses alone, taking\n# their abilities as known (as if linked through items already in the bank). The\n# search is bounded at +/- 6 logits, for items everyone got right or wrong.\ntheta <- rnorm(n_field)\nx <- sapply(b[test], function(bi) rbinom(n_field, 1, plogis(theta - bi)))\nb_field <- apply(x, 2, function(xi)\n  optimize(function(bb) -sum(dbinom(xi, 1, plogis(theta - bb), log = TRUE)), c(-6, 6))$minimum)\nc(rmse_field_test = sqrt(mean((b_field - b[test])^2)), rmse_prediction = sigma,\n  field_test_rmse_expected = 1 / sqrt(n_field * info))\n\n```\n:::\n\n\n[Download this code](code/ai-psychometrics-sim.R) to run it in your own R session.\n\n## With real data\n\n\n\nOur main example is [himmelstein-impossible_question-2025](https://itemresponsewarehouse.org/tables/himmelstein-impossible_question-2025/): its job is the deep dive in miniature, testing whether item text predicts difficulty. The two contrasts are items written by language models: [gpt4mcq_young_2025](https://itemresponsewarehouse.org/tables/gpt4mcq_young_2025/), multiple-choice items written by GPT-4, and [genpsych_russell_2024_gpt4o](https://itemresponsewarehouse.org/tables/genpsych_russell_2024_gpt4o/), personality items written by GPT-4o. Both are openly licensed, so their items are shown in full (citing the authors and naming the model). [Download the code](code/ai-psychometrics-irw.R); it needs `lme4`, `mirt` and `haven`.\n\n### Impossible questions: does the text predict difficulty?\n\nThe Forecasting Proficiency Test ([Himmelstein et al., 2025](https://doi.org/10.31234/osf.io/a7kdx_v8); materials and data at [forecastingresearch/fpt](https://github.com/forecastingresearch/fpt)) includes an impossible-question task adapted from [Bennett and Steyvers (2022)](https://doi.org/10.1037/dec0000165). Each question offers two answers and an opt-out. Most have a right answer; some ask about things that don't exist, and the right response is to opt out. Two examples from the study's [data file](https://github.com/forecastingresearch/fpt/blob/main/data_cognitive_tasks/task_datasets/data_impossible_question.csv) are \"Not all metals are attracted to magnets\" (true or false) and \"What's the habitat of a Rojixon bird?\" (deserts or tropical rainforests). Keying: 1 is the keyed answer, or an opt-out on an impossible question. A gentle note from the IRW's item-text notes: the instructions said opt-outs weren't scored, but on answerable questions they count as wrong.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nsuppressPackageStartupMessages(library(lme4))\n# Each IRW table has a landing page (itemresponsewarehouse.org/tables/<name>/) with a\n# CSV download. This link is pinned to one version of the data.\niq_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_2:v24_0.himmelstein-impossible_question-2025/rows?format=csv\"\niq <- read.csv(iq_url)\nc(respondents = length(unique(iq$id)), items = length(unique(iq$item)),\n  max_per_person_item = max(table(iq$id, iq$item)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        respondents               items max_per_person_item \n               1194                  90                   1 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Two waves: each respondent took 30 items in wave 3 and 30 in wave 5.\ntable(wave = iq$wave)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwave\n    3     5 \n35179 34924 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsummary(as.vector(table(iq$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  28.00   59.00   60.00   58.71   60.00   60.00 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The questions, from the study's own data file (pinned to one commit of the FPT\n# repository): the IRW item code is the file's `id`. `aig_version` says which form an\n# item was on: the anchor form, which every respondent took, or one of two forms\n# built for automatic item generation (A and B). Impossible questions have ids IQ_*.\nsrc_url <- paste0(\"https://raw.githubusercontent.com/forecastingresearch/fpt/\",\n                  \"fdbe605700cc172c03abe009bbd894a20f5cb69b/\",\n                  \"data_cognitive_tasks/task_datasets/data_impossible_question.csv\")\nsrc <- read.csv(src_url)\nitems <- unique(src[, c(\"id\", \"question_text\", \"answer_1\", \"answer_2\", \"question_type\", \"aig_version\")])\nnames(items)[1] <- \"item\"\ntable(type = items$question_type, form = items$aig_version)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    form\ntype aig_A aig_B anchor\n  GK    24    24     24\n  IQ     6     6      6\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Which form did each respondent take in which wave? The anchor form in one wave and\n# one generated form in the other, so pooling the waves counts each person once per item.\niq$form <- items$aig_version[match(iq$item, items$item)]\ntable(wave = iq$wave, form = iq$form)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    form\nwave aig_A aig_B anchor\n   3  8794  8151  18234\n   5  9309  8995  16620\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Two text features, as in the IRW vignette on item language and difficulty: word\n# count, and mean word length in characters with punctuation removed.\ntext_features <- function(txt) {\n  words <- strsplit(trimws(gsub(\"[[:punct:]]\", \" \", txt)), \"\\\\s+\")\n  words <- lapply(words, function(w) w[nchar(w) > 0])\n  data.frame(word_count = lengths(strsplit(trimws(txt), \"\\\\s+\")),\n             mean_word_length = vapply(words, function(w) if (length(w)) mean(nchar(w)) else NA_real_, 0))\n}\nitems <- cbind(items, text_features(items$question_text))\nitems$impossible <- as.integer(items$question_type == \"IQ\")\n# Proportion correct among those who answered, and its logit. (An opt-out is scored\n# correct on an impossible question and wrong on an answerable one.)\nitems$p <- as.vector(tapply(iq$resp, iq$item, mean)[items$item])\nitems$n <- as.vector(table(iq$item)[items$item])\nitems$logit_p <- qlogis((items$p * items$n + 0.5) / (items$n + 1))\nhead(items[order(items$p), c(\"item\", \"question_text\", \"p\")], 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    |item  |question_text                                                            |         p|\n|:---|:-----|:------------------------------------------------------------------------|---------:|\n|4   |IQ_6  |Resistance Configuration Theory is a psychological theory that explains: | 0.1922078|\n|196 |IQ_18 |The Diflective Assumption Theory helps us understand:                    | 0.2447552|\n|24  |IQ_2  |How many sides does a Detseroid have?                                    | 0.2724167|\n|205 |IQ_16 |What's the side effect of Grilpax's disease?                             | 0.2732049|\n\n</div>\n:::\n:::\n\n\nEach respondent took the 30-item anchor form in one wave and one of two generated forms in the other, and no one answered an item twice, so we pool the waves. The hardest items are impossible questions, answered correctly (by opting out) by as few as 19%.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Longer questions might be harder to read, or easier because they give more context. Across the 72 answerable questions, how strongly does word count track difficulty?\",\n  choices: [\"Strongly (|r| above 0.6)\", \"Moderately (|r| about 0.3)\", \"Barely (|r| below 0.1)\"],\n  answer: \"Moderately (|r| about 0.3)\",\n  reveal: \"The correlation of word count with the logit of proportion correct is −0.26 among the answerable questions, and −0.11 across all 90. Whether a question is impossible matters far more. Check below.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Word count against logit proportion correct: all 90 items, the 72 answerable ones,\n# and mean word length for comparison.\nans <- items$impossible == 0\nround(c(words_all = cor(items$word_count, items$logit_p),\n        words_answerable = cor(items$word_count[ans], items$logit_p[ans]),\n        word_length_all = cor(items$mean_word_length, items$logit_p)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       words_all words_answerable  word_length_all \n           -0.11            -0.26             0.15 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# What the text says: the impossible flag.\naggregate(cbind(p, word_count) ~ question_type, data = items, FUN = function(v) round(mean(v), 2))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|question_type |    p| word_count|\n|:-------------|----:|----------:|\n|GK            | 0.70|      11.36|\n|IQ            | 0.34|       7.50|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(r2_impossible_flag = summary(lm(logit_p ~ impossible, data = items))$r.squared,\n        r2_word_count = summary(lm(logit_p ~ word_count, data = items))$r.squared), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr2_impossible_flag      r2_word_count \n              0.23               0.01 \n```\n\n\n:::\n:::\n\n\nLonger answerable questions are somewhat harder (r = −0.26). Across all 90 the correlation is −0.11, because the impossible questions are both shorter (7.5 words against 11.4) and much harder (0.34 correct against 0.70), which pulls the other way. What the text *says* matters more than its length: the flag for an impossible question explains 23% of the variance in logit proportion correct, word count 1%. Now the LLTM with an item residual, the text features as item predictors:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The LLTM with an item residual (from \"What is an item?\"), with text features as the\n# item predictors: logit P(correct) = theta_j + beta_0 + features + epsilon_i. The item\n# residual's variance, with and without the features, says how much of the variation\n# in difficulty they explain. nAGQ = 0 keeps each fit to seconds.\nd <- merge(iq, items[, c(\"item\", \"word_count\", \"impossible\")], by = \"item\")\nd$words_z <- (d$word_count - mean(items$word_count)) / sd(items$word_count)\nm0 <- glmer(resp ~ 1 + (1 | id) + (1 | item), family = binomial, data = d, nAGQ = 0)\nm1 <- glmer(resp ~ words_z + (1 | id) + (1 | item), family = binomial, data = d, nAGQ = 0)\nm2 <- glmer(resp ~ words_z + impossible + (1 | id) + (1 | item), family = binomial, data = d, nAGQ = 0)\nsds <- sapply(list(none = m0, word_count = m1, word_count_and_flag = m2), function(m) {\n  v <- as.data.frame(VarCorr(m)); setNames(v$sdcor, v$grp)[c(\"item\", \"id\")] })\nround(rbind(sds, share_of_item_variance_explained = 1 - sds[\"item\", ]^2 / sds[\"item\", \"none\"]^2), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                  none word_count word_count_and_flag\nitem                             1.709      1.698               1.420\nid                               0.466      0.466               0.466\nshare_of_item_variance_explained 0.000      0.014               0.310\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(fixef(m2), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)     words_z  impossible \n       1.38       -0.40       -2.28 \n```\n\n\n:::\n:::\n\n\nItems differ far more than respondents (SD 1.71 against 0.47 for $\\theta$). Word count explains 1.4% of the item variance; adding the impossible flag, 31%, leaving a residual SD of 1.42. What is that worth?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# What is each prediction worth, in respondents? One respondent carries E[p(1 - p)]\n# units of information about an item's location (Rasch model, theta ~ N(0, sd_theta));\n# a prediction with error SD sigma is as good as a calibration on\n# n* = 1 / (sigma^2 * E[p(1 - p)]) respondents. E[p(1 - p)] is averaged over items at\n# the locations each model predicts.\nepq <- function(loc, sd_theta) integrate(function(t)\n  plogis(loc + t) * (1 - plogis(loc + t)) * dnorm(t, 0, sd_theta), -Inf, Inf)$value\nworth <- function(m) {\n  v <- as.data.frame(VarCorr(m)); sigma <- v$sdcor[v$grp == \"item\"]; sd_theta <- v$sdcor[v$grp == \"id\"]\n  loc <- unique(model.matrix(m) %*% fixef(m))\n  info <- mean(sapply(loc, epq, sd_theta = sd_theta))\n  c(sigma = sigma, info_per_respondent = info, respondents_worth = 1 / (sigma^2 * info))\n}\nround(sapply(list(none = m0, word_count = m1, word_count_and_flag = m2), worth), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    none word_count word_count_and_flag\nsigma               1.71       1.70                1.42\ninfo_per_respondent 0.20       0.21                0.18\nrespondents_worth   1.73       1.69                2.69\n```\n\n\n:::\n:::\n\n\nKnowing only that an item belongs to this test is worth about 1.7 respondents: that is the prior. Word count adds nothing; with the impossible flag, the prediction is worth 2.7. By my yardstick, what the text says about these items is worth about one respondent. Questions of the same kind still differ by 1.42 logits for reasons these features don't see.\n\nThe table holds one more check. Twelve of the impossible questions, on the two generated forms, were written by ChatGPT for this study; the six on the anchor form come from the original bank ([Himmelstein et al., 2025](https://doi.org/10.31234/osf.io/a7kdx_v8)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Six impossible questions are from the original item bank (the anchor form); the\n# twelve on the two generated forms were written by ChatGPT for this study.\niqs <- items[items$impossible == 1, ]\niqs$written_by <- ifelse(iqs$aig_version == \"anchor\", \"original bank\", \"ChatGPT\")\naggregate(cbind(p, word_count) ~ written_by, data = iqs, FUN = function(v) round(mean(v), 2))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|written_by    |    p| word_count|\n|:-------------|----:|----------:|\n|ChatGPT       | 0.34|       7.58|\n|original bank | 0.32|       7.33|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\niqs[order(iqs$written_by, iqs$p), c(\"item\", \"written_by\", \"question_text\", \"p\")]\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    |item  |written_by    |question_text                                                            |         p|\n|:---|:-----|:-------------|:------------------------------------------------------------------------|---------:|\n|196 |IQ_18 |ChatGPT       |The Diflective Assumption Theory helps us understand:                    | 0.2447552|\n|205 |IQ_16 |ChatGPT       |What's the side effect of Grilpax's disease?                             | 0.2732049|\n|190 |IQ_15 |ChatGPT       |What's the habitat of a Rojixon bird?                                    | 0.2827225|\n|125 |IQ_7  |ChatGPT       |When did the Laikrev Uprising occur?                                     | 0.3211921|\n|199 |IQ_17 |ChatGPT       |What is the Kraghold method used for?                                    | 0.3222997|\n|139 |IQ_12 |ChatGPT       |How does Binoxelation Impact Theory explain the growth of crystals?      | 0.3382838|\n|129 |IQ_11 |ChatGPT       |What does the Veklin Procedure involve?                                  | 0.3603306|\n|149 |IQ_9  |ChatGPT       |What is the speed of a Blargan Horse?                                    | 0.3698176|\n|145 |IQ_8  |ChatGPT       |What is the nutritional value of a Golgrest Fruit?                       | 0.3904448|\n|185 |IQ_13 |ChatGPT       |What are the ingredients of a traditional Zibrune stew?                  | 0.3937282|\n|210 |IQ_14 |ChatGPT       |What's the main purpose of a Tantrigon device?                           | 0.3989547|\n|147 |IQ_10 |ChatGPT       |What is the cure for Zolbrod's syndrome?                                 | 0.4347107|\n|4   |IQ_6  |original bank |Resistance Configuration Theory is a psychological theory that explains: | 0.1922078|\n|24  |IQ_2  |original bank |How many sides does a Detseroid have?                                    | 0.2724167|\n|8   |IQ_5  |original bank |What is the Parlichev method?                                            | 0.3466780|\n|19  |IQ_4  |original bank |What is the most prominent symptom of Seradot's disease?                 | 0.3634812|\n|7   |IQ_1  |original bank |When did the battle of Kavkav take place?                                | 0.3810742|\n|1   |IQ_3  |original bank |What is the population of Synomle?                                       | 0.3858603|\n\n</div>\n:::\n:::\n\n\nChatGPT's impossible questions are opted out of 34% of the time, the originals 32%, with similar lengths: the generated items behave like the ones they were written to match, the anchor-form check the study used for exchangeability.\n\n### GPT-4's multiple-choice items\n\n[Young, Courtney, Kah, Wilkerson and Chen (2025)](https://doi.org/10.1177/00986283241311220) gave GPT-4 a textbook chapter on love, friendship and social support and asked for 20 multiple-choice items, which 190 undergraduates answered after reading it. The items (CC BY 4.0) come from the [OSF deposit](https://osf.io/zq4eg/). Keying: `resp` is the option chosen, and option 1 is the key on every item, which the IRW confirmed against the published proportions correct.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(haven)\nsuppressPackageStartupMessages(library(mirt))\nmcq_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.gpt4mcq_young_2025/rows?format=csv\"\nmcq <- read.csv(mcq_url)\n# resp is the option chosen, 1 to 4; option 1 is the key on every item.\nwide <- tapply(mcq$resp, list(mcq$id, mcq$item), function(v) v[1])[, paste0(\"AIQ\", 1:20)]\nc(respondents = nrow(wide), missing = sum(is.na(wide)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents     missing \n        190           0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The items, from the SPSS labels in the authors' OSF deposit (osf.io/zq4eg, file\n# version 1): stems in the variable labels, options in the value labels.\nsav_file <- tempfile(fileext = \".sav\")\ndownload.file(\"https://osf.io/download/bj3gc/?version=1\", sav_file, mode = \"wb\", quiet = TRUE)\nsav <- read_sav(sav_file)\nstem <- sapply(colnames(wide), function(v) attr(sav[[v]], \"label\"))\nopts <- lapply(colnames(wide), function(v) { l <- attr(sav[[v]], \"labels\"); names(l)[order(l)] })\nkey_len <- sapply(opts, function(o) nchar(o[1])); dis_len <- sapply(opts, function(o) max(nchar(o[-1])))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nkey <- (wide == 1) * 1\nmcq_items <- data.frame(item = colnames(wide), stem = unname(stem), key = sapply(opts, `[`, 1),\n                        p = round(colMeans(key), 3), key_is_longest = key_len > dis_len)\nknitr::kable(mcq_items[, c(\"item\", \"stem\", \"key\", \"p\")], row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|item  |stem                                                                                                         |key                                                                                             |     p|\n|:-----|:------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------|-----:|\n|AIQ1  |Which factor is NOT listed as influencing attraction between people according to psychological research?     |Financial status                                                                                | 0.916|\n|AIQ2  |According to Durkheim, what is a crucial factor for personal well-being and potentially preventing suicide?  |Being socially connected                                                                        | 0.889|\n|AIQ3  |How does the Internet and social media influence the development of relationships, according to the chapter? |By providing a virtual space where people can meet and develop deep connections                 | 0.816|\n|AIQ4  |What does Sternberg's Triangular Theory of Love suggest about the components of love?                        |Love is comprised of intimacy, passion, and commitment                                          | 0.926|\n|AIQ5  |Which of the following is NOT a conceptual component of social support?                                      |Financial assistance                                                                            | 0.911|\n|AIQ6  |How does familiarity affect attraction, according to psychological research?                                 |Repeated exposure to someone increases the likelihood of attraction                             | 0.937|\n|AIQ7  |What role does reciprocity play in the formation of friendships and romantic relationships?                  |We are more likely to like someone if they show that they like us in return                     | 0.932|\n|AIQ8  |According to research, how does having close friendships affect individuals during difficult times?          |Close friendships can buffer individuals from stress and protect their self-esteem              | 0.932|\n|AIQ9  |What does Helen Fisher's research on brain chemistry in individuals who have just fallen in love suggest?    |Brain chemistry resembles that of an addict experiencing a high                                 | 0.926|\n|AIQ10 |How does perceived social support influence well-being?                                                      |Believing that others will be available in times of need can increase happiness and well-being  | 0.889|\n|AIQ11 |Why are online relationships sometimes considered more intimate than in-person relationships?                |They offer a safe space for more socially anxious individuals to develop meaningful connections | 0.889|\n|AIQ12 |How does the matching hypothesis explain attraction?                                                         |People are attracted to others who are similar to them in various attributes                    | 0.926|\n|AIQ13 |What impact does workplace friendship have on employees' attitudes towards their job?                        |Increases job satisfaction, job involvement, and organizational commitment                      | 0.947|\n|AIQ14 |What is a significant benefit of having a diverse social network?                                            |Less likely to get the common cold compared to those with less diverse networks                 | 0.679|\n|AIQ15 |How does the Internet change the dynamic of forming relationships, according to the chapter?                 |It reduces issues of proximity and allows for communication across distances                    | 0.832|\n|AIQ16 |According to Baumeister and Leary, what is a fundamental human need?                                         |The need to belong                                                                              | 0.926|\n|AIQ17 |What does the mere-exposure effect suggest about attraction?                                                 |We are more likely to be attracted to someone we are frequently exposed to                      | 0.937|\n|AIQ18 |What does research say about the importance of similarity in friendships and romantic relationships?         |Similarity in values, attitudes, and interests plays a key role in forming strong relationships | 0.937|\n|AIQ19 |What role does received social support play in an individual's life, according to the chapter?               |It can buffer people from stress but may not always be viewed as helpful if it is unwanted      | 0.500|\n|AIQ20 |How does Sternberg's model differentiate between types of love?                                              |By identifying different combinations of intimacy, passion, and commitment present in each type | 0.868|\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nc(median_p = median(mcq_items$p), key_longest = sum(mcq_items$key_is_longest))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   median_p key_longest \n      0.921      12.000 \n```\n\n\n:::\n:::\n\n\nThe items are easy for students who had just read the chapter: the median proportion correct is 0.92. The key is the longest option in 12 of the 20 items, a cue that item-writing guidelines advise against ([Haladyna, Downing & Rodriguez, 2002](https://doi.org/10.1207/S15324818AME1503_5)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Share of respondents choosing each option; rows 2-4 are the distractors.\nshares <- sapply(1:20, function(i) prop.table(table(factor(wide[, i], levels = 1:4))))\ncolnames(shares) <- colnames(wide)\nround(shares[, c(\"AIQ1\", \"AIQ14\", \"AIQ19\")], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   AIQ1 AIQ14 AIQ19\n1 0.916 0.679 0.500\n2 0.016 0.084 0.453\n3 0.042 0.163 0.011\n4 0.026 0.074 0.037\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ndis <- shares[2:4, ]\nc(distractors = length(dis), chosen_by_under_5_percent = sum(dis < 0.05), chosen_by_nobody = sum(dis == 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              distractors chosen_by_under_5_percent          chosen_by_nobody \n                       60                        48                         2 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nopts[[19]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"It can buffer people from stress but may not always be viewed as helpful if it is unwanted\"\n[2] \"Received social support has universally positive effects on individuals\"                   \n[3] \"It has no significant impact on stress levels or well-being\"                               \n[4] \"Received support is less important than perceived support in coping with stress\"           \n```\n\n\n:::\n:::\n\n\nOf the 60 distractors, 48 are chosen by fewer than 5% of students and 2 by nobody, as in the widget's easy item. The exception is AIQ19, on received social support: 45% chose \"Received social support has universally positive effects on individuals\", a distractor that works.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Reliability and item parameters. Alpha as in \"Classical test theory\"; then the 2PL,\n# with mirt's intercept d converted to a difficulty, b = -d / a.\nalpha <- function(x) { k <- ncol(x); k / (k - 1) * (1 - sum(apply(x, 2, var)) / var(rowSums(x))) }\ntable(sum_score = rowSums(key))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsum_score\n 0  3  4  5  7  8 10 11 12 13 14 15 16 17 18 19 20 \n 1  1  2  1  1  3  2  2  1  5  8  6  9 11 33 45 59 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nset.seed(55)\nfit2 <- mirt(as.data.frame(key), 1, itemtype = \"2PL\", verbose = FALSE)\ncf <- coef(fit2, simplify = TRUE)$items\nb <- -cf[, \"d\"] / cf[, \"a1\"]\nround(c(alpha = alpha(key), median_b = median(b), min_b = min(b), max_b = max(b)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   alpha median_b    min_b    max_b \n    0.89    -1.64    -2.88     0.00 \n```\n\n\n:::\n:::\n\n\nAlpha is 0.89, yet 59 of the 190 students answered every item correctly. The alpha comes largely from the few who missed many items, and the 2PL difficulties (median −1.64) sit well below the average student. The test separates students who struggled with the chapter from the rest, which suits a check on reading, the use the authors recommend.\n\n### GPT-4o's personality items\n\n[Russell-Lasalandra, Christensen and Golino (2024)](https://doi.org/10.31234/osf.io/fgbj4) generated Big Five items with GPT-4o through AI-GENIE and gave the 35 that survived to a nationally representative US sample; items and traits come from their [OSF deposit](https://osf.io/zcytb/) (CC0). Keying: 1 is strongly disagree and 5 strongly agree, and every item is worded toward its trait.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nb5_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.genpsych_russell_2024_gpt4o/rows?format=csv\"\nb5 <- read.csv(b5_url)\n# resp runs from 1 (strongly disagree) to 5 (strongly agree). The items, and the trait\n# each was written for, from the authors' OSF deposit (osf.io/zcytb, file version 1),\n# in the same order as items_1 to items_35.\nb5_items <- read.csv(\"https://osf.io/download/k7e5t/?version=1\")\nb5_items$item <- paste0(\"items_\", seq_len(nrow(b5_items)))\nw5 <- tapply(b5$resp, list(b5$id, b5$item), function(v) v[1])[, b5_items$item]\nc(respondents = nrow(w5), complete = sum(complete.cases(w5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents    complete \n        999         897 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nw5 <- w5[complete.cases(w5), ]\ntable(trait = b5_items$characteristic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntrait\n    agreeableness conscientiousness      extraversion       neuroticism \n                7                 8                 5                 8 \n         openness \n                7 \n```\n\n\n:::\n:::\n\n\nWe keep the 897 respondents who answered every item. Does each item go with its trait? Each item's correlation with the sum of the *other* items of each trait:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Does each item go with the trait it was written for? Correlate it with the sum of\n# the other items of each trait (its own trait's sum leaves it out).\ntrait <- b5_items$characteristic\ntraits <- unique(trait)\nir <- t(sapply(seq_len(ncol(w5)), function(i) sapply(traits, function(t) {\n  cols <- setdiff(which(trait == t), i); cor(w5[, i], rowSums(w5[, cols, drop = FALSE])) })))\nown <- ir[cbind(seq_along(trait), match(trait, traits))]\nother <- sapply(seq_along(trait), function(i) max(ir[i, traits != trait[i]]))\nc(items_closest_to_own_trait = sum(own > other), items = length(own))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nitems_closest_to_own_trait                      items \n                        35                         35 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(median_own = median(own), median_best_other = median(other)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       median_own median_best_other \n             0.60              0.21 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nb5_items[which.min(own - other), c(\"item\", \"characteristic\", \"item_content\")]\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |item     |characteristic |item_content                                                  |\n|:--|:--------|:--------------|:-------------------------------------------------------------|\n|32 |items_32 |openness       |I love experimenting with new recipes and cooking techniques. |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(ir[which.min(own - other), ], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    agreeableness conscientiousness      extraversion       neuroticism \n             0.31              0.13              0.23             -0.07 \n         openness \n             0.34 \n```\n\n\n:::\n:::\n\n\nAll 35 items correlate most with their own trait (median 0.60, against 0.21 for the closest other trait). The narrowest margin is \"I love experimenting with new recipes and cooking techniques\", written for openness: 0.34 with openness, 0.31 with agreeableness.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Alpha for each trait's items, and the mean correlation among them.\nt(sapply(traits, function(t) { x <- w5[, trait == t]; r <- cor(x)\n  round(c(items = ncol(x), alpha = alpha(x), mean_r = mean(r[upper.tri(r)])), 2) }))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  items alpha mean_r\nagreeableness         7  0.77   0.33\nconscientiousness     8  0.83   0.38\nextraversion          5  0.85   0.54\nneuroticism           8  0.93   0.61\nopenness              7  0.77   0.34\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nb5_items$item_content[b5_items$characteristic == \"neuroticism\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"I frequently worry about small things.\"                     \n[2] \"I often find myself feeling anxious without a clear reason.\"\n[3] \"I often feel overwhelmed by my emotions.\"                   \n[4] \"I frequently experience sudden mood changes.\"               \n[5] \"I frequently feel sad or down for no specific reason.\"      \n[6] \"I find myself getting upset easily over minor issues.\"      \n[7] \"I often feel tense or stressed.\"                            \n[8] \"I frequently feel nervous about the future.\"                \n```\n\n\n:::\n:::\n\n\nThe eight neuroticism items reach alpha 0.93 with a mean correlation of 0.61, and read almost as rewordings of each other. High homogeneity can mean items that repeat one another rather than a broad construct measured well ([Boyle, 1991](https://doi.org/10.1016/0191-8869(91)90115-R)).\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd): items worded against the construct have to be reverse-keyed. Here no item is: keying is easy, and a respondent's tendency to agree is mixed into every trait score. **If you've done** [From construct map to items](instrument-building.qmd), that is the all-forward scale whose alpha rose with acquiescence.\n:::\n\nEach set of machine-written items needed the usual checks, and each turned something up. A machine-written item is still an item.\n\n## Problems\n\n1. **QWK from a table.** Show that QWK $= 1 - \\sum w_{ik}O_{ik}/\\sum w_{ik}E_{ik}$ with weights $(i-k)^2$ equals $2\\sigma_{XY}/(\\sigma_X^2 + \\sigma_Y^2 + (\\mu_X - \\mu_Y)^2)$. With two categories, show that it equals Cohen's kappa.\n2. **Without the impossible questions.** Drop the 18 impossible questions and refit the LLTM with word count and mean word length. What do they explain, and what is the prediction worth? Code a feature of your own from the text (true–false or not, say) and test it.\n3. **A 2PL for GPT-4's items.** Plot the 2PL test information for `gpt4mcq_young_2025`. Where is it informative? Which three items would you ask the writer to make harder, and how?\n4. **Judgment.** A vendor's engine agrees with human raters at QWK 0.80 on your essays; two humans agree at 0.72. What else do you need before it replaces the second rater?\n5. **Design.** Design a study of whether difficulties predicted by a language model could replace a state's field test of new reading items. What result would convince you?\n6. **Challenge (open): models as respondents.** A hundred language models answer a thousand benchmark questions. What would \"ability\" mean for a model, and which assumption is likeliest to fail: local independence (models trained on overlapping data), one dimension, or something else? I don't know the answer.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22AI%20and%20psychometrics%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20how%20AI%20and%20psychometrics%20meet%3A%20judging%20automated%20scoring%20engines%20by%20their%20agreement%20with%20human%20raters%20%28exact%20agreement%2C%20Cohen%27s%20kappa%2C%20quadratic%20weighted%20kappa%20and%20what%20agreement%20can%27t%20show%29%3B%20predicting%20item%20difficulty%20from%20item%20text%20with%20the%20linear%20logistic%20test%20model%20and%20converting%20a%20prediction%27s%20error%20into%20the%20number%20of%20respondents%20it%20is%20worth%3B%20language%20models%20as%20simulated%20respondents%3B%20and%20checking%20items%20written%20by%20language%20models%20%28difficulty%2C%20distractors%2C%20keying%2C%20whether%20items%20go%20with%20their%20construct%29%2C%20with%20general-knowledge%20and%20impossible%20questions%2C%20GPT-4-written%20multiple-choice%20items%20and%20GPT-4o-written%20Big%20Five%20items%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Across the IRW\n\nCan item text predict difficulty across the IRW? [`compute.R`](https://github.com/ben-domingue/irw-course/blob/main/deepdives/ai-psychometrics/compute.R) takes each English dichotomous cognitive table with at least 200 respondents and item text in the IRW, and correlates word count and mean word length with the logit of proportion correct *within* the table. Pooling items across tables would confound an item's length with the test it came from. No feature from a language model is used yet.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Constructs and construct maps](constructs.qmd): of the nine number-series items, NS_2 was solved by 84% of those who answered it and NS_6, whose key accepts 165 where tripling the steps gives 120, by 1.5%. The corpus run includes that table to check its own pipeline.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndd_path <- file.path(\"..\", \"deepdives\", \"ai-psychometrics\", \"results.rds\")\ndd <- if (file.exists(dd_path)) readRDS(dd_path) else NULL\nif (!is.null(dd)) {\n  ns <- dd$items[dd$items$table == \"himmelstein-number_series-2025\", ]\n  print(round(setNames(ns$p, ns$item)[c(\"NS_2\", \"NS_6\")], 3))   # the pipeline check\n  s <- dd$summary[order(dd$summary$r_word_count), ]\n  print(data.frame(table = s$table, items = s$n_items, median_p = round(s$median_p, 2),\n                   r_word_count = round(s$r_word_count, 2), r_word_length = round(s$r_word_length, 2)),\n        row.names = FALSE)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n NS_2  NS_6 \n0.839 0.015 \n                                table items median_p r_word_count r_word_length\n                    preschool_sel_box    20     0.59        -0.62         -0.40\n                rmet_higgins_2022_tom    16     0.55        -0.17          0.15\n himmelstein-impossible_question-2025    90     0.63        -0.11          0.15\n       himmelstein-number_series-2025     9     0.48         0.07         -0.23\n             gcbs_brotherton_2013_vcl    16     0.86           NA         -0.40\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Partial run: 5 of 33 tables\n\nThis is a pilot run of `compute.R`, on three tables whose answers are known (the number series, this lesson's impossible questions, and `preschool_sel_box`, the IRW vignette's strongest case) and 3 drawn at random, to check the pipeline. The full run replaces it.\n:::\n\nRun on 25 September 2026: 5 tables summarised, 1 failed (`polca_cheating`: fewer than 5 items with both responses and text). Within-table correlations of word count with logit proportion correct run from -0.62 to 0.07 (median -0.14).\n\nThe pipeline reproduces the number-series proportions. In this pilot the correlations for word count are small, except for the preschool task at −0.62; the full run will show how they spread across all the candidate tables. The IRW's [item language and difficulty](https://itemresponsewarehouse.org/vignettes/item_text_difficulty.html) vignette runs the same analysis with a plot for each table.\n\n## Going further\n\n- Kapoor, R., Truong, S. T., Haber, N., Ruiz-Primo, M. A., & Domingue, B. W. (2025). Prediction of item difficulty for reading comprehension items by creation of annotated item repository. arXiv:2502.20663. <https://arxiv.org/abs/2502.20663>. Difficulty predicted from annotated features and language-model embeddings, for state reading items.\n- Benedetto, L., Cremonesi, P., Caines, A., Buttery, P., Cappelli, A., Giussani, A., & Turrin, R. (2023). A survey on recent approaches to question difficulty estimation from text. *ACM Computing Surveys*, 55(9), 1–37. <https://doi.org/10.1145/3556538>. The methods for predicting difficulty from text, sorted by the kind of question.\n- Gorin, J. S., & Embretson, S. E. (2006). Item difficulty modeling of paragraph comprehension items. *Applied Psychological Measurement*, 30(5), 394–411. <https://doi.org/10.1177/0146621606288554>. Difficulty explained by a cognitive model of the items.\n- Stenner, A. J., Burdick, H., Sanford, E. E., & Burdick, D. S. (2006). How accurate are Lexile text measures? *Journal of Applied Measurement*, 7(3), 307–322. <https://pubmed.ncbi.nlm.nih.gov/16807496/>. How precisely a readability framework measures texts.\n- Liu, Y., Bhandari, S., & Pardos, Z. A. (2025). Leveraging LLM respondents for item evaluation: A psychometric analysis. *British Journal of Educational Technology*, 56(3), 1028–1052. <https://doi.org/10.1111/bjet.13570>. Language models as respondents, judged against students.\n- Argyle, L. P., Busby, E. C., Fulda, N., Gubler, J. R., Rytting, C., & Wingate, D. (2023). Out of one, many: Using language models to simulate human samples. *Political Analysis*, 31(3), 337–351. <https://doi.org/10.1017/pan.2023.2>. Simulated survey respondents conditioned on real backgrounds.\n- Scarlatos, A., Fernandez, N., Ormerod, C., Lottridge, S., & Lan, A. (2025). SMART: Simulated students aligned with item response theory for question difficulty prediction. arXiv:2507.05129. <https://arxiv.org/abs/2507.05129>. Simulated students trained to follow an item response model.\n- Williamson, D. M., Xi, X., & Breyer, F. J. (2012). A framework for evaluation and use of automated scoring. *Educational Measurement: Issues and Practice*, 31(1), 2–13. <https://doi.org/10.1111/j.1745-3992.2011.00223.x>. The kinds of evidence an automated scorer needs.\n- Lewis, J., & Casabianca, J. M. (2026). Limitations of QWK in evaluating automated and human scoring systems. *Educational Measurement: Issues and Practice*, 45(1). <https://doi.org/10.1111/emip.70017>. How QWK depends on the margins and the length of the scale.\n- McCaffrey, D. F., Casabianca, J. M., & Johnson, M. S. (2025). Measuring the accuracy of true score predictions for AI scoring evaluation. *Journal of Educational Measurement*, 62(4), 763–786. <https://doi.org/10.1111/jedm.70011>. PRMSE as an alternative to QWK.\n- Alvero, A. J., Giebel, S., Gebre-Medhin, B., Antonio, A. L., Stevens, M. L., & Domingue, B. W. (2021). Essay content and style are strongly related to household income and SAT scores: Evidence from 60,000 undergraduate applications. *Science Advances*, 7(42), eabi9031. <https://doi.org/10.1126/sciadv.abi9031>. What essays carry besides writing quality.\n- Attali, Y., & Burstein, J. (2006). Automated essay scoring with e-rater V.2. *Journal of Technology, Learning, and Assessment*, 4(3). <https://ejournals.bc.edu/index.php/jtla/article/view/1650>. An automated essay scorer, described by its developers.\n- Embretson, S. E. (1999). Generating items during testing: Psychometric issues and models. *Psychometrika*, 64(4), 407–433. <https://doi.org/10.1007/BF02294564>. Items generated from a cognitive design, and models that calibrate the design.\n- Gierl, M. J., & Haladyna, T. M. (Eds.). (2012). *Automatic item generation: Theory and practice*. Routledge. <https://doi.org/10.4324/9780203803912>. Item models and templates.\n- Russell-Lasalandra, L. L., Christensen, A. P., & Golino, H. (2024). Generative psychometrics via AI-GENIE: Automatic item generation with network-integrated evaluation. PsyArXiv. <https://doi.org/10.31234/osf.io/fgbj4>. Items from language models, pruned by network psychometrics.\n- Haladyna, T. M., & Downing, S. M. (1993). How many options is enough for a multiple-choice test item? *Educational and Psychological Measurement*, 53(4), 999–1010. <https://doi.org/10.1177/0013164493053004013>. How often distractors perform.\n- Martínez-Plumed, F., Prudêncio, R. B. C., Martínez-Usó, A., & Hernández-Orallo, J. (2019). Item response theory in AI: Analysing machine learning classifiers at the instance level. *Artificial Intelligence*, 271, 18–42. <https://doi.org/10.1016/j.artint.2018.09.004>. Psychometrics turned on AI systems.\n- From the IRW: the [item language and difficulty](https://itemresponsewarehouse.org/vignettes/item_text_difficulty.html) vignette, which this lesson's deep dive follows.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`himmelstein-impossible_question-2025`](https://itemresponsewarehouse.org/tables/himmelstein-impossible_question-2025/): Himmelstein, Mark, Sophie Ma Zhu, Nikolay Petrov, Ezra Karger, Jessica Helmer, Sivan Livnat, Amory Bennett, Page Hedley, and Phil Tetlock. “The Forecasting Proficiency Test: A General Use Assessment of Forecasting Ability”. PsyArXiv, November 23, 2025. doi:10.31234/osf.io/a7kdx_v8. <https://doi.org/10.31234/osf.io/a7kdx_v8>. Licence: CC BY 4.0.\n- [`gpt4mcq_young_2025`](https://itemresponsewarehouse.org/tables/gpt4mcq_young_2025/): Young, R., Courtney, E., Kah, A., Wilkerson, M., & Chen, Y.-H. (2025). Content and Item Response Theory Analysis of ChatGPT-4-Generated Multiple-Choice Items. Teaching of Psychology, 0(0). <https://doi.org/10.1177/00986283241311220>. Licence: CC BY 4.0.\n- [`genpsych_russell_2024_gpt4o`](https://itemresponsewarehouse.org/tables/genpsych_russell_2024_gpt4o/): Russell-Lasalandra, L. L., Christensen, A. P., & Golino, H. (2024, September 12). Generative Psychometrics via AI-GENIE: Automatic Item Generation and Validation via Network-Integrated Evaluation. <https://doi.org/10.31234/osf.io/fgbj4>. Licence: CC0 1.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 10 (slides c10, 1–41: the two intersections, automated scoring and QWK, simulated respondents, item difficulty modelling, automatic item generation) and `c10/model.R` in `ben-domingue/252`.\n- **Timing:** the core ideas and widgets take about 50 minutes; the real-data section is a 30-minute lab. The three `glmer` fits take about a minute in local R.\n- **Changed from 252:** the slides' automated-scoring evidence is a widget, since no IRW table pairs human and engine scores. The slides' remark on prediction metrics is worked out as the respondents yardstick and applied to the impossible questions. The meta-analysis QWK of about 0.8 (slides 7 and 16) and the human–human QWK of 0.60 (slide 17) are left out until their sources are verified. The slides' state reading-item project is cited (Kapoor et al., 2025); their ENEM project and AI-generated reading-efficiency forms (slides 37–41) are left out.\n- **Held back:** rater effects for human and machine raters ([Rater models](rater-models.qmd)); distractor analysis with the nominal model ([Nominal response and multiple-choice models](nominal.qmd)); predicted difficulties for new items in a bank ([Item banks and adaptive testing](item-banks-cat.qmd)); differential functioning of machine scores. Models as respondents is problem 6.\n- **Across the IRW:** `deepdives/ai-psychometrics/compute.R` is run by hand (it needs a Redivis token); the page reads its `results.rds`. The pilot took under a minute for six tables.\n- **Solutions:** held back in `solutions/ai-psychometrics.qmd` (not published). Problem 6 is open.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}