{
  "hash": "b1d60e14f0b63c92cc4a76a48e65bd4e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Gathering validity evidence\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Validity  \n**Tranche:** core (a first course)  \n**Before this:** [Validity as an argument](validity-argument.qmd) · [Classical test theory and reliability](ctt-reliability.qmd) · [From construct map to items: building an instrument](instrument-building.qmd)  \n**Builds toward:** none  \n**Picks up threads:** Unreliability attenuates correlations (from [Classical test theory and reliability](ctt-reliability.qmd)); A criterion built from the same items inflates validity evidence (from [Validity as an argument](validity-argument.qmd))  \n**IRW tables:** [`de_vries_2022_hexaco_self`](https://itemresponsewarehouse.org/tables/de_vries_2022_hexaco_self/), [`de_vries_2022_hexaco_other`](https://itemresponsewarehouse.org/tables/de_vries_2022_hexaco_other/), [`ieswriting_molloy_2022`](https://itemresponsewarehouse.org/tables/ieswriting_molloy_2022/)  \n**From EDUC 252:** n/a  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n```{ojs}\n//| echo: false\nimport {palette, grid, dnorm} from \"./widgets/irt.js\"\nimport {mtmm, restrictSample, binormal, rocCurve} from \"./widgets/validity-evidence.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nA writing survey given to college students has a confidence scale with an alpha of 0.95, and its scores correlate 0.07 with the students' course grades. Is the scale failing? That depends on what it is for. [Validity as an argument](validity-argument.qmd) laid out the chain of inferences from responses to a use and which evidence backs each link. This lesson gathers the evidence, mostly the kind that needs outside data. We read a multitrait–multimethod matrix of self- and colleague ratings, ask how far a criterion correlation can be trusted when the measures are unreliable or the sample selected, and measure classification against a criterion that doesn't borrow from the test.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- match a source of validity evidence to the inference it backs;\n- read a multitrait–multimethod matrix with Campbell and Fiske's comparisons, and say what a failed comparison means;\n- compute criterion and incremental validity, and bound a validity coefficient by reliability;\n- say how selection shrinks a validity coefficient, correct it with Thorndike's case II, and state what the correction assumes;\n- compute sensitivity, specificity and the positive predictive value, and say why the base rate and an independent criterion matter.\n\n## Core ideas\n\n### Which evidence, for which inference?\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Validity as an argument](validity-argument.qmd): the *Standards* list five sources of validity evidence, and each tends to back one link of the interpretation/use argument: test content and response processes back scoring, internal structure backs generalization, relations to other variables back extrapolation, and consequences back the decision.\n:::\n\nThe sources are described in chapter 1 of the *Standards* ([AERA, APA & NCME, 2014, pp. 13–21](https://www.testingstandards.net/open-access-files.html); open access). Evidence goes where the inference is most in doubt.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [From construct map to items](instrument-building.qmd): review by content experts and cognitive interviews come before any pilot, and they catch what an item analysis can't, such as an item that everyone misreads in the same way.\n:::\n\n**Content evidence** is that review, written down: judges independent of the item writers rate how well each item matches the blueprint cell or map level it was written for, and whether the items together cover the domain ([Sireci & Faulkner-Bond, 2014](https://doi.org/10.7334/psicothema2013.256)). It needs no response data. Cognitive interviews provide **response-process evidence**.\n\n**Internal-structure evidence** asks whether the relations among items match what the construct predicts ([Rios & Wells, 2014](https://doi.org/10.7334/psicothema2013.260)). In [Constructs and construct maps](constructs.qmd), a map's levels ordered nine number-series items before any data, with a rank correlation of −0.76 against their proportions correct. A test built for one dimension predicts one factor; a test with subscales predicts more.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Factor analysis I](fa-exploratory.qmd) and [Factor analysis II](fa-confirmatory.qmd): those lessons test such predictions. The DASS-21, written as three scales, had one general factor behind most of its total score's reliable variance (omega hierarchical 0.88): internal-structure evidence about whether three subscale scores are worth reporting.\n:::\n\nThe rest of this lesson is about **relations to other variables**: with measures of the same construct and of different constructs, and with criteria the scores should predict ([AERA, APA & NCME, 2014, pp. 16–18](https://www.testingstandards.net/open-access-files.html)).\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Before a new reading test is piloted, two teachers who didn't write the items independently assign each item to the blueprint cell they think it measures, and agree with the writers' assignments for 45 of 50 items. What kind of evidence is this?\",\n  options: [\n    {text: \"Content evidence, backing the claim that the items measure what they were written for and represent the blueprint's domain\", correct: true, why: \"Judges checking items against the blueprint is content evidence. It backs scoring and, for a claim about a domain, extrapolation from the items to the domain.\"},\n    {text: \"Internal-structure evidence, backing generalization\", correct: false, why: \"Internal structure is about the relations among responses to the items. No one has answered the items yet.\"},\n    {text: \"Evidence of relations to other variables, backing extrapolation\", correct: false, why: \"That needs scores and some outside measure: another reading test, grades, a later outcome. Here there are only judgments about the items.\"}\n  ]\n})\n```\n\n### Convergent and discriminant evidence\n\nA score should agree with other measures of the same trait (**convergent** evidence) and less with measures of different traits (**discriminant** evidence). [Campbell and Fiske (1959)](https://doi.org/10.1037/h0046016) saw a catch: two measures can agree because they share a *method*, such as the respondent's way of describing themselves or one colleague's overall impression. So they measured several traits by several methods and laid out every correlation in a **multitrait–multimethod (MTMM) matrix**, whose cells come in three kinds:\n\n- **validity values**: the same trait, measured by different methods;\n- **heterotrait–heteromethod** values: different traits, different methods;\n- **heterotrait–monomethod** values: different traits, the same method.\n\nCampbell and Fiske asked for four things. Validity values clearly above zero. Each larger than the heterotrait–heteromethod values in its row and column. Each larger than the heterotrait–monomethod values for its trait, or else the method may be doing the agreeing. And a similar pattern of trait correlations within every method and across methods.\n\n#### Try it: build a matrix\n\nThree traits, each measured by self-report and by a colleague's rating, all with the same reliability. A share of each score's reliable variance comes from its method (a style of describing oneself, a colleague's general liking). The heat map is the implied correlation matrix, with the validity values outlined.\n\n```{ojs}\n//| echo: false\nviewof mm_rel = Inputs.range([0.5, 0.95], {value: 0.8, step: 0.05, label: \"Reliability of every score\"})\nviewof mm_phi12 = Inputs.range([0, 0.8], {value: 0.1, step: 0.05, label: \"Correlation of traits 1 and 2\"})\nviewof mm_phi = Inputs.range([0, 0.8], {value: 0.1, step: 0.05, label: \"Correlation of the other trait pairs\"})\nviewof mm_s1 = Inputs.range([0, 0.8], {value: 0.3, step: 0.05, label: \"Method share, self-report\"})\nviewof mm_s2 = Inputs.range([0, 0.8], {value: 0.3, step: 0.05, label: \"Method share, colleague\"})\n```\n\n```{ojs}\n//| echo: false\nmm = mtmm({rel: mm_rel, phi: mm_phi, phi12: mm_phi12, s1: mm_s1, s2: mm_s2})\nmm_lab = [\"T1 self\", \"T2 self\", \"T3 self\", \"T1 coll\", \"T2 coll\", \"T3 coll\"]\nmm_cells = mm.R.flatMap((row, i) => row.map((v, j) => ({i: mm_lab[i], j: mm_lab[j], v, validity: Math.abs(i - j) === 3}))).filter(d => d.i !== d.j)\nPlot.plot({\n  width: 470, height: 440, marginLeft: 60, marginTop: 50,\n  x: {domain: mm_lab, axis: \"top\", label: null}, y: {domain: mm_lab, label: null},\n  color: {domain: [0, 1], range: [palette.white, palette.main]},\n  marks: [\n    Plot.cell(mm_cells, {x: \"j\", y: \"i\", fill: \"v\", stroke: palette.rule, inset: 1}),\n    Plot.cell(mm_cells.filter(d => d.validity), {x: \"j\", y: \"i\", fill: \"none\", stroke: palette.contrast, strokeWidth: 3, inset: 2}),\n    Plot.text(mm_cells, {x: \"j\", y: \"i\", text: d => d.v.toFixed(2), fill: d => d.v > 0.55 ? palette.white : palette.ink, fontSize: 11})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`${mm.checks.map(c => `**Trait ${c.trait}:** validity ${c.validity.toFixed(2)}; largest different-trait, different-method value ${c.maxHTHM.toFixed(2)}; largest different-trait, same-method value ${c.maxHTMM.toFixed(2)}. ${c.beatsHTMM ? \"It passes\" : \"It **fails**\"} the same-method comparison.`).join(\"\\n\\n\")}`\n```\n\nAt the starting values every validity value (0.56) beats both comparisons. Raise the correlation of traits 1 and 2 to 0.6: their same-method correlation reaches 0.58 and the comparison fails for both, although nothing is wrong with either measure. Set that correlation to 0.3 and the colleague's method share to 0.5: the validity values fall to 0.47 and the colleague's ratings of traits 1 and 2 correlate 0.52, another failure. Close traits and a strong method both produce it, and the matrix alone doesn't say which.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Self-reports and parent reports of anxiety correlate 0.40. Self-reported anxiety and self-reported depression correlate 0.60, and parent-reported anxiety and parent-reported depression correlate 0.55. What does Campbell and Fiske's comparison say?\",\n  options: [\n    {text: \"It fails for anxiety: within each informant, anxiety agrees more with depression than with the other informant's anxiety\", correct: true, why: \"The validity value (0.40) is below both same-method values. Either the two constructs are close, or each informant's reports share something beyond the traits, and the matrix can't tell which.\"},\n    {text: \"It passes, because 0.40 is well above zero\", correct: false, why: \"That is only the first requirement. The comparison with same-method values is the one that guards against shared method, and here it fails.\"},\n    {text: \"It shows that the anxiety scale is unreliable\", correct: false, why: \"Unreliability lowers every correlation involving the scale, the same-method ones included. The comparison is about what the scores share, not how precise they are.\"}\n  ]\n})\n```\n\n### Criterion evidence, and what bounds it\n\nA **criterion** measures the outcome a score should predict, such as a later grade or a diagnosis. A **predictive** study measures it later, as in admissions; a **concurrent** study at about the same time, as when a new screener is checked against an established interview ([AERA, APA & NCME, 2014, p. 17](https://www.testingstandards.net/open-access-files.html)). The evidence is usually a correlation, the **validity coefficient**. What does 0.5 mean? In the widget below, selecting the top half on the predictor puts 65% of those selected above the criterion's median, against 50% by chance.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd), problem 2: a correlation between two error-laden scores is attenuated, $\\text{cor}(X, Y) = \\text{cor}(T_X, T_Y)\\sqrt{\\rho_{XX'}\\,\\rho_{YY'}}$ ([Spearman, 1904](https://doi.org/10.2307/1412159)), so a test's correlation with anything is bounded by $\\sqrt{\\rho_{XX'}}$.\n:::\n\nTurned around, it gives the **correction for attenuation**, $r_{XY}/\\sqrt{\\rho_{XX'}\\rho_{YY'}}$, the correlation the measures would have without their error. It assumes the classical model, and that the reliability estimate counts as error exactly what the two measures don't share; the real data test the second assumption.\n\nThe bound also explains the **reliability paradox** that [Classical test theory and reliability](ctt-reliability.qmd) pointed to. Tasks that produce robust experimental effects, such as the Stroop task, do so partly because respondents differ little in the effect, which leaves low reliability ([Hedge, Powell & Sumner, 2018](https://doi.org/10.3758/s13428-017-0935-1)). A task with reliability 0.3 can correlate at most $\\sqrt{0.3} \\approx 0.55$ even with a perfectly measured criterion, so its small criterion correlations say more about its reliability than about its construct.\n\nCriterion evidence can be **incremental**: does the new score predict beyond what we already have ([Sechrest, 1963](https://doi.org/10.1177/001316446302300113))? That is the change in $R^2$ when it joins a regression.\n\nWhat if the sample was selected on the predictor? A college sees grades only for the students it admitted, partly for their test scores. In that narrower group scores vary less and the correlation shrinks (comment to Standard 1.21, [AERA, APA & NCME, 2014, p. 29](https://www.testingstandards.net/open-access-files.html)).\n\n#### Try it: selecting on the predictor\n\nEight hundred applicants with a predictor and a criterion; the ones kept are the top share on the predictor.\n\n```{ojs}\n//| echo: false\nviewof rr_rho = Inputs.range([0, 0.9], {value: 0.5, step: 0.05, label: \"Correlation in the applicant pool\"})\nviewof rr_keep = Inputs.range([0.1, 1], {value: 0.5, step: 0.05, label: \"Share selected\"})\nviewof rr_ceiling = Inputs.toggle({label: \"Criterion has a ceiling\", value: false})\nviewof rr_corr = Inputs.toggle({label: \"Show the case II correction\", value: true})\n```\n\n```{ojs}\n//| echo: false\nrr = restrictSample({seed: 12, n: 800, rho: rr_rho, keep: rr_keep, ceiling: rr_ceiling})\nPlot.plot({\n  width: 560, height: 360, x: {label: \"Predictor (SD units)\", domain: [-3.5, 3.5]}, y: {label: \"Criterion (SD units)\", domain: [-3.5, 3.5]},\n  marks: [\n    Plot.dot(rr.pts.filter(p => !p.sel), {x: \"x\", y: \"y\", r: 2.5, fill: palette.light, fillOpacity: 0.6}),\n    Plot.dot(rr.pts.filter(p => p.sel), {x: \"x\", y: \"y\", r: 2.5, fill: palette.main, fillOpacity: 0.6}),\n    Plot.linearRegressionY(rr.pts, {x: \"x\", y: \"y\", stroke: palette.guide, strokeDasharray: \"4,3\", ci: 0}),\n    Plot.linearRegressionY(rr.pts.filter(p => p.sel), {x: \"x\", y: \"y\", stroke: palette.contrast, strokeWidth: 2, ci: 0}),\n    Plot.ruleX([rr.cutX], {stroke: palette.guide, strokeDasharray: \"4,3\"})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Correlation in the pool: **${rr.rAll.toFixed(2)}**. Among the ${rr.nSel} selected (dark points): **${rr.rSel.toFixed(2)}**.${rr_corr ? ` The predictor's SD is ${rr.u.toFixed(2)} times larger in the pool, and case II gives **${rr.corrected.toFixed(2)}**.` : \"\"} Of the selected, ${(100 * rr.above).toFixed(0)}% are above the pool's median on the criterion.`\n```\n\nWith half kept, the correlation drops from 0.52 to 0.34, and the correction returns 0.52. Keep a fifth: 0.30 observed, 0.55 corrected. Now turn on the ceiling, which caps the criterion as a top grade does: the selected points bunch at the top, their line flattens, and the correction gives 0.39 against a pool value of 0.48.\n\nThe correction is Thorndike's **case II** ([Thorndike, 1949](https://openlibrary.org/works/OL3700883W)): with $r$ the correlation among the selected and $u$ the ratio of the pool's predictor SD to the selected group's,\n$$\\hat R = \\frac{r\\,u}{\\sqrt{1 - r^2 + r^2u^2}}.$$\nIt assumes selection on the predictor alone and a linear regression with the same residual spread everywhere. When selection works on something related to both, such as an admissions officer's overall judgment, the restriction is **indirect** and case II corrects too little ([Sackett & Yang, 2000](https://doi.org/10.1037/0021-9010.85.1.112); [Hunter, Schmidt & Le, 2006](https://doi.org/10.1037/0021-9010.91.3.594)), as the simulation shows.\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: where case II comes from\n\n**Assumptions:** in the pool, $Y = \\beta_0 + \\beta_1 X + e$ with $e$ uncorrelated with $X$ and of the same variance $\\sigma^2_e$ at every $X$; selection depends on $X$ only, so among the selected the slope $\\beta_1$ and $\\sigma^2_e$ are unchanged. Write $S$ and $s$ for the SD of $X$ in the pool and among the selected, and $u = S/s$.\n\n**Among the selected**, $r^2 = \\beta_1^2 s^2 / (\\beta_1^2 s^2 + \\sigma^2_e)$, so $\\sigma^2_e = \\beta_1^2 s^2 (1 - r^2)/r^2$.\n\n**In the pool**, with the same $\\beta_1$ and $\\sigma^2_e$,\n$$R^2 = \\frac{\\beta_1^2 S^2}{\\beta_1^2 S^2 + \\sigma^2_e} = \\frac{S^2}{S^2 + s^2(1 - r^2)/r^2} = \\frac{r^2u^2}{r^2u^2 + 1 - r^2},$$\nand taking the square root gives the formula above. Nothing about $Y$'s distribution in the pool is needed, which is what makes the correction usable when criterion scores exist only for the selected.\n\n**Where it breaks.** If selection also depends on something correlated with $e$, the selected group's residual variance is smaller than the pool's and the correction is too small. If the regression bends or the residual spread changes with $X$ (a ceiling does both), the slope and residual variance among the selected aren't the pool's, and the correction can miss in either direction.\n\n**Across groups.** The same regression, compared across groups of respondents rather than across a selection, defines predictive bias ([Cleary, 1968](https://doi.org/10.1111/j.1745-3984.1968.tb00613.x)): a test is biased in prediction for a group when a common regression line systematically over- or under-predicts that group's criterion. [Differential item functioning](dif.qmd) asks the related question item by item.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A test has reliability 0.64 and its criterion 0.49; the observed validity coefficient is 0.28. What is the largest correlation these two measures could have, and what does the correction for attenuation give?\",\n  options: [\n    {text: \"At most 0.56; corrected, 0.50\", correct: true, why: \"The bound is $\\\\sqrt{0.64 \\\\times 0.49} = 0.56$, and $0.28 / 0.56 = 0.50$ is the estimated correlation between the true scores, if the classical assumptions hold.\"},\n    {text: \"At most 0.80; corrected, 0.35\", correct: false, why: \"That bounds the test's correlation with a perfectly measured criterion ($\\\\sqrt{0.64}$) and corrects for the test's error only. The criterion's error attenuates the correlation too.\"},\n    {text: \"At most 1; corrected, 0.28, since correlations aren't affected by reliability\", correct: false, why: \"Error in either measure adds variance that the other doesn't share, and that lowers the correlation. That is Spearman's point.\"}\n  ]\n})\n```\n\n### Classification accuracy\n\nWhen a score classifies, the criterion is usually a category and the evidence a cross-tabulation. **Sensitivity** is the share of cases flagged; **specificity** the share of non-cases cleared.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Validity as an argument](validity-argument.qmd): in the Children's Attention Project tables, six or more symptoms in either domain matched the ADHD indicator for all 355 children, because the indicator was that rule applied to the same parent reports. A criterion built from the test's own items makes agreement certain, and says nothing about extrapolation.\n:::\n\nSo a classification study needs a criterion **independent** of the test: an interview by a clinician who hasn't seen the screener, or a later outcome. Against the ADHD indicator, sensitivity and specificity were both 1 by construction. The box \"What is the AUC?\" in [that lesson](validity-argument.qmd) defines the **ROC curve**, sensitivity against $1 - \\text{specificity}$ as the cut moves, and the **AUC**, the chance that a random case outscores a random non-case ([Hanley & McNeil, 1982](https://doi.org/10.1148/radiology.143.1.7063747); [Swets, 1988](https://doi.org/10.1126/science.3287615)).\n\nWhat neither number says is how many flagged respondents are cases. That is the **positive predictive value** (PPV), and it depends on the **base rate**, the share of cases in the population screened ([Meehl & Rosen, 1955](https://doi.org/10.1037/h0048070)).\n\n#### Try it: a cut, a curve and a base rate\n\nNon-cases' scores are normal with SD 1; cases' scores are shifted up by the separation you choose. Everyone at or above the cut is flagged.\n\n```{ojs}\n//| echo: false\nviewof rc_d = Inputs.range([0, 3.5], {value: 2, step: 0.1, label: \"Separation of cases from non-cases (SDs)\"})\nviewof rc_cut = Inputs.range([-2, 4], {value: 1.2, step: 0.1, label: \"Cut\"})\nviewof rc_prev = Inputs.range([0.01, 0.5], {value: 0.1, step: 0.01, label: \"Base rate\"})\n```\n\n```{ojs}\n//| echo: false\nrc = binormal({d: rc_d, cut: rc_cut, prev: rc_prev})\nrc_dens = grid(-4, 7, 221).flatMap(x => [{x, y: (1 - rc_prev) * dnorm(x), group: \"non-cases\"}, {x, y: rc_prev * dnorm(x, rc_d), group: \"cases\"}])\nrc_p1 = Plot.plot({\n  width: 380, height: 260, x: {label: \"Score\"}, y: {label: \"Density × share of population\"},\n  color: {legend: true, domain: [\"non-cases\", \"cases\"], range: [palette.light, palette.contrast]},\n  marks: [Plot.areaY(rc_dens, {x: \"x\", y: \"y\", fill: \"group\", fillOpacity: 0.6}), Plot.ruleX([rc_cut], {stroke: palette.ink, strokeWidth: 1.5}), Plot.ruleY([0])]\n})\nrc_p2 = Plot.plot({\n  width: 280, height: 260, x: {label: \"1 − specificity\", domain: [0, 1]}, y: {label: \"Sensitivity\", domain: [0, 1]},\n  marks: [Plot.line([[0, 0], [1, 1]], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n          Plot.line(rocCurve(rc_d), {x: \"fpr\", y: \"tpr\", stroke: palette.main, strokeWidth: 2.5}),\n          Plot.dot([{fpr: 1 - rc.spec, tpr: rc.sens}], {x: \"fpr\", y: \"tpr\", r: 6, fill: palette.contrast})]\n})\nhtl.html`<div style=\"display: flex; flex-wrap: wrap; gap: 1rem;\">${rc_p1}${rc_p2}</div>`\n```\n\n```{ojs}\n//| echo: false\nmd`Sensitivity **${rc.sens.toFixed(2)}**, specificity **${rc.spec.toFixed(2)}**, AUC **${rc.auc.toFixed(2)}**. The screener flags ${(100 * rc.flagged).toFixed(1)}% of the population, and of those flagged, **${(100 * rc.ppv).toFixed(0)}%** are cases (the PPV). Of those cleared, ${(100 * rc.npv).toFixed(1)}% are non-cases.`\n```\n\nAt the starting values (AUC 0.92), 43% of flagged respondents are cases; move the base rate to 0.03 and it falls to 17%, with sensitivity and specificity unchanged. Moving the cut slides the point along the curve, trading one error for the other. Youden's $J$, sensitivity + specificity − 1 ([Youden, 1950](https://doi.org/10.1002/1097-0142(1950)3:1<32::AID-CNCR2820030106>3.0.CO;2-3)), weighs the two errors equally; problem 1 asks what happens when they aren't.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [What does a score mean?](score-meaning.qmd): there the PHQ-9's cut of 10 was a decision, chosen from a range of cuts that did about equally well against diagnostic interviews. Accuracy against a criterion narrows the range; where to cut within it depends on what each kind of error costs.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A screener has sensitivity 0.90 and specificity 0.90. It is used on a population where 2% have the condition. Roughly what share of flagged respondents have it?\",\n  options: [\n    {text: \"About 16%\", correct: true, why: \"Of 1,000 people, 20 have it and 18 of them are flagged; of the 980 without it, 98 are flagged. So 18 of 116 flagged, about 16%, are cases.\"},\n    {text: \"About 90%\", correct: false, why: \"That is the sensitivity, the share of cases flagged. The share of the flagged who are cases also depends on how many non-cases there are to be wrongly flagged.\"},\n    {text: \"About 2%\", correct: false, why: \"That is the base rate. Flagging raises the share of cases from 2% to about 16%, a real gain, but most flags are still false alarms.\"}\n  ]\n})\n```\n\n### What a complete argument would need\n\nEverything above comes from item responses and a few covariates, which is what an IRW table holds, and it backs only some links of an argument. What would the rest look like? [Shepard (1993, pp. 431–432)](https://doi.org/10.3102/0091732X019001405) sets out an example from [Kane (1992, pp. 531–532)](https://doi.org/10.1037/0033-2909.112.3.527): an algebra test used to send college students either to calculus or to a remedial algebra course. The argument for that use rests on seven assumptions, paraphrased in the table with the evidence each needs.\n\n::: {.callout-note appearance=\"simple\"}\n## Kane's placement argument, and what the IRW could supply\n\n| Assumption (after Kane, 1992, as listed by Shepard, 1993, pp. 431–432) | Evidence needed | In the IRW? |\n|---|---|---|\n| 1. The algebra skills tested are used heavily in calculus, so they are prerequisites | Analysis of the calculus course: its materials, tasks and instructors' judgments | No |\n| 2. The test's content matches those skills | Expert review of the items against the course ([From construct map to items](instrument-building.qmd)) | No: some tables have item text, but not the course to match it to |\n| 3. Scores generalize across items, occasions and scorers | Reliability, and the standard error near the cut ([Many sources of error](g-theory.qmd); [What does a score mean?](score-meaning.qmd)) | Yes, where a table has the design (several forms, occasions or raters) |\n| 4. No systematic error biases scores as measures of algebra skill | Response processes (think-alouds, speededness) and bias for groups ([Differential item functioning](dif.qmd)) | Partly: DIF needs a group covariate, which some tables have |\n| 5. A suitable measure of success in calculus exists | A criterion defined for the course, independent of the test | Partly: a few tables carry grades, as ours does |\n| 6. The remedial course teaches the algebra that calculus uses | A study of what students learn in the remedial course | No |\n| 7. Students with strong algebra wouldn't gain much from the remedial course | Outcomes by score for students in each course, which is where the decision's consequences show | No |\n:::\n\nShepard's point about this list is that several studies backing the first three assumptions can't make up for missing evidence on the fifth and sixth (p. 432). For placement in particular she puts the effects of the placement at the centre: students on each side of the cut should end up better off than they would have been without the test (p. 441). Her own cases (the SAT, the General Aptitude Test Battery, and placement in special education and two-year kindergartens; pp. 432–443) follow the same pattern. Response data are strongest on assumptions 3 and 4, the ones that can't compensate for the rest. The others need course records, studies of instruction and outcomes across the cut, gathered for that use in that setting.\n\n## Simulate\n\nPart 1 draws 20,000 applicants whose predictor and criterion correlate 0.5 and selects the top half, either on the predictor (direct) or on a third variable related to the predictor and to what it misses in the criterion (indirect). Part 2 draws a screener whose cases score 2 SDs higher, cuts it at 1.2, and compares base rates of 3% and 30%.\n\nWith the seed as written, direct selection lowers the correlation to 0.33 and case II returns 0.50, the pool's value; indirect selection lowers it to 0.27 and case II returns only 0.32. In part 2, sensitivity (about 0.79) and specificity (about 0.88) barely move while the PPV goes from 0.175 to 0.749. Then set the 0.4 in the line defining `z` to 0: is indirect selection still a problem?\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-16\n# Range restriction and base rates. Part 1 draws a predictor x and a criterion y\n# with a known correlation, selects on x (direct restriction) or on a third\n# variable z related to both (indirect restriction), and compares the observed,\n# case II corrected and true correlations. Part 2 draws a screener and an\n# independent criterion and asks how many flagged respondents are cases at two\n# base rates. Base R only. New for this course (not in EDUC 252).\nset.seed(60)\nn     <- 20000   # applicants\nrho   <- 0.5     # true correlation between x and y in the applicant pool\nkeep  <- 0.5     # share selected\nrho_z <- 0.7     # for indirect selection: z's correlation with x (and with y's residual)\n\nx <- rnorm(n)\ny <- rho * x + sqrt(1 - rho^2) * rnorm(n)\n# z is related to x and also to the part of y that x doesn't predict (say, motivation).\nz <- rho_z * x + 0.4 * (y - rho * x) / sqrt(1 - rho^2) + sqrt(1 - rho_z^2 - 0.16) * rnorm(n)\n\n# Case II (Thorndike, 1949): u is the ratio of the pool's SD of x to the selected SD.\ncase2 <- function(r, u) r * u / sqrt(1 - r^2 + r^2 * u^2)\nsummarize <- function(sel) {\n  r <- cor(x[sel], y[sel]); u <- sd(x) / sd(x[sel])\n  c(pool = cor(x, y), selected = r, corrected = case2(r, u), u = u)\n}\ndirect   <- x > quantile(x, 1 - keep)\nindirect <- z > quantile(z, 1 - keep)\nround(rbind(direct = summarize(direct), indirect = summarize(indirect)), 3)\n\n# Part 2: a screener whose scores differ by d SDs between cases and non-cases, with\n# a cut at `cut`. Sensitivity and specificity don't depend on the base rate; the\n# share of flagged respondents who are cases (the positive predictive value) does.\nd   <- 2\ncut <- 1.2\nscreen <- function(prev, n = 100000) {\n  case  <- rbinom(n, 1, prev)\n  score <- rnorm(n, mean = d * case)\n  flag  <- score > cut\n  c(prevalence = prev,\n    sensitivity = mean(flag[case == 1]), specificity = mean(!flag[case == 0]),\n    PPV = mean(case[flag] == 1), flagged = mean(flag))\n}\nround(rbind(screen(0.03), screen(0.30)), 3)\n\n```\n:::\n\n\n[Download this code](code/validity-evidence-sim.R) to run it in your own R session.\n\n## With real data\n\n\n\nThe main example, [de_vries_2022_hexaco_self](https://itemresponsewarehouse.org/tables/de_vries_2022_hexaco_self/) with [de_vries_2022_hexaco_other](https://itemresponsewarehouse.org/tables/de_vries_2022_hexaco_other/), is an MTMM matrix in which one trait agrees less with itself across methods than with another trait within each method. The contrast, [ieswriting_molloy_2022](https://itemresponsewarehouse.org/tables/ieswriting_molloy_2022/), carries the criterion analyses: a very reliable scale that predicts almost nothing, and a range-restriction correction whose assumptions fail. [Download the code](code/validity-evidence-irw.R); it needs only base R.\n\n### Self and colleagues: an MTMM matrix\n\n[De Vries, Broks, Bloemers, Kuntze and de Vries (2022)](https://doi.org/10.1371/journal.pone.0272095) asked Dutch employees to describe themselves on the HEXACO Personality Inventory–Revised ([Lee & Ashton, 2004](https://doi.org/10.1207/s15327906mbr3902_8)), and up to three colleagues each to rate them on the observer version: 96 items of the 100-item form ([Lee & Ashton, 2018](https://doi.org/10.1177/1073191116659134)), 16 for each of six traits, answered from 1 (strongly disagree) to 5 (strongly agree). Self-report and a colleague's rating are our two methods; items appear by code, since their wording is licensed for non-commercial research only.\n\nThe tables hold all 434 employees in the data file (the paper analysed 359 after quality checks), so our numbers won't match the paper's. The responses arrive unkeyed. We reverse the 48 items the published key reverses ([hexaco.org](https://hexaco.org/downloads/ScoringKeys_100.pdf)), the same 48 the authors' data file carries reversed copies of; after keying, higher means more of the trait.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The CSV links on the tables' landing pages (pinned to one version).\nbase4 <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_4:v7_0.\"\nself  <- read.csv(paste0(base4, \"de_vries_2022_hexaco_self/rows?format=csv\"))\nother <- read.csv(paste0(base4, \"de_vries_2022_hexaco_other/rows?format=csv\"))\nhead(other, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  id|item    | resp|rater      |\n|---:|:-------|----:|:----------|\n| 151|PAgent4 |    2|colleague1 |\n|  48|PEdepe6 |    2|colleague1 |\n| 168|PEsent1 |    2|colleague1 |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(self_rows = nrow(self), self_targets = length(unique(self$id)),\n  other_rows = nrow(other), other_targets = length(unique(other$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    self_rows  self_targets    other_rows other_targets \n        41664           434         90528           398 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(rater = other$rater[!duplicated(other[, c(\"id\", \"rater\")])])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrater\ncolleague1 colleague2 colleague3 \n       393        361        189 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Item codes are P + trait letter (H, E, X, A, C, O) + facet + number. The 96 items\n# are the HEXACO-100 without its four Altruism items, and they arrive unkeyed. These\n# 48 are reverse-keyed in the published scoring key for the 100-item version\n# (hexaco.org, ScoringKeys_100.pdf, items 1R, 6R, 9R, ..., 96R, matched to codes by\n# the item order of the authors' data file, which also carries a reversed copy of\n# exactly these 48 items).\nreversed <- c(\"POaesa1\", \"PHsinc1\", \"PAgent4\", \"PXsocb2\", \"PHfair1\", \"POcrea2\",\n  \"PAflex1\", \"PXsoci2\", \"POunco2\", \"PCprud2\", \"PApati2\", \"POaesa3\", \"PEfear4\",\n  \"PEanxi4\", \"PHfair4\", \"PCperf2\", \"PEdepe6\", \"PHgree4\", \"PCprud3\", \"PCorga6\",\n  \"PAforg7\", \"PXsses5\", \"PHsinc5\", \"POinqu6\", \"PCdili5\", \"PEanxi6\", \"PAflex7\",\n  \"PHgree5\", \"PXlive4\", \"PHmode6\", \"PCorga8\", \"PAforg8\", \"PXsses8\", \"PEfear8\",\n  \"POinqu8\", \"PCdili6\", \"PXsocb8\", \"PHfair8\", \"POcrea8\", \"PAflex8\", \"PEdepe8\",\n  \"PHgree7\", \"POunco8\", \"PCprud8\", \"PApati6\", \"PXlive7\", \"PEsent7\", \"PHmode8\")\nkeyit <- function(d) { d$resp <- ifelse(d$item %in% reversed, 6 - d$resp, d$resp); d }\nself <- keyit(self); other <- keyit(other)\ntraits <- c(H = \"Honesty-Humility\", E = \"Emotionality\", X = \"Extraversion\",\n            A = \"Agreeableness\", C = \"Conscientiousness\", O = \"Openness\")\nwide <- function(d) {\n  w <- reshape(d[, c(\"id\", \"item\", \"resp\")], idvar = \"id\", timevar = \"item\", direction = \"wide\")\n  names(w) <- sub(\"^resp\\\\.\", \"\", names(w))\n  w[order(w$id), ]\n}\nws  <- wide(self)\nwc1 <- wide(other[other$rater == \"colleague1\", ])   # the first colleague for each target\nitems <- setdiff(names(ws), \"id\")\ntrait_of <- substr(items, 2, 2)\n# Keying check: each keyed item against the rest of its trait's 16 items.\nitem_rest <- function(w) sapply(items, function(i) {\n  rest <- setdiff(items[trait_of == substr(i, 2, 2)], i)\n  cor(w[[i]], rowSums(w[, rest]))\n})\nround(rbind(self = range(item_rest(ws)), colleague = range(item_rest(wc1))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1] [,2]\nself      0.15 0.60\ncolleague 0.14 0.67\n```\n\n\n:::\n:::\n\n\nEvery keyed item correlates positively with the rest of its trait (the weakest at 0.15 and 0.14), so key and codes agree. Each trait is scored as the mean of its 16 items, using each target's first colleague.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nalpha <- function(x) {\n  k <- ncol(x)\n  k / (k - 1) * (1 - sum(apply(x, 2, var)) / var(rowSums(x)))\n}\nscore <- function(w) sapply(names(traits), function(t) rowMeans(w[, items[trait_of == t]]))\nS <- data.frame(id = ws$id, score(ws)); C1 <- data.frame(id = wc1$id, score(wc1))\nrel <- rbind(self      = sapply(names(traits), function(t) alpha(ws[, items[trait_of == t]])),\n             colleague = sapply(names(traits), function(t) alpha(wc1[, items[trait_of == t]])))\nround(rel, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             H    E    X    A    C    O\nself      0.80 0.82 0.80 0.83 0.80 0.84\ncolleague 0.86 0.82 0.82 0.88 0.85 0.85\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nm <- merge(S, C1, by = \"id\", suffixes = c(\".self\", \".coll\"))\nnrow(m)   # targets with a self-report and a first colleague's rating\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 393\n```\n\n\n:::\n:::\n\n\nTrait alphas run from 0.80 to 0.84 (self) and 0.82 to 0.88 (colleague); 393 employees have both.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nR <- cor(m[, -1])   # the full matrix is drawn in the next chunk\nRs <- R[1:6, 1:6]; Rc <- R[7:12, 7:12]; Rsc <- R[1:6, 7:12]\noff <- row(Rsc) != col(Rsc)\nc(validity_min = min(diag(Rsc)), validity_max = max(diag(Rsc)),\n  hetero_hetero = mean(abs(Rsc[off])),                                  # different trait, different method\n  hetero_mono = mean(abs(c(Rs[upper.tri(Rs)], Rc[upper.tri(Rc)]))))     # different trait, same method\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n validity_min  validity_max hetero_hetero   hetero_mono \n        0.257         0.522         0.064         0.127 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nop <- par(mar = c(1, 5.5, 5.5, 1))\nlab <- c(paste(names(traits), \"self\"), paste(names(traits), \"coll\"))\nimage(1:12, 1:12, t(R[12:1, ]), zlim = c(-1, 1), axes = FALSE, xlab = \"\", ylab = \"\",\n      col = hcl.colors(41, \"Blue-Red 3\", rev = TRUE))\naxis(3, 1:12, lab, las = 2, tick = FALSE); axis(2, 1:12, rev(lab), las = 1, tick = FALSE)\ntext(rep(1:12, 12), rep(12:1, each = 12), sprintf(\"%.2f\", R), cex = 0.6)\nabline(v = 6.5, h = 6.5, lwd = 2)\n```\n\n::: {.cell-output-display}\n![](validity-evidence_files/figure-html/heatmap-1.png){width=624}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npar(op)\n```\n:::\n\n\nThe validity values run from 0.26 (Honesty-Humility) to 0.52 (Openness), well above the average absolute correlation of different traits by different methods (0.06) or by the same method (0.13). Two colleagues rating the same person give another baseline:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Sanity check on the pipeline: two colleagues rating the same target.\nwc2 <- wide(other[other$rater == \"colleague2\", ])\nC2 <- data.frame(id = wc2$id, score(wc2))\nm12 <- merge(C1, C2, by = \"id\", suffixes = c(\".c1\", \".c2\"))\nc(targets = nrow(m12))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntargets \n    357 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(sapply(names(traits), function(t) cor(m12[[paste0(t, \".c1\")]], m12[[paste0(t, \".c2\")]])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   H    E    X    A    C    O \n0.30 0.48 0.51 0.41 0.43 0.58 \n```\n\n\n:::\n:::\n\n\nFor 357 targets, two colleagues agree at 0.30 to 0.58, much as each agrees with the self-report. Now Campbell and Fiske's comparisons:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Campbell and Fiske's comparisons, trait by trait. Each validity value (same trait,\n# different method) should beat the 10 different-trait correlations in its row and\n# column of the self-colleague block, and the 10 different-trait correlations that\n# involve the trait within each method.\ncf <- t(sapply(1:6, function(i) {\n  hh <- abs(c(Rsc[i, -i], Rsc[-i, i])); hm <- abs(c(Rs[i, -i], Rc[i, -i]))\n  c(validity = Rsc[i, i],\n    beats_hetero_hetero = sum(Rsc[i, i] > hh), largest_hetero_hetero = max(hh),\n    beats_hetero_mono = sum(Rsc[i, i] > hm), largest_hetero_mono = max(hm))\n}))\nrownames(cf) <- traits\nround(cf, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  validity beats_hetero_hetero largest_hetero_hetero beats_hetero_mono\nHonesty-Humility      0.26                  10                  0.14                 8\nEmotionality          0.42                  10                  0.16                10\nExtraversion          0.45                  10                  0.16                10\nAgreeableness         0.38                  10                  0.14                10\nConscientiousness     0.41                  10                  0.12                10\nOpenness              0.52                  10                  0.12                10\n                  largest_hetero_mono\nHonesty-Humility                 0.37\nEmotionality                     0.25\nExtraversion                     0.26\nAgreeableness                    0.37\nConscientiousness                0.25\nOpenness                         0.16\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(self_HA = Rs[\"H.self\", \"A.self\"], colleague_HA = Rc[\"H.coll\", \"A.coll\"]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     self_HA colleague_HA \n        0.32         0.37 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Is the pattern of trait correlations the same within each method?\nround(cor(Rs[lower.tri(Rs)], Rc[lower.tri(Rc)]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.87\n```\n\n\n:::\n:::\n\n\nEvery validity value beats its ten heterotrait–heteromethod values, and the trait correlations follow much the same pattern in both methods (the two sets correlate 0.87). But Honesty-Humility's validity value, 0.26, is below its correlation with Agreeableness within self-reports (0.32) and within colleagues' ratings (0.37), and Agreeableness only just passes (0.38 against 0.37).\n\nShared method or close traits? The overlap appears in self-reports too, which points to the traits; [Ashton and Lee (2007)](https://doi.org/10.1177/1088868306294907) relate both to reciprocal altruism. De Vries et al. note that employees chose their own raters, who may have liked them. Liking would add to the overlap in colleagues' ratings only, where it is a little larger (0.37 against 0.32).\n\nDoes the correction for attenuation help?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Correct each validity value for unreliability in both ratings, using alpha.\ncorrected <- diag(Rsc) / sqrt(rel[\"self\", ] * rel[\"colleague\", ])\nround(rbind(observed = diag(Rsc), corrected = corrected), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             H    E    X    A    C    O\nobserved  0.26 0.42 0.45 0.38 0.41 0.52\ncorrected 0.31 0.51 0.56 0.45 0.49 0.62\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The colleagues' Honesty-Humility-Agreeableness correlation, corrected the same way.\nround(Rc[\"H.coll\", \"A.coll\"] / sqrt(rel[\"colleague\", \"H\"] * rel[\"colleague\", \"A\"]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.42\n```\n\n\n:::\n:::\n\n\nHonesty-Humility's validity value rises from 0.26 to 0.31, and the colleagues' Honesty-Humility–Agreeableness correlation from 0.37 to 0.42: the comparison still fails. Alpha counts everything the 16 items share as true score, a rater's general impression included, so the correction removes item-sampling error, not method.\n\n### A confident writer, and a grade\n\nThe ETS IES Writing Achievement Study collected coursework, grades, admissions test scores and a writing-attitudes survey adapted from [MacArthur, Philippakos and Graham (2016)](https://doi.org/10.1177/0731948715583115) from students in courses aimed mainly at first-year college students ([Educational Testing Service, n.d.](https://github.com/EducationalTestingService/ies-writing-achievement-study-data); licensed CC BY-NC-SA 4.0 at the source, so we quote only two items). Part 2 asks how confident, from 0 to 100% (stored as 0 to 10), a student is of doing 22 writing tasks, such as \"I can write a paper using correct grammar\" and \"I can avoid distractions while I write\" (items 2.7 and 2.12 of the [survey](https://github.com/EducationalTestingService/ies-writing-achievement-study-data/blob/main/docs/surveys/writing_attitudes_survey.pdf)); higher means more confidence. The criterion is the grade (0 to 4) in the course the survey was given in. ACT scores were converted to the SAT scale by the study team.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nbase <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v59_0.\"\nies <- read.csv(paste0(base, \"ieswriting_molloy_2022/rows?format=csv\"))\nc(rows = nrow(ies), students = length(unique(ies$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    rows students \n   28250      565 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Part 2 of the survey (items Q2.1 to Q2.22): confidence about writing tasks, 0 to 10.\nconf <- ies[grepl(\"^Q2\\\\.\", ies$item), ]\nwconf <- wide(conf)\nround(alpha(wconf[, -1]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nst <- unique(ies[, c(\"id\", \"cov_participating_course_grade\", \"cov_sat_total\", \"cov_cum_GPA\")])\nnames(st) <- c(\"id\", \"grade\", \"sat\", \"gpa\")\nst$confidence <- rowMeans(wconf[match(st$id, wconf$id), -1])\nst <- na.omit(st)\nnrow(st)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 526\n```\n\n\n:::\n:::\n\n\nAlpha is 0.95, and 526 students have a grade and a GPA. The SAT column merits a look:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The most common SAT values. One value stands out.\nhead(sort(table(st$sat), decreasing = TRUE), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n1036.86    1080    1140 \n    116      25      23 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nimputed <- abs(st$sat - 1036.86) < 0.01\nc(students_at_1036.86 = sum(imputed), mean_of_the_rest = round(mean(st$sat[!imputed]), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstudents_at_1036.86    mean_of_the_rest \n                116                1038 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(r_with_them = cor(st$sat, st$grade), r_without = cor(st$sat[!imputed], st$grade[!imputed])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr_with_them   r_without \n       0.43        0.49 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nk <- st[!imputed, ]\nnrow(k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 410\n```\n\n\n:::\n:::\n\n\n116 students have an SAT total of 1036.86, a value no test reports and close to the mean of the others (1038): probably a missing score filled in with the mean, though the documentation doesn't say. These 116 pull the SAT–grade correlation from 0.49 down to 0.43. We keep the 410 students with a reported score.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"The confidence scale has alpha 0.95. For these 410 students, SAT correlates 0.49 with course grade. What does the confidence scale correlate with course grade?\",\n  choices: [\"About 0.5, like SAT\", \"About 0.25\", \"Under 0.1\"],\n  answer: \"Under 0.1\",\n  reveal: \"0.07. Adding confidence to a regression of grade on SAT leaves $R^2$ at 0.24 (p = 0.77). Reliability says the scores are precise, not what they predict.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nround(cor(k[, c(\"grade\", \"gpa\", \"sat\", \"confidence\")]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           grade  gpa  sat confidence\ngrade       1.00 0.76 0.49       0.07\ngpa         0.76 1.00 0.45       0.08\nsat         0.49 0.45 1.00       0.12\nconfidence  0.07 0.08 0.12       1.00\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nm_sat  <- lm(grade ~ sat, data = k)\nm_both <- lm(grade ~ sat + confidence, data = k)\nround(c(R2_sat = summary(m_sat)$r.squared, R2_sat_confidence = summary(m_both)$r.squared,\n        p_added = anova(m_sat, m_both)[2, \"Pr(>F)\"]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           R2_sat R2_sat_confidence           p_added \n             0.24              0.24              0.77 \n```\n\n\n:::\n:::\n\n\nConfidence correlates 0.07 with course grade and 0.08 with GPA; SAT, 0.49 and 0.45. Adding confidence to SAT leaves $R^2$ at 0.24 ($p$ = 0.77): no incremental validity for grades. Is that evidence against the scale? Against using it to predict grades, yes. But it was built to measure motivation to write ([MacArthur et al., 2016](https://doi.org/10.1177/0731948715583115)), and better grades for confident writers was never part of its argument.\n\n### Restricting the range\n\nSuppose a college had admitted only the top half of these students on SAT.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Keep only students above the median SAT, as if the college had admitted them alone.\ntop <- k[k$sat > median(k$sat), ]\nu <- sd(k$sat) / sd(top$sat)          # how much wider SAT is in the full group\ncase2 <- function(r, u) r * u / sqrt(1 - r^2 + r^2 * u^2)\nr_top <- cor(top$sat, top$grade)\nround(c(n_top = nrow(top), r_all = cor(k$sat, k$grade), r_top = r_top, u = u,\n        case_II = case2(r_top, u)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n_top   r_all   r_top       u case_II \n 202.00    0.49    0.27    1.53    0.39 \n```\n\n\n:::\n:::\n\n\nAmong the 202 students above the median SAT, the correlation is 0.27, down from 0.49. SAT's SD is 1.53 times larger in the full group, and case II gives 0.39: most of the way back, but short. Why?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Case II assumes the regression of grade on SAT is linear with the same spread of\n# residuals everywhere. Compare the two halves.\nbottom <- k[k$sat <= median(k$sat), ]\nfit_half <- function(d) { f <- lm(grade ~ I(sat / 100), data = d); c(slope_per_100 = coef(f)[[2]], resid_sd = sigma(f)) }\nround(rbind(bottom = fit_half(bottom), top = fit_half(top)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       slope_per_100 resid_sd\nbottom          0.38     1.13\ntop             0.25     0.91\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(share_grade_4_top = mean(top$grade == 4), share_grade_4_bottom = mean(bottom$grade == 4)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   share_grade_4_top share_grade_4_bottom \n                0.48                 0.15 \n```\n\n\n:::\n:::\n\n\nCase II assumes the same line, with the same scatter, in both halves. The slope is 0.38 grade points per 100 SAT points in the bottom half and 0.25 in the top, and the residual SD falls from 1.13 to 0.91. Grades stop at 4.0, and 48% of the top half got one (15% of the bottom half): the widget's ceiling.\n\nBoth corrections rest on assumptions the data can question. The correction for attenuation assumes the reliability estimate counts as error exactly what two measures don't share; alpha doesn't when raters carry an impression across traits. Case II assumes direct selection and a straight, evenly scattered regression; grades have a ceiling. When I correct a validity coefficient, for unreliability or for range restriction, I report the observed value first and the corrected one beside it, with the assumption the correction rests on; I don't report the corrected value alone. Standard 1.21 asks for both values and the method ([AERA, APA & NCME, 2014, p. 29](https://www.testingstandards.net/open-access-files.html)). A correction is a model, and it comes with a model's assumptions.\n\n## Problems\n\n1. **Where to cut.** For the ROC widget's screener (non-cases $N(0, 1)$, cases $N(d, 1)$), show that the cut maximizing Youden's $J$ is $d/2$. Now minimize the total share misclassified, $p(1 - \\text{sensitivity}) + (1 - p)(1 - \\text{specificity})$, for base rate $p$. Where is the cut, and which way does it move as $p$ falls?\n2. **All the colleagues.** Average each target's available colleagues (up to three) in `de_vries_2022_hexaco_other`, recompute the MTMM matrix, and correct the validity values for attenuation. Which trait gains most, and does Honesty-Humility now pass the same-method comparison? What does averaging raters remove that correcting with alpha doesn't?\n3. **GPA.** Repeat the range-restriction analysis with cumulative GPA as the criterion. Does case II fall short, land on the full-group value, or overshoot? Use the slopes and residual SDs in the two halves to explain why.\n4. **Which use?** Write two uses for the confidence scale's scores, one for which its failure to predict grades counts against it and one for which it is beside the point. For the second, what evidence would you gather instead?\n5. **Plan a classification study.** A new 10-item screener targets a condition with 3% prevalence, and you can afford 200 diagnostic interviews. How many cases would 200 randomly chosen people include, and what does that do to your estimate of sensitivity? Whom would you interview instead, and how would you keep the interviewer independent of the screener?\n6. **Challenge: an unreliable task.** A cognitive task has retest reliability 0.3. What is the largest correlation it can have with a criterion of reliability 0.8? Would a correlation near that bound convince you the task measures a stable trait, and what else would you want to see? This is open.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Gathering%20validity%20evidence%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20sources%20of%20validity%20evidence%20matched%20to%20inferences%20%28content%2C%20response%20processes%2C%20internal%20structure%2C%20relations%20to%20other%20variables%29%2C%20convergent%20and%20discriminant%20evidence%20in%20the%20multitrait-multimethod%20matrix%20with%20Campbell%20and%20Fiske%27s%20comparisons%2C%20criterion%20evidence%20%28predictive%20and%20concurrent%20studies%2C%20the%20correction%20for%20attenuation%2C%20the%20reliability%20paradox%2C%20incremental%20validity%29%2C%20range%20restriction%20and%20Thorndike%27s%20case%20II%20correction%2C%20and%20classification%20accuracy%20%28sensitivity%2C%20specificity%2C%20ROC%20and%20AUC%2C%20base%20rates%20and%20positive%20predictive%20value%29%2C%20with%20HEXACO%20self-%20and%20colleague%20ratings%20and%20a%20college%20writing%20survey%20with%20grades%20and%20SAT%20scores%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- AERA, APA, & NCME. (2014). *Standards for educational and psychological testing*. American Educational Research Association. <https://www.testingstandards.net/open-access-files.html>. Chapter 1 describes the sources of validity evidence (pp. 13–21) and sets standards for criterion studies, including reporting adjusted and unadjusted coefficients (Standard 1.21); open access.\n- Campbell, D. T., & Fiske, D. W. (1959). Convergent and discriminant validation by the multitrait-multimethod matrix. *Psychological Bulletin*, 56(2), 81–105. <https://doi.org/10.1037/h0046016>. The MTMM matrix and the four comparisons.\n- Widaman, K. F. (1985). Hierarchically nested covariance structure models for multitrait-multimethod data. *Applied Psychological Measurement*, 9(1), 1–26. <https://doi.org/10.1177/014662168500900101>. The MTMM matrix as a factor model with trait and method factors.\n- Sireci, S., & Faulkner-Bond, M. (2014). Validity evidence based on test content. *Psicothema*, 26(1), 100–107. <https://doi.org/10.7334/psicothema2013.256>. How content evidence is gathered and summarized.\n- Rios, J., & Wells, C. (2014). Validity evidence based on internal structure. *Psicothema*, 26(1), 108–116. <https://doi.org/10.7334/psicothema2013.260>. Dimensionality, reliability and invariance as internal-structure evidence.\n- Shepard, L. A. (1993). Evaluating test validity. *Review of Research in Education*, 19, 405–450. <https://doi.org/10.3102/0091732X019001405>. Validity as the evaluation of a test use, with Kane's placement argument and cases on the SAT, the GATB and placement in special education and kindergarten.\n- Kane, M. T. (1992). An argument-based approach to validity. *Psychological Bulletin*, 112(3), 527–535. <https://doi.org/10.1037/0033-2909.112.3.527>. The placement argument in the table.\n- Lane, S. (2014). Validity evidence based on testing consequences. *Psicothema*, 26(1), 127–135. <https://doi.org/10.7334/psicothema2013.258>. The source of evidence this lesson doesn't reach.\n- Hunsley, J., & Meyer, G. J. (2003). The incremental validity of psychological testing and assessment: Conceptual, methodological, and statistical issues. *Psychological Assessment*, 15(4), 446–455. <https://doi.org/10.1037/1040-3590.15.4.446>. How to design and read an incremental-validity study.\n- Sackett, P. R., & Yang, H. (2000). Correction for range restriction: An expanded typology. *Journal of Applied Psychology*, 85(1), 112–118. <https://doi.org/10.1037/0021-9010.85.1.112>. The kinds of selection, and the correction each needs.\n- Hunter, J. E., Schmidt, F. L., & Le, H. (2006). Implications of direct and indirect range restriction for meta-analysis methods and findings. *Journal of Applied Psychology*, 91(3), 594–612. <https://doi.org/10.1037/0021-9010.91.3.594>. A correction for indirect restriction, and how much it changes validity estimates.\n- Meehl, P. E., & Rosen, A. (1955). Antecedent probability and the efficiency of psychometric signs, patterns, or cutting scores. *Psychological Bulletin*, 52(3), 194–216. <https://doi.org/10.1037/h0048070>. Base rates, and when a test adds nothing to them.\n- Swets, J. A. (1988). Measuring the accuracy of diagnostic systems. *Science*, 240(4857), 1285–1293. <https://doi.org/10.1126/science.3287615>. The ROC curve across many fields.\n- Hedge, C., Powell, G., & Sumner, P. (2018). The reliability paradox: Why robust cognitive tasks do not produce reliable individual differences. *Behavior Research Methods*, 50(3), 1166–1186. <https://doi.org/10.3758/s13428-017-0935-1>. Why tasks with robust experimental effects can give unreliable measures of individual differences; see also the IRW vignette on [the reliability paradox](https://itemresponsewarehouse.org/vignettes/hf_reliability_paradox.html).\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`de_vries_2022_hexaco_self`](https://itemresponsewarehouse.org/tables/de_vries_2022_hexaco_self/): de Vries A, et al. (2022) Self-, other-, and meta-perceptions of personality: Relations with burnout symptoms and eudaimonic workplace well-being. PLOS ONE. <https://doi.org/10.1371/journal.pone.0272095>. Licence: CC BY 4.0.\n- [`de_vries_2022_hexaco_other`](https://itemresponsewarehouse.org/tables/de_vries_2022_hexaco_other/): de Vries A, et al. (2022) Self-, other-, and meta-perceptions of personality: Relations with burnout symptoms and eudaimonic workplace well-being. PLOS ONE. <https://doi.org/10.1371/journal.pone.0272095>. Licence: CC BY 4.0.\n- [`ieswriting_molloy_2022`](https://itemresponsewarehouse.org/tables/ieswriting_molloy_2022/): Educational Testing Service. (n.d.). IES Writing Achievement Study Data. GitHub. Retrieved January 6, 2025, from <https://github.com/EducationalTestingService/ies-writing-achievement-study-data>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** new material, not in EDUC 252. The lesson was added after the landscape analysis (`notes/landscape-2026-09-24.md`), where convergent and discriminant evidence, the MTMM matrix, criterion validity, range restriction and classification accuracy each appear in 5 or 6 of 11 first-course syllabi. The sources of evidence follow chapter 1 of the *Standards*.\n- **Timing:** about 50 minutes for the core ideas and widgets; the two real-data analyses work as a 30-minute lab. Problems 4 and 5 work as small-group discussions.\n- **Held back:** consequences as evidence (only in *Going further*); the MTMM matrix as a factor model (only in *Going further*); internal structure in depth ([Factor analysis I](fa-exploratory.qmd), [Factor analysis II](fa-confirmatory.qmd)); invariance across groups ([Factor analysis II](fa-confirmatory.qmd)); predictive bias, named here, and item-level bias ([Differential item functioning](dif.qmd)); cut scores as decisions ([What does a score mean?](score-meaning.qmd)).\n- **Data:** the HEXACO item wording is licensed for non-commercial research only (hexaco.org), so no item is quoted. The writing survey is CC BY-NC-SA 4.0 at its source, stricter than the CC BY 4.0 on its IRW page; the lesson follows the source and quotes two items. Classification accuracy has no IRW table: none found pairs a screener with an independent diagnosis, so the widget, the simulation and the recall of the ADHD tables carry it.\n- **Solutions:** held back in `solutions/validity-evidence.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "validity-evidence_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}