{
  "hash": "284d21cd75e00c5e0d27d9b1d0142a62",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Latent classes and cognitive diagnosis\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Beyond the standard models  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [What is an item? Explanatory item response models](explanatory-irt.qmd)  \n**Builds toward:** none  \n**Picks up threads:** The sum score is sufficient under the Rasch model (from [The Rasch model](rasch.qmd))  \n**IRW tables:** [`frac20`](https://itemresponsewarehouse.org/tables/frac20/), [`cdm_ecpe`](https://itemresponsewarehouse.org/tables/cdm_ecpe/)  \n**From EDUC 252:** slides c7; problem sets PS7#2; code [`c7/3_cdm.R`](https://github.com/ben-domingue/252/blob/main/c7/3_cdm.R), [`ps7/cdm.R`](https://github.com/ben-domingue/252/blob/main/ps7/cdm.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\noptions(mc.cores = 1)\nwebr::install(\"GDINA\", quiet = TRUE)\nsuppressPackageStartupMessages(library(GDINA))\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {palette} from \"./widgets/irt.js\"\nimport {cutClasses, fracQ, fracAttributes, dinaItems, hoCurve, classCounts} from \"./widgets/cdm.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\n[What is an item?](explanatory-irt.qmd) explained item difficulty with a matrix of item features and kept every respondent on one continuum. This lesson keeps the matrix and drops the continuum. Suppose respondents differ not in how much of something they have but in *which* skills they have: a student who can find a common denominator but can't borrow from a whole number needs different teaching from one with the opposite gap, even if both get half the items right. Latent class analysis puts respondents in a few unobserved groups; cognitive diagnosis builds the groups from profiles of skills, with a matrix saying which skills each item needs. [Constructs and construct maps](constructs.qmd) asked whether a construct is a continuum or a set of classes, and summary statistics couldn't tell. Here we fit both and see which the data prefer.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- write down the latent class model, fit it with `poLCA`, and choose the number of classes;\n- say why ordered latent classes behave like a continuum cut into pieces, and what would be evidence of something else;\n- read a Q-matrix and say which items a skill profile should answer correctly under DINA;\n- fit DINA and G-DINA with `GDINA`, and read guessing, slipping and the share of respondents with each skill;\n- compare a cognitive diagnosis model with the Rasch model and the 2PL, and use empirical Q-matrix validation with care.\n\n## Core ideas\n\n### Latent classes\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Constructs and construct maps](constructs.qmd): latent classes are unobserved groups inside each of which people are alike. Ordered classes close together gave nearly the same sum scores and item-rest correlations as a continuum, and telling them apart was left to models fit to the responses.\n:::\n\nA latent class model says each respondent belongs to one of $C$ classes, class $c$ holding a share $\\pi_c$ of the population, and that within a class each item has its own probability of success, $p_{ic}$. Given the class, responses are independent: local independence, with a class in place of $\\theta$. The probability of respondent $j$'s responses is a mixture over the classes,\n$$\\Pr(\\mathbf{x}_j) = \\sum_{c=1}^{C} \\pi_c \\prod_{i} p_{ic}^{\\,x_{ij}}\\,(1 - p_{ic})^{1 - x_{ij}}.$$\nThe model comes from Lazarsfeld's latent structure analysis ([Lazarsfeld & Henry, 1968](https://openlibrary.org/works/OL3915958W)); [Goodman (1974)](https://doi.org/10.1093/biomet/61.2.215) took up its estimation and when its parameters are identified. With $I$ items it has $C - 1$ class shares and $C \\times I$ item probabilities. It is fit by EM: from a guess at the item probabilities, compute each respondent's posterior probability of each class, re-estimate the item probabilities with responses weighted by those posteriors, and repeat. We use the `poLCA` package ([Linzer & Lewis, 2011](https://doi.org/10.18637/jss.v042.i10)).\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Estimating item parameters](item-estimation.qmd): the two biased coins that introduced EM were a two-class latent class model, with the ten tosses in a set as its items.\n:::\n\nAnother class always raises the log likelihood, so the number of classes is chosen by a criterion that charges for parameters, such as BIC, and by whether the classes mean anything. A latent class model is a reasonable choice when a theory says there are types, as Moffitt's account of antisocial behaviour does, or to describe how responses hang together without assuming a continuum.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Model fit and out-of-sample prediction](fit-prediction.qmd): AIC and BIC, which charge for each parameter, also compare models that aren't nested, such as a latent class model and a 2PL.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A latent class model with four classes is fit to 28 binary items. How many parameters does it have?\",\n  options: [\n    {text: \"115\", correct: true, why: \"Three free class shares (the fourth is one minus the others) plus $4 \\\\times 28 = 112$ item probabilities.\"},\n    {text: \"112\", correct: false, why: \"That counts the item probabilities but forgets the class shares, $C - 1 = 3$ of them.\"},\n    {text: \"31\", correct: false, why: \"Each class has its own probability for *every* item, so the item parameters number $C \\\\times I$, not $I$.\"}\n  ]\n})\n```\n\n### Classes or a continuum?\n\nWhat does a continuum look like to a latent class model? Cut it into slices, and each slice is a class.\n\n#### Try it: a continuum cut into classes\n\nTen Rasch items have difficulties from −1.5 to 1.5; $\\theta$ is normal. The widget cuts $\\theta$ into equal classes and shows each class's probability of success on each item. The toggle adds a class that finds the odd-numbered items easy and the even-numbered ones hard.\n\n```{ojs}\n//| echo: false\nviewof cc_K = Inputs.range([2, 7], {value: 4, step: 1, label: \"Classes cut from the continuum\"})\nviewof cc_skill = Inputs.toggle({label: \"Add a class that differs in which items it finds hard\", value: false})\n```\n\n```{ojs}\n//| echo: false\ncc = cutClasses(cc_K, cc_skill)\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Item (easiest to hardest)\", ticks: 10}, y: {label: \"P(correct) in the class\", domain: [0, 1]},\n  marks: [\n    Plot.line(cc.rows, {x: \"item\", y: \"p\", z: \"cls\", stroke: d => d.kind === \"skill\" ? palette.contrast : palette.main, strokeWidth: d => d.kind === \"skill\" ? 3 : 2}),\n    Plot.dot(cc.rows, {x: \"item\", y: \"p\", fill: d => d.kind === \"skill\" ? palette.contrast : palette.main, r: 3})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Items on which a class does worse than the class below it (classes ordered by their average): **${cc.outOfOrder} of 10**.`\n```\n\nHowever many classes you cut, the lines never cross: 0 of 10 items are out of order. Add the other class and its line zigzags across the rest, putting all ten out of order. Ordered classes are what a continuum produces. The converse holds too: a Rasch model whose $\\theta$ takes only a few values, ordered classes by another name, gives nearly the same item estimates as the Rasch model's conditional likelihood once it has at least $(I + 1)/2$ of them ([Lindsay, Clogg & Grego, 1991](https://doi.org/10.1080/01621459.1991.10475008)). Evidence for classes as something other than a continuum has to come from crossings, classes that differ in *which* items they find hard.\n\n### Cognitive diagnosis: classes built from attributes\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is an item?](explanatory-irt.qmd): the LLTM wrote each item's easiness as $\\beta_i = \\sum_k q_{ik}\\eta_k$, where $q_{ik}$ is 1 if item $i$ has feature $k$. The matrix of $q_{ik}$ described the items, and respondents stayed on one continuum.\n:::\n\nCognitive diagnosis uses such a matrix differently. Each respondent has a profile $\\boldsymbol\\alpha_j = (\\alpha_{j1}, \\dots, \\alpha_{jK})$ of binary **attributes**, skills they have ($\\alpha_{jk} = 1$) or lack. $K$ attributes give $2^K$ profiles, and each profile is a latent class. The **Q-matrix** says which attributes each item requires: $q_{ik} = 1$ if item $i$ needs attribute $k$. In the LLTM the matrix explained how hard an item is; here it decides which classes an item can tell apart. A cognitive diagnosis model (CDM) is therefore a *restricted* latent class model ([Haertel, 1989](https://doi.org/10.1111/j.1745-3984.1989.tb00336.x)): the classes are fixed in advance by the attributes, and the Q-matrix ties their item probabilities together ([Rupp, Templin & Henson, 2010](https://openlibrary.org/works/OL15026394W)).\n\nThe classic example is fraction subtraction, from Kikumi Tatsuoka's work on diagnosing students' errors ([Tatsuoka, 1983](https://doi.org/10.1111/j.1745-3984.1983.tb00212.x); the data as analysed by [Tatsuoka, 2002](https://doi.org/10.1111/1467-9876.00272)). Twenty items are coded on eight attributes, giving $2^8 = 256$ profiles. The attribute labels are those of the `CDM` package documentation, which takes the Q-matrix from [DeCarlo (2011)](https://doi.org/10.1177/0146621610377081) and [de la Torre and Douglas (2004)](https://doi.org/10.1007/bf02295640).\n\n#### Try it: the Q-matrix at work\n\nChoose a student's attributes. Under DINA (next section), an item is answered correctly with probability $1 - s$ if the student has every attribute it needs, and $g$ otherwise.\n\n```{ojs}\n//| echo: false\nviewof qm_has = Inputs.checkbox(fracAttributes, {value: fracAttributes.filter((_, k) => k !== 4), label: \"Attributes the student has\"})\nviewof qm_g = Inputs.range([0, 0.4], {value: 0.1, step: 0.01, label: \"Guess g (all items)\"})\nviewof qm_s = Inputs.range([0, 0.4], {value: 0.1, step: 0.01, label: \"Slip s (all items)\"})\n```\n\n```{ojs}\n//| echo: false\nqm_profile = fracAttributes.map(a => qm_has.includes(a) ? 1 : 0)\nqm_items = dinaItems(qm_profile, qm_g, qm_s)\nPlot.plot({\n  width: 700, height: 260, x: {label: \"Item\", tickFormat: d => d}, y: {label: \"P(correct)\", domain: [0, 1]},\n  color: {legend: true, domain: [\"has every attribute the item needs\", \"lacks at least one\"], range: [palette.main, palette.contrast]},\n  marks: [\n    Plot.barY(qm_items, {x: \"item\", y: \"p\", fill: d => d.eta ? \"has every attribute the item needs\" : \"lacks at least one\", title: d => d.eta ? \"\" : `lacks ${d.missing}`}),\n    Plot.ruleY([0])\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`This profile can do **${qm_items.filter(d => d.eta).length} of 20** items; its expected score is **${qm_items.reduce((s, d) => s + d.p, 0).toFixed(1)}**.`\n```\n\nThe default student lacks only A5, borrowing from the whole number part; eight items need it, so 12 of 20 are within reach. Now tick A5 and untick A7, subtracting numerators: 19 items need A7, and one is left. Profiles that lack different attributes can also reach similar expected scores through different items, a difference a sum score can't see.\n\n### DINA: all or nothing\n\nThe DINA model (\"deterministic inputs, noisy *and* gate\"; [Junker & Sijtsma, 2001](https://doi.org/10.1177/01466210122032064)) asks one question per item: does the respondent have *every* attribute it needs? Write\n$$\\eta_{ij} = \\prod_{k} \\alpha_{jk}^{\\,q_{ik}},$$\nwhich is 1 if they do and 0 if they lack any. Then\n$$\\Pr(x_{ij} = 1 \\mid \\boldsymbol\\alpha_j) = (1 - s_i)^{\\eta_{ij}}\\, g_i^{\\,1 - \\eta_{ij}}.$$\nThe **slip** $s_i$ is the chance that a respondent with everything the item needs still gets it wrong; the **guess** $g_i$ is the chance that one without gets it right. Each item has two parameters, because the model splits the $2^K$ classes into two groups per item. Having some of the required attributes counts for nothing.\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [From the 1PL to the 4PL](1pl-to-4pl.qmd): its section on ceilings and slips pointed here. DINA's $1 - s$ and $g$ are an upper and a lower asymptote, like the 4PL's $u$ and $c$, with nothing in between.\n:::\n\nOther models relax the rule. In DINO, any one required attribute is enough ([Templin & Henson, 2006](https://doi.org/10.1037/1082-989X.11.3.287)), which suits a symptom that several conditions can produce. G-DINA ([de la Torre, 2011](https://doi.org/10.1007/s11336-011-9207-7)) gives each combination of an item's $K_i$ required attributes its own probability, $2^{K_i}$ of them, and contains DINA and DINO; the log-linear CDM ([Henson, Templin & Willse, 2009](https://doi.org/10.1007/s11336-008-9089-5)) is an equivalent family written as a logistic regression on the attributes and their interactions. DINA is a reasonable choice when an item is solved by a chain of steps that must all succeed, as fraction subtraction is, and when there are too few respondents for G-DINA's extra parameters; G-DINA, when there are enough to let the data say how partial mastery counts.\n\n#### Try it: two plateaus, and a curve between them\n\nDINA has no $\\theta$. But suppose, as the higher-order model below does, that attribute $k$ is mastered with probability $\\text{logistic}(\\lambda(\\theta - \\delta_k))$, with thresholds $\\delta_k$ spread from −1 to 1. Averaging DINA over the attributes gives an item curve against $\\theta$.\n\n```{ojs}\n//| echo: false\nviewof ho_m = Inputs.range([1, 4], {value: 1, step: 1, label: \"Attributes the item needs\"})\nviewof ho_l = Inputs.range([0.5, 4], {value: 1.5, step: 0.1, label: \"Attribute slope λ\"})\nviewof ho_g = Inputs.range([0, 0.4], {value: 0.2, step: 0.01, label: \"Guess g\"})\nviewof ho_s = Inputs.range([0, 0.4], {value: 0.1, step: 0.01, label: \"Slip s\"})\n```\n\n```{ojs}\n//| echo: false\nho = hoCurve(ho_m, ho_l, ho_g, ho_s)\nPlot.plot({\n  width: 700, height: 280, x: {label: \"θ\"}, y: {label: \"P(correct)\", domain: [0, 1]},\n  marks: [\n    Plot.ruleY([ho_g, 1 - ho_s], {stroke: palette.guide, strokeDasharray: \"4 3\"}),\n    Plot.line(ho, {x: \"theta\", y: \"p\", stroke: palette.main, strokeWidth: 2.5})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`At θ = 0 the chance of having all ${ho_m} required attribute${ho_m > 1 ? \"s\" : \"\"} is **${ho[120].all.toFixed(2)}**, and P(correct) is **${ho[120].p.toFixed(2)}**.`\n```\n\nThe dashed lines are the plateaus, $g$ and $1 - s$, where respondents lacking an attribute and those with all of them sit. Given only $\\theta$ the attributes are uncertain, so the curve runs between. With one attribute it is a 4PL curve (see the Go deeper callout). Require more and the curve moves right and loses its symmetry, since every threshold must be passed. Raise $\\lambda$ and the curve steepens toward a step.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Under DINA, an item needs attributes A2 and A5 and has $g = 0.2$, $s = 0.1$. What is P(correct) for a student with A2, A3 and A7 but not A5?\",\n  options: [\n    {text: \"0.2\", correct: true, why: \"The student lacks A5, so $\\\\eta = 0$ and the probability is the guess, $g$. Having A2 earns nothing under DINA.\"},\n    {text: \"0.55\", correct: false, why: \"That is halfway between $g$ and $1 - s$, as if having one of the two attributes earned half the credit. G-DINA could say that; DINA can't.\"},\n    {text: \"0.9\", correct: false, why: \"That is $1 - s$, for students with *every* required attribute. A3 and A7 aren't needed by this item, so they don't make up for A5.\"}\n  ]\n})\n```\n\n### How many classes, which Q-matrix, and why not IRT?\n\nEight attributes give 256 profiles, so an unrestricted distribution over them has 255 parameters, to be estimated from 536 students in the fraction data. Two restrictions shrink that. A **higher-order** model lets one continuous $\\theta$ drive the attributes, as in the last widget ([de la Torre & Douglas, 2004](https://doi.org/10.1007/bf02295640)); with the slope fixed at 1, as `GDINA` does by default, that is one parameter per attribute. An **attribute hierarchy** allows only profiles consistent with an order of learning, ruling out an advanced skill without its prerequisite ([Templin & Bradshaw, 2014](https://doi.org/10.1007/s11336-013-9362-0)). Both move a CDM toward a continuum.\n\n#### Try it: the cost of a profile\n\n```{ojs}\n//| echo: false\nviewof pc_K = Inputs.range([1, 12], {value: 8, step: 1, label: \"Attributes K\"})\nviewof pc_n = Inputs.range([100, 5000], {value: 536, step: 1, label: \"Respondents\"})\n```\n\n```{ojs}\n//| echo: false\nPlot.plot({\n  width: 700, height: 260, x: {label: \"Attributes K\"}, y: {label: \"Parameters for the distribution of profiles\", type: \"log\"},\n  color: {legend: true, domain: [\"Unrestricted: 2^K - 1\", \"Higher-order: K\"], range: [palette.main, palette.contrast]},\n  marks: [\n    Plot.line(classCounts(12), {x: \"K\", y: \"count\", stroke: \"model\", strokeWidth: 2.5}),\n    Plot.ruleX([pc_K], {stroke: palette.guide, strokeDasharray: \"4 3\"})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`With ${pc_K} attribute${pc_K > 1 ? \"s\" : \"\"}: **${2 ** pc_K}** profiles and **${2 ** pc_K - 1}** free class share${pc_K > 1 ? \"s\" : \"\"}, against **${pc_K}** for the higher-order model. ${pc_n} respondents spread evenly would put **${(pc_n / 2 ** pc_K).toFixed(1)}** in each profile.`\n```\n\nAt eight attributes and 536 respondents, an even spread leaves about two students per profile. Each attribute doubles the unrestricted count and adds one to the higher-order count.\n\nThe Q-matrix usually comes from content experts, and may be wrong. **Empirical Q-matrix validation** looks for better entries. The PVAF method ([de la Torre & Chiu, 2016](https://doi.org/10.1007/s11336-015-9467-8)) asks, item by item, for the smallest set of attributes whose G-DINA success probabilities carry at least a set share (by default 95%) of the variation that the item's full set of attributes would give. It is a reasonable way to find items whose coding deserves a second look; a suggestion is a hypothesis about the item, to be checked against what the item asks and by refitting. Is a CDM better than IRT? The models aren't nested, so we compare them by AIC and BIC, or by predicting held-out responses (problem 3).\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"On the same data, a higher-order DINA model has a much lower BIC than DINA with an unrestricted distribution of profiles. What does that suggest?\",\n  options: [\n    {text: \"Much of what distinguishes respondents' profiles lies along one continuum\", correct: true, why: \"The higher-order model spends one parameter per attribute because it ties the attributes to a single $\\\\theta$. If that fits better than hundreds of free class shares, the profiles are mostly ordered along that $\\\\theta$.\"},\n    {text: \"The Q-matrix is wrong\", correct: false, why: \"Both models use the same Q-matrix. They differ only in how respondents are spread over the profiles.\"},\n    {text: \"The attributes are unrelated to one another\", correct: false, why: \"The opposite: the higher-order model says every attribute depends on the same $\\\\theta$, so attributes go together.\"}\n  ]\n})\n```\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: with one attribute, the higher-order DINA item is a 4PL\n\n**Assumptions:** the DINA model for item $i$, with guess $g$ and slip $s$; a higher-order model in which, given a continuous $\\theta$, attribute $k$ is mastered with probability $\\text{logistic}(\\lambda(\\theta - \\delta_k))$, independently across attributes.\n\nGiven $\\theta$, a respondent answers correctly either by having every required attribute and not slipping, or by lacking one and guessing:\n$$\\Pr(x_i = 1 \\mid \\theta) = (1 - s)\\,P_{\\text{all}}(\\theta) + g\\,\\big(1 - P_{\\text{all}}(\\theta)\\big) = g + (1 - s - g)\\,P_{\\text{all}}(\\theta),$$\nwhere $P_{\\text{all}}(\\theta) = \\prod_{k:\\,q_{ik}=1} \\text{logistic}(\\lambda(\\theta - \\delta_k))$ is the probability of having all of them.\n\nWith one required attribute, $P_{\\text{all}}(\\theta) = \\text{logistic}(\\lambda(\\theta - \\delta))$, and\n$$\\Pr(x_i = 1 \\mid \\theta) = g + \\big((1 - s) - g\\big)\\,\\frac{\\exp(\\lambda(\\theta - \\delta))}{1 + \\exp(\\lambda(\\theta - \\delta))},$$\nwhich is the 4PL with $c = g$, $u = 1 - s$, slope $a = \\lambda$ and difficulty $b = \\delta$. The curve's location and slope belong to the attribute: every item that needs only attribute $k$ has the same slope and difficulty and differs only in its asymptotes.\n\nWith $m \\ge 2$ attributes, $P_{\\text{all}}$ is a product of logistic curves, which isn't a logistic curve. In log-odds its lower tail has slope $m\\lambda$ and its upper tail slope $\\lambda$, so it leaves the floor abruptly and approaches the top slowly; and at the largest threshold every other factor is above 0.5 and that one equals 0.5, so its midpoint sits to the right of every $\\delta_k$. As $\\lambda$ grows, each factor becomes a step at $\\delta_k$ and the product a step at the largest threshold. So the higher-order DINA is a unidimensional IRT model whose item curves are built from the Q-matrix. [DeCarlo (2011)](https://doi.org/10.1177/0146621610377081) fits a logistic version of DINA with software for latent class analysis, along the same lines.\n:::\n\n## Simulate\n\nThe code simulates 1,000 respondents answering ten items on three attributes and fits DINA with `GDINA` ([Ma & de la Torre, 2020](https://doi.org/10.18637/jss.v093.i14)), then G-DINA, then DINA with one wrong Q-matrix entry. The first run takes about half a minute, most of it installing `GDINA`.\n\nWith the seed as written, guesses and slips come back within about 0.05 of the truth, except item 7's slip (0.18 true, 0.27 estimated), on the item needing all three attributes. Each attribute is classified correctly for 94% to 95% of respondents, the whole profile for 84%. AIC prefers DINA (10,692) to G-DINA (10,712), as it should: DINA generated the data. Telling the model that item 4 needs only A1 (it needs A1 and A2) sends its slip from 0.19 to 0.50: respondents with A1 but not A2 now count as able, and get it wrong. The AIC rises to 10,828. Try `n <- 300`, or make some profiles rare in `share`.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-19\n# Simulate responses from the DINA model, fit it with GDINA (Ma & de la Torre, 2020),\n# and compare the estimates and classifications with the truth. Then misstate one\n# entry of the Q-matrix and see where the misfit goes.\nlibrary(GDINA)\nset.seed(49)\n\nn <- 1000   # respondents\n# Ten items, three attributes. Each attribute has an item that needs it alone.\nQ <- matrix(c(1,0,0,  0,1,0,  0,0,1,  1,1,0,  1,0,1,\n              0,1,1,  1,1,1,  1,0,0,  0,1,0,  0,0,1), ncol = 3, byrow = TRUE,\n            dimnames = list(paste0(\"item\", 1:10), paste0(\"A\", 1:3)))\nprofiles <- as.matrix(expand.grid(A1 = 0:1, A2 = 0:1, A3 = 0:1))   # all 2^3 = 8\nshare <- rep(1 / 8, 8)                                              # how common each is\nguess <- runif(10, 0.05, 0.25)\nslip  <- runif(10, 0.05, 0.25)\n\nalpha <- profiles[sample(8, n, replace = TRUE, prob = share), ]\n# eta = 1 when a respondent has every attribute the item needs\neta <- (alpha %*% t(Q)) == matrix(rowSums(Q), n, 10, byrow = TRUE)\np <- ifelse(eta, 1 - matrix(slip, n, 10, byrow = TRUE), matrix(guess, n, 10, byrow = TRUE))\nX <- matrix(rbinom(n * 10, 1, p), n, 10, dimnames = list(NULL, rownames(Q)))\n\nfit <- GDINA(X, Q, model = \"DINA\", verbose = 0)\ngs <- coef(fit, \"gs\")\nprint(round(cbind(guess_true = guess, guess_est = gs[, \"guessing\"],\n                  slip_true = slip, slip_est = gs[, \"slip\"]), 2))\n\n# Classification: each respondent's most probable profile\nmap <- personparm(fit, \"MAP\")[, 1:3]\ncat(\"\\nAttribute-by-attribute agreement with the truth:\", round(colMeans(map == alpha), 3), \"\\n\")\ncat(\"Whole profile right:\", round(mean(rowSums(map == alpha) == 3), 3), \"\\n\")\n\n# The saturated G-DINA model frees every combination of an item's attributes\nfit_g <- GDINA(X, Q, model = \"GDINA\", verbose = 0)\ncat(\"\\nAIC: DINA\", round(AIC(fit)), \" G-DINA\", round(AIC(fit_g)), \"\\n\")\n\n# Misstate one entry: tell the model item 4 needs only A1 (it needs A1 and A2)\nQ_wrong <- Q\nQ_wrong[4, \"A2\"] <- 0\nfit_w <- GDINA(X, Q_wrong, model = \"DINA\", verbose = 0)\ncat(\"\\nItem 4, true Q:  guess\", round(gs[4, \"guessing\"], 2), \" slip\", round(gs[4, \"slip\"], 2), \"\\n\")\ngw <- coef(fit_w, \"gs\")\ncat(\"Item 4, wrong Q: guess\", round(gw[4, \"guessing\"], 2), \" slip\", round(gw[4, \"slip\"], 2), \"\\n\")\ncat(\"AIC: true Q\", round(AIC(fit)), \" wrong Q\", round(AIC(fit_w)), \"\\n\")\n\n```\n:::\n\n\n[Download this code](code/cdm-sim.R) to run it as large as you like in your own R session.\n\n## With real data\n\n\n\n[cdm_ecpe](https://itemresponsewarehouse.org/tables/cdm_ecpe/) has two jobs: the latent class example, fit without a Q-matrix to ask whether its classes come out ordered, and the contrast for cognitive diagnosis, a test whose attributes may be one scale in disguise. [frac20](https://itemresponsewarehouse.org/tables/frac20/) is the main example, Tatsuoka's fraction subtraction items. Both tables carry their Q-matrix in `Qmatrix__` columns. [Download the code](code/cdm-irw.R); it needs `poLCA`, `GDINA` and `mirt` ([Chalmers, 2012](https://doi.org/10.18637/jss.v048.i06)).\n\n### ECPE: classes without a Q-matrix\n\nThe Examination for the Certificate of Proficiency in English (ECPE) data are 28 grammar items answered by 2,922 respondents, from a tutorial by [Templin and Hoffman (2013)](https://doi.org/10.1111/emip.12010). The Q-matrix codes three attributes: morphosyntactic, cohesive and lexical rules (`CDM` package documentation; [George et al., 2016](https://doi.org/10.18637/jss.v074.i02)). Keying: 1 is correct.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nsuppressPackageStartupMessages({library(poLCA); library(GDINA); library(mirt)})\noptions(digits = 7)  # R's default, in case a .Rprofile changes it\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.cdm_ecpe/rows?format=csv\"\necpe <- read.csv(url)\n# One row per response; the Q-matrix travels in the Qmatrix__ columns.\nwide <- reshape(ecpe[, c(\"id\", \"item\", \"resp\")], idvar = \"id\", timevar = \"item\",\n                direction = \"wide\")\nwide <- wide[order(wide$id), ]\ne_items <- paste0(\"E\", 1:28)\nXe <- as.matrix(wide[, paste0(\"resp.\", e_items)])\ncolnames(Xe) <- e_items\nQe <- unique(ecpe[, c(\"item\", \"Qmatrix__skill1\", \"Qmatrix__skill2\", \"Qmatrix__skill3\")])\nQe <- as.matrix(Qe[match(e_items, Qe$item), -1])\ncolnames(Qe) <- c(\"morphosyntactic\", \"cohesive\", \"lexical\")\ncat(nrow(Xe), \"respondents,\", ncol(Xe), \"items,\", sum(is.na(Xe)), \"missing responses\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2922 respondents, 28 items, 0 missing responses\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncat(\"Proportion correct: from\", min(round(colMeans(Xe), 2)), \"to\", max(round(colMeans(Xe), 2)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProportion correct: from 0.43 to 0.9 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same data ship with GDINA; check that the copies agree.\ndata(realdata_ECPE, package = \"GDINA\")\ncat(\"Same responses as GDINA's copy:\", all(Xe == as.matrix(realdata_ECPE$dat)),\n    \"  Same Q-matrix:\", all(Qe == as.matrix(realdata_ECPE$Q)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSame responses as GDINA's copy: TRUE   Same Q-matrix: TRUE \n```\n\n\n:::\n:::\n\n\nNothing is missing, and proportions correct run from 0.43 to 0.90. First, set the attributes aside and fit one to five classes:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# poLCA wants categories coded 1, 2, ...; nrep = 5 starts each fit from five random\n# places and keeps the best, since EM can stop on a local maximum.\nd <- as.data.frame(Xe + 1)\nf <- as.formula(paste(\"cbind(\", paste(e_items, collapse = \",\"), \") ~ 1\"))\nset.seed(252)\nlca <- lapply(1:5, function(k)\n  poLCA(f, d, nclass = k, nrep = if (k == 1) 1 else 5, maxiter = 3000, verbose = FALSE))\nrasch_e <- mirt(Xe, 1, \"Rasch\", verbose = FALSE)\ntwopl_e <- mirt(Xe, 1, \"2PL\", verbose = FALSE)\nfits <- data.frame(\n  model = c(paste(1:5, \"classes\"), \"Rasch\", \"2PL\"),\n  logLik = round(c(sapply(lca, `[[`, \"llik\"), extract.mirt(rasch_e, \"logLik\"),\n                   extract.mirt(twopl_e, \"logLik\")), 1),\n  parameters = c(sapply(lca, `[[`, \"npar\"), extract.mirt(rasch_e, \"nest\"),\n                 extract.mirt(twopl_e, \"nest\")),\n  AIC = round(c(sapply(lca, `[[`, \"aic\"), extract.mirt(rasch_e, \"AIC\"),\n                extract.mirt(twopl_e, \"AIC\"))),\n  BIC = round(c(sapply(lca, `[[`, \"bic\"), extract.mirt(rasch_e, \"BIC\"),\n                extract.mirt(twopl_e, \"BIC\"))))\nprint(fits, row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     model   logLik parameters   AIC   BIC\n 1 classes -45376.9         28 90810 90977\n 2 classes -42972.7         57 86059 86400\n 3 classes -42547.8         86 85268 85782\n 4 classes -42453.2        115 85136 85824\n 5 classes -42402.6        144 85093 85954\n     Rasch -42729.8         29 85518 85691\n       2PL -42546.7         56 85205 85540\n```\n\n\n:::\n:::\n\n\nBIC chooses three classes (85,782); AIC keeps falling through five. But the 2PL has a lower BIC (85,540) than any class model, and with 56 parameters its log likelihood (−42,546.7) matches the three-class model's (−42,547.8) with 86. Are the classes ordered?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Put each solution's classes in order of their average proportion correct, then\n# count the items on which a higher class does worse than the class below it.\nclass_probs <- function(fit) {\n  P <- sapply(fit$probs, function(p) p[, 2])   # classes x items: P(correct)\n  o <- order(rowMeans(P))\n  list(P = P[o, , drop = FALSE], share = fit$P[o])\n}\nfor (k in 2:5) {\n  cp <- class_probs(lca[[k]])\n  out_of_order <- sum(apply(cp$P, 2, function(v) any(diff(v) < 0)))\n  cat(sprintf(\"%d classes: shares %s; mean P(correct) %s; items out of order: %d\\n\", k,\n              paste(sprintf(\"%.2f\", cp$share), collapse = \" \"),\n              paste(sprintf(\"%.2f\", rowMeans(cp$P)), collapse = \" \"), out_of_order))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2 classes: shares 0.47 0.53; mean P(correct) 0.58 0.84; items out of order: 0\n3 classes: shares 0.19 0.51 0.30; mean P(correct) 0.48 0.70 0.89; items out of order: 0\n4 classes: shares 0.13 0.38 0.37 0.12; mean P(correct) 0.44 0.64 0.81 0.94; items out of order: 0\n5 classes: shares 0.14 0.35 0.11 0.29 0.11; mean P(correct) 0.45 0.65 0.74 0.82 0.94; items out of order: 15\n```\n\n\n:::\n:::\n\n\nUp to four classes, yes, like the continuum in the first widget. The five-class solution puts 15 items out of order. Where do its classes cross?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The five-class solution, with its items grouped by the attributes the ECPE's\n# Q-matrix says they need (1 = needed; order: morphosyntactic, cohesive, lexical).\ncp5 <- class_probs(lca[[5]])\npattern <- apply(Qe, 1, paste, collapse = \"\")\ntab5 <- aggregate(t(cp5$P), list(Q_row = pattern), mean)\nnames(tab5)[-1] <- paste0(\"class\", 1:5)\ntab5$items <- as.vector(table(pattern)[tab5$Q_row])\nprint(cbind(tab5[, 1, drop = FALSE], round(tab5[, 2:6], 2), items = tab5$items), row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Q_row class1 class2 class3 class4 class5 items\n   001   0.47   0.74   0.81   0.88   0.95    10\n   010   0.57   0.74   0.66   0.87   0.93     4\n   011   0.70   0.90   0.87   0.93   0.98     1\n   100   0.42   0.52   0.68   0.71   0.93     5\n   101   0.30   0.50   0.71   0.77   0.95     7\n   110   0.60   0.76   0.77   0.89   0.97     1\n```\n\n\n:::\n:::\n\n\nClass 3 (11% of respondents) beats class 2 on items needing morphosyntactic rules (0.68 against 0.52 on the five needing only those, 0.71 against 0.50 on the seven also needing lexical rules) and trails it on the four needing only cohesive rules (0.66 against 0.74). That is a class that differs in which items it finds hard, and the difference follows the Q-matrix, which the fit never saw. But BIC doesn't support a fifth class (85,954 against 85,782 for three). The unrestricted classes mostly come out ordered: a continuum cut into pieces.\n\n### Fraction subtraction: DINA\n\nThese are 536 students' responses to the 20 items ([Tatsuoka, 2002](https://doi.org/10.1111/1467-9876.00272)); the IRW table matches the copy in `GDINA`. Keying: 1 is correct.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.frac20/rows?format=csv\"\nfrac <- read.csv(url)\nwide <- reshape(frac[, c(\"id\", \"item\", \"resp\")], idvar = \"id\", timevar = \"item\",\n                direction = \"wide\")\nwide <- wide[order(wide$id), ]\nf_items <- paste0(\"item_\", 1:20)\nXf <- as.matrix(wide[, paste0(\"resp.\", f_items)])\ncolnames(Xf) <- f_items\nQf <- unique(frac[, c(\"item\", paste0(\"Qmatrix__\", 1:8))])\nQf <- as.matrix(Qf[match(f_items, Qf$item), -1])\ncolnames(Qf) <- paste0(\"A\", 1:8)\ncat(nrow(Xf), \"respondents,\", ncol(Xf), \"items,\", sum(is.na(Xf)), \"missing responses\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n536 respondents, 20 items, 0 missing responses\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ndata(realdata_Tatsuoka1990, package = \"GDINA\")\ncat(\"Same responses as GDINA's copy:\", all(Xf == as.matrix(realdata_Tatsuoka1990$dat)),\n    \"  Same Q-matrix:\", all(Qf == as.matrix(realdata_Tatsuoka1990$Q)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSame responses as GDINA's copy: TRUE   Same Q-matrix: TRUE \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncat(\"Attributes per item:\", rowSums(Qf), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAttributes per item: 3 2 2 4 4 1 3 1 1 4 3 2 4 2 2 2 3 4 5 4 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncat(\"Items needing each attribute:\", colSums(Qf), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nItems needing each attribute: 3 13 3 5 8 2 19 3 \n```\n\n\n:::\n:::\n\n\nItems need one to five attributes. A7 is needed by 19 items and A2 by 13; A1, A3 and A8 by three each, and A6 by two. Now DINA:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\ndina_f <- GDINA(Xf, Qf, model = \"DINA\", verbose = 0)\ngs <- coef(dina_f, \"gs\")\nprint(round(t(gs[, c(\"guessing\", \"slip\")]), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Item 1 Item 2 Item 3 Item 4 Item 5 Item 6 Item 7 Item 8 Item 9 Item 10\nguessing   0.03   0.02   0.00   0.22   0.30   0.10   0.03   0.44   0.29    0.03\nslip       0.09   0.04   0.13   0.11   0.17   0.04   0.20   0.18   0.25    0.21\n         Item 11 Item 12 Item 13 Item 14 Item 15 Item 16 Item 17 Item 18\nguessing    0.07    0.13    0.01    0.06    0.03    0.11    0.04    0.12\nslip        0.08    0.04    0.33    0.06    0.11    0.11    0.14    0.14\n         Item 19 Item 20\nguessing    0.02    0.01\nslip        0.24    0.16\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncat(sprintf(\"Items with slip at most 0.25: %d of 20. Largest guess: %.2f (item %d)\\n\",\n            sum(gs[, \"slip\"] <= 0.25), max(gs[, \"guessing\"]), which.max(gs[, \"guessing\"])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nItems with slip at most 0.25: 19 of 20. Largest guess: 0.44 (item 8)\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncat(\"Log likelihood\", round(logLik(dina_f), 1), \"with\", npar(dina_f)$`No. of parameters`,\n    \"parameters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLog likelihood -4402.3 with 295 parameters\n```\n\n\n:::\n:::\n\n\nSlips are at most 0.25 on 19 items; item 13's is 0.33. Most guesses are near zero, as expected for free-response subtraction. Item 8 stands out with a guess of 0.44: it needs only A7, yet students without A7 answer it correctly 44% of the time by the model's estimate. Perhaps it can be solved another way, or its Q row misses something. Who has which attributes?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nprev <- extract(dina_f, \"prevalence\")$all[, \"Level1\"]\ncat(\"Proportion mastering each attribute:\", round(prev, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProportion mastering each attribute: 0.58 0.77 0.72 0.69 0.6 0.79 0.81 0.82 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\natt_f <- personparm(dina_f, \"EAP\")   # attribute mastered if its posterior probability > 0.5\nn_att <- rowSums(att_f)\ncat(\"Respondents with all eight:\", sum(n_att == 8), sprintf(\"(%.1f%%)\", 100 * mean(n_att == 8)),\n    \"  Distinct profiles among\", nrow(att_f), \"respondents:\",\n    length(unique(apply(att_f, 1, paste, collapse = \"\"))), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRespondents with all eight: 200 (37.3%)   Distinct profiles among 536 respondents: 49 \n```\n\n\n:::\n:::\n\n\nBetween 58% (A1) and 82% (A8) of students master each attribute, and 200 of 536 (37.3%) are classified as having all eight. Counting an attribute as mastered when its posterior probability is above 0.5, the students fall into 49 profiles.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd): under the Rasch model the sum score is sufficient for $\\theta$. Two respondents with the same number right get the same estimate, whichever items they got right.\n:::\n\nDINA reads *which* items. Among students with the same sum score, do the profiles differ?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nr <- rowSums(Xf)\nprofile <- apply(att_f, 1, paste, collapse = \"\")\nby_r <- data.frame(sum_score = sort(unique(r)),\n                   respondents = as.vector(table(r)),\n                   profiles = as.vector(tapply(profile, r, function(p) length(unique(p)))),\n                   fewest_attributes = as.vector(tapply(n_att, r, min)),\n                   most_attributes = as.vector(tapply(n_att, r, max)))\nprint(by_r[by_r$sum_score %in% c(0, 5, 10, 15, 20), ], row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sum_score respondents profiles fewest_attributes most_attributes\n         0          13        1                 0               0\n         5          31       11                 2               5\n        10          16       10                 5               7\n        15          23        3                 7               8\n        20          30        1                 8               8\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncat(\"\\nThe 16 respondents with 10 correct, by profile (A1 ... A8):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nThe 16 respondents with 10 correct, by profile (A1 ... A8):\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nprint(sort(table(profile[r == 10]), decreasing = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n01010111 11010111 01110111 00111111 01011110 01101011 01110011 10010111 \n       4        3        2        1        1        1        1        1 \n11101111 11110111 \n       1        1 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nrasch_f <- mirt(Xf, 1, \"Rasch\", verbose = FALSE)\ntheta_f <- fscores(rasch_f)[, 1]\ncat(\"\\nCorrelation of attributes mastered with the sum score:\", round(cor(n_att, r), 2),\n    \"; with Rasch theta:\", round(cor(n_att, theta_f), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCorrelation of attributes mastered with the sum score: 0.95 ; with Rasch theta: 0.93 \n```\n\n\n:::\n:::\n\n\nAt a sum score of 10, 16 students fall into 10 different profiles, with five to seven attributes; at 0 and at 20 everyone shares a profile. The number of attributes mastered correlates 0.95 with the sum score and 0.93 with the Rasch $\\theta$. The count of attributes mostly says what the sum score says; the profile adds which skills lie behind it, and that addition rests on the Q-matrix. How do the models compare?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\ngdina_f <- GDINA(Xf, Qf, model = \"GDINA\", verbose = 0)\nho_f <- GDINA(Xf, Qf, model = \"DINA\", att.dist = \"higher.order\", verbose = 0)\ntwopl_f <- mirt(Xf, 1, \"2PL\", verbose = FALSE)\ncdm_row <- function(name, m) data.frame(model = name, logLik = round(as.numeric(logLik(m)), 1),\n  parameters = npar(m)$`No. of parameters`, AIC = round(AIC(m)), BIC = round(BIC(m)))\nirt_row <- function(name, m) data.frame(model = name, logLik = round(extract.mirt(m, \"logLik\"), 1),\n  parameters = extract.mirt(m, \"nest\"), AIC = round(extract.mirt(m, \"AIC\")),\n  BIC = round(extract.mirt(m, \"BIC\")))\nprint(rbind(cdm_row(\"DINA\", dina_f), cdm_row(\"G-DINA\", gdina_f),\n            cdm_row(\"higher-order DINA\", ho_f), irt_row(\"Rasch\", rasch_f),\n            irt_row(\"2PL\", twopl_f)), row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             model  logLik parameters  AIC   BIC\n              DINA -4402.3        295 9395 10658\n            G-DINA -4265.8        445 9422 11328\n higher-order DINA -4509.6         48 9115  9321\n             Rasch -4796.3         21 9635  9725\n               2PL -4640.1         40 9360  9532\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The higher-order model: each attribute is a Rasch-type item on one theta (slope\n# fixed at 1, GDINA's default), so its profile distribution has 8 parameters, not 255.\ncat(\"\\nHigher-order DINA, attribute intercepts:\", round(coef(ho_f, \"lambda\")[, \"intercept\"], 2),\n    \"; slopes:\", unique(coef(ho_f, \"lambda\")[, \"slope\"]), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nHigher-order DINA, attribute intercepts: 0.44 2.48 2.86 1.21 0.58 3.6 1.39 2.54 ; slopes: 1 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# A Q-matrix with no thought behind it: redraw the entries for attributes 5 to 8 at\n# random, keeping each attribute's share of items (as in 252's c7/3_cdm.R).\nset.seed(10103101)\nQ_random <- Qf\nfor (k in 5:8) Q_random[, k] <- rbinom(20, 1, mean(Qf[, k]))\ndina_random <- GDINA(Xf, Q_random, model = \"DINA\", verbose = 0)\ncat(\"\\nDINA with attributes 5-8 of the Q-matrix redrawn at random: AIC\", round(AIC(dina_random)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDINA with attributes 5-8 of the Q-matrix redrawn at random: AIC 9769 \n```\n\n\n:::\n:::\n\n\nDINA beats the Rasch model by AIC (9,395 against 9,635) but not the 2PL (9,360), and by BIC trails both: 255 of its 295 parameters are class shares. G-DINA's extra parameters don't pay (AIC 9,422). The higher-order DINA wins on both criteria (AIC 9,115, BIC 9,321, 48 parameters), with all its attributes riding on one $\\theta$. The Q-matrix carries information: with attributes 5 to 8 redrawn at random, the AIC rises to 9,769. Do the data suggest a better one?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Empirical Q-matrix validation by the proportion of variance accounted for (PVAF;\n# de la Torre & Chiu, 2016), starting from the DINA fit and from the G-DINA fit.\n# For each suggestion, refit the same model with the suggested Q-matrix.\nfor (m in list(list(\"DINA\", dina_f), list(\"GDINA\", gdina_f))) {\n  Q_sug <- extract(Qval(m[[2]], method = \"PVAF\", eps = 0.95), \"sug.Q\")\n  changed <- which(rowSums(Q_sug != Qf) > 0)\n  refit <- GDINA(Xf, Q_sug, model = m[[1]], verbose = 0)\n  cat(sprintf(\"From %s: changes suggested to %d items (%s). AIC %.0f with the original Q, %.0f with the suggested one.\\n\",\n              m[[1]], length(changed), paste(changed, collapse = \", \"), AIC(m[[2]]), AIC(refit)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrom DINA: changes suggested to 10 items (4, 5, 7, 8, 9, 10, 13, 16, 19, 20). AIC 9395 with the original Q, 9527 with the suggested one.\nFrom GDINA: changes suggested to 8 items (1, 4, 7, 8, 9, 12, 13, 19). AIC 9422 with the original Q, 9340 with the suggested one.\n```\n\n\n:::\n:::\n\n\nStarting from the DINA fit, PVAF suggests changing 10 of the 20 items, and DINA refit with the suggested matrix is worse (AIC 9,527 against 9,395). Starting from G-DINA, the model the method is defined under, it suggests 8, and G-DINA with the suggested matrix improves (9,340 against 9,422). The suggestions depend on the starting model, and one is worth taking only if it survives a refit and a look at the item (problem 3).\n\n### ECPE with its Q-matrix\n\nBack to the ECPE, now with its three attributes and eight profiles.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"G-DINA estimates the share of ECPE respondents in each of the eight profiles of three attributes. How many profiles does it take to hold at least 90% of respondents?\",\n  choices: [\"Two\", \"Four\", \"Six\", \"All eight, roughly evenly\"],\n  answer: \"Four\",\n  reveal: \"Four profiles hold 0.956 of respondents: none of the three attributes (0.302), lexical rules only (0.125), lexical and cohesive (0.180), and all three (0.349). They form a chain. The output is below.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\ngdina_e <- GDINA(Xe, Qe, model = \"GDINA\", verbose = 0)\nshares <- extract(gdina_e, \"posterior.prob\")[1, ]\nprint(round(sort(shares, decreasing = TRUE), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  111   000   011   001   101   110   010   100 \n0.349 0.302 0.180 0.125 0.016 0.014 0.012 0.002 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncat(\"Four largest profiles together:\", round(sum(sort(shares, decreasing = TRUE)[1:4]), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFour largest profiles together: 0.956 \n```\n\n\n:::\n:::\n\n\nFour profiles hold 95.6% of respondents, the other four under 2% each. The four form a chain: lexical rules first, then cohesive, then morphosyntactic, so knowing how many attributes a respondent has tells you which. [Templin and Bradshaw (2014)](https://doi.org/10.1007/s11336-013-9362-0) used these data to test for such a hierarchy. With only the four profiles allowed:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\ndina_e <- GDINA(Xe, Qe, model = \"DINA\", verbose = 0)\n# G-DINA allowed only the four profiles of a chain: none, lexical, lexical + cohesive, all\nchain <- matrix(c(0, 0, 0,  0, 0, 1,  0, 1, 1,  1, 1, 1), ncol = 3, byrow = TRUE)\ngdina_chain <- GDINA(Xe, Qe, model = \"GDINA\", att.str = chain, verbose = 0)\nprint(rbind(cdm_row(\"DINA\", dina_e), cdm_row(\"G-DINA\", gdina_e),\n            cdm_row(\"G-DINA, four-profile chain\", gdina_chain),\n            irt_row(\"Rasch\", rasch_e), irt_row(\"2PL\", twopl_e)), row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      model   logLik parameters   AIC   BIC\n                       DINA -42841.6         63 85809 86186\n                     G-DINA -42738.6         81 85639 86124\n G-DINA, four-profile chain -42751.3         68 85639 86045\n                      Rasch -42729.8         29 85518 85691\n                        2PL -42546.7         56 85205 85540\n```\n\n\n:::\n:::\n\n\nThe chain matches the full G-DINA's AIC (85,639) with 13 fewer parameters, so its BIC is better (86,045 against 86,124). But the Rasch model (AIC 85,518) and the 2PL (85,205) beat every CDM on both criteria. A four-step chain is an ordinal scale, and here the continuum describes the responses better. Both routes through the ECPE, classes without a Q-matrix and profiles with one, arrive at ordered groups. In the fraction data the Q-matrix adds information, but the model that uses it best ties the attributes to one continuum.\n\n<!-- TODO (Ben, F27): first-person verdict goes here, on the practitioner's choice of whether to fit a CDM. Candidate from the outline: \"a CDM earns its keep only when the Q-matrix was designed into the test, not retrofitted to it.\" On hold with Ben; nothing on the page until he decides. -->\n\n## Problems\n\n1. **The DINA likelihood.** Write the likelihood of one respondent's responses under DINA as a latent class model over the $2^K$ profiles. Show that with a single attribute ($K = 1$), DINA is a two-class latent class model whose item probabilities are $g_i$ in one class and $1 - s_i$ in the other. How many parameters does each model have, and are they the same model?\n2. **The Q-matrix in an LLTM.** Fit `resp ~ 0 + Qmatrix__1 + ... + Qmatrix__8 + (1 | id)` to `frac20` with `glmer`, as in [What is an item?](explanatory-irt.qmd) (PS7#2 B). Do items with the same Q row have similar Rasch difficulties? What does the LLTM assume about attributes that DINA doesn't, and the reverse?\n3. **Held out.** Hold out a random 20% of `frac20` responses (set them to missing), fit the Rasch model, the 2PL, DINA and the higher-order DINA to the rest, and compute each model's IMV over the Rasch model on the held-out responses ([Model fit and out-of-sample prediction](fit-prediction.qmd)). Does the ranking agree with AIC? Then run the full PVAF analysis: which suggested changes make sense for the items as written? (PS7#2 D.)\n4. **Skill reports from a state test.** A district wants attribute-level reports for each student from a state mathematics test built from a blueprint of content strands, not a Q-matrix. Advise them. What would you want to see before any report goes home?\n5. **Design a Q-matrix.** Write a Q-matrix for eight items on three attributes in which each attribute has an item that needs it alone. Why does that matter for telling the $2^3$ profiles apart under DINA? Try a Q-matrix without such items in the simulation.\n6. **Challenge (open).** When attributes form a hierarchy, as the ECPE's appear to, is a CDM a new kind of model or a unidimensional model with cut points? Set out what each reading predicts about data you could collect, such as items needing a later attribute but not an earlier one. What would convince you?\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Latent%20classes%20and%20cognitive%20diagnosis%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20latent%20class%20analysis%20%28the%20model%2C%20EM%2C%20choosing%20the%20number%20of%20classes%20with%20BIC%2C%20and%20whether%20classes%20come%20out%20ordered%20like%20a%20continuum%20cut%20into%20pieces%29%20fit%20with%20poLCA%2C%20and%20cognitive%20diagnosis%20models%20as%20restricted%20latent%20class%20models%3A%20attributes%2C%20the%20Q-matrix%2C%20the%20DINA%2C%20DINO%20and%20G-DINA%20models%2C%20higher-order%20and%20hierarchical%20attribute%20structures%2C%20empirical%20Q-matrix%20validation%20%28PVAF%29%2C%20and%20comparisons%20with%20the%20Rasch%20model%20and%202PL%2C%20fit%20with%20the%20GDINA%20package%20to%20the%20ECPE%20grammar%20test%20and%20Tatsuoka%27s%20fraction%20subtraction%20data.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Rupp, A. A., Templin, J., & Henson, R. A. (2010). *Diagnostic measurement: Theory, methods, and applications*. Guilford Press. <https://openlibrary.org/works/OL15026394W>. A book-length treatment of cognitive diagnosis models, from Q-matrices to estimation.\n- Ma, W., & de la Torre, J. (2020). GDINA: An R package for cognitive diagnosis modeling. *Journal of Statistical Software*, 93(14). <https://doi.org/10.18637/jss.v093.i14>. The package used here, with examples.\n- Linzer, D. A., & Lewis, J. B. (2011). poLCA: An R package for polytomous variable latent class analysis. *Journal of Statistical Software*, 42(10). <https://doi.org/10.18637/jss.v042.i10>. Latent class models in R, including covariates for class membership.\n- Lindsay, B., Clogg, C. C., & Grego, J. (1991). Semiparametric estimation in the Rasch model and related exponential response models, including a simple latent class model for item analysis. *Journal of the American Statistical Association*, 86(413), 96–107. <https://doi.org/10.1080/01621459.1991.10475008>. Why a few ordered latent classes can stand in for the Rasch model's continuum.\n- de la Torre, J., & Douglas, J. A. (2004). Higher-order latent trait models for cognitive diagnosis. *Psychometrika*, 69(3), 333–353. <https://doi.org/10.1007/bf02295640>. Attributes driven by one continuous trait.\n- DeCarlo, L. T. (2011). On the analysis of fraction subtraction data: The DINA model, classification, latent class sizes, and the Q-matrix. *Applied Psychological Measurement*, 35(1), 8–26. <https://doi.org/10.1177/0146621610377081>. DINA fit as a latent class model to the fraction data, and how it classifies students who get every item wrong.\n- Templin, J., & Bradshaw, L. (2014). Hierarchical diagnostic classification models: A family of models for estimating and testing attribute hierarchies. *Psychometrika*, 79(2), 317–339. <https://doi.org/10.1007/s11336-013-9362-0>. Testing an attribute hierarchy, with a grammar test as the example.\n- Templin, J., & Bradshaw, L. (2013). Measuring the reliability of diagnostic classification model examinee estimates. *Journal of Classification*, 30(2), 251–275. <https://doi.org/10.1007/s00357-013-9129-4>. How consistently a CDM classifies respondents, a question this lesson leaves open.\n- Rost, J. (1990). Rasch models in latent classes: An integration of two approaches to item analysis. *Applied Psychological Measurement*, 14(3), 271–282. <https://doi.org/10.1177/014662169001400305>. Mixture IRT: a continuum within each class.\n- von Davier, M., & Rost, J. (2016). Logistic mixture-distribution response models. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 393–406). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315374512>. A handbook chapter on mixture item response models.\n- Wang, C., & Chang, H.-H. (2017). Cognitive diagnostic assessment. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 3. Applications* (pp. 329–348). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315117430>. A handbook chapter on cognitive diagnostic assessment.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`frac20`](https://itemresponsewarehouse.org/tables/frac20/): Tatsuoka, C. (2002). Data analytic methods for latent partially ordered classification models. Journal of the Royal Statistical Society: Series C (Applied Statistics), 51(3), 337-350. <https://doi.org/10.1111/1467-9876.00272>. Licence: GPL-3.0.\n- [`cdm_ecpe`](https://itemresponsewarehouse.org/tables/cdm_ecpe/): Templin, J., & Hoffman, L. (2013). Obtaining diagnostic classification model estimates using Mplus. Educational Measurement: Issues and Practice, 32, 37-50. <https://doi.org/10.1111/emip.12010>. Licence: GPL-3.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 7 (the c7 slides are missing from the export, so the lesson is built from the code) and problem set 7 (#2), with the code in `ben-domingue/252`: `c7/3_cdm.R` and `ps7/cdm.R`.\n- **Timing:** the core ideas and widgets take about 50 minutes; the real-data section is a 30-minute lab. The latent class fits take a minute or two, so run them before class.\n- **Changed from 252:** latent class analysis now comes first, as the general model; the ECPE's unrestricted classes and its four-profile chain are new. The DINA fit to the fraction data follows `c7/3_cdm.R` (same data and Q-matrix, and the same log likelihood, −4,402.3), including its randomly redrawn Q-matrix. Attributes are classified by posterior probability above 0.5 rather than by the most probable profile, because `personparm(..., \"MAP\")` breaks ties at random.\n- **Held back:** longitudinal CDMs (the IRW's `hmcdm_spatialreasoning` table), mixture IRT (in *Going further*) and the classification accuracy of attribute profiles are not taken up in this course. The held-out comparison and the full PVAF analysis are problem 3. `cdm_timss07` (15 attributes) is too slow for class.\n- **Verdict:** on hold with Ben (F27).\n- **Solutions:** held back in `solutions/cdm.qmd` (not published). Problem 6 is open.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}