{
  "hash": "f5d84c6054179a64b518218b25347b32",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Differential item functioning\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Fairness and invariance  \n**Tranche:** core (a first course)  \n**Before this:** [From the 1PL to the 4PL](1pl-to-4pl.qmd) · [Validity as an argument](validity-argument.qmd) · [Fairness in testing: bias, impact, and measurement invariance](fairness.qmd)  \n**Builds toward:** [Measurement invariance under treatment and life events](invariance-experience.qmd)  \n**Starts threads:** Items can function differently by treatment (→ [Measurement invariance under treatment and life events](invariance-experience.qmd))  \n**Picks up threads:** The sum score is sufficient under the Rasch model (from [The Rasch model](rasch.qmd)); A mean difference keeps its sign under every rescaling only under stochastic dominance (from [What is measurement?](measurement.qmd)); What we want from a measure: insensitive to nonfocal attributes, calibrated, precise quickly (from [What is measurement?](measurement.qmd)); A group difference is impact unless the measure works differently (from [Fairness in testing: bias, impact, and measurement invariance](fairness.qmd)); A bias shared by every item is invisible to invariance tests (from [Fairness in testing: bias, impact, and measurement invariance](fairness.qmd))  \n**IRW tables:** [`gilbert_meta_11`](https://itemresponsewarehouse.org/tables/gilbert_meta_11/), [`DART_Brysbaert_2020_1`](https://itemresponsewarehouse.org/tables/dart_brysbaert_2020_1/), [`alexandrowicz_2018_cesd`](https://itemresponsewarehouse.org/tables/alexandrowicz_2018_cesd/)  \n**From EDUC 252:** slides c5; problem sets PS5#3; code [`c5/art.R`](https://github.com/ben-domingue/252/blob/main/c5/art.R), [`ps5/dif_itemtext.R`](https://github.com/ben-domingue/252/blob/main/ps5/dif_itemtext.R), [`ps5/groupdiff.R`](https://github.com/ben-domingue/252/blob/main/ps5/groupdiff.R), [`ps5/groupdiff_example.R`](https://github.com/ben-domingue/252/blob/main/ps5/groupdiff_example.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n\n```{ojs}\n//| echo: false\nimport {grid, p2pl, palette} from \"./widgets/irt.js\"\nimport {simGroups, mhAll, mhPurified, logisticDIF} from \"./widgets/dif.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nTwo groups of children take a vocabulary test, and one group scores higher. Is the test fair to both? A difference in scores is not, by itself, evidence of unfairness: the groups may differ in vocabulary. What we can check is narrower and more useful. Take children from the two groups who do equally well on the test as a whole: do they find each item equally hard? An item on which they don't shows **differential item functioning** (DIF). [Fairness in testing](fairness.qmd) separated impact from bias; this lesson finds bias item by item. It builds the two standard methods, Mantel–Haenszel and logistic regression, takes on the question of what to match on, and applies all of it to a first-grade vocabulary test from a randomized trial, grouping the children seven demographic ways and then one more.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- say why a raw gap between groups mixes impact with DIF, and what matching does about it;\n- define uniform and non-uniform DIF with item characteristic curves, and say why DIF is always relative to the other items;\n- choose a matching variable, say what purifying it does, and say what robust scaling does instead;\n- run the Mantel–Haenszel procedure and classify items with the ETS A/B/C categories;\n- fit the three nested logistic-regression models for uniform and non-uniform DIF, and report an effect size;\n- read DIF by treatment in a randomized trial as item-to-item variation in the treatment effect.\n\n## Core ideas\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Fairness in testing](fairness.qmd): impact is a difference between groups in the construct itself; bias is a difference in scores that comes from something else. DIF is the item-level case of bias: an item that works differently for respondents who are equal on the construct.\n:::\n\n### DIF: the same item, at the same level of the construct\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [From the 1PL to the 4PL](1pl-to-4pl.qmd): an item characteristic curve's difficulty $b$ slides it left and right, and its slope $a$ sets how steeply it rises. Curves with different slopes cross.\n:::\n\nAn item shows DIF if respondents with the same $\\theta$ but in different groups have different chances of answering it correctly ([Lord, 1980, \"Study of item bias\"](https://doi.org/10.4324/9780203056615-20); [AERA, APA & NCME, 2014, p. 51](https://www.testingstandards.net/open-access-files.html)). Give each group its own curve. If they differ only in $b$, one group finds the item harder at every $\\theta$: **uniform DIF**. If they differ in $a$, the curves cross and the item favours one group at low $\\theta$ and the other at high: **non-uniform DIF**. The group we are asking about is the **focal** group; the comparison is the **reference** group.\n\n#### An example: who recognizes which authors?\n\nThe Dutch Author Recognition Test shows respondents 132 names and asks which are authors ([Brysbaert, Sui, Dirix & Hintz, 2020](https://doi.org/10.5334/joc.95); [DART_Brysbaert_2020_1](https://itemresponsewarehouse.org/tables/dart_brysbaert_2020_1/)). Its job here is intuition. Tastes in books differ by gender, which could presumably lead to some DIF: among respondents who recognize the same number of authors, do women and men recognize particular authors at different rates? Two notes on the data. Forty-two names are made-up foils, and in the IRW table a checked foil scores 1 like a recognized author, so we drop them using the paper's list. And the sample is small: 199 respondents, 67 of them men.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# The Dutch Author Recognition Test (Brysbaert, Sui, Dirix & Hintz, 2020): 132 names,\n# \"is this person an author?\". 42 names are made-up foils (the paper's Appendix A);\n# in the IRW table a checked name scores 1 whether or not it is a real author, so we\n# drop the foils and keep the 90 authors. 1 = recognized.\ndart_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v59_0.DART_Brysbaert_2020_1/rows?format=csv\"\ndart <- read.csv(dart_url)\ndart$name <- sub(\"^Is de volgende persoon een auteur- \\\\[(.*)\\\\]$\", \"\\\\1\", dart$item)\nfoils <- c(\"Andrée Oudin\", \"Chiara Ricci\", \"E.L. Wilford\", \"E. Buxton\", \"Elizabeth Wigelsworth\",\n  \"Emily Oldani\", \"Emmanuelle Duvernay\", \"Eric Ferey\", \"Georges Roudaut\", \"H. M. van der Grinten\",\n  \"Hans Ulfsson\", \"Hendrik van Weenen\", \"1ne Jessup\", \"John Kestley\", \"John Punnett\",\n  \"Jorge Eudoro Remache\", \"Judith L. Schecter\", \"Kathryn Lightner\", \"Kelly Weaver\",\n  \"Kettil Christoffersen\", \"Kim Wassing\", \"Konstantin Ryschkov\", \"Kyra Appels\", \"Ludwig Lorenz\",\n  \"Mahmoud Abdellah\", \"Marcus Fernandes\", \"Mark Robin\", \"Martijn van der Worp\",\n  \"Mathijs L. van Bueren\", \"Melanie Marrero Morales\", \"Pablo Daniel Gonzalez\", \"Pim Duijster\",\n  \"Richard Grigley\", \"Robert Teesdale\", \"Roberto Borsani\", \"Roy Leeman\", \"Sara Lakin\",\n  \"Theresa Ziegler\", \"Tim Singler\", \"Tomas Arensman\", \"Yasushi Sugawara\", \"Zofia Kwiatkowski\")\nc(foils_found = sum(foils %in% dart$name), names = length(unique(dart$name)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfoils_found       names \n         42         132 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# (The IRW labels \"1ne Jessup\", \"1ne Austen\" and \"1mes Patterson\" stand for Jane and James.)\naut <- dart[!dart$name %in% foils, ]\nA <- tapply(aut$resp, list(aut$id, aut$name), function(x) x[1])\nsex <- tapply(aut$cov_gender, aut$id, function(x) x[1])[rownames(A)]\ntable(sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsex\n  Man Vrouw \n   67   132 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nwomen <- as.integer(sex == \"Vrouw\")\ntotal <- rowSums(A)\nc(authors = ncol(A), respondents = nrow(A), missing = sum(is.na(A)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    authors respondents     missing \n         90         199           0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nround(tapply(total, sex, mean), 1)   # mean number of the 90 authors recognized\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Man Vrouw \n 33.9  30.8 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# For each author: the difference between women and men in the proportion who\n# recognize the author, first raw, then at the same total (women's totals as\n# weights: the standardization approach of Dorans & Kulick, 1986), and a\n# Mantel-Haenszel test of no difference at the same total.\nstd_gap <- function(y) {\n  pw <- tapply(y[women == 1], total[women == 1], mean)\n  pm <- tapply(y[women == 0], total[women == 0], mean)\n  k <- intersect(names(pw), names(pm))\n  wt <- table(total[women == 1])[k]\n  sum(wt * (pw[k] - pm[k])) / sum(wt)\n}\nmh_p <- function(y) {\n  keep <- total %in% as.numeric(names(which(table(total) > 1)))\n  tab <- table(factor(y[keep], 0:1), factor(women[keep], 0:1), total[keep])\n  mantelhaen.test(tab)$p.value\n}\ndres <- data.frame(raw_gap = colMeans(A[women == 1, ]) - colMeans(A[women == 0, ]),\n                   matched_gap = sapply(colnames(A), function(a) std_gap(A[, a])),\n                   p = sapply(colnames(A), function(a) mh_p(A[, a])))\ndres$p_holm <- p.adjust(dres$p, \"holm\")\nround(dres[order(dres$matched_gap), ][c(1:4, 87:90), ], 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                       | raw_gap| matched_gap|     p| p_holm|\n|:----------------------|-------:|-----------:|-----:|------:|\n|J.R.R. Tolkien         |  -0.222|      -0.225| 0.005|  0.415|\n|Tom Clancy             |  -0.296|      -0.199| 0.009|  0.780|\n|Tim Krabbé             |  -0.159|      -0.181| 0.030|  1.000|\n|Arnon Grunberg         |  -0.152|      -0.153| 0.013|  1.000|\n|Khaled Hosseini        |   0.105|       0.137| 0.054|  1.000|\n|Emily Brontë           |   0.141|       0.221| 0.010|  0.898|\n|Gabriel Garcia Márquez |   0.164|       0.245| 0.002|  0.174|\n|1ne Austen             |   0.317|       0.408| 0.000|  0.001|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nc(p_below_05 = sum(dres$p < 0.05), holm_below_05 = sum(dres$p_holm < 0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   p_below_05 holm_below_05 \n            9             1 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Recognition of four authors by total (in four bands), women and men.\nband <- cut(total, quantile(total, 0:4 / 4), include.lowest = TRUE)\nop <- par(mfrow = c(1, 4), mar = c(4, 3, 2, 0.5))\nfor (a in c(\"Tom Clancy\", \"J.R.R. Tolkien\", \"1ne Austen\", \"Emily Brontë\")) {\n  pr <- tapply(A[, a], list(band, women), mean)\n  plot(1:4, pr[, \"0\"], type = \"b\", pch = 19, col = \"#999\", ylim = c(0, 1), xaxt = \"n\",\n       xlab = \"Total (quartile)\", ylab = \"\", main = sub(\"1ne\", \"Jane\", a), cex.main = 0.9)\n  lines(1:4, pr[, \"1\"], type = \"b\", pch = 19, col = \"#2780e3\")\n  axis(1, 1:4)\n}\nlegend(\"bottomright\", c(\"men\", \"women\"), col = c(\"#999\", \"#2780e3\"), pch = 19, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](dif_files/figure-html/dart-plot-1.png){width=864}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\npar(op)\n```\n:::\n\n\nAt the same total, men recognize J.R.R. Tolkien 23 percentage points more often than women and Tom Clancy 20 points more often; women recognize Jane Austen 41 points more often, and Emily Brontë 22. Matching matters: men recognize a few more authors overall (34 of 90 on average, against 31), and Clancy's raw gap of 30 points shrinks to 20 once totals are equal. How firm is this? Nine of the 90 authors differ at $p < .05$ (a test built below), about twice the 4.5 expected by chance, but after a Holm correction for 90 tests only Austen remains. Read it as a picture of what DIF is (an item that works differently for people equal on the construct), not as a finding about these authors.\n\nThe widget shows why raw proportions won't do: the raw gap mixes impact with DIF.\n\n#### Try it: impact and DIF\n\nTwo groups of 1,000 answer ten Rasch items. The sliders set the focal group's mean ability (impact) and make item 5 alone harder for it (DIF). Top: raw gaps in proportion correct. Bottom: the Mantel–Haenszel delta (below), which compares the groups at the same total score.\n\n```{ojs}\n//| echo: false\nviewof w1_imp = Inputs.range([0, 1.5], {value: 1, step: 0.1, label: \"Impact (SDs of ability)\"})\nviewof w1_dif = Inputs.range([0, 1.5], {value: 0.8, step: 0.1, label: \"DIF on item 5 (logits)\"})\n```\n\n```{ojs}\n//| echo: false\nw1 = {\n  const {X, g} = simGroups({seed: 11, nPer: 1000, nItems: 10, impact: w1_imp, dif: w1_dif > 0 ? [{item: 4, db: w1_dif}] : []});\n  const mean = (grp, i) => X.reduce((s, r, j) => s + (g[j] === grp ? r[i] : 0), 0) / 1000;\n  const mh = mhAll(X, g);\n  return X[0].map((_, i) => ({item: `${i + 1}`, gap: mean(1, i) - mean(0, i), delta: mh[i].delta, ets: mh[i].ets, dif: i === 4 && w1_dif > 0}));\n}\nPlot.plot({\n  width: 700, height: 200, x: {label: \"Item\", domain: w1.map(d => d.item)}, y: {label: \"Raw gap in proportion correct\", domain: [-0.5, 0.1]},\n  marks: [Plot.ruleY([0]), Plot.barY(w1, {x: \"item\", y: \"gap\", fill: d => d.dif ? palette.contrast : palette.main})]\n})\n```\n\n```{ojs}\n//| echo: false\nPlot.plot({\n  width: 700, height: 200, x: {label: \"Item\", domain: w1.map(d => d.item)}, y: {label: \"MH delta (matched)\", domain: [-3.5, 1]},\n  marks: [Plot.ruleY([0]), Plot.ruleY([-1.5, -1, 1], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n          Plot.dot(w1, {x: \"item\", y: \"delta\", r: 6, fill: d => d.dif ? palette.contrast : palette.main})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Raw gaps run from ${d3.min(w1, d => d.gap).toFixed(2)} to ${d3.max(w1, d => d.gap).toFixed(2)}. Matched, item 5's delta is **${w1[4].delta.toFixed(2)}** (category ${w1[4].ets}); the other nine run from ${d3.min(w1.filter((d, i) => i !== 4), d => d.delta).toFixed(2)} to ${d3.max(w1.filter((d, i) => i !== 4), d => d.delta).toFixed(2)}.`\n```\n\nWith impact and no DIF, every raw gap is negative and the matched deltas sit near zero. Add DIF and only item 5's delta moves; among the raw gaps it is one negative bar among ten.\n\nNobody observes $\\theta$, so what goes on the x-axis? A score from the test itself: the total, the rest score (the total without the studied item), or $\\theta$ estimated from the other items. The items in the matching score are the **anchor**. Two things follow. First, DIF is relative to the anchor: if every item were harder for the focal group by the same amount, the matched comparison would find nothing, since a shift common to all items looks like impact. Second, DIF items contaminate the anchor. If some items are harder for the focal group, its total understates its $\\theta$, and clean items drift toward favouring it. The usual remedy is **purification**: drop the flagged items from the matching score and run the analysis again ([Holland & Thayer, 1986](https://doi.org/10.1002/j.2330-8516.1986.tb00186.x); [Candell & Drasgow, 1988](https://doi.org/10.1177/014662168801200304)). In simulations it helps when DIF runs mostly one way, and can cost a little when DIF is balanced ([Clauser, Mazor & Hambleton, 1993](https://doi.org/10.1207/s15324818ame0604_2); [Zwick, 2012, pp. 16–22](https://doi.org/10.1002/j.2333-8504.2012.tb02290.x)).\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is measurement?](measurement.qmd): on an ordinal scale, the sign of a group comparison is safe only when one group's distribution sits above the other's everywhere (stochastic dominance).\n:::\n\nImpact adds a subtler problem: with no DIF at all, if the reference group's $\\theta$ dominates, reference respondents at a given total still sit a little higher on $\\theta$, and matching can show spurious DIF in both directions ([Zwick, 1990](https://doi.org/10.3102/10769986015003185)). The total matches exactly only when it is sufficient for $\\theta$ (Go deeper, below).\n\n#### Try it: what to match on\n\nTwenty items, 1,000 respondents per group. Set the number and size of DIF items and the impact; match on the total or a purified total.\n\n```{ojs}\n//| echo: false\nviewof w3_k = Inputs.range([0, 8], {value: 4, step: 1, label: \"Items with DIF\"})\nviewof w3_size = Inputs.range([0, 1.2], {value: 0.7, step: 0.1, label: \"DIF size (logits)\"})\nviewof w3_imp = Inputs.range([0, 1.5], {value: 0.5, step: 0.1, label: \"Impact (SDs)\"})\nviewof w3_match = Inputs.radio([\"Total score\", \"Purified total\"], {value: \"Total score\", label: \"Match on\"})\n```\n\n```{ojs}\n//| echo: false\nw3 = {\n  const difItems = Array.from({length: w3_k}, (_, k) => 2 + 2 * k);\n  const {X, g} = simGroups({seed: 3, nPer: 1000, nItems: 20, impact: w3_imp, dif: difItems.map(i => ({item: i, db: w3_size}))});\n  const P = mhPurified(X, g);\n  const res = w3_match === \"Total score\" ? P.first : P.second;\n  return {rows: res.map(d => ({...d, label: `${d.item + 1}`, dif: difItems.includes(d.item)})), dropped: P.dropped};\n}\nPlot.plot({\n  width: 700, height: 260, x: {label: \"Item\", domain: w3.rows.map(d => d.label)}, y: {label: \"MH delta\", domain: [-3, 1.5]},\n  marks: [Plot.ruleY([0]), Plot.ruleY([-1.5, -1, 1, 1.5], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n          Plot.dot(w3.rows, {x: \"label\", y: \"delta\", r: 6, fill: d => d.dif ? palette.contrast : palette.main})]\n})\n```\n\n```{ojs}\n//| echo: false\n{\n  const clean = w3.rows.filter(d => !d.dif), bad = w3.rows.filter(d => d.dif);\n  const m = clean.reduce((s, d) => s + d.delta, 0) / clean.length;\n  return md`Clean items (blue): mean delta **${m.toFixed(2)}**, ${clean.filter(d => d.ets !== \"A\").length} in category B or C. DIF items (orange): ${bad.filter(d => d.ets !== \"A\").length} of ${bad.length} in B or C.${w3_match === \"Purified total\" ? ` Purification dropped ${w3.dropped} item${w3.dropped === 1 ? \"\" : \"s\"} from the matching score.` : \"\"}`\n}\n```\n\nAdd DIF items and the blue (clean) dots rise together: on a contaminated total, clean items look easier for the focal group. Purify and they come back toward zero.\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: the anchor problem, and robust scaling\n\n**Assumptions:** two groups; a unidimensional item response model (here the 2PL) fitted in each group; some unknown subset of items has DIF.\n\n**Why an anchor is unavoidable.** Fit the 2PL separately in each group and each fit fixes its own scale (mean 0, SD 1 for $\\theta$). To compare the groups we need the difference between their means, and each item gives an estimate of it: if item $i$ has no DIF, the shift in its intercept between groups, divided by its slope, is the difference in means. If *every* item shifted by the same amount, the data could not say whether the groups differ or the items do. Some items have to be assumed free of DIF (the anchor), or some other assumption has to pin down the scale. The matching score does this implicitly: it treats the whole test as the anchor. Purification refines the choice iteratively, but it starts from a contaminated total, and simulations disagree about when it helps ([Zwick, 2012, pp. 16–22](https://doi.org/10.1002/j.2333-8504.2012.tb02290.x)).\n\n**Robust scaling.** [Halpin (2024)](https://doi.org/10.1007/s11336-024-09957-6) recasts DIF as outlier detection. Each item's implied estimate of the group difference is one data point; items without DIF cluster around the true difference, and DIF items are outliers. A robust estimator of the centre (a redescending M-estimator, which gives far-out items zero weight) estimates the group difference without choosing anchors in advance, and it is tuned so that items without DIF are flagged at a chosen false-positive rate. Wald tests then compare each item with that robust centre. The paper develops it for the 2PL in two independent groups. The `robustDIF` package ([Halpin, 2026](https://doi.org/10.32614/CRAN.package.robustDIF)) implements it with Tukey's bisquare, taking separate `mirt` fits as input, and also tests whether ignoring DIF changes the estimated difference between groups. It is a reasonable choice when no set of items can be trusted as anchors in advance, as in a trial where the program may have moved any item. *With real data* runs it on the vocabulary test.\n:::\n\n::: {.callout-tip appearance=\"simple\"}\n**If you've done** [Factor analysis II](fa-confirmatory.qmd): an unequal loading in a multigroup factor model is non-uniform DIF and an unequal intercept is uniform DIF ([Meredith, 1993](https://doi.org/10.1007/BF02294825)); the model estimates the factor and the group difference jointly, while the methods here match on an observed score, one item at a time.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Every item on a test is 0.3 logits harder for group F than for group R, at every $\\\\theta$. What will a DIF analysis matched on the total score find?\",\n  options: [\n    {text: \"Essentially no DIF\", correct: true, why: \"A shift shared by every item looks exactly like a difference in $\\\\theta$. DIF is defined relative to the other items, so only departures from the common pattern show up.\"},\n    {text: \"Uniform DIF against F on every item\", correct: false, why: \"The matched comparison sets F respondents beside R respondents with the same total; if every item shifted equally, those respondents answer each item alike.\"},\n    {text: \"Non-uniform DIF, since the shift is the same size everywhere\", correct: false, why: \"Non-uniform DIF means the curves cross (different slopes). An equal shift in $b$ doesn't make curves cross.\"}\n  ]\n})\n```\n\n### The Mantel–Haenszel procedure and the ETS categories\n\nAt each total score $k$, cross group with right and wrong on the studied item. Write $A_k, B_k$ for the reference group's right and wrong answers, $C_k, D_k$ for the focal group's, and $n_k$ for everyone at that score. The common odds ratio\n$$\\hat\\alpha_{MH} = \\frac{\\sum_k A_k D_k / n_k}{\\sum_k B_k C_k / n_k}$$\npools the tables ([Mantel & Haenszel, 1959](https://doi.org/10.1093/jnci/22.4.719)); a chi-square tests whether it is 1. [Holland and Thayer (1986)](https://doi.org/10.1002/j.2330-8516.1986.tb00186.x) brought it to DIF, reported on ETS's scale of item difficulty,\n$$\\Delta_{MH} = -2.35 \\ln \\hat\\alpha_{MH},$$\nnegative when the item is harder for the focal group. ETS sorts items into three categories ([Zwick, 2012, pp. 3–4](https://doi.org/10.1002/j.2333-8504.2012.tb02290.x)):\n\n- **A** (negligible): the chi-square is not significant at .05, or $|\\Delta_{MH}| < 1$;\n- **C** (moderate to large): $|\\Delta_{MH}| \\ge 1.5$ and significantly greater than 1;\n- **B** (slight to moderate): everything else.\n\nNeeding only a matching score and counts, it is a reasonable first choice for uniform DIF in large samples. A relative standardizes the difference in proportions correct across score levels ([Dorans & Kulick, 1986](https://doi.org/10.1111/j.1745-3984.1986.tb00255.x)).\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: when the Mantel–Haenszel null is exact\n\n**Assumptions:** $I$ dichotomous items; the Rasch model holds in both groups with the *same* difficulties (no DIF); local independence; the groups may have any distributions of $\\theta$. Matching is on the total score $r$, studied item included.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd): the sum score is sufficient for $\\theta$. Conditioning on it removes $\\theta$: $\\Pr(\\mathbf{x} \\mid r, \\theta) = \\prod_i \\varepsilon_i^{x_i} / \\gamma_r(\\boldsymbol\\varepsilon)$, with $\\varepsilon_i = e^{-b_i}$ and $\\gamma_r$ the elementary symmetric function.\n:::\n\n**The item, given the total.** Add that conditional probability over the patterns with $x_i = 1$ and total $r$. Each is item $i$ right plus $r - 1$ right among the others, so\n$$\\Pr(x_i = 1 \\mid r, \\theta) = \\frac{\\varepsilon_i\\, \\gamma_{r-1}^{(i)}(\\boldsymbol\\varepsilon)}{\\gamma_r(\\boldsymbol\\varepsilon)},$$\nwhere $\\gamma_{r-1}^{(i)}$ is the elementary symmetric function of the other items. It contains no $\\theta$. Within a score level, every respondent, whatever their $\\theta$ and whichever group they belong to, has the same chance of getting item $i$ right. So in every $2 \\times 2$ table the population odds ratio is exactly 1, however different the groups' $\\theta$ distributions ([Holland & Thayer, 1986](https://doi.org/10.1002/j.2330-8516.1986.tb00186.x); [Zwick, 1990](https://doi.org/10.3102/10769986015003185)). Impact cannot pass for DIF.\n\n**Why the studied item belongs in the total.** Match on the rest score $s = r - x_i$ instead. Given $\\theta$, $x_i$ is independent of the other items, so $\\Pr(x_i = 1 \\mid s, \\theta) = \\Pr(x_i = 1 \\mid \\theta)$: $\\theta$ is back, and $s$ only partly pins it down. If the reference group's $\\theta$ is higher, its members at rest score $s$ are higher on average too, and every item appears to favour it (Zwick, 1990). Including the item looks like double counting; under the Rasch model it is what makes the comparison exact.\n\n**Why the 2PL loses this.** Under the 2PL, the weighted score $\\sum_i a_i x_i$ is sufficient, not $r$ ([From the 1PL to the 4PL](1pl-to-4pl.qmd)). Within a level of $r$, $\\theta$ still varies with *which* items were right, and its distribution there differs between groups whose $\\theta$ distributions differ. The odds ratios then drift from 1, in either direction, for items whose slopes differ from the rest. The simulation below shows it: with an impact of 1 SD, clean items are flagged more often when slopes vary than when they are equal.\n:::\n\nWith many items and large samples, something is nearly always significant. The categories add a size criterion, and at ETS it is the C items that go to review committees ([Zwick, 2012, p. 11](https://doi.org/10.1002/j.2333-8504.2012.tb02290.x)). A flag is a fact about an item in a sample. The *Standards* ask for a substantial explanation before an item is called biased ([AERA, APA & NCME, 2014, p. 51](https://www.testingstandards.net/open-access-files.html)), and it comes from the item's content, not the statistic. (If you've done [From construct map to items](instrument-building.qmd): the number flags the item; the text decides.)\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"An item has $\\\\Delta_{MH} = -0.6$ with $p < .001$ in a sample of 20,000. Which ETS category is it, and what does that mean?\",\n  options: [\n    {text: \"A: the difference is probably real but small, below the size ETS flags\", correct: true, why: \"Category A covers items that are not significant *or* have $|\\\\Delta| < 1$. With 20,000 respondents small differences are significant; the size rule keeps them from being flagged.\"},\n    {text: \"C, because the p-value is tiny\", correct: false, why: \"C needs $|\\\\Delta| \\\\ge 1.5$ as well as significance. The p-value reflects the sample size as much as the size of the DIF.\"},\n    {text: \"B, because it is significant and negative\", correct: false, why: \"B needs $|\\\\Delta| \\\\ge 1$. The sign says which group the item favours (here the reference group), not the category.\"}\n  ]\n})\n```\n\n### Logistic regression DIF\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The likelihood and logistic regression](likelihood.qmd): regressing chess responses on Elo, with an intercept for each problem, is an ordinary logistic regression fitted by maximum likelihood, and comparing log likelihoods compares models.\n:::\n\nThe most straightforward DIF analysis is that same logistic regression, one item at a time, with the matching score as the predictor ([Swaminathan & Rogers, 1990](https://doi.org/10.1111/j.1745-3984.1990.tb00754.x)). Fit three nested models for item $i$:\n$$\\begin{aligned}\nM_0:&\\quad \\text{logit} \\Pr(x_{ij} = 1) = \\beta_0 + \\beta_1 r_j,\\\\\nM_1:&\\quad \\text{logit} \\Pr(x_{ij} = 1) = \\beta_0 + \\beta_1 r_j + \\beta_2 g_j,\\\\\nM_2:&\\quad \\text{logit} \\Pr(x_{ij} = 1) = \\beta_0 + \\beta_1 r_j + \\beta_2 g_j + \\beta_3 g_j r_j,\n\\end{aligned}$$\nwith $r_j$ the matching score and $g_j = 1$ for the focal group. $M_1$ adds uniform DIF: $\\beta_2$ is where the action is, the difference in log odds between groups at the same score. $M_2$ adds non-uniform DIF: $\\beta_3$ lets the slope on the score differ by group. Likelihood-ratio tests compare the models in turn, or $M_0$ with $M_2$ for both kinds at once.\n\nHow big is the DIF? $e^{\\beta_2}$ is an odds ratio at a fixed score, like $\\hat\\alpha_{MH}$, so $2.35\\,\\beta_2$ sits on the delta scale. Or take the change in Nagelkerke's pseudo-$R^2$ from $M_0$ to $M_2$; [Jodoin and Gierl (2001)](https://doi.org/10.1207/S15324818AME1404_2) proposed categories for it, which `difR` implements as negligible below 0.035, moderate from 0.035 to 0.07 and large above ([Magis, Béland, Tuerlinckx & De Boeck, 2010](https://doi.org/10.3758/BRM.42.3.847)). \n\nWhy the workhorse? It is a model we already know, fitted with `glm()`; it tests non-uniform DIF, which Mantel–Haenszel pools away; it takes continuous matching variables and extra covariates; and it extends to ordered categories as a cumulative logit model (problem 3; [Crane, Gibbons, Jolley & van Belle, 2006](https://doi.org/10.1097/01.mlr.0000245183.28384.ed)). Comparing item parameters estimated in each group is a third family ([Lord, 1980, \"Study of item bias\"](https://doi.org/10.4324/9780203056615-20); [Thissen, Steinberg & Wainer, 1993](https://doi.org/10.4324/9780203357811)).\n\n#### Try it: uniform and non-uniform DIF\n\nThe studied item has $b = 0$ and $a = 1$ in the reference group; the sliders set its focal-group curve. Fifteen other items complete the matching score; 2,000 respondents per group, no impact.\n\n```{ojs}\n//| echo: false\nviewof w2_b = Inputs.range([-1, 1], {value: 0.5, step: 0.1, label: \"Focal group's difficulty\"})\nviewof w2_a = Inputs.range([0.4, 2.5], {value: 1, step: 0.1, label: \"Focal group's slope\"})\n```\n\n```{ojs}\n//| echo: false\nPlot.plot({\n  width: 700, height: 260, x: {label: \"Ability θ\"}, y: {label: \"P(correct)\", domain: [0, 1]},\n  color: {legend: true, domain: [\"reference\", \"focal\"], range: [palette.main, palette.contrast]},\n  marks: [Plot.line(grid(-4, 4).flatMap(t => [{t, p: p2pl(t, 0, 1), grp: \"reference\"}, {t, p: p2pl(t, w2_b, w2_a), grp: \"focal\"}]),\n                    {x: \"t\", y: \"p\", stroke: \"grp\", strokeWidth: 2.5})]\n})\n```\n\n```{ojs}\n//| echo: false\nw2 = {\n  const b = Array.from({length: 16}, (_, i) => (i === 7 ? 0 : -1.5 + 3 * i / 15));\n  const {X, g} = simGroups({seed: 5, nPer: 2000, nItems: 16, b, dif: [{item: 7, db: w2_b, a: w2_a}]});\n  return {mh: mhAll(X, g)[7], lr: logisticDIF(X, g, 7)};\n}\nmd`Mantel–Haenszel delta **${w2.mh.delta.toFixed(2)}** (category ${w2.mh.ets}). Logistic regression: group coefficient **${w2.lr.group.toFixed(2)}** (times 2.35: ${(2.35 * w2.lr.group).toFixed(2)}); slope on the total score ${w2.lr.b1.toFixed(2)} in the reference group and ${(w2.lr.b1 + w2.lr.interaction).toFixed(2)} in the focal group.`\n```\n\nWith the slope at 1, the delta and 2.35 times the group coefficient move together. Now set the difficulty to 0 and the slope to 2: the curves cross, the delta stays near 0, and the slopes on the total part company. Mantel–Haenszel pools over scores and can miss DIF that changes sign; the interaction term sees it.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In a logistic-regression DIF analysis, adding group to the model improves the fit a lot, but adding the group × score interaction does not. What kind of DIF is it?\",\n  options: [\n    {text: \"Uniform: the item is harder for one group by about the same log odds at every score\", correct: true, why: \"The group term shifts the curve; the interaction would change its slope. Only the shift is needed.\"},\n    {text: \"Non-uniform: the groups' curves cross\", correct: false, why: \"Crossing curves need different slopes on the score, which is the interaction term, and it didn't help.\"},\n    {text: \"None: the interaction is what detects DIF\", correct: false, why: \"The group term alone detects uniform DIF; the interaction adds the non-uniform kind.\"}\n  ]\n})\n```\n\n### Treatment as a grouping variable\n\nIn a randomized trial, treatment assignment is a grouping too: among children with the same total, is an item easier for treated children? It is if the program raises some items much more than others. DIF by treatment is variation in the treatment effect from item to item ([Gilbert, Kim & Miratrix, 2023](https://doi.org/10.3102/10769986231171710); [Ahmed et al., 2025](https://doi.org/10.1080/19345747.2024.2361337)). It says what the effect on the total is made of.\n\n## Simulate\n\nThe code below simulates 20 2PL items for two groups, the focal group 1 SD lower on $\\theta$ and items 9 and 10 harder for it by 0.6 logits, and runs Mantel–Haenszel on every item in 100 replications, matching on the total and on a purified total. It is base R and takes a few seconds.\n\nWith the seed as written, the DIF items' mean delta is −1.3 (true values −1.3 and −1.4), significant in 99% of replications. On the contaminated total the clean items drift upward (mean delta 0.13) and are significant 8.7% of the time, against a nominal 5%; purified, 7.4%.  Set `slopes_vary <- FALSE` and the purified rate falls to 3.6%. Try `n_dif <- 6` (33% false flags on the total), and `n_dif <- 0` with `impact <- 2`.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-17\n# Differential item functioning, simulated: two groups answer 20 items from a 2PL.\n# The focal group sits `impact` SDs below the reference group, and `n_dif` items\n# (from item 9 on) are harder for the focal group by `dif` logits at every theta (uniform DIF).\n# Each replication runs the Mantel-Haenszel procedure on every item, matching on the\n# total score and then on a purified total, and records which items are flagged.\n# Base R only; runs in a few seconds.\nset.seed(252)\nn_ref <- 1000; n_foc <- 1000       # respondents per group\nn_items <- 20\nimpact <- 1.0                      # reference mean minus focal mean, in SDs of theta\nn_dif <- 2; dif <- 0.6             # how many DIF items, and how much harder for the focal group\nslopes_vary <- TRUE                # FALSE: every slope 1 (the Rasch model)\nreps <- 100\n\na <- if (slopes_vary) exp(seq(-0.5, 0.5, length.out = n_items)) else rep(1, n_items)\nb <- seq(-1.5, 1.5, length.out = n_items)\ndif_items <- seq_len(n_dif) + 8   # items 9, 10, ...: middling difficulty, slope near 1\n\n# Mantel-Haenszel delta and its chi-square p-value for one item (g = 1 is focal).\nmh <- function(y, g, score) {\n  k <- score + 1; K <- max(k)\n  A <- tabulate(k[y == 1 & g == 0], K); B <- tabulate(k[y == 0 & g == 0], K)\n  C <- tabulate(k[y == 1 & g == 1], K); D <- tabulate(k[y == 0 & g == 1], K)\n  n <- A + B + C + D; s <- n > 1\n  A <- A[s]; B <- B[s]; C <- C[s]; D <- D[s]; n <- n[s]\n  nR <- A + B; nF <- C + D; m1 <- A + C; m0 <- B + D\n  chisq <- max(0, abs(sum(A) - sum(nR * m1 / n)) - 0.5)^2 / sum(nR * nF * m1 * m0 / (n^2 * (n - 1)))\n  c(delta = -2.35 * log(sum(A * D / n) / sum(B * C / n)), p = pchisq(chisq, 1, lower.tail = FALSE))\n}\n\none_rep <- function() {\n  g <- rep(0:1, c(n_ref, n_foc))\n  theta <- rnorm(n_ref + n_foc, mean = ifelse(g == 1, -impact, 0))\n  bb <- matrix(b, length(g), n_items, byrow = TRUE)\n  bb[g == 1, dif_items] <- bb[g == 1, dif_items] + dif\n  p <- plogis(sweep(theta - bb, 2, a, \"*\"))\n  X <- matrix(rbinom(length(p), 1, p), nrow = length(g))\n  # Stage 1: match on the total. Stage 2: drop flagged items from the total\n  # (each studied item stays in its own matching score) and run again.\n  s1 <- sapply(1:n_items, function(i) mh(X[, i], g, rowSums(X)))\n  flag <- which(s1[\"p\", ] < 0.05 & abs(s1[\"delta\", ]) >= 1)\n  s2 <- sapply(1:n_items, function(i) mh(X[, i], g, rowSums(X[, union(setdiff(1:n_items, flag), i), drop = FALSE])))\n  rbind(delta_total = s1[\"delta\", ], sig_total = s1[\"p\", ] < 0.05,\n        delta_purified = s2[\"delta\", ], sig_purified = s2[\"p\", ] < 0.05)\n}\nout <- replicate(reps, one_rep())   # 4 x n_items x reps\n\nclean <- setdiff(1:n_items, dif_items)\nsummary_table <- data.frame(\n  matching = c(\"total\", \"purified\"),\n  mean_delta_dif_items = c(mean(out[\"delta_total\", dif_items, ]), mean(out[\"delta_purified\", dif_items, ])),\n  power = c(mean(out[\"sig_total\", dif_items, ]), mean(out[\"sig_purified\", dif_items, ])),\n  mean_delta_clean_items = c(mean(out[\"delta_total\", clean, ]), mean(out[\"delta_purified\", clean, ])),\n  type_I_error = c(mean(out[\"sig_total\", clean, ]), mean(out[\"sig_purified\", clean, ])))\nprint(summary_table, digits = 2)\n# The true DIF on the delta scale is -2.35 x the log odds ratio. For a 2PL item that is\n# about -2.35 * a * dif near the middle of the scale.\nround(-2.35 * a[dif_items] * dif, 2)\n\nop <- par(mar = c(4, 4, 1, 1))\nplot(1:n_items, rowMeans(out[\"delta_total\", , ]), pch = 19, col = \"#2780e3\", ylim = c(-2.5, 1),\n     xlab = \"Item (DIF items from item 9 on)\", ylab = \"Mean MH delta over replications\")\npoints(1:n_items, rowMeans(out[\"delta_purified\", , ]), pch = 1, col = \"#c2410c\")\nabline(h = c(-1, 0, 1), lty = c(3, 2, 3), col = \"#999\")\nlegend(\"bottomright\", c(\"matched on total\", \"matched on purified total\"),\n       pch = c(19, 1), col = c(\"#2780e3\", \"#c2410c\"), bty = \"n\")\npar(op)\n\n```\n:::\n\n\n[Download this code](code/dif-sim.R) to run it in your own R session.\n\n## With real data\n\nOur table is [gilbert_meta_11](https://itemresponsewarehouse.org/tables/gilbert_meta_11/): a vocabulary test from a cluster-randomized trial of a content literacy program, in which treated schools taught thematic science and social studies lessons ([Kim, Relyea, Burkhauser, Scherer & Rich, 2021](https://doi.org/10.1007/s10648-021-09609-6); data at [doi:10.7910/DVN/HQEMN6](https://doi.org/10.7910/DVN/HQEMN6)), in the trial collection of [Gilbert, Himmelsbach, Soland, Joshi & Domingue (2025)](https://doi.org/10.1002/pam.70025). Its job is to be a test we can split many ways: it records gender, race and ethnicity, English-learner status, an individualized education program (IEP), low income and treatment. The trial enrolled first and second graders; the IRW and the item text mark this table as the grade 1 form (grade 2 is the trial in [What is measurement?](measurement.qmd)), which I could not check against the paper's full text. Each item asks a child to circle the two of four words that go with a target word; 1 is correct, so higher means more vocabulary. There is one outcome occasion. [Download the code](code/dif-irw.R); it needs only base R, except the last chunk (`mirt` and `robustDIF`).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The IRW table, from the CSV link on its landing page (pinned to one version).\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v59_0.gilbert_meta_11/rows?format=csv\"\nlong <- read.csv(url)\nhead(long[, c(\"id\", \"item\", \"resp\", \"treat\", \"cov_male\", \"cov_lep\")], 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| id|item  | resp| treat| cov_male| cov_lep|\n|--:|:-----|----:|-----:|--------:|-------:|\n| 77|sci3  |    1|     0|        0|       0|\n| 77|sci8  |    0|     0|        0|       0|\n| 77|sci10 |    1|     0|        0|       0|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# One row per child: the 24 items (12 science, 12 social studies; 1 = correct) and\n# the child's covariates. We keep the children who answered all 24 items.\nitems <- c(paste0(\"sci\", 1:12), paste0(\"ss\", 1:12))\nw <- reshape(long[, c(\"id\", \"item\", \"resp\")], idvar = \"id\", timevar = \"item\", direction = \"wide\")\nnames(w) <- sub(\"^resp\\\\.\", \"\", names(w))\nkids <- long[!duplicated(long$id), c(\"id\", \"treat\", grep(\"^cov_\", names(long), value = TRUE))]\nw <- merge(w, kids, by = \"id\")\nc(children = nrow(w), complete = sum(complete.cases(w[, items])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchildren complete \n    2588     2347 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nw <- w[complete.cases(w[, items]), ]\nX <- as.matrix(w[, items])\n```\n:::\n\n\nWe keep the 2,347 of 2,588 children who answered all 24 items. For race and ethnicity the reference group is White children (76 children with none of the four indicators are left out).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Each grouping is a focal group (coded 1) against a reference group (coded 0);\n# children in neither are left out (NA). A positive delta favours the focal group.\nrace <- function(g) ifelse(w[[g]] == 1, 1, ifelse(w$cov_white == 1, 0, NA))\ngroups <- list(\n  \"girls vs. boys\"              = 1 - w$cov_male,\n  \"Black vs. White\"             = race(\"cov_black\"),\n  \"Hispanic vs. White\"          = race(\"cov_hispanic\"),\n  \"Asian vs. White\"             = race(\"cov_asian\"),\n  \"English learners vs. not\"    = w$cov_lep,\n  \"IEP vs. not\"                 = w$cov_iep,\n  \"low income vs. not\"          = w$cov_ses_low,\n  \"treated vs. control\"         = w$treat)\nt(sapply(groups, function(g) c(focal = sum(g == 1, na.rm = TRUE), reference = sum(g == 0, na.rm = TRUE))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         focal reference\ngirls vs. boys            1138      1209\nBlack vs. White            868       448\nHispanic vs. White         761       448\nAsian vs. White            194       448\nEnglish learners vs. not   533      1814\nIEP vs. not                188      2159\nlow income vs. not         941      1406\ntreated vs. control       1286      1061\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The Mantel-Haenszel procedure for one item. Children are matched on a score (by\n# default the total on all 24 items, the studied item included); within each score\n# level k we have a 2 x 2 table of group by right/wrong. The common odds ratio pools\n# the tables; delta = -2.35 ln(alpha) puts it on the ETS delta scale (Holland &\n# Thayer, 1986). SE: Robins, Breslow & Greenland (1986). Chi-square: with the\n# continuity correction, as ETS computes it (Zwick, 2012, eq. 3).\nmh <- function(y, g, score) {\n  ok <- !is.na(g)\n  y <- y[ok]; g <- g[ok]; s <- score[ok]\n  A <- tapply(y == 1 & g == 0, s, sum)   # reference, right\n  B <- tapply(y == 0 & g == 0, s, sum)   # reference, wrong\n  C <- tapply(y == 1 & g == 1, s, sum)   # focal, right\n  D <- tapply(y == 0 & g == 1, s, sum)   # focal, wrong\n  n <- A + B + C + D\n  keep <- n > 1\n  A <- A[keep]; B <- B[keep]; C <- C[keep]; D <- D[keep]; n <- n[keep]\n  R <- A * D / n; S <- B * C / n\n  alpha <- sum(R) / sum(S)\n  P <- (A + D) / n; Q <- (B + C) / n\n  var_log <- sum(P * R) / (2 * sum(R)^2) + sum(P * S + Q * R) / (2 * sum(R) * sum(S)) +\n             sum(Q * S) / (2 * sum(S)^2)\n  nR <- A + B; nF <- C + D; m1 <- A + C; m0 <- B + D\n  chisq <- max(0, abs(sum(A) - sum(nR * m1 / n)) - 0.5)^2 / sum(nR * nF * m1 * m0 / (n^2 * (n - 1)))\n  c(delta = -2.35 * log(alpha), se = 2.35 * sqrt(var_log), chisq = chisq,\n    p = pchisq(chisq, 1, lower.tail = FALSE))\n}\n# The ETS categories (Zwick, 2012, pp. 3-4). A: not significant at .05, or |delta| < 1.\n# C: |delta| >= 1.5 and |delta| significantly greater than 1. B: everything else.\nets <- function(delta, se, p) {\n  ifelse(p >= 0.05 | abs(delta) < 1, \"A\",\n         ifelse(abs(delta) >= 1.5 & (abs(delta) - 1) / se > qnorm(0.95), \"C\", \"B\"))\n}\nmh_all <- function(g, score = rowSums(X), cols = items) {\n  out <- as.data.frame(t(sapply(cols, function(i) mh(X[, i], g, score))))\n  out$ets <- ets(out$delta, out$se, out$p)\n  out\n}\nsummarise_mh <- function(r) c(significant = sum(r$p < 0.05), A = sum(r$ets == \"A\"),\n                              B = sum(r$ets == \"B\"), C = sum(r$ets == \"C\"),\n                              largest = round(max(abs(r$delta)), 2))\n```\n:::\n\n\nWhat does no DIF look like? Split the children at random twenty times.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The sanity check: random halves of the same children. Nothing but chance can make\n# an item \"work differently\" for them, so these counts are the baseline.\nset.seed(44)\nrand <- t(replicate(20, summarise_mh(mh_all(rbinom(nrow(X), 1, 0.5)))))\nround(colMeans(rand), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsignificant           A           B           C     largest \n       0.80       24.00        0.00        0.00        0.52 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nmax(rand[, \"largest\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.66\n```\n\n\n:::\n:::\n\n\nOn random halves, 0.80 items in 24 are significant on average, none is ever in B or C, and the largest $|\\Delta|$ is 0.66. That is the baseline.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Which grouping will show the most DIF on this vocabulary test?\",\n  choices: [\"Girls vs. boys\", \"Race and ethnicity\", \"English learners vs. not\", \"IEP vs. not\", \"Low income vs. not\", \"Treated vs. control\"],\n  answer: \"Treated vs. control\",\n  reveal: \"Treatment: 7 of the 24 items are in B or C, 6 of them in C, and the largest $|\\\\Delta|$ is 5.74. No demographic grouping has more than 6 items in B or C (Hispanic vs. White), and girls vs. boys has none. Check the table below.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nres <- lapply(groups, mh_all)\nabc <- t(sapply(res, summarise_mh))\nabc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         significant  A B C largest\ngirls vs. boys                     5 24 0 0    0.81\nBlack vs. White                    6 20 4 0    1.32\nHispanic vs. White                 8 18 5 1    1.72\nAsian vs. White                    1 23 1 0    1.07\nEnglish learners vs. not           7 20 4 0    1.21\nIEP vs. not                        4 21 3 0    1.23\nlow income vs. not                11 22 2 0    1.31\ntreated vs. control               15 17 1 6    5.74\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same numbers from the difR package (Magis et al., 2010), if installed: its\n# difMH matches on the total score and reports alpha; delta = -2.35 ln(alpha).\nif (requireNamespace(\"difR\", quietly = TRUE)) {\n  d <- difR::difMH(Data = X, group = w$treat, focal.name = 1)\n  max(abs(-2.35 * log(d$alphaMH) - res[[\"treated vs. control\"]]$delta))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n(Our function and `difR` agree to rounding error.)\n\nTake the demographic groupings first. Girls and boys: 5 items significant, all in A, largest $|\\Delta|$ 0.81, near the random baseline. The other comparisons each put 1 to 5 items in B, and one item reaches C: `sci12`, at 1.72, easier for Hispanic than for White children with the same total.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The B items among the demographic groupings, with the proportion correct in each group.\ndem <- do.call(rbind, lapply(names(groups)[1:7], function(nm) {\n  r <- res[[nm]]; g <- groups[[nm]]\n  b <- rownames(r)[r$ets != \"A\"]\n  if (!length(b)) return(NULL)\n  data.frame(grouping = nm, item = b, delta = round(r[b, \"delta\"], 2),\n             p_focal = round(colMeans(X[g %in% 1, b, drop = FALSE]), 2),\n             p_reference = round(colMeans(X[g %in% 0, b, drop = FALSE]), 2))\n}))\nrownames(dem) <- NULL\ndem\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|grouping                 |item  | delta| p_focal| p_reference|\n|:------------------------|:-----|-----:|-------:|-----------:|\n|Black vs. White          |sci5  | -1.10|    0.62|        0.83|\n|Black vs. White          |sci7  |  1.31|    0.43|        0.41|\n|Black vs. White          |sci10 | -1.15|    0.51|        0.75|\n|Black vs. White          |ss2   |  1.32|    0.37|        0.38|\n|Hispanic vs. White       |sci6  | -1.27|    0.68|        0.88|\n|Hispanic vs. White       |sci7  |  1.20|    0.40|        0.41|\n|Hispanic vs. White       |sci10 | -1.19|    0.49|        0.75|\n|Hispanic vs. White       |sci12 |  1.72|    0.36|        0.35|\n|Hispanic vs. White       |ss2   |  1.47|    0.32|        0.38|\n|Hispanic vs. White       |ss8   | -1.13|    0.57|        0.83|\n|Asian vs. White          |ss1   | -1.07|    0.51|        0.64|\n|English learners vs. not |sci7  |  1.02|    0.43|        0.40|\n|English learners vs. not |sci12 |  1.05|    0.34|        0.34|\n|English learners vs. not |ss8   | -1.21|    0.50|        0.72|\n|English learners vs. not |ss9   | -1.13|    0.59|        0.78|\n|IEP vs. not              |sci4  |  1.01|    0.21|        0.28|\n|IEP vs. not              |sci11 |  1.23|    0.18|        0.16|\n|IEP vs. not              |ss11  | -1.06|    0.41|        0.67|\n|low income vs. not       |ss2   |  1.31|    0.37|        0.35|\n|low income vs. not       |ss8   | -1.08|    0.55|        0.75|\n\n</div>\n:::\n:::\n\n\nSome items recur (`sci5`, `sci10` and `ss8` harder, `sci7`, `sci12` and `ss2` easier for several focal groups). These are facts about items in this sample, not verdicts on the groups, and they are modest next to what comes next.\n\n### The twist: DIF by treatment\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Items by their treatment DIF. Each item asks the child to pick the two of four\n# words that go with a target word; a few target words, from the IRW item text\n# (reconstructed from the study's materials), label the items discussed in the text.\nwords <- c(ss2 = \"expedition\", ss7 = \"indigenous\", ss6 = \"obstacle\",\n           sci5 = \"behavior\", ss8 = \"celebrate\", sci10 = \"habitat\", ss11 = \"community\")\ntr <- res[[\"treated vs. control\"]]\ntr$p_control <- colMeans(X[w$treat == 0, ])\ntr$p_treated <- colMeans(X[w$treat == 1, ])\ntr$word <- ifelse(rownames(tr) %in% names(words), words[rownames(tr)], \"\")\ntr <- tr[order(-tr$delta), ]\nprint(data.frame(word = tr$word, delta = round(tr$delta, 2), se = round(tr$se, 2),\n                 ets = tr$ets, p_control = round(tr$p_control, 2),\n                 p_treated = round(tr$p_treated, 2), row.names = rownames(tr)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            word delta   se ets p_control p_treated\nss2   expedition  5.74 0.29   C      0.09      0.58\nss7   indigenous  1.83 0.23   C      0.38      0.62\nss6     obstacle  1.75 0.24   C      0.46      0.68\nss12              0.78 0.25   A      0.20      0.32\nsci9              0.77 0.28   A      0.14      0.26\nsci11             0.76 0.30   A      0.12      0.19\nss5               0.22 0.24   A      0.22      0.30\nsci7              0.16 0.21   A      0.37      0.44\nsci3              0.14 0.29   A      0.77      0.82\nsci8             -0.08 0.30   A      0.13      0.17\nsci12            -0.10 0.23   A      0.31      0.37\nss3              -0.23 0.27   A      0.20      0.26\nss4              -0.28 0.23   A      0.52      0.59\nsci1             -0.33 0.22   A      0.38      0.41\nss10             -0.42 0.26   A      0.22      0.27\nsci2             -0.56 0.23   A      0.42      0.45\nsci4             -0.68 0.25   A      0.25      0.29\nss1              -0.77 0.22   A      0.50      0.51\nsci6             -0.87 0.27   A      0.75      0.75\nss9              -0.95 0.27   A      0.73      0.74\nss11   community -1.49 0.24   B      0.67      0.62\nsci10    habitat -1.81 0.25   C      0.58      0.54\nss8    celebrate -1.87 0.28   C      0.68      0.66\nsci5    behavior -1.93 0.26   C      0.70      0.65\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The raw treatment difference in the total score is the sum of the items'\n# differences in proportion correct. How much of it is expedition's?\ngap <- tr$p_treated - tr$p_control\nround(c(total_gap = sum(gap), expedition = gap[rownames(tr) == \"ss2\"],\n        share = gap[rownames(tr) == \"ss2\"] / sum(gap)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n total_gap expedition      share \n      1.70       0.48       0.28 \n```\n\n\n:::\n:::\n\n\nTreatment puts six items in C. The largest by far is `ss2`, whose target word is *expedition* (from the IRW item text): 9% of control and 58% of treated children answered it correctly, a delta of 5.74, and this one item is 28% of the raw treatment difference in the total (0.48 of 1.70 items). *Indigenous* and *obstacle* follow. Three C items have negative deltas (*behavior*, *celebrate*, *habitat*): they barely moved while the total rose.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Expedition, matched: the proportion correct by total score, in each arm.\ntot <- rowSums(X)\nband <- cut(tot, c(-1, 8, 12, 16, 20, 24), labels = c(\"0-8\", \"9-12\", \"13-16\", \"17-20\", \"21-24\"))\nround(tapply(X[, \"ss2\"], list(total = band, arm = ifelse(w$treat == 1, \"treated\", \"control\")), mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       arm\ntotal   control treated\n  0-8      0.08    0.23\n  9-12     0.07    0.57\n  13-16    0.11    0.75\n  17-20    0.27    0.87\n  21-24    1.00    0.98\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nop <- par(mar = c(4, 4, 1, 1))\npc <- tapply(X[, \"ss2\"], list(tot, w$treat), mean)\nnn <- table(tot, w$treat)\npc[nn < 10] <- NA   # hide score levels with fewer than 10 children in an arm\nplot(as.numeric(rownames(pc)), pc[, \"0\"], type = \"b\", pch = 19, col = \"#999\", ylim = c(0, 1),\n     xlab = \"Total score (24 items)\", ylab = \"Proportion correct on 'expedition'\")\nlines(as.numeric(rownames(pc)), pc[, \"1\"], type = \"b\", pch = 19, col = \"#2780e3\")\nlegend(\"topleft\", c(\"control\", \"treated\"), col = c(\"#999\", \"#2780e3\"), pch = 19, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](dif_files/figure-html/expedition-1.png){width=576}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npar(op)\n```\n:::\n\n\nMatched, the gap for *expedition* holds at every band of totals below 21: among children with 13 to 16 correct, 75% of treated and 11% of control children got it. Now logistic regression, for every item and grouping.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Logistic regression DIF (Swaminathan & Rogers, 1990): three nested models per item,\n#   M0: total score;  M1: + group (uniform DIF);  M2: + group x total (non-uniform DIF).\n# Likelihood-ratio tests compare them. The effect size is the change in Nagelkerke's\n# R^2 from M0 to M2, classified as Jodoin & Gierl (2001) do in difR: below .035\n# negligible (A), .035 to .07 moderate (B), above .07 large (C).\nnagelkerke <- function(m, ll0, n) {\n  cs <- 1 - exp(2 * (ll0 - as.numeric(logLik(m))) / n)\n  cs / (1 - exp(2 * ll0 / n))\n}\nlr_item <- function(y, g, total) {\n  d <- data.frame(y = y, g = g, total = total)[!is.na(g), ]\n  ll0 <- as.numeric(logLik(glm(y ~ 1, binomial, d)))\n  m0 <- glm(y ~ total, binomial, d)\n  m1 <- glm(y ~ total + g, binomial, d)\n  m2 <- glm(y ~ total * g, binomial, d)\n  c(beta_group = unname(coef(m1)[\"g\"]),\n    p_uniform = anova(m0, m1, test = \"LRT\")[2, \"Pr(>Chi)\"],\n    p_nonuniform = anova(m1, m2, test = \"LRT\")[2, \"Pr(>Chi)\"],\n    p_both = anova(m0, m2, test = \"LRT\")[2, \"Pr(>Chi)\"],\n    dR2 = nagelkerke(m2, ll0, nrow(d)) - nagelkerke(m0, ll0, nrow(d)))\n}\nlr_all <- function(g) {\n  out <- as.data.frame(t(sapply(items, function(i) lr_item(X[, i], g, rowSums(X)))))\n  out$jg <- ifelse(out$p_both >= 0.05 | out$dR2 < 0.035, \"A\", ifelse(out$dR2 < 0.07, \"B\", \"C\"))\n  out\n}\nlr <- lapply(groups, lr_all)\n# Side by side with Mantel-Haenszel: items significant (2-df test), and the Jodoin &\n# Gierl categories.\nt(sapply(lr, function(r) c(significant = sum(r$p_both < 0.05), A = sum(r$jg == \"A\"),\n                           B = sum(r$jg == \"B\"), C = sum(r$jg == \"C\"),\n                           largest_dR2 = round(max(r$dR2), 3))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         significant  A B C largest_dR2\ngirls vs. boys                     4 24 0 0       0.008\nBlack vs. White                    9 24 0 0       0.017\nHispanic vs. White                12 24 0 0       0.025\nAsian vs. White                    4 24 0 0       0.023\nEnglish learners vs. not           9 24 0 0       0.010\nIEP vs. not                        6 24 0 0       0.007\nlow income vs. not                 9 24 0 0       0.014\ntreated vs. control               17 23 0 1       0.244\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Treatment, item by item: the group coefficient (a log odds ratio at a fixed total;\n# 2.35 times it is on the MH delta scale), the non-uniform test, and the effect size.\nlt <- lr[[\"treated vs. control\"]]\nlt <- data.frame(word = tr[rownames(lt), \"word\"], beta_group = round(lt$beta_group, 2),\n                 odds_ratio = round(exp(lt$beta_group), 2),\n                 lr_delta = round(2.35 * lt$beta_group, 2),\n                 mh_delta = round(tr[rownames(lt), \"delta\"], 2),\n                 p_nonuniform = signif(lt$p_nonuniform, 2), dR2 = round(lt$dR2, 3),\n                 jg = lt$jg, mh_ets = tr[rownames(lt), \"ets\"], row.names = rownames(lt))\nlt[order(-lt$dR2), ][1:8, ]\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |word       | beta_group| odds_ratio| lr_delta| mh_delta| p_nonuniform|   dR2|jg |mh_ets |\n|:-----|:----------|----------:|----------:|--------:|--------:|------------:|-----:|:--|:------|\n|ss2   |expedition |       2.57|      13.08|     6.04|     5.74|      3.0e-07| 0.244|C  |C      |\n|sci5  |behavior   |      -0.85|       0.43|    -2.01|    -1.93|      1.2e-02| 0.031|A  |C      |\n|ss7   |indigenous |       0.78|       2.18|     1.83|     1.83|      1.5e-02| 0.030|A  |C      |\n|ss11  |community  |      -0.65|       0.52|    -1.53|    -1.49|      1.2e-04| 0.029|A  |B      |\n|ss6   |obstacle   |       0.74|       2.10|     1.74|     1.75|      5.2e-04| 0.026|A  |C      |\n|sci10 |habitat    |      -0.77|       0.46|    -1.80|    -1.81|      2.6e-01| 0.025|A  |C      |\n|ss8   |celebrate  |      -0.76|       0.47|    -1.79|    -1.87|      4.8e-03| 0.021|A  |C      |\n|sci11 |           |       0.35|       1.41|     0.81|     0.76|      3.9e-05| 0.017|A  |A      |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(cor(lt$lr_delta, lt$mh_delta), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9991\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsum(lr[[\"treated vs. control\"]]$p_nonuniform < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n:::\n\n\nThe two methods agree on the size of uniform DIF: 2.35 times the group coefficient tracks the Mantel–Haenszel delta item for item (correlation 0.9991), and for *expedition* the odds ratio at a fixed total is 13.08. They sort items differently. By the Jodoin–Gierl categories every demographic item is negligible, and so is every treatment item except *expedition* ($\\Delta R^2$ = 0.244); the other five ETS C items have $\\Delta R^2$ between 0.021 and 0.031. The interaction is significant at .05 for 14 of the 24 items: with 2,347 children, small differences in slope are significant too, which is why sizes, not p-values, should decide what gets reviewed.\n\nLast, the relativity of DIF. The total contains *expedition* and the other C items, so for the remaining items it overstates treated children's vocabulary. Purify:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Purification: drop the C items from the matching score (each studied item stays\n# in its own score), then run the procedure again (Holland & Thayer, 1986).\nflag <- rownames(res[[\"treated vs. control\"]])[res[[\"treated vs. control\"]]$ets == \"C\"]\nflag\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"sci5\"  \"sci10\" \"ss2\"   \"ss6\"   \"ss7\"   \"ss8\"  \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npur <- as.data.frame(t(sapply(items, function(i) {\n  anchor <- union(setdiff(items, flag), i)\n  mh(X[, i], w$treat, rowSums(X[, anchor]))\n})))\npur$ets <- ets(pur$delta, pur$se, pur$p)\ncmp <- data.frame(total = round(res[[\"treated vs. control\"]]$delta, 2),\n                  purified = round(pur$delta, 2),\n                  ets_total = res[[\"treated vs. control\"]]$ets, ets_purified = pur$ets,\n                  row.names = items)\ncmp[order(-cmp$total), ]\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      | total| purified|ets_total |ets_purified |\n|:-----|-----:|--------:|:---------|:------------|\n|ss2   |  5.74|     5.77|C         |C            |\n|ss7   |  1.83|     2.03|C         |C            |\n|ss6   |  1.75|     1.97|C         |C            |\n|ss12  |  0.78|     1.05|A         |B            |\n|sci9  |  0.77|     1.18|A         |B            |\n|sci11 |  0.76|     0.82|A         |A            |\n|ss5   |  0.22|     0.44|A         |A            |\n|sci7  |  0.16|     0.22|A         |A            |\n|sci3  |  0.14|     0.35|A         |A            |\n|sci8  | -0.08|     0.09|A         |A            |\n|sci12 | -0.10|     0.09|A         |A            |\n|ss3   | -0.23|     0.15|A         |A            |\n|ss4   | -0.28|     0.14|A         |A            |\n|sci1  | -0.33|    -0.14|A         |A            |\n|ss10  | -0.42|    -0.13|A         |A            |\n|sci2  | -0.56|    -0.26|A         |A            |\n|sci4  | -0.68|    -0.29|A         |A            |\n|ss1   | -0.77|    -0.54|A         |A            |\n|sci6  | -0.87|    -0.53|A         |A            |\n|ss9   | -0.95|    -0.64|A         |A            |\n|ss11  | -1.49|    -1.28|B         |B            |\n|sci10 | -1.81|    -1.32|C         |B            |\n|ss8   | -1.87|    -1.18|C         |B            |\n|sci5  | -1.93|    -1.54|C         |C            |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(total = cmp$ets_total, purified = cmp$ets_purified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     purified\ntotal  A  B  C\n    A 15  2  0\n    B  0  1  0\n    C  0  2  4\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(mean_total = mean(cmp$total), mean_purified = mean(cmp$purified)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   mean_total mean_purified \n        -0.01          0.27 \n```\n\n\n:::\n:::\n\n\nPurified, the three items favouring treated children stay in C, *habitat* and *celebrate* drop from C to B, every negative delta moves toward zero, and `ss12` and `sci9` rise into B. The mean delta rises from −0.01 to 0.27: part of the negative DIF was a shadow of the positive.\n\nPurification still starts from the whole test. Robust scaling (Go deeper, above) chooses no anchor in advance:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Robust scaling (Halpin, 2024; robustDIF package): fit a 2PL in each arm, then\n# estimate the difference between the arms on theta while down-weighting items whose\n# item-level estimates of that difference are outliers. No anchor is chosen in\n# advance. Needs the mirt and robustDIF packages; skipped if they are missing.\nif (requireNamespace(\"mirt\", quietly = TRUE) && requireNamespace(\"robustDIF\", quietly = TRUE)) {\n  fits <- lapply(0:1, function(k) mirt::mirt(as.data.frame(X[w$treat == k, ]), 1,\n                                              itemtype = \"2PL\", SE = TRUE, verbose = FALSE))\n  rob <- robustDIF::rdif(mle = robustDIF::get_model_parms(fits), fun = \"d_fun3\", alpha = 0.05)\n  rt <- rob$dif.test\n  rownames(rt) <- items   # the package labels items by position\n  print(data.frame(word = tr[items, \"word\"], delta = round(rt$delta, 2), z = round(rt$z.test, 1),\n                   weight = round(rob$weights, 2), row.names = items)[order(-abs(rt$delta)), ][1:8, ])\n  print(c(flagged = sum(rt$p.val < 0.05), zero_weight = sum(rob$weights == 0)))\n  # Treatment effect on theta (in SDs): all items weighted equally vs. robust.\n  print(robustDIF::delta_test(rob)[, c(\"naive.est\", \"rdif.est\", \"delta\", \"z.test\", \"p.val\")], digits = 3)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            word delta    z weight\nss2   expedition  2.84 19.5      0\nsci11             0.83  2.7      0\nss7   indigenous  0.73  9.3      0\nss11   community -0.64 -6.0      0\nss12              0.60  3.6      0\nss6     obstacle  0.59  9.2      0\nsci9              0.59  3.8      0\nsci5    behavior -0.53 -6.6      0\n    flagged zero_weight \n         14          14 \n  naive.est rdif.est delta z.test    p.val\n1     0.482    0.302 0.181   3.32 0.000904\n```\n\n\n:::\n:::\n\n\nIt gives *expedition* the largest departure by far (2.84 SDs of $\\theta$) and, at the 5% level, flags 14 of the 24 items, all given zero weight. It also answers a question the item statistics don't: counting every item equally, treated children are 0.48 SD ahead on $\\theta$; downweighting the DIF items, 0.30 SD ($p < .001$ for the difference). How large the program's effect on vocabulary is depends on which items we let define vocabulary.\n\nWhat should a trialist take from this? Two assumptions first: that the total is meant to measure vocabulary broadly, and that an effect concentrated in a few items means something different from one spread across many. Given those, my rule is to run a DIF analysis by treatment before reporting a trial's effect on a total score. Here it says that over a quarter of the raw effect is one word, which the curriculum materials may explain and a reader of the effect size would want to know. [Measurement invariance under treatment and life events](invariance-experience.qmd) takes this further.\n\n## Problems\n\n1. **The Mantel–Haenszel null.** Show that under the Rasch model with no DIF, $\\Pr(x_i = 1 \\mid r)$ is the same in both groups at every total $r$, so the MH odds ratio is 1 whatever the groups' $\\theta$ distributions ([Zwick, 1990](https://doi.org/10.3102/10769986015003185)). Construct a 2PL example with two groups whose $\\theta$ distributions differ in which it is not. What happens under the Rasch model if you match on the rest score?\n2. **Demographic DIF, with treatment held out (PS5#3).** Treated children are 62% of the low-income group and 50% of the others. Repeat the demographic analyses within the control group only. Which B items survive? How can DIF by treatment show up as DIF by a demographic grouping?\n3. **Polytomous DIF on the CES-D.** [alexandrowicz_2018_cesd](https://itemresponsewarehouse.org/tables/alexandrowicz_2018_cesd/) holds the 20-item CES-D ([Radloff, 1977](https://doi.org/10.1177/014662167700100306)), answered 0–3 by a general-population sample in Austria ([Alexandrowicz, Jahn & Wancata, 2018](https://doi.org/10.1371/journal.pone.0197908)). The positively worded items arrive keyed. For ordered categories, logistic regression becomes a cumulative logit model, $\\text{logit} \\Pr(x_{ij} \\ge k) = \\beta_{0k} + \\beta_1 s_j + \\beta_2 g_j + \\beta_3 g_j s_j$, with $s_j$ the rest score ([Crane, Gibbons, Jolley & van Belle, 2006](https://doi.org/10.1097/01.mlr.0000245183.28384.ed); the `lordif` package, [Choi, Gibbons & Crane, 2011](https://doi.org/10.18637/jss.v039.i08)). Fit it per item with `MASS::polr`, grouping on `cov_sex` (264 of 518 in the source file are coded 2, the paper's number of women; no codebook confirms it). Which item flags most strongly, in which direction, and why might it? Compare [Cole, Kawachi, Maller & Berkman (2000)](https://doi.org/10.1016/S0895-4356(99)00151-1). (If you've done [Models for polytomous responses](polytomous.qmd): this is DIF in the category boundaries.)\n4. **An anchor outside the test.** `gilbert_meta_11` also records `std_baseline`, each child's standardized score before the trial. Match on it instead of the total: cut it into ten groups and run the Mantel–Haenszel procedure by treatment. How do the deltas compare with those matched on the total, and why are they nearly all positive? What does an external matching variable assume, and what question does it answer?\n5. **Design.** You are building a mathematics test for a state with many English learners. Where in development would you look for bias, and with what data? [Martiniello (2008)](https://doi.org/10.17763/haer.78.2.70783570r1111t32) combined DIF statistics with children's think-alouds; what does each tell you that the other can't?\n6. **Challenge: schooled worlds.** [Kroupin et al. (2025)](https://doi.org/10.1073/pnas.2407955122) compared children with and without formal schooling on typical executive-function tasks, and argue that the tasks reflect culturally specific development. If such items showed DIF between these groups, would that be bias, a different construct, or both? What data could tell? This one is open.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Differential%20item%20functioning%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20differential%20item%20functioning%3A%20impact%20versus%20bias%2C%20uniform%20and%20non-uniform%20DIF%2C%20the%20matching%20variable%20and%20purification%2C%20the%20Mantel-Haenszel%20procedure%20with%20the%20ETS%20delta%20scale%20and%20A%2FB%2FC%20categories%2C%20logistic-regression%20DIF%2C%20and%20DIF%20by%20treatment%20in%20a%20randomized%20trial%2C%20with%20a%20first-grade%20vocabulary%20test%20%28gilbert_meta_11%29%20analysed%20in%20base%20R.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Across the IRW\n\nHow common is DIF by gender or sex across the warehouse? Following the IRW's [gender DIF vignette](https://itemresponsewarehouse.org/vignettes/gender_dif.html), [`compute.R`](https://github.com/ben-domingue/irw-course/blob/main/deepdives/dif/compute.R) takes every table with a gender or sex covariate, at least 6 items, at most 10 response categories and a mostly complete matrix. It keeps the covariate's two most common values (at least 50 respondents each, at most 5,000 in all) and runs this lesson's procedure on every item. Polytomous items get the Liu–Agresti common cumulative odds ratio, which reduces to Mantel–Haenszel's for two categories ([Liu & Agresti, 1996](https://doi.org/10.2307/2532838); [Penfield & Algina, 2003](https://doi.org/10.1111/j.1745-3984.2003.tb01151.x)), with A/B/C applied by analogy. It reports the share of items in B and C, not direction: which code is women is rarely documented.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndd_path <- file.path(\"..\", \"deepdives\", \"dif\", \"results.rds\")\ndd <- if (file.exists(dd_path)) readRDS(dd_path) else NULL\nif (!is.null(dd)) {\n  s <- dd$summary[order(-(dd$summary$share_B + dd$summary$share_C)), ]\n  print(data.frame(table = s$table, items = s$n_items, reference = s$n_ref, focal = s$n_foc,\n                   polytomous = s$polytomous, significant = round(s$significant, 2),\n                   share_B = round(s$share_B, 2), share_C = round(s$share_C, 2),\n                   max_abs_delta = round(s$max_abs_delta, 2)), row.names = FALSE)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              table items reference focal polytomous\n       malik_2018_social_motivation    14       145   152       TRUE\n            alexandrowicz_2018_cesd    20       262   246       TRUE\n    baumgaertner_2018_vaccine_trust     6       491   444       TRUE\n                    gilbert_meta_11    24      1209  1138      FALSE\n           wang2022_dass_depression     7       159   160       TRUE\n c19prc_uk_mcbride_2021_eu_identity     6      1064   989       TRUE\n significant share_B share_C max_abs_delta\n        0.29    0.07    0.21          1.98\n        0.20    0.15    0.05          2.78\n        0.17    0.17    0.00          1.42\n        0.21    0.00    0.00          0.81\n        0.00    0.00    0.00          1.02\n        1.00    0.00    0.00          0.71\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Partial run: 6 of 1665 tables\n\nThis is a pilot run of `compute.R`, on two tables whose answers are known (`alexandrowicz_2018_cesd` and `gilbert_meta_11`) and 4 others drawn at random, to check the pipeline. The full run replaces it.\n:::\n\nRun on 25 September 2026: 6 tables analysed, 0 failed. The share of items in B or C runs from 0.00 to 0.29 (median 0.08).\n\nThe pilot checks the pipeline: `gilbert_meta_11` reproduces this lesson's gender result, and on the CES-D the crying item is the one C, as problem 3 finds by another method. In `c19prc_uk_mcbride_2021_eu_identity` every item is significant and none reaches B. The full run will say how often gender DIF of a size ETS would review turns up.\n\n## Going further\n\n- AERA, APA, & NCME. (2014). *Standards for educational and psychological testing*. American Educational Research Association. <https://www.testingstandards.net/open-access-files.html>. Chapter 3 is on fairness in testing, DIF included; open access.\n- Holland, P. W., & Wainer, H. (Eds.). (1993). *Differential item functioning*. Erlbaum. <https://doi.org/10.4324/9780203357811>. The standard collection, including Thissen, Steinberg and Wainer on DIF with item response models.\n- Holland, P. W., & Thayer, D. T. (1986). Differential item functioning and the Mantel-Haenszel procedure. *ETS Research Report Series*, 1986(2). <https://doi.org/10.1002/j.2330-8516.1986.tb00186.x>. Where the MH procedure for DIF starts.\n- Zwick, R. (2012). A review of ETS differential item functioning assessment procedures: Flagging rules, minimum sample size requirements, and criterion refinement. *ETS Research Report Series*, 2012(1). <https://doi.org/10.1002/j.2333-8504.2012.tb02290.x>. The A/B/C rules in full, and what purification does.\n- Zwick, R. (1990). When do item response function and Mantel-Haenszel definitions of differential item functioning coincide? *Journal of Educational Statistics*, 15(3), 185–197. <https://doi.org/10.3102/10769986015003185>. The Go deeper callout, and what impact does outside the Rasch model.\n- Swaminathan, H., & Rogers, H. J. (1990). Detecting differential item functioning using logistic regression procedures. *Journal of Educational Measurement*, 27(4), 361–370. <https://doi.org/10.1111/j.1745-3984.1990.tb00754.x>. Logistic-regression DIF.\n- Halpin, P. F. (2024). Differential item functioning via robust scaling. *Psychometrika*, 89(3), 796–821. <https://doi.org/10.1007/s11336-024-09957-6>. DIF without choosing anchors: items with DIF as outliers in IRT scaling. The `robustDIF` package (Halpin, 2026, <https://doi.org/10.32614/CRAN.package.robustDIF>) implements it.\n- Jodoin, M. G., & Gierl, M. J. (2001). Evaluating Type I error and power rates using an effect size measure with the logistic regression procedure for DIF detection. *Applied Measurement in Education*, 14(4), 329–349. <https://doi.org/10.1207/S15324818AME1404_2>. An effect size for the logistic approach, to go with its tests.\n- Steinberg, L., & Thissen, D. (2006). Using effect sizes for research reporting: Examples using item response theory to analyze differential item functioning. *Psychological Methods*, 11(4), 402–415. <https://doi.org/10.1037/1082-989X.11.4.402>. DIF reported as sizes rather than tests.\n- Magis, D., Béland, S., Tuerlinckx, F., & De Boeck, P. (2010). A general framework and an R package for the detection of dichotomous differential item functioning. *Behavior Research Methods*, 42(3), 847–862. <https://doi.org/10.3758/BRM.42.3.847>. The `difR` package.\n- Gilbert, J. B., Kim, J. S., & Miratrix, L. W. (2023). Modeling item-level heterogeneous treatment effects with the explanatory item response model: Leveraging large-scale online assessments to pinpoint the impact of educational interventions. *Journal of Educational and Behavioral Statistics*, 48(6), 889–913. <https://doi.org/10.3102/10769986231171710>. Treatment effects item by item, as a model.\n- Ahmed, I., Bertling, M., Zhang, L., Ho, A. D., Loyalka, P., & Xue, H. (2025). Heterogeneity of item-treatment interactions masks complexity and generalizability in randomized controlled trials. *Journal of Research on Educational Effectiveness*, 18(4), 854–877. <https://doi.org/10.1080/19345747.2024.2361337>. DIF by treatment across 15 trials.\n- Kim, J. S., Relyea, J. E., Burkhauser, M. A., Scherer, E., & Rich, P. (2021). Improving elementary grade students' science and social studies vocabulary knowledge depth, reading comprehension, and argumentative writing: A conceptual replication. *Educational Psychology Review*, 33(4), 1935–1964. <https://doi.org/10.1007/s10648-021-09609-6>. The trial behind the vocabulary test.\n- From the IRW: the [gender DIF vignette](https://itemresponsewarehouse.org/vignettes/gender_dif.html), the corpus question of *Across the IRW*.\n- Gamerman, D., Gonçalves, F. B., & Soares, T. M. (2017). Differential item functioning. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 3. Applications* (pp. 67–86). Chapman and Hall/CRC. <https://doi.org/10.1201/9781315117430>. A handbook chapter on differential item functioning.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`gilbert_meta_11`](https://itemresponsewarehouse.org/tables/gilbert_meta_11/): Kim, J. S., Relyea, J. E., Burkhauser, M. A., Scherer, E., & Rich, P. (2021). Improving elementary grade students’ science and social studies vocabulary knowledge depth, reading comprehension, and argumentative writing: A conceptual replication. Educational Psychology Review, 1-30. Kim, James; Relyea, Jackie Eunjung; Burkhauser, Mary A.; Scherer, Ethan; Rich, Patrick, 2021, \"Replication Data for: Improving Elementary Grade Students’ Science and Social Studies Vocabulary Knowledge Depth, Reading Comprehension, and Argumentative Writing: A Conceptual Replication\", <https://doi.org/10.7910/DVN/HQEMN6>, Harvard Dataverse, V1, UNF:6:fM1zIBl88IKxt400zYOJag== [fileUNF]. Licence: CC BY-NC-SA 4.0.\n- [`DART_Brysbaert_2020_1`](https://itemresponsewarehouse.org/tables/dart_brysbaert_2020_1/): Brysbaert, M., Sui, L., Dirix, N., & Hintz, F. (2020). Dutch Author Recognition Test. Journal of Cognition, 3(1), 6. <https://doi.org/10.5334/joc.95>. Licence: CC BY-NC-SA 4.0.\n- [`alexandrowicz_2018_cesd`](https://itemresponsewarehouse.org/tables/alexandrowicz_2018_cesd/): Alexandrowicz, R.; Jahn, R.; Wancata, J. (2018). Assessing the dimensionality of the CES-D using multi-dimensional multi-level Rasch models. PLOS ONE, 13(5), e0197908. <https://doi.org/10.1371/journal.pone.0197908>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 5 (slides c5, 1–31) and problem set 5 (#3), with the code in `ben-domingue/252`: `c5/art.R` and `ps5/dif_itemtext.R`. Polytomous DIF (PS8#3, `ps8/polydif.R`) is problem 3.\n- **Timing:** about 60 minutes for the core ideas and widgets; the vocabulary analysis works as a 30-minute lab, and problem 2 extends it.\n- **Changed from 252 (Ben, 09-24 and 09-25):** impact vs. bias, sources of bias and predictive bias moved to [Fairness in testing](fairness.qmd); logistic regression is a core idea of its own; anchor selection and robust scaling ([Halpin, 2024](https://doi.org/10.1007/s11336-024-09957-6)) are a Go deeper; multigroup CFA invariance moved to [Factor analysis II](fa-confirmatory.qmd) and is recalled here in one paragraph; polytomous DIF became problem 3, taught self-contained; the slides' author-recognition example (DART) opens the lesson (Ben, 09-25), with the foils removed and the small sample stated; problem 4 now matches on the baseline score. The main example takes the demographic groupings first and turns to treatment. The slides' SAT analogy example is left out, because its source couldn't be checked.\n- **Held back:** DIF by treatment and by life events ([Measurement invariance under treatment and life events](invariance-experience.qmd)); anchors in linking ([Linking and equating](equating.qmd)); explaining DIF with item features ([What is an item?](explanatory-irt.qmd)); DIF screens for item banks ([Item banks and adaptive testing](item-banks-cat.qmd)).\n- **Data:** in `gilbert_meta_11` the scoring rule (whether a 1 needs both words right) isn't documented, and the grade rests on the IRW description and item text. In the DART table three labels begin with \"1\" where the name begins \"Ja\" (`1ne Austen`, `1ne Jessup`, `1mes Patterson`), which matters when matching them to the paper's foil list; the respondents are mostly 18 years old.\n- **Across the IRW:** `deepdives/dif/compute.R` is run by hand (it needs a Redivis token); the page reads its `results.rds`. The pilot took under a minute for six tables.\n- **Solutions:** held back in `solutions/dif.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "dif_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}