# Writes lessons/code/_webr-setup.R, the hidden code every lesson runs in the
# browser before any webR cell. GENERATED: edit this script, not the output.
#
# Why it exists: mirt imports SimDesign, and webR's R 4.6 build of SimDesign
# imports 'mirai' and 'qs2', neither of which can be built for WebAssembly
# (mirai needs 'nanonext'). So library(mirt) fails in the browser. The stubs in
# webr/stubs/ satisfy those imports (four functions, none used when fitting
# models) and stop with a message if called. They are embedded as hex rather than
# served from a URL, because webR fetches from its own worker and cannot resolve
# a path relative to the page. Delete webr/ and this step once library(mirt)
# works in webR without it.
#
# Run from course/ after editing a stub:  Rscript webr/build_repo.R
tmp <- tempfile(); dir.create(tmp)
old <- setwd(tmp)
for (pkg in list.dirs(file.path(old, "webr", "stubs"), recursive = FALSE))
  system2(file.path(R.home("bin"), "R"),
          c("CMD", "INSTALL", "--build", "--no-test-load", "-l", tmp, pkg),
          stdout = FALSE, stderr = FALSE)
setwd(old)
built <- list.files(tmp, pattern = "\\.tar\\.gz$", full.names = TRUE)
hex <- vapply(built, function(f) paste(readBin(f, "raw", file.size(f)), collapse = ""), "")
names(hex) <- sub("_.*$", "", basename(built))
out <- c(
  "# GENERATED by webr/build_repo.R -- do not edit. Runs hidden before any in-browser",
  "# code on a lesson page: installs mirt, then replaces 'mirai' and 'qs2' with stubs",
  "# so mirt can load (see webr/build_repo.R for why). Not needed in local R.",
  "# Warnings about nanonext and qs2 are expected: those are what the stubs replace.",
  "suppressWarnings(webr::install(\"mirt\", quiet = TRUE))",
  "local({",
  "  stubs <- c(",
  paste0("    ", names(hex), " = \"", hex, "\"", c(rep(",", length(hex) - 1), "")),
  "  )",
  "  # mirt's install puts the real mirai in a read-only mount, so it can't be",
  "  # replaced; the stubs go in their own library, searched first.",
  "  lib <- file.path(tempdir(), \"stubs\")",
  "  dir.create(lib, showWarnings = FALSE)",
  "  for (h in stubs) {",
  "    f <- tempfile(fileext = \".tar.gz\")",
  "    writeBin(as.raw(strtoi(substring(h, seq(1, nchar(h), 2), seq(2, nchar(h), 2)), 16L)), f)",
  "    untar(f, exdir = lib, tar = \"internal\")  # webR has no system tar",
  "  }",
  "  .libPaths(c(lib, .libPaths()))",
  "})",
  "options(mc.cores = 1)  # webR cannot fork; keeps any parallel::mclapply sequential",
  "suppressPackageStartupMessages(library(mirt))"
)
writeLines(out, file.path("lessons", "code", "_webr-setup.R"))
cat("wrote lessons/code/_webr-setup.R with stubs:", names(hex), "\n")
