{
  "hash": "56859976e8410419ea1f263dd66711fc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Rater models: many-facet Rasch and beyond\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Beyond the standard models  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [Many sources of error: generalizability theory](g-theory.qmd) · [The Rasch model](rasch.qmd) · [Models for polytomous responses](polytomous.qmd)  \n**Builds toward:** none  \n**Picks up threads:** The sum score is sufficient under the Rasch model (from [The Rasch model](rasch.qmd)); Responses are independent given θ (from [The Rasch model](rasch.qmd)); Raters are treated as exchangeable draws from a universe of raters (from [Many sources of error: generalizability theory](g-theory.qmd))  \n**IRW tables:** [`Forthmann-2024-cleverness_ratings`](https://itemresponsewarehouse.org/tables/forthmann-2024-cleverness_ratings/), [`teacherjudgements_lohmann_2026_essayratings`](https://itemresponsewarehouse.org/tables/teacherjudgements_lohmann_2026_essayratings/)  \n**From EDUC 252:** n/a  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\nwebr::install(\"TAM\", quiet = TRUE)\nsuppressPackageStartupMessages(library(TAM))\noptions(mc.cores = 1)\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {palette} from \"./widgets/irt.js\"\nimport {harshRater, ratingDist, hrmSE, drift} from \"./widgets/rater-models.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nWhen each essay is read by whichever teacher it was assigned to, a harsh teacher is not noise to be averaged away: it is a bias in the scores of the essays that teacher happened to read. [Many sources of error: generalizability theory](g-theory.qmd) summarized raters with a variance component, which answers a design question (how many raters?) but not a respondent's question: was I scored by a harsh rater, and what would my score have been otherwise? This lesson gives each rater parameters of their own inside an item response model: severity in the many-facet Rasch model, centrality and halo, the hierarchical rater model for several ratings of one response, and drift. In the cleverness ratings the raters differ modestly and adjusting changes little; in the essays, teachers differ by about half a point, and an expert benchmark lets us check the adjustment.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Many sources of error: generalizability theory](g-theory.qmd): rater severity, $\\sigma^2_r$, is error for absolute decisions and, when respondents have different raters, for ranking too. It was 2.1% of a rating's variance in the cleverness ratings and 9.7% in the essays. Problem 6 asked when severity should be estimated and adjusted for instead.\n:::\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- write the many-facet Rasch model, and say what a rater's severity is and what the rating design must provide to estimate it;\n- fit the model with `TAM`, read a Wright map with a rater column, and adjust scores for the raters a respondent drew;\n- tell severity, centrality and halo apart, and say what data would show each;\n- explain why the hierarchical rater model gives extra ratings of one response less credit than the many-facet model does;\n- say when a rater is better treated as a fixed parameter, a random effect or a variance component.\n\n## Core ideas\n\n### Which rater, and by how much?\n\nG theory and a rater model can be fitted to the same ratings ([Sudweeks, Reeve & Bradshaw, 2004](https://doi.org/10.1016/j.asw.2004.11.001)), and G theory can itself be written as an item response model ([Briggs & Wilson, 2007](https://doi.org/10.1111/j.1745-3984.2007.00031.x)). They report different things. G theory says how large the rater component is, which is what you need to choose a design. A rater model says that rater 5 is 0.37 logits harsher than average, with a standard error, which is what you need to fix one respondent's score. When every respondent has the same raters, severity shifts everyone alike and the two agree on ranking; when raters vary across respondents, they part.\n\n### The many-facet Rasch model\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd) and [Models for polytomous responses](polytomous.qmd): the Rasch log-odds is $\\theta_j - b_i$, persons and items share one scale (the Wright map), and the sum score is sufficient. The rating scale model ([Andrich, 1978](https://doi.org/10.1007/BF02293814)) makes each step between adjacent categories a Rasch item, with the same steps for every item.\n:::\n\nAdd a rater. For respondent $j$, task $i$ and rater $r$, the **many-facet Rasch model** ([Linacre, 1989](https://www.winsteps.com/a/Linacre-MFRM-book.pdf); [Eckes, 2011](https://doi.org/10.3726/978-3-653-04844-5)) writes the log-odds of category $k$ over $k-1$ as\n$$\\log\\frac{\\Pr(x_{ijr} = k)}{\\Pr(x_{ijr} = k-1)} = \\theta_j - b_i - \\rho_r - \\tau_k .$$\n$\\rho_r$ is the rater's **severity**: a harsh rater acts like a harder item. The steps $\\tau_k$ are shared by every task and rater. Raters are a third **facet**, and go on the Wright map beside the tasks ([Engelhard, 1994](https://doi.org/10.1111/j.1745-3984.1994.tb00436.x), for essays; [Eckes, 2005](https://doi.org/10.1207/s15434311laq0203_2), for writing and speaking tests).\n\nThe Rasch algebra carries over: given the raters a respondent drew, the sum of the ratings is sufficient, and the estimate solves \"expected total = observed total\". The expected total depends on the raters, so equal raw totals from different raters give different estimates. That is the adjustment. Its usual report is the **fair average**, the rating a respondent would be expected to get from an average rater on average tasks ([Linacre, Facets manual](https://www.winsteps.com/facetman/fairaverage.htm)).\n\nThe adjustment has a price in design: severity and ability are separated only if the raters are linked, their respondents overlapping directly or through a chain of raters.\n\n#### Try it: one harsh rater\n\nTwo hundred simulated respondents do three tasks, rated 1–5 by some of five raters drawn at random; rater 5 is harsher by the amount set below. Left: the raw mean rating. Right: the model's estimate of $\\theta$, with the severities known (as after calibration).\n\n```{ojs}\n//| echo: false\nviewof hr_harsh = Inputs.range([0, 2], {value: 1, step: 0.1, label: \"How much harsher rater 5 is (logits)\"})\nviewof hr_per = Inputs.radio([2, 3, 5], {value: 2, label: \"Raters per respondent\"})\n```\n\n```{ojs}\n//| echo: false\nhr = harshRater({seed: 150, n: 200, harsh: hr_harsh, per: hr_per})\nhr_plot = (y, label) => Plot.plot({\n  width: 340, height: 300, x: {label: \"True θ\"}, y: {label},\n  color: {domain: [\"did not\", \"drew the harsh rater\"], range: [palette.light, palette.contrast], legend: true},\n  marks: [Plot.dot(hr.pts, {x: \"theta\", y, fill: \"drew\", r: 3, fillOpacity: 0.8})]\n})\nhtml`<div style=\"display:flex;flex-wrap:wrap;gap:1rem\">${hr_plot(\"raw\", \"Raw mean rating\")}${hr_plot(\"est\", \"Model estimate of θ\")}</div>`\n```\n\n```{ojs}\n//| echo: false\nmd`${hr.nHarsh} of 200 respondents drew rater 5. Their average distance from others with the same θ, in SDs of each score: **${hr.gapRaw.toFixed(2)}** on the raw mean, **${hr.gapEst.toFixed(2)}** on the model's estimate.`\n```\n\nAt the starting values, respondents who drew rater 5 sit 0.19 SDs lower on the raw mean than others with the same $\\theta$; the model's estimate removes the gap (0.02). Push the harshness to 2 and the raw gap doubles, to 0.40. Give everyone all five raters and the gap is zero for both.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Rater A scored only the essays from school 1 and rater B only those from school 2. School 2's essays average one point lower. What can a many-facet Rasch analysis conclude?\",\n  options: [\n    {text: \"Nothing about which is harsher: rater and school are confounded\", correct: true, why: \"No essay links the two raters, so a lower average from B could be B's severity or school 2's essays. Severity is estimable only through overlap, direct or through a chain of raters.\"},\n    {text: \"Rater B is one point harsher\", correct: false, why: \"That assumes the two schools' essays are equally good, which is the question. The model can't separate the two without essays both raters scored.\"},\n    {text: \"School 2's essays are one point weaker\", correct: false, why: \"That assumes the raters are equally severe. Without linking essays, either reading fits the data equally well.\"}\n  ]\n})\n```\n\nShould you adjust? That rests on three assumptions: the design is linked, severities differ by more than their standard errors, and a rater's severity is the same for every respondent. When scores go to individuals, raters vary across respondents, and those assumptions hold, I adjust for severity and say in the report that I did. When every respondent had the same raters, I report the raw mean, since the adjustment can't change the order.\n\n### Beyond severity: centrality and halo\n\nSeverity is where a rater sits. **Centrality** is how a rater uses the scale: a central rater avoids the ends and piles ratings in the middle, which shows up as rater-specific steps pulled apart. **Halo**: a rater's overall impression colours every criterion, so criteria move together more than the performance does ([Thorndike, 1920](https://doi.org/10.1037/h0071663), described it; [Saal, Downey & Lahey, 1980](https://doi.org/10.1037/0033-2909.88.2.413), review how halo and other rating errors have been defined and measured). Each is a question for the data, not a charge against a rater: highly correlated criteria may reflect essays whose qualities do go together.\n\n#### Try it: a central rater\n\nOne rater's ratings over a population of respondents, next to a typical rater's. Severity moves the steps together; spread stretches them apart (above 1) or squeezes them (below 1).\n\n```{ojs}\n//| echo: false\nviewof rd_sev = Inputs.range([-1.5, 1.5], {value: 0, step: 0.1, label: \"Severity (logits)\"})\nviewof rd_spread = Inputs.range([0.5, 2], {value: 1.6, step: 0.05, label: \"Spread of the steps\"})\n```\n\n```{ojs}\n//| echo: false\nrd = ratingDist({sev: rd_sev, spread: rd_spread})\nPlot.plot({\n  width: 640, height: 260, x: {label: null, axis: null}, fx: {label: \"Rating\"}, y: {label: \"Proportion\", grid: true},\n  color: {domain: [\"typical rater\", \"this rater\"], range: [palette.light, palette.main], legend: true},\n  marks: [Plot.barY(rd.rows, {fx: \"rating\", x: \"rater\", y: \"p\", fill: \"rater\"})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Typical rater: mean **${rd.typical.m.toFixed(2)}**, SD **${rd.typical.sd.toFixed(2)}**. This rater: mean **${rd.me.m.toFixed(2)}**, SD **${rd.me.sd.toFixed(2)}**.`\n```\n\nWith the steps spread by 1.6, the rater gives a 3 to 48% of respondents (against 36%) and the SD falls from 0.98 to 0.77, while the mean barely moves (2.95 against 2.97). Set spread to 1 and severity to 0.8, and the mean falls to 2.55 instead. Centrality is invisible in a rater's mean, so one severity per rater misses it.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A rater gives nearly every essay a 3 or a 4 on a 1–6 scale, and their average matches the other raters'. What does a many-facet Rasch model with one severity per rater and shared steps say about this rater?\",\n  options: [\n    {text: \"Average severity; the pattern needs rater-specific steps to show\", correct: true, why: \"A shared-steps model has only a location for each rater, and this rater's location is average. Giving each rater their own steps shows this rater's outer steps far apart.\"},\n    {text: \"Harsh, because they never give a 6\", correct: false, why: \"They never give a 1 either. Severity is a shift of the whole scale, and this rater's average isn't shifted.\"},\n    {text: \"Inconsistent, so they add a large person × rater variance\", correct: false, why: \"Centrality is a systematic squeeze, not noise. A central rater can order essays just as the others do while using fewer categories.\"}\n  ]\n})\n```\n\n### The hierarchical rater model: raters rate the response\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd): responses are assumed **locally independent**, so once we know $\\theta$, one response says nothing more about another.\n:::\n\nThe many-facet model applies that assumption to ratings: five ratings of one response count as five items, and each extra rater shrinks the standard error of $\\hat\\theta$ as an extra item would. But the five raters read the same response. If the respondent had an off day on the rope task, all five see a weaker list.\n\nThe **hierarchical rater model** ([Patz, Junker, Johnson & Mariano, 2002](https://doi.org/10.3102/10769986027004341)) puts the response between respondent and raters. Each response has an **ideal rating** $\\xi_{ij}$, the category a perfectly accurate rater would give, generated from $\\theta_j$ by a polytomous item response model; each rater reports $\\xi_{ij}$ with a severity and precision of their own; [DeCarlo, Kim and Johnson (2011)](https://doi.org/10.1111/j.1745-3984.2011.00143.x) use a signal-detection model for that layer. More raters pin down $\\xi_{ij}$, and $\\xi_{ij}$ is one observation of $\\theta_j$, so the information about $\\theta_j$ from one response can never exceed what the ideal rating carries. [Wilson and Hoskens (2001)](https://doi.org/10.3102/10769986026003283) model the same dependence with a rater bundle model and argue that ignoring it understates measurement error.\n\n#### Try it: more raters, same responses\n\nA binary version of both models: ten items at difficulty 0, a respondent at $\\theta = 0$, each ideal rating a Rasch item, and each rater reporting it correctly with the probability set below.\n\n```{ojs}\n//| echo: false\nviewof hs_acc = Inputs.range([0.6, 0.99], {value: 0.8, step: 0.01, label: \"Chance a rater reports the ideal rating\"})\n```\n\n```{ojs}\n//| echo: false\nhs = hrmSE({acc: hs_acc, nItems: 10, maxR: 20})\nPlot.plot({\n  width: 640, height: 300, x: {label: \"Raters per response\"}, y: {label: \"SE of θ\", domain: [0, 1.8], grid: true},\n  color: {legend: true, range: [palette.main, palette.contrast]},\n  marks: [Plot.line(hs.rows, {x: \"R\", y: \"se\", stroke: \"model\", strokeWidth: 2.5}),\n          Plot.ruleY([hs.floor], {stroke: palette.guide, strokeDasharray: \"4 3\"})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`With 20 raters: **${hs.rows.find(d => d.R === 20 && d.model.startsWith(\"hier\")).se.toFixed(3)}** under the hierarchical rater model, **${hs.rows.find(d => d.R === 20 && d.model.startsWith(\"local\")).se.toFixed(3)}** if the ratings were independent. The dashed line, **${hs.floor.toFixed(3)}**, is the SE if every ideal rating were known.`\n```\n\nWith raters who are right 80% of the time, 20 raters give a standard error of 0.634 under the hierarchical model, a hair above the floor of 0.632 set by the ideal ratings, against 0.236 if the ratings were independent. With one rater the models agree. Sharper raters (0.95) reach the floor with five raters; nothing goes below it (Go deeper, below).\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: why extra raters can't beat the ideal rating\n\n**Assumptions:** one response to one item with ideal rating $\\xi$, whose distribution $\\Pr(\\xi \\mid \\theta)$ depends on $\\theta$; ratings $\\mathbf{x} = (x_1, \\dots, x_R)$ that depend on $\\theta$ only through $\\xi$, so $\\Pr(\\mathbf{x} \\mid \\xi, \\theta) = \\Pr(\\mathbf{x} \\mid \\xi)$. Nothing is assumed about how the raters err.\n\n**Fisher information as a variance.** The information about $\\theta$ in data $Y$ is $I_Y(\\theta) = \\text{Var}\\big(\\partial_\\theta \\log \\Pr(Y \\mid \\theta)\\big)$, the variance of the score.\n\n**The ratings' score is a conditional mean.** Since $\\Pr(\\mathbf{x} \\mid \\theta) = \\sum_\\xi \\Pr(\\xi \\mid \\theta)\\Pr(\\mathbf{x} \\mid \\xi)$,\n$$\\partial_\\theta \\log \\Pr(\\mathbf{x} \\mid \\theta) = \\sum_\\xi \\frac{\\Pr(\\xi \\mid \\theta)\\Pr(\\mathbf{x} \\mid \\xi)}{\\Pr(\\mathbf{x} \\mid \\theta)}\\,\\partial_\\theta \\log \\Pr(\\xi \\mid \\theta) = E\\big[S \\,\\big|\\, \\mathbf{x}\\big], \\qquad S = \\partial_\\theta \\log \\Pr(\\xi \\mid \\theta).$$\nThe weights are the posterior probabilities of each $\\xi$ given the ratings, so the ratings' score is the ideal rating's score averaged over what the ratings leave uncertain about $\\xi$.\n\n**A conditional mean has less variance.** By the law of total variance, $\\text{Var}(S) = \\text{Var}\\big(E[S \\mid \\mathbf{x}]\\big) + E\\big[\\text{Var}(S \\mid \\mathbf{x})\\big] \\ge \\text{Var}\\big(E[S \\mid \\mathbf{x}]\\big)$. So\n$$I_{\\mathbf{x}}(\\theta) \\le I_\\xi(\\theta)$$\nfor any number of raters. Equality needs $\\text{Var}(S \\mid \\mathbf{x}) = 0$: the ratings must reveal $\\xi$ exactly, which is the limit as raters become many or perfect. $\\blacksquare$\n\nUnder local independence the information from $R$ raters is instead $R$ times the information from one, which grows without bound. The two agree at $R = 1$ and part as $R$ grows, as in the widget. With several items, sum over items: the bound is the information in the ideal ratings, the test a perfect rater would have scored.\n:::\n\nThe hierarchical model's item response layer can be multidimensional ([Nieto & Casabianca, 2019](https://doi.org/10.1111/jedm.12225)) or longitudinal ([Casabianca, Junker, Nieto & Bond, 2017](https://doi.org/10.1080/00273171.2017.1342202)). The many-facet model is a reasonable choice when each response gets one rating, or when the raters are the object of study (monitoring a scoring session), since its parameters are simple to read and it fits in seconds.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A program has 100 raters score every response on a 20-item constructed-response test. Under the hierarchical rater model, what is the standard error of a respondent's $\\\\hat\\\\theta$ close to?\",\n  options: [\n    {text: \"The SE the test would have if a perfect rater had scored it\", correct: true, why: \"With 100 raters each ideal rating is nearly known, so the information is nearly that of the 20 ideal ratings. The raters can't add information the responses don't carry.\"},\n    {text: \"Close to zero: 2,000 ratings is a lot of data\", correct: false, why: \"That is what local independence would say. Under the hierarchical model the 100 ratings of one response are 100 looks at one ideal rating.\"},\n    {text: \"About the SE with one rater per response\", correct: false, why: \"One fallible rater leaves each ideal rating uncertain, so the SE is larger than the floor. More raters help until the ideal ratings are pinned down, and then stop helping.\"}\n  ]\n})\n```\n\n### Raters change, and raters are many\n\nA severity is a parameter only if it stays put. Add time to the rater term and test it: [Myford and Wolfe (2009)](https://doi.org/10.1111/j.1745-3984.2009.00088.x) give indices for raters whose accuracy or use of the scale changes during scoring. In two years of classroom-observation ratings of 458 teachers, [Casabianca, Lockwood and McCaffrey (2015)](https://doi.org/10.1177/0013164414539163) found drift that was very large in raters' first days and persisted for nearly two years, and the variability among raters grew rather than shrank. Their model is a G study with time trends: drift is a variance component and a rater parameter at once.\n\n#### Try it: drift\n\nEight raters score for 30 days, each moving by a fixed amount per day: a shared drift plus a part of their own.\n\n```{ojs}\n//| echo: false\nviewof dr_common = Inputs.range([-0.03, 0.03], {value: 0, step: 0.005, label: \"Shared drift per day (logits)\"})\nviewof dr_spread = Inputs.range([0, 0.05], {value: 0.02, step: 0.005, label: \"SD of raters' own drift per day\"})\n```\n\n```{ojs}\n//| echo: false\ndr = drift({seed: 2015, nr: 8, days: 30, common: dr_common, spread: dr_spread})\nPlot.plot({\n  width: 640, height: 280, x: {label: \"Day of scoring\"}, y: {label: \"Severity (logits)\", domain: [-1.8, 1.8], grid: true},\n  marks: [Plot.line(dr.rows, {x: \"day\", y: \"severity\", z: \"rater\", stroke: palette.light, strokeWidth: 1.5}),\n          Plot.line(dr.sds, {x: \"day\", y: \"mean\", stroke: palette.main, strokeWidth: 3})]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`SD of severity across raters: **${dr.sds[0].sd.toFixed(2)}** on day 1, **${dr.sds[29].sd.toFixed(2)}** on day 30. Mean severity (dark line): ${dr.sds[0].mean.toFixed(2)} on day 1, ${dr.sds[29].mean.toFixed(2)} on day 30.`\n```\n\nA shared drift moves the dark line and leaves the spread alone. Raters' own drift fans the lines out: at the starting values the SD across raters grows from 0.36 to 0.54, the pattern Casabianca et al. found, and a severity estimated on day 1 is out of date by day 30.\n\nTwo design points follow. First, raters must stay linked over time. A **linkage set**, responses scored by most or all raters, helps: [Casabianca, Donoghue, Shin, Chao and Choi (2023)](https://doi.org/10.1111/jedm.12360) found that a large one spanning the score scale improved connectedness, that two human ratings connected raters better than one human plus an automated engine, and that engine scores alone did not connect raters adequately. Second, with hundreds of raters rating a handful each, severities are better treated as **random effects**, shrunk toward the mean in proportion to how little each rater rated ([De Boeck, 2008](https://doi.org/10.1007/s11336-008-9092-x), does the same for items; fitted with `lme4`, [Bates, Mächler, Bolker & Walker, 2015](https://doi.org/10.18637/jss.v067.i01)). The random-effect variance is G theory's $\\sigma^2_r$ again. [What is an item?](explanatory-irt.qmd) develops random effects in item response models, and [AI and psychometrics](ai-psychometrics.qmd) treats an automated scoring engine as one more rater.\n\n## Simulate\n\nThe code simulates 200 respondents, three tasks and five raters, one harsh (rater 5) and one central (rater 4, steps stretched by 1.6), with two raters per respondent. It fits the many-facet Rasch model with `TAM` ([Robitzsch, Kiefer & Wu, 2025](https://doi.org/10.32614/CRAN.package.TAM)), then rater-specific steps, and compares raw means with the model's estimates. Loading `TAM` takes 20 to 30 seconds the first time; the fits take a second or two.\n\nWith the seed as written, the severities come back within 0.14 of the truth; rater 5's has the largest standard error (0.13), since `TAM` derives the last rater's value from the others'. Rater 4's first-to-last step span is 8.6 logits against 4.9 to 5.8 for the rest (truth 8.8 and 5.5). The raw mean and the estimate correlate about equally with $\\theta$ (0.90 and 0.91), but respondents who drew rater 5 sit 0.17 SDs low on the raw mean and 0.02 on the estimate. Set `per <- 5` and both correlations rise to 0.96, with no gap. Try a harsher rater 5, or `spread` of 1 for everyone.\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-19\n# Simulate ratings from a many-facet Rasch model with one harsh rater and one\n# central rater, fit the model with TAM (Robitzsch, Kiefer & Wu), and compare the\n# estimates with the truth. Then give each respondent only some of the raters and\n# see what adjusting for severity buys over the raw mean.\nlibrary(TAM)\nset.seed(150)\nnp  <- 200                          # respondents\nnt  <- 3                            # tasks\nper <- 2                            # raters per respondent (5 = fully crossed)\ntheta <- rnorm(np, 0, 1.2)          # respondents' levels, in logits\ndelta <- c(-0.2, 0, 0.2)            # task difficulties\nsev   <- c(-0.3, -0.2, 0, -0.1, 0.6)  # rater severities: rater 5 is harsh\ntau   <- c(-2.8, -0.7, 0.8, 2.7)    # steps between categories 0-1, ..., 3-4\nspread <- c(1, 1, 1, 1.6, 1)        # rater 4 stretches the steps apart: central\n\n# Rating scale model with a rater facet: the log-odds of category k over k - 1\n# is theta - delta - severity - tau_k (rater 4's taus are stretched).\nrate <- function(th, d, r) {\n  eta <- cumsum(th - d - sev[r] - tau * spread[r])\n  p <- exp(c(0, eta)); sample(0:4, 1, prob = p / sum(p))\n}\nrows <- do.call(rbind, lapply(1:np, function(j) {\n  raters <- sort(sample(1:5, per))\n  t(sapply(raters, function(r) c(id = j, rater = r, sapply(1:nt, function(i) rate(theta[j], delta[i], r)))))\n}))\nd <- as.data.frame(rows)\nnames(d)[3:(2 + nt)] <- paste0(\"task\", 1:nt)\nresp <- d[, 3:(2 + nt)]\n\n# Many-facet Rasch model: task + rater + common steps. TAM reports severities that\n# sum to zero, so compare them with the centred truth.\n# (TAM warns about row names when it builds the design matrices; the warnings are harmless.)\nfit <- suppressWarnings(tam.mml.mfr(resp, facets = d[\"rater\"], pid = d$id,\n                                    formulaA = ~ item + rater + step, verbose = FALSE))\nest <- fit$xsi.facets\nround(cbind(true = sev - mean(sev), estimate = est$xsi[est$facet == \"rater\"],\n            se = est$se.xsi[est$facet == \"rater\"]), 2)\n\n# Rater-specific steps: a central rater's outer steps sit further out.\nfit2 <- suppressWarnings(tam.mml.mfr(resp, facets = d[\"rater\"], pid = d$id,\n                                     formulaA = ~ item + rater + step + rater:step, verbose = FALSE))\nx2 <- fit2$xsi.facets\ndev <- x2[x2$facet == \"step:rater\", ]\nstep_of <- as.integer(sub(\"step(\\\\d):.*\", \"\\\\1\", dev$parameter))\nrater_of <- sub(\".*:rater\", \"\", dev$parameter)\ncommon <- setNames(x2$xsi[x2$facet == \"step\"], 1:4)\n# Distance from each rater's first step to their last: wider = more central.\nspan <- tapply(dev$xsi[step_of == 4], rater_of[step_of == 4], sum) -\n        tapply(dev$xsi[step_of == 1], rater_of[step_of == 1], sum) + common[4] - common[1]\nround(span, 2)\nround(c(common_steps_AIC = fit$ic$AIC, rater_steps_AIC = fit2$ic$AIC))\n\n# Scores: the raw mean of each respondent's ratings against the model's estimate\n# (weighted likelihood), each correlated with the true theta.\nwle <- tam.wle(fit, progress = FALSE)\nraw <- tapply(rowMeans(resp), d$id, mean)\ndrew_harsh <- tapply(d$rater == 5, d$id, any)\nround(c(raw = cor(raw, theta), model = cor(wle$theta, theta)), 3)\n# How far respondents who drew the harsh rater sit below others with the same true\n# theta, in SDs of each score (raw means are in rating points, estimates in logits):\ngap <- function(s) mean(resid(lm(s ~ theta))[drew_harsh]) / sd(s)\nround(c(raw = gap(raw), model = gap(wle$theta)), 2)\n\n```\n:::\n\n\n[Download this code](code/rater-models-sim.R).\n\n## With real data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsuppressPackageStartupMessages({library(TAM); library(sirt); library(lme4)})\noptions(digits = 7)  # R's default, in case a .Rprofile changes it\n# TAM's many-facet fits warn about row names while building design matrices; the\n# warnings are harmless, so each fit goes through this wrapper.\nmfr <- function(...) suppressWarnings(tam.mml.mfr(..., verbose = FALSE))\n# Rater-specific steps from a rater:step fit: each rater's distance from their\n# first step to their last, in logits. Wider means ratings squeezed toward the middle.\nstep_span <- function(fit) {\n  x <- fit$xsi.facets\n  dev <- x[x$facet %in% c(\"rater:step\", \"step:rater\"), ]\n  k <- as.integer(sub(\".*step(\\\\d).*\", \"\\\\1\", dev$parameter))\n  r <- sub(\".*(rater\\\\d+).*\", \"\\\\1\", sub(\"raterrater\", \"rater\", dev$parameter))\n  common <- x$xsi[x$facet == \"step\"]\n  if (!length(common)) common <- tapply(x$xsi[x$facet == \"item:step\"],\n    as.integer(sub(\".*step\", \"\", x$parameter[x$facet == \"item:step\"])), mean)\n  K <- max(k)\n  tapply(dev$xsi[k == K], r[k == K], sum) - tapply(dev$xsi[k == 1], r[k == 1], sum) +\n    common[K] - common[1]\n}\n```\n:::\n\n\nBoth tables return from [Many sources of error: generalizability theory](g-theory.qmd). [Download the code](code/rater-models-irw.R); it needs `TAM`, `sirt` ([Robitzsch, 2025](https://doi.org/10.32614/CRAN.package.sirt)) and `lme4`, and the hierarchical rater model takes one to two minutes.\n\n### Cleverness ratings: modest severities\n\nThe main example is [Forthmann-2024-cleverness_ratings](https://itemresponsewarehouse.org/tables/forthmann-2024-cleverness_ratings/) ([Forthmann & Myszkowski, 2024](https://osf.io/a9qnc); CC BY 4.0): 202 respondents' lists of unusual uses for a paperclip, a garbage bag and a rope, each rated for cleverness (1 to 5, higher is cleverer) by the same five raters. Its job: a fully crossed design, where rater parameters are cleanly estimable.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_2:v22_0.Forthmann-2024-cleverness_ratings/rows?format=csv\"\ncl <- read.csv(url)[, c(\"id\", \"item\", \"rater\", \"resp\")]\ntasks <- c(\"paperclip\", \"garbagebag\", \"rope\")\n# One row per respondent x rater, one column per task, categories 0-4 for TAM\nw <- reshape(cl, idvar = c(\"id\", \"rater\"), timevar = \"item\", direction = \"wide\")\nnames(w) <- sub(\"resp.\", \"\", names(w), fixed = TRUE)\nw <- w[order(w$id, w$rater), ]\nresp <- w[, tasks] - 1\ndim(resp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1010    3\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(cl$resp, cl$rater, mean), 2)   # raw mean rating by rater, on 1-5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrater1 rater2 rater3 rater4 rater5 \n  3.02   3.12   3.18   2.88   2.80 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nfit_cl <- mfr(resp, facets = w[\"rater\"], pid = w$id, formulaA = ~ item + rater + step)\nxs <- fit_cl$xsi.facets\nsev <- xs[xs$facet == \"rater\", c(\"parameter\", \"xsi\", \"se.xsi\")]\nsev$parameter <- sub(\"raterrater\", \"rater\", sev$parameter)\ndata.frame(rater = sev$parameter, severity = round(sev$xsi, 2), se = round(sev$se.xsi, 3))  # higher = harsher\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|rater  | severity|    se|\n|:------|--------:|-----:|\n|rater1 |    -0.04| 0.039|\n|rater2 |    -0.23| 0.039|\n|rater3 |    -0.32| 0.039|\n|rater4 |     0.22| 0.039|\n|rater5 |     0.37| 0.079|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(sd_severity = sd(sev$xsi), sd_persons = sqrt(fit_cl$variance[1, 1])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd_severity  sd_persons \n       0.29        1.19 \n```\n\n\n:::\n:::\n\n\nSeverities run from −0.32 (rater 3) to 0.37 (rater 5), with standard errors of about 0.04 (0.08 for rater 5, derived from the others'), so the raters differ reliably, but modestly against the respondents: the SD of the severities is 0.29, against 1.19 for $\\theta$. That is G theory's 2.1% seen one rater at a time, and on the Wright map the raters make a tight column well inside the spread of respondents.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwle_cl <- tam.wle(fit_cl, progress = FALSE)\nsteps <- xs$xsi[xs$facet == \"step\"]; items <- xs[xs$facet == \"item\", ]\nh <- hist(wle_cl$theta, breaks = seq(-5, 5, 0.25), plot = FALSE)\nplot(NULL, xlim = c(-45, 42), ylim = c(-4.5, 4.5), xaxt = \"n\", xlab = \"\", ylab = \"Logits\",\n     las = 1, main = \"Cleverness ratings: a Wright map with a rater column\")\nrect(-h$counts, h$breaks[-length(h$breaks)], 0, h$breaks[-1], col = \"#93c5fd\", border = \"white\")\n# Each task and rater gets its own column, so the labels don't overlap\npoints(c(5, 9, 13), items$xsi, pch = 18, cex = 1.6, col = \"#c2410c\")\ntext(c(5, 9, 13), items$xsi, c(\"clip\", \"bag\", \"rope\"), pos = 3, cex = 0.7)\npoints(seq(20, 36, 4), sev$xsi, pch = 15, cex = 1.3, col = \"#2780e3\")\ntext(seq(20, 36, 4), sev$xsi, sub(\"rater\", \"\", sev$parameter), pos = 3, cex = 0.7)\nabline(v = 0); mtext(c(\"Respondents\", \"Tasks\", \"Raters\"), side = 1, at = c(-22, 9, 28), line = 1)\n```\n\n::: {.cell-output-display}\n![](rater-models_files/figure-html/wright-clever-1.png){width=672}\n:::\n:::\n\n\nDoes adjusting change anyone's score? With every respondent rated by every rater it can't change the order: the raw mean and the estimate correlate 0.996. So keep two raters per respondent, at random, and compare each score with the full-data estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Fully crossed: every respondent had every rater, so severity shifts everyone alike.\nraw_cl <- tapply(cl$resp, cl$id, mean)[wle_cl$pid]\nround(cor(raw_cl, wle_cl$theta), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.996\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Now pretend each respondent had only two of the five raters, drawn at random, and\n# compare each score with the full-data estimate.\nset.seed(150)\nkeep <- unlist(lapply(unique(w$id), function(i) paste(i, sample(unique(w$rater), 2))))\nsub2 <- paste(w$id, w$rater) %in% keep\nfit_2 <- mfr(resp[sub2, ], facets = w[sub2, \"rater\", drop = FALSE], pid = w$id[sub2],\n             formulaA = ~ item + rater + step)\nwle_2 <- tam.wle(fit_2, progress = FALSE)\nraw_2 <- tapply(rowMeans(resp[sub2, ], na.rm = TRUE), w$id[sub2], mean)[wle_2$pid]\nfull <- setNames(wle_cl$theta, wle_cl$pid)[wle_2$pid]\nround(c(raw_mean = cor(raw_2, full), mfrm = cor(wle_2$theta, full)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nraw_mean     mfrm \n   0.948    0.951 \n```\n\n\n:::\n:::\n\n\nThe raw mean correlates 0.948 with the full-data estimate, the model's estimate 0.951: with severities this close, the adjustment buys little. Centrality is another matter:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nfit_cs <- mfr(resp, facets = w[\"rater\"], pid = w$id, formulaA = ~ item + rater + step + rater:step)\nround(rbind(step_span = step_span(fit_cs), raw_sd = tapply(cl$resp, cl$rater, sd)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          rater1 rater2 rater3 rater4 rater5\nstep_span   5.05   6.41   6.93   5.15   5.25\nraw_sd      1.06   0.92   0.89   0.99   0.98\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(common_steps = fit_cl$ic$Npars, rater_steps = fit_cs$ic$Npars)      # parameters\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncommon_steps  rater_steps \n          11           23 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(common_steps = fit_cl$ic$AIC, rater_steps = fit_cs$ic$AIC))   # AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncommon_steps  rater_steps \n        7149         7112 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(common_steps = fit_cl$ic$BIC, rater_steps = fit_cs$ic$BIC))   # BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncommon_steps  rater_steps \n        7186         7188 \n```\n\n\n:::\n:::\n\n\nRater 3's steps span 6.93 logits and rater 1's 5.05, and the raw SDs agree (0.89 and 1.06): rater 3 keeps to the middle, rater 1 uses the ends. AIC prefers rater-specific steps (7,112 against 7,149); BIC, which charges more for the 12 extra parameters, is indifferent (7,188 against 7,186).\n\nNow the hierarchical rater model (`sirt`'s signal-detection version), next to the many-facet model fitted by the same package.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The hierarchical rater model with a signal-detection rater level (DeCarlo, Kim &\n# Johnson, 2011): each response has an ideal rating; each rater has a precision d\n# and thresholds c. sirt's rm.facets fits the many-facet model on the same footing.\n# (Both functions print their progress; capture.output keeps it off the page.)\ninvisible(capture.output(\n  hrm <- rm.sdt(resp, pid = w$id, rater = w$rater, est.c.rater = \"r\", est.d.rater = \"r\",\n                maxiter = 500),\n  fac <- rm.facets(resp, pid = w$id, rater = w$rater)))\nround(c(facets_reliability = fac$EAP.rel, hrm_reliability = hrm$EAP.rel), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfacets_reliability    hrm_reliability \n              0.92               0.73 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(facets_AIC = fac$ic$AIC, hrm_AIC = hrm$ic$AIC))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfacets_AIC    hrm_AIC \n      7135       6539 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Rater precision d (higher = sharper), the same for every task in this fit\nround(tapply(hrm$rater$d, sub(\".*-\", \"\", hrm$rater$item.rater), mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrater1 rater2 rater3 rater4 rater5 \n  2.59   2.85   2.58   2.31   2.75 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(cor(hrm$person$EAP, fac$person$EAP), 3)        # the two models' person estimates\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.99\n```\n\n\n:::\n:::\n\n\nThe two models order respondents almost identically (estimates correlate 0.99) but disagree about precision: reliability 0.92 for the many-facet model, 0.73 for the hierarchical one. The hierarchical model also fits much better (AIC 6,539 against 7,135): five ratings of one list agree more than local independence allows. Its reliability sits near the relative G coefficient of 0.71 that G theory gave this design, and below the 0.77 no number of raters could beat with three tasks. The many-facet model counts 15 ratings as 15 items; G theory and the hierarchical model count three responses, each read five times. Rater precision runs from 2.31 (rater 4) to 2.85 (rater 2).\n\n### Essays: leniency, a benchmark, and halo\n\nThe contrast is [teacherjudgements_lohmann_2026_essayratings](https://itemresponsewarehouse.org/tables/teacherjudgements_lohmann_2026_essayratings/) ([Lohmann et al., 2026](https://doi.org/10.1037/edu0000969); CC BY 4.0): 315 preservice English teachers each rated five essays by learners of English on four criteria (language quality, structure, content, holistic), from 1 (very low quality) to 7 (very high). Its job: a sparse design with many raters, and an outside standard.\n\nThat standard is the `expert_benchmark` rows, one score per essay and criterion, which the study's [codebook](https://osf.io/eu2zb/) describes as the fair score from a FACETS rater model of trained experts' ratings: the output of this lesson's model, stored as whole numbers. The G theory lesson set these rows aside; here we keep them out of every model of the teachers and use them three ways: to check the estimated leniency, to see whether adjusting brings teachers closer to the experts, and as the baseline for halo.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nurl <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_4:v7_0.teacherjudgements_lohmann_2026_essayratings/rows?format=csv\"\nes <- read.csv(url)[, c(\"id\", \"item\", \"rater\", \"resp\")]\ncrit <- c(\"language_quality\", \"structure\", \"content\", \"holistic\")\nbench <- es[es$rater == \"expert_benchmark\", ]\ntch <- es[es$rater != \"expert_benchmark\", ]\nc(benchmark_rows = nrow(bench), teacher_rows = nrow(tch),\n  teachers = length(unique(tch$rater)), essays = length(unique(bench$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbenchmark_rows   teacher_rows       teachers         essays \n          3524           6300            315            881 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The benchmark for the same essay and criterion, next to each teacher's rating\ntch$bench <- bench$resp[match(paste(tch$id, tch$item), paste(bench$id, bench$item))]\nround(c(teacher_minus_benchmark = mean(tch$resp - tch$bench)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nteacher_minus_benchmark \n                  -0.21 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(tapply(tch$resp - tch$bench, tch$item, mean)[crit], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlanguage_quality        structure          content         holistic \n            0.26            -1.34            -0.10             0.33 \n```\n\n\n:::\n:::\n\n\nTeachers' ratings average 0.21 points below the benchmark: 1.34 below on structure, within 0.33 elsewhere. Teachers and experts seem to have read the structure criterion differently, a question about the rubric these data raise and can't settle.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Teachers as random effects: each has a leniency, drawn from a common distribution.\nfit_es <- lmer(resp ~ item + (1 | id) + (1 | rater) + (1 | id:rater), data = tch)\nvc <- as.data.frame(VarCorr(fit_es))\nsetNames(round(vc$sdcor, 2), c(\"essay x teacher\", \"essay\", \"teacher\", \"residual\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nessay x teacher           essay         teacher        residual \n           0.75            0.90            0.51            0.94 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nlen <- setNames(ranef(fit_es)$rater[, 1], rownames(ranef(fit_es)$rater))\nround(quantile(len, c(0.1, 0.9)), 2)      # 10th and 90th percentiles of leniency\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  10%   90% \n-0.43  0.46 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# A direct estimate that uses the benchmark as the anchor: each teacher's mean\n# distance from it over their 20 ratings. The model never saw the benchmark.\ndirect <- tapply(tch$resp - tch$bench, tch$rater, mean)[names(len)]\nround(cor(len, direct), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9\n```\n\n\n:::\n:::\n\n\nWith teachers as random effects, the SD of leniency is 0.51 points, against 0.90 for essays (the G theory lesson had 0.50 and 0.87); the 10th and 90th percentiles are −0.43 and 0.46. Is that leniency real? The model never saw the benchmark, yet its estimates correlate 0.90 with each teacher's average distance from the benchmark over their 20 ratings.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\ntch$adjusted <- tch$resp - len[tch$rater]\nround(c(raw = cor(tch$resp, tch$bench), adjusted = cor(tch$adjusted, tch$bench)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     raw adjusted \n    0.40     0.44 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(raw = sqrt(mean((tch$resp - tch$bench)^2)),\n        adjusted = sqrt(mean((tch$adjusted - mean(len) - tch$bench)^2))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     raw adjusted \n    1.65     1.54 \n```\n\n\n:::\n:::\n\n\nSubtracting each teacher's leniency raises the correlation with the benchmark from 0.40 to 0.44 and lowers the root mean squared difference from 1.65 to 1.54 points: modest, because most of the disagreement is essay × teacher (SD 0.75), which no severity removes. That component was the G theory lesson's hint of halo, and the benchmark lets us test it.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"The average correlation among the four criteria can be computed within the teachers' ratings (across their essays) and within the benchmark's (on the same essays). Which is higher?\",\n  choices: [\"The teachers', clearly\", \"About the same\", \"The benchmark's, clearly\"],\n  answer: \"The teachers', clearly\",\n  reveal: \"The teachers' criteria correlate 0.66 on average, the benchmark's 0.43 on the same essays. Removing each teacher's own mean first barely changes this (0.64 against 0.44), so differences in leniency don't explain it. See the output below.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# One row per teacher x essay (four criteria), and the benchmark for the same essays\ntw <- reshape(tch[, c(\"id\", \"rater\", \"item\", \"resp\")], idvar = c(\"id\", \"rater\"),\n              timevar = \"item\", direction = \"wide\")\nnames(tw) <- sub(\"resp.\", \"\", names(tw), fixed = TRUE)\nbw <- reshape(bench[, c(\"id\", \"item\", \"resp\")], idvar = \"id\", timevar = \"item\", direction = \"wide\")\nnames(bw) <- sub(\"resp.\", \"\", names(bw), fixed = TRUE)\nbm <- bw[match(tw$id, bw$id), crit]\noff <- function(R) mean(R[lower.tri(R)])       # mean correlation between criteria\nround(cor(tw[, crit]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 language_quality structure content holistic\nlanguage_quality             1.00      0.44    0.60     0.81\nstructure                    0.44      1.00    0.56     0.70\ncontent                      0.60      0.56    1.00     0.83\nholistic                     0.81      0.70    0.83     1.00\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(cor(bm), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 language_quality structure content holistic\nlanguage_quality             1.00      0.16    0.36     0.72\nstructure                    0.16      1.00    0.50     0.27\ncontent                      0.36      0.50    1.00     0.59\nholistic                     0.72      0.27    0.59     1.00\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Remove each teacher's own mean first, so leniency can't create the correlation\nwithin <- function(x) sapply(crit, function(k) x[[k]] - ave(x[[k]], tw$rater))\nround(c(teachers = off(cor(tw[, crit])), benchmark = off(cor(bm)),\n        teachers_within = off(cor(within(tw))), benchmark_within = off(cor(within(bm)))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        teachers        benchmark  teachers_within benchmark_within \n            0.66             0.43             0.64             0.44 \n```\n\n\n:::\n:::\n\n\nThe teachers' criteria correlate 0.66 on average, the benchmark's 0.43 on the same essays, and the gap is largest where the benchmark treats criteria as most distinct (language quality and structure: 0.16 against 0.44). An average over trained raters keeps what an essay does to all four criteria and thins out one reader's impression, so this is the pattern halo would produce; [Lohmann et al. (2026)](https://doi.org/10.1037/edu0000969) study halo in these data. Centrality doesn't show:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Centrality: does a teacher spread their 20 ratings less than the benchmark does\n# on the same essays and criteria?\nsd_t <- tapply(tch$resp, tch$rater, sd); sd_b <- tapply(tch$bench, tch$rater, sd)\nc(narrower = sum(sd_t < sd_b), teachers = length(sd_t))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnarrower teachers \n     152      315 \n```\n\n\n:::\n:::\n\n\n152 of 315 teachers spread their ratings less than the benchmark does on the same essays, about half.\n\n## Problems\n\n1. **Derivation.** Under the many-facet Rasch model, show that the sum of a respondent's ratings is sufficient for $\\theta$ given the severities. Then show that two respondents with the same total, one rated by a harsh rater and one by a lenient one, get different estimates, and say which is higher.\n2. **Real data with a twist.** In the cleverness data, add a task × rater interaction (`formulaA = ~ item + rater + item:rater + step`). Is a harsh rater harsh on every task? What does the answer mean for adjusting scores?\n3. **Judgment.** An essay was scored by one teacher, whose estimated leniency is −0.6 points with a standard error of 0.25. Report the raw rating, the adjusted rating, or pay for a second rating? What would change your answer?\n4. **Design.** You must score 1,000 essays with 20 raters and two ratings per essay. Assign raters so every severity is estimable. How large a linkage set, containing what? Would an automated engine as the second rater help ([Casabianca et al., 2023](https://doi.org/10.1111/jedm.12360))? Check with the simulation.\n5. **Real data: who is lenient?** The essay table carries rater covariates (`ratercov_experience`, `ratercov_semester` and others). Add them to the `lmer` model: does leniency relate to them? Is the 1.34-point structure gap the same for every teacher?\n6. **Challenge (open).** Is the teachers' higher criterion correlation halo, or have experts trained on the rubric learned to separate criteria more than the essays warrant? What design would tell the two apart?\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Rater%20models%3A%20many-facet%20Rasch%20and%20beyond%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20rater%20models%3A%20the%20many-facet%20Rasch%20model%20%28rater%20severity%20as%20a%20facet%2C%20estimated%20with%20TAM%29%2C%20rater-specific%20steps%20for%20centrality%2C%20halo%20across%20rating%20criteria%2C%20the%20hierarchical%20rater%20model%20%28ideal%20ratings%20and%20a%20signal-detection%20rater%20layer%2C%20fitted%20with%20sirt%29%20and%20why%20it%20gives%20extra%20raters%20less%20credit%20than%20local%20independence%20does%2C%20rater%20drift%2C%20linkage%20sets%2C%20and%20raters%20as%20random%20effects%20in%20lme4%2C%20with%20cleverness%20ratings%20of%20alternate-uses%20responses%20and%20teachers%27%20ratings%20of%20essays%20checked%20against%20an%20expert%20benchmark.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Eckes, T. (2011). *Introduction to many-facet Rasch measurement*. Peter Lang. <https://doi.org/10.3726/978-3-653-04844-5>. A book-length introduction to the many-facet model for rater-mediated assessment.\n- Linacre, J. M. (1989). *Many-facet Rasch measurement*. MESA Press. <https://www.winsteps.com/a/Linacre-MFRM-book.pdf>. Where the model starts (the author's copy of the 1994 second edition).\n- Patz, R. J., Junker, B. W., Johnson, M. S., & Mariano, L. T. (2002). The hierarchical rater model for rated test items and its application to large-scale educational assessment data. *Journal of Educational and Behavioral Statistics*, 27(4), 341–384. <https://doi.org/10.3102/10769986027004341>. The hierarchical rater model, and how it relates to G theory and to the facets model.\n- Casabianca, J. M., Junker, B. W., & Patz, R. J. (2016). Hierarchical rater models. In W. J. van der Linden (Ed.), *Handbook of item response theory: Vol. 1. Models* (pp. 449–465). Chapman and Hall/CRC. <https://www.taylorfrancis.com/chapters/edit/10.1201/9781315374512-34/hierarchical-rater-models-jodi-casabianca-brian-junker-richard-patz>. A handbook chapter on the hierarchical rater model.\n- Casabianca, J. M. (2021). Digital module 27: Hierarchical rater models. *Educational Measurement: Issues and Practice*, 40(4), 103–104. <https://doi.org/10.1111/emip.12478>. An ITEMS module on the hierarchical rater model and its longitudinal and multidimensional extensions.\n- DeCarlo, L. T., Kim, Y., & Johnson, M. S. (2011). A hierarchical rater model for constructed responses, with a signal detection rater model. *Journal of Educational Measurement*, 48(3), 333–356. <https://doi.org/10.1111/j.1745-3984.2011.00143.x>. The signal-detection rater layer that `sirt::rm.sdt` fits.\n- Wilson, M., & Hoskens, M. (2001). The rater bundle model. *Journal of Educational and Behavioral Statistics*, 26(3), 283–306. <https://doi.org/10.3102/10769986026003283>. Another way to model the dependence among repeated ratings.\n- Uto, M., & Ueno, M. (2020). A generalized many-facet Rasch model and its Bayesian estimation using Hamiltonian Monte Carlo. *Behaviormetrika*, 47(2), 469–496. <https://doi.org/10.1007/s41237-020-00115-7>. Severity, consistency and range restriction in one model.\n- Myford, C. M., & Wolfe, E. W. (2009). Monitoring rater performance over time: A framework for detecting differential accuracy and differential scale category use. *Journal of Educational Measurement*, 46(4), 371–389. <https://doi.org/10.1111/j.1745-3984.2009.00088.x>. Drift in accuracy and in the use of the scale, with indices for monitoring it.\n- Casabianca, J. M., Lockwood, J. R., & McCaffrey, D. F. (2015). Trends in classroom observation scores. *Educational and Psychological Measurement*, 75(2), 311–337. <https://doi.org/10.1177/0013164414539163>. Rater drift over two years, in a G study with time trends.\n- Casabianca, J. M., Donoghue, J. R., Shin, H. J., Chao, S.-F., & Choi, I. (2023). Using linkage sets to improve connectedness in rater response model estimation. *Journal of Educational Measurement*, 60(3), 428–454. <https://doi.org/10.1111/jedm.12360>. How rating designs and linkage sets decide whether rater effects can be estimated.\n- Lewis, J., & Casabianca, J. M. (2026). Limitations of QWK in evaluating automated and human scoring systems. *Educational Measurement: Issues and Practice*, 45(1). <https://doi.org/10.1111/emip.70017>. How quadratic weighted kappa depends on the marginal distributions and the length of the scale.\n- McCaffrey, D. F., Casabianca, J. M., & Johnson, M. S. (2025). Measuring the accuracy of true score predictions for AI scoring evaluation. *Journal of Educational Measurement*, 62(4), 763–786. <https://doi.org/10.1111/jedm.70011>. Judging an automated scorer against human true scores rather than against observed human ratings.\n- Sudweeks, R. R., Reeve, S., & Bradshaw, W. S. (2004). A comparison of generalizability theory and many-facet Rasch measurement in an analysis of college sophomore writing. *Assessing Writing*, 9(3), 239–261. <https://doi.org/10.1016/j.asw.2004.11.001>. Both approaches on the same ratings.\n- Two IRW tables carry rating dates as well as raters, for anyone who wants to look for drift in real data: [moralvignettes_rakhmankulova_2025](https://itemresponsewarehouse.org/tables/moralvignettes_rakhmankulova_2025/) and [thomeczek2025_les](https://itemresponsewarehouse.org/tables/thomeczek2025_les/). Their raters rate vignettes and parties rather than respondents' work.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`Forthmann-2024-cleverness_ratings`](https://itemresponsewarehouse.org/tables/forthmann-2024-cleverness_ratings/): Forthmann, Boris, and Nils Myszkowski. 2024. “Analysis of a Divergent Thinking Dataset.” OSF. April 22. osf.io/a9qnc. <https://doi.org/No DOI>. Licence: CC BY 4.0.\n- [`teacherjudgements_lohmann_2026_essayratings`](https://itemresponsewarehouse.org/tables/teacherjudgements_lohmann_2026_essayratings/): Lohmann, J. F., Lötscher, F., Junge, F., Keller, S., Jansen, T., Fleckenstein, J., & Möller, J. (2026). Testing teacher judgments comprehensively: Accuracy, halo, frame of reference, strategy, and personality effects in holistic and analytic assessments of student essays.Journal of Educational Psychology, 118(6), 941–960. <https://doi.org/10.1037/edu0000969>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** new material, not in EDUC 252. Ben added the lesson on 09-25 while reviewing the G theory lesson, as the answer to its problem 6.\n- **Timing:** about 60 minutes for the core ideas and widgets; the real-data section works as a 30-minute lab (the hierarchical rater model takes one to two minutes in local R, so start it first).\n- **Software:** the many-facet model runs in the browser with `TAM`. The hierarchical rater model runs only in the downloadable code (`sirt::rm.sdt`), and the page shows its output from the render. A fixed-effects many-facet fit to the essay table's 315 teachers takes over a minute in local R; the lesson uses random effects in `lme4` there instead.\n- **Held back:** rater × criterion interactions (differential rater functioning) and rater-specific discrimination are in the problems and *Going further*; drift is shown by widget and cited, not fitted, since neither table has rating dates; automated scoring, and QWK against PRMSE for judging engines, are left to [AI and psychometrics](ai-psychometrics.qmd) and the readings.\n- **Solutions:** held back in `solutions/rater-models.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "rater-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}