{
  "hash": "e2ee47fb0cec43654ef75c05432d5ea8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Information, precision, and short forms\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Item response theory  \n**Tranche:** core (a first course)  \n**Before this:** [From the 1PL to the 4PL](1pl-to-4pl.qmd)  \n**Builds toward:** [Estimating abilities: MLE and EAP](ability-estimation.qmd) · [Item banks and adaptive testing](item-banks-cat.qmd) · [Models for polytomous responses](polytomous.qmd) · [What does a score mean? Norms, error bands, and cut scores](score-meaning.qmd)  \n**Picks up threads:** One standard error of measurement for everyone (from [Classical test theory and reliability](ctt-reliability.qmd)); What we want from a measure: insensitive to nonfocal attributes, calibrated, precise quickly (from [What is measurement?](measurement.qmd)); Under the 2PL the weighted score is sufficient (from [From the 1PL to the 4PL](1pl-to-4pl.qmd))  \n**IRW tables:** [`bialowolski_2024_financial_literacy`](https://itemresponsewarehouse.org/tables/bialowolski_2024_financial_literacy/), [`christensen_2018_wsssf_5831`](https://itemresponsewarehouse.org/tables/christensen_2018_wsssf_5831/)  \n**From EDUC 252:** slides c3, c4; problem sets PS3#1, PS4#1, PS6#3; code [`c4/info.R`](https://github.com/ben-domingue/252/blob/main/c4/info.R)  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n\n::: {.cell context='setup'}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| context: setup\n#| label: unnamed-chunk-2\noptions(mc.cores = 1)\n```\n:::\n\n\n```{ojs}\n//| echo: false\nimport {grid, dnorm, rng, normalQuantiles, p2pl, palette} from \"./widgets/irt.js\"\nimport {p4pl} from \"./widgets/1pl-to-4pl.js\"\nimport {itemInfo, testInfo, raschLoglik, raschMle, combinations, flItems} from \"./widgets/information.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\nHow precise is a score? Classical test theory gives one answer for everyone, yet a test measures well where its items are and poorly where they aren't, so a respondent in the middle of a well-built test and one far above it get very different precision from the same items. Item response models put this in numbers. The curvature of a respondent's likelihood becomes **information**, information adds up across items, and one over its square root is a standard error that changes along the scale. This lesson builds that machinery for the Rasch model, the 2PL and the 3PL, then uses it for two jobs: seeing where a real test is precise, and choosing a few items that are precise where a decision is made.\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- explain why the curvature of a respondent's log likelihood measures how precisely their $\\theta$ is estimated;\n- write down item information for the Rasch model, the 2PL and the 3PL, and say where each peaks and why;\n- add item information into test information and turn it into a conditional standard error of measurement;\n- read a test information curve against the distribution of respondents, and say for whom a test is precise;\n- build a short form targeted at a point on the scale, and say what it gives up elsewhere.\n\n## Core ideas\n\n### Information is the curvature of the likelihood\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The likelihood and logistic regression](likelihood.qmd): a sharper peak in the log likelihood means a more precise estimate. The negative of the second derivative at the peak is the **Fisher information**, and one over its square root is the standard error. Observations with a probability near 0 or 1 add almost nothing, because each contributes a term $p(1-p)$.\n:::\n\nNothing in that argument was specific to coins. Take one respondent, hold the item parameters fixed, and treat $\\theta$ as the unknown: the observations are that respondent's answers, and the log likelihood for $\\theta$ is a sum over items ([Birnbaum, 1968](https://openlibrary.org/works/OL6568286W); [Lord, 1980](https://doi.org/10.4324/9780203056615)). Its curvature says how sure we can be about this respondent's $\\theta$. The general formula for that curvature, the **information function**, is in the Go deeper callout below; the rest of the lesson uses its special cases, one model at a time. What makes it sharper: more items, or better-placed ones?\n\n::: {.callout-note collapse=\"true\"}\n## Go deeper: the information function in general\n\n**Assumptions:** one respondent answers $I$ dichotomous items; the item parameters are known; $P_i(\\theta) = \\Pr(x_i = 1 \\mid \\theta)$ is a smooth function of $\\theta$, with derivative $P_i'(\\theta)$; responses are locally independent given $\\theta$. No particular item model is assumed until the last step.\n\n**Definition.** The log likelihood for $\\theta$ is $\\ell(\\theta) = \\sum_i \\big[x_i \\log P_i + (1 - x_i)\\log(1 - P_i)\\big]$, a sum because local independence makes the probability of the pattern a product. Its derivative, the **score**, is\n$$\\frac{\\partial \\ell}{\\partial \\theta} = \\sum_i \\frac{P_i'\\,(x_i - P_i)}{P_i(1 - P_i)}.$$\nThe **Fisher information** for $\\theta$ is the expected negative second derivative of $\\ell$, which equals the variance of the score ([Fisher, 1925](https://doi.org/10.1017/S0305004100009580)):\n$$I(\\theta) = -\\,E\\!\\left[\\frac{\\partial^2 \\ell}{\\partial \\theta^2}\\right] = \\text{Var}\\!\\left[\\frac{\\partial \\ell}{\\partial \\theta}\\right].$$\n\n**One item.** Each term of the score has mean 0, and $x_i$ has variance $P_i(1 - P_i)$, so\n$$I_i(\\theta) = \\frac{P_i'(\\theta)^2}{P_i(\\theta)\\,\\big(1 - P_i(\\theta)\\big)}.$$\n**The test.** Under local independence the terms are independent, so their variances add: $I(\\theta) = \\sum_i I_i(\\theta)$ ([Birnbaum, 1968](https://openlibrary.org/works/OL6568286W); [Lord, 1980](https://doi.org/10.4324/9780203056615)). If two items share something beyond $\\theta$ (a reading passage, say), their terms are positively correlated and the sum overstates what the pair tells us ([Sireci, Thissen & Wainer, 1991](https://doi.org/10.1111/j.1745-3984.1991.tb00356.x), show the same problem in reliability).\n\n**The special cases.** Only $P_i'$ changes from model to model.\n\n- Rasch: $P' = P(1 - P)$, so $I_i = P(1-P)$, a Bernoulli variance, at most $1/4$, at $\\theta = b$.\n- 2PL: $P' = aP(1 - P)$, so $I_i = a^2P(1-P)$. The score is $\\sum_i a_i(x_i - P_i)$, the weighted score minus its expectation, and its second derivative contains no $x_i$, so the observed curvature equals the expected information: a test has one information curve, drawn before anyone takes it.\n- 3PL: $P = c + (1 - c)L$ with $L = \\text{logit}^{-1}(a(\\theta - b))$, so $P' = a(P - c)(1 - P)/(1 - c)$ and $I_i = a^2\\frac{(P - c)^2}{(1 - c)^2}\\frac{1 - P}{P}$. Here the observed curvature depends on the responses, and this is the expected information.\n\nThe standard error $1/\\sqrt{I(\\theta)}$ is a large-sample approximation, as it was for the coin; with few items, or near the ends of the scale, it can mislead, and the simulation below shows where.\n:::\n\n#### Try it: one respondent's likelihood\n\nA respondent with true ability $\\theta$ answers Rasch items whose difficulties are spread (SD 1) around a centre you choose. The curve is the log likelihood for $\\theta$, shifted so its peak sits at 0.\n\n```{ojs}\n//| echo: false\nviewof rl_n = Inputs.range([3, 60], {value: 10, step: 1, label: \"Number of items\"})\nviewof rl_center = Inputs.range([-3, 3], {value: 0, step: 0.1, label: \"Where the items sit (mean b)\"})\nviewof rl_theta = Inputs.range([-3, 3], {value: 0.5, step: 0.1, label: \"Respondent's true θ\"})\n```\n\n```{ojs}\n//| echo: false\nrl_u = { const r = rng(36); return Array.from({length: 60}, () => r.unif()); }\nrl_b = normalQuantiles(rl_n, rl_center, 1)\nrl_x = rl_b.map((b, i) => rl_u[i] < p2pl(rl_theta, b) ? 1 : 0)\nrl_r = rl_x.reduce((s, v) => s + v, 0)\nrl_mle = raschMle(rl_x, rl_b)\nrl_top = Number.isFinite(rl_mle) ? raschLoglik(rl_mle, rl_x, rl_b) : Math.max(...grid(-5, 5, 201).map(t => raschLoglik(t, rl_x, rl_b)))\nrl_curve = grid(-5, 5, 401).map(t => ({theta: t, ll: raschLoglik(t, rl_x, rl_b) - rl_top})).filter(d => d.ll > -6)\nrl_info = Number.isFinite(rl_mle) ? testInfo(rl_mle, rl_b.map(b => ({b}))) : NaN\nPlot.plot({\n  width: 700, height: 280, x: {label: \"Candidate θ\", domain: [-5, 5]}, y: {label: \"Log likelihood (peak at 0)\", domain: [-6, 0.3]},\n  marks: [\n    Plot.ruleY([-0.5], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n    Plot.ruleX([rl_theta], {stroke: palette.rule}),\n    Plot.ruleX(rl_b, {x: d => d, y1: -6, y2: -5.6, stroke: palette.contrast}),\n    Plot.line(rl_curve, {x: \"theta\", y: \"ll\", stroke: palette.main, strokeWidth: 2.5}),\n    ...(Number.isFinite(rl_mle) ? [Plot.dot([{theta: rl_mle, ll: 0}], {x: \"theta\", y: \"ll\", r: 5, fill: palette.main})] : [])\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`${rl_r} of ${rl_n} correct. ${Number.isFinite(rl_mle) ?\n  `The maximum-likelihood estimate is **${rl_mle.toFixed(2)}** (true θ ${rl_theta.toFixed(1)}, grey line). The information there is ${rl_info.toFixed(2)}, so the standard error is 1 / √${rl_info.toFixed(2)} = **${(1 / Math.sqrt(rl_info)).toFixed(2)}**. The curve falls by one half (dashed line) about one standard error either side of the peak.` :\n  `With ${rl_r === 0 ? \"no item right\" : \"every item right\"}, the likelihood keeps rising toward ${rl_r === 0 ? \"−∞\" : \"+∞\"}: there is no finite maximum, and no standard error.`} Item difficulties are the ticks along the bottom.`\n```\n\nAt the defaults this respondent gets 3 of 10 right, and the estimate, −1.01, lands two standard errors (0.75 each) below the true 0.5. With 40 items the curve narrows: the estimate is 0.49 and the standard error 0.35, about half, as four times the items should give. Put 10 items far above the respondent (mean $b$ = 3) and nothing is right: the curve never turns over, which is a problem for [Estimating abilities](ability-estimation.qmd).\n\n### Item information for the Rasch model, the 2PL and the 3PL\n\nEach item adds one term to the curvature. Under the Rasch model that term is\n$$I_i(\\theta) = P_i(\\theta)\\,\\big(1 - P_i(\\theta)\\big),$$\nthe variance of a single 0/1 response. It is largest, 1/4, where $P_i = 1/2$, which under the Rasch model is at $\\theta = b_i$, and it fades on either side: a respondent far above or below an item almost always gives the answer we'd have predicted, and a predictable answer carries little news. The Go deeper callout above gives the general formula it comes from.\n\nThe 2PL multiplies it by the squared slope,\n$$I_i(\\theta) = a_i^2\\,P_i(\\theta)\\,\\big(1 - P_i(\\theta)\\big),$$\nso an item with $a = 2$ carries four times the information of a Rasch item at its peak, over a narrower band.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [From the 1PL to the 4PL](1pl-to-4pl.qmd): under the 2PL the weighted score $\\sum_i a_i x_i$ is sufficient for $\\theta$, so a correct answer counts in proportion to its item's slope. The score equation was $\\partial\\ell/\\partial\\theta = \\sum_i a_i (x_i - P_i)$.\n:::\n\nInformation is where that weighting shows up in precision. Each term of the score equation is $a_i$ times a Bernoulli residual, so its variance is $a_i^2 P_i(1-P_i)$: the item's weight, squared, times the Bernoulli variance. Items that count for more in the score also tell us more about $\\theta$, and an item with a slope near zero tells us almost nothing wherever it sits.\n\nThe 3PL adds a lower asymptote $c$, and the information (the expected information; see the callout above) becomes\n$$I_i(\\theta) = a_i^2\\,\\frac{\\big(P_i - c_i\\big)^2}{(1 - c_i)^2}\\,\\frac{1 - P_i}{P_i}.$$\nWith $c > 0$ it falls, most of all below the item's difficulty, where a correct answer may be a guess and so says less about $\\theta$; the peak moves above $b$ (problem 1 finds by how much). What fixing $c$ or giving it a prior does to information at the bottom of the scale is for [Guessing and priors](guessing-priors.qmd).\n\n#### Try it: an item's information curve\n\n```{ojs}\n//| echo: false\nviewof ii_b = Inputs.range([-3, 3], {value: 0, step: 0.1, label: \"Difficulty b\"})\nviewof ii_a = Inputs.range([0.2, 3], {value: 1, step: 0.05, label: \"Slope a\"})\nviewof ii_c = Inputs.range([0, 0.4], {value: 0, step: 0.01, label: \"Lower asymptote c\"})\n```\n\n```{ojs}\n//| echo: false\nii_th = grid(-4, 4, 401)\nii_curve = ii_th.map(t => ({theta: t, p: p4pl(t, ii_b, ii_a, ii_c), info: itemInfo(t, ii_b, ii_a, ii_c), rasch: itemInfo(t, ii_b)}))\nii_peak = ii_curve.reduce((m, d) => d.info > m.info ? d : m)\nPlot.plot({\n  width: 700, height: 190, x: {label: null, domain: [-4, 4]}, y: {label: \"P(correct)\", domain: [0, 1]},\n  marks: [\n    Plot.ruleX([ii_b], {stroke: palette.rule}),\n    Plot.line(ii_curve, {x: \"theta\", y: \"p\", stroke: palette.main, strokeWidth: 2.5})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nPlot.plot({\n  width: 700, height: 240, x: {label: \"Ability θ\", domain: [-4, 4]}, y: {label: \"Item information\", domain: [0, Math.max(0.3, ii_peak.info * 1.1)]},\n  color: {legend: true, domain: [\"This item\", \"Rasch item with the same b\"], range: [palette.main, palette.light]},\n  marks: [\n    Plot.ruleX([ii_b], {stroke: palette.rule}),\n    Plot.line(ii_curve, {x: \"theta\", y: \"rasch\", stroke: () => \"Rasch item with the same b\", strokeWidth: 2, strokeDasharray: \"5,3\"}),\n    Plot.line(ii_curve, {x: \"theta\", y: \"info\", stroke: () => \"This item\", strokeWidth: 2.5}),\n    Plot.dot([ii_peak], {x: \"theta\", y: \"info\", r: 5, fill: palette.contrast})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Information peaks at θ = **${ii_peak.theta.toFixed(2)}** (b = ${ii_b.toFixed(1)}), at a height of **${ii_peak.info.toFixed(3)}**. A Rasch item peaks at its difficulty, at 0.25.`\n```\n\nRaise the slope to 2 and the peak rises to 1.000, four times the Rasch item's, over a narrower range; at 0.5 it falls to 0.063. With $a = 1$ and $c = 0.25$ the peak drops to 0.155 and moves up to 0.31, and the left side sinks further than the right.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A 2PL item has $a = 2$ and $b = 1$. Where is its information largest, and how large is it?\",\n  options: [\n    {text: \"At $\\\\theta = 1$, where it is 1\", correct: true, why: \"A 2PL item's information $a^2P(1-P)$ peaks where $P = 1/2$, at $\\\\theta = b = 1$, and there it is $a^2/4 = 4/4 = 1$.\"},\n    {text: \"At $\\\\theta = 1$, where it is 0.25\", correct: false, why: \"0.25 is the Rasch item's peak. The slope enters squared, so $a = 2$ multiplies it by 4.\"},\n    {text: \"At $\\\\theta = 1$, where it is 0.5\", correct: false, why: \"That would be $a/4$. Information goes with $a^2$, as the weight in the score equation does when you take its variance.\"},\n    {text: \"Above $\\\\theta = 1$, because steep items favour stronger respondents\", correct: false, why: \"Without a lower asymptote the curve is symmetric about $b$, and so is its information. It is $c > 0$ that moves the peak above $b$.\"}\n  ]\n})\n```\n\n### Information adds; precision follows\n\nLocal independence lets item information add: the **test information** is\n$$I(\\theta) = \\sum_i I_i(\\theta),$$\nand the **conditional standard error of measurement** (CSEM) at $\\theta$ is\n$$SE(\\theta) = \\frac{1}{\\sqrt{I(\\theta)}}.$$\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Classical test theory and reliability](ctt-reliability.qmd): the standard error of measurement, $\\sigma_E = \\sigma_X\\sqrt{1 - \\rho_{XX'}}$, is the typical distance between a respondent's observed and true scores, and CTT gives the same one to everyone, whatever their score.\n:::\n\nThe CSEM replaces that one number with a curve, low where many informative items sit and rising where they run out, which need not be at the extremes of the respondents. [Samejima (1977)](https://doi.org/10.1177/014662167700100209) argued for this standard error, rather than reliability, as the index of how dependable a score is, and [Kolen, Zeng and Hanson (1996)](https://doi.org/10.1111/j.1745-3984.1996.tb00485.x) carry it to a reported score scale. The standard error of one respondent's estimate evaluates the CSEM at their $\\hat\\theta$: [Estimating abilities](ability-estimation.qmd) picks up there.\n\n#### Try it: build a test\n\nChoose how many items, where they sit and how steep they are. The curve is the CSEM; the shading is where respondents are (a standard normal). The dashed line is the one SEM this test would get if its error variance were averaged over those respondents, CTT style.\n\n```{ojs}\n//| echo: false\nviewof bt_n = Inputs.range([5, 80], {value: 20, step: 1, label: \"Number of items\"})\nviewof bt_mean = Inputs.range([-2, 2], {value: 0, step: 0.1, label: \"Mean difficulty\"})\nviewof bt_sd = Inputs.range([0, 2], {value: 1, step: 0.1, label: \"Spread of difficulties (SD)\"})\nviewof bt_a = Inputs.range([0.5, 2.5], {value: 1, step: 0.1, label: \"Slope a (every item)\"})\n```\n\n```{ojs}\n//| echo: false\nbt_items = normalQuantiles(bt_n, bt_mean, bt_sd).map(b => ({b, a: bt_a}))\nbt_th = grid(-4, 4, 401)\nbt_se = bt_th.map(t => ({theta: t, se: 1 / Math.sqrt(testInfo(t, bt_items))}))\nbt_w = bt_th.map(t => dnorm(t))\nbt_one = Math.sqrt(bt_th.reduce((s, t, k) => s + bt_w[k] / testInfo(t, bt_items), 0) / bt_w.reduce((s, v) => s + v, 0))\nPlot.plot({\n  width: 700, height: 300, x: {label: \"Ability θ\", domain: [-4, 4]}, y: {label: \"Conditional SEM\", domain: [0, 2]},\n  marks: [\n    Plot.areaY(bt_th.map((t, k) => ({theta: t, d: bt_w[k] / dnorm(0) * 1.2})), {x: \"theta\", y: \"d\", fill: palette.light, fillOpacity: 0.5}),\n    Plot.ruleY([bt_one], {stroke: palette.guide, strokeDasharray: \"5,3\"}),\n    Plot.ruleX(bt_items, {x: \"b\", y1: 0, y2: 0.08, stroke: palette.contrast}),\n    Plot.line(bt_se.filter(d => d.se <= 2), {x: \"theta\", y: \"se\", stroke: palette.main, strokeWidth: 2.5})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`CSEM at θ = −2: **${(1 / Math.sqrt(testInfo(-2, bt_items))).toFixed(2)}**; at θ = 0: **${(1 / Math.sqrt(testInfo(0, bt_items))).toFixed(2)}**; at θ = 2: **${(1 / Math.sqrt(testInfo(2, bt_items))).toFixed(2)}**. One SEM for everyone: ${bt_one.toFixed(2)}. Item difficulties are the ticks along the bottom.`\n```\n\nAt the defaults the CSEM is 0.49 at the centre and 0.66 two SDs out, so the one SEM, 0.53, is too large for the middle and too small at the edges. Forty items shrink every CSEM by $\\sqrt 2$ (0.49 becomes 0.35); doubling the slope instead takes the centre to 0.29. Move the mean difficulty to 1.5 with a spread of 0.3, and the CSEM is 0.47 at $\\theta = 2$ and 1.30 at $\\theta = -2$: the test now measures well where few respondents are.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A test has information 16 at $\\\\theta = 0$. What is its conditional SEM there, and what would it be if you added a second, identical set of items?\",\n  options: [\n    {text: \"0.25, then about 0.18\", correct: true, why: \"$1/\\\\sqrt{16} = 0.25$. Doubling the items doubles the information to 32, and $1/\\\\sqrt{32} \\\\approx 0.18$: precision improves with the square root.\"},\n    {text: \"0.25, then 0.125\", correct: false, why: \"Doubling the items doubles the information, not its square root. The SEM falls by $\\\\sqrt 2$, not by 2.\"},\n    {text: \"0.0625, then about 0.031\", correct: false, why: \"That is $1/16$ and $1/32$: the error *variance*. The SEM is its square root.\"}\n  ]\n})\n```\n\n### Targeting: a test is precise where its items are\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [The Rasch model](rasch.qmd): a Wright map puts respondents and item difficulties on one scale. Where they overlap, the test can tell people apart; where respondents sit beyond every item, it can't. That lesson handed the idea on by name: precision depends on where you are on the scale.\n:::\n\nThe test information curve is the Wright map with error bars. Read against the distribution of respondents, it says for whom a test is precise, and the design question turns around: given the respondents we care about, where should the items go? [Lord (1977)](https://doi.org/10.1111/j.1745-3984.1977.tb00032.x) set out test construction this way: specify the information you need along the scale (a *target information function*), then add items until their sum reaches it. A test that must rank everyone wants its items spread across the population; a test that makes one pass/fail decision wants them bunched at the cut. What a CSEM means for a reported score, and for respondents near a cut score where information is low, is the subject of [What does a score mean?](score-meaning.qmd).\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A certification exam passes respondents above $\\\\theta = 1.5$. With 20 Rasch items to spend, which test classifies respondents near the cut most precisely?\",\n  options: [\n    {text: \"All 20 items with difficulties near 1.5\", correct: true, why: \"Each Rasch item's information peaks at its difficulty, so stacking the items at the cut gives the most information there. Try it in the widget above: mean difficulty 1.5, spread near 0.\"},\n    {text: \"20 items spread evenly from −2 to 2\", correct: false, why: \"That test measures everyone moderately well, which is what you want for ranking the whole population, but it spends most of its items where no decision is made.\"},\n    {text: \"20 items centred on the mean respondent, θ = 0\", correct: false, why: \"They are informative for respondents near 0, who are far below the cut and pass or fail without much doubt either way.\"}\n  ]\n})\n```\n\n### Short forms\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is measurement?](measurement.qmd): among the things we want from a measure are that it be calibrated to its task, sometimes covering a wide range and sometimes making fine distinctions near one point, and that it give precise information quickly, with few items.\n:::\n\nInformation turns \"precise quickly\" into something we can compute. If a respondent will answer only five items, which five? Information at a target $\\theta$ is a sum over the chosen items, so the best five are the five most informative there, and they may be poor elsewhere. Other costs don't show in the information curve: a short form covers less of the construct's content, and its validity has to be checked on its own ([Smith, McCarthy & Anderson, 2000](https://doi.org/10.1037/1040-3590.12.1.102)). Choosing items one at a time, each the most informative at the current estimate, is adaptive testing: [Item banks and adaptive testing](item-banks-cat.qmd).\n\n#### Try it: pick a five-item form\n\nHere are the 18 items of the financial-literacy test analysed below, with their 2PL slopes and difficulties. Pick five and a target $\\theta$.\n\n```{ojs}\n//| echo: false\nsf_labels = flItems.map(d => `${d.item} (a = ${d.a.toFixed(2)}, b = ${d.b.toFixed(2)})`.replaceAll(\"-\", \"−\"))\nviewof sf_pick = Inputs.checkbox(sf_labels, {label: \"Your form\", value: sf_labels.slice(0, 5)})\nviewof sf_target = Inputs.range([-3, 3], {value: -1, step: 0.1, label: \"Target θ\"})\n```\n\n```{ojs}\n//| echo: false\nsf_sel = flItems.filter((d, i) => sf_pick.includes(sf_labels[i]))\nsf_all5 = combinations(18, 5)\nsf_infoT = flItems.map(d => itemInfo(sf_target, d.b, d.a))\nsf_sums = sf_all5.map(k => k.reduce((s, i) => s + sf_infoT[i], 0)).sort((x, y) => x - y)\nsf_best = sf_infoT.map((v, i) => ({v, i})).sort((x, y) => y.v - x.v).slice(0, 5)\nsf_mine = testInfo(sf_target, sf_sel)\nsf_th = grid(-4, 4, 321)\nPlot.plot({\n  width: 700, height: 280, x: {label: \"Financial literacy θ\", domain: [-4, 4]}, y: {label: \"Test information\"},\n  color: {legend: true, domain: [\"All 18 items\", \"Your form\", \"Best five for the target\"], range: [palette.light, palette.main, palette.contrast]},\n  marks: [\n    Plot.ruleX([sf_target], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n    Plot.line(sf_th.flatMap(t => [\n      {theta: t, I: testInfo(t, flItems), form: \"All 18 items\"},\n      {theta: t, I: testInfo(t, sf_sel), form: \"Your form\"},\n      {theta: t, I: testInfo(t, sf_best.map(d => flItems[d.i])), form: \"Best five for the target\"}]),\n      {x: \"theta\", y: \"I\", stroke: \"form\", strokeWidth: 2.5})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`${sf_sel.length === 5 ? \"\" : `*You have picked ${sf_sel.length} items; the comparison is with five-item forms.* `}At θ = ${sf_target.toFixed(1)}, your form gives information **${sf_mine.toFixed(2)}** (CSEM ${(1 / Math.sqrt(sf_mine)).toFixed(2)}), more than ${(100 * sf_sums.filter(v => v < sf_mine).length / sf_sums.length).toFixed(0)}% of all ${sf_sums.length.toLocaleString()} five-item forms. The median form gives ${sf_sums[Math.floor(sf_sums.length / 2)].toFixed(2)}; the best five (${sf_best.map(d => flItems[d.i].item).join(\", \")}) give **${sf_best.reduce((s, d) => s + d.v, 0).toFixed(2)}** (CSEM ${(1 / Math.sqrt(sf_best.reduce((s, d) => s + d.v, 0))).toFixed(2)}); all 18 items give ${testInfo(sf_target, flItems).toFixed(2)}.`\n```\n\nThe default form (the first five items) gives 1.72 at $\\theta = -1$, more than 35% of the possible forms. The best five give 4.18, more than half the full test's 7.25. Move the target to 1.5 and the best five change completely (to FL_10, FL_5, FL_4, FL_17 and FL_11), while the whole test reaches only 1.55: there aren't enough hard items to make this test precise for its strongest respondents.\n\n## Simulate\n\nDoes $1/\\sqrt{I(\\theta)}$ describe how far estimates actually fall from the truth? The code below simulates Rasch responses from 4,000 respondents spread evenly from $\\theta = -3$ to 3, estimates each $\\theta$ by maximum likelihood with the difficulties treated as known, and compares the SD of $\\hat\\theta - \\theta$ within bins of true $\\theta$ with the CSEM. It is base R and runs in a second or two.\n\nWith the seed as written (20 items from $b = -2$ to 2), the two agree closely across the middle: 0.53 and 0.52 near $\\theta = 0$, and 0.56 and 0.56 at $\\theta = 1.25$. At the ends they part. In the bins at $\\pm 2.75$, 34 and 38 respondents answered every item wrong or every item right and have no estimate at all, and the rest scatter *less* than the CSEM says (0.66 and 0.64 against 0.79): the respondents who would have had the largest errors are the ones who drop out. Change `b` to `rep(1, 20)`, all items at one difficulty. Now 202 respondents in the lowest bin have no estimate, and the CSEM there, 1.49, is more than three times the scatter of the rest (0.42). Then try five items, `seq(-2, 2, length.out = 5)`. The formula is a large-sample result; with few items it is a rough guide, and what to do about respondents with no finite estimate is for [Estimating abilities](ability-estimation.qmd).\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-20\n# Does 1/sqrt(I(theta)) describe how far ability estimates really fall from the truth?\n# Simulate Rasch responses from a test with a chosen difficulty profile, estimate each\n# respondent's theta by maximum likelihood (item difficulties treated as known), and\n# compare the spread of the errors within bins of true theta with the conditional SEM.\n# Base R only; runs in a second or two.\nset.seed(36)\nnp <- 4000                        # respondents\nb  <- seq(-2, 2, length.out = 20) # item difficulties: try rep(1, 20), or seq(-2, 2, length.out = 5)\nth <- runif(np, -3, 3)            # true abilities, spread evenly so every bin has respondents\n\np    <- plogis(outer(th, b, \"-\"))\nresp <- matrix(rbinom(length(p), 1, p), np, length(b))\nr    <- rowSums(resp)\n\n# Test information under the Rasch model: the sum over items of p(1 - p).\ninfo <- function(t) sapply(t, function(x) sum(plogis(x - b) * (1 - plogis(x - b))))\n\n# Maximum-likelihood theta for one respondent. The Rasch score equation says the\n# expected sum score equals the observed one; solve it. A respondent with every item\n# right (or wrong) has no finite estimate: we set those aside and count them.\nml <- function(score) uniroot(function(t) sum(plogis(t - b)) - score, c(-10, 10))$root\nfinite <- r > 0 & r < length(b)\nth_hat <- rep(NA, np)\nth_hat[finite] <- sapply(r[finite], ml)\n\nbins <- cut(th, seq(-3, 3, by = 0.5))\nmid  <- seq(-2.75, 2.75, by = 0.5)\nout <- data.frame(\n  theta = mid,\n  n_no_estimate = as.vector(tapply(!finite, bins, sum)),\n  empirical_sd  = round(as.vector(tapply(th_hat - th, bins, sd, na.rm = TRUE)), 2),\n  csem          = round(1 / sqrt(info(mid)), 2))\nprint(out, row.names = FALSE)\n\nplot(mid, out$csem, type = \"l\", lwd = 2, col = \"#2780e3\", ylim = c(0, 1.5),\n     xlab = \"True ability theta (bin midpoint)\", ylab = \"Standard error\",\n     main = paste(length(b), \"items\"))\npoints(mid, out$empirical_sd, pch = 19, col = \"#c2410c\")\nlegend(\"top\", c(\"1 / sqrt(I(theta))\", \"SD of estimate - truth\"), lwd = c(2, NA),\n       pch = c(NA, 19), col = c(\"#2780e3\", \"#c2410c\"), bty = \"n\")\n\n```\n:::\n\n\n[Download this code](code/information-sim.R) to run it in your own R session.\n\n## With real data\n\n\n\n### A financial-literacy test\n\nOur main example is [bialowolski_2024_financial_literacy](https://itemresponsewarehouse.org/tables/bialowolski_2024_financial_literacy/): 18 questions answered by 4,389 Polish adults ([Bialowolski, 2024](https://doi.org/10.7910/DVN/MTQGSF)), about inflation, bonds, diversification, loan interest and the like. Its job is to be a test aimed near the middle of its population. A response is 1 for a correct answer and 0 otherwise, including \"don't know\", which every question offered (the deposit's supplementary appendix lists the questions). Each question came in one of three wordings that differed in grammatical gender; the IRW table pools them, and so do we. [Lusardi and Mitchell (2014)](https://doi.org/10.1257/jel.52.1.5) review research on financial literacy. [Download the code](code/information-irw.R) to run every chunk yourself; it needs `mirt` ([Chalmers, 2012](https://doi.org/10.18637/jss.v048.i06)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(mirt)\n# Each IRW table has a landing page (itemresponsewarehouse.org/tables/<name>/) with a\n# CSV download. This link is pinned to one version of the data.\nfl_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_4:v7_0.bialowolski_2024_financial_literacy/rows?format=csv\"\ndf <- read.csv(fl_url)\n# resp is 1 for a correct answer and 0 otherwise (\"don't know\" included). Every\n# respondent answered every item once; there are no waves.\nlong2wide <- function(df) {\n  wide <- tapply(df$resp, list(df$id, df$item), function(x) x[1])\n  as.data.frame(wide[, order(as.numeric(gsub(\"\\\\D\", \"\", colnames(wide))))])\n}\nfl <- long2wide(df)\nc(respondents = nrow(fl), items = ncol(fl), complete = sum(complete.cases(fl)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents       items    complete \n       4389          18        4389 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(range(colMeans(fl)), 2)   # proportion correct: the hardest and easiest items\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.17 0.96\n```\n\n\n:::\n:::\n\n\nEvery respondent answered every item. The items run from hard (17% correct) to very easy (96%).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Rasch and 2PL. mirt writes the 2PL as a*theta + d; our difficulty is b = -d/a.\nfl_r <- mirt(fl, 1, itemtype = \"Rasch\", verbose = FALSE)\nfl_2 <- mirt(fl, 1, itemtype = \"2PL\", verbose = FALSE)\nc(BIC_Rasch = round(extract.mirt(fl_r, \"BIC\")), BIC_2PL = round(extract.mirt(fl_2, \"BIC\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBIC_Rasch   BIC_2PL \n    81439     80012 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ncf <- coef(fl_2, simplify = TRUE)$items\npars <- data.frame(a = cf[, \"a1\"], b = -cf[, \"d\"] / cf[, \"a1\"])\npars$info_at_peak <- pars$a^2 / 4   # a 2PL item's information at theta = b\nround(pars[order(pars$b), ], 2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |    a|     b| info_at_peak|\n|:-----|----:|-----:|------------:|\n|FL_16 | 1.17| -3.18|         0.34|\n|FL_13 | 1.52| -1.48|         0.58|\n|FL_7  | 1.20| -1.23|         0.36|\n|FL_19 | 1.37| -1.14|         0.47|\n|FL_12 | 2.06| -1.08|         1.06|\n|FL_1  | 2.17| -1.01|         1.18|\n|FL_8  | 1.10| -0.89|         0.30|\n|FL_6  | 1.67| -0.65|         0.70|\n|FL_14 | 1.93| -0.58|         0.93|\n|FL_15 | 1.16| -0.43|         0.33|\n|FL_17 | 1.58| -0.21|         0.63|\n|FL_11 | 1.84| -0.19|         0.84|\n|FL_5  | 1.41|  0.04|         0.50|\n|FL_4  | 1.06|  0.33|         0.28|\n|FL_9  | 0.36|  0.45|         0.03|\n|FL_3  | 0.72|  1.64|         0.13|\n|FL_10 | 0.92|  1.88|         0.21|\n|FL_2  | 0.14| 11.52|         0.00|\n\n</div>\n:::\n:::\n\n\nBIC prefers the 2PL (80,012 against 81,439), and we use it from here on. Most slopes are between 1 and 2.2 and most difficulties below 0. Two items have slopes far below the rest: FL_9 (0.36) and FL_2 (0.14, whose difficulty of 11.52 comes from dividing by a slope near zero, as chess problem Y15's did in [From the 1PL to the 4PL](1pl-to-4pl.qmd)). The last column is each item's information at its peak, $a^2/4$: 1.18 for FL_1, 0.00 for FL_2.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Test information is the sum of the item informations; the conditional SEM is one\n# over its square root. testinfo() and iteminfo() do the sums.\ntheta <- seq(-4, 4, by = 0.01)\nI_fl <- testinfo(fl_2, matrix(theta))\nat <- c(-2, -1, 0, 1, 2)\ndata.frame(theta = at, information = round(I_fl[match(at, theta)], 2),\n           csem = round(1 / sqrt(I_fl[match(at, theta)]), 2))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| theta| information| csem|\n|-----:|-----------:|----:|\n|    -2|        3.61| 0.53|\n|    -1|        7.25| 0.37|\n|     0|        5.73| 0.42|\n|     1|        2.47| 0.64|\n|     2|        1.01| 1.00|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(peak_at = theta[which.max(I_fl)], peak_information = round(max(I_fl), 2),\n  csem_at_peak = round(1 / sqrt(max(I_fl)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         peak_at peak_information     csem_at_peak \n           -0.77             7.45             0.37 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The two flattest items, and what they add to the test information at its peak.\nflat <- rownames(pars)[order(pars$a)[1:2]]\nround(sapply(flat, function(i) iteminfo(extract.item(fl_2, i), theta[which.max(I_fl)])), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n FL_2  FL_9 \n0.003 0.031 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Information adds: the item informations at theta = 0 sum to the test information there.\nall.equal(sum(sapply(colnames(fl), function(i) iteminfo(extract.item(fl_2, i), 0))),\n          testinfo(fl_2, matrix(0)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nThe test information peaks at 7.45 near $\\theta = -0.77$, where the CSEM is 0.37, and falls to 1.01 at $\\theta = 2$ (CSEM 1.00). The two flat items add 0.003 and 0.031 to the peak, under half a percent between them. The item informations sum to the test information exactly (`all.equal` returns `TRUE`).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The single-number summary: mirt's marginal reliability of the ability estimates,\n# and the one SEM it implies on a scale whose ability SD is 1.\neap <- fscores(fl_2, full.scores.SE = TRUE)\nrel <- empirical_rxx(eap)\nc(reliability = round(unname(rel), 2), one_sem = round(sqrt(1 - unname(rel)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nreliability     one_sem \n       0.81        0.44 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# The conditional SEM at the 2.5th and 97.5th percentiles of the respondents' estimates.\nq <- quantile(eap[, \"F1\"], c(0.025, 0.975))\nround(c(q, csem = 1 / sqrt(testinfo(fl_2, matrix(q)))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5% 97.5% csem1 csem2 \n-1.88  1.52  0.50  0.81 \n```\n\n\n:::\n:::\n\n\nSummarised as one number, this test's reliability is 0.81, which on a $\\theta$ scale with SD 1 implies one SEM of 0.44 for everyone. The curve says otherwise: 0.50 at the 2.5th percentile of respondents, 0.81 at the 97.5th, and 0.37 at its best. The single number averages over a curve that varies by more than a factor of two across these respondents.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nop <- par(mar = c(4, 4, 1, 4))\nhist(eap[, \"F1\"], breaks = seq(-4, 4, 0.25), col = \"#93c5fd\", border = \"white\",\n     main = \"\", xlab = \"Financial literacy (theta)\", ylab = \"Respondents\")\npar(new = TRUE)\nplot(theta, 1 / sqrt(I_fl), type = \"l\", lwd = 2.5, col = \"#c2410c\", ylim = c(0, 2),\n     axes = FALSE, xlab = \"\", ylab = \"\")\naxis(4, col.axis = \"#c2410c\"); mtext(\"Conditional SEM\", side = 4, line = 2.5, col = \"#c2410c\")\n```\n\n::: {.cell-output-display}\n![](information_files/figure-html/plot-fl-1.png){width=576}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npar(op)\n```\n:::\n\n\nThis is the Wright map with error bars that the Rasch lesson promised: the respondents' estimates (bars) with the CSEM (line) laid over them. The CSEM is lowest just below the middle of the respondents and rises faster to the right, because the test has few hard items: only three difficulties are above 0.5.\n\n### A short form for decisions near $\\theta = -1$\n\nSuppose the test were used to decide who is offered a financial-education course, with the decision made at about $\\theta = -1$ (14% of these respondents have estimates below it). Five items, chosen for that point:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# A five-item short form for decisions made near theta = -1: take the five items\n# with the most information there. Compare it with the full test and with every\n# possible five-item form (choose(18, 5) = 8,568 of them).\ntarget <- -1\nc(share_of_respondents_below_target = round(mean(eap[, \"F1\"] < target), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nshare_of_respondents_below_target \n                             0.14 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nitem_info <- function(t) sapply(colnames(fl), function(i) iteminfo(extract.item(fl_2, i), t))\ninfo_target <- item_info(target)\nbest5 <- names(sort(info_target, decreasing = TRUE))[1:5]\nbest5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"FL_1\"  \"FL_12\" \"FL_14\" \"FL_6\"  \"FL_13\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nforms <- combn(18, 5)\nall5 <- apply(forms, 2, function(k) sum(info_target[k]))\nc(full_test = round(sum(info_target), 2), best_five = round(sum(info_target[best5]), 2),\n  median_five = round(median(all5), 2), five_90th_percentile = round(unname(quantile(all5, 0.9)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           full_test            best_five          median_five \n                7.25                 4.18                 1.99 \nfive_90th_percentile \n                2.88 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# What the targeted form gives up away from its target.\nup <- 1.5\ninfo_up <- item_info(up)\nc(full_test = round(sum(info_up), 2), best_five = round(sum(info_up[best5]), 2),\n  best_five_for_1.5 = round(sum(sort(info_up, decreasing = TRUE)[1:5]), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        full_test         best_five best_five_for_1.5 \n             1.55              0.20              0.89 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(1 / sqrt(c(best5_at_target = sum(info_target[best5]), best5_at_1.5 = sum(info_up[best5]))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbest5_at_target    best5_at_1.5 \n           0.49            2.22 \n```\n\n\n:::\n:::\n\n\nThe best five for $\\theta = -1$ (FL_1, FL_12, FL_14, FL_6 and FL_13) give information 4.18 there, 58% of the full test's 7.25, from 28% of the items. The median of all 8,568 possible five-item forms gives 1.99, and the 90th percentile 2.88, so a form picked without looking at information is likely to give less than half as much. What the targeted form gives up shows at $\\theta = 1.5$: its information there is 0.20 (a CSEM of 2.22, against 0.49 at its target), and even the best five for $\\theta = 1.5$ would reach only 0.89.\n\nSo what should a practitioner do with a short form? It depends on an assumption about its use. If it serves one decision at a known point on the scale, precision elsewhere matters little, and information at that point is the right criterion. If it must rank everyone, or serve decisions no one has located yet, a form aimed at one point is a poor bet. When I know where the decisions are made, I build the short form from the items most informative there and report its CSEM at that point, not its reliability. Here, five well-chosen items give a CSEM of 0.49 at the decision point, against the full test's 0.37; no five items, and not even all eighteen, make the test precise at $\\theta = 1.5$.\n\n### A scale aimed high\n\nFor contrast, a scale built for a different job: the Perceptual Aberration scale of the Wisconsin Schizotypy Scales–Short Forms ([Winterstein et al., 2011](https://doi.org/10.1016/j.paid.2011.07.027)), in [christensen_2018_wsssf_5831](https://itemresponsewarehouse.org/tables/christensen_2018_wsssf_5831/). The data are 5,831 undergraduates who completed the scales as part of mass screening at one university ([Christensen et al., 2018](https://doi.org/10.3758/s13428-018-1032-9)). Its job here is to show a test whose information sits, by design, far from most of the people who took it. The items are true–false statements, and the scale measures distortions of body image and perception ([Chapman, Chapman & Raulin, 1978](https://doi.org/10.1037/0021-843X.87.4.399), who developed the full scale). They are keyed so that 1 is the response scored toward schizotypy ([Christensen et al., 2018, p. 2537](https://doi.org/10.3758/s13428-018-1032-9)).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nwss_url <- \"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_5:v4_0.christensen_2018_wsssf_5831/rows?format=csv\"\nws <- read.csv(wss_url)\nws <- as.data.frame(tapply(ws$resp, list(ws$id, ws$item), function(x) x[1]))\n# Items are keyed so that 1 is the response scored toward schizotypy. The 60 items\n# form four 15-item subscales (mi, pb, py, sa); their sum scores correlate like this:\nsub <- sapply(c(mi = \"mi\", pb = \"pb\", py = \"py\", sa = \"sa\"),\n              function(s) rowSums(ws[, startsWith(names(ws), s)]))\nround(cor(sub), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      mi   pb    py   sa\nmi  1.00 0.59 -0.06 0.14\npb  0.59 1.00  0.00 0.19\npy -0.06 0.00  1.00 0.31\nsa  0.14 0.19  0.31 1.00\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# We use one subscale, Perceptual Aberration (pb).\npb <- ws[, startsWith(names(ws), \"pb\")]\nc(respondents = nrow(pb), items = ncol(pb))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents       items \n       5831          15 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(range(colMeans(pb)), 2)   # proportion endorsing each item\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04 0.16\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nsum(rowSums(pb) == 0)             # respondents who endorse no item\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3430\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(mean(rowSums(pb) == 0), 2)  # as a share of all respondents\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.59\n```\n\n\n:::\n:::\n\n\nThe table holds four 15-item subscales. Their sum scores fall into two groups, Perceptual Aberration with Magical Ideation (correlation 0.59) and the two anhedonia scales (0.31), with correlations between −0.06 and 0.19 across the groups. One information curve assumes one $\\theta$, so we take one subscale, Perceptual Aberration. Each of its items is endorsed by 4% to 16% of respondents, and 3,430 of the 5,831 (59%) endorse none.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\npb_2 <- mirt(pb, 1, itemtype = \"2PL\", verbose = FALSE)\ncfp <- coef(pb_2, simplify = TRUE)$items\nround(c(min_b = min(-cfp[, \"d\"] / cfp[, \"a1\"]), max_b = max(-cfp[, \"d\"] / cfp[, \"a1\"]),\n        min_a = min(cfp[, \"a1\"]), max_a = max(cfp[, \"a1\"])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmin_b max_b min_a max_a \n 1.44  2.24  1.65  3.12 \n```\n\n\n:::\n:::\n\n\nThe difficulties run from 1.44 to 2.24 and the slopes from 1.65 to 3.12. Every item sits well above the average respondent (at 0), and every slope is above the median slope of the financial-literacy items.\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"Where on the scale will this subscale's conditional SEM be smallest?\",\n  choices: [\"Near θ = 0, the average respondent\", \"Near θ = −0.55, the estimate shared by the 59% who endorsed nothing\", \"Near θ = 2, above almost everyone\", \"About the same everywhere\"],\n  answer: \"Near θ = 2, above almost everyone\",\n  reveal: \"Near θ = 2: the information peaks at 18.22 at θ = 1.83, a CSEM of 0.23. At θ = 0 the CSEM is 0.88, and at −0.55, where most respondents sit, 1.49. Check the output below.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nI_pb <- testinfo(pb_2, matrix(theta))\nat <- c(-1, 0, 1, 2, 3)\ndata.frame(theta = at, information = round(I_pb[match(at, theta)], 2),\n           csem = round(1 / sqrt(I_pb[match(at, theta)]), 2))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| theta| information| csem|\n|-----:|-----------:|----:|\n|    -1|        0.19| 2.27|\n|     0|        1.29| 0.88|\n|     1|        8.18| 0.35|\n|     2|       17.50| 0.24|\n|     3|        4.86| 0.45|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(peak_at = theta[which.max(I_pb)], peak_information = round(max(I_pb), 2),\n  csem_at_peak = round(1 / sqrt(max(I_pb)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         peak_at peak_information     csem_at_peak \n            1.83            18.22             0.23 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Where the respondents are: everyone who endorsed nothing gets the same estimate.\neap_pb <- fscores(pb_2)[, 1]\nc(estimate_for_score_zero = round(unique(eap_pb[rowSums(pb) == 0]), 2),\n  csem_there = round(1 / sqrt(testinfo(pb_2, matrix(unique(eap_pb[rowSums(pb) == 0])))), 2),\n  share_with_csem_below_0.4 = round(mean(1 / sqrt(testinfo(pb_2, matrix(eap_pb))) < 0.4), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  estimate_for_score_zero                csem_there share_with_csem_below_0.4 \n                    -0.55                      1.49                      0.16 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nop <- par(mar = c(4, 4, 1, 4))\nhist(eap_pb, breaks = seq(-4, 4, 0.25), col = \"#93c5fd\", border = \"white\",\n     main = \"\", xlab = \"Perceptual aberration (theta)\", ylab = \"Respondents\")\npar(new = TRUE)\nplot(theta, pmin(1 / sqrt(I_pb), 3), type = \"l\", lwd = 2.5, col = \"#c2410c\", ylim = c(0, 3),\n     axes = FALSE, xlab = \"\", ylab = \"\")\naxis(4, col.axis = \"#c2410c\"); mtext(\"Conditional SEM (capped at 3)\", side = 4, line = 2.5, col = \"#c2410c\")\n```\n\n::: {.cell-output-display}\n![](information_files/figure-html/plot-wss-1.png){width=576}\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\npar(op)\n```\n:::\n\n\nThe information peaks at 18.22 at $\\theta = 1.83$, a CSEM of 0.23, lower than the financial-literacy test reaches anywhere. At $\\theta = 0$ the CSEM is 0.88; at $\\theta = -1$ it is 2.27. Everyone who endorsed nothing gets the same estimate, −0.55, where the CSEM is 1.49, and only 16% of respondents have a CSEM below 0.4. For most of these students, the scale says little more than \"not high\".\n\nThat is what a screening scale is for. Its items are ones few people endorse, so that endorsing several picks out the few respondents high on the trait; its precision is spent at the high end, where a screen makes its decisions. The curve that would be a problem for ranking all 5,831 students is the right shape for finding the ones to invite for a follow-up interview. Whether a test is precise is always a question of where, and for which decision.\n\n## Problems\n\n1. **The 3PL's information.** Starting from $P = c + (1 - c)L$ with $L = \\text{logit}^{-1}(a(\\theta - b))$ and the general formula $I = P'^2/[P(1-P)]$, fill in the algebra that gives the 3PL item information $a^2\\frac{(P - c)^2}{(1 - c)^2}\\frac{1 - P}{P}$. Then show that it peaks at $\\theta = b + \\frac{1}{a}\\log\\frac{1 + \\sqrt{1 + 8c}}{2}$, and check the answer against the widget with $a = 1$ and $c = 0.25$. (PS3#1)\n2. **Three items.** A test has three Rasch items with $b = -1, 0, 1.5$. Write down the test information, plot it, and find where it is largest. What is the CSEM there, and at $\\theta = 3$? Which single item would you add to bring the CSEM at $\\theta = 3$ below 1? (PS4#1)\n3. **What can go?** In the financial-literacy test, which three items could you drop with the least loss of information below $\\theta = 0$? Define \"below $\\theta = 0$\" yourself (a point, an average over a range, an average over the respondents there), and say whether your answer depends on the choice.\n4. **Design a form.** Ten Rasch items have difficulties $-2.5, -2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2$. Find the best five-item form for $\\theta = -1$ and its CSEM there. Then draw ten random five-item forms and compare. How often does a random form come within 10% of the best one's information? (PS6#3)\n5. **Is it a flaw?** A colleague reads the Perceptual Aberration output and says the scale is imprecise for 84% of respondents and should be revised. Write a paragraph in reply. For which uses is the colleague right, and for which not? What would you change if the scale had to rank all students, and what would that cost the screen?\n6. **Challenge (open): is the curve right?** A CSEM curve is computed from the model, so it inherits the model's assumptions (one $\\theta$, local independence, the right item curves). How would you check whether the CSEM curve for the financial-literacy test describes the real precision of its scores? Think about what you'd need: a retest, a split of the items, a second measure. I don't know of a check that works well with one administration and no other measure.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Information%2C%20precision%2C%20and%20short%20forms%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20item%20and%20test%20information%20in%20item%20response%20theory%3A%20information%20as%20the%20curvature%20of%20a%20respondent%27s%20log%20likelihood%2C%20item%20information%20for%20the%20Rasch%20model%2C%202PL%20and%203PL%2C%20why%20test%20information%20adds%20under%20local%20independence%2C%20the%20conditional%20standard%20error%20of%20measurement%201%2Fsqrt%28I%28theta%29%29%2C%20targeting%20tests%20to%20respondents%2C%20and%20choosing%20short%20forms%20by%20information%2C%20with%20mirt%20analyses%20of%20a%20financial-literacy%20test%20and%20the%20Perceptual%20Aberration%20scale%20of%20the%20Wisconsin%20Schizotypy%20Scales.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Lord, F. M., & Novick, M. R. (1968). *Statistical theories of mental test scores* (with contributions by A. Birnbaum). Addison-Wesley. <https://openlibrary.org/works/OL6568286W>. Birnbaum's chapters introduce the information of an item and of a test.\n- Lord, F. M. (1980). *Applications of item response theory to practical testing problems*. Erlbaum. <https://doi.org/10.4324/9780203056615>. Information functions put to work in test design.\n- Lord, F. M. (1977). Practical applications of item characteristic curve theory. *Journal of Educational Measurement*, 14(2), 117–138. <https://doi.org/10.1111/j.1745-3984.1977.tb00032.x>. Building a test to a target information curve.\n- Samejima, F. (1977). A use of the information function in tailored testing. *Applied Psychological Measurement*, 1(2), 233–247. <https://doi.org/10.1177/014662167700100209>. The standard error, rather than reliability, as the index of a score's dependability.\n- Kolen, M. J., Zeng, L., & Hanson, B. A. (1996). Conditional standard errors of measurement for scale scores using IRT. *Journal of Educational Measurement*, 33(2), 129–140. <https://doi.org/10.1111/j.1745-3984.1996.tb00485.x>. The CSEM on the score scale a testing program reports.\n- Fisher, R. A. (1925). Theory of statistical estimation. *Mathematical Proceedings of the Cambridge Philosophical Society*, 22(5), 700–725. <https://doi.org/10.1017/S0305004100009580>. Where information as a property of an estimation problem comes from.\n- Smith, G. T., McCarthy, D. M., & Anderson, K. G. (2000). On the sins of short-form development. *Psychological Assessment*, 12(1), 102–111. <https://doi.org/10.1037/1040-3590.12.1.102>. What a short form has to show beyond information.\n- Sireci, S. G., Thissen, D., & Wainer, H. (1991). On the reliability of testlet-based tests. *Journal of Educational Measurement*, 28(3), 237–247. <https://doi.org/10.1111/j.1745-3984.1991.tb00356.x>. What happens to precision when items share a passage. The IRW's [local dependence](https://itemresponsewarehouse.org/vignettes/local_dependence.html) vignette asks how often local independence fails across its tables.\n- Winterstein, B. P., Silvia, P. J., Kwapil, T. R., Kaufman, J. C., Reiter-Palmon, R., & Wigert, B. (2011). Brief assessment of schizotypy: Developing short forms of the Wisconsin Schizotypy Scales. *Personality and Individual Differences*, 51(8), 920–924. <https://doi.org/10.1016/j.paid.2011.07.027>. The short forms in the contrast table.\n- Chapman, L. J., Chapman, J. P., & Raulin, M. L. (1978). Body-image aberration in schizophrenia. *Journal of Abnormal Psychology*, 87(4), 399–407. <https://doi.org/10.1037/0021-843X.87.4.399>. The full Perceptual Aberration scale.\n- Christensen, A. P., Kenett, Y. N., Aste, T., Silvia, P. J., & Kwapil, T. R. (2018). Network structure of the Wisconsin Schizotypy Scales–Short Forms: Examining psychometric network filtering approaches. *Behavior Research Methods*, 50(6), 2531–2550. <https://doi.org/10.3758/s13428-018-1032-9>. The source of the schizotypy data.\n- Lusardi, A., & Mitchell, O. S. (2014). The economic importance of financial literacy: Theory and evidence. *Journal of Economic Literature*, 52(1), 5–44. <https://doi.org/10.1257/jel.52.1.5>. A review of research on financial literacy.\n- Chalmers, R. P. (2012). mirt: A multidimensional item response theory package for the R environment. *Journal of Statistical Software*, 48(6). <https://doi.org/10.18637/jss.v048.i06>. `testinfo()` and `iteminfo()` compute the curves in this lesson.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`bialowolski_2024_financial_literacy`](https://itemresponsewarehouse.org/tables/bialowolski_2024_financial_literacy/): Bialowolski, P. (2024). Financial literacy in a gendered language context [Data set]. Harvard Dataverse. <https://doi.org/10.7910/DVN/MTQGSF>. Licence: CC0 1.0.\n- [`christensen_2018_wsssf_5831`](https://itemresponsewarehouse.org/tables/christensen_2018_wsssf_5831/): Christensen, A.P., Kenett, Y.N., Aste, T. et al. Network structure of the Wisconsin Schizotypy Scales–Short Forms: Examining psychometric network filtering approaches. Behav Res 50, 2531–2550 (2018). <https://doi.org/10.3758/s13428-018-1032-9>. Licence: CC0 1.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 3 (slides c3, 35–42) and class 4 (slide 49), problem sets 3 (#1), 4 (#1) and 6 (#3), and the code in `ben-domingue/252`: `c4/info.R`.\n- **Timing:** the core ideas and widgets take about 60 minutes; the two real-data analyses work as a 30-minute lab. The fits take a few seconds each in local R.\n- **Changed from 252:** 2PL and 3PL information are taught here directly, since the lesson follows [From the 1PL to the 4PL](1pl-to-4pl.qmd). The contrast table uses one subscale of the Wisconsin Schizotypy Scales (Perceptual Aberration) rather than all 60 items, because the four subscales form two nearly uncorrelated groups and one information curve assumes one $\\theta$. The general information function, with the Rasch, 2PL and 3PL cases and additivity, is one Go deeper callout at the top of Core ideas (Ben, 09-25); problem 1 fills in the 3PL algebra and finds its peak.\n- **Held back:** the standard error of an individual estimate, and respondents with perfect or zero scores ([Estimating abilities](ability-estimation.qmd)); choosing items by information one at a time ([Item banks and adaptive testing](item-banks-cat.qmd)); error bands on reported scores and precision at cut scores ([What does a score mean?](score-meaning.qmd)); what fixing $c$ or giving it a prior does to information at the bottom of the scale ([Guessing and priors](guessing-priors.qmd)); information from polytomous items ([Models for polytomous responses](polytomous.qmd)) and from distractors ([Nominal response and multiple-choice models](nominal.qmd)). Local dependence, which inflates information, is named here; the lessons that treat it ([Dimensionality and multidimensional IRT](dimensionality.qmd), [Explanatory item response models](explanatory-irt.qmd)) are outside this lesson's prerequisite chain.\n- **Solutions:** held back in `solutions/information.qmd` (not published).\n",
    "supporting": [
      "information_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}