{
  "hash": "3cc67747aa7b339f3ea408c33c0ec13e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Validity as causation: Borsboom's view\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Module:** Validity  \n**Tranche:** extension (beyond a first course)  \n**Before this:** [Validity as an argument](validity-argument.qmd)  \n**Builds toward:** none  \n**Picks up threads:** Measurement as discovery; is the attribute quantitative? (from [What is measurement?](measurement.qmd))  \n**IRW tables:** [`vocab_assessment_3_to_8_year_old_children`](https://itemresponsewarehouse.org/tables/vocab_assessment_3_to_8_year_old_children/), [`robison_2026_retesting_stroop`](https://itemresponsewarehouse.org/tables/robison_2026_retesting_stroop/)  \n**From EDUC 252:** slides c4  \n**Status:** draft  \n**Authorship:** Written largely by Claude (Anthropic), from Ben Domingue's EDUC 252 materials and under Ben's direction. Ben reviews each lesson before it is marked done.\n:::\n\n```{ojs}\n//| echo: false\nimport {palette, grid} from \"./widgets/irt.js\"\nimport {ruleAnswer, torqueAnswer, ruleCorrect, itemType, ITEM_TYPES, mixAt, mixP, simEffects} from \"./widgets/validity-causal.js\"\nimport {quiz, predict} from \"./widgets/quiz.js\"\n```\n\n## What this is for\n\n[Validity as an argument](validity-argument.qmd) ended on a tension: an argument for every proposed use is a great deal to ask, and it may never be finished. This lesson takes up a narrower account. [Borsboom, Mellenbergh and van Heerden (2004)](https://doi.org/10.1037/0033-295X.111.4.1061) propose that a test is valid for an attribute when the attribute exists and differences in it cause differences in the responses. The evidence that matters most is then a theory of how respondents arrive at their answers, one that could be shown wrong. We work through the classic example, the balance scale, and then ask two questions of IRW data: does a simple theory of a vocabulary task predict which words are hard, and does a robust Stroop effect mark an attribute on which people differ?\n\n## Goals\n\nBy the end of this lesson you should be able to:\n\n- state Borsboom et al.'s definition of validity and the two claims it makes;\n- say how it differs from the argument-based view, and what each assumes;\n- derive the predictions of a theory of response behaviour, including an item on which respondents using a less advanced strategy should do better;\n- distinguish an effect that a manipulation causes within each person from an attribute on which people differ, and check which one a score tracks;\n- set out three ways the causal definition might relate to the argument-based view.\n\n## Core ideas\n\n### Is the bar too high?\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Validity as an argument](validity-argument.qmd): the *Standards* treat validity as the degree to which evidence supports an interpretation of scores for a proposed use, organized as an argument from responses to a decision. Backing some uses would take studies no psychometric analysis supplies.\n:::\n\nShould every measure of length first reckon with every use it might be put to? A ruler cuts shelves and tracks a child's growth, and nobody writes an argument for each. For many educational uses the argument is the right tool, since the uses are narrow and the stakes real. But if no argument is ever complete, a researcher who wants to know whether a task measures what it was built to measure may wonder where to start. Borsboom et al. (2004) narrow the question.\n\n### Borsboom's definition\n\nTheir definition has two parts. A test is valid for measuring an attribute if and only if the attribute exists and \"variations in the attribute causally produce variations in the outcomes of the measurement procedure\" ([Borsboom et al., 2004, p. 1061](https://doi.org/10.1037/0033-295X.111.4.1061)). They present this as a return to an older idea, which they trace to [Kelley (1927, p. 14)](https://openlibrary.org/works/OL22124924W): a test is valid if it measures what it claims to measure (as cited by Borsboom et al., 2004, p. 1061).\n\nThree features set it apart from the argument-based view.\n\n- **Validity is a property of the test.** *Validation* is the research that finds out whether a test has it (p. 1063). A test can have the property while some use of its scores is unwise.\n- **It is yes or no**, as truth is: the attribute exists and affects the responses, or not (p. 1070). Reliability, bias and usefulness still matter, under their own names.\n- **The evidence is about response processes.** A pattern of correlations with other measures, the nomological network of [Cronbach and Meehl (1955)](https://doi.org/10.1037/h0040957), can corroborate a theory, they argue, but networks in psychology are loose enough that many attributes besides the intended one would fit them (pp. 1064–1065). What needs testing is a theory of how the attribute produces the answers (p. 1061): construct representation ahead of nomothetic span, in the terms of [Whitely (1983)](https://doi.org/10.1037/0033-2909.93.1.179), now Embretson (Borsboom et al., 2004, p. 1067).\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [What is measurement?](measurement.qmd): measurement is a discovery. Temperature was there all along; what took a century of work was the theory of what an equal step of it is. Whether a psychological attribute is quantitative is a claim about the world that could be false.\n:::\n\nBorsboom et al. take the same realist stance: if an attribute isn't there, no test measures it, however useful the scores. What does the definition assume? That the attribute exists apart from the test; that causation runs from attribute to responses, so formative indices such as socioeconomic status fall outside it (p. 1069); and that we know whether the attribute varies between people or within a person, a point we return to below.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"A reading test's scores correlate 0.6 with teacher ratings and 0.5 with grades, as its developers predicted. On Borsboom et al.'s definition, what do these correlations establish?\",\n  options: [\n    {text: \"They corroborate the theory behind the test but don't settle whether reading ability causes the scores\", correct: true, why: \"A match with a network of correlations is consistent with many attributes. The definition asks whether reading ability exists and produces differences in the responses, which is a claim about the response process.\"},\n    {text: \"That the test is valid, since the correlations match the prediction\", correct: false, why: \"That is closer to the nomological-network view. On the causal definition, correlations are evidence that can point toward validity, not what validity consists of.\"},\n    {text: \"Nothing at all, since correlations are irrelevant to validity\", correct: false, why: \"Borsboom et al. treat correlations as relevant evidence (they can indicate causation), but not as what makes a test valid.\"}\n  ]\n})\n```\n\n### A theory of response behaviour: the balance scale\n\nWhat does a theory of response behaviour look like? Borsboom et al.'s example is the balance scale (p. 1068), studied by [Inhelder and Piaget (1958)](https://doi.org/10.1037/10034-000) and turned into rules by [Siegler (1976)](https://doi.org/10.1016/0010-0285(76)90016-5). A child sees a beam with a stack of weights on one peg on each side of the fulcrum, and says whether it will tip left, tip right or balance. Children are proposed to move through four rules:\n\n- **Rule I:** look only at the number of weights; the heavier side goes down.\n- **Rule II:** the same, but when the weights are equal, the side with weights farther out goes down.\n- **Rule III:** consider weights and distances, and when they point opposite ways, guess.\n- **Rule IV:** compare weight times distance on each side (the torque), which is always right.\n\nThe theory says what each rule answers on every item, so it predicts whole response patterns, not only totals.\n\n#### Try it: four rules, one beam\n\nSet the weights and pegs. The table gives each rule's answer to this item.\n\n```{ojs}\n//| echo: false\nviewof bs_wl = Inputs.range([1, 5], {value: 4, step: 1, label: \"Weights on the left\"})\nviewof bs_dl = Inputs.range([1, 5], {value: 2, step: 1, label: \"Left peg (distance from the fulcrum)\"})\nviewof bs_wr = Inputs.range([1, 5], {value: 2, step: 1, label: \"Weights on the right\"})\nviewof bs_dr = Inputs.range([1, 5], {value: 3, step: 1, label: \"Right peg (distance from the fulcrum)\"})\n```\n\n```{ojs}\n//| echo: false\n{\n  const blocks = [\n    ...d3.range(bs_wl).map(k => ({x: -bs_dl, y: 0.15 + k * 0.5})),\n    ...d3.range(bs_wr).map(k => ({x: bs_dr, y: 0.15 + k * 0.5}))\n  ];\n  return Plot.plot({\n    width: 520, height: 230, x: {domain: [-5.8, 5.8], ticks: d3.range(-5, 6), tickFormat: d => Math.abs(d), label: \"Peg\"},\n    y: {domain: [-1.2, 2.8], axis: null},\n    marks: [\n      Plot.ruleY([0], {x1: -5.5, x2: 5.5, stroke: palette.ink, strokeWidth: 4}),\n      Plot.tickX(d3.range(-5, 6).filter(d => d !== 0), {x: d => d, y1: -0.15, y2: 0.1, stroke: palette.guide}),\n      Plot.dot([{x: 0, y: -0.55}], {x: \"x\", y: \"y\", symbol: \"triangle\", r: 14, fill: palette.guide}),\n      Plot.rect(blocks, {x1: d => d.x - 0.3, x2: d => d.x + 0.3, y1: \"y\", y2: d => d.y + 0.42, fill: palette.main})\n    ]\n  });\n}\n```\n\n```{ojs}\n//| echo: false\n{\n  const truth = torqueAnswer(bs_wl, bs_dl, bs_wr, bs_dr);\n  const say = a => a === \"balance\" ? \"balances\" : a === \"guess\" ? \"guesses\" : `${a} side down`;\n  const cell = \"padding:0.25rem 0.7rem;text-align:left\";\n  const kind = itemType(bs_wl, bs_dl, bs_wr, bs_dr);\n  const lab = kind === \"agree\" ? \"Weight and distance point the same way\" : ITEM_TYPES.find(t => t.key === kind).label;\n  return htl.html`<p>Torques: left ${bs_wl} × ${bs_dl} = ${bs_wl * bs_dl}, right ${bs_wr} × ${bs_dr} = ${bs_wr * bs_dr}. The beam <b>${truth === \"balance\" ? \"balances\" : `tips ${truth}`}</b>. Item type: <i>${lab}</i>.</p>\n  <table style=\"font-size:0.9rem;border-collapse:collapse\"><thead><tr><th style=${cell}>Rule</th><th style=${cell}>Says</th><th style=${cell}>Chance of a right answer</th></tr></thead>\n  <tbody>${[1, 2, 3, 4].map(r => { const p = ruleCorrect(r, bs_wl, bs_dl, bs_wr, bs_dr);\n    return htl.html`<tr><td style=${cell}>${[\"I\", \"II\", \"III\", \"IV\"][r - 1]}</td><td style=${cell}>${say(ruleAnswer(r, bs_wl, bs_dl, bs_wr, bs_dr))}</td>\n    <td style=${cell}><span style=\"color:${p === 1 ? palette.main : palette.contrast}\">${p === 1 ? \"1\" : p === 0 ? \"0\" : \"1 in 3\"}</span></td></tr>`; })}</tbody></table>`;\n}\n```\n\nThe starting item puts four weights on peg 2 against two on peg 3; the heavier side has more torque (8 against 6) and goes down. Rules I and II get it right from the weights alone; Rule III sees the cues disagree and guesses. On such items, children using an earlier rule should outscore those using a later one. Move the right-hand stack to peg 5 and only Rule IV is sure to be right.\n\nA theory that predicts a *drop* in performance as children develop is a theory the data can break. It says what must happen between showing the item and hearing the answer for the task to measure the child's stage (Borsboom et al., 2004, p. 1068).\n\n#### Try it: rule classes to response patterns\n\nIf each child uses one rule, the rules are **latent classes**, and the mix of rule users predicts the proportion correct on each item type. The first slider moves a group along the sequence (0: everyone on Rule I; 3: everyone on Rule IV); the second sets how much rule use overlaps. The curve is stylized, not data.\n\n```{ojs}\n//| echo: false\nviewof rc_pos = Inputs.range([0, 3], {value: 2, step: 0.05, label: \"Where the group is in the sequence\"})\nviewof rc_spread = Inputs.range([0.2, 1.5], {value: 0.6, step: 0.05, label: \"How much rule use overlaps\"})\n```\n\n```{ojs}\n//| echo: false\n{\n  const shown = [\n    {j: 2, name: \"Same weights, distances differ\", colour: palette.guide},\n    {j: 3, name: \"Conflict: heavier side goes down\", colour: palette.contrast},\n    {j: 4, name: \"Conflict: farther side goes down, or it balances\", colour: palette.main}\n  ];\n  const curve = grid(0, 3, 121).flatMap(p => { const q = mixP(mixAt(p, rc_spread)); return shown.map(s => ({p, v: q[s.j], name: s.name})); });\n  const now = mixP(mixAt(rc_pos, rc_spread));\n  return Plot.plot({\n    width: 640, height: 300, x: {label: \"Position in the rule sequence (0 = Rule I, 3 = Rule IV)\"}, y: {label: \"Expected proportion correct\", domain: [0, 1]},\n    color: {legend: true, domain: shown.map(s => s.name), range: shown.map(s => s.colour)},\n    marks: [\n      Plot.ruleY([1 / 3], {stroke: palette.rule}),\n      Plot.line(curve, {x: \"p\", y: \"v\", stroke: \"name\", strokeWidth: 2.5}),\n      Plot.ruleX([rc_pos], {stroke: palette.guide, strokeDasharray: \"4,3\"}),\n      Plot.dot(shown.map(s => ({p: rc_pos, v: now[s.j], name: s.name})), {x: \"p\", y: \"v\", fill: \"name\", r: 5})\n    ]\n  });\n}\n```\n\n```{ojs}\n//| echo: false\n{\n  const mix = mixAt(rc_pos, rc_spread), q = mixP(mix), total = q.reduce((u, v) => u + v, 0);\n  return md`Rule users here: I ${(100 * mix[0]).toFixed(0)}%, II ${(100 * mix[1]).toFixed(0)}%, III ${(100 * mix[2]).toFixed(0)}%, IV ${(100 * mix[3]).toFixed(0)}%. Expected proportion correct on the heavier-side conflict item: **${q[3].toFixed(2)}**. Expected total over one item of each of the six types: **${total.toFixed(2)}** of 6.`;\n}\n```\n\nThe heavier-side conflict line starts at 1, falls to about 0.56 when most children use Rule III, and climbs again as Rule IV takes over. A single ability that makes every item easier as it grows can't produce that dip, which is why [Jansen and van der Maas (1997)](https://doi.org/10.1006/drev.1997.0437) tested the rules as latent classes. Totals hide the difference: Rule II and Rule III children both expect 4 of the 6 right, but not the same 4. In 805 respondents aged 5 to 19, [Jansen and van der Maas (2002)](https://doi.org/10.1006/jecp.2002.2664) found that children use rules, that different ages use different rules, and that some use them inconsistently. The theory isn't settled (Borsboom et al., 2004, p. 1068); it is definite enough to test.\n\n::: {.callout-tip appearance=\"simple\"}\n**Recall** from [Constructs and construct maps](constructs.qmd): a good construct map orders items before anyone answers them, and assumes a continuum. The balance-scale theory orders response *patterns*, with latent classes in place of a continuum, the alternative that lesson raised. [Latent classes and cognitive diagnosis](cdm.qmd) fits such models.\n:::\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"Which item separates a Rule II child from a Rule III child?\",\n  options: [\n    {text: \"Three weights on peg 2 against two on peg 4 (the farther side wins, 8 against 6)\", correct: true, why: \"Weights and distances conflict. Rule II goes by the weights and says the left side goes down, which is wrong; Rule III guesses and is right a third of the time. Here the Rule III child is expected to do better.\"},\n    {text: \"Three weights on peg 2 against two on peg 2\", correct: false, why: \"The distances are equal, so both rules go by the weights and both are right.\"},\n    {text: \"Two weights on peg 3 against two on peg 1\", correct: false, why: \"The weights are equal, so both rules look at distance and both are right. This item separates Rule I from the rest.\"}\n  ]\n})\n```\n\n### Does the attribute exist, and in whom?\n\nA manipulation can cause differences in responses without there being an attribute on which people differ. [Borsboom, Mellenbergh and van Heerden (2003)](https://doi.org/10.1037/0033-295X.110.2.203) distinguish between-subjects from within-subjects readings of a latent variable, and the 2004 paper draws the consequence: variation across people can only be caused by something that varies across people, and variation within a person only by something that varies within that person (pp. 1069–1070). Evidence at one level doesn't establish the other.\n\nIn the Stroop task ([Stroop, 1935](https://doi.org/10.1037/h0054651)), naming a word's ink colour takes longer when the word names another colour, an effect caused within each person. Does each person's effect then measure a trait on which people differ? Only if they differ stably. [Hedge, Powell and Sumner (2018)](https://doi.org/10.3758/s13428-017-0935-1) argue that tasks become established for their effects partly because respondents differ little in them, which leaves the effects unreliable as measures of individuals.\n\n#### Try it: a common cause, small differences\n\nHere 250 simulated respondents do a Stroop-like task twice. Conflict slows them by 0.11 s on average; the sliders set how much the true slowing varies from person to person and how many trials each condition gets. Trial response times have SD 0.8 s, about what the IRW table below shows.\n\n```{ojs}\n//| echo: false\nviewof ws_tau = Inputs.range([0, 0.3], {value: 0.1, step: 0.01, label: \"Person SD of the true effect (s)\"})\nviewof ws_trials = Inputs.range([10, 300], {value: 25, step: 5, label: \"Trials per condition\"})\nviewof ws_seed = Inputs.range([1, 20], {value: 1, step: 1, label: \"Sample (seed)\"})\n```\n\n```{ojs}\n//| echo: false\nws = simEffects({tau: ws_tau, trials: ws_trials, seed: ws_seed})\nPlot.plot({\n  width: 420, height: 380, x: {label: \"Effect at session 1 (s)\", domain: [-1.2, 1.4]}, y: {label: \"Effect at session 2 (s)\", domain: [-1.2, 1.4]},\n  marks: [\n    Plot.ruleX([0], {stroke: palette.rule}), Plot.ruleY([0], {stroke: palette.rule}),\n    Plot.dot(ws.pts, {x: \"s1\", y: \"s2\", r: 2.5, fill: palette.main, fillOpacity: 0.6}),\n    Plot.dot([{s1: ws.mean, s2: ws.mean}], {x: \"s1\", y: \"s2\", r: 7, fill: palette.contrast})\n  ]\n})\n```\n\n```{ojs}\n//| echo: false\nmd`Group effect at session 1: **${ws.mean.toFixed(3)} s**, t = **${ws.t.toFixed(1)}**, positive for ${(100 * ws.pos).toFixed(0)}% of respondents. Retest correlation of the effect: **${ws.r.toFixed(2)}** (the model's reliability: ${ws.rel.toFixed(2)}).`\n```\n\nSet the person SD to 0. The group effect stays clear (t near 7 with 25 trials) while the retest correlation hovers around zero: the manipulation slows everyone, and there is nothing to rank. At 0.1 s the retest correlation is low with 25 trials and passes 0.6 with 240, the number Hedge et al. gave per condition. A clear group effect shows that the cause operates within people, not that there is a between-person attribute.\n\n```{ojs}\n//| echo: false\nquiz({\n  q: \"In the widget, with the person SD at 0, what does the retest correlation of the effect estimate?\",\n  options: [\n    {text: \"Zero: respondents don't differ in the true effect, so their effects on two occasions are unrelated noise\", correct: true, why: \"The reliability is the share of variance in observed effects that is true between-person variance, and here there is none.\"},\n    {text: \"A high value, since the group effect is very clear\", correct: false, why: \"The group effect depends on the average, the retest correlation on differences between people. With no differences, the average can be clear and the ranking empty.\"},\n    {text: \"It depends on the number of trials\", correct: false, why: \"More trials shrink the noise in each respondent's effect, but with no true differences the correlation is still expected to be zero.\"}\n  ]\n})\n```\n\n### Replacement, complement, or a different grain size?\n\nHow does the causal definition sit beside the argument-based view? If validity concerns only the attribute, where do uses go? What about score variation the attribute doesn't cause, such as familiarity with a tablet? And the examples that make the causal view persuasive, balance scales and small cognitive tasks, are a different grain of instrument from a state test serving several uses. There are three readings, each resting on its own assumptions.\n\n- **A replacement.** Validity means the causal claim and nothing else. Borsboom et al. offer their conception as an alternative to the current consensus, with consequences central to test *use* but not to validity (p. 1069), and a test's fitness for a purpose judged under a plainer heading such as overall quality (p. 1070). This assumes that what a test measures can be settled apart from any use, and that *validity* is clearer kept for it.\n- **A complement.** The causal claim is one warrant inside an argument, for the scoring and extrapolation links, backed by response-process evidence, which the *Standards* already list as a source ([AERA, APA & NCME, 2014, pp. 13–14](https://www.testingstandards.net/open-access-files.html)). This assumes an argument can carry a causal claim as one link, and that uses and consequences belong under the same word.\n- **A concept for a different grain size.** The causal definition fits instruments with one attribute and a known response process; the argument fits instruments whose scores summarize a content domain for many uses, where no single attribute may be doing the causing. This assumes the two answer different questions about different kinds of instrument, so one concept of validity need not cover both.\n\nWhich reading holds has no settled answer; challenge problem 6 leaves it open. If you've done [Structural equation modeling with lavaan](sem.qmd), its equivalent models, different causal structures that fit the same covariances equally well, carry the same caution about causal claims.\n\n## Simulate\n\nThe code below is the between/within widget in R, for person SDs of 0, 0.1 and 0.2 s and for 25 and 240 trials per condition. It is base R and runs in about a second.\n\nWith the seed as written and 25 trials, a person SD of 0 gives t = 6.6 and a retest correlation of 0.04; a person SD of 0.2 gives t = 4.2 and 0.48. A clearer group effect is no sign of a better ranking. Congruent RT retests at 0.9 or above throughout, since the simulated respondents differ in speed. Correlations move by about ±0.06 between runs, so compare `r_effect` with `reliability`. Then set `sigma` to 0.3: how many trials does a person SD of 0.1 need for a retest correlation of 0.7?\n\n\n::: {.cell}\n```{webr}\n#| results: markup\n#| warning: false\n#| message: false\n#| include: true\n#| label: unnamed-chunk-15\n# A cause without an individual attribute. Every simulated respondent is slowed by\n# conflict (the Stroop manipulation), by mu seconds on average; respondents differ in\n# that slowing with SD tau, and in their overall speed with SD 0.45 s. Each respondent\n# does the task twice, with `trials` trials per condition each time, and every trial\n# adds noise with SD sigma. For several values of tau and trials we ask two questions:\n# is the group effect clear (t at session 1), and does each respondent's effect at\n# session 1 predict their effect at session 2 (the retest correlation)? Base R only.\n# New for this course.\nset.seed(34)\nn     <- 250    # respondents\nmu    <- 0.11   # average conflict effect (s)\nsigma <- 0.8    # trial-to-trial SD of RT (s), about what the IRW Stroop table shows\n\none_run <- function(tau, trials) {\n  speed  <- rnorm(n, 1.6, 0.45)           # each respondent's congruent RT\n  effect <- rnorm(n, mu, tau)             # each respondent's true conflict effect\n  session <- function() {\n    cong   <- speed + rnorm(n, 0, sigma / sqrt(trials))           # mean of `trials` trials\n    incong <- speed + effect + rnorm(n, 0, sigma / sqrt(trials))\n    data.frame(cong = cong, eff = incong - cong)\n  }\n  s1 <- session(); s2 <- session()\n  c(tau = tau, trials = trials,\n    t_session1   = mean(s1$eff) / (sd(s1$eff) / sqrt(n)),\n    share_pos    = mean(s1$eff > 0),\n    r_effect     = cor(s1$eff, s2$eff),\n    r_congruent  = cor(s1$cong, s2$cong),\n    reliability  = tau^2 / (tau^2 + 2 * sigma^2 / trials))   # what r_effect estimates\n}\n\ngrid <- expand.grid(tau = c(0, 0.1, 0.2), trials = c(25, 240))\nres <- t(mapply(one_run, grid$tau, grid$trials))\nround(res, 2)\n\n```\n:::\n\n\n[Download this code](code/validity-causal-sim.R) to run it in your own R session.\n\n## With real data\n\n\n\nThe main example, [vocab_assessment_3_to_8_year_old_children](https://itemresponsewarehouse.org/tables/vocab_assessment_3_to_8_year_old_children/), tests a theory of response behaviour, standing in for the balance scale, which the IRW doesn't hold. The contrast, [robison_2026_retesting_stroop](https://itemresponsewarehouse.org/tables/robison_2026_retesting_stroop/), has a cause that works in everyone and asks whether it ranks anyone. [Download the code](code/validity-causal-irw.R); it needs only base R.\n\n### A vocabulary task with a theory\n\noREV is a receptive vocabulary task for German-speaking children aged 3 to 8 ([Bohn et al., 2022](https://doi.org/10.31234/osf.io/4z86w)). A child hears a word and picks one of four pictures: the target, a semantically related distractor, a phonologically similar one and an unrelated one. Twenty of the 52 words were added to an existing task for their rated ages of acquisition, between six and ten years (pp. 8–9). A response is 1 when the child picked the target, and nothing is missing. The `item` column is the trial position, which holds different words in the two presentation orders, so the word (`targetword`) is the item here.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The IRW table, from the CSV link on its landing page (pinned to one version).\norev <- read.csv(paste0(\"https://redivis.com/api/v1/tables/datapages.item_response_warehouse:v60_0.\",\n                        \"vocab_assessment_3_to_8_year_old_children/rows?format=csv\"))\nc(rows = nrow(orev), children = length(unique(orev$id)), words = length(unique(orev$targetword)),\n  missing = sum(is.na(orev$resp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    rows children    words  missing \n   30212      581       52        0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# `item` is the trial position, and the two presentation orders put different\n# words at the same position, so the word itself (`targetword`) is the item here.\nunique(orev[orev$item == 1, c(\"item\", \"itemcov_order\", \"targetword\")])\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    | item|itemcov_order |targetword |\n|:---|----:|:-------------|:----------|\n|1   |    1|orderB        |door       |\n|169 |    1|orderA        |squirrel   |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(range(tapply(orev$cov_age, orev$id, mean)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3 8\n```\n\n\n:::\n:::\n\n\nThe theory is simple: a child picks the target once they know the word, and children learn words at about the ages adults rate. Before any response is seen, it predicts that later-acquired words will be harder.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# resp is 1 when the child picked the pictured target. One row per word: its\n# proportion correct and its rated age of acquisition (in years).\nwords <- data.frame(p   = tapply(orev$resp, orev$targetword, mean),\n                    aoa = tapply(orev$itemcov_aoa_german_comb, orev$targetword, unique))\n# Difficulty on the logit scale: the log odds of a wrong answer. Words that every\n# child answered correctly have no finite logit and are set aside.\nwords$logit <- qlogis(1 - words$p)\nfin <- words[words$p < 1, ]\nc(words_all_correct = sum(words$p == 1), words_used = nrow(fin))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwords_all_correct        words_used \n                5                47 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(r_aoa_logit = cor(fin$aoa, fin$logit),\n        rank_r_aoa_p_all_words = cor(words$aoa, words$p, method = \"spearman\")), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           r_aoa_logit rank_r_aoa_p_all_words \n                  0.88                  -0.86 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nhead(words[order(words$aoa), c(\"aoa\", \"p\")], 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|         |  aoa|         p|\n|:--------|----:|---------:|\n|cap      | 1.95| 0.9982788|\n|snake    | 2.00| 1.0000000|\n|squirrel | 2.60| 0.9965577|\n|eye      | 2.69| 0.9965577|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntail(words[order(words$aoa), c(\"aoa\", \"p\")], 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|          |  aoa|         p|\n|:---------|----:|---------:|\n|cello     | 8.67| 0.4681583|\n|kayak     | 8.82| 0.5731497|\n|satellite | 8.94| 0.5903614|\n|orchid    | 9.76| 0.7142857|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot(fin$aoa, fin$logit, pch = 19, col = \"#2780e3\",\n     xlab = \"Rated age of acquisition (years)\", ylab = \"Difficulty (log odds of a wrong answer)\")\nabline(lm(logit ~ aoa, data = fin), lty = 2, col = \"#999999\")\n```\n\n::: {.cell-output-display}\n![](validity-causal_files/figure-html/orev-plot-1.png){width=576}\n:::\n:::\n\n\nAge of acquisition correlates 0.88 with difficulty over the 47 words that some child missed (the rank correlation with proportion correct, over all 52, is −0.86). Against the baseline of [Constructs and construct maps](constructs.qmd), where a map written from item text ordered nine number-series items at −0.76, this theory orders the words rather well. Both orders also put later-acquired words later in the task, so fatigue could mimic the pattern; the check below rules that out.\n\n::: {.callout-note collapse=\"true\"}\n## Could position be doing the ordering?\n\nPosition and age of acquisition correlate 0.83, by design. But each word sits at different positions in the two orders, so we can ask whether a word does worse where it comes later.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The task's two orders were built so that later trials have later-acquired words.\n# If words late in the task are harder because children tire, position would do the\n# work we credit to age of acquisition. Each word sits at different positions in the\n# two orders, so compare.\npos <- aggregate(cbind(position = item, p = resp) ~ targetword + itemcov_order, data = orev, FUN = mean)\nround(cor(pos$position, words[pos$targetword, \"aoa\"]), 2)   # position vs AoA, by design\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.83\n```\n\n\n:::\n\n```{.r .cell-code}\nwa <- pos[pos$itemcov_order == \"orderA\", ]; wb <- pos[pos$itemcov_order == \"orderB\", ]\nboth <- merge(wa, wb, by = \"targetword\", suffixes = c(\"_A\", \"_B\"))\n# Does a word placed later get answered correctly less often?\nround(cor(both$position_A - both$position_B, both$p_A - both$p_B), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.05\n```\n\n\n:::\n\n```{.r .cell-code}\n# The AoA-difficulty correlation within each order separately:\nsapply(split(pos, pos$itemcov_order), function(d) {\n  d <- d[d$p < 1, ]\n  round(cor(words[d$targetword, \"aoa\"], qlogis(1 - d$p)), 2)\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\norderA orderB \n  0.87   0.88 \n```\n\n\n:::\n:::\n\n\nIt isn't: the difference in position between the orders and the difference in proportion correct correlate −0.05, and the correlation between age of acquisition and difficulty is 0.87 and 0.88 within each order.\n:::\n\nThe theory's other prediction, that older children know more words, holds too:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The same theory says older children know more words.\nkids <- data.frame(age   = tapply(orev$cov_age, orev$id, mean),\n                   score = tapply(orev$resp, orev$id, sum))\nround(cor(kids$age, kids$score), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.63\n```\n\n\n:::\n:::\n\n\nAge correlates 0.63 with the number of words a child got right. And the wrong answers? The theory as stated says a child who doesn't know a word guesses, so wrong answers should split evenly across the three distractors.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# A second prediction. If a child who doesn't know a word guesses at random, wrong\n# answers should spread evenly over the three other pictures. The distractor types\n# are coded dist1, dist2, dist3; the chosen words show which is which (ruin ->\n# fortress is semantic; Gazelle -> Libelle, \"dragonfly\", is phonological).\nunique(orev[orev$targetword %in% c(\"ruin\", \"gazelle\") & orev$chosencategory != \"target\",\n            c(\"targetword\", \"chosencategory\", \"chosenword\")])\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |targetword |chosencategory |chosenword |\n|:-----|:----------|:--------------|:----------|\n|7555  |ruin       |dist1          |fortress   |\n|7569  |ruin       |dist3          |goalkeeper |\n|7574  |ruin       |dist2          |railtracks |\n|10481 |gazelle    |dist1          |deer       |\n|10687 |gazelle    |dist3          |astronaut  |\n|10702 |gazelle    |dist2          |dragonfly  |\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nwrong <- orev$chosencategory[orev$resp == 0]\nwrong <- factor(wrong, levels = c(\"dist1\", \"dist2\", \"dist3\"),\n                labels = c(\"semantic\", \"phonological\", \"unrelated\"))\nround(prop.table(table(wrong)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwrong\n    semantic phonological    unrelated \n        0.47         0.31         0.22 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nchisq.test(table(wrong))$p.value < 0.001\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nThey don't: 47% go to the semantic distractor, 31% to the phonological one and 22% to the unrelated one. Children who miss a word often know something about it. This part of the theory is broken by the data, which is what a theory of response behaviour is for; the repair is partial knowledge, and a model for which option a respondent picks ([Nominal response and multiple-choice models](nominal.qmd)) can write it down.\n\n### A Stroop task given twice\n\n[Robison et al. (2026)](https://doi.org/10.3758/s13428-025-02897-8) gave undergraduates a battery of cognitive tasks over four weekly sessions, repeating the first two sessions in the last two, so each task was retaken about two weeks later. Ours is a timed Stroop ([Burgoyne et al., 2023](https://doi.org/10.1037/xge0001408)): RED or BLUE appears in red or blue ink, and respondents click the response word that matches the ink, as many times as they can in 90 seconds (Robison et al., 2026, Method). The items are the four word–ink combinations, and `itemcov_conflict` marks whether word and ink disagree. A response is 1 when correct; response times are in seconds.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nstroop <- read.csv(paste0(\"https://redivis.com/api/v1/tables/datapages.item_response_warehouse_5:v5_0.\",\n                          \"robison_2026_retesting_stroop/rows?format=csv\"))\ntable(item = stroop$item, conflict = stroop$itemcov_conflict)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               conflict\nitem            congruent incongruent\n  BlueinBlueInk      7383           0\n  BlueinRedInk          0        7385\n  RedinBlueInk          0        7253\n  RedinRedInk        7346           0\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nc(respondents = length(unique(stroop$id)), trials = nrow(stroop))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrespondents      trials \n        250       29367 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\ntable(wave = stroop$wave)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwave\n    1     2 \n13953 15414 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\n# Trials per respondent in each session (the timed block lasts 90 s).\nround(tapply(stroop$id, stroop$wave, length) / tapply(stroop$id, stroop$wave, function(x) length(unique(x))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 1  2 \n57 64 \n```\n\n\n:::\n:::\n\n\nFirst, a check on the pipeline: the task's own score, correct minus incorrect responses, retested at 0.80 in Robison et al.'s Table 6.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Sanity check: the task's own score (correct minus incorrect responses in the timed\n# block) should rank people about as consistently as Robison et al. report.\nsc <- aggregate(resp ~ id + wave, data = stroop, FUN = function(x) sum(x == 1) - sum(x == 0))\nsc <- reshape(sc, idvar = \"id\", timevar = \"wave\", direction = \"wide\")\nround(cor(sc$resp.1, sc$resp.2, use = \"complete.obs\"), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.81\n```\n\n\n:::\n:::\n\n\nWe get 0.81. Now the effect: each respondent's mean response time on correct conflicting trials minus that on correct congruent trials.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# The Stroop effect for each respondent and session: mean RT (seconds) on correct\n# incongruent trials minus mean RT on correct congruent trials. Trials faster than\n# 0.2 s or slower than 5 s are set aside (about 1% of correct trials).\nok <- stroop$resp == 1 & stroop$rt > 0.2 & stroop$rt < 5\nround(mean(!ok[stroop$resp == 1]), 3)         # share of correct trials set aside\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.012\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nm <- aggregate(rt ~ id + wave + itemcov_conflict, data = stroop[ok, ], FUN = mean)\nm <- reshape(m, idvar = c(\"id\", \"wave\"), timevar = \"itemcov_conflict\", direction = \"wide\")\nm$effect <- m$rt.incongruent - m$rt.congruent\ns1 <- m[m$wave == 1, ]\nn_trials <- aggregate(rt ~ id + wave + itemcov_conflict, data = stroop[ok, ], FUN = length)\nmedian(n_trials$rt)                            # correct trials per condition and session\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(c(n = nrow(s1), mean_effect = mean(s1$effect), sd_effect = sd(s1$effect),\n        d_z = mean(s1$effect) / sd(s1$effect),\n        t = mean(s1$effect) / (sd(s1$effect) / sqrt(nrow(s1))),\n        share_positive = mean(s1$effect > 0)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             n    mean_effect      sd_effect            d_z              t \n        244.00           0.11           0.29           0.37           5.71 \nshare_positive \n          0.70 \n```\n\n\n:::\n:::\n\n\nAt session 1, conflict slows respondents by 0.11 s on average ($d_z = 0.37$, $t = 5.7$ over 244 respondents), and 70% show a positive effect. The manipulation works. Does each respondent's effect say something stable about them?\n\n```{ojs}\n//| echo: false\npredict({\n  q: \"For the 234 respondents with both sessions, what is the correlation between their Stroop effect at session 1 and at session 2, about two weeks later?\",\n  choices: [\"About 0.15\", \"About 0.45\", \"About 0.75\"],\n  answer: \"About 0.15\",\n  reveal: \"It is 0.17. Congruent response time alone retests at 0.73 over the same two weeks, and the task score at 0.81. Respondents differ stably in speed, and barely in how much conflict slows them.\"\n})\n```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n# Retest: the same respondents, about two weeks later.\nb <- merge(m[m$wave == 1, ], m[m$wave == 2, ], by = \"id\", suffixes = c(\"_1\", \"_2\"))\nround(c(n_both = nrow(b),\n        r_effect      = cor(b$effect_1, b$effect_2),\n        r_congruent   = cor(b$rt.congruent_1, b$rt.congruent_2),\n        r_incongruent = cor(b$rt.incongruent_1, b$rt.incongruent_2)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       n_both      r_effect   r_congruent r_incongruent \n       234.00          0.17          0.73          0.64 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\nround(mean(m$effect[m$wave == 2]), 2)          # the group effect at session 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1\n```\n\n\n:::\n:::\n\n\nThe effect's retest correlation is 0.17, against 0.73 for congruent and 0.64 for conflicting response time. Each effect rests on a median of 25 correct trials per condition and session, and the widget shows what more trials would buy. Still, the pattern is the one Borsboom et al.'s distinction points to: conflict slows people, clearly enough to detect in 244 of them; people differ stably in speed; they differ little, over two weeks, in how much conflict slows them. [Trials as items](trials.qmd) takes the reliability paradox further.\n\nWhere does that leave a practitioner? Before I trust a score as a measure of an attribute, I want two checks. First, one prediction from a theory of how people answer the items that the data could have broken and didn't: which items should be harder, or an item that lower scorers should get right more often. Second, evidence that people differ stably on the attribute, not only that a manipulation moves the group mean. In this lesson's data, oREV meets the first (and shows where its theory needs repair); the Stroop effect is clear at the group level but barely ranks people, so it doesn't meet the second.\n\n## Problems\n\n1. **The reliability of a difference.** Let $X$ and $Y$ have equal variances, reliabilities $\\rho_X$ and $\\rho_Y$, and correlation $r$. Show that, if their errors are uncorrelated, the reliability of $X - Y$ is $\\frac{(\\rho_X + \\rho_Y)/2 - r}{1 - r}$ ([Cronbach & Furby, 1970](https://doi.org/10.1037/h0029382)). Plug in the Stroop table's retest correlations for congruent and conflicting response time as rough reliabilities, with $r$ from the same data, and compare the result with the effect's retest correlation of 0.17. What does the formula assume that these data might not give it?\n2. **Words out of line.** Using the oREV table, find the words whose difficulty is furthest from what their age of acquisition predicts (the residuals from the line in the plot). Look at the words and their distractors (`chosenword`). Why might each be out of line? Then fit the Rasch model with `mirt` and check whether its item difficulties order the words as the logits do.\n3. **A screener, the causal way.** California now requires reading screening in kindergarten to grade 2 ([Validity as an argument](validity-argument.qmd), problem 5). Pick one skill a screener measures, such as naming letters quickly. What would a Borsboom-style validity study of that subtest look like: which theory of response behaviour, and which prediction that could fail? What would it leave out that a district deciding who gets extra help needs?\n4. **When the network is all you have.** Name a construct for which a network of correlations is all the evidence you can currently get. On Borsboom et al.'s definition, does that make the measure invalid, or the theory of response behaviour thin? What would it take to do better?\n5. **Design a theory.** For a construct you work with, write a theory of response behaviour strong enough to predict an item on which respondents lower on the construct do better, as conflict items do for the balance scale. What data would test it?\n6. **Challenge (open): what kind of concept is it?** Is Borsboom et al.'s definition a replacement for the argument-based view, a complement to it, or a concept for a different grain size of instrument? Make the best case you can for the reading you find weakest, stating what it assumes. This is open; there is no answer key.\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n**Stuck, or curious about something this lesson doesn't cover?** [Ask Claude about this lesson](https://claude.ai/new?q=I%27m%20working%20through%20a%20lesson%20called%20%22Validity%20as%20causation%3A%20Borsboom%27s%20view%22%20in%20an%20open%20psychometrics%20course%20built%20on%20the%20Item%20Response%20Warehouse%20%28IRW%29.%20It%20covers%20Borsboom%2C%20Mellenbergh%20and%20van%20Heerden%27s%20%282004%29%20causal%20definition%20of%20validity%20%28the%20attribute%20exists%20and%20causally%20produces%20variation%20in%20the%20responses%29%2C%20how%20it%20differs%20from%20the%20argument-based%20view%20and%20from%20Cronbach%20and%20Meehl%27s%20nomological%20network%2C%20theories%20of%20response%20behaviour%20with%20Siegler%27s%20balance-scale%20rules%20and%20the%20conflict%20items%20on%20which%20children%20using%20an%20earlier%20rule%20do%20better%2C%20between-%20versus%20within-person%20readings%20of%20a%20latent%20variable%20and%20the%20reliability%20of%20experimental%20effects%2C%20and%20three%20readings%20of%20how%20the%20causal%20and%20argument-based%20views%20relate%2C%20with%20a%20German%20receptive%20vocabulary%20task%20%28age%20of%20acquisition%20predicting%20difficulty%29%20and%20a%20Stroop%20task%20given%20twice%20as%20examples.%20Please%20act%20as%20a%20patient%20tutor%3A%20answer%20my%20questions%2C%20check%20my%20reasoning%2C%20and%20prefer%20small%20worked%20examples%20in%20R.%20If%20data%20would%20help%2C%20IRW%20tables%20are%20described%20at%20https%3A%2F%2Fitemresponsewarehouse.org%2Fllms.txt.%20My%20first%20question%20is%3A%20){target=\"_blank\" .btn .btn-outline-primary .btn-sm} opens a new conversation that already knows what the lesson is about; add your question at the end. Claude shows a caution notice on any prompt that arrives through a link; that's expected.\n:::\n\n## Going further\n\n- Borsboom, D., Mellenbergh, G. J., & van Heerden, J. (2004). The concept of validity. *Psychological Review*, 111(4), 1061–1071. <https://doi.org/10.1037/0033-295X.111.4.1061>. The causal definition, the argument against defining validity by a nomological network, and the balance scale as the model of a theory of response behaviour.\n- Borsboom, D., Mellenbergh, G. J., & van Heerden, J. (2003). The theoretical status of latent variables. *Psychological Review*, 110(2), 203–219. <https://doi.org/10.1037/0033-295X.110.2.203>. Realism about latent variables, and the difference between between-subjects and within-subjects readings.\n- Markus, K. A., & Borsboom, D. (2013). *Frontiers of test validity theory: Measurement, causation, and meaning*. Routledge. <https://doi.org/10.4324/9780203501207>. The causal view at book length, set beside other accounts of validity.\n- Whitely, S. E. (1983). Construct validity: Construct representation versus nomothetic span. *Psychological Bulletin*, 93(1), 179–197. <https://doi.org/10.1037/0033-2909.93.1.179>. The distinction between the processes behind a response and a score's relations with other measures (the author now publishes as Embretson).\n- Siegler, R. S. (1976). Three aspects of cognitive development. *Cognitive Psychology*, 8(4), 481–520. <https://doi.org/10.1016/0010-0285(76)90016-5>. The balance-scale rules and the rule assessment method.\n- Jansen, B. R. J., & van der Maas, H. L. J. (1997). Statistical test of the rule assessment methodology by latent class analysis. *Developmental Review*, 17(3), 321–357. <https://doi.org/10.1006/drev.1997.0437>. The balance-scale rules tested as latent classes.\n- Jansen, B. R. J., & van der Maas, H. L. J. (2002). The development of children's rule use on the balance scale task. *Journal of Experimental Child Psychology*, 81(4), 383–416. <https://doi.org/10.1006/jecp.2002.2664>. Rule use in 805 respondents aged 5 to 19, including inconsistent use.\n- Hedge, C., Powell, G., & Sumner, P. (2018). The reliability paradox: Why robust cognitive tasks do not produce reliable individual differences. *Behavior Research Methods*, 50(3), 1166–1186. <https://doi.org/10.3758/s13428-017-0935-1>. Why tasks with robust effects can rank people poorly; see also the IRW vignette on [the reliability paradox](https://itemresponsewarehouse.org/vignettes/hf_reliability_paradox.html).\n- Cronbach, L. J., & Furby, L. (1970). How we should measure \"change\": Or should we? *Psychological Bulletin*, 74(1), 68–80. <https://doi.org/10.1037/h0029382>. The reliability of difference scores (problem 1).\n- Michell, J. (1997). Quantitative science and the definition of measurement in psychology. *British Journal of Psychology*, 88(3), 355–383. <https://doi.org/10.1111/j.2044-8295.1997.tb02641.x>. The realist view of measurement that the causal definition shares.\n\n## Data sources\n\nData from the [Item Response Warehouse](https://itemresponsewarehouse.org) (each table name links to its IRW page); references from IRW biblio.\n\n- [`vocab_assessment_3_to_8_year_old_children`](https://itemresponsewarehouse.org/tables/vocab_assessment_3_to_8_year_old_children/): Bohn, M., Prein, J. C., Delikaya, B., Haun, D. B. M., & Gagarina, N. (2022, August 24). oREV: an Item Response Theory based open receptive vocabulary task for 3 to 8-year-old children. <https://doi.org/10.31234/osf.io/4z86w>. Licence: CC BY 4.0.\n- [`robison_2026_retesting_stroop`](https://itemresponsewarehouse.org/tables/robison_2026_retesting_stroop/): Robison, M. K., Campbell, S., Garner, L. D., Sibley, C., & Coyne, J. (2026). A comprehensive psychometrics of cognitive ability measures: Reliability, practice effects, and the stability of latent factor structures across retesting. Behavior Research Methods, 58(2), Article 56. <https://doi.org/10.3758/s13428-025-02897-8>. Licence: CC BY 4.0.\n\n## For instructors\n\n- **Source:** EDUC 252 class 4 (slides c4, \"Back to validity\" through \"What I would worry about\", slides 2–15). The two real-data analyses and the between/within simulation are new.\n- **Timing:** about 45 minutes for the core ideas and widgets (the balance-scale widget works well at the board); the real-data section works as a 20-minute lab. Problems 3 and 6 work as small-group discussions, as slides 16–17 use the screener question.\n- **Changed from 252:** slide 6 quotes the whole definition and slides 13–14 a long passage from Borsboom et al. (2004, p. 1068); here the lesson's one quotation is the causal clause of the definition, and the rest is paraphrased. The slide's aside on nomological networks becomes a paraphrase of Borsboom et al.'s argument (pp. 1064–1065). Slide 15's worries become the three readings, left open (Ben, E8a). Kelley (1927) is cited as Borsboom et al. cite it.\n- **Data:** the IRW has no balance-scale responses, so oREV stands in (F4). oREV's `item` column is the trial position, not the word. The distractor codes `dist1`–`dist3` read, from the chosen words, as semantic, phonological and unrelated, a different order from the preprint's description (Bohn et al., 2022, pp. 8–9). The Stroop table records conflict between word and ink only, not whether the two response options conflicted, and averages 57 and 64 trials per respondent at the two sessions against the 43 and 49 Robison et al. report for the 90-second block, so it may include practice trials; they would affect both sessions alike.\n- **Held back:** the reliability paradox in full (in [Trials as items](trials.qmd)); latent class models (in [Latent classes and cognitive diagnosis](cdm.qmd)); item features that explain difficulty, such as age of acquisition as a predictor (in [What is an item?](explanatory-irt.qmd)).\n- **Solutions:** held back in `solutions/validity-causal.qmd` (not published). Problem 6 is open.\n",
    "supporting": [
      "validity-causal_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}